### ISSUE TITLE
6. Vanuit zaak een gerelateerde zaak starten

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1000]
***Als*** 
Behandelaar en/of postmedewerker

***Wil ik*** 
Vanuit een zaak een gerelateerde zaak starten. Hiermee wordt de relatie tussen de 2 zaken: gerelateerde zaak

***Zodat*** 
Er 1 of meerdere gerelateerde zaken aangemaakt kunnen worden vanuit een zaak, waar een andere proces uitgevoerd kan worden. De gerelateerde zaak is dan van evt. een ander zaaktype, met (evt.) andere behandelaar. Beide zaken hebben eigen afhandeling die niet van elkaar afhankelijk is.
De relatie tussen 2 zaken, gerelateerde zaak, ook bij lopende en afgehandelde zaken kunnen leggen.
***

### Acceptance criteria:
Vanuit een Zaak op makkelijke manier een gerelateerde zaak kunnen starten.
Relatie (gerelateerde zaak) wordt automatisch gelegd.
Vanuit zaak moet je eenvoudig naar de gerelateerde zaak moeten kunnen navigeren.
Documenten van de gerelateerde zaak zijn te zien in beide zaken, evt. met optie tonen documenten gerelateerde zaak.
Vernietiging: Geen onderlinge afhankelijkheid tussen de gerelateerde zaken.

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Gerelateerde zaak kunnen aanmaken vanuit een zaak en rekening houden met de acceptatie criteria.

***Belangrijkste functionaliteiten:***
- 
-
Zie ook User Storie 8.2.14 Taak-Starten nieuwe zaak (#488)

**Comment by robertverboom** [comment]
Oppakken als er concrete stories beschikbaar zijn

**Comment by robertverboom** [comment]
ivm duplicate sluit ik dit issue
