### ISSUE TITLE
BUG: Bij verwijderen medewerker zijn de zaken die aan deze medewerker zijn toegewezen niet meer te openen

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#1004]
***Steps to reproduce:***

1. Verwijder een medewerker uit het systeem die een zaak op zijn naam heeft staan
2. Open de betreffende zaak

***Expected***
De zaak kan nog worden geopend, echter bij de behandelaar wordt aangegeven dat de medewerker niet meer bestaat

***Actual***
De zaak kan niet meer worden geopend en geeft een foutmelding terug

**Comment by andyverberne** [comment]
Dit had ik al eerder opgelost. Wanneer een medewerker is verwijderd krijg je als behandelaar van zaak of taak de gebruikersnaam van de betreffende gebruiker te zien.

**Comment by robertverboom** [comment]
test ok
