### ISSUE TITLE
ACCEPTATIE BUG: Intake afronden levert Foutpagina op

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1019]
**Gebruikersrol:**
**Device:**
**OS:** 
**Browser:**
**Versie:**

**Issuenummer**
#251

**Beschrijf de bug**
Bij kiezen voor Intake afronden, en tekst ingeven komt na klikken op Ja (Actie "Intake afronden" uitvoeren?) een foutpagina: 500 Algemene foutpagina.
O.a. bij zaak ZAAK-2022-0000000033

**Te reproduceren:**
Zie hierboven

**Verwacht gedrag**
Intake afronden

**Daadwerkelijk gedrag**
Foutpagina

**Screenshots**

**Foutmelding/Log tekst**
Foutpagina
De server heeft code 500 geretourneerd

**Aanvullende informatie**
NVT

**Comment by VictorTielenius** [comment]
![Foutpagina Intake afronden.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/032d8fe5-57d5-43af-b14e-509a834724d8)

**Comment by RoyBuis** [comment]
Duplicaat
