### ISSUE TITLE
ACCEPTATIE BUG: Toevoegen van Persoon pas bij Historie na verversen pagina. 

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1020]
**Gebruikersrol:**
Behandelaar
**Device:**
Laptop
**OS:** 
**Browser:**
Edge
**Versie:**

**Issuenummer**
#251 + #252

**Beschrijf de bug**
Toevoegen van Persoon pas bij Historie na verversen pagina. Ook alleen een nummer zichtbaar in Historie.
Bij Persoon is dit het BSN.
Bij Bedrijf is dit Vestigingsnummer bij Historie, "Oude waarde	Nieuwe waarde".

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1. Persoon toevoegen aan reeds aangemaakte zaak.
2.
3.
4.

**Verwacht gedrag**
Zoals bij Verwijderen persoon bij een zaak wat direct in Historie zichtbaar is, ook bij Toevoegen persoon /  bedrijf

**Daadwerkelijk gedrag**
_Een duidelijke en beknope beschrijving van wat er daadwerkelijk gebeurde_

**Screenshots**

**Foutmelding/Log tekst**
NVT

**Aanvullende informatie**
NVT

**Comment by VictorTielenius** [comment]
![Toevoegen persoon.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/c0e559f1-79d2-4c16-b69e-a3d367964e86)

**Comment by robertverboom** [comment]
Onderzoeken welke websockets binnenkomen of afgevuurd worden. 
In serverlog kan je zien welke notificaties binnen komen

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Getest (ZAAK-2022-0000000072) en Akkoord
