### ISSUE TITLE
ACCEPTATIE BUG: bij Historie 01-01-3428 als je document toevoegt met 4 cijferig nummer "3428".

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1021]
**Gebruikersrol:**
Behandelaar
**Device:**
Laptop
**OS:** 
**Browser:**
Edge
**Versie:**

**Issuenummer**
tegengekomen tijdens testen #361

**Beschrijf de bug**
Document met bestandsnaam en titel een nummer van 4 cijfers (3428) wordt bij Historie weergegeven als  01-01-3428. (DOCUMENT-2022-0000000044 in zaak ZAAK-2022-0000000030)

**Te reproduceren:**
Zie hierboven

**Verwacht gedrag**
bestandsnaam of titel bij historie te zien. Lijkt er nu een datum van te maken.
Bij de details van het document is de bestandsnaam en titel wel: 3428

**Daadwerkelijk gedrag**
Bij Historie van zaak ZAAK-2022-0000000030
27-05-2022
Victor Tielenius
Document
-
01-01-3428

**Screenshots**

**Foutmelding/Log tekst**
nvt

**Aanvullende informatie**
nvt

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Getest en OK
