### ISSUE TITLE
BUG: Teveel karakters geeft geen update in toelichting 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#103]
***Steps to reproduce:***

1. Ga naar een zaakgegevenspagina
2. Voer extra veel karakters in

***Expected***
een max aantal karakters (1000?) is toegestaan en deze worden getoond

***Actual***
Alle karakters worden tijdens het bewerken getoond, echter niet tijdens het 'tonen' van omschrijving/toelichting.

**Comment by robertverboom** [comment]
Wordt ook niet weggeschreven in Historie

**Comment by bartlukens-atos** [comment]
Max aantal karakters van **Omschrijving**: 80
Max aantal karakters van **Toelichting**: 1000

**Comment by robertverboom** [comment]
test ok
