### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1034]
***Steps to reproduce:***

1. test voor #725: een document kan alleen ontkoppeld worden en dan komt deze in een algemene bak van ontkoppelde documenten. Als recordmanager moet je direct het document kunnen verwijderen uit de zaak
2. 
3. 

***Expected***

***Actual***

**Comment by Snijhuis** [comment]
Dit is een onterechte bug. Werking is nu gebouwd zoals bedoelt voor de zaakbehandelaar. Story voor de werking voor een Recordmanager heb ik aangemaakt, zie #1085
