### ISSUE TITLE
Error500 bij afhandelen intake

### ISSUE THREAD

**Issue by JosDimpact** [NL-AMS-LOCGOV/zaakafhandelcomponent#1038]
Bij het afhandelen van de intake krijgt onze tester een 500 foutmelding en kan dus niet verder met het testen van de goedkeuringstaken. 
Dit doet zich ook voor op de zandbak.

**Comment by VictorTielenius** [comment]
Intake in nu af te handelen, in Zaak ZAAK-2022-0000000049 getest
