### ISSUE TITLE
Navigeren door schermen met het toetsenbord

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1042]
***Als gebruiker*** 

***Wil ik door middel van TAB-toets en andere toetsencombinaties door een scherm kunnen navigeren*** 

***Zodat veel handelingen met het toetsenbord kan afhandelen *** 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd.
