### ISSUE TITLE
Toevoegen aanvrager in werkvoorraad (algemeen en in mijn werkvoorraad)

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#1045]
***Als*** Behandelaar

***Wil ik*** in de werkvoorraad en mijn werkvoorraad ook de aanvrager zien

***Zodat*** ik daarop kan zoeken , filteren en sorteren

***

### Acceptance criteria:
- in de werkvoorraad moet in een kolom de aanvrager zichtbaar zijn. Tevens moet daarom kunnen worden gezocht en gesorteerd

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***

-

**Comment by Snijhuis** [comment]
***Refinement Roy/ Sander***
Bespreken wat de mogelijkheden zijn om aanvrager-gegevens (personen/bedrijven) te tonen in de voorraden van zaken.
Vermoeden dat er dan telkens calls moeten plaatsvinden (HaalCentraal)

**Comment by RoyBuis** [comment]
### Refinement 25-10
Via issue #946 wordt een zoekfunctie voor klanten gemaakt. daarmee kan een persoon of bedrijf gezocht worden en alle zaken van die klant ingezien worden

**Comment by RoyBuis** [comment]
### Backlog refinement RV, SN & RB

De gegevens van de initiator kunnen niet in de werklijsten getoond worden omdat deze altijd zouden moeten worden opgehaald bij het openen van een werklijst. Indexeren is hier geen optie.

Zie ook vorig comment, er wordt gewerkt aan een uitgebreidere zoekfunctie voor personen en bedrijven met daarbij ook een overzicht van de zaken die bij die persoon/bedrijf horen.

Dit issue wordt om bovenstaande redenen gesloten

**Comment by HilbrandHurtak** [comment]
Tijdens de sprint van 22 November is het zoeken op personen/bedrijven getoond. Deze functionaliteit moet onder #946  worden getest. Lijkt in eerste instantie voldoende om ook te voorzien inde gevraagde functionaliteit in #1045

**Comment by HilbrandHurtak** [comment]
Getest en zoeken op persoon/Zaken is mogelijk
