### ISSUE TITLE
7.3.6 Documenten in een zaak ver- ontgrendelen door Gebruiker 

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#1054]
Als	: Gebruiker* 

Wil ik	: Een door mij in een zaak aangemaakt (concept-) document voor bewerking door anderen kunnen vergrendelen en ontgrendelen

Zodat 	: niemand anders dan mijzelf dit document verder kan bewerken totdat ik dit zelf weer ontgrendel 

_*Elke bij de zaak betrokken gebruiker kan documenten in de zaak aanmaken en toevoegen.  Dit hoeft dus perse niet de zaakbehandelaar te zijn._ 

Acceptance criteria:
-Gebruiker kan conceptdocument vergrendelen voor bewerking door anderen. 
-Gebruiker kan een door hemzelf vergrendeld conceptdocument zelf wel verder bewerken. 
-Alleen gebruiker kan een door hem vergrendeld conceptdocument weer voor bewerking (door anderen) ontgrendelen. 

Relatie met User Story "7.3.7 Documenten in een zaak ontgrendelen door Recordmanager"
***
### Prioriteit
- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een document dat niet de status 'Definitief' heeft kan worden vergrendeld. Andere gebruikers die de 'behandelaar' rol hebben kunnen het document dan niet bewerken of andere acties op het document uitvoeren. Een vergrendeld document is te herkennen aan de gekleurde indicatie met slot icoon.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in de documentgegevenspagina met de actie [Vergrendelen] het document vergrendelen. Op het document wordt hierna een indicatie 'Vergrendeld' geplaatst.
- Gebruiker die het document vergrendeld heeft kan met de actie [Ontgrendelen] het document van het slot af halen
- Gebruiker kan door met de muis over de indicatie te zweven zien door welke gebruiker het document vergrendeld is

**Comment by RoyBuis** [comment]
### Refinement 7-6
**Te realiseren**

Functioneel/UI

- Doc kan vergrendeld worden met de actie in rechter menu 'Vergrendelen'
- Na het vergrendelen wordt een chip getoond op de documentkopregel met de naam 'Is vergrendeld'
- Bij mouse-over op de chip wordt de gebruiker die de vergrendeling gedaan heeft getoond
- Als een document gelocked is dan is de actie Nieuwe versie niet beschikbaar
- Doc kan ontgrendeld worden met de actie 'Ontgrendelen', deze is alleen beschikbaar als het doc vergrendeld is en alleen door de gebruiker die heeft vergrendeld

Technisch

- Lock opslaan in database samen met uuid enkelvoudig infoobject en user id
- Bestaande map vervangen door database
- Bij wijzigen document eerst controleren of deze al gelocked is en door wie

**Comment by VictorTielenius** [comment]
Zie ook #1055.

Getest en akkoord.
