### ISSUE TITLE
BUG:  Na annuleren van Document toevoegen panel blijven ingevulde waarden bewaard

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#1069]
***Steps to reproduce:***

1. Open een zaak
2. klik button _Document toevoegen_
3. Vul het _Titel_ veld
4. klik button _Annuleren_
5. klik button _Document toevoegen_

***Expected***
Het _Titel_ veld is leeg

***Actual***
Het _Titel_ veld heeft de waard van de vorige keer

**Comment by andyverberne** [comment]
Dit gedrag is opgelost in het _Document maken_ panel

**Comment by marcoatos** [comment]
In overleg met Andy zo opgelost dat het document toevoegen scherm leeggemaakt wordt bij klikken op de annuleer knop, maar niet bij wegklikken uit het sidepanel. Zodat je op die manier wel even in de zaak kan kijken of perongeluk er langs kunt klikken zonder dat je je ingevulde waarden kwijt bent. Hetzelfde is ook nu zo bij documenten creeeren.

**Comment by robertverboom** [comment]
test ok
