### ISSUE TITLE
6B.1.2 Signalering op zaken voor groep

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#109]
***Als*** Zaakbehandelaar of werkverdeler

***Wil ik*** erop geattendeerd worden dat er een nieuwe zaak is toegekend aan de groep waar ik bij hoor

***Zodat*** ik snel inzicht krijg in wijzigingen die niet door mijzelf zijn aangebracht, bijvoorbeeld nieuwe zaak op mijn groep, en weet dat ik actie moet ondernemen op die zaak

**Acceptance criteria:**

- Signalering moet door behandelaar zelf aan/uit kunnen worden gezet
- Signalering moet op basis van een communicatievoorkeur kunnen worden ingesteld
- Signalering moet ook zichtbaar zijn zonder gebruik te maken van het systeem (notificatie buiten systeem om)

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De groepsignalering kan worden verstuurd wanneer een zaak niet op naam van een behandelaar maar alleen op naam van een groep komt te staan. Als er een trigger voor een signalering die niet voor een gebruiker is bestemd komt dan wordt gekeken of de groepsignalering is ingeschakeld in de Beheer-instellingen van de ZAC. Als dit het geval is dan wordt het ingestelde e-mailadres gebruikt om de signaleringsmail naar toe te sturen. Het e-mailadres van de groep is nu door een system integrator in te stellen in Web2LDAP.

***Belangrijkste functionaliteiten:***
- De signalering wordt per e-mail verstuurd naar het e-mailadres dat bij de groep is ingesteld.
- Gebruiker kan het versturen van de e-mail in- en uitschakelen door in de Beheer-instellingen > menukeuze Groepsignalering-instellingen de zaaksignalering 'Er is een zaak op de groep gezet' aan te passen.

**Comment by RoyBuis** [comment]
Refinement 9 december:
Oplossing voor nieuwe zaak op groep:
- Dashboard gebruiken voor overzicht signaleringen
- Knop dashboard toont een badge als er een nieuwe signalering is, badge verwdijnt weer wanneer alle signaleringen verdwenen zijn
- Als een zaak geopend wordt, vanuit dashboard of op andere wijze, dan verdwijnt de signalering

**Comment by RoyBuis** [comment]
Uren schatten met het hele team tijdens planning of andere refinement sessie

**Comment by RoyBuis** [comment]
Refinement 28-3:

- Dashboardcard is niet mogelijk omdat het niet kan om vanuit Open zaak te filteren op 'behandelaar=leeg'
- Mogelijkheden later bekijken via de stories over zoekfunctionaliteit

**Comment by robertverboom** [comment]
### Refinement 21-07:
- LDAP email instellen op groep. Voorkeur dat deze vanuit keycloack wordt meegegeven als attribute
- Web2LDAP gebruiken om te controleren of de synchronisatie werkt. Zo niet; dan emailadres via web2LDAP toevoegen
- Nieuw beheerscherm: Signaleringen
- Eerst groep kiezen en dan: 
- Signaleringen per groep instellen: Er is een zaak op mijn groep gezet (zelfde signalering als: Er is een zaak op mijn naam gezet)
- Signalering wordt getriggerd als groep gewijzigd wordt en 'behandelaar=leeg'
- Alleen mailsignalering realiseren

**Comment by robertverboom** [comment]
Test ok, moet alleen synchronisatie met keycloack nog realiseren #1454

**Comment by robertverboom** [comment]
@HilbrandHurtak Dit wordt ingericht in Keycloack, waar wij de groepen en gebruikers beheren. Een groep kan een mail adres toegekend krijgen en middels de beheerinstellingen in de ZAC kan deze signalering verstuurd worden. 
Ik kan tijdelijk een bekend mailadres instellen als 'groepsmail' zodat je dit voor jezelf kan testen.

**Comment by HilbrandHurtak** [comment]
@robertverboom Ik zal dit even aan jos voorleggen
@JosDimpact kun jij aangeven welk emailadres we kunnen gebruiken om dit te testen? Het moet dan wel een emailadres zijn waar de overige testers ook bij kunnen.

**Comment by JosDimpact** [comment]
@HilbrandHurtak, moet dat wel een mailbox zijn die voor de gehele groep toegankelijk is? Mag dat niet jouw adres gewoon zijn, zolang als het nodig is voor deze test, waarna Robert die instelling weer ongedaan kan maken?

**Comment by HilbrandHurtak** [comment]
@robertverboom . Wil jij mijn emailadres even aan de groep evenementen koppelen zodat ik kan testen. Na de test kan dit dan weer ongedaan worden gemaakt

**Comment by robertverboom** [comment]
@HilbrandHurtak Op de Accept omgeving is groep A gekoppeld aan jouw email adres. Op de Zandbak omgeving is groep Evenementen gekoppeld aan jouw mail adres. Bij de beheerinstellingen kan je deze functie aan of uit zetten. Let op: de zaak mag geen behandelaar hebben, anders gaat de signalering naar de behandelaar ipv toegewezen groep.

**Comment by HilbrandHurtak** [comment]
Bij groepsignalering Zaak signalering aangezet voor Evenementen. Zaak evenementen aangemaakt en toegewezen aan groep. Tijdelijk mijn mailaccount laten koppelen
Na het aanmaken van de mail kwam er netjes een mail.
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/94eb698d-699f-4faf-b4ab-87f355e51b17)

Test ok
@robertverboom wil je mijn e-mail weer gaan ontkoppelen bij deze groep
