### ISSUE TITLE
Zaakacties niet tonen wanneer de zaak is afgesloten

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1091]
***Als*** Zaakbehandelaar

***Wil ik*** dat de zaakacties in het linkermenu verdwijnen/verborgen zijn als een zaak is afgesloten

***Zodat*** ik geen aanpassingen wijzigingen op een afgesloten zaak kan doorvoeren.

***

### Acceptance criteria:
- Zaakacties verbergen indien zaak is afgesloten
- Zaak moet te heropenen zijn door Recordmanager #1086
- Zaakacties moeten daarna weer beschikbaar zijn
- Zie screenshots met aanduidingen van de acties (geel gearceerd)

**Zaken API zegt het volgende**
Als een Zaak een eindstatus heeft dan is de zaak afgesloten en mogen gegevens van de zaak niet meer aangepast worden (behalve om redenen van correctie). Dit MOET beveiligd worden met de scope zds.scopes.zaken.geforceerd-bijwerken. “Gegevens van de zaak” omvat hier ook de gerelateerde gegevens zoals klantcontacten, resultaat, rollen, statussen, zaakinformatieobjecten, zaakobjecten, zaakbesluiten en zaakeigenschappen.

RB:
Als ik dit zo lees dan zou ik ook zeggen weghalen de acties die er nu staan. Er als er dan nog eens een terug moet dan zoeken we dat wel weer uit.

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Met deze aanpassing zijn de acties, zoals Document toevoegen, die bij een zaak beschikbaar zijn weggehaald als de zaak beëindigd is. Om weer over de acties te beschikken kan een zaak kan worden heropend.

***Belangrijkste functionaliteiten:***
- een beëindigde zaak kan niet gewijzigd worden

**Comment by Snijhuis** [comment]
![image.png](https://images.zenhubusercontent.com/61a7728f4b7bcc716765fdd1/f833979a-df89-4cc4-b30d-9ac02ca4de53)

**Comment by Snijhuis** [comment]
[Uploading... image.png]

**Comment by robertverboom** [comment]
## Refinement 09-06:

- Alle functionaliteit de actie meegeven; isWijzigbaar. 
- Aparte actie: isHeropenbaar (zie 2e bullet)

**Comment by VictorTielenius** [comment]
Zaakacties verbergen indien zaak is afgesloten
Zaak moet te heropenen zijn door Recordmanager #1086
Zaakacties moeten daarna weer beschikbaar zijn

ZAAK-2022-0000000073
Na Afhandelen zaak zijn de zaakacties niet meer aanwezig. Heropenen is nu wel aanwezig.
Document: ook hier zijn de acties (verplaatsten + ontkoppelen) niet meer beschikbaar.
Na Heropenen: 
Heropenen zaak geeft foutmelding(code 500)

**Comment by VictorTielenius** [comment]
WG Refinement bekijkt of Notitie bewerken / toevoegen bij afgehandelde zaak wenselijk / logisch is en of een notitie zaakdata is wordt voorgelegd aan WG Informatiebeheer

**Comment by Snijhuis** [comment]
Update: Notities op zaken zijn geen zaakdata. In principe mogen notities dus nog aangepast worden/ toegevoegd worden. Denk bijvoorbeeld aan een instructie voor een medewerker/collega. Notities worden ook niet bij de zaak opgeslagen in OpenZaak.

@VictorTielenius Volgens mij kan dit issue dan gesloten worden?

**Comment by VictorTielenius** [comment]
Geen fout bij Heropenen (nog eens getest) en antwoord mbt Notitie. OK
