### ISSUE TITLE
6B.1.x Signaleringen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#110]
Geattendeerd willen worden op wijzigingen

**Comment by GertrudeKampherbeek** [comment]
- 6B.1.1 Signalering op zaken voor zaakbehandelaar buiten ZAC om #129 
- 6B.1.2 Signalering op zaken voor groep  #109 
- 6B.1.3 Signaleringen gebruikers/groepen kunnen instellen door beheerder #114 
- 6B.1.4 Signaleringen gebruiker kunnen instellen door gebruiker #121

**Comment by RoyBuis** [comment]
### Refinement KM, RB en RV
Stories zijn gerealiseerd op één na. Deze wordt als los staande verder besproken. Epic wordt gesloten.
