### ISSUE TITLE
Zaakhistorie vereist refresh bij koppelen bedrijf

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1108]
Dit issue is gekoppeld aan #294

Na het koppelen van een bedrijf aan mijn zaak wordt de zaakhistorie niet direct bijgewerkt. Na een refresh is de zaakhistorie wel bijgewerkt. Gewenst: de zaakhistorie direct aanpassen.

**Comment by VictorTielenius** [comment]
Bij koppelen bedrijf (of persoon) zaakhistorie direct ververst
