### ISSUE TITLE
Afsluiten van Locatiescherm is onduidelijk

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1109]
Het afsluiten van een opgevraagd Loctiescherm is niet duidelijk (#304).

![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/2916adfb-ec89-4ab5-8820-c6b3a6184e39)

Als gebruiker verwacht ik een X om op te kunnen klikken zodat het scherm wordt afgesloten. Na wat geklikt te hebben is duidelijk dat een klik in het donkere deel van het scherm zorgt voor het afsluiten van het scherm. Prima, maar een extra X zou mooi zijn.

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd via #2474
