### ISSUE TITLE
Filteren en sortering op Taken-werkvoorraad

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1112]
***Als*** Zaakbehandelaar

***Wil ik*** net als bij de zaken-werkvoorraad ook op taken-werkvoorraad willen sorteren en filteren op de kolommen

***Zodat*** ik snel een overzicht krijg welke taken er zijn en deze kan prioriteren

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
Filter, zoek en sorteer opties zijn toegepast op de taken-werkvoorraad en mijn taken werklijsten

Belangrijkste functionaliteiten:
- SOLr engine is toegepast op taken werkvoorraden

**Comment by robertverboom** [comment]
## 13-06 Refinement:
- taken indexeren in SOLr
- Bij wijzigingen van een taak in de werkvoorraad direct herindexeren van taak
- Bij wijzigingen van een taak 'in het algemeen' taak markeren dat deze geindexeerd moet worden. Dit kan vanuit de Flowable service
- Eerst taken, dan zaken in de cronjob indexeren
- Behandelaar toevoegen als kolom

**Comment by VictorTielenius** [comment]
taken-werkvoorraad willen sorteren en filteren op de kolommen

Nu mogelijk om diverse kollommen te filteren / sorteren en in sommige kolommen te zoeken. 
Ook Behandelaar (van de Taak) aanwezig als kolom
