### ISSUE TITLE
Filteren en sortering op Ontkoppelde documenten 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1114]
***Als*** Zaakbehandelaar

***Wil ik*** net als bij de zaken-werkvoorraad ook op ontkoppelde documenten willen sorteren en filteren op de kolommen

***Zodat*** ik snel documenten kan opzoeken in de tabel

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De werklijst 'Ontkoppelde documenten' is verrijkt met sorteer, filter- en zoekopties. De beschikbare opties zijn afhankelijk van het type data dat de kolom bevat. Zo kan er bijvoorbeeld bij data dat uit een waardelijst komt, zoals 'Behandelaar' op gesorteerd en gefilterd worden. 

***Belangrijkste functionaliteiten:***
- Gebruiker kan met het pijl icoon in de kolomkop het overzicht sorteren op basis van de gegevens in een kolom. Door nog een keer op de pijl te klikken wordt de andere kant op gesorteerd.
- Gebruiker kan filters op meerdere kolommen toepassen. Door te klikken op het vergrootglas in de kolomkop kan gefilterd worden op trefwoorden, met de keuzelijst kan gefilterd worden op één keuze en door te klikken op de kalender kan een datumbereik worden ingevuld.
- Gebruiker kan met het trechter icoon alle toegepaste filters wissen
- Gebruiker kan met het ster icoon de toegepaste sortering en filters als zoekopdracht opslaan. Door in een ongefilterd overzicht op het trechter icoon te klikken kan een bewaarde zoekopdracht worden geopend en kunnen zoekopdrachten met een klik op de prullenbak worden gewist.

**Comment by VictorTielenius** [comment]
Filtering van Ontkoppelde documenten op Creatie datum geeft niet altijd juiste resultaat

**Comment by KarinMasselink** [comment]
@VictorTielenius wil je deze als aparte bug(s) inschieten en koppelen? En deze naar de juiste pipeline verslepen.

**Comment by KarinMasselink** [comment]
@VictorTielenius  wil je deze ook hertesten. De bug is opgelost.

**Comment by VictorTielenius** [comment]
#2410 getest en akkoord.
