### ISSUE TITLE
Filteren en sortering op Inbox documenten

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1115]
***Als*** Zaakbehandelaar

***Wil ik*** net als bij de zaken-werkvoorraad ook op inbox documenten willen sorteren en filteren op de kolommen

***Zodat*** ik snel documenten kan opzoeken in de tabel

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
Filter, zoek en sorteer opties zijn toegepast op de ontkoppelde- en inboxdocumenten

**Comment by robertverboom** [comment]
## 13-06 Refinement: 
- Eerst lijstje testen met 1000 documenten
- Eerst controleren hoe het gaat met serverside

**Comment by VictorTielenius** [comment]
Geen Inbox documenten aanwezig. Kunnen hier er een aantal documenten neergezet worden?

Bij Ontkoppelde documenten nu wel fiteren / sorteren en soms zoeken mogelijk

**Comment by VictorTielenius** [comment]
Bij op pijl klikken (sorteren) van kolom "1identificatie" Foutpagina - De server heeft code 500 geretourneerd - Algemene Fout
Naam heeft een 1 ervoor.

**Comment by JosDimpact** [comment]
@Sevdiya, zou je mee willen kijken? De huidige oplevering lijkt te beperkt te zijn: zou jij aanvullingen willen doen?

**Comment by VictorTielenius** [comment]
Beschrijving / Documenttype (standaard aan op werklijst "Inbox  - documenten")
Bestandsnaam / Registratiedatum / Status / Vertrouwelijkheidaanduiding (mogelijkheid om toe te voegen aan de werklijst "Inbox  - documenten")

Auteur / Taal (hier twijfel ik of deze toe te voegen moeten zijn als kolom)

**Comment by RoyBuis** [comment]
@VictorTielenius 
Jouw comment van 6 dagen geleden lijkt op een nieuwe user story. Klopt dit en moet deze nog aangemaakt worden? Als het lukt om er voor morgenochtend 10:00 uur naar te kijken dan kan deze wellicht nog mee in de sprint?

**Comment by robertverboom** [comment]
Graag originele issue hertesten. Indien @VictorTielenius zijn punten toegevoegd moeten worden, graag in een nieuwe story meenemen

**Comment by VictorTielenius** [comment]
Aanvullende wensen werklijst "Inbox - documenten" via: #2231

**Comment by VictorTielenius** [comment]
Hertest: 
De 3 aanwezige kolommen kun je sorteren (alle 3) en in zoeken (Identificatie + Titel)
Datum-range bij Creatiedatum aanwezig
Akkoord
