### ISSUE TITLE
BUG: Bij starten taak scherm wordt de ingevulde data niet opgeslagen

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#112]
***Steps to reproduce:***

1. Start vanuit een zaak een nieuwe taak
2. Vul het "Start taak" formulier in
3. Druk op "Starten"

***Expected***
Het afhandelen taak formulier wordt getoond met informatie uit het "start taak" formulier

***Actual***
De data welke is ingevuld in het "start taak" formulier wordt niet getoond omdat deze niet wordt opgeslagen.

**Comment by robertverboom** [comment]
test ok
