### ISSUE TITLE
Foutmelding bij invoeren KvKnr

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1126]
De foutmelding wordt gegeven bij het invoeren van een KvKnr (#294) als een bedrijf gekoppeld wordt aan de zaak.

Bij het invoeren van een KvKnr wordt direct na het invoeren van 1 character een foutmelding gegeven. De melding verdwijnt pas als het KvKnr volledig (juist) is ingevoerd. Dit komt ook o.a. voor bij:
- invoeren van het vestigingsnr
- invoeren van het verstingsadres (postcode)

De foutmelding werkt verwarrend voor de gebruiker. De gebruiker denkt een fout te maken op het moment van invoeren. De verwarring zou niet optreden als de foutmelding pas gegeven wordt op het moment dat de 'focus' verandert (druk op de TAB-knop, met de muis naar een ander invoerveld of een klik met de muis op een button).

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd.
