### ISSUE TITLE
Document bewerken (Webdav): gebruikersnaam ook wegschrijven in historie na opslaan nieuwe versie

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1144]
***Als*** Zaakbehandelaar

***Wil ik*** dat bij de wijziging van een document via webdav (Office documenten) de gebruikersnaam ook wordt opgeslagen bij de historie als er een nieuwe versie is ontstaan

***Zodat*** ik altijd kan terugzien wie welke versie van een document heeft gemaakt

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by Snijhuis** [comment]
Op zandbak werkt het wel: ![image.png](https://images.zenhubusercontent.com/61a7728f4b7bcc716765fdd1/3e4f3fec-e79e-4765-a3f7-a8c41ec9cc3a)

**Comment by andyverberne** [comment]
werkt ook op develop
