### ISSUE TITLE
Geautomatiseerd deployen van SOLr schema

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1145]
Schema moet worden vervangen op de NFS server
SOLr moet herstart worden. 
1. Vergelijken dat het schema is aangepast ( 1 file: schema.xml)
2. Indien stap 1 waar is, dan SOLr stoppen
3. managed-schema.xml weggooien en schema.xml vervangen
4. SOLr starten, of reload commando geven via curl

**Comment by andyverberne** [comment]
Dit is toch niet de juiste aanpak. De SOLR admin API moet gebruikt worden om het schema te updaten

**Comment by andyverberne** [comment]
We doen deze toch voorlopig even niet

**Comment by andyverberne** [comment]
https://stackoverflow.com/questions/56063470/updating-solr-schema-using-version-numbers
