### ISSUE TITLE
Nadenken over de zaakafhandelparameters

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1149]
Rekening houden met wijzigen zaaktype
Rekening houden met wijzigen CMMN

**Comment by RoyBuis** [comment]
### Refinement 23-6

**Starten van een nieuwe zaak**
1 het zaaktype wordt bepaald obv Identificatie (let op, bij het aanpassen van omschrijving dan hebben oudere zaken een andere naam)
2 filteren op begin- en einddatum geldigheid
3 zaaktype met laatste versiedatum wordt gebruikt
4 zaaktype moet gepubliceerd zijn

**Comment by RoyBuis** [comment]
**Zaakafhandelparameters**
1 Bij een event 'nieuw zaaktype' of 'gewijzigd zaaktype' controleren of het zaaktype gepubliceerd is en dan de bestaande laatste versie van 
 de zaakafhandelparameters kopiëren
2 de gekopieerde zaakafhandelparameters valideren en niet-valide settings eruit halen en dan de zaakafhandelparameters markeren als valide/niet-valide

**Comment by RoyBuis** [comment]
### Refinement 27-6
**Updaten van CMMN-model**

1 Koppeling taakformulier en taak komt vast te liggen in de code. Dus keuze verwijderen uit database en scherm.
2 Indien voor een human task of een event listener geen zaakafhandelparameters aanwezig zijn dan worden lege waarden gebruikt

**Comment by robertverboom** [comment]
Epic #1205 aangemaakt
