### ISSUE TITLE
Toelichtingsveld bij goedkeuring is niet optioneel

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1157]

**Comment by CommonGroundGroningen** [comment]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/005f9a56-8ff0-46ff-a0e3-b70e31002251)

**Comment by CommonGroundGroningen** [comment]
Ok. Dan moet Acceptance criteria nr 4 aangepast worden: Een tekstveld voor het beantwoorden van de goedkeuringsvraag (**optioneel**)

**Comment by Snijhuis** [comment]
Vanwege het tonen van waarden uit taken voor het kunnen bewaken van de voortgang is het veld verplicht gemaakt.
Eventueel kunnen we later kijken of deze toch echt optioneel moet zijn. Dan maken we er een nieuwe story van.

Deze graag accorderen als verder alles werkt.

**Comment by HilbrandHurtak** [comment]
Acceptatiecriteria aangepast naar verplicht ivm toelichting van Sander
