### ISSUE TITLE
Menu-optie 'Afhandelen zaak' wordt niet getoond

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1161]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/5db8ad0b-3603-41da-be03-9ad719d3147d)

**Comment by CommonGroundGroningen** [comment]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/6fbd865a-5416-41dd-a5b7-0701c4e9fb47)

**Comment by CommonGroundGroningen** [comment]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/4f8d9fc5-6a62-4005-a59a-5eb6baf22610)

**Comment by robertverboom** [comment]
Verwarring komt door de titel. Deze story gaat gepaard met handmatig afhandelen, echter wordt er in ZAC gesproken over afbreken en deze wordt wel getoond.

**Comment by Snijhuis** [comment]
Zaken tussentijds afbreken kan. Zaken tussentijds handmatig afhandelen niet.
In principe kun je daar vrij snel komen door eerst de intake af te handelen. 

Indien handmatig afhandelen toch nodig is, dan moet hiervoor een nieuwe story komen met een goede zodat. Die konden wij als WG niet zo bedenken.

**Comment by HilbrandHurtak** [comment]
Dag Sander
Als je al diverse taken hebt laten aanmaken kun je nu alleen de zaak afbreken. Hierbij is dan een reden te kiezen. De bewaartermijn is aan de reden gekoppeld (Bijvoorbeeld Ingetrokken- 12 Maanden)   

Bij Zaak Afronden moeten alle taken afgehandeld zijn(anders krijg je de optie niet). De enige redenen om dan niet te kiezen voor Zaak afbreken zouden de bewaartermijnen zijn. In mijn voorbeeld zou je ook Akkoord kunnen invullen met een permanente bewaartermijn(optie bij Zaak Afronden die misschien niet bij Zaak Afbreken aanwezig is. Als dat het geval is moet je dus alle taken afhandelen. Dit was ook de reden voor deze functionaliteit(automatisch de zaken afronden en de juiste bewaartermijn bepalen). Misschien is dit een reden om het opnieuw te bekijken.

Als de juiste selectielijst-items en bewaartermijnen ook voorkomen bij de functie Zaak afbreken is de wekring zoals die nu is wel goed.

**Comment by HilbrandHurtak** [comment]
De resultaattypes bij Afbreken en Afronden zijn gelijk. Bij afbreken kun je dus alle openstaande taken automatisch laten afronden. Het vertalen van een resultaat naar een omschrijving blijft ongelukkig maar is misschien voor de behandelaar wel duidelijker. Voor nu werkt de functionaliteit om openstaande zaken in 1 keer in te trekken door de zaak af te breken.
