### ISSUE TITLE
Foutpagina na afhandelen zaak

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1162]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/55b595f8-2d65-4b63-8aa2-f142f51bda9f)

**Comment by CommonGroundGroningen** [comment]
Na het afhandelen van een zaak (menu-optie 'Afhandelen zaak', invoeren van 'Resultaat' en 'Toelichting') wordt een foutmelding gegeven. Zaak wordt niet afgehandeld, applicatie blijft hangen.

**Comment by robertverboom** [comment]
Wordt opgelost met #1205

**Comment by robertverboom** [comment]
Opnieuw beoordelen

**Comment by HilbrandHurtak** [comment]
Afhandelen gaat nu goed. Heropenen geeft nog steeds 500 foutmelding. Zie issue niet #1268
