### ISSUE TITLE
Taak aanvullende informatie uitbreiden met mogelijkheid om termijn in te geven waarbij de einddatum van de taak wordt bepaald

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#1165]
***Als*** behandelaar

***Wil ik*** bij het aanmaken van een taak voor aanvullende informatie een termijn aangeven waarbinnen de informatie moet worden aangevuld waarbij de einddatum van de taak gelijk is aan de termijn die ik heb aangegeven. 

***Zodat*** ik kan sturen op de termijn waarop de aanvullende informatie moet zijn ontvangen

***

### Acceptance criteria:
- Het ingeven van een einddatum waarop de aanvullende informatie moet zijn ontvangen. Nu wordt er in de mailtemplate een termijn als tekst aangegeven maar wordt de einddatum van de taak 'Aanvullende informatie" op 1 dag gezet. Dit is niet logisch. 

***
### Prioriteit
- Should haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #175 is het opschorten van de streef- en fatale datum van een zaak vanuit de zaakgegevenspagina opgeleverd. Deze story maakt het mogelijk om ook op te schorten bij het starten van de taak 'Aaanvullende informatie opvragen'. Een zaak mag maar één maal worden opgeschort dus deze optie is aleen beschikbaar als dit nog niet is gebeurd. De behandelaar kan de opschorting doen door de optie te selecteren in het taakstartscherm en de verwachte duur (in kalenderdagen) van de opschorting bepalen door de fatale datum van de taak in te vullen. De werking van de opschorting is identiek aan een opschorting via het zaakgegevensscherm.

***Belangrijkste functionaliteiten:***
- Gebruiker kan bij het starten van een 'Aanvullende informatie opvragen' taak een zaak opschorten
- Gebruiker kan de verwachte duur (in kalenderdagen) van de opschorting bepalen door de fatale datum van de taak in te vullen
- De optie om op te schorten is alleen beschikbaar als de zaak nog niet is opgeschort
- De opschorting wordt als wijziging van de streef- en/of fatale datum vastgelegd in de historie van de zaak. Als toelichting wordt standaard 'Opschorting: Aanvullende informatie opgevraagd' gegeven.

**Comment by HilbrandHurtak** [comment]
@robertverboom . Wordt deze nog opgepakt. Nu kun je wel een datum in de mail opgeven (14 dagen bijvoorbeeld) maar de datum van de taak wordt niet aangepast. Eigenlijk  weet je nu bij de taak niet wanneer de aanvullende info binnen moet zijn (standaard wordt daar nu 7 dagen ingevuld)

**Comment by RoyBuis** [comment]
### Refinement 24-11

**Te realiseren**

- Taakstartscherm van Aanvullende info taak wordt uitgebreid met een datumveld waarin de fatale datum van de taak wordt ingevuld. Standaard waarde voor dit veld is de ingetelde fatale datum van de taak in de zap
- Er komt een checkbox waar de behandelaar kan aangeven of de zaak ook moet worden opgeschort. 
- De opschorten checkbox is alleen zichtbaar als: 
  - de zaak nog niet opgeschort is geweest 
  - opschorten is toegestaan vanuit zaaktype 
  - vanuit rechten is toegestaan
- De zaak wordt opgeschort met de doorlooptijd van de taak
- De reden van opschorten is standaard 'Aanvullende informatie opgevraagd'. Dit vult de behandelaar niet zelf maar wordt automatisch gezet
- In historie vastleggen als 'Opschorting: Aanvullende informatie opgevraagd'

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Zaak aangemaakt:
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/4459d967-d892-41ac-af00-0f5dcd10bf83) 

Taak Aanvullende informatie met termijn van 111 dagen opschorten
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/895b4c57-3948-4588-8d48-8faea6e21062)

Historie
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/61117153-bd40-475a-baa9-9cd0bc972cf0)

2e taak aanvullende informatie(Optie opschorten is niet meer zichtbaar)
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/7ecfaf76-c11a-4c2f-b8ae-e31a969d85b4)
