### ISSUE TITLE
Mail verzonden vanuit GZAC niet meer als .txt aan document laten toevoegen 

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#1166]
***Als*** Behandelaar

***Wil ik*** mijn verzonden mail ook als mail(of pdf)  weer bij de documenten zien en niet als een.txt zonder daarin het e-mailadres

***Zodat*** goed kan zien welke mail (inclusief de opmaak) ik naar wie heb verstuurd 

***

### Acceptance criteria:
- De verstuurde mail inclusief de opmaak bewaren als document bij de zaak
- Het opnemen van het e-mailadres waar de mail naartoe is gestuurd  

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***

_Omschrijving van de op te leveren functionaliteit in deze story_
De mail zoals die nu binnen de huidige e-Suite wordt toegevoegd aan de documenten ziet er veel beter uit dan in de nieuwe common ground omgeving. Daar staat alleen een .txt bestand zonder opmaak en e-mailadres

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd.
