### ISSUE TITLE
De vanuit het ZAC verzonden mail als mail bestand of pdf opslaan ipv als txt bestand

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#1179]
***Als*** behandelaar

***Wil ik*** de vanuit het ZAC verzonden mail als email bestand of als pdf bestand zien en niet in het txt format.

***Zodat*** de opgeslagen mail ook gewoon via een mailprogramma of pdf reader kan worden geopend 

***

### Acceptance criteria:
- Alle gegevens uit het verzonden mailtje moeten als email bestand of pdf worden opgeslagen 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In de huidige eSuite wordt de verzonden mail als PDF opgeslagen. Hierop staan alle gegevens(Verzender, ontvanger enz). In het ZAC component wordt de alleen de inhoud van de mail als txt bestand opgenomen

***Belangrijkste functionaliteiten:***
- 
-

**Comment by HilbrandHurtak** [comment]
Ook bij de nieuwe oplevering(mailtemplates configureerbaar met variabelen) valt wederom op dat de verzonden mail als TXT wordt opgeslagen. Als je meerdere keren aanvullende info gaat opvragen en als bijlage de vorige mail gaat toevoegen krijgt de klant ook een txt bestand. @robertverboom zou je dit ticket nog eens onder de aandacht willen brengen.

![image](https://user-images.githubusercontent.com/96229645/203519928-f6b849a3-f8dd-4664-8a3c-f21655c88af4.png)

![image](https://user-images.githubusercontent.com/96229645/203520114-636732fd-9a7b-4ab2-8638-245ff427bea5.png)

**Comment by robertverboom** [comment]
Wordt meegenomen in #1844 wat een vervolg op huidige US is. Er wordt gekeken naar een PDF converter echter is deze nog niet beschikbaar. De mail bestanden worden nu omgezet naar html bestanden, zodat de styling ook te zien is.

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd.
