### ISSUE TITLE
BUG: Bij taak aanvullende informatie ontbreek de mogelijkheid om een bijlage toe te voegen

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#1180]
***Steps to reproduce:***

1. Start de taak aanvullende informatie
2. Je ziet hier geen mogelijkheid om bijlages mee te sturen
3. 

***Expected***
Het kunnen toevoegen van bijlages zodat deze ook in de mail worden meegestuurd (conform de acceptatie criteria)

***Actual***
Er kunnen nu geen bijlages worden toegevoegd

**Comment by robertverboom** [comment]
### Refinement 11-7:
- Bijlage kunnen toevoegen in elke mailfunctie

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Getest inclusief de mogelijkheid om de mail zelf vorm te geven. Kon bij het aanmaken van de taak direct een bijlage meesturen. Dat werkt dus

**Comment by HilbrandHurtak** [comment]
Ook getest met de variabelen en een SmartDocument document. Het werkt
