### ISSUE TITLE
Relevante documenten zijn niet meer in afgeronde advies of goedkeuringstaken te zien

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#1189]
***Als*** behandelaar

***Wil ik*** bij afgesloten advies en goedkeuringstaken de relevante documenten zien op basis waarvan het advies of de goedkeuring is gegeven

***Zodat*** Ik weet waarop het besluit is gebaseerd 

***

### Acceptance criteria:
- Na afronding van de advies en goedkeuringstaken moet duidelijk zijn welke documenten bij het besluit zijn meegestuurd als relevante documenten. Bij het aanmaken zie je dat wel maar na afronding niet meer

***
### Prioriteit
*Verwijder wat niet van toepassing is:*

Taak tijdens behandeling
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/b6e2dd94-d937-4d1b-bd96-8a813cb4d6b4)

Taak na afronding
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/e69ec94e-d060-4475-8048-addfbd225055)

- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd.
