### ISSUE TITLE
BUG: Niets meer klikbaar bij error op dialog/popup

### ISSUE THREAD

**Issue by marcoatos** [NL-AMS-LOCGOV/zaakafhandelcomponent#1197]
Als er een error plaatsvindt op een dialog of popup dat ga je naar de algemene foutpagina met de dialog/popup nog steeds zichtbaar. Echter is dan niets meer klikbaar, de dialog/popup kan niet gesloten worden en doordat deze openstaat is verder ook niets meer klikbaar waardoor je moet refreshen om verder te gaan. Maar dan ben je ook de stacktrace informatie kwijt in de front-end.

Voorbeeld: 
![image](https://user-images.githubusercontent.com/13099469/175520284-e898d9df-25b9-49d4-91c5-6cc693530a79.png)

**Comment by RoyBuis** [comment]
### Refinement 27-6
Bij het optreden van een error moet de dialog sluiten zodat de stacktrace bekeken kan worden.
Oplossen in generiek component.

**Comment by robertverboom** [comment]
test ok
