### ISSUE TITLE
Zaak update websocket op zaak view een directe update geven?

### ISSUE THREAD

**Issue by marcoatos** [NL-AMS-LOCGOV/zaakafhandelcomponent#1198]
Op dit moment wordt een zaak niet meteen geupdate als iemand iets wijzigt in de zaak, maar komt er een snackbar welke zegt dat er wijzigingen zijn en of je wilt refreshen.

Kan dit naar een directe update zodat ik meteen wijzigingen zie? Bijvoorbeeld gekoppelde zaken en/of documenten.

Zo niet, is er dan een combi mogelijk waarbij je aan kunt geven welke event direct een update mogen doen en welke via een snackbar lopen?

**Comment by RoyBuis** [comment]
### Refinement 27-6
Deze aanpassing geldt voor alle plekken in het ZAC waar een snackbar getoond wordt na een wijziging.
We houden alleen de variant waarbij een snackbar met melding getoond wordt zonder refresh over.
