### ISSUE TITLE
BUG: Behandelaar wordt niet vervangen bij autocomplete

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#120]
***Steps to reproduce:***

1. Zet een zaak op je naam, volgens het bewerk behandelaar component
2. Zet een andere behandelaar op de zaak 
3. zet hem weer terug op je naam
4. Bewerk vervolgens de behandelaar weer

***Expected***
De laatste behandelaar wordt getoond

***Actual***
Vorige behandelaar wordt in het bewerkscherm getoond

**Comment by robertverboom** [comment]
Let op: Bij het vrijgeven van behandelaar krijg je een lege placeholder, maar de behandelaar blijft wel staan. 
Besproken met @bartlukens-atos

**Comment by nl23727** [comment]
Issue succesvol getest op de development omgeving. --> nog openstaand de auto testen hiervoor fixen. Deze gaan uit van een gevuld veld behandelaar na bewerken

**Comment by robertverboom** [comment]
test ok
