### ISSUE TITLE
Tonen van zaaktypen bij starten nieuwe zaak

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1206]
### Refinement 23-6
**Starten van een nieuwe zaak**

Aanname dat de check of zaakafhandelparameters valide zijn al bestaat. Zie US 'Zaakafhandelparameters bij wijzigen zaaktype' #1207

1 het zaaktype wordt bepaald obv omschrijving
2 filteren op begin- en einddatum geldigheid
3 filter: zaaktype moet gepubliceerd zijn
4 filter: zaaktype moet valide zaakafhandelparameters hebben
5 zaaktype met laatste versiedatum wordt gebruikt
6 bij starten zaak vanuit ZAC dan mag een zaaktype maar 1 keer voorkomen in de lijst van zaaktypen. Alleen zaaktypen die gestart kunnen worden mogen in de lijst getoond worden, zie criteria hierboven.

**Comment by andyverberne** [comment]
De lijst van zaaktypen die volgens bovenstaande algoritme bepaald wordt moet als laatste nog een keer door de policyService om hieruit de toegestaane zaaktypen voor de ingelogde gebruiker te bepalen. Daar is al een methode voor.
