### ISSUE TITLE
6B.1.4 Signaleringen gebruiker kunnen instellen door gebruiker

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#121]
Als zaakbehandelaar

Wil ik kunnen instellen dat ik signaleringen ontvang voor mijzelf en voor mijn groep

Zodat ik zelf kan bepalen of ik gesignaleerd wordt

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Onder het profiel icoontje (rechtsboven) kunnen de signalering-instellingen bekeken worden. 
Aan/uit vinken wat de gebruiker wilt. 

Belangrijkste functionaliteit:
- Door deze aan of uit te vinken wordt gelijk de functionaliteit gerealiseerd.

**Comment by RoyBuis** [comment]
Refinement 9 december:

- Voorlopige cards: 'Nieuwe zaken behandelaar' en 'Nieuwe zaken groep'
- Per card op dashboard een toggle waarmee de signalering aan en uit gezet kan worden

**Comment by bartlukens-atos** [comment]
- Tabel nodig; per gebruiker; per signalering welke verschijningsvorm (card) gewenst is
- Servicelaag/objecten
- Scherm in het menu
- Bij het genereren van de signalering moet gekeken worden of deze aangemaakt moet worden

**Comment by RoyBuis** [comment]
Extra punt uit refinement: rekening houden met story #129 waarmee een gebruiker ook een signalering per e-mail kan krijgen. Het moet voor een gebruiker ook in te stellen zijn of hij deze wil ontvangen.

**Comment by hansmarks** [comment]
https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/pull/740

**Comment by hansmarks** [comment]
Het is dus uiteindelijk een scherm geworden wat erg lijkt op het eSuite scherm met directe manipulatie (geen opslaan-knop) en met (toekomst) mogelijkheden voor meer dan twee checkboxen per signaleringtype. De E-Mail checkbox doet op dit moment nog niets, maar daarvoor staat een story op de volgende sprint.

Review commentaar verwerkt. In overleg met Robert de sorteer-mogelijkheid er weer af gehaald omdat het effect op de volgorde op z'n zachts gezegd verrassend zou zijn geweest voor de gebruiker. In plaats daarvan een

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Instellen dat ik signaleringen ontvang voor mijzelf en voor mijn groep:
Voor mijzelf is dit (3 stuks nu) in te stellen. Voor groep?
