### ISSUE TITLE
BUG: Zaak heropenen op Zandbak/Test/Accept

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1212]
***Steps to reproduce:***

1. Rond zaak af
2. Heropen een zaak
3. 

***Expected***
Zaak op de omgevingen kunnen heropend worden 

***Actual***
Krijgt 500 error

**Comment by andyverberne** [comment]
Deze omgevingen missen nog de nieuwe 'Heropend' status
