### ISSUE TITLE
Ontkoppelen van zaken

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1218]
***Als*** Zaakbehandelaar

***Wil ik*** Zaken kunnen ontkoppelen van elkaar

***Zodat*** ik ze aan een andere zaak kan koppelen

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
-

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Het is mogelijk om twee als hoofd- en zaak gekoppelde zaken weer los van elkaar te maken. 

***Belangrijkste functionaliteiten:***
- Gebruiker kan in een zaak via het tabblad ‘Gerelateerde zaken’ op de regel van de zaak die ontkoppeld moet worden op het Zaak ontkoppelen-icoon klikken 
- Het ontkoppelen van zaken als hoofd- en deelzaak wordt als wijziging van hoofdzaak in de historie van de DEELzaak vastgelegd

**Comment by robertverboom** [comment]
## Refinement 30-06:

- Bij opbouwen historie de hoofdzaak en deelzaak wijzigingen ook tonen. De URL moet vertaald worden naar de zaak identificatie
- In tab Gerelateerde zaken, achter de zaak knop met ontkoppelen 
- Reden meegegeven in dialog
- Icoon van 'document ontkoppelen' gebruiken
- Tweezijdig ontkoppelen. De zaak waar je in zit en de zaak waar hij mee gekoppeld is.

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Test OK. Bij werkvoorraad duurt het even voordat het icoontje is verdwenen maar dat zal door Solr komen denk ik

**Comment by HilbrandHurtak** [comment]
Test OK. Bij werkvoorraad duurt het even voordat het icoontje is verdwenen maar dat zal door Solr komen denk ik
