### ISSUE TITLE
Indicaties op zaken werkvoorraad en mijn zakenwerkvoorraad

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1221]
***Als*** Werkverdeler

***Wil ik*** indicaties op de werkvoorraad

***Zodat*** ik weet wat er met een zaak speelt zonder hem te openen

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De werklijsten 'Zaken-werkvoorraad' en 'Mijn zaken' tonen in het overzicht  bij de zaken die indicaties hebben welke dit zijn. De indicaties zijn zichtbaar in de kolom 'Indicaties' in de vorm van een chip met daarop de letter van het type indicatie. De kolom wordt standaard in de werklijst weergegeven.
De gebruikte afkortingen van de indicaties in de chips:
O: Is opgeschort
V: Is verlengd
H: Is heropend
HZ: Is hoofdzaak
DZ: Is deelzaak

***Belangrijkste functionaliteiten:***
- Gebruiker kan de kolom verbergen met filters icoon
- Gebruiker kan door de muisaanwijzer over de chip te houden de volledige naam van de indicatie zien en de ingevulde reden daarvoor

**Comment by robertverboom** [comment]
### Refinement 04-08:
Voor 'zaken werkvoorraad' en 'mijn zaken' 
- In de werklijsten kolom toevoegen: Indicaties
- Component maken voor de indicaties met verkorte/kolom view
- Bolletje met eerste letter van indicatie tonen (zonder 'is') 
- Bolletje met mouse over voor de volledige naam 
- Zaak- en documentscherm refactoren

**Comment by robertverboom** [comment]
test ok

**Comment by GertrudeKampherbeek** [comment]
Het tonen van de indicatie werkt goed. 
Vraag aan werkgroep: de indicatie van opschorten is fuchsia maar die van verlengen grijs. aanpassen?
![image.png](https://images.zenhubusercontent.com/6215ee21a7a0b74c19209bdb/8700bd24-0e65-472a-9798-17fd8238c52b)
