### ISSUE TITLE
Gerelateerde documenten van koppelzaak inzien

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1234]
***Als*** Zaakbehandelaar

***Wil ik*** Documenten van andere zaken die gekoppeld zijn kunnen inzien

***Zodat*** ik een overzicht heb van alle documenten die betrekking hebben tot de verschillende zaken

***

### Acceptance criteria:
- Kunnen zien in 1 oogopslag. 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een zaak kan een of meer gekoppelde zaken hebben. Het is mogelijk om vanuit een zaak de documenten van de gekoppelde zaak te bekijken.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in een zaak door het ‘Toon gekoppelde zaakdocumenten’ schuifje aan te zetten de documenten van gekoppelde zaken in het zaakdocumentenoverzichten weergeven

**Comment by RoyBuis** [comment]
### Refinement 4-7

**Te realiseren**

- Knop bij overzicht documenten waarmee docs van de gekoppelde zaak kunnen worden opgehaald
- Daarna worden er 2 kolommen toegevoegd: 1 zaakidentificatie (Zaaknummer) en 2 aard relatie (Relatietype)

**Technisch**
- Documenten van de gerelateerde zaken komen in zelfde tabel als van de geopende zaak

**Comment by robertverboom** [comment]
test ok.

**Comment by HilbrandHurtak** [comment]
Getest op acc met zaak  ZAAK-2023-0000000050 en ZAAK-2023-0000000049
Beide zaken hebben 2 documenten. Ik zie echter niet bij de hoofdzaak de documenten van de deelzaak en andersom. Schuifje 'Toon gekoppelde zaakdocumenten is weg. Wordt pas getoond na een refresh van de url. Na het aanzetten van deze functionaliteit worden er helemaal geen documenten meer getoond. Dit werkte eerder wel maar nu dus niet meer
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/a2916d60-68d2-40b8-b36a-67395642ee16)

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/dad87f78-1847-4142-9578-4d06ba8366b6)

**Niet Akkoord**

**Comment by KarinMasselink** [comment]
@HilbrandHurtak de bug is opgelost en deze heb je ook gesloten. Wil je deze US dan ook hertesten en bij akkoord sluiten?

**Comment by HilbrandHurtak** [comment]
Getest onder bug #2394 en akkoord bevonden
