### ISSUE TITLE
Koppelen van gesloten zaken

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1235]
***Als*** Zaakbehandelaar (of recordmanager?) 

***Wil ik*** afgesloten zaken kunnen koppelen zonder ze eerst te heropenen

***Zodat*** ik eenvoudig de relaties kan bijwerken. 

***

### Acceptance criteria:
- Mag dit wel? 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Could haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #895 is het kunnen koppelen van openstaande zaken als hoofd- en deelzaak opgeleverd. In deze story is deze functionaliteit uitgebreid waardoor het mogelijk is om ook beëindigde zaken als hoofd- en deelzaak te koppelen. Deze functionaliteit is alleen beschikbaar met de recordmanager rol.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met de actie [Zaak koppelen] een afgehandelde zaak op het klembord plaatsen
- Gebruiker kan in een afgehandelde zaak waarmee de koppeling gelegd moet worden vanuit het klembord te zaken aan elkaar koppelen en de soort relatie tussen de zaken bepalen
- Het koppelen van zaken als hoofd- en deelzaak wordt als wijziging van hoofdzaak in de historie van de DEELzaak vastgelegd

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Knop 'Zaak koppelen' beschikbaar maken bij een beindigde zaak: Knop is aanwezig.
Maar bij Afgehandelde zaken (ZAAK-2023-0000000039 / ZAAK-2023-0000000079) lukt het niet om deze aan elkaar te relateren.
Er is geen koppeling mogelijk. Er zijn al koppelingen aanwezig op de andere zaak, of op de onderhanden zaak die conflicteren.

**Comment by VictorTielenius** [comment]
![Koppelen afgehandelde zaken.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/6c496efc-2615-4fad-a0a4-18cd74547bcd)

**Comment by RoyBuis** [comment]
### Refinement KM, SN, RV & RB

Deze foutmelding houdt in dat je voor dit zaaktype geen hoofd-deelzaak koppeling mag leggen omdat die kopeeling niet in het zaaktype is gelegd. 

In de accept omgeving is hoofd-deel zaak koppeling gelegd tussen Melding klein evenement en Bezwaar indienen. Met deze twee zaaktypen kun je dit issue testen.

**Comment by VictorTielenius** [comment]
ZAAK-2023-0000000079 (melding klein evenement) gekoppeld aan ZAAK-2023-0000000068	(bezwaar indienen): OK
