### ISSUE TITLE
Restpunten SDsjabloon

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1236]
***Als*** Zaakbehandelaar

***Wil ik*** in de zaakhistorie kunnen zien wie het SD sjabloon heeft toegevoegd

***Zodat*** ik weet wie dit document heeft toegevoegd

***

### Acceptance criteria:
- Eventueel auteur overnemen
- Toelichting op zaakhistorie meegeven aan SD
- Creatiedatum meegeven 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by andyverberne** [comment]
- [ ] Eventueel auteur overnemen
- [ ] Toelichting op zaakhistorie meegeven aan SD
- [ ] Creatiedatum meegeven
