### ISSUE TITLE
afsluiten van heropende zaak moet zelfde functionaliteit krijgen als zaak afhandelen 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1237]
Als zaakbehandelaar

Wil ik de zelfde functionaliteit hebben bij het afsluiten van een zaak als bij het regulier afhandelen van een zaak

Zodat de juiste zaakgegevens kan worden vastgelegd

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #1086 is het kunnen heropenen van een zaak opgeleverd. In deze story is deze functionaliteit uitgebreid door een heropende zaak op identieke wijze als een openstaande zaak te kunnen afhandelen.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met de actie [Zaak afhandelen] een heropende zaak afhandelen, hierbij is dezelfde functionaliteit als bij een openstaande zaak beschikbaar. De actie [Zaak afbreken] is niet beschikbaar.

**Comment by robertverboom** [comment]
### Refinement 30-06

- Zelfde knop en titel: Zaak afhandelen
- Opnieuw pop-up om resultaat te kiezen

**Comment by robertverboom** [comment]
test ok

**Comment by Renvooi** [comment]
7-3-2023 getest en akkoord
