### ISSUE TITLE
werkvoorraad filters bewaren ook na uitloggen. 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1240]
***Als*** Werkverdeler

***Wil ik*** de mijn ingestelde filters/sortering behouden na uitloggen. 

***Zodat*** de volgende dag weer verder kan met het verdelen van het werk

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een gebruiker heeft de mogelijkheid om de toegepaste filters in een werklijst als zoekopdracht te bewaren. Deze zoekopdracht blijft ook na het uitloggen bewaard en kan in een nieuwe sessie weer geopend worden.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met het ster icoon de toegepaste sortering en filters als zoekopdracht opslaan.
- Door in een ongefilterd overzicht op het trechter icoon te klikken kan een bewaarde zoekopdracht worden geopend en kunnen zoekopdrachten met een klik op de prullenbak worden gewist.

**Comment by robertverboom** [comment]
### Refinement 30-06

- Zoekopdracht kunnen opslaan in de DB met naam
- Bijhouden welke actief is 
- DB krijgt ID, gebruikersnaam, welke lijst, json string, actief

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Diverse filters aangemaakt en opgeslagen via onderstaande knopjes
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/1faeef32-32fb-4110-be4f-6c64e866aea4)

Deze zijn vervolgens weer netjes op te roepen. Bestaande filters kunnen ook worden aangepast of worden verwijderd

Test OK
