### ISSUE TITLE
BUG: 400 als een document is vergrendeld en je wilt de zaak afronden

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1242]
***Steps to reproduce:***

1. Maak een zaak aan
2. Voeg document toe en vergrendel hem
3. Handel de zaak af

***Expected***
Zaak wordt afgehandeld

***Actual***
(400) Title: Invalid input., Detail: Name: nonFieldErrors, Code: informatieobject-locked, Reason: Er zijn gerelateerde informatieobjecten die nog gelocked zijn.Deze informatieobjecten moet eerst unlocked worden voordat de zaak afgesloten kan worden.

**Comment by marcoatos** [comment]
Gaat opgelost worden mbv OPA.
