### ISSUE TITLE
BUG: Vertaling in taakhistorie

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1246]
***Steps to reproduce:***

1. ga naar taak historie 
2. 
3. 

***Expected***
Vertaling van oude en nieuwe waarde 

***Actual***

**Comment by hansmarks** [comment]
Geen bug. Dit was gewoon nog niet gebouwd. ;-)

De kolom Wijziging is nu vertaald, inhoud was nog hardgecodeerd. En gebruikers en groepen in de waarden worden met naam getoond inplaats van een id en datums zijn netjes geformateerd.

**Comment by robertverboom** [comment]
test ok
