### ISSUE TITLE
Bepaalde foutmeldingen uit Open Zaak tonen aan gebruiker

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#1258]
In een aantal gevallen is het wenselijk wanneer een validatie fout uit Open Zaak op een 'nette' manier aan de gebruiker getoond wordt. Bijvoorbeeld in de volgende gevallen:

- Een zaak kan niet worden afgesloten omdat er nog gelockte documenten zijn

Dit zijn situaties welke door het zac gecontroleerd kunnen worden maar deze controles zijn complex en vragen veel resources. In plaats daarvan kan deze controle in Open Zaak plaatsvinden mits de foutmelding netjes getoond wordt.

**Comment by andyverberne** [comment]
Huidige situatie:
* De ZGW Api Client gooit een aparte exceptie in het geval van een 400 fout: ValidatieFoutException
* Deze exceptie bevat gedetaileerde fout informatie via het ValidatieFout object

**Comment by RoyBuis** [comment]
### Refinement 4-7

- Basis REST object die validatie foutmeldingen bevat
- Foutmelding uit Open Zaak (en later ook uit andere componenten) tonen in dialog
- Controle op open deelzaken verwijderen uit policy en hardcoded business rule van maken met foutmelding via bovenstaande REST object

Later policies nog een keer bespreken met elkaar, ook in het kader van deze story!

**Comment by andyverberne** [comment]
Is het niet ook mogelijk om een vanuit de backend een HTTP 400 te gooien met een specifiek RESTFoutmelding object en deze in Angular op te vangen om de foutmelding te tonen? Dan hoeven niet alle REST objecten te worden aangepast. 

Er staat ook al een ToDo in de code welke verwijst naar deze user story
