### ISSUE TITLE
BUG: Heropenen zaak geeft foutpagina

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1268]
***Steps to reproduce:***

1. Afgehandelde zaak Heropenen
2. 
3. 

***Expected***
Zaak wordt Heropend en aantal Acties is weer beschikbaar

***Actual***
Foutpagina 
De server heeft code 500 geretourneerd
Algemene Fout

**Comment by robertverboom** [comment]
wordt opgelost met #1205

**Comment by robertverboom** [comment]
Graag opnieuw beoordelen

**Comment by HilbrandHurtak** [comment]
Afhandelen gaat nu goed zie #1162. Heropenen geeft nog steeds een 500 foutmelding. Getest op zandbak en testomgeving GZAC

**Comment by robertverboom** [comment]
Bleek een inrichtingsfout te zijn in Open-Zaak, echter werkt het nog niet na behoren. Ander issue voor aangemaakt

**Comment by VictorTielenius** [comment]
ZAAK-2022-0000000137 aangemaakt, Afgebroken en Heropend.
Actie Zaak Afbreken niet teruggekomen.
Zaak niet meer terug te vinden ???

**Comment by robertverboom** [comment]
_ZAAK-2022-0000000137 aangemaakt, Afgebroken en Heropend.
Actie Zaak Afbreken niet teruggekomen.
Ook Actie "Ontvangstbevestiging sturen"+ "Intake afhandelen" en Taak Starten komt niet terug. Bewust?_
Bewust; Het CMMN wordt afgerond bij het afbreken en afhandelen van zaken. Hierdoor wordt er geen status meer gewijzigd en Taken meer gestart. Een ontvangsbevesting sturen zal de behandelaar in een eerder stadium moeten doen. Wanneer deze alsnog eentje wilt versturen, zal dit via een 'normale' mail gedaan moeten worden. (functionaliteit werkt het zelfde. 

_Zaak niet meer terug te vinden via Werklijst. (Bug issue aangemaakt) Er was geen Groep of Behandelaar gekoppeld. 
Via URL de zaak weer gevonden en op Groep A en mijn naam gezet, maar via Werklijsten nog niet terug te vinden._
Wordt aan gewerkt. Momenteel speelt er een issue die meerdere functionaliteiten raakt: #1520 

_Oudere zaak Heropenen (ZAAK-2022-0000000082) levert geen terugkomen van Acties op._
Oudere zaken vallen onder een ouder CMMN model, waardoor deze actie nog niet bestond.
