### ISSUE TITLE
BUG: Bij Historie Zaak geen verschil tussen verwijderen document en Ontkoppelen document.

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1276]
***Steps to reproduce:***

1. Document verwijderen uit zaak
2. Document ontkoppelen bij zaak
3. Historie bekijken

***Expected***
Zoals in de e-Suite bij Historie bij kolom Wijziging: Document verwijderd of Document ontkoppeld

***Actual***
Bij Historie bij kolom Wijziging:  Document

**Comment by VictorTielenius** [comment]
![image.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/83763541-1089-42bf-a643-64ef7c02ec37)

**Comment by VictorTielenius** [comment]
![image.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/78041479-f4f3-4535-8686-63590c77e6c0)

**Comment by robertverboom** [comment]
Ontwikkelomgeving nagespeeld met zaak: https://zac.develop-public-service-platform.net/zaken/ZAAK-2022-0000001409

**Comment by robertverboom** [comment]
### Refinement 18-07:
- Prefix met Ontkoppeld/Verwijderd

**Comment by robertverboom** [comment]
tes

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Nu bij de Toelichting in de Historie begint het altijd met "Ontkoppeld:" of "Verwijderd:"
Reden verwijderen is verplicht.
Reden bij Ontkoppelen is niet verplicht. Zonder reden komt er: "Ontkoppeld: null"
Bij Historie niet direct zichtbaar, pas na verversen.

**Comment by HilbrandHurtak** [comment]
Ik krijg bij het verwijderen een 500 melding(op zandbak en test). Document is echter wel verwijderd en de historie bijgewerkt(pas na verversing). Getest met zaak ZAAK-2022-0000000121 (Zandbak)

**Comment by VictorTielenius** [comment]
Document verwijderen geeft foutpagina (Foutpagina
De server heeft code 500 geretourneerd)
Historie (bij Ontkoppelen) niet direct zichtbaar. Pas na verversen

**Comment by robertverboom** [comment]
laatste opmerking wordt opgelost met #1782

**Comment by VictorTielenius** [comment]
Hertest #1590:
Nu een PDF en een Word document te verwijderen zonder foutpagina te krijgen

**Comment by VictorTielenius** [comment]
Historie (bij Ontkoppelen) niet direct zichtbaar. Pas na verversen: wordt opgelost met #1782
