### ISSUE TITLE
BUG: Titelwaarde in documenthistorie wordt als datum getoond

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1288]
***Steps to reproduce:***

1.  maak een document aan als titel 1234
2.  ga naar de historie van het document
3. 

***Expected***
nieuwe warde: 1234

***Actual***
nieuwe waarde 01-02-1234

**Comment by robertverboom** [comment]
Lijkt op: #1021

**Comment by robertverboom** [comment]
Datumpipe moet aan de voorkant eraf

**Comment by andyverberne** [comment]
@hansmarks : Had jij dit niet al opgelast door die pipes te verwijderen? Of moet dat juist nog gedaan worden?

**Comment by hansmarks** [comment]
Moet nog.

**Comment by jeroen-dekker** [comment]
Zo te zien worden de `oudeWaarde` en `nieuweWaarde` op de `informatie-object-view.component`-pagina gevuld door de `historie` datasource. Deze twee attributen van de `historie-regel` zijn een `string`, net als de andere attributen. Deze informatie wordt door de back-end opgeleverd via een GET-request naar `/informatieobject/${uuid}/historie`. De informatie wordt geconverteert vanuit de audit trail naar de nodige historieregel d.m.v. `RESTHistorieRegelConverter::convertAuditTrailBasis`.

Ik vermoed dat er in de doorontwikkeling een wijziging is geweest in hoe deze historieregels worden aangeleverd aan de front-end. De Datum-pipe is nu niet meer nodig om de data goed te tonen, maar in het verleden waarschijnlijk wel (anders had de datum-pipe hier vast niet gestaan). Wat daar precies gewijzigd is, ben ik nog naar op zoek.

**Comment by hansmarks** [comment]
Dat laatste klopt. Is ook zo besproken tijden de planning (daar was je ook bij dacht ik). En wat dat ticket betreft waarin dat gewijzigd is.

Ehm... heb je dat gekoppelde ticket gezien? Heb je dat ticket gezien wat Marco noemde? En waarvan ik zei dat het ook in het ticket stond?

**Comment by jeroen-dekker** [comment]
Ik heb gekeken naar het gekoppelde ticket, maar daar kan ik het PR niet van terugvinden. In de comments zie ik ook niet terug wat daar precies is gewijzigd, alleen dat er een andere oplossingsrichting is gekozen. Ik ben nog aan het kijken naar het ticket wat Marco noemde en wat voor implicaties die diff had i.c.m. de git history van de files waar ik naar aan het kijken ben.

**Comment by jeroen-dekker** [comment]
Zo te zien is er een wijziging geweest aan `RESTHistorieRegel::toWaarde` waardoor de LocalDate of ZonedDateTime als geformatteerd als String wordt toegewezen aan het object wat wordt geretourneerd naar de front-end. Hierdoor is de datum-pipe overbodig geworden, en kunnen ook andere wijzigingen dan data correct getoond worden.

De oplossing is - zoals al eerder door meerdere mensen genoemd - het verwijderen van de overbodig geworden datum-pipe. Om er achter te komen waar deze allemaal verwijderd moet worden kan ik kijken naar de usages van de historie-regel in de front-end.

**Comment by hansmarks** [comment]
Ik zie het, dat is het klant ticket. Hier is de commit: https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/pull/1185/commits

Gewoon even vragen als je zoiets niet kunt vinden. ;-)

**Comment by jeroen-dekker** [comment]
PR geopend: https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/pull/1371
