### ISSUE TITLE
Signalering voor taken behandelaar wordt niet gegeven

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1289]
Fout bij 'Signalering voor taken behandelaar' #462

Zowel de signalering per email als de signalering in dashboard worden niet gegeven.

**Comment by CommonGroundGroningen** [comment]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/c68c66b8-c3e0-4d34-895b-aa31e4dc9c1d)

**Comment by HilbrandHurtak** [comment]
Vanuit een ander account heb ik bij de zaak 155 een taak toegekend aan mijzelf. Ik heb de volgende instelling bij Signaleringen:
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/e5339b85-d6a2-4a6f-b048-bbdfee12f098)

Nadat ik onder mijn eigen account ben ingelogd zie ik geen taken die recent aan mij zijn toegekend.
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/82a3302b-f204-42e8-bbe6-6cca228e974d)

**Comment by robertverboom** [comment]
- Vanuit starttaak formulier werkt de signalering 'recent aan mij toegewezen taken' niet, 
- Vanuit de taak zelf en verdelen uit de taak werkvoorraad wel.

**Comment by hansmarks** [comment]
Graag alle commits op zaakafhandelcomponent-1289 reviewen, de meeste zijn al gemergd (omdat ik timig problemen lastig lokaal kan testen) maar als er nog iets verbeterd moet worden dan doe ik dat uiteraard nog.

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by HilbrandHurtak** [comment]
De taak die ik van Robert kreeg staat in mijn Signalering. Tevens heb ik hiervan een mail gekregen. Lijkt dus te werken

**Comment by HilbrandHurtak** [comment]
@robertverboom Jij ook de besten wensen Robert. 

Heb het issue kunnen testen. Zie de signalering en het mailtje bij een nieuwe taak op mijn naam.

Test ok
