### ISSUE TITLE
Archiefbeheercomponent installeren/uitrollen op de zandbak

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1297]
***Als*** WG Informatiebeheer

***Wil ik*** de Archiefbeheercomponent kunnen testen/ gebruiken op de Zandbak-omgeving (i.c.m. OpenZaak)

***Zodat*** deze beoordeeld kan worden (fit-gap) en wij de user stories kunnen aanscherpen

***

Zie Github voor info over het Archiefbeheercomponent: https://github.com/maykinmedia/archiefbeheercomponent

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by andyverberne** [comment]
https://archiefbeheercomponent.readthedocs.io/en/latest/

**Comment by Snijhuis** [comment]
Deze sluit ik. Wanneer er namelijk een podiumD zaak omgeving wordt opgetuigd zal het doorontwikkelde ABC component ook onderdeel uitmaken van de oplossing. Technisch hebben we connectie gelegd op de zandbak en dat hebben we bereikt met deze story.
