### ISSUE TITLE
Openen dialog sluit niet de sidenav

### ISSUE THREAD

**Issue by marcoatos** [NL-AMS-LOCGOV/zaakafhandelcomponent#1302]
Het openen van een dialog sluit niet de sidenav.

Hierdoor is het mogelijk om bijvoorbeeld de intake fase een formulier te starten voor aanvullende informatie. Terwijl het formulier openstaat in de sidenav kun je de intake afronden. Als je daarna verder gaat met de aanvullende informatie sidenav krijg je een foutpagina.

**Comment by robertverboom** [comment]
### Refinement 14-07:
- Vanuit een menu actie eerst de dialogvenster sluiten
