### ISSUE TITLE
BUG: Aanmaken notitie knop is altijd ingeschakeld

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#131]
***Steps to reproduce:***

1. Open een lopende zaak
2. Klik op de notitie knop
3. Klik op de opslaan knop

***Expected***
De opslaan knop is uitgeschakeld omdat ik geen inhoud heb ingevuld. De knop wordt pas actief als ik minimaal één karakter in de inhoud heb ingevuld

***Actual***
De opslaan knop is actief ondanks dat ik geen inhoud heb ingevuld. Als ik opslaan klik dan toont de browser console ook een error

Tweede scenario:
1. Open een lopende zaak
2. Klik op de notitie knop
3. Vul de inhoud en maak een notitie aan
4.  Klik op bewerken bij de aangemaakte notitie
5. Vul een tekst in bij het nieuwe notitie veld en klik op de opslaan knop bij voeg een notitie toe

***Expected***
Het nieuwe notitie veld en de opslaan knop zijn uitgeschakeld omdat ik een bestaande notitie aan het bewerken ben. Ik wil één van de twee handelingen doen, of een bestaande bewerken óf een nieuwe aanmaken.

***Actual***
De opslaan knop is actief ondanks dat ik geen inhoud heb ingevuld. Tijdens het bewerken van een bestaande notitie kan ik een nieuwe notitie toevoegen.

**Comment by robertverboom** [comment]
test ok
