### ISSUE TITLE
Zaakhistorie met niet te veel regels

### ISSUE THREAD

**Issue by YvonKoomen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1313]
***Als*** 
behandelaar
***Wil ik*** 
de historie van een overdracht makkelijk kunnen lezen
***Zodat*** 
ik snel begrijp dat in het verleden de zaak van de ene naar de andere behandelaar is overgezet
***

### Acceptance criteria:
- geen dubbele informatie in de historie
- een transactie in een regel vastleggen

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Should haves
gelinkt aan het testen van #158
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by PaskalKiers** [comment]
Ik denk dat de essentie is dat ik als gebruiker de functionele historie wil zien. 
Dus als ik een zaak overneem van Yvon, dan wil in de historie zien dat op 14 juli 11:25 de oude waarde van de assignee wijzigt van Yvon naar de nieuwe: Paskal.


Aan de story wordt op dit moment voldaan, ook als je rekening houdt met de acceptatiecriteria, want transactie is minimaal ambigu in deze context, maar ik ken dit woord vooral in de technische context en dan beschrijft de story precies wat er nu gebeurt.   
Mijn voorstel zou zijn om het acceptatiecriterium aan te passen dat in een historie regel de oude en nieuwe waarde vanuit gebruikersperspectief (behandelaar en dergelijke) te zien is.  Want tenzij deze de zaak helemaal ontkoppeldop zich wordt nu voldaan.
Ik denk zelfs dat ik het hele story een beetje concreter zou maken.   Als behandelaar wil ik de oude en nieuwe waarde van mijn wijzigingen naast elkaar terug kunnen zien, zodat ik een in oogopslag kan zien wat er gewijzigd is op één bepaald moment oid. 

Nu laat de historie zien wat er waarschijnlijk technisch gebeurd. Namelijk eerst wordt er een regel gemaakt waarin Yvon ontkoppeld wordt (en er dus niemand gekoppeld is) (transactie 1) en vervolgens wordt er een regel gemaakt, waarin ik gekoppeld wordt. (transactie 2), terwijl de behandelaar geïnteresseerd is in het resultaat van de transacties.

**Comment by YvonKoomen** [comment]
bedankt Paskal, ik heb de acceptatiecriteria aangepast
