### ISSUE TITLE
Bij ontkoppelen van zaken (alle relatietypen) moet het reden veld verplicht zijn

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1317]
***Als*** Zaakbehandelaar

***Wil ik*** Dat het redenveld verplicht is bij ontkoppelen van zaken

***Zodat*** er altijd een reden moet worden opgegeven bij het ontkoppelen en deze terug te vinden is in de historie

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #1218 is het kunnen ontkoppelen van zaken als hoofd- en deelzaak opgeleverd. In deze story is deze functionaliteit uitgebreid door de gebruiker hier verplicht een reden bij te laten vastleggen.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in een zaak via het tabblad ‘Gerelateerde zaken’ op de regel van de zaak die ontkoppeld moet worden op het Zaak ontkoppelen-icoon klikken
- Gebruiker kan een reden invullen na het klikken op het Zaak ontkoppelen-icoon
- De reden bij het ontkoppelen van zaken als hoofd- en deelzaak wordt als toelichting bij de wijziging van hoofdzaak in de historie van de DEELzaak vastgelegd

**Comment by robertverboom** [comment]
test ok
