### ISSUE TITLE
Verduidelijken van de interface voor het knippen en plakken van documenten

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1318]
***Als*** Zaakbehandelaar

***Wil ik*** Dat de knip en plak functionaliteit (klembord) verduidelijkt wordt

***Zodat*** Ik goed wordt meegenomen in de werking van deze functionaliteit

***
NB. Gebruikers geven aan dat ze bij de knip en plak acties de logica niet goed begrijpen. Vanuit de WG hebben we de volgende suggesties:

1. Klembord van een titel voorzien: Verplaatsen documenten
2. Na het klikken op het 'knipicoon' bij het document het 'plakicoon' op het klembord rood maken (is nu grijs). Toelichtende tekst (mouseover?): zoek of selecteer een zaak waar het document naartoe verplaatst moet worden
3. 'plakicoon' groen maken als er geplakt mag worden,

Uiteraard zijn suggesties welkom vanuit ontwikkelteam.

### Acceptance criteria:
- 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by robertverboom** [comment]
### Refiniment 18-07:

2 klemborden maken: 
- Documenten verplaatsen
- Zaken koppelen
- Als actie niet uitgevoerd kan worden, met mouse-over? hint geven wat er dan wel gedaan moet worden. Bijv:  _zoek of selecteer een zaak waar het document naartoe verplaatst moet worden._ Zaken klembord:
_Zoek of selecteer een zaak waar de zaak aan gekoppeld moet worden_
