### ISSUE TITLE
BUG: 500 melding bij invullen spatie voor veld auteur bij Toevoegen van een document

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#1330]
***Steps to reproduce:***

1. Open een bestaande zaak
2. Klik op Toevoegen van een document
3. Vul alle verplichte velden
4. Maak het veld auteur leeg en vul daar enkel een spatie in

***Expected***
Validatiemelding dat het veld auteur verplicht is

***Actual***
Error 500 melding bij het toevoegen van het document

**Comment by robertverboom** [comment]
test ok
