### ISSUE TITLE
BUG: Zoeken werkt niet

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#1333]
***Steps to reproduce:***

1. Start een zoek actie

***Expected***
De mogelijkheid om trefwoorden in te vullen

***Actual***
Er wordt een voortgang indicator getoond welke niet verdwijnt waardoor het niet mogelijk is om een trefwoord in te voeren.

**Comment by robertverboom** [comment]
test ok
