### ISSUE TITLE
Verduidelijken werking koppelen van zaken (relatie leggen)

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1334]
***Als*** Zaakbehandelaar

***Wil ik*** dat het koppelen/relateren van zaken  verduidelijkt wordt

***Zodat*** ik goed wordt meegenomen in de koppelfunctionaliteit en ik de relatie (hoofd, deel, etc) goed kan bepalen.

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Story is gerealiseerd.
