### ISSUE TITLE
BUG: Werklijstkolommen worden niet meegenomen in opslaan functie

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1337]
***Steps to reproduce:***

1. Ga naar werklijsten
2. Wijzig de kolommen
3. Sla vervolgens de wijzigingen op

***Expected***
kolommen van de wijziging worden getoond

***Actual***
kolommen zijn niet meegenomen

**Comment by hansmarks** [comment]
Dat is geen bug, dat is gewoon (nog) niet geimplementeerd.
