### ISSUE TITLE
BUG: Filters worden gereset met wijziging kolommen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1338]
***Steps to reproduce:***

1. ga naar werklijsten
2. wijzig een filter
3. voeg een kolom toe

***Expected***
filter/sortering wijziging blijft staan 

***Actual***
filter/sortering wordt teruggezet (speelt bij alle werklijsten)

**Comment by hansmarks** [comment]
Dat is geen bug, dat is gewoon (nog) niet geimplementeerd.
