### ISSUE TITLE
BUG: Na heropende zaak geen ontvangsbevesting meer kunnen sturen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1344]
***Steps to reproduce:***

1. Heropen een zaak
2. Verstuur een ontvangsbevesting
3. 

***Expected***
Of een onvangstbevesting kan nog verstuurd worden na een heropende zaak, of deze functie is niet beschikbaar. (voorkeur laatste ivm andere story over afhandelingsmail)

***Actual***
krijgt 500: No case instance found for zaak with UUID: '72853db6-a2a1-4fa9-8233-bdee0b349c0b'

**Comment by jeroen-dekker** [comment]
Net een goed aandachtspuntje van Andy gekregen: ook even controleren of het versturen van een ontvangstbevestiging &uuml;berhaupt wel werkt. Dat neem ik hier direct mee.

**Comment by robertverboom** [comment]
test ok
