### ISSUE TITLE
Improvement op zaakafhandelparameters

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1352]
1. sortering op de kolommen. Laatst aangemaakte in Openzaak staat nu bovenaan. 
2. mouse-over (of andere indicatie) waarom er een vinkje staat ipv uitroepteken; "zaakafhandelparameters op het zaaktype zijn compleet" oid
3. Parameters kunnen kloppen, echter kan versie nog niet goed zijn. Wordt onduidelijk getoond. (wellicht iets met filter/sortering). Zie afbeelding. Krijgen wel vinkjes, echter 1 is geldig. Straks als je verschillende zaaktypen hebt is overzicht lastig te bewaren

![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/e51deaa9-6efa-429b-a7fc-4a7b8f7bced2)

**Comment by robertverboom** [comment]
### Refinement 25-07:
Filteren en sorteren: 
- valide/niet valide
- geldig/ niet geldig ( geldig verleden, geldig toekomst)
- zaaktype
- cmmn model

**Comment by bartlukens-atos** [comment]
Default geldig op ja zetten
Filters op zaaktype en cmmn model -> dropdown lijstje
Filters en sorteringen opslaan in sessionstorage
