### ISSUE TITLE
OPA zaakbehandelaar 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1360]
***Als*** 

***Wil ik*** 

***Zodat*** 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by robertverboom** [comment]
Excel toegevoegd op 07-09: ![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/cfd88bc2-57ed-4218-9286-dd97b0b40d2f)

**Comment by RoyBuis** [comment]
### Refinement 20-9

Overzicht van rollen compleet maken voordat er begonnen kan worden met inrichten in OPA
Overzicht in Githun delen zodat iedereen hetzelfde overzicht heeft
