### ISSUE TITLE
Bedrijven kunnen opzoeken op RSIN

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1362]
***Als*** Zaakbehandelaar

***Wil ik*** bedrijven kunnen opzoeken op hun RSIN

***Zodat*** ik ook andere bedrijven zonder KVK kan opzoeken. 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Bij een aantal functionaliteiten van de ZAC kan er naar een bedrijf gezocht worden, bijvoorbeeld om deze als initiator of betrokkene toe te voegen. In deze story zijn de zoekmogelijkheden uitgebreid waardoor het mogelijk wordt om op RSIN te zoeken. Op deze manier kunnen ook niet natuurlijke personen (rechtspersoon of samenwerkingsverband) gevonden worden, deze kunnen met de KvK Zoeken API niet op kvk-nummer gezocht worden. Als een rechtspersoon of samenwerkingsverband als initiator of betrokkene aan de zaak wordt toegevoegd dan krijgt deze in de rol het betrokkene type 'niet-natuurlijk persoon'.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in de algemene zoekfunctie zoeken op RSIN om zo een rechtspersoon of samenwerkingsverband te vinden
- Gebruiker kan in het zoekpanel voor het toevoegen van een initiator of betrokkene een rechtspersoon of samenwerkingsverband op RSIN zoeken en deze aan de zaak toevoegen

**Comment by robertverboom** [comment]
### Refinement 21-07:
- Zoeken op RSIN mogelijk maken in UI
- Het gevonden resultaat analyseren of het een vestingsnummer heeft. 
Zo ja; koppelen via vestingsnummer
Zo nee; URL naar resultaat in Haal Centraal vullen in betrokkene veld van rolVestiging 
- URL moet gecommuniceerd naar Angular om uit Haal Centraal te kunnen halen.

**Comment by hansmarks** [comment]
https://developers.kvk.nl/nl/support/oas-swagger/zoeken-api
http://open-zaak.default/zaken/api/v1/schema/#operation/rol_create

**Comment by hansmarks** [comment]
Gebouwd zoals gespecificeerd. Alleen is het met de huidige test KvK API. Niet te testen daar zitten namelijk geen RSIN in. Op elke denkbare query die ik uitvoer krijg ik vestigingen terug zonder RSIN.

Gevolg is:
1) Er kan gezocht worden op RSIN maar er komt nooit iets terug.

2) Het opslaan van een RolVestiging op basis van de URL (als de gevonden vestiging gene vestigingsnummer heeft) is nooit daadwerkelijk getest. En hoewel ik de service bekend heb gemaakt bij open_zaak (conform BAG, zoals aangegeven door Andy) kan het goed zijn dat open_zaak de betrokkene URLs (nog) niet accepteert, of zelfs dat het toch niet mogelijk blijkt om het Vestigingsnummer leeg te laten.

**Comment by hansmarks** [comment]
Overigens is er ook het nodige gerefactored als consequentie van het feit dat een BSN en een RSIN hetzelfde aantal cijfers hebben. Die verbeteringen zijn sowieso, ehm... verbeteringen.

De verplichtheid van de toelichting bij een betrokkene werkte ook niet correct. Hersteld.

In het zaakaanmaken-scherm is de initiator-control nu qua gedrag gelijk aan de lokatie-control. Dat wil zeggen readonly en kan alleen via het panel gezet worden.

**Comment by hansmarks** [comment]
Ronnie wist toch de rsins te vinden:
Met vestigingsnummer: 857587973
Zonder vestigingsnummer: 858311537 (heeft wel KvK-nummer)

**Comment by hansmarks** [comment]
Blijkbaar krijg je alleen een rsin terug als je ook gezocht hebt naar een rsin.

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Gezocht op de door Ronnie aangegeven RSIN's en deze geven inderdaad een gevonden resultaat terug.

Na selecteren van vestiging wordt dit nummer niet weergegeven bij de details. Kan niet beoordelen of dit de wens was en of dit in de  API wordt weergegeven. Misschien worden deze gegevens wel via de betaald versie teruggegeven.

Voor nu Akkoord (Zoeken op RSIN)

Test OK
