### ISSUE TITLE
Initiator kunnen wijzigen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1363]
***Als*** Zaakbehandelaar

***Wil ik*** eenvoudig een initiator kunnen wijzigen 

***Zodat*** niet eerst moet ontkoppelen en weer een nieuwe moet koppelen

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Could haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Bij een zaak die een initiatior toegekend heeft kan deze in één handeling worden gewijzigd naar een andere initiator. Dit kan zowel een persoon als bedrijf zijn.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het menu met de actie [Initiator wijzigen] een nieuwe persoon of bedrijf zoeken en selecteren waarmee de vorige persoon/bedrijf wordt verwijderd bij de zaak
- Het wijzigen van een initiator wordt als wijziging van een persoon/bedrijf met vermelding van het bsn/vestigingsnummer vastgelegd in de historie van de zaak

**Comment by robertverboom** [comment]
### Refinement 21-07:
- Het feit dat er maar 1 initiator kan zijn op een zaak mag hard gecodeerd worden en hoeft niet ingeregeld te worden via een policy. businessrule verwijderen uit de policy, afdwingen in de UI en back-end
- toevoegen en verwijderen is genoeg
- actie toevoegen: wijzigen initiator

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
OK, zoeken van personen (#293) nog wel aantal issues.
