### ISSUE TITLE
We hebben een low level functie nodig om UUIDs om te zetten in URLs.

### ISSUE THREAD

**Issue by hansmarks** [NL-AMS-LOCGOV/zaakafhandelcomponent#1368]
Er wordt nu op veel plaatsen bijvoorbeeld een zaak opgehaald alleen maar omdat je de UUID hebt en je voor een methode de URL nodig hebt.

Andy geeft aan dat dat ophalen zelfs helemaal niet nodig is, omdat er een URL-builder is die dit netjes kan doen.

Als we deze functie hebben kunnen we veel meer met UUIDs gaan werken in method parameters inplaats van met URLs of zelfs complete zaken. En wordt onze code een stuk netter. En er wordt veel minder vaak een complete entiteit opgehaald.

**Comment by robertverboom** [comment]
'eerste slag' maken
