### ISSUE TITLE
BAG: Gebruik maken van relatieomschrijving

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#1374]
Bij het koppelen van het ZaakObject aan de zaak kan ook een relatieomschrijving worden opgegeven. 
Deze zou bijvoorbeeld opgevraagd kunnen worden op het moment dat men op de knop drukt om het BAG object te koppelen aan de zaak

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Is niet meer relevant.
