### ISSUE TITLE
BUG: Lukt niet meer om een Zaak aan te maken waaraan een locatie is gekoppeld

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#1385]
***Steps to reproduce:***

1. Maak een nieuwe zaak aan m.b.v. zaakaanmaken button
2. Selecteer een locatie bij het aanmaken van de zaak
3. Klik op de zaakaanmaken button

***Expected***
Er wordt een nieuwe zaak aangemaakt met daaraan gekoppeld de locatie

***Actual***
Er wordt geen zaak aangemaakt

**Comment by andyverberne** [comment]
Ik kan deze niet reproduceren. Heeft het met specifieke rechten te maken?

**Comment by robertverboom** [comment]
Steps:
Maak een nieuwe zaak aan
Voeg een locatie toe, zonder het pinnetje te gebruiker. Ofwel voer in: 'S.S. Rosensteinlaan 1, 9713AS Groningen'
druk op Aanmaken

Console geeft een: ERROR TypeError: Cannot read properties of undefined (reading 'centroide_ll')

**Comment by hansmarks** [comment]
Het is nooit mogelijk geweest om zomaar een adres in dat veld te plakken en dat het dan werkt. Dat kan alleen via het sidenav-panel.

De reden is dat die tekst niet de locatie is, de echte locatie zit achter de schermen en de tekst is daar alleen maar een leesbare weergave van.

Bij het initiator veld is het wel mogelijk om er met de hand een BSN of Vestigingsnummer in te zetten. Maar dat kan alleen omdat dat unieke sleutelwaarden zijn voor respectievelijk een Persoon of een Vestiging.

Kortom dit is geen bug. Maar misschien wel verwarrend. Daarom heb ik het veld disabled gemaakt zodat je alleen via de sidenav er een waarde in kunt krijgen.

Ik heb nog verwoedde pogingen gedaan om de styling aan te passen zodat ie weer lijkt op de andere controls op het scherm maar dat is me niet gelukt. Het probleem is dat die "disabled"-styling vooral op de elementen zit die om de daarwerkelijke input heen zitten en het id (waarop je zou willen selecteren) zit dus juist op die input.

Kortom daar moeten we nog maar eens naar kijken. Hoe we dat netjes kunnen oplossen. Voor nu kan de fout niet meer optreden, en wordt Marc gedwongen om de control te gebruiken zoals ie bedoeld is. ;-)
