### ISSUE TITLE
BUG: Werkvoorraad filters worden niet onthouden in sessionstorage

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1386]
***Steps to reproduce:***

1.  Ga naar werkvoorraad
2. verander iets in de filters
3. ga naar een zaak
4. navigeer terug naar de werkvoorraad 

***Expected***
laatste gegevens zijn bewaard (ookal heb ik niet expliciet de filtersfuncties opgeslagen

***Actual***
je moet weer opnieuw je kolomopties instellen.

**Comment by hansmarks** [comment]
Dat is geen bug, dat is gewoon (nog) niet geimplementeerd.

**Comment by andyverberne** [comment]
Er is nog geen consensus in het team dat dit een bug is ....

**Comment by robertverboom** [comment]
Kolommen blijven wel onthouden. Filters echter niet.

**Comment by robertverboom** [comment]
### Refinement 04-08:
- Filter instellingen opslaan in de sessionstorage
- toepassen op 7 werklijsten

**Comment by robertverboom** [comment]
test ok
