### ISSUE TITLE
BUG: Taken signalering geeft geen signalering

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1390]
***Steps to reproduce:***

1. maak een taak aan. 
2. Ken hem aan iemand toe
3. 

***Expected***
toegekende behandelaar krijgt een signalering

***Actual***
behandelaar krijgt geen signalering

**Comment by hansmarks** [comment]
Niet reproduceerbaar. Hertest OK.
