### ISSUE TITLE
Hoofdzaak met openstaande deelzaken kan gesloten worden

### ISSUE THREAD

**Issue by marcoatos** [NL-AMS-LOCGOV/zaakafhandelcomponent#1396]
Dit had opgelost moeten zijn in PolicyService in de methode valideerZaakAfsluiten.

Maar ik kon op develop een hoofdzaak met openstaande deelzaken afbreken.

**Comment by robertverboom** [comment]
snackbar dat zaak is gesloten wordt nog wel getoond.

**Comment by marcoatos** [comment]
Daar had ik issue 1411 al voor aangemaakt.
