### ISSUE TITLE
BUG: Niet mogelijk om te zoeken op tussenvoegsel bij het toevoegen van een initiator (Persoon)

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#1399]
***Steps to reproduce:***

1. Open een bestaande zaak die nog geen initiator heeft (Of maak een nieuwe aan)
2. Voeg een initiator toe bij de zaak en zoek op van der meijden
3. 

***Expected***
De persoon  Peter-Jan van der Meijden wordt gevonden

***Actual***
Er wordt geen persoon gevonden

**Comment by andyverberne** [comment]
Er is nu alleen een zoekveld "Geslachtsnaam". En deze zoekt op "Geslachtsnaam".
De Geslachtsnaam van "Peter-Jan van der Meijden" is "Meijden" en in voorvoegsel staat "van der" maar daarop wordt niet gezocht.
Dus dit is geen bug maar een feature

**Comment by robertverboom** [comment]
maak van geslachtsnaam, Achternaam en voeg in het zelfde veld tussenvoegsels toe

**Comment by robertverboom** [comment]
### Refinement 04-08:
Eerst uitzoeken of dit kan: 
- Zoekvelden kopieren wat beschikbaar is in de API 
- Geboortedatum achter BSN plaatsen
- Voorvoegsel veld voor Geslachtsnaam
