### ISSUE TITLE
BUG: Na afronden taak, kan je nog steeds bewerken

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#140]
***Steps to reproduce:***

1. Rond een taak af
2. bewerk een veld

***Expected***
Het kunnen bewerken van een taak zou niet meer mogen na het afronden van de taak. 

***Actual***
Krijgt een 500 error  omdat het geen Human task meer is

[https://app.zenhub.com/files/416646145/2c65273f-40f2-4e1b-9747-19600cbe57fa/download](https://app.zenhub.com/files/416646145/2c65273f-40f2-4e1b-9747-19600cbe57fa/download)

**Comment by andyverberne** [comment]
Deze speelt nu niet meer volgens mij.

**Comment by robertverboom** [comment]
Behandelaar en toelichting in bovenste vlak kan nog steeds bewerkt worden.

**Comment by andyverberne** [comment]
Besproken met @bartlukens-atos dat dit moet worden opgelost in het abstracte EditComponent door een boolean toe te voegen waarmee een component readonly kan worden gemaakt.
