### ISSUE TITLE
Mogelijkheid adres te noteren bij Contactpersonen - Bedrijf

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1400]
***Als*** behandelaar

***Wil ik*** adresgegevens bij contactpersonen van een bedrijf toe te voegen. 

***Zodat*** de schriftelijke correspondentie naar een penningmeester en niet naar adres van inschrijving van een bedrijf, vereniging, stichting oid kan worden gestuurd

***

### Acceptance criteria:
- zie ook WIJZ-246 https://support.dimpact.nl/jira/browse/WIJZ-246

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Dit hoort niet in de ZAC thuis, story naar PodiumD verplaatsen. Wellicht in Open Klant.
