### ISSUE TITLE
Toelichitng ontbreekt bij betrokkene

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1401]
***Steps to reproduce:***

1. Betrokkene toevoegen

***Expected***
Verwacht een toelichting bij in te vullen in sidepanel
Wordt in de historie weggeschreven als: Betrokkene toegevoegd: <toelichting van de gebruiker> 

***Actual***
Wordt geen optie geboden om toelichting in te vulllen

**Comment by robertverboom** [comment]
aantal gebruikte karakters op toelichting ontbreekt

**Comment by nl23727** [comment]
Kleine aanvulling: verplichte karakter van toelichting wordt niet goed afgewikkeld. Indien toelichting wordt leeggelaten, dan wordt de button Zoek toch enabled en gaat de persoon zoeken. Bij het selecteren van de persoon wordt vervolgens een error 400 teruggegeven. Beter is hier de button pas te enablen op het moment dat alle verplichte velden zijn ingevuld.

**Comment by jeroen-dekker** [comment]
Comment van Marc lijkt alleen van toepassing op de testserver. Lokaal werkt het naar behoren. Wellicht dat dit nog voor wat problemen zorgt bij het testen.
