### ISSUE TITLE
Snackbar wordt getoond bij mislukken van afronden zaak

### ISSUE THREAD

**Issue by marcoatos** [NL-AMS-LOCGOV/zaakafhandelcomponent#1411]
Bij het afronden van een zaak met openstaande deelzaken krijg je een fout melding, Na het sluiten van de foutmelding wordt de snackbar getoond dat de zaak gesloten is.

De zaak wordt niet gesloten vanwege de openstaande deelzaken, dus de snackbar hoeft niet getoond te worden.

**Comment by robertverboom** [comment]
test ok
