### ISSUE TITLE
BUG: Hoofdzaak mag je afbreken, ondanks deelzaak nog open is

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1412]
***Steps to reproduce:***

1. Koppel 2 zaken aan elkaar 
2. Breek de hoofdzaak af

***Expected***
mag neit omdat deelzaak nog gekoppeld is

***Actual***
kan hem gewoon afbreken

**Comment by marcoatos** [comment]
Issue was opgelost, maar de cloud build was voor een of andere reden niet goed gegaan, een simpele herstart van de build was genoeg en nu staat de fix op develop.
