### ISSUE TITLE
We hebben een low level functie nodig om UUIDs om te zetten in URLs: DEEL 2

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1413]

**Comment by bartlukens-atos** [comment]
Overal toepassen van de low level functie

**Comment by jeroen-dekker** [comment]
In https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1565 is ook een methode toegevoegd voor het ophalen van gekoppelde informatieobjecten aan een besluit. Daarvoor wordt de URI van het besluit in de back-end aangemaakt obv de UUID die uit de front-end wordt verstuurd. Dat zou met dit issue ook moeten worden omgeschreven.

**Comment by robertverboom** [comment]
### Refinement 22-09:
- Besluiten ook meenemen

**Comment by andyverberne** [comment]
Ticket voortgezet in #1659
