### ISSUE TITLE
Tab 'overige gegevens' verwijderen op zaakgegevenspagina

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1422]
Omdat we nu veel nieuwe tabs krijgen, graag niet gebruikte tabs verwijderen. In dit geval: Overige gegevens

**Comment by robertverboom** [comment]
evt niet gebruitke tabs verwijderen? Denk aan koppelen van zaak tab

**Comment by robertverboom** [comment]
### Refinement 04-08:
- Niet gebruikte tabs onderdrukken

**Comment by robertverboom** [comment]
Nu wordt alles onderdrukt. Als je een bag object toeveogd of een zaak koppelt, verwacht je een tabje. Deze worden nu niet getoond.

**Comment by jeroen-dekker** [comment]
Fix lijkt wel te werken, probleem ontstond doordat het koppelen van data aan een zaak stuk was. Is inmiddels gefixt, dus cannot reproduce.
