### ISSUE TITLE
BUG: Zaak kan niet afgebroken worden 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1425]
***Steps to reproduce:***

1. Ga naar zaak: https://zac.develop-public-service-platform.net/zaken/ZAAK-2022-0000001624
2. probeer deze af te breken
3. 

***Expected***
Zaak wordt afgebroken, of juiste foutmeldign wordt getoond

***Actual***
Eerste keer krijg je foutmelding:
(400) Title: Invalid input., Detail: Name: nonFieldErrors, Code: indicatiegebruiksrecht-unset, Reason: Er zijn gerelateerde informatieobjecten waarvoor `indicatieGebruiksrecht` nog niet gespecifieerd is. Je moet deze zetten voor je de zaak kan afsluiten.

Vervolgens de foutmelding: 
(400) Title: Invalid input., Detail: Name: zaak, Code: unique, Reason: Dit veld moet uniek zijn.

**Comment by jeroen-dekker** [comment]
De tweede foutmelding wordt veroorzaakt omdat de zaak in OpenZaak wel is afgesloten, maar volgens ZAC nog niet. Ik vermoed dat er in de logica van het afsluiten iets mis is gegaan waardoor er via de ZRCClient wel een resultaat op de zaak is gekomen in OpenZaak, maar de volledige afsluit-logica in ZAC niet is uitgevoerd, vanwege de eerste foutmelding in de beschrijving.

**Comment by jeroen-dekker** [comment]
Bij het toevoegen van een document wordt er een informatieobject aangemaakt waar de `indicatieGebruiksrecht` de waarde `true` heeft. Ik vermoed dat bij het *toevoegen* van een document dus niets fout gaat. Hoe dat zit bij het *aanmaken* van een document via SmartDocuments kan ik (nog) niet testen, maar ik vermoed dat daar wel eens het probleem vandaan kan komen.
