### ISSUE TITLE
Downloaden van het dossier(alle documenten) tijdens het behandelen van de zaak DEEL2

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1429]
Met werkgroep bespreken: 

- Naamgeving zip bestandsnaam: Zaaknummer als bestandsnaam zip
- Zip indeling qua folderstructuur (gaven aan documentrichting, echter bestaat dit in Openzaak niet) Kijken naar ontvangstdatum en verzenddatum. Hierin groeperen als ontvangen of verzonden document. Indien niet gevuld, deze documenten ook groeperen.
- Policy toevoegen (welke gebruikers mogen dit): Iedereen die de documenten mag zien, mag deze downloaden.
- Wat te doen met meerdere titels met dezelfde naam: Alle documenten downloaden en nummeren. 

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze user story is de functionaliteit van het downloaden van zaakdocumenten verbeterd door de geselecteerde documenten in het zip bestand te ordenen en te voorzien van de documentidentificatie.

***Belangrijkste functionaliteiten:***
- Gebruiker heeft na het downloaden van zaakdocumenten een zip bestand waarin de documenten per map zijn geordend op 'Inkomend', 'Uitgaand' en 'Intern'
- Gebruiker ziet in de naam van het document een combinatie van de bestandsnaam en de documentidentificatie

**Comment by robertverboom** [comment]
### Refinement 23-08:
- Folder per zaaknummer
In zo'n folder kijken naar datum: 
- Ontvangsdatum: inkomend
- Verzenddatum: uitgaand
- Geen datum bekend: intern

- Altijd documentindentificatie achter documentnaam zetten.

**Comment by robertverboom** [comment]
test ok

**Comment by CommonGroundGroningen** [comment]
**Gebruiker heeft na het downloaden van zaakdocumenten een zip bestand waarin de documenten per map zijn geordend op 'Inkomend', 'Uitgaand' en 'Intern'**
Test OK
**Gebruiker ziet in de naam van het document een combinatie van de bestandsnaam en de documentidentificatie**
Test OK
