### ISSUE TITLE
BUG: Toelichting en omschrijving worden niet direct opgepakt in de historie

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#143]
***Steps to reproduce:***

1. Wijzig de toelichting en omschrijving van een zaak
2. ga na historie tab

***Expected***
De aanpassing is zichtbaar

***Actual***
Een andere gebruiker (dmv websockets) ziet hem wel verschijnen. na refresh (F5) komt hij ook binnen. Echter komt de wijziging niet direct. 
(Bij veranderen van behandelaar gebeurt dit wel)

**Comment by hansmarks** [comment]
In overleg ook de websockets aangepast in die zin dat nu op de zaak-, taak- en document-view de listener met snackbar wordt gebruikt, omdat dit nu defacto de edit-schermen zijn geworden door de inline-edit mogelijkheden.

**Comment by robertverboom** [comment]
tet ok
