### ISSUE TITLE
Communicatiekanaal wordt niet gevuld bij het aanmaken van een zaak vanuit een e-formulier

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#1430]
Via het formulier evenementen een zaak aangemaakt. Hierbij geconstateerd dat het veld cummunicatiekanaal in GZAC niet wordt gevuld.

**Comment by robertverboom** [comment]
in VNG -referentielijsten een communicatiekanaal toeveoegen.

**Comment by robertverboom** [comment]
### Refinement 09-08:
- Naam van het kanaal hardcoderen: E-formulier
- Fout als 'E-formulier' niet bestaat
- Bij het editen op het scherm/starten nieuwe zaak E-formulier weglaten, tenzij dit al is ingevuld

**Comment by jeroen-dekker** [comment]
Met Robert besproken; het testen van het aanmaken van een zaak via de notificatie die binnenkomt vanuit Open Forms werkt op dit moment niet vanwege een recente wijziging. Pas als dat gefixt is, kan de oplossing van dit issue volledig getest worden.

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by HilbrandHurtak** [comment]
@robertverboom Met welk formulier kan dit in de acc worden getest. ( https://zac.accept-public-service-platform.net/startformulieren/ werk niet meer)

**Comment by robertverboom** [comment]
@HilbrandHurtak Op de acceptatie omgeving is het open-formulieren component niet geïnstalleerd. Dit ticket kan wel getest worden op de zandbak middels deze link: https://open-forms.zandbak-public-service-platform.net/melding-klein-evenement

Verplichte velden invullen op het formulier. Er wordt vervolgens een zaak aangemaakt. In de werkvoorraad zal de zaak verschijnen.

**Comment by HilbrandHurtak** [comment]
@robertverboom. Prima ik ga het daar dan even testen

**Comment by HilbrandHurtak** [comment]
Test op onderdeel :
Kanaal - OK
Omschrijving: OK
Toelichting: OK

Geen test kunnen uitvoeren t.a.v. de overige data uit het formulier die dan als data bij de zaak beschikbaar is.
 
![image](https://user-images.githubusercontent.com/96229645/201061499-176e0f42-aec2-4dce-9744-de35dee95acf.png)
