### ISSUE TITLE
ACCEPTATIE BUG: Bij interne taak kan de inhoud van de radio buttons voor de adviseurs niet worden geconfigureerd

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#1433]
In de acceptatiecriteria stond het volgende:
Bij een adviestaak moet uit een lijstje (**die te configureren is**) de uitkomst van het advies op hoofdlijnen kunnen worden aangegeven (bijvoorbeeld positief, positief onder voorwaarde, negatief, negatief tenzij, niet beoordeeld)

Nu is het lijst niet te wijzigen bij de standaard configuratie van de proces parameters

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/c3036fdf-95e0-43b1-aa73-8ae3912f4f10)

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/ca0fcb38-4730-4248-86e8-1b56cd32926e)

**Comment by robertverboom** [comment]
### Refinement 16-08:
- tabel met een code, een wijzigbare naam en een vinkje of het een systeemtabel is. 
- detailtabel met een wijzigbare waarde en naam van de waarde
- er komt een relatietabel bij, om de tabel te koppelen aan de taken in de afhandelparameters (2 fk's en een veldnaam)
- scherm nodig om de tabellen te editen: referentietabelbeheer 
- In de zaakafhandelparameters moet in de taak advies intern een tabel gekozen worden voor de waarde. Default is dat de tabel met naam: Advies intern
- In de flywayscript wordt de tabel advies intern alvast gemaakt en ingevuld. Dit is een systeemtabel
- In de editer kan je de code nooit aanpassen (dus ook niet verwijderen), wel de naam en waardes wijzigen als het een systeemtabel is
- De optie 'tussentijds opslaan' controleren of het goed gaat bij verdwenen waardes

**Comment by robertverboom** [comment]
Nog kijken of wij hem kunnen splitsen en nadenken over aanpassingen op het formulier zelf.

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by robertverboom** [comment]
De bedoeling is dat er een referentietabel gemaakt wordt in het beheer stuk (wat je volgens mij gedaan hebt), echter moet je dan ook de goede tabel bij de taak advies intern installeren. De acties die zijn uitgevoerd bij de zaakafhandelparameters moeten inderdaad worden opgeslagen. 

Bij een ander zaaktype wil je wellicht andere antwoordopties voor het advies. Vandaar dat je hem nog moet aangeven bij de zaakafhandelparameters

**Comment by HilbrandHurtak** [comment]
@robertverboom Hoi Robert

Helder verhaal. Misschien een tip om bij zaakafhandelparameters dan een signaal te krijgen dat er ergens iets is gewijzigd en dat dit pas actief wordt  als de wijziging wordt opgeslagen. Nu wordt het niet actief.
