### ISSUE TITLE
ACCEPTATIE BUG: Taak heeft geen fatale datum

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#1438]
Volgens de acceptatiecriteria heeft elke taak een fatale datum. Bij de gerealiseerde functionaliteit staat dit ook zo

Dit veld ontbreekt echter. Getest met aanvullende informatie opvragen en interne adviestaak

![image.png](https://ima![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/d8ea54c3-0e7d-4911-8ddc-9ab6482fcd77)ges.zenhubusercontent.com/621fbac8fb54e5427009eefc/31115de7-306e-436b-8b20-57a339d9a0a9)

**Comment by JosDimpact** [comment]
Dit 'fatale datum' veld is per ongeluk bij de acceptancecriteria mee gecopy-paste.
Vandaag voorgelegd aan de WG refinement en acceptatie. Daar was geen gemeente die dit veld op dit moment actief gebruikt. 
Ik heb op SAM de vraag nu aan alle (meelezende) gemeenten gesteld, omdat het vermoeden is dat dit nergens gebruikt wordt. Vooralsnog kan dit issue nog wel even 'on hold' blijven in afwachting van een conclusie.

**Comment by GertrudeKampherbeek** [comment]
Antwoord is: ja maar de fatale bij de taak dan wel optioneel zijn

**Comment by RoyBuis** [comment]
### Refinement 15-11

Een fatale datum bij een taak bestaat niet. Bespreken met Sander wat een goede naam is voor de doeldatum die nu beschikbaar is.

**Comment by Snijhuis** [comment]
WG R&A 16-11
Een tweede datum toevoegen aan taken lijkt ons niet de gewenste oplossing vanuit de generieke processen. Tevens vergt dit een grotere aanpassing dan vooraf bedacht (meer impact).

Voorstel is:
Het veld 'streefdatum' dat nu beschikbaar is voor een taak wordt nu gevuld op basis van:
Aanmaakdatum taak + streefdatum uit zaakafhandel-parameters (per ZT).
Dit veld zouden we kunnen hernoemen naar 'fatale datum'. Een taak heeft dan een fatale datum of helemaal geen datum. In principe zijn we bezig met generieke zaakafhandeling dus zou een optionele fatale datum voldoende moeten zijn.
NB. Eventueel zouden we wel meerdere notificaties kunnen laten verzenden/ tonen op deze fatale datum. (andere story)

1. Wat vinden jullie van deze oplossing?
2. Is de term fatale datum een goede term of zijn er andere suggesties?

**Comment by VictorTielenius** [comment]
Streefdatum en Fatale datum van de taak is nu per taak in te richten (optioneel) in de e-Suite. Alleen Fatale datum taak zou ook voldoende zijn.
Wel per taak in te richten (bv. Taak advies 5 dagen na starten taak, of geen fatale datum bij een taak)

**Comment by Snijhuis** [comment]
WG R&A 23-11
Streef kan vervangen worden door de fatale datum. Veld moet wel optioneel zijn.

**Comment by RoyBuis** [comment]
### Refinement 24-11

Te realiseren

- Taak blijft 1 doorlooptijd houden, huidige streefdatum vervangen voor fatale datum
- 'gewenste doorlooptijd' vervangen door 'doorlooptijd' in zap
- 'Mijn taak heeft de streefdatum bereikt' vervangen door 'Mijn taak heeft de fatale datum bereikt' in signaleringinstellingen
- naamgeving aanpassen in oa Solr index, domeinobjecten, REST taken, typescript taken, taakhistorie. Overal aanpassen naar 'fatale datum'

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Test ok
