### ISSUE TITLE
Websockets op de notities

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#144]
***Steps to reproduce:***

1. Gebruik 2 verschillende accounts
2. Voeg een notitie toe

***Expected***
Notitie wordt op ander account ook getoond

***Actual***
pas na een refresh is de notitie zichtbaar

**Comment by andyverberne** [comment]
Op dit moment is er geen websocket ondersteuning voor het aanpassen van Notities.
Ik zie dit dan ook niet als een bug. Deze User Story moet refined worden.

**Comment by RoyBuis** [comment]
Refinement 20 december:
Websockets neit nodig voor notities, komt zelden voor dat mdws aan de zelfde zaak werken
