### ISSUE TITLE
BUG: Geen websockets op het verdelen van zaken en taken

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#145]
***Steps to reproduce:***

1. gebruik 2 accounts tegelijkertijd (en 2 browsers) 
2. verdeel een zaak/taak

***Expected***
op het andere account zie je de wijziging

***Actual***
pas na refresh komt de wijziging in beeld.

_Dit speelt ook voor 'aan jezelf toekennen'. (Dan komt er geen update met het andere account)_

**Comment by andyverberne** [comment]
Ik heb dit net getest op develop en dat werkt. Het werkt alleen wanneer je in browser 1 de zaak verdeelt en in browser 2 naar de zaak details kijkt van de zaak die net verdeelt is. Als je in browser 2 naar de lijst van zaken kijkt dan wordt die lijst niet ge-update. Dat is zoals het zou moeten werken

**Comment by robertverboom** [comment]
issue speelt inderdaad alleen op de werklijst. maar als dit zo hoort dan is dit ok!
