### ISSUE TITLE
ACCEPTATIE BUG: Gebruiker kan geen extra metadata toevoegen

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1457]
**Gebruikersrol:** ?
**Device:** Laptop
**OS:** Windows 10 Enterprise, 20H2
**Browser:** Chrome
**Versie:** 95.0.4638.69

**Issuenummer**
#330

**Beschrijf de bug**
Acceptatie criterium 5: Gebruiker kan metadata toevoegen. De gebruiker kan echter alleen de voorgestelde metadata invullen, niet toevoegen.

**Te reproduceren:**
1. Zaak aanmaken
2. Document toevoegen
of
1. Zaak openen
2. Document openen

**Verwacht gedrag**
Een knop om metadata toe te voegen 

**Daadwerkelijk gedrag**
Zie printscreens.

**Screenshots**
Zie printscreens.

**Foutmelding/Log tekst**
-

**Aanvullende informatie**
-

**Comment by CommonGroundGroningen** [comment]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/520f7a87-b794-4098-a165-d0b8228411dd)

**Comment by CommonGroundGroningen** [comment]
In bovenstaande printscreen zijn geen mogelijkheden om metadata toe te voegen. Er is geen button beschikbaar.

**Comment by CommonGroundGroningen** [comment]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/bdbb36f7-bbff-420f-80e9-4ded0124ce07)

**Comment by CommonGroundGroningen** [comment]
In bovenstaand scherm is geen button beschikbaar om metadata toe te voegen.

**Comment by Snijhuis** [comment]
@HilbrandHurtak OpenZaak biedt op dit moment nog geen extra velden aan om als metadata vast te leggen bij documenten. Welke mis je? Of gaat het juist om dynamische metadata?

Hoe dan ook, dit kan nu niet opgelost worden.

**Comment by HilbrandHurtak** [comment]
@Snijhuis . In Epic 10A wordt de noodzakelijke metadata verder uitgewerkt. In deze user story ging het om metadata die ook moet kunnen worden gewijzigd. Nadat een document is toegevoegd kan de metadata niet meer worden bewerkt(bijvoorbeeld wijzigen status of Auteur)

**Comment by HilbrandHurtak** [comment]
Voorbeeld huidige e-Suite. Ontbrekende en foutieve metadata bij een document kan worden gewijzigd. In de GZAC bestaat deze optie niet:
![image](https://user-images.githubusercontent.com/96229645/187605741-264a4d99-2282-4497-9197-084eea654a81.png)

Knop wijzigen geeft deze mogelijkheden(wijzigen en toevoegen ontbrekende metadata)
![image](https://user-images.githubusercontent.com/96229645/187605885-da8a807e-8ec8-40ee-b3cb-2eea36d044a3.png)

**Comment by Snijhuis** [comment]
@HilbrandHurtak Ik neem deze nog even mee in overleg met Atos straks. Je moet wel degelijk metadata aan kunnen passen (maar kan met rechten te maken hebben dat het nu niet lukt). Elke aanpassing aan metadata betekent wel een nieuwe versie van het informatieobject, dat dwingt Open Zaak af.

**Comment by HilbrandHurtak** [comment]
@Snijhuis . Is goed ik hoor de uitkomst dan wel. Heb net even weer gekeken en zag wel extra functionaliteit bij het document(nu ook bewerken)

![image](https://user-images.githubusercontent.com/96229645/187649904-332f8307-a188-4ae7-9d85-fcffefa44564.png)

Volgens mij kan ik alleen het document bewerken en niet de metadata.

**Comment by RoyBuis** [comment]
Om de metadata van een document aan te passen kan de knop 'Nieuwe versie' gebruikt worden. Dit kan alleen wanneer een document niet definitief is. De Documenten API dwingt af dat bij iedere wijziging van een document, inhoudelijk of metadata, een nieuwe versie ontstaat.
De 'Bewerken' knop in het ZAC maakt het mogelijk om een Word, Excel of Powerpoint document inhoudelijk aan te passen. In dit geval wordt uiteraard ook een nieuwe versie aangemaakt.

**Comment by GertrudeKampherbeek** [comment]
wordt opnieuw getest

**Comment by HilbrandHurtak** [comment]
Opnieuw getest. Via de optie Nieuwe versie kan de metadata worden gewijzigd. De knop bewerken blijft ook zichtbaar als het document de status definitief heeft. Ook bij definitieve documenten kon de metadata worden aangepast en werd er een nieuwe versie gemaakt. Ik ga er vanuit dat dit is gelukt omdat deze functionaliteit nog niet achter een specifieke autorisatie zit. Dat zou wel moeten

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/f203771a-0ffc-4cd2-b410-85992f47202f)
