### ISSUE TITLE
ACCEPTATIE BUG: Ontvangstdatum/verzenddatum moet niet worden overgenomen

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1458]
**Gebruikersrol:** ?
**Device:** Laptop
**OS:** Windows 10 Enterprise, 20H2
**Browser:** Chrome
**Versie:** 95.0.4638.69

**Issuenummer**
#330

**Beschrijf de bug**
Bij het toevoegen van meerdere documenten, wordt de metadata van het vorige document 'gekopieerd'. Dit blijft als default staan in de invoer velden. Dit voldoet aan AC3: "... volgend document worden toegevoegd waarbij de ingevulde metadata van het vorige document worden overgenomen." Maar door het invoeren van een ontvangstdatum, blijft de status 'uitgegrijst'. Het verwijderen van Ontvangstdatum is noodzakelijk om Status aan te kunnen passen. Dit voldoet niet aan AC1: "Gebruiker moet de actie kunnen uitvoeren met zo min mogelijk klikken". 

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1. Zaak aanmaken 
2. Document toevoegen
3. Invullen megadata inclusief de ontvangstdatum
4. Nog een document toevoegen

**Verwacht gedrag**
Omdat zo min mogelijk klikken prioriteit lijkt, zou de ontvangstdatum niet ingevuld moeten worden zodat de status direct aanpasbaar is.

**Daadwerkelijk gedrag**
De ontvangstdatum wordt gevuld zodat de status niet aanpasbaar is. Om de status aan te kunnen passen moet eerst de ontvangstdatum verwijderd worden.

**Screenshots**
Zie hieronder.

**Foutmelding/Log tekst**
-

**Aanvullende informatie**
-

**Comment by CommonGroundGroningen** [comment]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/201e50ff-c20a-4cc8-ab4b-77f81de06617)

**Comment by robertverboom** [comment]
### Refinement 16-08:
- Na toevoegen van meerdere documenten niet de ontvangstdatum of verzenddatum invullen, zodat andere velden weer enabled worden

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Bij toevoegen document en dan "Nog een document toevoegen" is de Ontvangstdatum of Verzenddatum leeg bij volgende document: OK
