### ISSUE TITLE
Bepalen archiefactietermijn op basis van resultaat i.c.m. besluit met begin en einddatum

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1473]
***Als*** Zaakbehandelaar

***Wil ik*** een zaak goed kunnen afhandelen in ZAC en de juiste archiefactietermijn kunnen bepalen op basis van resultaat en begin/einddatum van een besluit

***Zodat*** Zaken met de juiste bewaar/vernietigingsdatum worden vastgelegd in Open Zaak

***

### Acceptance criteria:
- Zaakbehandelaar moet een besluit kunnen vastleggen bij een zaak --> Voorstel is een taak (naam: Vatsleggen besluit') met daarin de volgende velden:
1. **label:** Selecteer besluittype: **Type veld:** dropdownlijst met de aan het zaaktype gekoppelde besluittype
2a. **Label:** Ingangsdatum besluit: **Type veld:** Datumveld (verplicht)
2b: **Label:** Vervaldatum besluit: **Type veld:** Datumveld (verplicht)
3. **Label:** Selecteer besluitdocument: **Type veld:** Document selecteer grid (optioneel)
4. In linkeractiemenu bij de taak ook de document toevoegen en document maken actieknoppen tonen

NB. Wanneer iemand kiest voor zaak afhandelen als actie, en men kiest voor een resultaat waarbij een besluit nodig is voor het berekenen van de archiefactietrmijn, dan een melding tonen aan gebruiker dat deze taak 'Vastleggen besluit' eerst moet worden doorlopen (als deze taak dus nog niet is doorlopen).

Eventueel kan de knop 'Zaak afhandelen' in dat geval 'Vastleggen besluit' worden in de zaakafhandeldialog. Bespreken met team wat eventuele oplossingsrichtingen kunnen zijn.

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
1473
### Gerealiseerd
**Let op: na de oplevering van deze story zijn er nieuwe stories (#1565, #1570, #1689 en #1886) gerealiseerd die deze story hebben beïnvloed. Deze stories zijn meegenomen in de 'Gerealiseerd' beschrijving.**
_Omschrijving van de op te leveren functionaliteit in deze story_
De uitkomst van de behandeling van een zaak kan in de 'In behandeling fase' als zaakbesluit worden vastgelegd. Bij dit besluit kan ook het document waarin (een deel van) het besluit is beschreven worden toegevoegd. Het is mogelijk om meerdere besluiten bij een zaak vast te leggen en om meerdere documenten aan een besluit toe te voegen.
Of een besluit kan worden vastgelegd is afhankelijk van of dit is ingesteld bij het zaaktype. In het zaaktype kan ook zijn ingesteld dat een besluit verplicht moet worden vastgelegd als bij die zaak een bepaald resultaattype wordt vastgelegd. In dat resultaat kan namelijk vastliggen dat de bewaartermijn pas in mag gaan zodra de ingangs- of vervaldatum van dat besluit is bereikt.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met de actie [Besluit vastleggen] een besluit bij een zaak vastleggen. Het is mogelijk om meerdere besluiten bij een zaak vast te leggen.
- Gebruiker kiest bij het vastleggen van het besluit ook het resultaat dat de zaak krijgt. Afhankelijk van het gekozen resultaat moet de vervaldatum verplicht ingevuld worden.
- Gebruiker kan een document waarin (een deel van) het besluit is beschreven toevoegen aan het besluit door het document te selecteren in het besluitpanel. Dit is alleen mogelijk voor documenten van een documenttype dat in de zaaktypecatalogus aan het gekozen besluittype is gekoppeld. Het is mogelijk om meerdere documenten aan een besluit toe te voegen.
- Gebruiker kan met het potlood icoon op het besluit de gegevens van het besluit wijzigen. Het besluittype kan niet gewijzigd worden.
- Gebruiker wordt bij het afhandelen van de zaak met een resultaat waar in vastligt dat de ingangs- of vervaldatum wordt gebruikt om de brondatum te berekenen dan wordt de gebruiker doorgestuurd naar het besluitpanel om deze alsnog vast te leggen.
- Het vastleggen of wijzigen van een besluit wordt vastgelegd in de historie van het besluit

**Comment by RoyBuis** [comment]
### Refinement 18-8

Of een besluit vastgelegd moet zijn is te herleiden uit de afleidingswijze brondatum van het resultaat, die moet dan 'Ingangsdatum besluit' of 'Vervaldatum besluit' zijn.

Te realiseren
Actieknop 'Vastleggen besluit' in het sidepanel, deze bevat
- resultaat (keuze uit de gekoppelde resultaattypen)
- besluittype (keuze uit de aan de zaaktype gekoppelde geldige besluittypen)
- bronorganisatie is standaard rsin van gemeente (niet op scherm tonen)
- datum is standaard systeemdatum vandaag (niet op scherm tonen)
- toelichting, tekstveld met max grootte 1000 karakters, optioneel
- ingangsdatum, verplicht datumveld, default leeg, mag in verleden liggen
- vervaldatum, verplicht datumveld o.b.v. gekozen resultaattype als afleidingswijze 'Vervaldatum besluit' is, > ingangsdatum
Gebruiker mag 1 besluit bij een zaak vastleggen. 

Een document koppelen aan besluit komt in latere versie (deel 2), moet nog nader uitgezocht worden

Zaak afhandelen dialog wordt uitgebreid:
Als een besluit is vastgelegd:
- het bij het besluit gekozen resultaat wordt disabled getoond samen met het besluit, gebruiker kan alleen toelichting nog invullen

Als een besluit niet is vastgelegd:
- als de gebruiker in de 'zaak afhandelen' actie een resultaat kiest waarbij een besluit verplicht is dan knop 'zaak afhandelen' wizjigen in 'vastelggen besluit' waardoor gebruiker naar vastleggen besluit actie wordt gestuurd.

Bij een heropende zaak is functionaliteit voor verwijderen of wijzigen besluit nodig. Dit wordt later in andere story uitgewerkt.

**Comment by CommonGroundGroningen** [comment]
Gebruiker kiest bij het vastleggen van het besluit ook het resultaat dat de zaak krijgt. Afhankelijk van het gekozen resultaat moet de vervaldatum verplicht ingevuld worden.
**Akkoord**
Het vastleggen of wijzigen van een besluit wordt vastgelegd in de historie van het besluit
**Akkoord**

**Comment by CommonGroundGroningen** [comment]
Onderliggende tickets zijn getest.

Het onderstaande is niet te testen omdat dergelijke resultaten niet zijn ingericht.
**Gebruiker wordt bij het afhandelen van de zaak met een resultaat waar in vastligt dat de ingangs- of vervaldatum wordt gebruikt om de brondatum te berekenen dan wordt de gebruiker doorgestuurd naar het besluitpanel om deze alsnog vast te leggen.**

Voor de rest akkoord

**Comment by CommonGroundGroningen** [comment]
Nieuw kaartje gemaakt van dit issue #2515.

**Comment by CommonGroundGroningen** [comment]
#2515 is afgesloten
