### ISSUE TITLE
BUG: Na hoofdzaak verkeerd afhandelen kan de gebruiker niks

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1488]
***Steps to reproduce:***

1. Koppel 2 zaken aan elkaar 
2. Laat de deelzaak open (status: in behandeling/intake)
3. probeer de hoofdzaak af te ronden

***Expected***
na sluiten van de foutmelding kan je de pop-up sluiten, door op bijv annuleren te drukken. 

***Actual***
Pop-up blijft staan en pas na een hardrefresh kan de gebruiker weer verder.

**Comment by jeroen-dekker** [comment]
Lijkt niet reproduceerbaar op dev en lokaal, misschien onovereenkomstigheid tussen zac op dev en acceptatie?

**Comment by jeroen-dekker** [comment]
Even met Marco besproken of het het waard is om hiervoor het generieke `dialog`-component te gebruiken, om te voorkomen dat er in de toekomst ook op twee plekken fixes moeten worden toegevoegd. Dat lijkt de moeite niet waard, helemaal aangezien de uiteindelijke fix in het bestaande component zo simpel is, dus die is doorgevoerd.
