### ISSUE TITLE
USER STORY: Naamgeving van Error meldingen 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#149]
***Als*** medewerker

***Wil ik*** weten wat ik moet doen bij een bepaalde melding

***Zodat*** ik weet welke input ik dan wel moet geven 

***

### Acceptance criteria:
- Wordt er aangegeven wat dan wel gedaan moet worden? 
- Verplichte velden
- Volgens de WCAG van de overheid

***
### Prioriteit

-  Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Wanneer de gebruiker een veld verkeerd gebruikt, wordt met rode tekst uitgelegd wat de gebruiker wel moet doen.

***Belangrijkste functionaliteiten:***
- Gebruik gemaakt van de WCAG richtlijnen

**Comment by robertverboom** [comment]
Aanmaken zaak: 
- Zaaktype
- Startdatum

taak startformulier: 
- toelichting

taak behandelformulier: 
- toelichting

**Comment by RoyBuis** [comment]
Refinement 23 december:

- Bij verplichte velden de melding die nu in de e-Suite wordt gebruikt overnemen
- Bij andere meldingen ook uitgaan van e-Suite
- Naam van het veld waar de fout is gemaakt opnemen in de foutmelding

**Comment by hansmarks** [comment]
Geimplementeerd voor alle validatie-fouten die op dit moment kunnen optreden. Als volgt:
-   Het {{label}}-veld is niet ingevuld. Vul de vereiste gegevens in!
-   Het {{label}}-veld bevat een te kleine waarde. Vul minimaal {{min}} in!
-   Het {{label}}-veld bevat een te grote waarde. Vul maximaal {{max}} in!
-   Het {{label}}-veld bevat een te korte waarde. Gebruik minimaal {{requiredLength}} tekens!
-   Het {{label}}-veld bevat een te lange waarde. Gebruik maximaal {{requiredLength}} tekens!
-   Het {{label}}-veld bevat een ongeldig E-Mailadres. Gebruik het voorbeeld@example.com formaat!
-   Het {{label}}-veld bevat een ongeldige waarde. Gebruik het {{requiredPattern}} formaat!
(Waarbij ook het in de melding genoemde label netjes vertaald wordt.)

Het uitbreiden met meldingen voor andere/toekomstige kan op dezelfde plaats gebeuren.

**Comment by andyverberne** [comment]
Nu moet overal die translate service geïnjecteerd worden.
Was het niet beter geweest een FormBuilderService te maken die overal geïnjecteerd wordt waar nu ook de TranslateService geïnjecteerd wordt en dan de TranslateService te injecteren in de FormBuilderService?

**Comment by nl23727** [comment]
Bij het invullen van een verkeerd formaat datum in een Startdatum veld op een Zaakaanmaken scherm, bijvoorbeeld 00-01-2022 wordt de validatiemelding: Het Startdatum-veld is niet ingevuld. Vul de vereiste gegevens in!
Verwachting is dat hier een melding komt te staan zoals "Er is een ongeldige datum ingevoerd in het veld Startdatum"

Voor het veld Registratiedatum speelt een iets ander issue: indien hier een ongeldig formaat datum wordt ingevuld, ontbreekt er een validatiemelding. Verwachting is dat hier een soortgelijke melding komt te staan als bij de Startdatum

**Comment by VictorTielenius** [comment]
Akkoord
