### ISSUE TITLE
Wijzigen zaaktype

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1497]
***Als*** kwaliteitsmedewerker of medewerker DIV 

***Wil ik*** een zaaktype kunnen wijzigen waarbij het zaaknummer gelijk blijft en documenten worden overgezet. 

***Zodat*** de fouten bij verkeerd gekozen zaaktype hersteld kan worden zodat de kwaliteit van registratie en informatie beheer op orde is

***

### Acceptance criteria:
- zie WIJZ-165/ESUITEXT-6266
- zie WIJZ-503/ESUITEXT-10670

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by VictorTielenius** [comment]
Zaaktype wijzigen wordt nu geregeld gebruikt en wens is om dit ook in ZAC te kunnen,
