### ISSUE TITLE
6B.7.X Betrokkenen toevoegen aan zaak

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#150]
Epic voor functionaliteit rondom betrokkenen toevoegen aan zaak (Persoon/organisaties)
NB: Basisregistraties zijn hiervoor nodig

**Comment by GertrudeKampherbeek** [comment]
- #172 
- #173 
- #252 
- #252

**Comment by RoyBuis** [comment]
### Refinement KM, RB en RV
Stories zijn gerealiseerd. Eventuele openstaande stories gaan als losse stories verder.
