### ISSUE TITLE
US: Aanmaken zaak scherm - doorontwikkeling

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1502]
N.a.v. het testen van het handmatig aanmaken van zaken (o.a. #287 ) de volgende doorontwikkelwensen:

Zaak aanmaken
1. Registratiedatum is altijd het moment (datum + tijd) van moment van registeren (hoeft niet getoond te worden bij zaak aanmaken scherm of tonen en uitgrijzen/disabled)
2. Initiële groep (zoals ingericht bij zaakafhandelparameters) tonen na keuze zaaktype.
3. Groep moet aan te passen zijn
4. Directe toewijzing aan medewerker ook toestaan in zaak aanmaken scherm 
NB - werking van 3 en 4 gelijk aan toewijzen functionaliteit vanuit werklijst? 

Overige gegevens

6. Communicatiekanaal: verplicht maken. Default nader bepalen (waarschijnlijk gebruikersinstelling)
7. Vertrouwelijkheidsaanduiding: verplicht maken. Default wellicht later bepalen (ook navragen bij WG Informatiebeheer)
8. Omschrijving: verplicht maken
9. Toelichting: mag optioneel blijven. (geen actie vereist)

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In een eerdere user story is het aanmaken van een zaak in de ZAC opgeleverd. In deze story is de functionaliteit van het 'Zaak aanmaken' scherm verfijnd door velden toe te voegen, velden weg te halen en de specificaties van velden te verbeteren.

***Belangrijkste functionaliteiten:***
N.v.t., de functionaliteit van het aanmaken van een zaak is ongewijzigd, de UI is hierbij aangepast

**Comment by bartlukens-atos** [comment]
- Registratiedatum niet tonen
- Bij wisselen zaaktype, groep overnemen en medewerker wissen
- Kopje boven toekenningsgegevens "Zaaktoewijzing"
- Letter tellertje bij omschrijving toevoegen

**Comment by HilbrandHurtak** [comment]
Test ok

**Comment by HilbrandHurtak** [comment]
Test ok
