### ISSUE TITLE
ACCEPTATIE BUG: Optionele velden verplicht maken bij vastleggen/wijzigen communicatiekanaal bij een zaak

### ISSUE THREAD

**Issue by JosDimpact** [NL-AMS-LOCGOV/zaakafhandelcomponent#1506]
**Gebruikersrol:** Zaakbehandelaar
**Device:** Desktop
**OS:** Win10
**Browser:** Any
**Versie:**nvt

**Issuenummer**
#410 

**Beschrijf de bug**
In User story #410, is een oplossing gemaakt voor het wijzigen van een communicatiekanaal, maar (we hebben in de werkgroep de uitkomst besproken en) we vinden dat deze te vrijblijvend is ingericht, hetgeen zal leiden tot problemen met de acceptatietests door informatie beheerders.
Bij aanmaken van de zaak moet het kanaal verplicht zijn.
Bij het wijzigen van de zaak moet de reden verplicht zijn.

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1. Maak een zaak aan (dit kan nu nog onterecht zonder kanaal)
2. Wijzig het kanaal (dit kan nu nog onterecht zonder reden)

**Comment by VictorTielenius** [comment]
communicatiekanaal bij aanmaken zaak nu verplicht. En in de aangemaakte zaak te wijzigen (incl. Reden en dit komt bij de historie)
