### ISSUE TITLE
7.8.2 mailen met voor gedefinieerde mailadressen

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1507]
***Als*** zaakbehandelaar 

***Wil ik*** een document kunnen mailen met als afzender een algemeen mailadres, bv gemeente@emmen.nl

***Zodat*** ik op een veilige manier kan mailen zonder dat mijn eigen mailadres bekend gaat worden bij burgers/bedrijven. 

***

### Acceptance criteria:
- lijst met te gebruiken mailadressen moet door functioneel beheer kunnen worden gemaakt.

- gebruikers moeten uit de lijst met mailadressen kunnen kiezen welke de afzender van de mail is

- het mailverkeer moet veilig verlopen via ?

- deze manier van mailadressen beschikbaar stellen moet ook kunnen worden ingezet wanneer mails direct vanuit een proces worden gemaild

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Duplicaat, issue wordt gesloten.
