### ISSUE TITLE
6B.8.X Documenten toevoegen aan zaak

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#151]
Epic voor toevoegen van documenten aan zaak (vanuit de zaak zelf)
NB. Overlap met Epics voor Documenten (volgen nog)

**Comment by Snijhuis** [comment]
Wordt inhoudelijk opgepakt in Epic documenten

**Comment by RoyBuis** [comment]
### Refinement KM, RB en RV
Niet meer nodig
