### ISSUE TITLE
Reden tonen bij opschorten, hervatten en verlengen in de historie

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1521]
Als Zaakbehandelaar

Wil ik redenen voor opschorten, verlengen en hervatten terug vinden in de historie

Zodat ik de reden kan terug vinden in het Zaakafhandelcomponent

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een zaak kan worden opgeschort en later worden hervat, zie #175 . Daarnaast kan een zaak worden verlengd, zie #176 . Bij deze handelingen is het verplicht om een reden in te vullen. Deze reden wordt als toelichting in de regel van de zaakhistorie opgenomen, voorafgegaan met de handeling waarvoor de reden is ingevuld, bijvoorbeeld: Hervatting: _ingevulde reden_

***Belangrijkste functionaliteiten:***
nvt

**Comment by RoyBuis** [comment]
### Refinement 30-8

Te realiseren:
- De reden die wordt opgegeven bij opschorten, hervatten, verlengen en aanpassen streefdatum tonen als toelichting in de historie
- opmaak in historie: bijv 'opschorten: _reden opschorten_'

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
@GertrudeKampherbeek ik was begonnen met het testen van de oorspronkelijke tickets. Helaas was daar de info van de refining niet in verwerkt. Ik heb inmiddels de volgende tickets achterhaald:
#175
#176
#1703
#1521
#1848

Tevens heb ik nog een document gevonden waarin je duidelijk het verschil aangeeft t.a.v. verlengen(is dus verdagen) en opschorting en wat vragen stelt over de berekening van de termijnen en de eventuele instelbaarheid per zaaktype.

Gezien je rol bij het refinen lijkt het me verstandig dat jij ook het testen doet. Ik heb het volgende op de zandbak geconstateerd en in de tickets bijgewerkt:

Optie Verlengen op de zandbak doet het niet(aantal dagen mag niet hoger zijn dan 0). Roy pakt dit al op
Op de acc doet verlengen het wel ( bij de  ZAAK-2023-0000000004). Je kunt **oneindig** vaak verlengen. Label verlenging wordt netjes gezet.

Optie Opschorten op de zandbak kan 1 keer worden gekozen en pakt de laatste streef en fatale datum (dus ook nadat je deze een paar keer via verlengen hebt aangepast). Label Opschorten wordt getoond. Alleen optie 'Hervatten' is nog te selecteren.  Na hervatten van de zaak is de knop Opschorting niet meet te selecteren en geeft een duidelijke melding dat dit maar 1 keer mag. De knop Verlengen is weer te selecteren. Je kunt daarna weer eindeloos verlengen

gr 
Hilbrand

**Comment by Sevdiya** [comment]
Reden / toelichting verdageln/verlengen/opschorten wordt getoond in tabblad historie.
