### ISSUE TITLE
BUG: Optie in communicatiekanaal en vertrouwelijkheidaanduiding leeg te laten mag weg

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1527]
***Steps to reproduce:***

1. maak een zaak aan
2. Kies optie communicatiekanaal.-geen- 
3. Kies optie -geen vertrouwelijksheidsaanduiding -

***Expected***
Gezien deze nu verplicht zijn, mag je deze opties niet meer zien

***Actual***
beide opties zijn nog zichtbaar bij het kiezen van een vertrouwelijkheidsaanduiding en communicatiekanaal op de zaakgegevenspagina

**Comment by jeroen-dekker** [comment]
Ik kan hem lokaal niet reproduceren, ik vermoed dat hier door caching o.i.d. een probleem ontstaat. Dat is ook aan de hand van de code te bevestigen.

Beide de `vertrouwlijkheidsaanduiding` (https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/pull/1512/files#diff-e8053199587909e95a7ae3b336b2a4bd4df4a22f6ddc529c4c93d1c81ee0526aR121) en `communicatiekanaal` (https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/pull/1512/files#diff-e8053199587909e95a7ae3b336b2a4bd4df4a22f6ddc529c4c93d1c81ee0526aR114) invoervelden zijn verplicht geworden.

In de abstracte klasse `AbstractFormFieldBuilder` wordt de waarde `required` van de `formField` (`AbstractFormField`) op `true` geset door deze `validators` methode.

In het `select`-component wat uiteindelijk wordt getoond voor beide dropdowns wordt de aanwezigheid van de `-geen-`-optie ook bepaald a.d.h.v. deze waarde. De opties zouden dus helemaal niet getoond moeten kunnen worden.

Ik denk dat deze bug gesloten kan worden.

**Comment by robertverboom** [comment]
speelt op develop nog steeds. Ook bij @hansmarks lokaal gezien.
