### ISSUE TITLE
EPIC: IAM voor het hele platform

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1538]
Paar user stories om richting te geven: 
•	Als klant wil ik slechts één keer inloggen bij eHerkenning/Digid als ik gebruik maak van Mijn Loket en OpenFormulieren
•	Als gemeente wil ik slechts één DigiD en één eHerkenning aansluiting gebruiken voor het platform.
•	Als medewerker wil ik slechts een keer inloggen bij het platform (SSO).
•	Als gemeente wil ik dat (de onderdelen van) het platform aansluit(en) op de gemeentelijke identity provider (meestal ADFS).
•	Als beheerder wil ik dat de rollen en rechten van medewerkers centraal en op dezelfde wijze binnen het platform worden ingericht. 
o	KCC en archiveringsapp moeten ook gebruik van OPA.
o	Geen dubbel beheer van gebruikers en rollen/rechten
•	Mijn Loket en OpenFormulieren moeten aansluiten op de nieuwe machtigingsvoorziening.

![image.png](https://images.zenhubusercontent.com/61a7728f4b7bcc716765fdd1/c29ab663-6226-4359-ad4f-bc3c598d9246)

•	Beschouw elke API alsof deze potentieel als externe API aangeboden wordt, zelfs als daar momenteel nog geen plannen voor zijn.
•	**Zero-trust networking: elk applicatie-component gedraagt zich alsof deze aan het publieke netwerk zit.**
•	Gebruik generieke methoden voor authenticatie en authorisatie over alle API's, bij voorkeur op basis van bestaande componenten. Voorkom specifieke oplossingen voor individuele API's.
•	Versleutel alle data in opslag (at rest) en in uitwisseling (in transit).
•	**Least privilege: API clients krijgen alleen de toegang die zij minimaal nodig hebben om hun functie uit te oefenen.**

Het gaat mij om de vetgedrukte. Ter info, de andere laten staan.

Plaatje dat helpt om het gesprek te voeren, ook uit de API strategie:
 ![image.png](https://images.zenhubusercontent.com/61a7728f4b7bcc716765fdd1/146204ff-1956-4fda-b211-f3a993e30e4f)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Deze staat al op de backlog van PodiumD. Issue wordt gesloten.
