### ISSUE TITLE
BUG: Aangemaakte zaak niet via Werklijsten of via Zoeken te vinden. 

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1539]
***Steps to reproduce:***

1. Zaak aanmaken
2. terugzoeken Werklijsten of via Zoeken
3. 

***Expected***
Zaak aanwezig

***Actual***
Zaak niet te vinden, wel door in URL het zaaknummer te plakken. Zaak had ook geen Groep na aanmaken.

**Comment by robertverboom** [comment]
Met @JosDimpact gecommuniceerd.
Momenteel wordt de status niet gezet, waardoor er een foutmelding optreed. Hierdoor wordt de zaak niet opgepakt in SOLr en dus niet getoond in een werklijst. #1520

**Comment by robertverboom** [comment]
Graag opnieuw testen

**Comment by VictorTielenius** [comment]
Nu is de zaak (ZAAK-2022-0000000143) wel na ff wachten in de werkvoorraad;
Akkoord
