### ISSUE TITLE
6B.11.X Zaak verdagen vanuit de zaak

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#154]
Epic voor het verdagen van de zaak vanuit de zaak zelf

**Comment by GertrudeKampherbeek** [comment]
- #176

**Comment by RoyBuis** [comment]
### Refinement KM, RB en RV
Stories zijn gerealiseerd. Eventuele openstaande stories gaan als losse stories verder.
