### ISSUE TITLE
Taken aanmaken kan niet

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1540]

**Comment by CommonGroundGroningen** [comment]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/13f15b3a-6e1d-4391-8d9d-1c9a1a22e1da)

**Comment by CommonGroundGroningen** [comment]
Bij het aanmaken van een nieuwe zaak moet volgens mij de menuoptie 'Intake afronden' getoond worden waarna de menuopties 'goedkeuren', 'intern advies' en 'extern advies' verschijnen. Dit wordt op dit moment niet getoond. De taken kunnen niet meer aangemaakt worden.

**Comment by robertverboom** [comment]
Met @JosDimpact gecommuniceerd. 
Momenteel wordt de status niet gezet, deze geeft door welke taken en fase veranderingen er kunnen plaatsvinden.

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by CommonGroundGroningen** [comment]
Menu items worden weer getoond.
- [x] OK
