### ISSUE TITLE
Inrichtingscheck

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1541]
***Als*** Beheerder

***Wil ik*** tijdens het deployen van de ZAC, geholpen worden met de inrichting

***Zodat*** ik 'verplichte' settings niet vergeet

***

### Acceptance criteria:
- 4 statustype; Intake, In behandeling, Heropend, Afgerond: met Afgerond als laatste statustypevolgnummer
- min 1 resultaattype
- Roltypen, omschrijving generiek: initiator en behandelaar. 1 overig roltype
- Communicatiekanaal: e-formulier
- Informatieobjecttype: e-mail
- indien zaak besluit heeft, Besluittype

***
### Prioriteit
- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Dit Inrichtingscheck is bedoeld als hulpmiddel om de inrichting van een zaaktype in zowel de ZAC als de zaaktypecatalogus te controleren op minimaal benodigde inrichting.
***Belangrijkste functionaliteiten:***

**_Zaaktypecatalogus synchronisatie_**
- Gebruiker kan de synchronisatie starten door op de blauwe knop te klikken. De volgende gegevens worden gesynchroniseerd: Zaaktypen, Informatieobjecttypen, Besluittypen, Zaaktype-informatieobjecttypen, Resultaattypen, Statustypen en Roltypen.
- Gebruiker kan door op het vraagteken icoon te klikken meer informatie zien over het doel en de werking van de synchronisatie

_**Zaaktype inrichtingscheck**_
Hier kan voor een zaaktype dat nog niet volledig en correct is ingericht worden gecheckt welke onderdelen nog inrichting nodig hebben. Als een zaaktype niet in deze lijst voorkomt dan is de minimaal benodigde inrichting correct. Er wordt hier een validatie uitgevoerd op de ZAC zaakafhandel-parameters en de zaaktypecatalogus implementatie. 
- Gebruiker kan een zaaktype in de lijst controleren door op de regel te klikken. Daarna worden alle inrichtingsonderdelen die aandacht nodig hebben geopend en wordt per onderdeel vermeld wat er niet correct is ingericht. Voor nu worden de volgende onderdelen gecheckt:
  - Zaakafhandelparameters | er wordt gecheckt of deze volledig zijn ingericht
  - Statustypen | er wordt gecheckt of voor de werking van de ZAC vereiste statustypen zijn toegevoegd aan het zaaktype. Dit zijn momenteel ‘Intake’, ‘In behandeling’, ‘Heropend’ en ‘Afgerond’ waarbij ‘Afgerond’ het hoogste volgnummer moet hebben zodat dit de eindstatus wordt.
  - Rollen | er wordt gecheckt of de voor de werking van de ZAC vereiste rollen zijn toegevoegd aan het zaaktype. Dit zijn momenteel ‘Initiator’ en ‘Behandelaar’ die nodig zijn om de functionaliteit voor het toevoegen van een initiator aan een zaak en het op naam van een behandelaar zetten van een zaak mogelijk te maken. Daarnaast wordt gecheckt of er minimaal één andere rol is toegevoegd die gebruikt wordt bij de functionaliteit voor het toevoegen van betrokkenen aan eem zaak.
  - Informatieobjecttype | er wordt voor de werking van de ZAC gecheckt of het zaaktype aan de vereiste informatieobjecttypen is gekoppeld. Dit is momenteel ‘e-mail’ dat gebruikt wordt voor het als document toevoegen van vanuit de ZAC verzonden e-mails.
  - Besluittype | er wordt gecheckt of aan het zaaktype een besluittype is gekoppeld. Dit gebeurt alleen als aan het zaaktype een resultaattype is toegevoegd dat als afleidingswijze de begin- of vervaldatum van een besluit heeft.

**_Referentielijsten en selectielijst inrichtingscheck_**
- Gebruiker kan checken of de voor de ZAC benodigde inrichting in de referentielijsten en selectielijsten correct is. Er wordt hier een validatie uitgevoerd tussen de ZAC en de referentielijsten en selectielijsten implementatie. Voor nu worden de volgende onderdelen gecheckt:
  - Communicatiekanaal | er wordt gecheckt of het kanaal ‘E-formulier’ is toegevoegd. Deze is alleen vereist als er via Open Formulieren productaanvragen worden aangemaakt waarvoor de ZAC zaken voor aan moet maken.
- Gebruiker kan door op het vraagteken icoon te klikken meer informatie zien over het gecheckte onderdeel

**Comment by RoyBuis** [comment]
### Refinement 6-9

Spike met volgende uitgangspunten:

- Bij beheerinstellingen een onderdeel toevoegen dat valideert of verplichte inrichting gedaan is. 
  - Naam menu item: Zaaktype inrichtingscheck 
  - Icoon: health and safety
- Er kan gevalideerd worden op zaaktypeniveau, alleen actuele en geldige versies van zaaktypen kunnen gecheckt worden
- Bij starten ZAC worden validaties van zaaktypen uitgevoerd en in managed cache opgeslagen. Er komt geen refresh knop. Notificaties moeten er voor zorgen dat de managed cache geupdatet wordt.
- Bij de validatie wordt ook de zaakafhandelparameterscheck gedaan en de uitkomst daarvan als een indicatie getoond.
- Per zaaktype wordt gevalideerd en de uitkomst getoond van:
  - Valide zaakafhandelparameters
  - Valide inrichting (Open zaak en andere externe systemen)

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
@robertverboom en @RoyBuis . Om dit te kunnen testen zou ik ook in Open zaak iets moeten kunnen inrichten/wijzigen. 
Ik zie nu alleen de meldingen maar kan dus niet testen door het zelf aan te passen

![image](https://user-images.githubusercontent.com/96229645/226341893-9ac61aec-7f54-4f05-84fd-c507ca088e5c.png)

Mee eens? Hoe kunnen we dit organiseren.

**Comment by RoyBuis** [comment]
@HilbrandHurtak Ja dat is inderdaad alleen te testen i.c.m. Open zaak. We kunnen wel een keer een half uur inplannen en dan testen door wat wijzigingen aan te brengen. Maar om het grondig te testen zou je als tester zelf in Open zaak moeten kunnen wijzigen.

**Comment by HilbrandHurtak** [comment]
@RoyBuis . Robert heeft dit getest en een akkoord gegeven. Voor nu ga ik hier dan vanuit. Zodra we een PodiumD omgeving hebben met daarin alle componenten en de trainingen hebben gevolgd, zullen we dit soort integraties ook moeten gaan testen. Voor nu dit ticket dan maar sluiten?

**Comment by RoyBuis** [comment]
@HilbrandHurtak Ja dat lijkt me een goede oplossing

**Comment by HilbrandHurtak** [comment]
In overleg met Roy deze story gesloten. Bij de integratietesten (openzaak-ZAC en andere componenten) moet dit goed worden getest. Het gaat dan met name om de ZAC afhankelijkheden en de afstemming binnen de componenten
