### ISSUE TITLE
Button 'Alleen groepsleden' lijkt niet te werken

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1547]

**Comment by CommonGroundGroningen** [comment]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/c4b0412a-b58d-427d-8e2b-259118d34d35)

**Comment by CommonGroundGroningen** [comment]
Ik verwacht dat de button 'Alleen groepsleden' ervoor zorgt dat alleen die medewerkers getoond worden die horen bij de groep die geselecteerd is bij 'Taak toekennen aan groep'. Er is echter geen verschil in leden tussen de button aan en de button uitzetten. De button lijkt niet te werken.

**Comment by robertverboom** [comment]
Komt omdat alle gebruikers in alle groepen voorkomen. Ik heb een gebruiker User A aangemaakt. Deze is alleen gekoppeld aan Groep A. 

Graag opnieuw beoordelen

**Comment by robertverboom** [comment]
Consistent maken: Groep/behandelaar in 1 component zetten net als bij taak startformulier. Zowel op het taakscherm als op zaakscherm. 
Verdelen van taken consistent maken met verdelen van zaken in de werkvoorraad

**Comment by RoyBuis** [comment]
### Refinement 15-9

Toekennen aan groep/behandelaar consistent maken. Overal groep en behandelaar velden met optie om 'alleen groepsleden' in te schakelen.

Dit wordt op de volgende plekken toegepast:
- Verdelen Taken werkvoorraad
- Verkorte taakinformatie van het taakscherm
- Verdelen Zaken-werkvooorraad (is al correct)
- Algemene gegevens van zaakscherm
- Taak starten scherm van alle taken (is al correct)

De werking van alleen groepsleden knop irt de toekennen aan mezelf moet logisch zijn
Voor inline editen is een nieuw component nodig
Voor de dialogs en panels is er al een medewerker-.groep component

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by HilbrandHurtak** [comment]
Test akkoord

**Comment by HilbrandHurtak** [comment]
Test akkoord
