### ISSUE TITLE
IAM: Keycloak en OIC configureren voor de volgende CG componenten

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1554]
***Als*** Gemeente

***Wil ik*** dat mijn medewerkers eenmalig kunnen inloggen op het platform (via ADFS) en bij de diverse componenten toegang hebben op basis van centraal in te richten rollen

***Zodat*** ik mijn gebruikersbeheer centraal kan inrichten en mijn gebruikers eenmalig inloggen

***

Een eerste opsomming van de componenten:  

- ZAC
- Open Formulieren (medewerker login)
- OpenZaak (voor ZTC inrichting)
- Referentielijsten
- ORC (overige registraties)
- KISS
- OIP
- Archiefapp (Delft)
- Etc... er volgen er nog meer.

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by andyverberne** [comment]
**Develop**

- Open Zaak - vinkje Supergebruikerstatus aanzetten bij gebruiker nadat deze is aangemaakt in Open Zaak
