### ISSUE TITLE
Om te gaan met aanroepen van buitenaf en policies controleren

### ISSUE THREAD

**Issue by ronniekoopmans-atos** [NL-AMS-LOCGOV/zaakafhandelcomponent#1556]
Als er een call van buitenaf word gedaan en de policyservice gaat de ingelogde gebruiker controleren, dan treed hier een NPE op.

Een voorbeeld is de ZoekService die wordt aangeroepen door de SignaleringenJob.
Voor nu is er een stukje code toegevoegd aan de zoekservice om te controleren dat er een ingelogde gebruiker is,
Maar misschien zijn er wel meer plekken waar iets moet gebeuren.

Ook is het mooier dat er een gebruiker wordt meegeven vanuit jobs/externe aanroepen om de rechten te controleren.

**Comment by RoyBuis** [comment]
### Refinement 6-9

- Als de indexeer- of signaleerservice wordt aangeroepen door een cronjob dan moet er een functionele gebruiker plus rol in de session worden gezet. De policycheck kan gebruik maken van deze functionele gebruiker en rol.

- Ook functionele gebruiker toevoegen bij afhandelen van notificaties

- Eén functionele gebruiker en één rol aanmaken ergens als constante in de code. Functionele gebruiker komt niet in de lijst van gebruikers dus niet in Key Cloak, LDAP, etc

**Comment by ronniekoopmans-atos** [comment]
Geprobeerd om de servletContext door te geven vanuit de CDI fireAsync naar de nieuwe thread om zo de active gebruiker te raadplegen vanuit een nieuwe thread. dit is niet gelukt, dus heb het nu als volgt gemaakt; als er geen sessie is, dan de functionele gebruiker terug geven. dit kan omdat er vanuit een servlet context altijd een sessie aanwezig is (ook als je niet ingelogd bent)
