### ISSUE TITLE
In ZAC per zaaktype instellen welke productaanvraagtype een zaak van het zaaktype moet starten

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1558]
***Als*** beheerder

***Wil ik*** in het ZAC per zaaktype kunnen instellen dat een productaanvraag met een bepaald type een zaak moet starten

***Zodat*** ik kan bepalen welke productaanvragentypen een zaak moeten starten (en welke niet en dus bijv voor de e-Suite bedoeld zijn)

***

### Acceptance criteria:
-

***
### Prioriteit

- Must haves
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In de zaakafhandelparameters (de 'zaps') kan ingesteld worden of bij het ontvangen van een productaanvraag (uit Open Formulieren) de ZAC een zaak moet aanmaken. Dit wordt gedaan door de naam van het in Open Formulieren geconfigureerde productaanvraagtype in het daarvoor bedoelde veld van de zaps in te vullen. Als een ontvangen productaanvraag matcht met een van de ingestelde waarden in de zaps dan wordt een zaak van het betreffende zaaktype aangemaakt.
Als er van een ontvangen productaanvraag géén zaak aangemaakt hoeft te worden maar er is wel een aanvraagdocument voor aanwezig in Open zaak dan wordt het document in de Inbox documenten van de ZAC geplaatst. 

***Belangrijkste functionaliteiten:***
- Gebruiker kan in de zaps in het tabblad 'Gegevens' bij het veld 'Productaanvraagtype' instellen van welke waarde een zaak aangemaakt moet worden

**Comment by RoyBuis** [comment]
### Refinement 6-9

**Te realiseren**
- In zaakafhandelparameters kan je optioneel een productaanvraagtype instellen
- ZAC ontvangt een notificatie dat er productaanvraag is aangemaakt, hieruit moet het type gehaald worden en gekeken worden of deze voorkomt in de zaakafhandelparameters (verwerktproductaanvraag in de productaanvraagservice)
- Dit productaanvraagtype moet matchen met de naam zoals in OF ingesteld om door het ZAC een zaak aan te laten maken
- In één regel loggen of er wel of geen zaak wordt aangemaakt
- In één regel een warning als het aanvraagdocument wel gevonden wordt in Open zaak op het moment dat er géén zaak aangemaakt hoeft te worden. Van het opgeslagen aanvraagdocument een inboxdocument maken, dit gebeurt waarschijnlijk automatisch.

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
@robertverboom . Voor het zaaktype Klacht heb ik nu een formulier in Open formulieren gemaakt. Conform de inhoud van het ticket heb ik geprobeerd om daar de productaanvraagtype aan te koppelen. Als ik dat doe via de zaakafhandelparameters krijg ik een melding en kan ik niet verder:
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/795bdf5c-6f8d-45f1-93b4-2becd8435664)

Vraag:
1. wat moet ik nog doen om de waarde in te kunnen vullen
2. welke waarde moet ik van OF invullen (ik gok op het ID?)
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/17614609-1c70-4839-831e-dc235e3c3e44)

De ingediende formulieren komen nu binnen als document
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/275c642f-6b15-46e8-af3e-88ce5fe49be9)

Ik heb nog even gekeken hoe de koppeling tussen OF en ZAC is gemaakt voor de Melding klein evenement. Bij een oude zaakinrichting stond hier:
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/e94cc72c-3733-4e09-b276-be559825b99a) 



In een nieuwe versie van de zaakinrichting is het veld niet gevuld en kan ik hem ook niet wijzigen en bewaren
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/dd6069f9-b78b-4970-aea8-e3af3fd0aab0)

**Comment by HilbrandHurtak** [comment]
Reactie Robert: Ik heb zojuist een klacht middels jouw formulier ingediend. Bij beide componenten de productaanvraagtype gelijk gezet, echter worden er geen zaken gestart (zowel niet op zandbak als op onze develop). Uitgerekend nu is een collega bezig met ticket #319 en #2249 die ook gebruik maken van een productaanvraagtype. 
Er staat een fix klaar (Pullrequest #2420 ), die moet alleen nog even door de review heen. Als dit gebeurt is (verwacht vandaag) dan controleer ik alles nog eens en rol ik de zandbak opnieuw uit. Bug zit namelijk ook in de zandbak.

**Comment by HilbrandHurtak** [comment]
Bug opgelost. Zaak wordt nu gestart vanuit een Open formulier aanvraag met de volgende configuratie:
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/e64ab602-f2af-4aab-b42e-b5b3da310694)

In open formulieren is de configuratie als volgt
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/d3470b72-090d-4159-8953-c7db222f052b)

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/90a8506b-be65-41b8-b28a-18f0fa0e7e98)

Formulier met bijlage maakt geen zaak aan. Formulier komt in Inbox documenten en bijlage is verdwenen. Is aan Robert doorgegeven
