### ISSUE TITLE
Document toevoegen aan besluit

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1565]
***Als*** Beslisser

***Wil ik*** een bestaand informatieobject koppelen aan een besluit, bij het vastleggen van een besluit

***Zodat*** het besluit ook in een document is vastgelegd. 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #1473 is het vastleggen van een besluit bij een zaak opgeleverd. In deze story is deze functionaliteit uitgebreid waardoor het mogelijk is om een of meerdere documenten aan een besluit toe te voegen. Dit is alleen mogelijk voor documenten van een documenttype dat in de zaaktypecatalogus aan het gekozen besluittype is gekoppeld.
Als een document aan een besluit is toegevoegd dan kan dit document niet van de zaak ontkoppeld worden, het besluit is immers gekoppeld aan de zaak en het document hoort bij het besluit.

***Belangrijkste functionaliteiten:***
- Gebruiker kan een document waarin (een deel van) het besluit is beschreven via de actie [Besluit toevoegen] aan het besluit toevoegen door het te selecteren in het besluitpanel
- Gebruiker kan een aan een besluit toegevoegd document weer ontkoppelen door via het potlood icoon op het besluit het document uit te vinken

**Comment by robertverboom** [comment]
Refinement 08-09:
- Als er geen informatieobjecttype op het besluittype staat, dan de knop document selecteren niet tonen op het besluit, bij het aanmaken van een besluit. 
- Mogelijk om meerdere documenten te selecteren met het informatieobjecttype die op het besluittype staan

**Comment by CommonGroundGroningen** [comment]
Getest in zandbak omdat in de acceptatie documenten niet het documenttype 'besluit' kunnen hebben.

**Gebruiker kan een document waarin (een deel van) het besluit is beschreven via de actie [Besluit toevoegen] aan het besluit toevoegen door het te selecteren in het besluitpanel**
Test ok
**Gebruiker kan een aan een besluit toegevoegd document weer ontkoppelen door via het potlood icoon op het besluit het document uit te vinken**
Test ok

**Als er geen informatieobjecttype op het besluittype staat, dan de knop document selecteren niet tonen op het besluit, bij het aanmaken van een besluit.**
Test ok
**Mogelijk om meerdere documenten te selecteren met het informatieobjecttype die op het besluittype staan
In besluitenblok de documenten tonen**
Test ok
**Document mag niet bij de zaak verwijderd worden als deze aan een besluit is gekoppeld**
Test ok

**Comment by KarinMasselink** [comment]
@robertverboom wil jij deze ook inrichten zodat we deze kunnen hertesten op acceptatie

**Comment by robertverboom** [comment]
het zaaktype 'Bezwaar indienen' heeft het besluit 'Verleend' gekregen waar het informatieobjecttype/documenttype besluit aangekoppeld is. 

Wanneer je een besluit toevoegt, wordt er gevraagd om een besluittype te kiezen, deze moet gevuld worden met 'Verleend' om de validatie op de informatieobjecttype in werking te zetten. (moet volgens de API) Documenten met het documenttype 'Besluit' kunnen alleen gekoppeld worden.

**Comment by CommonGroundGroningen** [comment]
Hertest in acceptatie oke
