### ISSUE TITLE
Via LDAP inloggen op zowel ZAC, OZ, OF, AB, Refrentietabllen 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1566]
***Als*** informatiebeheerder 

***Wil ik*** met 1 account maar 1 keer inloggen

***Zodat*** ik niet bij alle componenten afzonderlijk moet inloggen. 

***

### Acceptance criteria:
-  Via LDAP inloggen op zowel ZAC, OZ, OF, AB, Refrentietabllen etc. 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by Snijhuis** [comment]
@robertverboom Ik had deze aangemaakt. Morgen maar even bespreken welke we gebruiken :) #1554
