### ISSUE TITLE
spreadsheet matchen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1569]
Spreadsheet matchen met policy:
[https://app.zenhub.com/files/416646145/1e3c699a-a951-400c-aae1-f6dec7495d83/download](https://app.zenhub.com/files/416646145/1e3c699a-a951-400c-aae1-f6dec7495d83/download)

**Comment by andyverberne** [comment]
Na bestudering van spreadsheet adviseer ik om gewoon verder te gaan met het vullen van her spreadsheet. Wanneer het klaar is houden we het tegen onze policies aan en kijken we of we daar nog aanpassingen in moeten maken.

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Issue wordt gesloten.
