### ISSUE TITLE
6B.2.3 Openen zaak met behoud huidige werkvoorraad (zoekopdracht) 

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#157]
***Als*** zaakbehandelaar

***Wil ik*** dat wanneer ik de zaak vanuit een door mij gegenereerde/gefilterde werkvoorraad open deze werkvoorraad niet verloren gaat en ik eenvoudig terug kan naar deze werkvoorraad

***Zodat*** ik niet telkens weer opnieuw mijn werkvoorraad moet openen/genereren/filteren

***

### Acceptance criteria:

- De zaak moet geopend kunnen worden zonder dat de huidige gegenereerde werkvoorraad verloren gaat. 

 NB. Oplossingsrichtingen bespreken met DEV team. CTRL + F5 werkt nu niet in ZAC 

- Zaak openen in overlay/ iFrame? 
- Of met browser knop kunnen terugnavigeren? 
- Andere mogelijkheden? 

***
### Prioriteit

- [ ] Must haves

### Gerealiseerd
De werkverdeler/behandelaar kan zelf zijn filter instellingen opgeven en opslaan. 

***Belangrijkste functionaliteiten:***
- Er kunnen meerdere filterinstellingen worden opgeslagen voor verschillende gepersonaliseerde werklijsten.

**Comment by RoyBuis** [comment]
Refinement:

- Vraag: hoe lang moet de gegenereerde werkvoorraad bewaard blijven? Bij sluiten sessie dan niet meer bewaren.
- Vraag: moet dit ook werken in een Citrix omgeving? Ja
- Deze story gaat niet over verdelen vanuit de werkvoorraad, alleen over werken/beheer vanuit de werkvoorraad

Werking van deze functionaliteit:
- Opslaan in session storage
- Toepassen op alle werklijsten 
- Knop bij werklijsten toevoegen waarmee je alle filters en sorteringen kan wissen
- Bij terug navigeren naar werkvoorraad, dan terug naar pagina waar je gebleven was
- Onthouden welke kolommen zichtbaar zijn
- Onthouden sortering en filteringen

**Comment by VictorTielenius** [comment]
Zie #1640
Nu in diverse weklijsten mogelijk om een Zaak / Taak / Document op nieuw tabblad of venster te openen. Met rechtermuisknop en met Ctrl / Shift en klikken
