### ISSUE TITLE
Wijzigen besluit

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1570]
***Als*** beslisser

***Wil ik*** een besluit kunnen wijzigen of verwijderen van een zaak

***Zodat*** zodat ik gemaakte fouten kan herstellen

***

### Acceptance criteria:
- de gegevens van een bij een zaak vastgelegd besluit kunnen via het systeem gewijzigd worden
- het bij een zaak vastgelegde besluit kan verwiijderd worden
-  het resultaat kan gewijzigd worden
- de uitgevoerde acties kunnen in de zaakhistorie bekeken worden
- de uitgevoerde acties kunnen in de besluithistorie bekeken worden

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #1473 is het vastleggen van een besluit bij een zaak opgeleverd. In deze story is deze functionaliteit uitgebreid waardoor het mogelijk is om een besluit te wijzigen. Het besluittype van een besluit kan niet gewijzigd worden.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met het potlood icoon op het besluit de gegevens van het besluit wijzigen. Het besluittype kan niet gewijzigd worden
- Het wijzigen van een besluit wordt vastgelegd in de historie van het besluit met de door de gebruiker ingevulde reden als toelichting

**Comment by RoyBuis** [comment]
### Refinement RV, SN, RB 12-9
Besluit wijzigen
- potlood opent sidepanel
- gebruiker kan alle gegevens wijzigen, bij wijzigen resultaat wordt opnieuw bepaald of vervaldatum verplicht is (technisch wordt het resultaat verwijderd)
- toevoegen en wijzigen besluit vastleggen in zaakhistorie
- historie van besluit in tab besluithistorie tonen

Besluit verwijderen
- prullenbak op besluitgegevensblok
- als document is gekoppeld dan ontkoppelen van besluit, doc blijft aan zaak gekoppeld
- verwijderen besluit vastleggen in zaakhistorie

**Comment by robertverboom** [comment]
Moet 'besluit vastleggen' worden getoond in de intake fase?

**Comment by robertverboom** [comment]
Refinement 13-09:
- bij input van policy van besluit wijzigen en verwijderen op besluit zelf zetten 
 (kijk bij informatieobject)

**Comment by CommonGroundGroningen** [comment]
**Gebruiker kan met het potlood icoon op het besluit de gegevens van het besluit wijzigen. Het besluittype kan niet gewijzigd worden**
Test ok
**Het wijzigen van een besluit wordt vastgelegd in de historie van het besluit met de door de gebruiker ingevulde reden als toelichting**
Test ok
