### ISSUE TITLE
Goedkeuringslijst aanpassen lukt niet

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#1577]

**Comment by CommonGroundGroningen** [comment]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/8c79d490-ca74-46e5-b2d8-3429e94610fe)

**Comment by CommonGroundGroningen** [comment]
User story: #480, acceptatie criterium nr 3:
"Bij een goedkeuringstaak moet uit een lijstje(die te configureren is) de uitkomst van de goedkeuring op hoofdlijnen kunnen worden aangegeven(bijvoorbeeld Akkoord, Niet akkoord, Gedeeltelijk akkoord/niet akkoord )"
Dit lijstje is niet te configureren door mij.

**Comment by robertverboom** [comment]
referentietabellen uitbreiden voor Goedkeuren taak en ook gelijk voor algemene informatie taak

**Comment by robertverboom** [comment]
Lijst uitbreiden met : 
Akkoord, Niet akkoord, Gedeeltelijk akkoord

**Comment by HilbrandHurtak** [comment]
Lijst graag configureerbaar maken conform de oplossing voor Intern advies
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/b3db031c-334d-48dd-93ae-23dc40b488ab)

**Comment by robertverboom** [comment]
Besloten met @Snijhuis extra opties toe te voegen

**Comment by HilbrandHurtak** [comment]
Zie besluit van Sander. Extra optie is toegevoegd. Dit item is dus niet configureerbaar.
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/063a8d32-de5d-4f4d-bf71-31134ad534b1)
