### ISSUE TITLE
Besluit verwijderen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1580]
***Als*** Beslisser

***Wil ik*** een besluit kunnen verwijderen

***Zodat*** een verkeerd besluit van de zaak gehaald kan worden. 

***

### Acceptance criteria:
- prullenbak op besluitgegevensblok
- als document is gekoppeld dan ontkoppelen van besluit, doc blijft aan zaak gekoppeld

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by robertverboom** [comment]
Een besluit die gekoppeld is aan een zaak kan verwijder worden (ook in OZ) of de relatie met de zaak kan ontkoppeld worden. 
Het is mogelijk om meerdere besluiten aan een zaak te koppelen

**Comment by Snijhuis** [comment]
**WG R&A 21-09 bespreken:**
Voorleggen aan de WG Informatiebeheer

**Comment by RoyBuis** [comment]
Vragen aan werkgroep:
In welke gevallen mag een besluit verwijderd worden. Wat zijn de voorwaarden? Denk aan de fase van de zaak. Mag een besluit nadat een zaak is beeindigd nog verwijderd worden, eventueel alleen door recordmanager?
Verwijderen toegestaan als een besluit verzonden is?
Wat zijn de voorwaarden voor het mogen verwijderen?

**Comment by robertverboom** [comment]
Nog niet bouwen. Mede omdat dit nog niet wordt vastgelegd in historie van de zaak. En het besluit wordt echt verwijderd (definitief uit besluitenregister)

**Comment by robertverboom** [comment]
Besluit mag niet verwijderd worden, allen ingetrokken: Besluit intrekken #2084

**Comment by Snijhuis** [comment]
Issue gaan we hierbij sluiten. Intrekken besluit pakken we wel op #2084
