### ISSUE TITLE
Lijst behandelaren op alfabetische volgorde tonen

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1583]
***Als*** gebruiker

***Wil ik*** de lijst van behandelaren op alfabetische volgorde zien

***Zodat*** snel de juiste persoon kan selecteren

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 27-10

In IdentityService aanpassen:
- Gebruikers sorteren op volledige naam
- Groepen sorteren op naam
