### ISSUE TITLE
samenvatting van documenten in zip toevoegen

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1584]
***Als*** gebruiker

***Wil ik*** een samenvatting zien in de .zip van de door mij gedownloade documenten 

***Zodat*** ik een direct overzicht heb van de documenten

***

### Acceptance criteria:

- zie #1429 en #305
- **in de samenvatting opnemen:**
- wat de documentrichting is (inkomend enz) 
- documenttitel
- bestandsnaam

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by jeroen-dekker** [comment]
To-do:
- [ ] `InformatieObjectenRESTService::readFilesAsZip` uitbreiden om naast bestanden in de zip te plaatsen ook een index-textfile te genereren.

Er zijn een aantal opties voor het opbouwen van het tekstbestand. Het categoriseren van ieder informatieobject in dezelfe loop als het aanmaken van de zip-file is mogelijk, maar daar komt een boel extra code en complexiteit bij kijken. Eigenlijk willen we 'simpelweg' een overzicht van de bestanden zoals deze in de zip-file terecht komen. Omdat ze daar al gecategoriseerd zijn, is het een stuk makkelijker om die opgebouwde bestandstructuur over te nemen in een tekstbestand.

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by HilbrandHurtak** [comment]
Test akkoord
