### ISSUE TITLE
BUG: bestandsformaat bij exporteren

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1585]
Als gebruiker
Wil ik een .csv bestand openen in excel zonder dat ik een wizard moet gebruiken
Zodat ik met weinig excel kennis ook een overzichtelijk rapport kan inzien

**Comment by robertverboom** [comment]
.csv formaat is gangbaarder dan .xlsx echter moet het csv bestand aangepast worden. in de e-suite is dit uitgezocht

**Comment by robertverboom** [comment]
De DSR referentietabellen in de e-suite worden ook als .csv geexporteerd, echter worden deze tabellen wel in kolommen gezet.

**Comment by robertverboom** [comment]
Om de opmaak netter te maken door excel zelf: tab Gegevens > Uit tekstbestand/CSV > document inladen

**Comment by RoyBuis** [comment]
### Refinement 22-12

- bij nederlandse locale een puntkomma ;
- default is een komma
- http:servletrequest.getlocale
- misschien kan de locale meegegeven worden aan open csv?

**Comment by HilbrandHurtak** [comment]
Op de zandbak getest. CSV wordt nu in Excel geopend (zonder eigen inleesactie). Voorwaarde is wel Nederlandse office(ivm punt en komma).

Test OK

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/fc9c03d5-a8f2-441a-ae82-a50bf5892736)
