### ISSUE TITLE
Knop exporteren werklijst 

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1586]
***Als*** gebruiker

***Wil ik*** de knop 'exporteren naar .csv' in de werklijst op een minder opvallende plek en kleur zien

***Zodat*** deze niet altijd opvallend in het oog zie

***

### Acceptance criteria:
- de knop verplaatsen naar rechtsboven naast de knoppen 'filters' en 'reset kolommen'. Het nu gekozen icoon bij de toepassing is prima.

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Should haves
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #443 is het exporteren van gegevens in een werklijst opgeleverd. In deze story is de UI aangepast, de functionaliteit is ongewijzigd.

***Belangrijkste functionaliteiten:***
Nvt

**Comment by robertverboom** [comment]
- Verplaatsten naar rechtsonder met zelfde styling als pagina instellen
- woord CSV verwijderen

**Comment by robertverboom** [comment]
Graag opnieuw controleren. Verplaatst naar rechtsonder met zelfde styling als pagina instellen

**Comment by HilbrandHurtak** [comment]
Icoontje aangepast en woord csv is weg (Is nu exporteer geworden)
![image](https://user-images.githubusercontent.com/96229645/226338819-dc92e0ac-6212-4e0a-9130-c4d2973129ca.png)
