### ISSUE TITLE
BUG: kleur van de indicaties in werklijst

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1587]
***Expected***
rustige weergave van de werklijsten wanneer er zaken zijn met indicaties al HZ, DZ, V enz

***Actual***
doordat de kleuren van de indicaties in de werklijst fuchsia zijn vallen deze erg op en verstoren het blikveld bij het analyseren van en zoeken in de werklijst. Wanneer de kleur zo helder is trekt deze de focus.
Voorstel is om de indicatie in de werklijst in dezelfde kleur te doen als de iconen 'filter' en 'reset kolommen'. Wanneer je de zaak opent is de opvallende kleur van de indicatie niet erg.

**Comment by robertverboom** [comment]
Lijst maken. Denk aan kortlopende en blijvende indicaties

**Comment by Renvooi** [comment]
Besproken in de werkgroep wat tijdelijk en wat vast is. Werkgroep is akkoord met hetgeen Atos daarover aangeeft.
