### ISSUE TITLE
BUG: filteren en sorteren in werklijsten

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1588]
***Expected***
kunnen filteren en sorteren op de kolomkop 'indicaties'
kunnen sorteren op kolomkop 'dagen tot streefdatum'
kunnen sorteren op kolomkop 'dagen tot fatale datum'

***Actual***
in de werklijsten is het de bedoeling dat op elke kolomkop gefilterd en gesorteerd moet kunnen worden

**Comment by GertrudeKampherbeek** [comment]
zie #452

**Comment by RoyBuis** [comment]
### Refinement RV & RB

- Sorteren op 'Dagen tot fatale datum' kan nu door te sorteren op 'fatale datum', de 'dagen tot' worden dan ook gesorteerd.
- Voor 'dagen tot streefdatum' geldt hetzlefde
- Voor 'Indicaties' een sortering en filter maken voor Werkvoorraad-zaken en Mijn zaken

**Comment by robertverboom** [comment]
### Refinement 13-10:
- select Lijstje tonen met gebruikersindiciaties.

**Comment by Renvooi** [comment]
7-3-2023 getest. Werkt zoals door Atos aangegeven maar ik weet niet of dat voor Gertrude acceptabel is. De oplossing is namelijk geen filter maar een kolomsortering.
