### ISSUE TITLE
6B.3.2 Verdelen zaken door werkverdeler in bulk aan een andere behandelaar/groep

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#159]
***Als*** Werkverdeler

***Wil ik*** zaken in bulk kunnen verdelen aan een behandelaar/groep

***Zodat*** ik de werkvoorraad goed kan beheren en de zaken in behandeling kunnen worden genomen door de juiste behandelaar en/of groep 

***

### Acceptance criteria:
- Bij het verdelen dient ook een reden te worden aangegeven (optioneel)
- De actie van verdelen moet worden vastgelegd bij de zaken (historie)
- Bij het verdelen van de zaken moet als optie ook de onderliggende taken van de behandelaar kunnen worden overgedragen (Andere story - nut en noodzaak nog bepalen)
- Het verdelen mag alleen aan een behandelaar/groep die daarvoor de juiste autorisaties heeft (Opnemen in story over autorisaties)

***
### Prioriteit

- Must haves

***
### Gerealiseerd
In de zaken-werkvoorraad kan een werkverdeler checkboxen aanvinken. Hierdoor verschijnt onderaan de knop Verdelen. Door op de knop te klikken, komt er een pop-up om een groep, behandelaar en/of reden op te geven. 

***Belangrijkste functionaliteiten:***
- Het bulk verdelen gaat per pagina
- De verdeelactie wordt geregistreerd in de zaakhistorie. Onder toelichting wordt de reden van verdelen getoond. 
- Het datamodel van Openzaak verbreekt eerst de oude relatie (waarde) en maakt vervolgens een nieuwe relatie (waarde) aan. Hierdoor wordt het in 2 rijen in de Historie getoond.

**Comment by RoyBuis** [comment]
Refinement 20 december:

Werking bij het verdelen:
- Groepen en medewerkers staan los van elkaar
- Als eerst een groep wordt gekozen dan kan worden alle medewerkers gekoppeld aan de groep getoond in het medewerker veld
- Als eerst een medewerkers wordt gekozen dan worden alle medewerkers uit het systeem getoond in het medewerker veld
- Een van de twee velden is verplicht

**Comment by robertverboom** [comment]
opgelost met ticket: #163

**Comment by GertrudeKampherbeek** [comment]
Als je eerst de behandelaar kiest lijkt het erop dat ik als gebruiker in 2 groepen ziet 'groep A' en 'groep B', klopt dat?

**Comment by HilbrandHurtak** [comment]
@RoyBuis Ik zie deze functionaliteit niet onder mijn eigen account en niet op die van de coordinator. Zie jij het wel?

Gerealiseerd
In de zaken-werkvoorraad kan een werkverdeler checkboxen aanvinken. Hierdoor verschijnt onderaan de knop Verdelen. Door op de knop te klikken, komt er een pop-up om een groep, behandelaar en/of reden op te geven.

**Comment by CommonGroundGroningen** [comment]
Getest door Tom en Pieta.
Commentaar op de refinements hierboven benoemd:
**Groepen en medewerkers staan los van elkaar**
Dit kunnen wij niet zien aangezien alle personen in alle groepen zitten. Is het mogelijk om een paar mensen uit enkele groepen te halen?

**Als eerst een groep wordt gekozen dan kan worden alle medewerkers gekoppeld aan de groep getoond in het medewerker veld**
Dit werkt zoals staat beschreven.

**Als eerst een medewerkers wordt gekozen dan worden alle medewerkers uit het systeem getoond in het medewerker veld**
Dit werkt niet zoals beschreven. Er moet eerst een groep worden geselecteerd.

**Een van de twee velden is verplicht**
Het veld groep is altijd verplicht.

**Comment by HilbrandHurtak** [comment]
@CommonGroundGroningen  Let op: toewijzen aan groepen en personen is gewijzigd. zie #2033 Graag op basis van deze gewijzigde functionaliteit opnieuw testen

**Comment by robertverboom** [comment]
@CommonGroundGroningen Op de zandbak omgeving is er een groep 'Groningen' aangemaakt. Hier zitten beperkte gebruikers in; oa alle medewerkers van Groningen.

**Comment by CommonGroundGroningen** [comment]
Verdelen zaken werkt nu door eerst groep te kiezen en daarna is het alleen mogelijk personen te selecteren als deze in de groep zitten. Verdere uitwerking en test kan volgens mij in  #2033.
