### ISSUE TITLE
BUG: Bij Verwijderen document uit een zaak foutpagina

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1590]
***Steps to reproduce:***

1. Document verwijderen
2. 
3. 

***Expected***
Document is verwijderd

***Actual***
Foutpagina, document wel verwijderd
 (Foutpagina De server heeft code 500 geretourneerd)

**Comment by robertverboom** [comment]
Lukt ons niet te reproduceren. Mogelijk om het scenario beter te beschrijven?

**Comment by VictorTielenius** [comment]
In zaak 150 / https://zac.accept-public-service-platform.net/zaken/ZAAK-2022-0000000150 (vandaag aangemaakt) via oogje naar de naar het document toe gaan. Daar op het prullenbakje / Verwijderen klikken. Reden ingeven en op Document Verwijderen klikken. Dan komt er een foutpagina in beeld (zie afbeelding). Het document is wel wel verwijderd. Net weer een document verwijderd, en foutpagina komt. Weer een document toegevoegd om door jou te verwijderen.

**Comment by VictorTielenius** [comment]
![Foutpagina bij verwijderen document uit zaak.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/9139ead8-841c-43b9-bd41-a7901490b6ca)

**Comment by robertverboom** [comment]
graag hertesten

**Comment by VictorTielenius** [comment]
Hertest: Nog steeds Foutpagina bij verwijderen document (PDF)
Document is wel verwijderd. 
Bij een Word document verwijderen geen foutpagina. (en document is verwijderd)
Zie ZAAK-2022-0000000170
Hier weer een document in gezet (PDF) @robertverboom

**Comment by RoyBuis** [comment]
Fout treedt op bij documenten waarvan een preview mogelijk is ie PDF en afbeelding. BIj bijv een Word document treedt de fout niet op

Te reproduceren op develop door:
- PDF of JPG document aan zaak toevoegen
- Documentgegevenspagina openen
- Document verwijderen

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by VictorTielenius** [comment]
Hertest:
Nu een PDF en een Word document te verwijderen zonder foutpagina te krijgen
