### ISSUE TITLE
BUG: ontkoppelde documenten kunnen niet verwijderd worden

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1593]
***Steps to reproduce:***

1. ga naar ontkoppelde documenten werklijst
2. open een document vanuit de werklijst 
3. verwijder het document

***Expected***
document wordt verwijderd

***Actual***
blijft hangen op de pop-up

**Comment by RoyBuis** [comment]
### Refinement 15-9

Foutmelding: TypeError: Cannot read properties of undefined (reading 'uuid')

Aanpassingen bij verwijderen van een ontkoppeld document:
- er hoeft geen reden opgegeven te worden (deze kan nergens bewaard worden)
- een 'weet u het zeker?' dialog tonen 
- na verwijderen terugkeren naar Werklijst 'Ontkoppelde documenten'

**Comment by jeroen-dekker** [comment]
Besproken met Roy, lijkt al gefixt te zijn op Develop omgeving.
