### ISSUE TITLE
Mijn Zaken toont default nog afgehandelde zaken

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1594]
***Als*** zaakbehandelaar

***Wil ik*** alleen mijn openstaande zaken zien

***Zodat*** ik weet welk werk ik nog moet doen

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Via #434 is de functionaliteit van Mijn zaken opgeleverd en beschreven. Met dit issue zijn de beëindigde zaken uit de werklijst gehaald omdat deze werklijst zich focust op lopende zaken. Voor beëindigde zaken kan de gebruiker de werklijst 'Afgehandelde zaken' gebruiken en daar filteren op Behandelaar.
***Belangrijkste functionaliteiten:***
- nvt
-

**Comment by robertverboom** [comment]
evt oplossen met checkboxen zodat je meerdere statussen tegelijk kan tonen

**Comment by RoyBuis** [comment]
### Refinement 15-9

Te realiseren

- In MIjn zaken alleen openstaande zaken tonen

Als een gebruiker zijn eigen afgehandelde zaken wilt zien dan kan de lijst 'afgehandelde zaken' gebruikt worden met filter op eigen naam.

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
alleen openstaande zaken op Werklijst Mijn Zaken.: OK
