### ISSUE TITLE
BUG: Selectie in zaakafhandelparameters werken niet op afronden van een fase

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1597]
***Steps to reproduce:***

1. Ga naar zaak afhandelparameters
2. verander de status mail afhandelfase in 'niet beschikbaar' of 'standaard aan'
3. ga naar een zaak en handel de in behandeling af

***Expected***
wanneer je een zaak afhandelt, verwacht je wat je geselecteerd hebt te zien

***Actual***
Je blijft de optie houden dat de mail optioneel is. 

Lijkt op  #1596

**Comment by jeroen-dekker** [comment]
Gefixt in https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1596

**Comment by robertverboom** [comment]
test ok
