### ISSUE TITLE
BUG: Bij zaak afhandelen kan het verplichte veld resultaat leeg gelaten worden

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1598]
***Steps to reproduce:***

1. maak een zaak melding klein evenement aan
2. rond de zaak af zonder besluit
3. 

***Expected***
Indien besluit niet verplicht is, wordt de zaak afgesloten

***Actual***
krijgt een 500 terug: 
(404) Title: Niet gevonden., Detail: Niet gevonden.

**Comment by marcoatos** [comment]
Bovenstaand issue komt niet meer voor. We hebben wel gezien dat we nog steeds de zaak kunnen afronden zonder de verplichte resultaat in te voeren. Dus dat wordt nu opgepakt in dit issue
