### ISSUE TITLE
Aanmaken documenten (via Smartdocuments): Deel 2

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1599]
N.a.v. de eerste testen en de eerste indrukken is er een sessie geweest met SmartDocuments om de doorontwikkeling en mogelijkheden te bespreken. Bijgevoegd aan deze story het verslag met de uitkomsten. Voor de volledigheid dit ticket aangemaakt.
Andy moet nog in overleg met Smartdocuments.

***Belangrijkste functionaliteiten:***
- Zie bijlage. Na gesprek van Andy wellicht subtaken laten aanmaken

**Comment by Snijhuis** [comment]
[24-08-2022_Aantekeningen meeting integratie SmartDocs-ZAC.docx](https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/files/9573256/24-08-2022_Aantekeningen.meeting.integratie.SmartDocs-ZAC.docx)

**Comment by andyverberne** [comment]
[https://app.zenhub.com/files/416646145/3dcc4a6f-b4d7-4a2a-9a3b-bd242a9f128c/download](https://app.zenhub.com/files/416646145/3dcc4a6f-b4d7-4a2a-9a3b-bd242a9f128c/download)

**Comment by robertverboom** [comment]
Zorgen dat SD beschikbaar is op de Zandbak

**Comment by RoyBuis** [comment]
### Refinement AV, SN, RV & RB

**Te realiseren**
Subtaak 1: Side panel voor Document maken komt te vervallen. Documenttitel en documenttype worden in de SD bepaald. Bij het klikken op de actie 'Document maken' moet direct SD openen in een nieuw tabblad

Subtaak 2: het 'template group' veld in de xml moet gevuld worden met de 'zaaktype omschrijving' van het zaaktype zodat hierme de link naar de sjabloongroep in SD gelegd kan worden

Subtaak 3:  Historie van zaak en taak aanvullen met de volgende informatie:
  - Gebruikersnaam van de gebruiker die het document heeft gemaakt vastleggen in kolom ‘Door’, deze is nu nog leeg
  - In kolom ‘Toelichting’ standaard de tekst ‘Door SmartDocuments’ of iets dergelijks vastleggen?
Deze informatie moet door SD meegegeven worden, graag met Waruzjan bespreken.
Verder met Waruzjan bespreken of het mogelijk is om het na het afronden van het document door op 'Klaar' te klikken automatisch het tabblad te sluiten.
En bespreken of het mogelijk is om het automatisch downloaden van het document na het afronden een instelling is en uitgezte kan worden.

**Comment by robertverboom** [comment]
Om SD weer werkend te krijgen moeten de volgende items bij SD ingericht worden: 

-  Documenttitel en documenttype
