### ISSUE TITLE
BUG: In Solr wordt zaak niet verwijderd na extern component 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1616]
***Steps to reproduce:***

1. Maak een zaak aan
2. Ga naar open zaak
3. Verwijder deze zaak
4. maak een nieuwe zaak aan in ZAC
5. herindexeer Solr

***Expected***
oude zaak is verwijderd. 
nieuwe aangemaakte zaak+1 ?

***Actual***
Oude zaak staat nog in Solr, nieuwe zaak ook, echter hebben ze beide hetzelfde nummer

**Comment by ronniekoopmans-atos** [comment]
Het lijkt erop dat er geen notificaties worden aangemaakt voor acties binnen de open-zaak admin interface. ook voor het creëren van een zaak, misschien een keer verwijderen mogelijk maken voor een record-manager??
