### ISSUE TITLE
Historie Deel 3

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#162]
lege velden vullen: 
- Datum: wijzigingen van start, streef, fatale
- opschorting
- verdagen
- verlengen
- betaling

**Comment by bartlukens-atos** [comment]
De in de historie gebruikte termen moeten vertaald worden

**Comment by andyverberne** [comment]
De huidige visualisatie van Zaak en Document historie matched niet met de AuditTrailRegel zoals deze wordt gegenereerd door de ZGW Api's.
