### ISSUE TITLE
Notificaties en het wissen van de caches

### ISSUE THREAD

**Issue by ronniekoopmans-atos** [NL-AMS-LOCGOV/zaakafhandelcomponent#1625]
http://open-zaak.default/ref/kanalen/
er zijn 3 notificaties die worden verzonden mbt de objecten die we cachen
Zaaktypen, Informatieobjecttypen en Besluittypen.

Er zijn meer objecten die we cachen en waar we geen notifcaties voor krijgen;
zaaktype-informatieobjecttypen
resultaattypen, statustypen, roltypen

Hoe moeten we hiermee omgaan?

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Is gerealiseerd, issue wordt gesloten.
