### ISSUE TITLE
USER STORY: Groep verdelen in bulk

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#163]
***Als*** werkverdeler

***Wil ik*** naast behandelaren ook een groep als bulk verdelen

***Zodat*** ik een grote hoeveelheid klikwerk voorkom

***

### Acceptance criteria:
- 

***
### Prioriteit

- [ ] Must haves
- [ x ] Should haves
- [ ] Could haves
- [ ] Won't haves

**Comment by edwinlambregts-atos** [comment]
Refinement 20 december:

Werking bij het verdelen:

Groepen en medewerkers staan los van elkaar
Als eerst een groep wordt gekozen dan kan worden alle medewerkers gekoppeld aan de groep getoond in het medewerker veld
Als eerst een medewerkers wordt gekozen dan worden alle medewerkers uit het systeem getoond in het medewerker veld
Een van de twee velden is verplicht

**Comment by edwinlambregts-atos** [comment]
Uiteindelijk opgelost met #158
