### ISSUE TITLE
Laatste versie componenten installeren

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1638]

**Comment by robertverboom** [comment]
vng referentie, Open-zaak, open-notificatie en open-forms

**Comment by andyverberne** [comment]
Nieuwe versie geinstalleerd van:

- [ ] Object registratie
- [ ] VNG Referentie lijsten
- [ ] Open Zaak
- [ ] Open Notificaties
- [ ] Open Forms
