### ISSUE TITLE
Mogelijkheid tot het openen van een extra tabblad vanuit het oog-icoon (rechtermuisknop bijv) #436

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#1640]
Besproken met de refinementwerkgroep op 28-9-2022.

In de acceptatiecriteria is opgenomen: "Gebruiker kan de Zaak | Taak | Contact vanuit de werklijst openen binnen hetzelfde scherm of op een nieuw browsertabblad"
De button 'Zaak bekijken' kent echter geen optie 'Openen op nieuw tabblad' (rechter muisknop menu). Daarom als aceptatiebug toegevoegd.
Oorzaak is mogelijk een huidig technisch probleem om dit te realiseren. Het acceptatiecriterium blijft echter van toepassing waarbij gekeken moet worden of de functie in de toekomst wel mogelijk is.

Deze functie moet in vele schermen (alle waar de button met het oogje voorkomt) gaan werken.

**Comment by VictorTielenius** [comment]
Nu in diverse weklijsten mogelijk om een Zaak / Taak / Document op nieuw tabblad of venster te openen. Met rechtermuisknop en met Ctrl of Shift en klikken.
Ook in Zaak om naar details document te gaan. Of bij Document om met oogje naar zaak te gaan. Dus Oogje overal heeft deze werkwijze nu.
