### ISSUE TITLE
Hard coded business rules realiseren

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#1649]
### Zaak
- [x] Toekenning wijzigen alleen wanneer open
- [x] Verlengen alleen wanneer open en niet heropend en niet opgeschort
- [x] Opschorten alleen wanneer open en niet heropend en niet opgeschort
- [x] Hervatten alleen wanneer opgeschort
- [x] Afbreken alleen wanneer open en niet heropend
- [x] Afronden alleen wanneer open
- [x] Heropenen alleen wanneer gesloten
- [x] Ontvangstbevestiging versturen alleen wanneer nog geen ontvangstbevestiging verstuurd
- [x] Vastleggen besluit alleen wanneer open en nog geen besluit vastgelegd en zaaktype heeft besluittype

### Taak
- [x] Alle acties met uitzondering van lezen alleen wanneer taak niet is afgerond

### Document
- [x] Vergrendelen alleen wanneer niet vergrendeld
- [x] Ontgrendelen alleen wanneer vergrendeld
- [x] Ondertekenen alleen wanneer niet ondertekend

**Comment by robertverboom** [comment]
Test ok
