### ISSUE TITLE
ACCEPTATIE BUG: Bij Streefdatum geen icoontje dat datum is overschreden.

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1669]
**Gebruikersrol:** Behandelaar
**Device:**Laptop
**OS:** nvt
**Browser:**nvt
**Versie:**nvt

**Issuenummer**
#442

**Beschrijf de bug**
Bij Streefdatum geen icoontje dat datum is overschreden.
Een rood driehoekje met uitroepteken is wel aanwezig wanneer de datum is verstreken bij Fatale datum, maar niet bij Streefdatu![Icoon bij Streefdatum.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/5476a397-98c3-4c45-bd39-a0f8d3789a38)m

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1. Op Zaken - Werkvoorraad kijken (in zac.accept) Zie afbeelding
2.
3.
4.

**Verwacht gedrag**
Icoontje (rood driehoekje met uitroepteken zichtbaar bij overschrijden streefdatum

**Daadwerkelijk gedrag**
Geen Icoontje

**Screenshots**
Toegevoegd 1 screenshot

**Foutmelding/Log tekst**
NVT

**Aanvullende informatie**
-

**Comment by VictorTielenius** [comment]
![Icoon bij Streefdatum.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/535b4584-a154-49b6-84cf-aa469caa68c9)

**Comment by robertverboom** [comment]
Verwachting is dat er een geel icoontje met uitroepteken staat.

**Comment by VictorTielenius** [comment]
Geel icoontje is ook goed bij overschreden Streefdatum, als er maar een icoontje komt :)

**Comment by robertverboom** [comment]
graag hertesten

**Comment by VictorTielenius** [comment]
Nu Oranje (of donker gele) driehoek icoontjes met uitroepteken aanwezig bij Overschreden Streefdatums
