### ISSUE TITLE
Mogelijkheid om vastgelegd kanaal aan te passen

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1672]
De mogelijkheid om vastgelegd kanaal aan te passen moet achter een recht komen.
Geldt voor openstaande zaken.

- Beheerder krijgt dit recht
- Recordmanager krijgt dit recht

Voorleggen aan WG R&A

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*

- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by GertrudeKampherbeek** [comment]
userstory is correct beschreven maar het recht moet per gemeente wel ook aan andere rollen kunnen worden toegekend

**Comment by RoyBuis** [comment]
### Refinement 15-11

In de ZAC zit nu geen logica op basis van kanaal dus er kan niets misgaan als een kanaal wordt aangepast. Voor nu stellen we voor om niet aparte rechten aan te maken voor specifieke zaakgegevens en het daardoor ingewikkelder maken.
