### ISSUE TITLE
Zaak- taak- documentdetails openen in nieuw browsertabblad

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#1680]
ZAC #436 US 11.1.3 
In de acceptatiecriteria is opgenomen: "Gebruiker kan de Zaak | Taak | Contact vanuit de werklijst openen binnen hetzelfde scherm of op een nieuw browsertabblad"
De button 'Zaak bekijken' kent echter geen optie 'Openen op nieuw tabblad' (rechter muisknop menu). Daarom label Bug toegevoegd
De rest van de AC's zijn akkoord.

**Comment by Snijhuis** [comment]
Opgepakt in #1640
