### ISSUE TITLE
BUG: pagina in nieuw tabblad of venster openen

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#1681]
***Steps to reproduce:***
ZAC #436 / US 11.1.3
In de acceptatiecriteria van de US  is opgenomen: "Gebruiker kan de Zaak | Taak | Contact vanuit de werklijst openen binnen hetzelfde scherm of op een nieuw browsertabblad"
De button 'Zaak bekijken' kent echter geen optie 'Openen op nieuw tabblad' (rechter muisknop menu). 

***Expected***
In diverse schermen met rechtermuisknop de button met het oogje gebruiken met de rechtermuisknop. Je zou dan de optie moeten zien "Open op nieuw tabblad"

***Actual***
Alleen bij Taakdocumenten werkt dit zo. Verder (vooralsnog) nergens.

**Comment by robertverboom** [comment]
Wordt opgelost met #436
