### ISSUE TITLE
reden meegeven voor het wijzigen van besluiten 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1689]
***Als*** zaakbehandelaar

***Wil ik*** een reden meegeven, waarom ik een besluite heb gewijzigd

***Zodat*** iedereen terug kan lezen waarom een besluit gewijzigd is. 

***

### Acceptance criteria:
- redenveld verplicht

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #1570 is het wijzigen van een vastgelegd besluit opgeleverd. In deze story is deze functionaliteit uitgebreid door de gebruiker hierbij verplicht een reden van maximaal 80 karakters te laten opgeven. De reden wordt als toelichting opgenomen in de historie van het besluit.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met het potlood icoon op het besluit de gegevens van het besluit wijzigen en hierbij een reden van max 80 karakters invullen
- Het wijzigen van een besluit wordt vastgelegd in de historie van het besluit met de door de gebruiker ingevulde reden als toelichting

**Comment by robertverboom** [comment]
### Refinement 06-10: 
- Redenveld meegeven boven wijzigen knop
- redenveld is verplicht
- max 80 karakters

**Comment by CommonGroundGroningen** [comment]
**Gebruiker kan met het potlood icoon op het besluit de gegevens van het besluit wijzigen en hierbij een reden van max 80 karakters invullen**
Test ok
**Het wijzigen van een besluit wordt vastgelegd in de historie van het besluit met de door de gebruiker ingevulde reden als toelichting**
Test ok
