### ISSUE TITLE
6B.4.1 Handmatig afhandelen van een zaak - DEEL 1

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#169]
***Als*** zaakbehandelaar

***Wil ik*** een zaak op elk moment handmatig kunnen afhandelen 

***Zodat*** ik een zaak sneller kan afhandelen zonder alle openstaande of nog te starten taken te moeten doorlopen. (bijv in geval van dubbele zaak) en de zaak niet meer in de werkvoorraad wordt getoond. 

***

### Acceptance criteria:

- De behandelaar moet een reden selecteren bij het handmatig afhandelen op basis van een keuzelijst (gekoppeld aan resultaten die zijn vastgelegd bij het zaaktype)
- De behandelaar kan een toelichting geven in een tekstarea (optioneel)
- Op basis van de keuze wordt de zaak afgehandeld en krijgt het juiste resultaat/status

(OUDE CRITERIA, nog op te pakken later)
- #189 
- Bij het handmatig afhandelen moet het resultaattype moet worden gekozen. Alleen resultaattypen tonen die bij het zaaktype zijn vastgelegd.
-  #188
- #190 
- #191
- Bij het handmatig afhandelen van de zaak moet de juiste bewaartermijn en datums (einddatum, reviewdatum en vernietigingsdatum) automatisch worden gevuld.  
~~De handmatige afhandeling moet worden vastgelegd bij de historie van de zaak zodat deze informatie zichtbaar is bij een eventuele kwaliteitscontrole.~~ ~zie ticket 190
~~Bij het kiezen van de eindstatus, het resultaattype en het besluit worden alleen de waarden getoond zoals die bij het zaaktype zijn vastgelegd.~~

***
### Prioriteit

- [ ] Must haves

***
### Gerealiseerd
Bij de Zaakafhandelparameters is optie 4; Zaakbeëindig gegevens toegevoegd. Hier kunnen de 3 redenen aangevinkt worden met een bijbehorend resultaat. Wanneer reden is aangevinkt, is resultaat verplicht. Als alles uitgevinkt wordt, zal de zaak afbreek functionaliteit niet getoond worden. 
Zaak afbreken wordt gerealiseerd in #504

**Comment by robertverboom** [comment]
Wanneer een zaak handmatig wordt afgehandeld:
- Wordt data van de taak van dat moment opgeslagen en de taak blijft als 'read only' raadpleegbaar. (zie afgeronde taken)
- Alle openstaande taken krijgen de status: 'Afgebroken'

**Comment by RoyBuis** [comment]
Refinement 20-1:
UI:
- Knop beschikbaar maken in linkermenu. Naam van knop: 'Zaak afbreken'
- Gebruiker kiest reden uit lijst. 
- Annuleerknop is ook beschikbaar

Openstaande taken:
- ingevulde velden blijven bewaard en zijn te raadplegen
- taak krijgt bij handmatig afhandelen van de zaak de status 'Afgerond' maar wordt getoond als 'Afgebroken'. Evt ook verdere visuele verduidelijking maken.

Case model:
- Lopende case moet worden afgesloten

Configuratie in zaakafhandelparameters:
- Per zaaktype de 'reden van beeindiging' kunnen inrichten
- Aan een reden moet het bijbehorende resultaat gekoppeld worden. Resultaten komen uit Open zaak.
- Eindstatus is bepaald door het zaaktype in Open zaak dus kan niet geconfigureerd worden

Historie van zaak:
- Reden van afbreken opnemen. Wijziging = resultaat, Toelichting = gekozen van reden afbreken

**Comment by bartlukens-atos** [comment]
in sprint Jan 27 - Feb 9

Configuratie in zaakafhandelparameters:

- Per zaaktype de 'reden van beeindiging' kunnen inrichten
- Aan een reden moet het bijbehorende resultaat gekoppeld worden. Resultaten komen uit Open zaak.
- Eindstatus is bepaald door het zaaktype in Open zaak dus kan niet geconfigureerd worden

**Comment by hansmarks** [comment]
De mogelijke beeindigredenen staan dus in een nieuwe referentietabel. En die tabel is gevuld met de redenen die Roy heeft aangeleverd maar er is (nog) geen scherm om de inhoud van die tabel te beheren.

De mogelijke resultaattypen bij die redenen komen van het zaaktype. Als het zaaktype geen resultaattypen heeft kunnen er ook geen beeindigredenen aan gekoppeld worden omdat daarbij een resultaat verplicht is.

**Comment by robertverboom** [comment]
test ok

**Comment by CommonGroundGroningen** [comment]
- [] De behandelaar moet een reden selecteren bij het handmatig afhandelen op basis van een keuzelijst (gekoppeld aan resultaten die zijn vastgelegd bij het zaaktype)
- [] De behandelaar kan een toelichting geven in een tekstarea (optioneel)
- [] Op basis van de keuze wordt de zaak afgehandeld en krijgt het juiste resultaat/status

**Comment by CommonGroundGroningen** [comment]
![image.png](https://images.zenhubusercontent.com/627bbb377405e91bc67a428b/0422bf74-8370-4971-9b7a-0abbbfc9c7d1)

**Comment by CommonGroundGroningen** [comment]
Testresultaat:
- [ ] OK
- [x] NOK

**Comment by CommonGroundGroningen** [comment]
**Testcase 1**
Afhandelen zaak terwijl 1 of meerdere taken openstaan. Reden wordt niet geselecteerd.
**Verwachting**
De zaak kan niet afgehandeld worden.
**Resultaat**
?

**Testcase 2**
Afhandelen zaak terwijl 1 of meerdere taken openstaan. Reden wordt geselecteerd.
**Verwachting**
De zaak kan afgehandeld worden
Zaakhistorie wordt aangepast
Zaak wordt niet meer in de werkvoorraad getoond
**Resultaat**
??

**Testcase 3**
Afhandelen zaak terwijl 1 of meerder taken openstaan. Reden wordt geselecteerd. Toelichting wordt gegeven.
Verwachting
De toelichting kan gegeven worden
De zaak kan afgehandeld wordern
Zaakhistorie wordt aangepast
Zaak wordt niet meer in de werkvoorraad getoond
**Resultaat**
??

**Testcase 4**
Afhandelen zaak terwijl 1 of meerdere taken openstaan. Reden wordt geselecteerd. Toelichting wordt niet gegeven.
**Verwachting**
De toelichting hoeft niet gegeven te worden
De zaak kan afgehandeld worden
Zaakhistorie wordt aangepast
Zaak wordt niet meer in de werkvoorraad getoond
**Resultaat**
??

**Comment by Snijhuis** [comment]
@CommonGroundGroningen Alle gekoppelde issues zijn gesloten. Deze kan ook gesloten worden? Graag even hertesten/ issue sluiten.

**Comment by HilbrandHurtak** [comment]
Gezien de historie van dit ticket heb ik globaal getest.

Kan ik een zaak afbreken, worden de openstaande taken afgerond en kan er een resultaat worden gekozen. Het antwoord is Ja
Kan ik een zaak handmatig afhandelen, worden de openstaande taken afgerond en kan er een resultaat worden gekozen zoals bij de zaak is geconfigureerd. Het antwoord is Ja

Bij de taak zie je niet dat deze door het afbreken of handmatig afhandelen is gesloten. Dat zie je alleen op zaakniveau. In de huidige e-Suite zie je dat ook niet in de taakdetails.

Voor nu werkt het en laten we dit bij een voorloop gemeente maar verder beoordelen en eventueel refinen. 

Info Hans
De mogelijke beeindigredenen staan dus in een nieuwe referentietabel. En die tabel is gevuld met de redenen die Roy heeft aangeleverd maar er is (nog) geen scherm om de inhoud van die tabel te beheren. **HJH: Indien gewenst moet dat later via een user story worden toegevoegd zodat elke gemeente dan dan zelf kan aanpassen**


Getest op de acc met zaak:
Afbreken: ZAAK-2022-0000000180
Handmatig zaak afhandelen:  Zaak afgerond en taken ook. Bij zaak staat in de historie ook de reden bij het veld toelichting. Of de juiste bewaartermijnen zijn gekozen is niet te testen omdat dit in open zaak geconfigureerd is en we hier als testers niets zien. Bij de zaak stond wel een vernietigingstermijn ingevuld. Voor nu dus OK

Zaak afhandelen: ZAAK-2022-0000000181
Zaak kan niet worden afgehandeld bij openstaande taken. Wel kan de zaak met de openstaande taken worden afgebroken. Pas als de openstaande taken zijn afgehandeld kun je de zaak afhandelen. Voor nu dus OK

De werking is nu zo dat als je de zaak versneld wilt afhandelen je de optie Afbreken moet kiezen. Bij het afhandelen moeten alle taken eerst netjes worden afgesloten. Deze werking verschilt met de huidige e-Suite. Feit blijft wel dat er een escape is om een zaak met openstaande taken af te sluiten. Of dit voldoende is moet bij het testen van de ZAC bij een koploper gemeente maar worden beoordeeld.
