### ISSUE TITLE
ACCEPTATIE BUG: actiemenu toevoegen initiator aan zaak

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#1690]
ZAC #386 Persoon koppelen als initiator bij starten nieuwe zaak.

Rol: Gebruiker

Het actiemenu om een initiator toe te voegen aan de zaak zou niet meer aanwezig moeten zijn als er al een initiator gekoppeld is.
Als je bij aanmaken van de zaak een initiator hebt gekoppeld en de zaak is aangemaakt, dan is in het actiemenu de optie nog aanwezig om een initiator toe te voegen. Er kan echter maar één initiator in een zaak zijn, andere personen/bedrijven moeten worden aangemerkt als betrokkenen. 

Het actiemenu om de initiator te verwijderen moet wel aanwezig zijn om een zaak anoniem te kunnen maken.
Als een zaak anoniem is gemaakt moet daarna weer het actiemenu aanwezig zijn om een initiator toe te voegen.

**Comment by Snijhuis** [comment]
Zie ook #1671

**Comment by Snijhuis** [comment]
Opgelost in #1671
