### ISSUE TITLE
ACCEPTATIE BUG: Aanpassen zaakgegeven - Kanaal

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#1692]
**Gebruikersrol:**  Gebruiker

Besproken in de werkgroep Refinement en acceptatie.

In een zaak kun je het Zaakgegeven 'Kanaal' aanpassen. 
Dit was ook in een US opgenomen. 
Bij nader inzien denken we dat dit een risico vormt als in het afhandelproces gebruik wordt gemaakt van kanaalsturing waarop wordt geflowed.
Bijv: als er sprake is van kanaal 'Internet'. Die komen van een e-formulier en in het afhandelproces kunnen op dat kanaal  condities zijn geplaatst. Overigens geldt dat ook bij andere kanalen.

Mogelijk moet dit met rollen/rechten worden afgevangen en in een andere setting nader worden besproken.

**Comment by Snijhuis** [comment]
Reeds gemeld, zie #1672
