### ISSUE TITLE
ACCEPTATIE BUG: Documenten/bestanden toevoegen aan een zaak

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#1693]
**Gebruikersrol:** Gebruiker

**Issuenummer**
Heeft o.a. betrekking op alle US waarin toevoegen, preview, verplaatsen, verwijderen van documenten voorkomt . #1028 , #347, #349, #351, #361, #365, #470, #496, #689, #725
US 7.x.x en 8.x.x

**Beschrijf de bug**
Als je een video-bestand wilt toevoegen aan een zaak dan is dat niet toegestaan omdat in de configuratie de extensie niet is opgenomen. Ook is het (momenteel beperkt tot 80MB). De video wilde ik juist toevoegen om te kijken hoe er met grote bestanden wordt omgegaan in alle situaties waarin acties m.b.t. bestanden uitgevoerd kunnen worden.

**Discussiepunt**
Bij een zaak wordt in het actiemenu vermeld ‘toevoegen document’. Als je dat scherm opent wordt de term ‘bestandsnaam’ gebruikt. Er wordt niet consequent één term gebruikt.
Omdat je niet alleen documenten aan een zaak wilt toevoegen maar ook foto’s, tekeningen, bewegend beeld, lijkt het me beter om consequent uit te gaan van de term ‘bestand’ omdat dit ruimer is. Dus menu-item = ‘Toevoegen bestand’. Naam = ‘bestandsnaam’

**Comment by robertverboom** [comment]
Refinement 06-10:
extensies toevoegen: .mp4 .avi .flv .mpeg .wmv .mkv .mov

**Comment by robertverboom** [comment]
Test ok.
Er zit echter nog geen bestandsgrootte configuratie. Graag rekening mee houden met testen van de diverse formaten

**Comment by HilbrandHurtak** [comment]
De volgende extensies aan zaaknummer ZAAK-2023-0000000002 toegevoegd
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/6f59c7cd-af0e-48bc-99e7-1ca6c635cbe6)

Bestanden zijn redelijk klein. In de toekomst moet ZAC wel grotere bestanden gaan ondersteunen(Omgevingswet is bijvoorbeeld al 250 MB). 

Heb nu ook een bestand van 49 toegevoegd en dat ging snel. Gezien de huidige problemen om grotere bestanden in de e-Suite uit te wisselen(eventueel via MTOM of via API) zou hier wel eens een test mogen worden uitgevoerd.

Opmerking t.a.v. Toevoegen documenten of Toevoegen bestanden laat ik voor nu even los. In de huidige e-Suite heet het ook toevoegen documenten. Als dit later toch ander moet gaan worden dan maken we er wel een user story van
