### ISSUE TITLE
ACCEPTATIE BUG: Zoekfunctie. Overlay toont direct gegevens van alle zaken. 

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#1694]
**Gebruikersrol:** Gebruiker

**Issuenummer**
_Welk issue was je aan het testen? Met een # voor het nummer wordt het een link_

**Beschrijf de bug**
Als ik de menu-optie 'Zoeken' gebruik krijg ik direct in de getoonde overlay zaken te zien en kan door alle aanwezige zaken bladeren. Bij openen van de zoekfunctie zou pas resultaat getoond moeten worden na ingeven van- en zoeken op trefwoorden.

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1. Klik op zoekknop
2. Overlay komt in beeld en toont direct alle aanwezige zaakgegevens

**Verwacht gedrag**
Overlay bevat een veld om zoektermen in te geven en bij gebruik daarvan worden pas zoekresultaten getoond.

**Daadwerkelijk gedrag**
Overlay toont direct gegevens van alle in de e-Suite aanwezige zaken

**Comment by robertverboom** [comment]
### Refinement 13-10:
- Het zoekveld component herbruiken van de werklijsten

**Comment by VictorTielenius** [comment]
Zoekvenster toont pas resultaten bij ingeven zoekterm
