### ISSUE TITLE
ACCEPTATIE BUG: Toon gekoppelde zaak documenten toont code500 error

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#1695]
**Gebruikersrol:** 

**Issuenummer**
nvt. Geconstateerd bij random testen

**Beschrijf de bug**
Als ik in het scherm met een lopende zaak rechts onderaan het schuifje 'Toon gekoppelde zaak documenten' gebruik krijg ik ook een code 500 melding. Als er geen gekoppelde zaak en dus ook geen gekoppelde zaak-documenten zijn, zou daarvan een melding moeten verschijnen maar geen error code 500.

Kwam ook voor in sprintreview van 5-10-2022

**Comment by HilbrandHurtak** [comment]
Opnieuw getest met een zaak zonder een gekoppelde zaak. Foutmelding komt niet meer voor. Wel lukt het koppelen van 2 zaken niet meer. Dit issue is al bij Atos bekend onder nummer

**Comment by HilbrandHurtak** [comment]
Test ok
