### ISSUE TITLE
11.4 Dashboard(cards) instellingen via gebruikersporfiel

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#1697]
***Als*** Gebruiker

***Wil ik*** op het dashboard (Home-pagina) een overzicht kunnen inzien van mijn lopende Zaken | Taken 

***Zodat*** ik na selectie van het dashboardCard en na inloggen op de e-Suite direct een overzicht heb van de mij toegewezen nog te behandelen - Zaken | Taken en deze vanuit het overzicht kan openen 

***

### Acceptance criteria:
•	Gebruiker kan via profielinstellingen selectie maken welk overzichten hij op het dashboard wil zien 
(DashboardCards van Lopende Zaken en/of Taken)
•	DashboardCards kunnen door gebruiker zelf binnen het dashboard op de gewenste plek worden geplaatst/gesleept
•	Betreffende overzichten moeten ook benaderbaar blijven via Zaken>Mijn Zaken en Taken >Mijn Taken

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Could haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze story is het dashboard uitgebreid met 2 kaarten en de mogelijkheid voor een gebruiker om het dashboard zelf in te stellen. In het dashboard kan een gebruiker nu de gegevens over de zaken in de ZAC naar eigen wens en belang in één overzicht organiseren. 

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het dashboard met het schuifje ‘Pas uw dashboard aan’ de bewerkingsmodus activeren
- Gebruiker heeft beschikking over twee nieuwe kaarten: 'Aan mij toegewezen zaken' en 'Aan mij toegewezen zaken'
- Gebruiker kan in de bewerkingsmodus via het dashboardcard toevoegen icoon een kaart toevoegen
- Gebruiker kan in de bewerkingsmodus door op het kruisje in de kaart te klikken een kaart verwijderen
- Gebruiker kan ook via Signalering-instellingen onder het profiel de kaarten die in het dashboard getoond moeten worden selecteren
- Gebruiker kan in de bewerkingsmodus een kaart met de muisaanwijzer oppakken en slepen naar een andere plaats in het dashboard. De plaats waar een kaart geplaatst kan worden wordt visueel aangegeven.

**Comment by robertverboom** [comment]
### Refinement 06-10:
- policy gelijk trekken aan werklijsten
- 2 cards toevoegen: Mijn zaken en Mijn taken
- Optie om dashboard te wijzigen
  - knop om extra dashboard card toe te voegen
  - dashboard card te verwijderen
  - optie om de cards te slepen/ volgorde te bepalen
- Moet worden opgeslagen 
- Wijzigingen moeten ook zichtbaar in signalering-instellingen
- Naam signalering-instellingen wordt gebruikers-instellingen 
  - subkopje met signalering-instellingen

**Comment by CommonGroundGroningen** [comment]
**Gebruiker kan in het dashboard met het schuifje ‘Pas uw dashboard aan’ de bewerkingsmodus activeren**
TEST OK
**Gebruiker heeft beschikking over twee nieuwe kaarten: 'Aan mij toegewezen zaken' en 'Aan mij toegewezen zaken'**
TEST OK
**Gebruiker kan in de bewerkingsmodus via het dashboardcard toevoegen icoon een kaart toevoegen**
TEST OK
**Gebruiker kan in de bewerkingsmodus door op het kruisje in de kaart te klikken een kaart verwijderen**
TEST OK
**Gebruiker kan ook via Signalering-instellingen onder het profiel de kaarten die in het dashboard getoond moeten worden selecteren**
TEST OK
**Gebruiker kan in de bewerkingsmodus een kaart met de muisaanwijzer oppakken en slepen naar een andere plaats in het dashboard. De plaats waar een kaart geplaatst kan worden wordt visueel aangegeven.**
TEST OK
