### ISSUE TITLE
Integratie van OpenZaak /ZAC met Mijn Overheid

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1699]
T.a.v. van de integratie met Mijn Overheid (landelijke voorziening)

- Graag kijken wat de mogelijkheden zijn om lopende zaken te tonen in Mijn Overheid - lopende zaken  (Technisch - Spike)
- Graag kijken wat de mogelijkheden zijn om berichten/ documenten te sturen naar Mijn Overheid - Berichtenbox (Technisch - Spike)

**Comment by andyverberne** [comment]
https://www.logius.nl/diensten/mijnoverheid/documentatie/api-documentatie-lopende-zaken

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Deze wordt via een andere story opgepakt, zie #2483
