### ISSUE TITLE
Open Zaak kent een verlengingstermijn bij zaaktypen: hoe te interpreteren? 

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1703]
In OpenZaak kun je per zaaktype aangeven of verlengen en opschorten mogelijk moeten zijn. Als verlengen mogelijk is kun je ook een verlengingstermijn opgeven. Hoe moeten we deze interpreteren?

- Als de maximale verlengtermijn? Je kunt een maximaal aantal dagen een zaak verlengen. Bij meerdere keren verlengen wordt dan opgeteld.
- Als de vaste verlengtermijn? Dus elke verlenging rekent dat met dit standaard termijn
- Anders? 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by Snijhuis** [comment]
**WG Refinement 19-10**
@GertrudeKampherbeek Gaat dit nog even navragen bij een specialist

**Comment by GertrudeKampherbeek** [comment]
[https://app.zenhub.com/files/416646145/317c9a82-afb5-4e59-aa15-71c07aab39f8/download](https://app.zenhub.com/files/416646145/317c9a82-afb5-4e59-aa15-71c07aab39f8/download)

zie de bijlage. zijn er nog meer vragen dan kan mijn college het jullie ook wel mondeling verder toelichten

**Comment by GertrudeKampherbeek** [comment]
@Snijhuis @robertverboom

**Comment by RikVedder** [comment]
@GertrudeKampherbeek is hier nog een concrete vraag voor WG IB of is dit afgerond?

**Comment by Snijhuis** [comment]
@GertrudeKampherbeek: Issue wordt besproken met Atos deze week

**Comment by RoyBuis** [comment]
### Refinement RV, SN & RB

- Aantekeningen uit documnent van gertrude refinen, deze beantwoorden de oorspronkelijk vragen uit dit issue
- Open zaak bevat momenteel een bug met het instellen van verlengingstermijn waardoor we dit nu niet kunnen testen. Dit wordt opgelost in versie 1.7.5 van Open zaak, zie https://github.com/open-zaak/open-zaak/issues/1275

**Comment by RoyBuis** [comment]
### Refinement 10-11
Mogelijk maken om één maal een verlenging door te voeren waarbij gelet wordt op de maximale verlengingstermijn zoals vastgelegd in het zaaktype. Als een tweede verlenging nodig is dan kan de streef- en fatale datum handmatig worden aangepast. Hierbij wordt geen rekening gehouden met de maximale verlengingstermijn van het zaaktype.

**Te realiseren**

- ZAC staat het toe om een zaak 1 keer te verlengen
- Voor de opgegeven duur wordt gekeken naar zaaktype.verlengingstermijn
- Apart recht (wijzigen doorlooptijd) voor wijzigen streef- en fatale datum (in eerste instantie alleen voor recordmanager, later bespreken bij welke rol(len) dit recht hoort)

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
#175 en #176 gelijktijdig afhandelen als de aanpassing heeft plaatsgevonden op basis van #1703 en #1844

**Comment by HilbrandHurtak** [comment]
@GertrudeKampherbeek ik was begonnen met het testen van de oorspronkelijke tickets. Helaas was daar de info van de refining niet in verwerkt. Ik heb inmiddels de volgende tickets achterhaald:
#175
#176
#1703
#1521
#1848

Tevens heb ik nog een document gevonden waarin je duidelijk het verschil aangeeft t.a.v. verlengen(is dus verdagen) en opschorting en wat vragen stelt over de berekening van de termijnen en de eventuele instelbaarheid per zaaktype.

Gezien je rol bij het refinen lijkt het me verstandig dat jij ook het testen doet. Ik heb het volgende op de zandbak geconstateerd en in de tickets bijgewerkt:

Optie Verlengen op de zandbak doet het niet(aantal dagen mag niet hoger zijn dan 0). Roy pakt dit al op
Op de acc doet verlengen het wel ( bij de  ZAAK-2023-0000000004). Je kunt **oneindig** vaak verlengen. Label verlenging wordt netjes gezet.

Optie Opschorten op de zandbak kan 1 keer worden gekozen en pakt de laatste streef en fatale datum (dus ook nadat je deze een paar keer via verlengen hebt aangepast). Label Opschorten wordt getoond. Alleen optie 'Hervatten' is nog te selecteren.  Na hervatten van de zaak is de knop Opschorting niet meet te selecteren en geeft een duidelijke melding dat dit maar 1 keer mag. De knop Verlengen is weer te selecteren. Je kunt daarna weer eindeloos verlengen

gr 
Hilbrand

**Comment by Sevdiya** [comment]
Bevindingen Hilbrand kloppen. Dit is door mij getest in de Zandbakomgeving.  
Opschorten is 1x te gebruiken. Je zou meerdere malen moeten kunnen opschorten omdat je bij sommige processen op meerdere plekken in een proces iets verwacht van de indiener / externe partij / ketenpartner.

Duidelijk zichtbaar dat de zaak opgeschort is. Knopje hervatten is goed te vinden. Ook fijn dat je kunt aangeven met hoeveel dagen je wil opschorten. Werkdagen ipv dagen zou beter zijn naar mijn mening. 

Opschorten moet een duidelijke knop krijgen aan de linker kant (zoals e-Suite) met een i button wat uitlegt wat het doet / waarvoor het te gebruiken is.

**Comment by yboers** [comment]
Test issue verlengen en opschorten issue 1703-1848
testzaak 2023-0000000075
nadat de zaak is verlengd met 15 dagen blijft de knop (play button) zichtbaar. Als je er met je muis overheen gaat lijkt het net of je de verlengdatum kunt pauzeren. (de pauze knop wordt dan zichtbaar)

**Comment by Sevdiya** [comment]
Test verlengen zaak 130
1. Verlengen met meer dan 30 dagen is niet mogelijk. De max aantal dagen wordt achteraf aangegeven. Graag dit vooraf aangeven bijv. dmv een i button. 
2. Is het max aantal dagen verlengen afhankelijk van het proces? Het mogelijk maken om met een langere periode te verlengen lijkt me wenselijk zoals in bijvoorbeeld proces bezwaar. 
3. Meerdere malen verlengen in een proces indien mogelijk op onderdeel is wenselijk. 
4. Verlengen met max 30 dagen lukt, en ook duidelijk zichtbaar dat het verlengd is in de zaak
5. Play button blijft zichtbaar in de zaak, waarom? Als je met je muis erover gaat krijg je een pauze button wat verwarrend is, zou niet moeten. 
6. Nog een keer verlengen is nu niet meer mogelijk. Heeft dit te maken met de datum waarmee verlengd is? Verlengd tot november, kun je erna wel weer verlengen? En als dat zo is, kan dit dat in het systeem zichtbaar gemaakt worden bijv. dmv mouseover of anders.

**Comment by GertrudeKampherbeek** [comment]
Het systeem doet technisch wat er wordt gevraagd in de userstory, ook aan de hand van de gestelde voorwaarden in het bijgevoegde document. Wat ik hierboven lees kan het op details nog wat 'netter' en/of duidelijker naar de gebruiker worden getoond maar dat laat ik aan de werkgroep.
Gertrude

**Comment by KarinMasselink** [comment]
Het mooie en netter maken van wat getoond wordt gaan we later oppakken bij gebruikerstesten en ui/ux testen. Daarom sluit ik dit issue, aangezien het aan de acceptatiecriteria voldoet.
