### ISSUE TITLE
ACCEPTATIE BUG: Zaak is aan te maken zonder Groep en Behandelaar

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1705]
**Gebruikersrol:**Behandelaar
**Device:**
**OS:** 
**Browser:**
**Versie:**

**Issuenummer**
#287

**Beschrijf de bug**
Zaak aan te maken zonder Groep of Behandelaar. (Zie zaak in zac.accept ZAAK-2022-0000000166)

**Te reproduceren:**
1. Zaak aanmaken en Groep leeg maken
2. 
3.
4.

**Verwacht gedrag**
Verplicht een Groep te moeten kiezen bij aanmaken zaak.

**Daadwerkelijk gedrag**
Verplicht Groep te kiezen bij aanmaken zaak.

**Screenshots**
Er is tenminste 1 screenshot als bijlage toegevoegd: Ja

**Foutmelding/Log tekst**
Nee

**Aanvullende informatie**

**Comment by robertverboom** [comment]
graag hertesten

**Comment by VictorTielenius** [comment]
Hertest gedaan: Bij nieuwe zaak is Groep verplicht en ook dus niet leeg te maken
