### ISSUE TITLE
ACCEPTATIE BUG: In een zaak het wijzigen van Groep naar Leeg geeft foutmelding.

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1706]
**Gebruikersrol:**Behandelaar
**Device:**
**OS:** 
**Browser:**
**Versie:**

**Issuenummer**
#287

**Beschrijf de bug**
In een zaak het proberen te wijzigen van Groep naar Leeg geeft foutmelding.  O.a. ZAAK-2022-0000000167. Zaak staat op Groep A, en met pennetje kan je dit leeg maken. Foutmelding op scherm. Wel is de Groep leeg gemaakt.
Dan ook behandelaar leeg maken (door naam weg te halen of knop Vrijgeven) een fout code 500. 
Behandelaar leeg maken (Vrijgeven) geeft ook fout bij wel een Groep ingevuld te hebben in de zaak.

**Te reproduceren:**
1. Groep leeg maken
2. Dan Behandelaar leeg maken /  Vrijgeven
3. Of Behandelaar Vrijgeven bij wel een Groep aan de zaak te hebben.
4.

**Verwacht gedrag**
Geen fout.
Tenminste moet een Groep aan de zaak gekoppeld zijn. Anders is er een zaak zonder Groep. Alleen te vinden bij Zaken-Werkvoorraad (en dan Kies een groep - Geen groep)

**Daadwerkelijk gedrag**
Foutmelding

**Screenshots**
Er is tenminste 1 screenshot als bijlage toegevoegd: Ja, van fout (400)

**Foutmelding/Log tekst**
Bij Groep leegmaken:
Fout
(400) Title: Invalid input., Detail: Name: nonFieldErrors, Code: invalid-betrokkene, Reason: betrokkene or betrokkeneIdentificatie must be provided

Bij Behandelaar leeg maken:
Foutpagina
De server heeft code 500 geretourneerd
Algemene Fout

**Comment by VictorTielenius** [comment]
![Groep leeg maken bij een zaak.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/d92b938f-732d-43db-bd24-6de1431c08bf)

**Comment by robertverboom** [comment]
### Refinement RB & RV
- Groep verplicht maken bij het aanmaken van een zaak 
- Groep verplicht maken op de zaakgegevenspagina

**Comment by RoyBuis** [comment]
### Refinement 18-10

Aanpassingen:
Zaak aanmaken scherm: groep verplicht maken
Zaak-  en taakgegevensscherm: groep heeft verplicht waarde 

Toe te passen in:

- Zaak aanmaken
- Taak aanmaken
- Zaakgegevensscherm
- Taak aanmaken
- Taakgegevensscherm
- Verdelen zaken en taken (hier is keuze groep niet verplicht)

**Comment by robertverboom** [comment]
Groep is nu verplicht en samengevoegd met behandelaar (deze is overigens niet verplicht)

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by VictorTielenius** [comment]
Hertest gedaan, en nu is bij een zaak de Groep niet leeg te maken
