### ISSUE TITLE
ACCEPTATIE BUG: #1584 samenvatting van documenten in zip toevoegen

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1707]
**Gebruikersrol:**
**Device:**
**OS:** 
**Browser:**
**Versie:**

**Issuenummer** 
#1584

**Beschrijf de bug**
in de acceptatiecriteria en in een commentaar van Jeroen staat hoe de gewenste opmaak van de regel is.

**Verwacht gedrag**
Graag aanpassen naar de omschreven userstory: 
ZAAK-2022-0000002001:
  Inkomend:
    - Titel (bestandsnaam)
    - Titel (bestandsnaam)
Op zich is het wel goed dat ook het documentkenmerk opgenomen is

**Comment by HilbrandHurtak** [comment]
Structuur is nu als volgt
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/a86ef0fc-a8a4-4535-adae-973f0a58f00a)

Document
![image.png]

Samenvatting:
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/ba0e4f5b-78b3-4461-bd4b-5a543d3670dc)(https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/44828df7-b113-4fec-81a4-acbbe578130d)


Test OK
