### ISSUE TITLE
6B.6.1 Notities toevoegen bij een zaak 

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#171]
***Als*** zaakbehandelaar

***Wil ik*** bij het behandelen van een zaak een notitie kunnen toevoegen

***Zodat*** niet zaakinhoudelijke informatie op een eenvoudige wijze kan worden vastgelegd en gedeeld bij een betreffende zaak

***

### Acceptance criteria:
- Het kunnen toevoegen van een notitie bij een zaak 
- Het kunnen toevoegen van meerdere notities 
- Het per notitie tonen van degene die de notitie heeft gemaakt(inclusief het tijdstip)  
- Het tonen van de notities bij een zaak 
- Het kunnen wijzigen van de notities  
- Het kunnen verwijderen van de notities 

***
### Prioriteit

- [ ] Should haves

***
### Gerealiseerd
Op de zaakgegevens pagina is rechts onderin een notitie icoon toegevoegd. Deze opent een scherm waar de behandelaar een notitie kan toevoegen. 

***Belangrijkste functionaliteiten:***
- Het kunnen toevoegen van een notitie bij een zaak 
- Het kunnen toevoegen van meerdere notities 
- Het per notitie tonen van degene die de notitie heeft gemaakt (inclusief het datum)  
- Door middel van een badge op de notitie-icoon wordt het aantal notities weergegeven. 
- Het volgende kan je met een notitie doen: create, read, update, delete

**Comment by robertverboom** [comment]
volledig opgeleverd

**Comment by JosDimpact** [comment]
Opgepakt door Hilbrand (Groningen)

**Comment by HilbrandHurtak** [comment]
Test uitgevoerd.  Het volgende gevonden.

Zoeken op handelsnaam met wildcard geeft foutmelding
![Zoeken bedrijf met wildcard](https://user-images.githubusercontent.com/96229645/164225001-131c3948-4d8b-4eb3-8361-a961bb36cca0.PNG)

Postcode en land ontbreken bij adres
![Postcode en land ontbreken bij vestigingsadres](https://user-images.githubusercontent.com/96229645/164225165-4622e670-e40c-461d-a20f-b9002d9c8e10.PNG)

Koppelen en ontkoppelen wordt niet bij zaakhistorie vastgelegd(3 keer een ander bedrijf gekoppeld)
![Historie voor koppelen en ontkoppelen wordt niet vastgelegd](https://user-images.githubusercontent.com/96229645/164225278-4bc71b2e-eeb1-42e0-9172-fb0fb5587564.PNG)

**Comment by HilbrandHurtak** [comment]
Testcripts

**Voeg een notitie toe:** Notitie wordt bij de zaak opgeslagen

**Voeg meerdere notities toe:** Meerdere notities worden bij zaak opgeslagen

**Open de toegevoegde notitie(s):** Naam van degene die notitie heeft toegevoegd moet zichtbaar zijn Dat geldt ook voor datum, tijdstip en de inhoud

**Zijn er notities bij een zaak aanwezig:** Het icoontje rechts onder bevat nu een getal (gelijk aan het aantal notities)

**Wijzig een notitie:** De inhoud van de notitie moet gewijzigd zijn. Controleer ook of de naam van degene die de notitie heeft gewijzigd is verwerkt. Dat geldt ook voor de datum en het tijdstip waarop dat is gedaan.

**Verwijder notitie(s):** Minder notities. Bij 0 notities moet het icoontje weer geen waarde tonen.

**Testresultaat:**

- [ ] OK
- [ ] NOK

### Bevindingen
Toelichting:
