### ISSUE TITLE
6B.7.1 Personen als betrokkenen bij een zaak 

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#172]
***Als*** zaakbehandelaar

***Wil ik*** bij het behandelen van een zaak personen als betrokkene kunnen toevoegen

***Zodat*** er een beeld bestaat t.a.v.de personen(en in welke hoedanigheid) die betrokken zijn bij de afhandeling van de zaak

***

### Acceptance criteria:
- Het kunnen opzoeken van personen(op naam, adres, BSN)
- Op basis van het zoekresultaat de juiste persoon kunnen koppelen aan de zaak 
- Het kunnen koppelen van een type betrokkenen (Bijvoorbeeld als belanghebbende, gemachtigde, melder, medeaanvrager of plaatsvervanger) 
_- Het kunnen bepalen of een betrokkene ook de zaak gerelateerde correspondentie moet ontvangen_ (deel 2)
- Een algemene toelichting kunnen toevoegen bij de betrokkene 
- Het tonen van de geregistreerde betrokkenen bij een zaak (inclusief de datum waarop de koppeling is aangebracht 
- Het kunnen ontkoppelen van een betrokkenen bij een zaak 
- In de historie van de zaak moet de actie van het (ont)koppelen zichtbaar zijn  

***
### Prioriteit

- [ ] Should haves

NB. Afhankelijk van de ontsluiting van basisregistraties Personen
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een betrokkene kan handmatig aan een zaak worden toegevoegd op een vergelijkbare wijze als het toekennen van een initiator. De persoon kan gezocht worden waarbij gebruik gemaakt wordt van de Basisregistratie Personen (BRP) Bevragen API. Na het toevoegen is de persoon als rol aan de zaak toegevoegd. Het is tevens mogelijk een betrokkene te verwijderen. Een zaak kan meerdere betrokkenen hebben.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het menu met de actie [Betrokkene toevoegen] het zoekscherm openen
- Een persoon kan gezocht worden op (een combinatie van) bsn, geslachtsnaam, geboortedatum, postcode/huisnummer en gemeentecode. Minimaal twee van deze zoekvelden moeten gebruikt worden bij een zoekopdracht.
- Gebruiker selecteert de persoon door in de lijst van zoekresultaten op het poppetje icoon te klikken. Hierna is de persoon zichtbaar in de tab 'Betrokkenen' van het zaakgegevensscherm.
- Gebruiker kan in de tab 'Betrokkenen' met het prullenbak icoon een betrokkene verwijderen
- Het toevoegen en verwijderen van een betrokkene wordt als wijziging van een persoon met vermelding van BSN vastgelegd in de historie van de zaak. Ook de opgegeven toelichting is hierin terug te vinden.

**Comment by VictorTielenius** [comment]
Gebruiker kan in het menu met de actie [Betrokkene toevoegen] het zoekscherm openen: OK
Een persoon kan gezocht worden op (een combinatie van) bsn, geslachtsnaam, geboortedatum, postcode/huisnummer en gemeentecode. Minimaal twee van deze zoekvelden moeten gebruikt worden bij een zoekopdracht. (Zie #293 mbt Bugs zoeken initiator)
Gebruiker selecteert de persoon door in de lijst van zoekresultaten op het poppetje icoon te klikken. Hierna is de persoon zichtbaar in de tab 'Betrokkenen' van het zaakgegevensscherm.: NOK. Alleen hier BSN te zien, geen naam.
Gebruiker kan in de tab 'Betrokkenen' met het prullenbak icoon een betrokkene verwijderen": OK
Het toevoegen en verwijderen van een betrokkene wordt als wijziging van een persoon met vermelding van BSN vastgelegd in de historie van de zaak. Ook de opgegeven toelichting is hierin terug te vinden.
Bij Historie in bij Toevoegen Betrokkene niet te zien dat het een betrokken is, alleen Persoon, BSN en Toelichting.
Toelichting verplicht (Zou dit optioneel moeten zijn?, zie Acc. Criteria)
Betrokkenheid: Nu 6 keuzes. Maar andere dan ik Acc. Criteria

**Comment by HilbrandHurtak** [comment]
Test personen: https://www.rvig.nl/brp/documenten/richtlijnen/2018/09/20/testdataset-persoonslijsten-proefomgevingen-gba-v

**Comment by KarinMasselink** [comment]
De set die door Atos wordt gebruikt is hier te vinden (voor zekerheid even gedeeld, waarschijnlijk wel dezelfde): https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/wiki/Testdata

**Comment by yboers** [comment]
getest resultaat:
Het kunnen opzoeken van personen(op naam, adres, BSN) = ok
Op basis van het zoekresultaat de juiste persoon kunnen koppelen aan de zaak = ok 
Het kunnen koppelen van een type betrokkenen (Bijvoorbeeld als belanghebbende, gemachtigde, melder, medeaanvrager of plaatsvervanger) = ok
Een algemene toelichting kunnen toevoegen bij de betrokkene = oke
Het tonen van de geregistreerde betrokkenen bij een zaak (inclusief de datum waarop de koppeling is aangebracht = oke
Het kunnen ontkoppelen van een betrokkenen bij een zaak = oke
In de historie van de zaak moet de actie van het (ont)koppelen zichtbaar zijn = oke

**Comment by HilbrandHurtak** [comment]
Personen toegevoegd (via klikken op ... worden de actuele gegevens opgehaald conform uitgangspunt HaalCentraal_
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/a61268d2-213c-4618-ac07-f56e801c9e3a):  
**Test OK**

Na verwijderen van een betrokkene wordt de verplichte reden bij de historie opgenomen(verkort en via mouse over de lange versie)
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/5a54fcc5-4862-46c1-b8be-fe5c09d8bfdc)
**Test OK**
