### ISSUE TITLE
E-mail component voor platform tbv mailtemplates, inrichting (af)zendadressen, etc

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1720]
***Achtergrond***
Vanuit de diverse componenten/oplossingen worden e-mails verzonden naar klanten (inwoners/bedrijven), ketenpartners en collega's. Zoals:
- e-mails over de voortgang van zaak (statusmails)
- e-mails vanuit het proces over de inhoudelijke behandeling
- e-mails als notificatie (bijv nieuwe gebruiker aangemaakt)
- e-mails met zaak informatie (en zaakdocumenten)
- Etc..

**Waarom belangrijk?**
- Het is voor gemeenten belangrijk dat ze deze mails kunnen vormgeven qua styling en tekst zodat er op een vertrouwde en herkenbare manier gecommuniceerd kan worden met de klanten, partners en collega's. Denk aan herkenbare teksten, verzend,- en afzendadressen, logo's/opmaak,
- Daarnaast moet het beheer van de e-mails niet verspreid liggen maar zoveel mogelijk centraal. Daarmee raakt dit component ook een deel van het integraal beheer.

**Eerste stap**
- E-mails rondom en vanuit het ZAC kunnen beheren op een centrale plek
- Generieke opzet die eventueel ook voor andere componenten straks gebruikt kan worden

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Tijdens de zaakbehandeling gebruikt de ZAC een aantal e-mails dat verstuurd wordt, iedere mail heeft een default template dat in het overzicht te herkennen is aan de vink in de 'default' kolom. De mailtemplates kunnen onder Beheerinstellingen vanuit menukeuze ‘Mailtemplates’ benaderd worden. Vanuit het overzicht kan een template ingezien en bewerkt worden.

***Belangrijkste functionaliteiten:***
- Gebruiker kan vanuit het overzicht een template openen om deze te bewerken. Het onderwerp en het bericht van de mailtemplate kunnen bewerkt worden. Het is ook mogelijk om de naam van de mailtemplate te wijzigen.
- Gebruiker kan in een template gebruik maken van de editor waarmee het mogelijk is om opmaak toe te voegen of bijvoorbeeld een link of afbeelding aan het bericht toe te voegen.

**Comment by RoyBuis** [comment]
### Refinement 11-10

**Betreft nu volgende typen mails:**
- e-mails over de voortgang van zaak (statusmails)
- e-mails vanuit het proces over de inhoudelijke behandeling (zaak informatie (en zaakdocumenten) incl 'E-mail versturen'
- e-mails voor signaleringen over zaak, taak en document (3 verschillende templates)

**Te realiseren**

- Optie om mailinrichting te doen toevoegen aan Beheerinstellingen 
- Per mail is er een standaardtemplate beschikbaar
- Het is mogelijk om zelf een template toe te voegen. Hierbij kan gebruik gemaakt worden van parameters, deze zijn inzichtelijk bij het maken van het template
- Bij de zaakafhandelparameters kan voor een zaaktype een ander template dan de standaard worden geselecteerd (indien mogelijk)
- Gebruiker krijgt de inhoud van template te zien en kan deze op een zo gebruiksvriendelijk mogelijke manier aanpassen (wellicht wysiwyg)

**Een template bevat:**
- onderwerp
- body (incl opmaak mogelijkheid obv html)
- default afzender emailadres
- reply to adres

**Beschikbare parameters per type mail**

Zaakstatusmail:
- zaaknummer
- zaaktype
- zaakstatus
- registratiedatum
- startdatum
- streefdatum
- fatale datum
- omschrijving
- toelichting
- naam initiator voorletter, tussenvoegsel, achternaam of bedrijfsnaam (alleen ophalen indien deze in template voorkomt)
- adres initiator (alleen ophalen indien deze in template voorkomt)

Procesmail:
zelfde als zaakstatusmail

Signaleringmail zaak
- zaaknummer
- zaaktype
- zaakstatus
- registratiedatum
- startdatum
- streefdatum
- fatale datum
- omschrijving
- toelichting
- url naar zaak
- toegewezen groep zaak
- toegewezen gebruiker zaak

Signaleringmail taak
- zaaknummer
- zaaktype
- zaakstatus
- registratiedatum
- startdatum
- streefdatum
- fatale datum
- omschrijving zaak
- toelichting zaak
- url naar taak
- toegewezen groep taak
- toegewezen gebruiker taak

Signaleringmail document
- zaaknummer
- zaaktype
- zaakstatus
- registratiedatum
- startdatum
- streefdatum
- fatale datum
- omschrijving
- toelichting
- url naar zaak
- toegewezen groep
- toegewezen gebruiker
- documenttitel
- url naar document

**Comment by robertverboom** [comment]
### Refinement 20-10:
Technisch: 
-

**Comment by CommonGroundGroningen** [comment]
**Optie om mailinrichting te doen toevoegen aan Beheerinstellingen**
Mail voor verschillende doeleinden kunnen worden ingesteld (Overigens niet door mij maar ik vermoed een autorisatie probleem)
Bij beheren mailtemplates kunnen mail templates worden aangemaakt inclusief parameters.

**Per mail is er een standaardtemplate beschikbaar**
Test ok

**Gebruiker krijgt de inhoud van template te zien en kan deze op een zo gebruiksvriendelijk mogelijke manier aanpassen (wellicht wysiwyg)**
Bij het openen van een taak is de voor ingevulde mailtemplate eenvoudig aan te passen
