### ISSUE TITLE
ACCEPTATIE BUG: werklijst Inbox documenten, sorteren kolom "1identificatie"; Foutpagina

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1729]
**Issuenummer**
#1115

**Beschrijf de bug**
Bij op pijl klikken (sorteren) van kolom in werklijst Inbox documenten, "1identificatie" Foutpagina - De server heeft code 500 geretourneerd - Algemene Fout
Naam heeft een 1 ervoor. Nu is de 1 ervoor niet meer aanwezig?? En begin de naam met hoofdletter i. Vreemd. Foutpagina nog wel bij sorteren

**Te reproduceren:**
1. Naar Werklijst Inbox documenten gaan
2. klikken (sorteren) van kolom "1identificatie"

**Verwacht gedrag**
Geen foutmelding
En kolom naam "Identificatie" ipv "1identificatie"
Dus met hoofdletter beginnen en zonder 1.

**Daadwerkelijk gedrag**
Foutpagina - De server heeft code 500 geretourneerd - Algemene Fout

**Screenshots**
nvt

**Foutmelding/Log tekst**
Foutpagina - De server heeft code 500 geretourneerd - Algemene Fout

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by VictorTielenius** [comment]
sorteren van kolom "Identificatie" in werklijst Inbox documenten: Geen foutpagina
