### ISSUE TITLE
6B.7.2 Bedrijven als betrokkenen bij een zaak

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#173]
***Als*** zaakbehandelaar

***Wil ik*** bij het behandelen van een zaak bedrijven/personen als betrokkene kunnen toevoegen

***Zodat*** er een beeld bestaat t.a.v.de bedrijven/personen(en in welke hoedanigheid) die betrokken zijn bij de afhandeling van de zaak

***

### Acceptance criteria:
- Het kunnen opzoeken van bedrijven(op naam, vestigingsadres, vestigingsnummer, en KvK nummer) 
- Op basis van het zoekresultaat het juiste bedrijf kunnen koppelen aan de zaak 
- Het kunnen koppelen van een type betrokkene (Bijvoorbeeld als belanghebbende, gemachtigde, melder, medeaanvrager of plaatsvervanger) 
- Het kunnen bepalen of een betrokkene ook de zaak gerelateerde correspondentie moet ontvangen 
- Een algemene toelichting kunnen toevoegen bij de betrokkene  
- Het tonen van de geregistreerde betrokkenen bij een zaak (inclusief de datum waarop de koppeling is aangebracht 
- Het kunnen ontkoppelen van een betrokkenen bij een zaak 
- In de historie van de zaak moet de actie van het (ont)koppelen zichtbaar zijn

***
### Prioriteit

- [ ] Should haves

NB. Afhankelijk van ontsluiting basisregistratie Bedrijven
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een betrokkene kan handmatig aan een zaak worden toegevoegd op een vergelijkbare wijze als het toekennen van een initiator. Het bedrijf kan gezocht worden waarbij gebruik gemaakt wordt van de Kamer van Koophandel API. Na het toevoegen is het bedrijf als rol aan de zaak toegevoegd. Het is tevens mogelijk een betrokkene te verwijderen. Een zaak kan meerdere betrokkenen hebben.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het menu met de actie [Betrokkene toevoegen] het zoekscherm openen
- Een vestiging van een bedrijf kan gezocht worden op kvk-nummer, vestigingsnummer of handelsnaam. Een rechtspersoon kan alleen gezocht worden op RSIN.
- Gebruiker selecteert het bedrijf door in de lijst van zoekresultaten op het gebouw icoon te klikken. Hierna is het bedrijf zichtbaar in de tab 'Betrokkenen' van het zaakgegevensscherm.
- Gebruiker kan in de tab 'Betrokkenen'met het prullenbak icoon een betrokkene verwijderen
- Het toevoegen en verwijderen van een betrokkene wordt als wijziging van een vestiging met vestigingsnummer of rechtspersoon met RSIN vastgelegd in de historie van de zaak. Ook de opgegeven toelichting is hierin terug te vinden.

**Comment by robertverboom** [comment]
### refinement 11-7:

- Rol aan zaak toevoegen (Zaken API maak een rol aan bij een zaak)
- Type betrokkene = niet_natuurlijk_persoon of vestiging. Wanneer gebruik je welke? 
- Roltype: Dit moet op catalogusniveau vastgelegd worden, roltype ‘belanghebbende’. Daarna moet dit roltype aan zaaktype gekoppeld worden.

**Comment by VictorTielenius** [comment]
Betrokkene toevoegen, bedrijf:
Een vestiging van een bedrijf kan gezocht worden op kvk-nummer, vestigingsnummer of handelsnaam: OK
Aanpassing hoe Betrokkene getoond wordt gaat via ander issue (incl. hoe dit bij Historie getoond wordt)
Verwijderen lukt ook.
