### ISSUE TITLE
BUG: Na heropenen kan je geen besluit meer toevoegen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1732]
***Steps to reproduce:***

1. maak een zaak aan
2. rond de zaak volgens normaal proces af
3. heropen de zaak
4. voeg een besluit toe

***Expected***
Besluit wordt toegevoegd

***Actual***
500 eurro met (400) Title: invalid input., Detail

**Comment by jeroen-dekker** [comment]
Overleg met Robert vanochtend:
Als er nog geen besluit is - zorgen dat besluit aangemaakt kan worden zonder errors
Als er al wel een besluit is - zorgen dat altijd het besluit getoond wordt en gewijzigd kan worden

Als er bij het afronden van een taak automatisch een besluit wordt aangemaakt, even nagaan wat de data daarin is en verder afstemmen met Robert.

**Comment by robertverboom** [comment]
Let op:
Als er al wel een besluit is - zorgen dat altijd het besluit getoond wordt en gewijzigd kan worden (Dit is al wel gerealiseerd) 
Als er bij het afronden van een taak automatisch een besluit wordt aangemaakt, (Deze functionaliteit bestaat nog niet in de ZAC en is verder niet van belang voor dit ticket)

**Comment by robertverboom** [comment]
test ok
