### ISSUE TITLE
Integratie SmartDocuments - Document opslaan

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#1736]

**Comment by andyverberne** [comment]
SmartDocuments slaat het document op als enkelvoudiginformatieobject in Open Zaak. Daarna maakt SmartDocuments een zaakinformatieobject aan om het document te koppelen aan de zaak. Er zou een terugkeer URL in het Registratie element kunnen worden geplaatst waarachter SmartDocuments, na het maken van het zaakinformatieobject, de UUID of URL plakt naar het zojuist aangemaakte zaakinformatieobject. 

Het is misschien zelfs beter als SmartDocuments alleen maar een enkelvoudiginformatieobject aan maakt en de UUID of URL van dat object achter de terugkeer URL plakt. Dan maakt het Zaakafhandelcomponent het zaakinformatieobject. Smartdocuments is uiteindelijk een document creatie tool en het is de verantwoordelijkgeid van het Zaakafhandelcomponent om te beslissen wat er met het document moet gebeuren. Het kan ook zijn dat het document ergens anders voor gebruikt wordt en niet aan een zaak wordt gekoppeld.

**Comment by robertverboom** [comment]
### Refinement 13-10:
- Snackbar met link naar aangemaakt document tonen op zaakscherm
- eventframework en websocketframework moet worden uitgebreid, zodat detail ID mee komt vanuit notificaties

**Comment by robertverboom** [comment]
test ok
