### ISSUE TITLE
6B.9.1 Mail versturen vanuit een zaak

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#174]
***Als*** zaakbehandelaar

***Wil ik*** bij het behandelen van een zaak direct een mail kunnen versturen

***Zodat*** deze mail direct bij de zaak wordt gearchiveerd en ik geen gebruik hoeft te maken van een andere (mail)applicatie 

***

### Acceptance criteria:
- Meerdere documenten moeten kunnen worden geselecteerd en verstuurd. 
- Per zaaktype kunnen bepalen of de mailfunctionaliteit wel/niet beschikbaar moet zijn
- De mail kan worden verstuurd vanuit het mailadres van de behandelaar.  
- Indien de behandelaar niet zijn eigen e-mailadres wil gebruiken(privacy redenen) zou ook de mail verstuurd moeten kunnen worden vanuit het centraal e-mailadres van de gemeente of een specifiek mailadres van de afdeling of groep 
- De specifieke e-mailadressen van de afdeling of groep moeten alleen geselecteerd kunnen worden als dit bij de configuratie van het zaaktype is bepaald. 
- Bij het opstellen van de mail kan gebruik worden gemaakt van een sjabloon 
- Bij het opstellen van de mail kan ook zelf het onderwerp en de inhoud worden ingevoerd  
- De verzonden mail wordt als document bij de zaak opgeslagen 
- De uitgevoerde acties t.a.v. documenten zijn zichtbaar bij de historie van de zaak 

***
### Prioriteit
- [ ] Should haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Vanuit een zaak kan een e-mail worden verstuurd. De mail is daarna als document aan de zaak gekoppeld waarbij de metadata standaard bepaald worden. Voor de techniek wordt gebruik gemaakt van de Mailjet API.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het menu met de actie [E-Mail versturen] een e-mail maken en verzenden
- Gebruiker kan zelf de ontvanger invullen en het onderwerp en bericht opstellen waarbij gebruik gemaakt kan worden van zaakvariabelen. Het onderwerp wordt tevens de titel van het document.
- Gebruiker kan documenten die aan de zaak gekoppeld zijn als bijlagen aan de mail toevoegen

**Comment by RoyBuis** [comment]
Refinement 24-1:
Mailfunctionaliteit eerst bespreken met de architectuurboard hoe en of dit gewenst is. Komt mailfunctionaliteit bijv voor in de refentiearchitectuur.
Daarnaast ook uitzoeken of er wellicht generieke componenten voor in ontwikkeling zijn.

**Comment by RoyBuis** [comment]
HtD: E-mail: standaarden zijn bekend, denk aan SMTP

**Comment by RoyBuis** [comment]
Refinement 17-2:
Een eerste eenvoudige oplossing maken, die bevat: 
- een knop waarmee je een mail kunt versturen
- gebruiker vult zelf e-mailadres ontvanger in, onderwerp en tekst (body)
- afzender e-mailadres is hardcoded,wordt tijdens bouw duidelijk wat dit gaat worden, alles wat voor een bepaalde domeinnaam staat
- mail als document bij de zaak opslaan als plain tekst
- als documenttype 'E-mail' hardcoded gebruiken
- als documentstatus 'Definitief' hardcoded gebruiken
- als documenttitel het onderwerp van de mail gebruiken
- versturen via Mailjet en bijbehorende API

UI:
- Optie toevoegen in linkermenu onder 'zaak' 
- 'Mail versturen' als naam van de knop

**Comment by robertverboom** [comment]
- De waarden in de historie zijn nog onvertaald. Label wordt al wel vertaald.

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Er is een eenvoudig email functionaliteit waarbij er vanuit een centraal adres mail wordt verstuurd. De mail met bijlage wordt aan het dossier toegevoegd(als html maar zou als mailbestand moeten) In de user story werd meer functionaliteit gevraagd. ik heb de user story gespitst t.a.v. de volgende onderdelen:

- De mail kan worden verstuurd vanuit het mailadres van de behandelaar.
- Indien de behandelaar niet zijn eigen e-mailadres wil gebruiken(privacy redenen) zou ook de mail verstuurd moeten 
   kunnen worden vanuit het centraal e-mailadres van de gemeente of een specifiek mailadres van de afdeling of 
  groep zoals dat bij het zaaktype is ingesteld
- De mail inclusief de meegestuurde bijlage moet als "mail" worden toegevoegd bij de zaak. Dat is nu even html 
  zonder de meegestuurde bijlagen

**Comment by HilbrandHurtak** [comment]
De simpele oplossing is ok. De user story is gesplitst isn
#2095
#2096
#2097
