### ISSUE TITLE
EPIC: Documentatie/ handleiding/ overview van ZAC voor overdracht naar Integrator

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1741]
**Als** Dimpact

**Wil ik** De Integrator kunnen voorzien van documentatie/handleidingen over de technische inrichting en de integraties van het ZAC

**Zodat** We de Integrator goed in positie kunnen brengen na de selectie en duidelijk wordt wat de omvang van de werkzaamheden is

NB. Deze epic verder aanvullen met criteria en concrete US.

**Comment by RoyBuis** [comment]
### Onderverdeling documentatie

**ZAC kunnen draaien in een container**
- lijst properties bij de image
- overzicht keuzes integraties (bijv ADFS)

**Gebruik van ZAC**
- functionele werking

**Functioneel beheer van ZAC**
- inrichting zaakafhandelparameters in ZAC

Verdere documentatie later beoordelen en aanvullen.
Voor iedere categorie een user story aanmaken om de documentatie in uit te werken

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Deze stories zijn gerealiseerd, epic kan gesloten worden
