### ISSUE TITLE
Policies nalopen omtrent toekennen/verdelen van zaken

### ISSUE THREAD

**Issue by bartlukens-atos** [NL-AMS-LOCGOV/zaakafhandelcomponent#1749]
Er is momenteel verschil tussen de policies voor het verdelen/vrijgeven van zaken en het toekennen/vrijgeven van een enkele zaak. Er wordt echter wel gebruik gemaakt van dezelfde methode in de restservice. Dit moet even nagelopen worden een waar nodig aangepast. Het zelfde geldt voor taken.

**Comment by RoyBuis** [comment]
### Refinement 18-10

Voor verschillende acties eigen REST call aanmaken met policy check
Overeenkomstige logica in een private method
Dit geldt voor zaken en taken
