### ISSUE TITLE
6B.10.1 Zaak opschorten en hervatten

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#175]
***Als*** zaakbehandelaar

***Wil ik*** bij het behandelen van een zaak de zaak kunnen opschorten en hervatten 

***Zodat*** de doorlooptijd van de zaak wordt gepauzeerd en weer kan worden hervat

***

### Acceptance criteria:
- Het automatisch kunnen opschorten van de termijnen door het ingeven van het gewenste aantal dagen en een reden 
- Alle onderliggende taken dienen ook te worden opgeschort als dit gewenst is (dus optioneel) 
- Het duidelijk tonen van de opschorting van de zaak 
- Het tonen van de datum van opschorting en de datum tot wanneer de zaak is opgeschort 
- Het kunnen hervatten van de termijnen door het invullen van de datum hervatten en een reden 
- Het tonen van de datum waarop en de reden waarom een zaak weer is hervat 
- De uitgevoerde acties moeten zichtbaar bij de historie van de zaak.

***
### Prioriteit

Must haves
***
### Gerealiseerd
**Let op: na de oplevering van deze story zijn er nieuwe stories gerealiseerd (#1848 en #1521 ) die de functionaliteit hebben veranderd. De beschrijving hieronder is hierop aangepast. Daarnaast hebben stories #1165 en #1940 effect op de werking van deze story**
 
_Omschrijving van de op te leveren functionaliteit in deze story_
De streef- en fatale datum van een zaak kunnen vanuit de zaakgegevenspagina eenmalig opgeschort worden. De behandelaar kan zelf de verwachte duur (in kalenderdagen) van de opschorting invullen waarmee het systeem de nieuwe verwachte streef- en fatale datum berekent. De zaak kan daarna door de behandelaar hervat worden waarna het werkelijke aantal dagen dat de opschorting heeft geduurd bij de oorspronkelijke streef- en fatale datum wordt opgeteld.

***Belangrijkste functionaliteiten:***
- Gebruiker kan op de zaakgegevenspagina met de knop [Zaak opschorten] een zaak opschorten.
- Gebruiker kan bij het opschorten het aantal kalenderdagen invullen of de verwachte einddatum van de opschorting invullen
- Gebruiker is verplicht om een reden voor de opschorting in te vullen
- Gebruiker kan op de zaakgegevenspagina met de knop [Zaak hervatten] een zaak hervatten. Het daadwerkelijke aantal dagen dat de opschorting geduurd heeft wordt bij de oorspronkelijke streef- en/of fatale datum opgeteld
- De knop om een zaak op te schorten kan eenmalig gebruikt worden en wordt na gebruik disabled weergegeven met een toelichting.
- De opschorting en hervatting worden als wijziging van de streef- en/of fatale datum vastgelegd in de historie van de zaak

**Comment by RoyBuis** [comment]
Refinement 17-2:
Stories voor opschorten en verdagen voorleggen aan Open zaak /Zaken API beheerder

De vraag is wat wij functioneel willen maken hoe dat via de API's in Open zaak vastgelegd moet worden:
aanpassing streef en fatale datum?
aanpassing verlenging velden?

Actie: @RoyBuis en @Snijhuis formuleren de vraag voor zowel de opschorten als verdagen stories en maken issue aan via Github bij VNG-Realisatie / gemma-zaken. https://github.com/VNG-Realisatie/gemma-zaken/issues

**Comment by RoyBuis** [comment]
Update: issue is aangemaakt, zie https://github.com/VNG-Realisatie/gemma-zaken/issues/1953
Er is nog geen reactie ontvangen

**Comment by robertverboom** [comment]
Reactie: https://github.com/VNG-Realisatie/gemma-zaken/issues/1953#issuecomment-1089979184

**Comment by RoyBuis** [comment]
Refinement 11-4:
Te realiseren:

- gebruiker kan via een icoon (rechtsboven de datumvelden) bij de datumvelden het opschorten dialoogvenster openen
- in het venster kan gebruiker aantal dagen en reden opgeven, de datumvelden zelf zijn disabled
- dagen betreft kalenderdagen
- aantal dagen en reden als velden naast elkaar
- Bij het invullen van aantal dagen worden de datumvelden aangepast zodat gebruiker de nieuwe datums kan zien
- Redenveld is verplicht en krijgt als placeholder 'reden opschorten'
- als een zaak opgeschort is dan kan gebruiker via icoon de zaak hervatten
- bij hervatten is een reden verplicht, krijgt als placeholder 'reden hervatten'
- zowel opschorten als hervatten opslaan in historie (reden, datum oud en nieuw en gebruiker die wijziging heeft gedaan)
- als zaak is opgeschort dan een indicatie tonen, Robert en Bart bespreken dit




Technisch:

- In Open zaak de 'indicatie opgeschort'en 'reden opgeschort' vullen
- Datum en tijd van opschorten in een case variabele van type 'localdate'. Naam = datumTijdOpgeschort
- Aantal dagen opschorting in een case variabele van type 'integer'. Naam= verwachteDagenOpgeschort

**Comment by HilbrandHurtak** [comment]
Volgens toelichting van Roy zou ook het opschorten meerdere keren moeten kunnen ( Zie #176 ) 
Voor het verlengen is dat wel gerealiseerd maar voor het opschorten niet. @Snijhuis kun jij aangeven wat het moet worden?

**Comment by HilbrandHurtak** [comment]
Zie #1703 en # #1848. Functionaliteit is dus gewijzigd. Was handig geweest om de verwijzing te maken richting deze tickets

**Comment by HilbrandHurtak** [comment]
@GertrudeKampherbeek ik was begonnen met het testen van de oorspronkelijke tickets. Helaas was daar de info van de refining niet in verwerkt. Ik heb inmiddels de volgende tickets achterhaald:
#175
#176
#1703
#1521
#1848

Tevens heb ik nog een document gevonden waarin je duidelijk het verschil aangeeft t.a.v. verlengen(is dus verdagen) en opschorting en wat vragen stelt over de berekening van de termijnen en de eventuele instelbaarheid per zaaktype.

Gezien je rol bij het refinen lijkt het me verstandig dat jij ook het testen doet. Ik heb het volgende op de zandbak geconstateerd en in de tickets bijgewerkt:

Optie Verlengen op de zandbak doet het niet(aantal dagen mag niet hoger zijn dan 0). Roy pakt dit al op
Op de acc doet verlengen het wel ( bij de  ZAAK-2023-0000000004). Je kunt **oneindig** vaak verlengen. Label verlenging wordt netjes gezet.

Optie Opschorten op de zandbak kan 1 keer worden gekozen en pakt de laatste streef en fatale datum (dus ook nadat je deze een paar keer via verlengen hebt aangepast). Label Opschorten wordt getoond. Alleen optie 'Hervatten' is nog te selecteren.  Na hervatten van de zaak is de knop Opschorting niet meet te selecteren en geeft een duidelijke melding dat dit maar 1 keer mag. De knop Verlengen is weer te selecteren. Je kunt daarna weer eindeloos verlengen

gr 
Hilbrand

**Comment by HilbrandHurtak** [comment]
Roy heeft inmiddels de zandbak nu goed ingericht. De acc heeft nog problemen en daar kan nu nog onbeperkt worden verlengd.

Op de zandbak werkt het nu als volgt:
Opschorting mag maximaal 1 keer. Bij 2e keer wordt er een melding gegeven. Wel via potlood fatale termijn wijzigen
Verlengen 1e keer via knopje met max 30 dagen.  Daarna door aanpassing van fatale termijn via potlood. Geen hervatting mogelijk

@GertrudeKampherbeek wil jij dit ook testen?

**Comment by yboers** [comment]
op acceptatie van ZAC issue 1703 getest opschorten en verlengen met zaaknummer 2023-0000000075.
Opschorten mag op de acceptatie-omgeving maximaal 1 keer. Dit moet meerdere keren in een proces mogelijk zijn. Tevens ontbreekt een melding dat er al een keer is opgeschort. Kortom de bevindingen van Hilbrand zijn correct. In de huidige eSuite is het opschorten en hervatten van een zaak duidelijker en logischer ingebouwd.

**Comment by Sevdiya** [comment]
Het opschorten en hervatten kan 1x  dit hebben we getest, resultaat is positief.
