### ISSUE TITLE
Gebruikers | Documentatie/ handleiding functionele werking

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1752]
***Als*** Gebruiker

***Wil ik*** Functionele documentatie/ handleidingen hebben voor het gebruik van het ZAC

***Zodat*** Weet welke functionaliteiten er zijn en hoe deze gebruikt kunnen worden

***

### Acceptance criteria:
- De documentatie graag op één centrale plek aanbieden en bijwerken zodat gebruikers altijd over de laatste informatie beschikken

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Voor de gebruikers van de ZAC is een handleiding gemaakt dat alle functionaliteit beschrijft rondom het werken met zaken in de ZAC vanuit de gebruiker gezien.
De handleiding bevat een overzicht van de werking van de onderdelen van de ZAC zoals het dashboard, de werklijsten en de zoekfunctie. Het grootste deel bestaat uit een beschrijvingen van de opzet van en de mogelijkheden die er zijn bij het behandelen van een zaak.
De handleiding is in PDF formaat beschikbaar in de Beyond23 Algemeen groep op SAM.

***Belangrijkste functionaliteiten:***
Niet van toepassing

**Comment by HilbrandHurtak** [comment]
Handleiding voor beheer staat in github: https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/blob/main/docs/Inrichting%20Zaakafhandelcomponent.md

Handleiding voor medewerker staat op SAM: https://sam.dimpact.nl/Project/Beyond23algemeen/Documents?path=%2F01_Koplopergroepen%20componenten%2FKoplopergroep%20ZAC%2FOverige%20documenten

Documentatie wordt periodiek bijgewerkt

**Comment by HilbrandHurtak** [comment]
Dubbel kaartje #1753
