### ISSUE TITLE
Dashboard cards afmaken

### ISSUE THREAD

**Issue by hansmarks** [NL-AMS-LOCGOV/zaakafhandelcomponent#1763]
De organisatie in rijen is niet ideaal. Het is minder intuitief voor de gebruiker en er is extra code nodig die niet nodig zou zijn als de structuur verticaal zou zijn.

Dat kan omgebouwd worden maar dan moet er wel even een keuze gemaakt worden tussen:
- cards met variable hoogte
- alle cards dezelfde vaste hoogte

**Comment by robertverboom** [comment]
eerste optie

**Comment by robertverboom** [comment]
Kijk ook eens naar #1773
