### ISSUE TITLE
Omgeving opschonen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1771]
Het komt vaak voor dat een zaak niet werkt, omdat deze met oude functionaliteiten werkt. Gezien er nu een stabiele omgeving staat, is het wellicht mogelijk om de develop omgeving eens op te schonen?

**Comment by RoyBuis** [comment]
### Refinement 27-10

Nieuwe instantie van Open zaak neerzetten
Daarna:
Technische inrichting: variabelen
Functionele inrichting: zaaktype, zaakafhandelparameters

Documentatie maken van zowel technische als functionele inrichting in Github

**Comment by ronniekoopmans-atos** [comment]
Na het opschonen **MOET** IndexeerService.markAllInformatieobjectenForReindexing worden aangepast

**Comment by robertverboom** [comment]
Nieuwe versie van Open Zaak 1.7.5 is beschikbaar op GitHub
