### ISSUE TITLE
websockets op cards

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1797]
***Als*** Behandelaar

***Wil ik*** Websockets op mijn dashboards cards hebben staan

***Zodat*** ik mijn dashboardscherm aan kan laten staan, zonder hem telkens te moeten refreshen. Zo heb ik gelijk in de gaten of ik signaleringen binnen krijg

***

### Acceptance criteria:
-

***
### Prioriteit
- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De werking van de kaarten op het dashboard is verbeterd door deze automatisch te laten updaten als er wijzigingen zijn in de gegevens op de kaarten.
***Belangrijkste functionaliteiten:***
- Gebruiker ziet wijzigingen in de gegevens op de kaarten direct in beeld verschijnen

**Comment by RoyBuis** [comment]
### Refinement 27-10

**Te realiseren**

- Voor de cards met signaleringen moet een signalering komen dat er een signalering is aangemaakt van een bepaald type. Die signalering wordt verwijderd zodra de websocket is verzonden
- Voor de andere cards een periodieke refresh, bijv om 5 minuten

**Comment by HilbrandHurtak** [comment]
Getest OK

Sommige meldingen zijn direct uit het dashboard verdwenen als ik de zaak  in een andere browser open. Andere cards worden inderdaad na max 5 minuten ververst.
