### ISSUE TITLE
Nadenken over een policy/recht op zaaktype

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1812]

**Comment by andyverberne** [comment]
@robertverboom : ik begrijp niet waarom deze al op de Sprint staat? Deze moet toch eerst nog gerefined worden?

**Comment by robertverboom** [comment]
@andyverberne Dit is voor het inrichten voor de instapgemeentes. Als wij weten welke zaaktypes er komen, kunnen de domeinen aangemaakt worden
