### ISSUE TITLE
formulier bij taken in beheer kunnen toevoegen of wijzigingen

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#1818]
***Als*** beheerder

***Wil ik*** zelf de mogelijkheid hebben om een formulier aan te passen of te maken en die kunnen hangen aan een taak (in beheer). 

***Zodat*** je als gemeente zelf, en eventueel per zaaktype, inhoud kan geven aan de informatie die je vraagt aan gebruikers. 

***

### Acceptance criteria:
- deze vraag gaat dus over het formulier dat bij de 'vaste' taken wordt gekozen bij de inrichting en staat los van de ontwikkelingen vanuit de werkgroep PDK

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Deze staat al op de backlog van PodiumD. Issue wordt gesloten.
