### ISSUE TITLE
Kolommen managen op dashboard

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1819]
***Als*** Behandelaar

***Wil ik*** meer dan twee kolommen kunnen zien op mijn dashboardpagina

***Zodat*** op grote schermen, meer gebruik wordt gemaakt van de witruimte

***

### Acceptance criteria:
- Voorkeur dat het responsive wordt, maar instelbaarheid door gebruiker kan ook

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Could haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Er kunnen 1 tot 3 kolommen ingesteld worden

**Comment by RoyBuis** [comment]
### Refinement 15-11

Een derde kolom toevoegen doen we niet want teveel info op die manier

Beter benutten van ruimte op scherm:
- In editmodus verandert er niets
- In niet-editmodus worden lege kolommen onderdrukt en volledige breedte gebruikt
- kijken naar werking van targets bij slepen van kaarten

**Comment by HilbrandHurtak** [comment]
Er kunnen nu maximaal 3 kolommen worden ingesteld De gebruiker kan dit zelf bepalen door in zijn dashboard de signaleringen te verschuiven waardoor zelfs alles in 1 kolom kan worden gezet.
