### ISSUE TITLE
BUG: Pagina nummers worden onjuist/niet getoond

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#182]
***Steps to reproduce:***

1. Ga naar werklijsten, stel je items per pagina op  bijv. 25
2. Pak een zaaktype met veel zaken
3. ga naar laatste pagina
4. Pak een ander zaaktype

***Expected***
werklijst begint te tellen vanaf begin en pagina nummers worden correct getoond. 

***Actual***
Hij blijft ook bij het nieuwe zaaktype op de oude pagina staan. 
Heeft zaaktype A 110 zaken. En zaaktype B heeft er 10, dan ga je bij zaaktype B ook naar pagina 100-110. Geeft hij geen zaak aan en de pagina nummering is onjuist: 101 - 125 van 81

**Comment by bartlukens-atos** [comment]
Oplossing:
Paginanummer resetten indien de zoekcriteria gewijzigd wordt.

**Comment by robertverboom** [comment]
test ok
