### ISSUE TITLE
Facetten op negatief kunnen zetten 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1821]
***Als*** Behandelaar

***Wil ik*** zoeken zonder geselecteerde items

***Zodat*** ik mijn zoekresultaten kan verfijnen

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Na een zoekopdracht ingevoerd te hebben, wordt er een resultatenpanel getoond. Daar kunnen resultaten verfijnt worden dmv facetten aan te vinken. Bij deze facetblokken zit een slider die de waarde op negatief kunnen zetten. 

***Belangrijkste functionaliteiten:***
- De aantallen in de facetblokken blijven positief
-

**Comment by RoyBuis** [comment]
### Refinement 10-11

**Te realiseren**
- toggle introduceren bij facetten waarbij het zinvol is om deze uit te sluiten

**Comment by robertverboom** [comment]
Eerst overleggen met Hans!!!

**Comment by VictorTielenius** [comment]
Dit kan nu: Akkoord
