### ISSUE TITLE
Aantallen achter facetresultaten tonen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1822]
***Als*** Behandelaar

***Wil ik*** aantallen achter facetresultaten zien

***Zodat*** ik weet of ik mijn zoekfunctie moet verfijnen

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Na een zoekopdracht ingevoerd te hebben, wordt er een resultatenpanel getoond. In de facetblokken worden de aantallen per type getoond.

**Comment by RoyBuis** [comment]
### Refinement 10-11
Dit heeft veel impact om dit aan te passen. We zouden een aantal use cases van gemeenten willen hebben zodat we beter kunnen inschatten hoe en of dit moet worden uitgebreid.
sander bespreekt dit met WG refinement en acceptatie.

**Comment by VictorTielenius** [comment]
De Aantallen achter de resultaten in Facet zoeken is wel gewenst.
Zodat je in 1 oogopslag zien bij welk zaaktype / afdeling / behandelaar de gevonden zaken zich bevinden.
Ook reverse zoeken (zoeken zoder geselecteerde items) dmv schuifje bij een facet is ook gewenst.
Zodat je zaaktype / afdeling / behandelaar kan uitsluiten van de zoekresultaten.
Voor openen van gevonden zaak in nieuw tabblad / venster heb ik Bug #1839 aangemaakt. (bij testen #948 tegengekomen)

**Comment by robertverboom** [comment]
Aantallen is meegenomen met een ander ticket en inmiddels gerealiseerd

**Comment by HilbrandHurtak** [comment]
Getest(beperkt tot 1 zaaktype  ivm problemen op zandbak). Telling wordt weergegeven. Test OK

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/cf5cfc55-96a0-4958-b39b-d139f31d1b59)
