### ISSUE TITLE
BUG: Document ontkoppelen vanuit een gerelateerde zaak resulteert in een foutpagina

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1834]
***Steps to reproduce:***

1. Koppel 2 zaken aan elkaar
2. voeg een document toe aan bijv de deelzaak
3. ga naar de hoofdzaak
4. toon de gerelateerde documenten (van de deelzaak)

***Expected***
Het ontkoppel icoontje en knip icoontje worden niet getoond (ook niet als recordmanager)

***Actual***
Beide icoontjes worden getoond. Wanneer een van de acties wilt uitvoeren, resulteert dit in een foutpagina

**Comment by RoyBuis** [comment]
### Refinement 8-11

Bij documenten van gekoppelde zaken de mogelijkheid om te ontkoppelen en verplaatsen weghalen. Dit mag alleen vanuit de zaak waar de documenten bij horen.
