### ISSUE TITLE
ACCEPTATIE BUG: Filter op Groep werkt niet goed (Mijn zaken + Afgehandelde zaken + Zaken-werkvoorraad)

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1838]
**Gebruikersrol:** Behandelaar
**Device:**
**OS:** 
**Browser:**
**Versie:**

**Issuenummer**
#440

**Beschrijf de bug**
Filter op Groep werkt niet goed.
Bij Groep A maar 1 zaak getoond. 
Andere Groepen niet te kiezen.
Bij Kies een Groep geen resultaten
Bij Geen Groep wel alle resultaten (dus met Groep)

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1. Werklijst Mijn zaken / Afgehandelde zaken / Zaken-werkvoorraad openen
2. Groep toevoegen
3. Via uitklaplijstje keuze maken.

**Verwacht gedrag**
Dat het werkt zoals verwacht

**Daadwerkelijk gedrag**
Verkeerde resultaten

**Screenshots**
Kolom Groep

**Foutmelding/Log tekst**
nvt

**Aanvullende informatie**
nvt

**Comment by VictorTielenius** [comment]
![Kolom Groep.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/5733f5d7-44ef-4694-83af-961df42188f2)

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by VictorTielenius** [comment]
Opnieuw getest en werk nu zoals verwacht
