### ISSUE TITLE
ACCEPTATIE BUG: Openen van de gevonden zaak niet mogelijk in nieuw tabblad / venster (via oogje)

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1839]
**Gebruikersrol:** Behandelaar
**Device:**
**OS:** 
**Browser:**
**Versie:**

**Issuenummer**
#948

**Beschrijf de bug**
Openen van de gevonden zaak niet mogelijk in nieuw tabblad / venster (met rechtermuis knop op oogje klikken)

**Te reproduceren:**
1. zoeken op zaaknummer (bijv. ZAAK-2022-0000000171)
2. Bij de resultaten met rechtermuis knop proberen om de zaak te openen in nieuw tabblad / venster

**Verwacht gedrag**
Dat bij alle oogjes je de mogelijkheid hebt om pagina te openen in nieuw tabblad / venster

**Daadwerkelijk gedrag**
Mogelijkheid openen in nieuw tabblad / venster niet aanwezig

**Screenshots**
nvt

**Foutmelding/Log tekst**
nvt

**Aanvullende informatie**
nvt

**Comment by robertverboom** [comment]
### Refinement 01-12:

- Oogje veranderen naar een link

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Kon vanuit het zoekresultaat via het oogje de zaak in een nieuw venster openen
