### ISSUE TITLE
BUG: inbox- en ontkoppelde werklijstfilter kan niet gewist worden

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1845]
***Steps to reproduce:***

1. Ga naar 1 van de documenten werklijsten
2. bewerk de filters
3. wis de filters (middels de trechter)

***Expected***
resultaten en de filters worden geleegd

***Actual***
trechter icoontje reageert niet

**Comment by RoyBuis** [comment]
### Refinement 8-11

- Wissen filters (trechter icoon) mogelijk maken in Ontkoppelde documenten en Inbox documenten werklijsten
- Er is een method die bepaalt of de kolommen gevuld zijn of niet, deze moet waaschijnlijk aangepast worden voor de niet-Solr werklijsten

**Comment by hansmarks** [comment]
Dit kun je nauwelijks een bug noemen, het was nog helemaal niet geimplementeerd op deze twee werklijsten maar blijkbaar was dat nog niemand opgevallen. Nu dus wel.

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Werklijst Inbox documenten + Ontkoppelde documenten: Nu na zoekopdracht is het filter te wissen
