### ISSUE TITLE
BUG: In log wordt er 2x gezocht

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1846]
***Steps to reproduce:***

1. Open serverlog
2. bewerk 1 van de werklijsten

***Expected***
Er wordt 1x gezocht

***Actual***
worden 2 zoekopdrachten uitgevoerd

**Comment by RoyBuis** [comment]
### Refinement 8-11
Lijkt alleen bij filter op datumvelden te gebeuren

**Comment by robertverboom** [comment]
heeft @ronniekoopmans-atos  dit opgelost?

**Comment by hansmarks** [comment]
Niet meer reproduceerbaar. Waarschijnlijk gefixt door de aanpassingen van Ronnie.
