### ISSUE TITLE
Zaak mag één keer opgeschort worden

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1848]
***Als*** organisatie

***Wil ik*** dat een zaak één keer opgeschort kan worden

***Zodat*** voldaan wordt aan juridische voorwaarden en niet meerdere keren kan worden opgeschort

***

### Acceptance criteria:
- systeem zorgt ervoor dat er niet meerdere keren opgeschort kan worden

***
### Prioriteit
- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #175 is het opschorten van de streef- en fatale datum van een zaak vanuit de zaakgegevenspagina opgeleverd. Deze story verfijnt deze functionaliteit door het kunnen opschorten van een zaak maar één maal mogelijk te maken.

***Belangrijkste functionaliteiten:***
- Gebruiker kan een zaak die al opgeschort is geweest niet nogmaals opschorten. Op de zaakgegevensscherm is de 'Opschorten' knop gedeactiveerd en bij de taak 'Aanvullende informatie opvragen' is de optie niet meer beschikbaar.

**Comment by RoyBuis** [comment]
### Refinement RV, SN & RB
Dit issue komt voort uit de aantekeningen van Gertrude uit issue #1703

**Comment by RoyBuis** [comment]
### Refinement 10-11

**Te realiseren**

- ZAC voorkomt dat een zaak die al een keer is opgeschort nog een keer opgeschort wordt. Kijken naar of zaak,redenopschorting gevuld is.
- In zaakgegevensscherm opschorten knop disabelen
- Bij mouseover melding tonen dat zaak al opgeschort is geweest met reden erbij opgenomen

**Comment by HilbrandHurtak** [comment]
@GertrudeKampherbeek ik was begonnen met het testen van de oorspronkelijke tickets. Helaas was daar de info van de refining niet in verwerkt. Ik heb inmiddels de volgende tickets achterhaald:
#175
#176
#1703
#1521
#1848

Tevens heb ik nog een document gevonden waarin je duidelijk het verschil aangeeft t.a.v. verlengen(is dus verdagen) en opschorting en wat vragen stelt over de berekening van de termijnen en de eventuele instelbaarheid per zaaktype.

Gezien je rol bij het refinen lijkt het me verstandig dat jij ook het testen doet. Ik heb het volgende op de zandbak geconstateerd en in de tickets bijgewerkt:

Optie Verlengen op de zandbak doet het niet(aantal dagen mag niet hoger zijn dan 0). Roy pakt dit al op
Op de acc doet verlengen het wel ( bij de  ZAAK-2023-0000000004). Je kunt **oneindig** vaak verlengen. Label verlenging wordt netjes gezet.

Optie Opschorten op de zandbak kan 1 keer worden gekozen en pakt de laatste streef en fatale datum (dus ook nadat je deze een paar keer via verlengen hebt aangepast). Label Opschorten wordt getoond. Alleen optie 'Hervatten' is nog te selecteren.  Na hervatten van de zaak is de knop Opschorting niet meet te selecteren en geeft een duidelijke melding dat dit maar 1 keer mag. De knop Verlengen is weer te selecteren. Je kunt daarna weer eindeloos verlengen

gr 
Hilbrand

**Comment by Sevdiya** [comment]
Issue getest, resultaat is positief. Het klopt dat een zaak maar 1x opgeschort kan worden.
