### ISSUE TITLE
Geen sortering in rijen van de referentietabellen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1854]
***Als*** Beheerder

***Wil ik*** geen alfabetische sortering hebben in de rijen van de referentietabellen

***Zodat*** ik mijn eigen volgorde kan maken, bijv van goed naar slecht

***

### Acceptance criteria:
-

***
### Prioriteit

- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Onder Beheer-instellingen kunnen de referentietabellen beheerd worden. In een geopende referentietabel kan de volgorde van de rijen aangepast worden door de rijen verticaal te slepen.
***Belangrijkste functionaliteiten:***
- Gebruiker kan met de muisaanwijzer via drag en drop de volgorde van de rijen in een referentietabel aanpassen

**Comment by robertverboom** [comment]
test ok

**Comment by CommonGroundGroningen** [comment]
TEST OK
