### ISSUE TITLE
Document informatie in signalering

### ISSUE THREAD

**Issue by marcoatos** [NL-AMS-LOCGOV/zaakafhandelcomponent#1868]
Er is op dit moment geen optie om extra informatie uit een signalering te halen buiten het subject (zaak, taak of enkelvoudig informatieobject). 

Bij een signalering document  op zaak toegevoegd zou je ook de documentinformatie willen weten voor de signalering (met name mail). Hans heeft hier wel het e.e.a. voor gedaan met betrekking tot de websockets. Graag deze uitbreiding ook toepassen voor de signaleringen.

Zodra dit gerealiseerd is zouden we ook de variabelen documenturl en documenttitel kunnen toevoegen aan de mailvariabelen.

**Comment by robertverboom** [comment]
- Document variabelen toevoegen @marcoatos
