### ISSUE TITLE
Doorontwikkeling zaakafhandelcomponent-1577

### ISSUE THREAD

**Issue by jeroen-dekker** [NL-AMS-LOCGOV/zaakafhandelcomponent#1877]
In #1577 zijn er meer opties toegevoegd aan de front-end voor het kiezen van de goedkeuring (in . Omdat deze tekst alleen in de taakdata wordt opgeslagen en verder niet in logica wordt gebruikt, worden de opties in de front-end opgebouwd. Dit gebeurt op een vergelijkbare manier in het `AanvullendeInformatie`-component.
De opties die in deze lijsten worden getoond kunnen in de back-end gedefini&euml;erd worden. Hierbij moet ook worden nagedacht over het toepassen van de vertalingen (staan in de front-end gedefini&euml;erd, maar data komt uit de back-end?). Naast de twee eerder genoemde componenten (`aanvullende-informatie` en `goedkeuren`) zouden andere usages van dezelfde builder ook in andere componenten verder onderzocht worden (zoals `IntakeAfrondenDialogComponent`).

**Comment by robertverboom** [comment]
gefixt
