### ISSUE TITLE
6B4.x. Bij het handmatig afhandelen moet, indien van toepassing, een besluit en ingangsdatum van het besluit worden ingegeven 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#188]
***Als*** Behandelaar

***Wil ik*** Bij het handmatig afhandelen moet, indien van toepassing, een besluit en ingangsdatum van het besluit worden ingegeven 

***Zodat*** het besluit wordt vastgelegd en evt een juiste procestermijn wordt berekend. 

***
### Acceptance criteria:
-  Alleen waarde tonen die bij het zaaktype zijn vastgelegd

***
### Prioriteit

-  x Must haves

**Comment by RoyBuis** [comment]
### Refinement KM, RB en RV
Story is gerealiseerd.
