### ISSUE TITLE
Meerdere besluiten in één zaak toevoegen

### ISSUE THREAD

**Issue by RikVedder** [NL-AMS-LOCGOV/zaakafhandelcomponent#1886]
***Als*** 
Behandelaar

***Wil ik*** 
Meer dan een besluit aan een zaak toevoegen

***Zodat*** 
Meerdere besluiten kan registreren wanneer deze binnen één zaakdossier genomen worden
***

### Acceptance criteria:
- Het moet mogelijk zijn meerdere besluiten binnen een zaak~type~ toe te voegen.

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
**- Must haves**
**- Should haves**
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #1473 is het vastleggen van een besluit bij een zaak opgeleverd. In deze story is deze functionaliteit uitgebreid waardoor het mogelijk is om meerdere besluiten bij een zaak vast te leggen. Als een zaak meerdere besluiten heeft dan wordt de meest recent toegevoegde uitgeklapt weergegeven in het zaakscherm.
Voor het eventueel berekenen van de brondatum wordt het besluit met de maximale vervaldatum gebruikt.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met de actie [Besluit vastleggen] meerdere besluiten bij een zaak vastleggen
- Als bij een zaak meerdere besluiten zijn vastgelegd dan wordt de meest recente opengeklapt weergegeven en kunnen de eerder toegevoegde besluiten met het pijltje uitgeklapt worden
- Het vastleggen van een besluit wordt vastgelegd in de historie van het besluit

**Comment by RoyBuis** [comment]
### Refinement 29-11

**Te realiseren**
- Mogelijk maken om meerdere besluiten toe te voegen. 
- Actie 'Besluit toevoegen' blijft beschikbaar nadat er één is toegevoegd. Let op: policy checks controleren
- Huidige panel van toevoegen besluit actie blijft bestaan zoals die nu is. 
- Bij toevoegen van een volgend besluit dan zaakresultaat voorvullen in het resultaatveld, deze kan door gebruiker worden aangepast. Bij toevoegen volgend besluit wordt ook altijd gekeken naar het gekozen resultaat.
- Als er één besluit is dan wordt deze uitgeklapt getoond in zaakscherm (net als nu). Bij meerdere besluiten dan op vergelijkbare wijze als gerelateerde zaken op het documentgegevensscherm tonen, hierbij is de laatst aangemaakte opengeklapt en staat bovenaan.
- Bij afhandelen zaak wordt gekeken naar besluit met de maximale vervaldatum (wordt in de API logica geregeld)

**Comment by CommonGroundGroningen** [comment]
**Gebruiker kan met de actie [Besluit vastleggen] meerdere besluiten bij een zaak vastleggen**
Test ok
**Als bij een zaak meerdere besluiten zijn vastgelegd dan wordt de meest recente opengeklapt weergegeven en kunnen de eerder toegevoegde besluiten met het pijltje uitgeklapt worden**
Test ok
**Het vastleggen van een besluit wordt vastgelegd in de historie van het besluit**
Test ok
