### ISSUE TITLE
ACCEPTATIE BUG: Gebruik van * bij huisnummer (en ook postcode ingeven) geeft foutpagina 500

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1893]
**Issuenummer**
#293

**Beschrijf de bug**
Gebruik van * bij huisnummer (en ook postcode ingeven) geeft foutpagina 500

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1. Initiator toekennen
2. Zoeken met Postcode (3011KD) en huisnummer (7*)
3. foutpagina verschijnt

**Verwacht gedrag**
Geen foutpagina. En geen blauwe zoekknopp bij gebruik * in huisnummer

**Daadwerkelijk gedrag**
foutpagina 500 verschijnt

**Screenshots**
nvt

**Foutmelding/Log tekst**
Foutpagina
De server heeft code 500 geretourneerd
Algemene Fout
RESTEASY008200: JSON Binding deserialization error: javax.json.bind.JsonbException: Unable to deserialize property 'huisnummer' because of: Error deserialize JSON value into type: class java.lang.Integer.

**Comment by RoyBuis** [comment]
Uitzoeken of het mogelijk is om een validatie op het huisnummer veld toe te passen, zowel bij persoon als bedrijf.

**Comment by robertverboom** [comment]
### Refinement: 
- "Het huisnummer mag alleen bestaan uit cijfers. Eventuele toevoegingen worden ook gevonden."

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by HilbrandHurtak** [comment]
Melding t.a.v huisnummer wordt getoond. Geen 500 melding meer gekregen. Geen zoekresultaten gevonden omdat postcode huisnummer nog niet in de dataset zitten van personen/bedrijven

Test ok
