### ISSUE TITLE
ACCEPTATIE BUG: Zoeken op postcode mogelijk, maar de testpersonen tonen geen postcode

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1894]
**Issuenummer**
#293

**Beschrijf de bug**
Zoeken op postcode mogelijk, maar de testpersonen tonen geen postcode. Zoeken op 3011KD, huisnummer 72 levert wel de testpersonen op. (= postcode van Goudsesingel 72)

**Te reproduceren:**
1. In zoekresultaten bij Toekennen Initiator geen postcode getoond
2. Bij  Initiator geen postcode getoond bij de zaak

**Verwacht gedrag**
Postcode aanwezig bij personen.

**Daadwerkelijk gedrag**
Geen postcode getoond

**Screenshots**
nvt

**Foutmelding/Log tekst**
nvt

**Comment by RoyBuis** [comment]
### Refinement SN, RV & RB

@JosDimpact Net als #814 kan hier de postcode niet opgehaald worden vanwege beperking in de testset. Dit issue testen zodra er volledige gegevens met postcodes opgehaald kunnen worden.

**Comment by JosDimpact** [comment]
@RoyBuis Dan zet ik 'm door naar de kolom 'todo later'

**Comment by robertverboom** [comment]
### Refinement: 
- Uitbreiden met Postcode en Land

**Comment by robertverboom** [comment]
indien het beschikbaar is, wordt dit getoond. Hier de testdata: https://www.rvig.nl/documenten/richtlijnen/2018/09/20/testdataset-persoonslijsten-proefomgevingen-gba-v

**Comment by robertverboom** [comment]
Kan alleen op BSN gezocht worden. Pas na ticket: #2451 worden andere velden beschikbaar.

**Comment by HilbrandHurtak** [comment]
Test personen: https://www.rvig.nl/brp/documenten/richtlijnen/2018/09/20/testdataset-persoonslijsten-proefomgevingen-gba-v

**Comment by VictorTielenius** [comment]
Bij Aanmaken Zaak kan er niet op Postcode gezocht worden
