### ISSUE TITLE
ACCEPTATIE BUG:  tab 'Betrokkenen' van het zaakgegevensscherm.: Alleen hier BSN te zien, geen naam.

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#1895]
**Issuenummer**
#172

**Beschrijf de bug**
Tab 'Betrokkenen' van het zaakgegevensscherm.: Alleen hier BSN te zien, geen naam.

Toelichting verplicht (Zou dit optioneel moeten zijn?, zie Acc. Criteria)

Betrokkenheid: Nu 6 keuzes. Maar andere dan ik Acc. Criteria

Bij Historie in bij Toevoegen Betrokkene te zien: 
18-11-2022
Victor Tielenius
Persoon
-
999992119
TEST VTK

Niet dat dit een Betrokkene is. 
Bij Verwijderen wel te zien dat je een Betrokkene verwijderd hebt:
18-11-2022
Victor Tielenius
Persoon
999992119
-
Betrokkene verwij...

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1. Betrokkene Toevoegen
2. Zie zaak in Accept ZAAK-2022-0000000156
3.
4.

**Verwacht gedrag**
Naam ook getoond bij Tabblad Betrokkenen
Tabblad Historie, Zien dat je een Betrokkene hebt toegevoegd. Bv. bij Toelichting (Betrokkene toegevoegd; Toelichting)

**Daadwerkelijk gedrag**
Alleen BSN

--
**Gerealiseerd**
_De persoonsgegevens worden bewust nergens opgeslagen binnen de ZAC, maar altijd opgehaald vanaf de bron. Het ophalen van de bron kan enige tijd in beslag nemen._

Het volgende is meegenomen in dit ticket: 

- Bij toevoegen en verwijderen van een betrokkene, meldt het roltype als prefix in de historie.
- termen "toevoegen" en "verwijderen" verwijderen uit de prefix
- Om de data op te halen, knopje achter bsn/vestigingsnummer tonen waar gebruiker op moet klikken om de naam op te halen
- Bij verwijderen betrokkene een verplichte reden opgeven.

**Comment by RoyBuis** [comment]
### Refinement SN, RV & RB

- Bij betrokkene toevoegen ook een prefix 'Toegevoegd' in de historieregel opnemen net als bij verwijderen
- Bij tonen betrokkene in tabblad ook de naam laten zien. Bij persoon volledige naam, bij bedrijf Handelsnaam. Volgorde: Rol Naam Type Id Toelichting
- Bij verwijderen betrokkene een verplichte reden opgeven

**Comment by robertverboom** [comment]
_De persoonsgegevens worden bewust nergens opgeslagen binnen het ZAC, maar altijd opgehaald vanaf de bron. Het ophalen van de bron kan enige tijd in beslag nemen._

### Refinement 22-11:
- Bij toevoegen en verwijderen van een betrokkene, meldt het roltype als prefix in de historie. 
- termen "toevoegen" en "verwijderen" verwijderen uit de prefix
- Om de data op te halen, knopje achter bsn/vestigingsnummer  tonen waar gebruiker op moet klikken om de naam op te halen
- Bij verwijderen betrokkene een verplichte reden opgeven.

**Comment by VictorTielenius** [comment]
Toelichting (bij toevoegen betrokkene) is nog verplicht. 
Bij Historie: 
Wijziging: Persoon
Toelichting: TEST VTK (wat je verplicht moet invullen bij Toevoegen Betrokkene)
Bij Historie geen roltype getoond. 
- knopje achter bsn/vestigingsnummer tonen waar gebruiker op moet klikken om de naam op te halen + Bij verwijderen betrokkene een verplichte reden opgeven.: (Nog) Niet in ZAC Accept aanwezig.
Niet te zien dat je een Betrokken hebt toegevoegd (bij Initiator hetzelfde (Persoon), maar bij toelichting: "Initiator toegekend door de medewerker tijdens het behandelen van de zaak" )

**Comment by robertverboom** [comment]
@VictorTielenius ivm dit ticket #2111 loopt de accept omgeving iets achter. Mocht je dit graag nu willen testen, graag testen op de Zandbak en anders wachten tot genoemd ticket is opgelost

**Comment by VictorTielenius** [comment]
Zaak in Accept:
ZAAK-2023-0000000010
Belanghebbende
<onbekend>, <onbekend>, <onbekend>	999992119 (P)

**Comment by robertverboom** [comment]
Wordt hopelijk opgelost met #2258 
Op dit moment kunnen wij geen verbinding maken met HaalCentraal. Bedrijven uit KVK kunnen wel getest worden.

**Comment by KarinMasselink** [comment]
Bug is opgelost.

**Comment by HilbrandHurtak** [comment]
Testpersonen: https://www.rvig.nl/brp/documenten/richtlijnen/2018/09/20/testdataset-persoonslijsten-proefomgevingen-gba-v

**Comment by KarinMasselink** [comment]
De set die door Atos wordt gebruikt is hier te vinden (voor zekerheid even gedeeld, waarschijnlijk wel dezelfde): https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/wiki/Testdata

**Comment by VictorTielenius** [comment]
500 fout bij poging Betrokenne (persoon) toe te voegen aan zaak ZAAK-2023-0000000125
@karinmasselink

**Comment by VictorTielenius** [comment]
In een nieuwe zaak (vandaag aangemaakt). Ik zie nu dat Hilbrand net wel een Betrokkene heeft toegevoegd aan deze zaak.
@karinmasselink @HilbrandHurtak

**Comment by KarinMasselink** [comment]
@HilbrandHurtak  @VictorTielenius  graag even een printscreen van jullie foutmelding toevoegen.

**Comment by HilbrandHurtak** [comment]
@VictorTielenius @KarinMasselink 
Was misschien iets met een gegeven in het BSN?. Heb inmiddels al 5 betrokkenen kunnen toevoegen
![image](https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/assets/96229645/9ee7bf7a-118b-44ea-89de-58add65187da)

**Comment by VictorTielenius** [comment]
![Aantekening 2023-05-23 145250.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/8a71e15a-c8a6-4991-a45b-50bea48c5c48)

**Comment by VictorTielenius** [comment]
![Aantekening 2023-05-23b 145250.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/6b6e4795-5577-4f61-83b3-6d4c6091ea2d)

**Comment by KarinMasselink** [comment]
@VictorTielenius zijn dit oude testset gegevens misschien die je probeert op te voeren of staan deze ook in de testset?

**Comment by HilbrandHurtak** [comment]
@VictorTielenius @KarinMasselink 
Fredje zit niet meer in de testset. Wil je er eentje van deze gebruiken Testpersonen: https://www.rvig.nl/brp/documenten/richtlijnen/2018/09/20/testdataset-persoonslijsten-proefomgevingen-gba-v

**Kan het probleem inmiddels reproduceren:**
Bij het toevoegen van een 2e betrokkenen blijft de eerste selectie in het scherm staan. Als je vervolgens een nieuw foute bsn(in mijn voorbeeldje een geboortedatum) gaat invullen en op de knop zoeken klikt krijg je de 500 melding.
![image](https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/assets/96229645/aa1d6755-9d82-4a46-9abe-a3a81bdc14d8)

**Comment by KarinMasselink** [comment]
@HilbrandHurtak wil je die als apart issue inschieten. Dan meld ik deze nog bij ATOS.

@VictorTielenius graag met andere BSN testen, als dat akkoord is mag dit ticket dicht.

**Comment by HilbrandHurtak** [comment]
@KarinMasselink  Het is bug #2534 geworden. Geef jij dit door aan Atos

**Comment by VictorTielenius** [comment]
Betrokkene (999994359) gekoppeld aan zaak ZAAK-2023-0000000125
En met op de 3 puntjes klikken zijn de volledige gegevens te zien:
Jules Lapidaire, 12‑04‑1946, Eemhavenweg 44, 3089KH, Rotterdam

Fredje Meijden heb ik wel succesvol als Initiator aan deze zaak kunnen koppelen gisteren.
