### ISSUE TITLE
6B.4.X Bij het handmatig afhandelen moeten alle openstaande taken worden afgesloten

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#191]
***Als*** Behandelaar

***Wil ik*** Bij het handmatig afhandelen dat alle openstaande taken worden afgesloten

***Zodat*** Zodat de zaak volledig is afgesloten

***

### Acceptance criteria:
- 

***
### Prioriteit
Should haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een zaak kan met de [Zaak afbreken] actie direct worden beëindigd. Als er taken open staan bij het uitvoeren van deze actie dan worden deze taken automatisch afgerond. Informatie die in de taken al was opgeslagen blijft bewaard. 

***Belangrijkste functionaliteiten:***
- Gebruiker kan met de actie [Zaak afbreken] een zaak direct beëindigen waarmee openstaande taken worden afgesloten
- Gebruiker de afgeronde taken, inclusief opgeslagen informatie, bekijken via het taken overzicht

**Comment by robertverboom** [comment]
Wat te doen met de verplichte velden die niet ingevuld zijn? 
Moet de taak nog zichtbaar zijn, als je de beindigde zaak weer opent

**Comment by Snijhuis** [comment]
Label question verwijderd. Besproken dat taken worden opgeslagen en afgesloten zoals ze op dat moment gevuld zijn.

**Comment by RoyBuis** [comment]
### Backlog refinement 17-5
is gerealiseerd

**Comment by HilbrandHurtak** [comment]
Test ok
