### ISSUE TITLE
BUG: ZAC kijkt niet naar einde geldigheid Bestluittype

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1913]
***Steps to reproduce:***

1. Zet op een besluittype datum geldigheid op gisteren
2. Synch ZAC
3. Ga naar een zaaktype waar het besltuite type aan gekoppeld is

***Expected***
Besluittype wordt niet getoond omdat einde geldigheid gezet is is

***Actual***
Besluittype wordt wel getoond

**Comment by RoyBuis** [comment]
### Refinement 22-11

Te realiseren:
ZAC moet kijken naar datum geldigheid van besluittype. Alleen de besluittypen tonen die een geldig begin- en einddatum hebben.
