### ISSUE TITLE
Keuzelijsten op alfabetische volgorde tonen

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1914]
***Als*** behandelaar

***Wil ik*** op plaatsen waar een lijst wordt gebruikt de keuzes op alfabestische volgorden worden getoond

***Zodat*** ik makkelijker de keuzelijst kan gebruiken

***

Dit wil ik terugzien in de volgende lijsten

Zaak aanmaken scherm:
- Zaaktype
- Groep
- Behandelaar

Document toevoegen:
- Documenttype

Taken:
- Taaktoewijzing groep en behandelaar

Beheerinstellingen:
- Zaakafhandelparameters

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Should haves

***
### Gerealiseerd
Bovenstaande filters zijn op alfabetische volgorde gezet

***Belangrijkste functionaliteiten:***
- 
-

**Comment by robertverboom** [comment]
### Refinement 22-11:
- Liefst zoveel mogelijk aan de achterkant sorteren. 
- natuurlijke sortering

**Comment by robertverboom** [comment]
test ok

**Comment by Renvooi** [comment]
In ACC nog niet volledig te testen op de onderdelen Zaaktype en Zaakafhandelparameters want er is maar 1 zaaktype beschikbaar. Bij de overige lijsten is de test akkoord.

**Comment by KarinMasselink** [comment]
Wordt opgepakt in issue #2379

**Comment by KarinMasselink** [comment]
@Renvooi wil je deze ook opnieuw testen, nu er 2 zaaktypes zijn.
