### ISSUE TITLE
BUG: indicatie Ondertekend wordt niet direct getoond

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#1919]
***Steps to reproduce:***

1. Maak een nieuwe zaak aan
2. Voeg een document toe
3. Rond de intake af en verklaar ontvankelijk
4. Maak een goedkeuren taak aan
5. Selecteer een document om te ondertekenen
6. Rond de goedkeur taak af en onderteken het document 

***Expected***
Verwachting het document dat ondertekend is krijgt de indicatie O 

***Actual***
De indicatie O ontbreekt bij het ondertekende document. Na een F5 wordt deze indicatie toegevoegd

**Comment by RoyBuis** [comment]
### Refinement 20-12

Controleren of Open Zaak een notificatie stuurt en anders zelf websocket event aanmaken en opgooien

**Comment by robertverboom** [comment]
test ok
