### ISSUE TITLE
Indicaties tonen in de zoekresultaten

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1924]
***Als*** Behandelaar

***Wil ik*** indicaties zien op het resultatenscherm

***Zodat*** ik een duidelijk beeld over de zaak die ik zoek 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Bovenstaande is gerealiseerd. Ook facetzoeken is mogelijk gemaakt

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 24-11

**Te realiseren**
- Indicaties van zaak en document opnemen in de zoekresultaten, toevoegen boven het label van zaak of document
- Bij zweven over chip tonen welke indicatie het is, bijv 'Is deelzaak'
- Zelfde kleuren en volgorde gebruiken als in werklijsten

**Comment by robertverboom** [comment]
Graag label Groep en Startdatum zelfde hoogte als 'Zaak' zetten idem met documenten en gebruikersindicaties

**Comment by robertverboom** [comment]
test ok

**Comment by CommonGroundGroningen** [comment]
**Indicaties van zaak en document opnemen in de zoekresultaten, toevoegen boven het label van zaak of document**
Akkoord
Er kan gezocht worden op specifieke indicaties van zaken en documenten door deze aan te vinken bij de zoekspecificaties

**Bij zweven over chip tonen welke indicatie het is, bijv 'Is deelzaak'**
Akkoord

**Zelfde kleuren en volgorde gebruiken als in werklijsten**
Akkoord
De kleuren en de volgorde van de iconen bij de zoekopdracht worden hetzelfde getoond als bij de werklijsten

**Comment by HilbrandHurtak** [comment]
Getest door testers Groningen en akkoord bevonden.
