### ISSUE TITLE
BUG: Taak toelichting wordt niet opgeslagen 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1932]
***Steps to reproduce:***

1. Maak een taak aan. 
2. Ken hem toe aan een andere behandelaar
3. Wijzig met huidige behandelaar de toelichting en sla hem op

***Expected***
Toelichting wordt opgeslagen

***Actual***
Toelichting wordt weer geleegd.

**Comment by RoyBuis** [comment]
### Refinement 24-11

- Gebeurt in alle taken
- Zie ook bug #1916 voor mogelijk verband
