### ISSUE TITLE
Adviestaak: document waarop advies is gegeven niet in overzicht afgeronde taak

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#1933]
OPM: in de werkgroep acceptatie en refinement is afgesproken (Sander Nijhuis) dat we testbevindingen ook in dit sjabloon voor de Kopgroep kunnen plaatsen. Het format is echter alleen geschikt gemaakt voor het aangeven van verbeterpunten. Daarbij wordt gevraagd waarom je de feature toegevoegd wilt hebben. 
Om mijn bevinding te plaatsen heb ik het format 'overschreven'. Onderstaande bevinding is een aanvulling op eerder via e-mail toegezonden bevindingen bij het testen als Kopgroep.

**Oost Gelre**: 

**Testbevinding testen zaaktype Toeristenbelasting. ZAAK-2022-0000000193**:

1 In deze zaak een Taak aangemaakt 'Advies Intern'  d.d. 23-11-2022.
2 Bij het aanmaken van de taak een document geselecteerd. 
3 Daarna de taak toegewezen aan groep-behandelaar.
4 Als Taakbehandelaar deze taak behandeld, een toelichting ingevuld en vervolgens afgerond.
5 Binnen de zaakgegevens de afgeronde taak geopend. Scherm = 'Taak | Advies intern raadplegen'.

Issue: Je ziet onder Relevante documenten niet het document wat er advies in de taak is meegegeven 
(of heeft dit een andere functie? Zo ja wat is dat dan)

**Comment by HilbrandHurtak** [comment]
Label acceptance verwijderd omdat de oplossing nog moet worden gebouwd. Hij stond nu ook nog in onze kolom User stories to Test

**Comment by HilbrandHurtak** [comment]
Opnieuw getest. ZAAK-2023-0000000032
Interne zaak met bijlage afgehandeld door behandelaar- Afgeronde taak met meegestuurde documenten is nog te raadplegen
Interne zaak met bijlage afgehandeld door alleen groep- Afgeronde taak met meegestuurde documenten is nog te raadplegen

Test OK
