### ISSUE TITLE
BUG: Toelichting advies veld in taak wordt niet getoond

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1939]
***Steps to reproduce:***

1. Maak een taak Advies intern aan
2. Vul het veld Toelichting advies in
3. Klik op opslaan

***Expected***
het veld is opgeslagen en wordt getoond

***Actual***
het veld is leeg

**Comment by RoyBuis** [comment]
### Refinement 24-11

Uitzoeken wat er mis gaat. Waarde wordt wel getoond in het overzicht van taken.
Staat in advies.ts, de builder moet een waarde krijgen.

**Comment by Renvooi** [comment]
duplicaat #1932

**Comment by robertverboom** [comment]
test ok
