### ISSUE TITLE
Taak verwerken aanvullende info: Indien zaak is opgeschort wil je ook kunnen hervatten via deze taak

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1940]
***Als*** Zaakbehandelaar

***Wil ik*** op de taak _Verwerken aanvullende info_ de mogelijkheid hebben om de zaak te hervatten

***Zodat*** ik bij het afhandelen van deze taak niet meer handmatig de zaak hoef te hervatten

***

### Acceptance criteria:
- De datum van afronding van de taak is dan ook de datum voor hervatting van de zaak
- Vinkje/toggle voor hervatten alleen tonen als de zaak is opgeschort
- Reden van opschorting tonen (default) en aanpasbaar maken

Deze oppakken na #1165

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #175 is het hervatten van een zaak vanuit de zaakgegevenspagina opgeleverd. Deze aanvullende story maakt het mogelijk om ook te hervatten bij het afronden van de taak 'Aanvullende informatie opvragen'. Een zaak kan maar één maal hervat worden dus deze optie is alleen beschikbaar als dit nog niet is gebeurd. De behandelaar kan de hervatting doen door de optie te selecteren in het taakbehandelscherm. De werking van de hervatting is identiek aan een hervatting via het zaakgegevensscherm.

***Belangrijkste functionaliteiten:***
- Gebruiker kan bij het afronden van een 'Aanvullende informatie opvragen' taak een opgeschorte zaak hervatten
- De optie om op te hervatten is alleen beschikbaar als de zaak nog niet is hervat
- De hervatting wordt als wijziging van de streef- en/of fatale datum vastgelegd in de historie van de zaak. Als toelichting wordt standaard 'Hervatting: Aanvullende informatie geleverd' gegeven.

**Comment by robertverboom** [comment]
test ok
