### ISSUE TITLE
BUG: Na verzenddatum gekozen te hebben, blijft ontvangstdatum disabled

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1953]
***Steps to reproduce:***

1. Maak een document aan
2. Zet een verzenddatum
3. zet status op in bewerking
4. Ga naar het document 
5. voeg andere versie toe
6. maak verzenddatum leeg

***Expected***
Wanneer verzenddatum leeg is,  wordt ontvangstdatum enabled

***Actual***
ontvangstdatum blijft disabled

**Comment by jeroen-dekker** [comment]
Er is een TODO toegevoegd in de diff. Hierbij horen twee gelinkte issues. Enerzijds https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/2020 voor het updaten van de Angular-versie naar v15, anderzijds https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/2021 voor het verwijderen van de workaroud die in de diff is toegepast.

**Comment by robertverboom** [comment]
test ok
