### ISSUE TITLE
Kampen: BUG: Behandelaar kan niet worden toegewezen

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#1961]
**Gemeentenaam**:  Kampen

**Feature verzoek**: 
Behandelaar toewijzen nadat zaak is aangemaakt

**Waarom zou je deze feature graag in de applicatie willen?**
Ik kan de behandelaar niet toewijzen als de zaak al is aangemaakt. Bij het toewijzen van de behandelaar, blijft het veld leeg na opslaan. Ook staat er geen zaak onder 'Mijn zaken'.

**Comment by robertverboom** [comment]
Klopt dit is een bug in de huidige versie. Wordt aangewerkt middels gekoppeld ticket: #1931

**Comment by robertverboom** [comment]
Sluit dit ticket ivm dubbel issue
