### ISSUE TITLE
"Wij hebben uw verzoek in behandeling genomen" e-mail is niet ingevuld

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#1963]
**Gemeentenaam**: Kampen

**Feature verzoek**: Invullen van e-mail : "Wij hebben uw verzoek in behandeling genomen"

Beste klant,
Uw verzoek over {zaaktypenaam} met zaaknummer {zaaknummer} is in behandeling genomen. Voor meer informatie gaat u naar Mijn Loket.
Met vriendelijke groet,
Gemeente

**Waarom zou je deze feature graag in de applicatie willen?**
De aanvrager krijgt bovenstaande mail. Deze moet automatisch ingevuld worden met de juiste gegevens.

**Comment by robertverboom** [comment]
Ivm dubbel issue, sluit ik dit ticket
