### ISSUE TITLE
contactmomenten ophalen vanuit de contactmomenten API 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1969]
***Als***  Behandelaar

***Wil ik*** weten of er al contact is geweest met de klant middels de contactmomenten API 

***Zodat*** ik weet welke contacten er zijn geweest met de klant

***

### Acceptance criteria:
-

***
### Prioriteit
- Should haves

***
1969
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De gegevens van een persoon of bedrijf kunnen bekeken worden vanuit de persoons- of bedrijfsgegevenspagina. Deze pagina is uitgebreid met de contactgegevens (telefoonnummer en e-mailadres) en een overzicht van contactmomenten die er met de persoon of bedrijf zijn geweest. Deze gegevens worden via de Klanten API en Contactmomenten API opgehaald uit Open Klant, de referentieimplementatie van deze API's
***Belangrijkste functionaliteiten:***
- Gebruiker kan de persoons- of bedrijfsgegevenspagina benaderen door de persoon of het bedrijf te zoeken via de zoekfunctie en deze vanuit de zoekresultaten te openen
- Gebruiker kan de contactgegevens onder de persoons- of bedrijfsgegevens bekijken. Als deze gegevens niet aanwezig zijn is er een streepje te zien.
- Gebruiker kan het overzicht van contactmomenten onder het zaken overzicht inzien

**Comment by Snijhuis** [comment]
SN: Technisch gereed en hebben gezien dat de integratie werkt. Bij de bij koploper PodiumD zaak pakken we de integratie verder op en gaan functioneel dan verder uitbouwen
