### ISSUE TITLE
Kampen: bij zoekresultaten de optie geven om meer metadatavelden te tonen

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#1975]
**Gemeentenaam**: Kampen

**Feature verzoek**:  Bij zoekresultaten de optie geven om meer metadatavelden te tonen

**Waarom zou je deze feature graag in de applicatie willen?**
Als ik via zoeken de zoekresultaten te zien krijg, dan worden de gevonden zaken met een vaste set aan metadatavelden getoond. Ik zou graag de optie willen hebben om bij de gevonden zaken meer gegevens van de zaak in een oogopslag te kunnen zien. Ik moet nu een zaak openen om bv. de bewaartermijn en vernietigingsdatum te zien, dat is onhandig.  Hoe meer gegevens ik kan zien, hoe meer inzicht ik heb in wat voor zaak het gaat.

**Comment by HilbrandHurtak** [comment]
Bewaartermijn en vernietigingsdatum zijn handig zijn om ook op te nemen. Welke velden zouden nog meer van toegevoegde waarde kunnen zijn? Ik denk zelf aan Resultaat en Vertrouwelijkheidsaanduiding

**Comment by VictorTielenius** [comment]
Bij zoekresultaten (van een Zaak) ook tonen: Aanvrager (initiator zaak, Naam /BSN of KVK) / Communicatiekanaal / Creatiedatum zaak.
Resultaat nu al in ZAC Accept getoond bij Zoekresultaten van Zaken.

Bij de Facet zoeken opties toevoegen: 
Afgesloten (Ja/Nee)
Kanaal (= Communicatiekanaal)
Creatiedatum
Afgehandeld (met datum velden, van / t/m)
Vertrouwelijkheidsaanduiding

**Comment by HilbrandHurtak** [comment]
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/40e7274e-bfca-4a12-9246-8077c8d3236f)

**Comment by KarinMasselink** [comment]
**WG Refinement 19-4**

Besproken met WG  om volgende aanpassingen nog door te voeren, om zo nog overzicht te kunnen houden: 
Zoekfilters uitbreiden met de optie: 
Open/Afgehandeld

Zoekresultaten uitbreiden met de opties: 
* Einddatum
* Communicatiekanaal

Overige velden:
Er blijven nog een aan aantal opties over zoals bewaartermijnen en vernietigingsdatum. Daarbij lijkt deze zoekingang niet het juiste kanaal, maar juist de werklijst afgehandelde zaken. In deze werklijst is het sinds de oplevering van #2228  mogelijk om kolomfilters aan te zetten op bewaartermijn en vernietigingsdatum waardoor zoeken op deze velden makkelijker wordt.

**Comment by RoyBuis** [comment]
### Refinement KM, SN, RV & RB

Besproken punten:

- Zoekfilters uitbreiden met de optie: Open/Afgehandeld wordt nu niet gereraliseerd omdat er maar één eindstatus mogelijk is. Deze status is 'afgerond' en daar kun je nu op filteren via facet aan de linkerkant
- Zoekresultaten uitbreiden met de optie 'Einddatum' wordt gerealiseerd
- Zoekresultaten uitbreiden met de optie Communicatiekanaal' wordt niet gerealiseerd. Er wordt een user story beschreven om de UI van het zoekscherm te verbeteren waardoor je ziet welke filters zijn toegepast op de zoekresultaten. Hierdoor zie je in een oogopslag dat bijv de filter 'Communicatiekanaal' is toegepast en welke opties getoond worden

**Comment by robertverboom** [comment]
### Refinement 20-04:
- Bij afgehandelde zaken de einddatum tonen bij de resultaten

**Comment by robertverboom** [comment]
Graag alleen tonen bij afgehandelde zaken. Andere zaken is dit niet relevant

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Test refinement 20/4.

Beide velden worden getoond bij afgehandelde zaken
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/ffc67224-3534-4f22-b7a1-60a1343c0e5c)


Test OK
