### ISSUE TITLE
Kampen: Zoekresultaat openen in nieuw venster

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#1976]
**Gemeentenaam**: Kampen

**Feature verzoek**: Zoekresultaat openen in nieuw venster

**Waarom zou je deze feature graag in de applicatie willen?**
Als ik via zoeken een zaak wil openen, dan opent deze in het huidige venster. Het lijkt alsof mijn zoekresultaten dan weg zijn, maar misschien is dat niet zo? Het is in ieder geval verwarrend. Optie om de zaak in een nieuw venster te laten openen graag toevoegen.

**Comment by robertverboom** [comment]
Refinement SN RV:
- Duidelijk maken dat je weer terug kan naar de laatst gekozen zoekresultaten. Wellicht middels een knop/melding in de je zoekvenster
