### ISSUE TITLE
Kampen: overzichten kunnen creëren van documenten

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#1978]
**Gemeentenaam**: Kampen

**Feature verzoek**: overzichten kunnen creëren van documenten

**Waarom zou je deze feature graag in de applicatie willen?**
Op dit moment kunnen overzichten opgesteld worden voor zaken en taken, maar dit zou ik ook graag voor documenten willen. Met de optie om te filteren op alle metadatavelden van een document. Als informatiebeheerder voer ik ook op documenten analyses uit, de optie om daar complete overzichten van de kunnen genereren zou erg nuttig zijn. Anders moet ik, net als bij de e-Suite nu, Dimpact vragen om te zorgen dat ik bepaalde overzichten kan creëren of uitwijken naar Power BI. Het zou mooi zijn als ik onafhankelijk in het zaaksysteem de gewenste overzichten kan creëren.

**Comment by robertverboom** [comment]
In de nieuwe versie hebben wij documenten die gekoppeld zijn aan een zaak ook geindexeerd. Deze worden bij de volgende release opgeleverd #1820

**Comment by IreneYolande** [comment]
Top! Hoop wel dat de mogelijk er is om dan alle metadatavelden van het document in het overzicht te kunnen krijgen.

**Comment by robertverboom** [comment]
Informatie wordt meegenomen in ticket #1820
Dit ticket wordt gesloten
