### ISSUE TITLE
Kampen: overzichten gebruiksvriendelijk maken

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#1979]
**Gemeentenaam**:  Kampen

**Feature verzoek**: Overzichten gebruiksvriendelijk maken

**Waarom zou je deze feature graag in de applicatie willen?**
Als ik overzichten heb gegenereerd, dan staan de gegevens niet gesplitst in kolommen, maar in een lange rij. Dit is niet gebruiksvriendelijk. Graag aanpassen.

**Comment by robertverboom** [comment]
Gaat dit over de overzichten wanneer je deze download als .csv vanuit de werkvoorraad?

**Comment by IreneYolande** [comment]
@robertverboom ja, klopt.

**Comment by robertverboom** [comment]
Wordt opgelost in ander ticket. Dit ticket wordt gesloten
