### ISSUE TITLE
Open Formulieren - Zandbak omgeving updaten naar laatst vrijegegeven systeemversie

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#1985]
***Als*** PO van open formulieren

***Wil ik*** graag dat Open Formulieren in de Zandbak omgeving van ATOS altijd worde bijgewerkt naar de laatste "vrijgegeven" systeem versie zodat de omgeving altijd de laatste functionaliteiten en securityupdates voldoet.

***Zodat*** ik beschik over de meest up-to-date versie van Open Formulieren.

***
NB. 2.0.1. is de laatst vrijgegeven versie van Open Formulieren, de Zandbakomgeving draait nog op 1.1.7.

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by StefSchots1993** [comment]
Is er al een "vaag" idee van wanneer er een update van de omgeving te verwachten is? 
Deze week wordt o.a. weer een demo gegeven van een nieuwe Alpha versie van OF.
Intussen loopt de omgeving steeds meer versies achter.
