### ISSUE TITLE
BUG: Ken toe aan mijzelf knop verdwijnt niet

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#199]
***Steps to reproduce:***

1. Ga naar zaken-werkvoorraad
2. Ken een zaak aan jezelf toe

***Expected***
Knop verdwijnt

***Actual***
Knop blijft staan. Pas na reload is hij weg

**Comment by nl23727** [comment]
Getest met Chrome op development omgeving 

Lijkt toch nog niet helemaal goed te werken. 

- Pas na 2 keer op de knop klikken wordt het scherm ververst.

**Comment by marcoatos** [comment]
Besproken met @nl23727 Het werkt wel op develop, maar nog niet op test. 
Waarschijnlijk is test nog niet up to date. In overleg met Marc gesloten omdat het werkt op develop.

**Comment by robertverboom** [comment]
Zit nog een fout in:

Als er al een behandelaar op staat werkt hij naar behoren
Als de zaak geen behandelaar heeft, moet je 2x klikken om hem aan jezelf toe te kennen. 
Console: Uncaught SyntaxError: Identifier 'foreground_entry_point' has already been declared
ERROR TypeError: Cannot read properties of undefined (reading 'naam')

**Comment by marcoatos** [comment]
Fout op assign to me knop in zaken werklijst is een cache/event issue wat Hans oppakt (zaakafhandelcomponent-397) ipv daarvan is nu een wijziging gemaakt bij taaktoekennen, omdat dit niet via de juiste manier ging. Dat laatste moet getest worden.

**Comment by robertverboom** [comment]
test ok
