### ISSUE TITLE
Tabel mailtemplates kunnen filteren/sorteren

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1995]
***Als*** Beheerder

***Wil ik*** in de mailtemplates de kolommen kunnen filteren. 

***Zodat*** ik een overzicht heb welke mailtemplates bij welke type mails horen. 

***

### Acceptance criteria:
-

***
### Prioriteit

- Should haves

***
### Gerealiseerd
Onder Beheer-instellingen kunnen de mailtemplates beheerd worden. Met deze story is het mogelijk gemaakt om in het overzicht van mailtemplates te kunnen sorteren en filteren.

**Belangrijkste functionaliteiten:**
- Gebruiker kan met het pijl icoon in de kolomkop het overzicht sorteren op basis van de gegevens in een kolom. Door nog een keer op de pijl te klikken wordt de andere kant op gesorteerd.
- Gebruiker kan filteren op de mailtemplates door trefwoorden in het 'Filter' veld in te vullen. Er wordt op de trefwoorden gezocht in de 'Mailtemplate naam', de 'Mail voor' beschrijving en in de inhoud van de mailtemplates.

**Comment by robertverboom** [comment]
### Refinement: 
- Kolommen kunnen sorteren 
- Kolom mailtemplate naam kunnen zoeken
- Kolom 'Mail voor' kunnen filteren
- Uitklap functie per mailtemplate om te laten zien bij welke zaaktype (omschrijving) deze hoort incl. creatiedatum van zaaktype. Oogje om direct naar de ZAP te gaan

**Comment by CommonGroundGroningen** [comment]
Test ok
