### ISSUE TITLE
zaaktypes + versie tonen in mailtemplates

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1996]
***Als*** Beheerder

***Wil ik*** kunnen zien welke zaaktypes + versies de mailtemplates zijn gekoppeld. 

***Zodat*** ik niet elke versie van de zaaktypes bij langs hoef om de mailtemplates te controleren en aan te passen. 
(in de title van het prullenbakje wordt 1 zaaktype getoond)
***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Could haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 13-12

Overzicht van aan welke zaaktypen het template gekoppeld is is wenselijk, dit moet een complete lijst zijn. Uitzoeken of dit op soortgelijke wijze als de inrichtingscheck gemaakt kan worden waarbij deze info als uitklap optie wordt getoond, mogelijk per zaaktype een regel met oog om deze direct te openen.

**Comment by robertverboom** [comment]
Wordt opgelost in #1995
