### ISSUE TITLE
Linear mode uitzetten van de Stepper in de zaakafhandelparamters

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1997]
***Als*** Beheerder

***Wil ik*** met 1 klik naar een andere parameter gaan in de zaakafhanelparameters bewerken pagina

***Zodat*** ik niet 4x moet klikken om naar de zaakbeeindig gegevens te gaan. 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 13-12

**Te realiseren**
- Mogelijk maken om direct naar een latere stap te gaan 
- Naar een latere stap kan alleen als validatie op alle eerdere stappen succesvol is

**Comment by robertverboom** [comment]
test ok
