### ISSUE TITLE
Aanmaken zaak: Naast scrollen ook typen om zaaktype te kunnen vinden

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1998]
***Als*** Behandelaar

***Wil ik*** bij het aanmaken van een nieuwe zaak ook kunnen typen om mijn zaaktype te kunnen vinden

***Zodat*** ik niet door een hele lijst moet scrollen om het juiste zaaktype te vinden

***

### Acceptance criteria:
- Zelfde functionaliteit als bij Medewerker toekennen

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 13-12

Te realiseren
Bij aanmaken zaak toepassen in zaaktype veld

**Comment by robertverboom** [comment]
Graag ID meegeven voor de automatische testen
