### ISSUE TITLE
BUG: Uitleg wordt niet volledig weergegeven in de variabelen dorpdown mailtemplates 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2001]
***Steps to reproduce:***

1. Ga naar https://zac.develop-public-service-platform.net/admin/mailtemplate
2. open een mailtemplate
3. open een variabelen dropdown

***Expected***
Nu er een uitleg achter een variablen staat wordt de volledige informatie wordt getoond, zonder dat ik hoef te scrollen

***Actual***
Dropdown schaalt niet met de regelafstand van de opties: 
![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/6dd6fa82-73cc-4156-9ba3-2f24403e5891)

**Comment by RoyBuis** [comment]
Mooie layout maken!

**Comment by robertverboom** [comment]
Speelt nog steeds
