### ISSUE TITLE
Naamwijziging mailtemplates

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2005]
Naamwijzing van de mailtemplates: 
Kolomnaam: Mail -> Mail voor: 

Proces aanvullende informatie -> Taak formulierdefinitie: Aanvullende informatie
Proces advies -> Taak formulierdefinitie: Extern advies (met e-mail)
Proces ontvangstbevestiging	-> Ontvangstbevestiging		
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Via #1720 is het kunnen beheren van mailtemplates voor de mails binnen het ZAC opgeleverd. In deze story is dit verbeterd door meer duidelijke namen in de UI van het beheeronderdeel te gebruiken.

***Belangrijkste functionaliteiten:***
Niet van toepassing

**Comment by hansmarks** [comment]
"mail.ZAAK_ONTVANKELIJK": "Zaak ontvankelijk",
  "mail.ZAAK_NIET_ONTVANKELIJK": "Zaak niet ontvankelijk",
  "mail.ZAAK_AFGEHANDELD": "Zaak afgehandeld",
  "mail.PROCES_AANVULLENDE_INFORMATIE": "Proces aanvullende informatie",
  "mail.PROCES_ONTVANGSTBEVESTIGING": "Proces ontvangstbevestiging",
  "mail.PROCES_ADVIES": "Proces advies",
  "mail.SIGNALERING_ZAAK_DOCUMENT_TOEGEVOEGD": "Signalering zaak document toegevoegd",
  "mail.SIGNALERING_ZAAK_OP_NAAM": "Signalering zaak op naam",
  "mail.SIGNALERING_ZAAK_VERLOPEND_STREEFDATUM": "Signalering zaak verlopend (streefdatum)",
  "mail.SIGNALERING_ZAAK_VERLOPEND_FATALE_DATUM": "Signalering zaak verlopend (fatale datum)",
  "mail.SIGNALERING_TAAK_OP_NAAM": "Signalering taak op naam",
  "mail.SIGNALERING_TAAK_VERLOPEN": "Signalering taak verlopen",

**Comment by hansmarks** [comment]
PROCES_AANVULLENDE_INFORMATIE(MailTemplateVariabelen.PROCES_VARIABELEN),
    PROCES_ONTVANGSTBEVESTIGING(MailTemplateVariabelen.PROCES_VARIABELEN),
    PROCES_ADVIES(MailTemplateVariabelen.PROCES_VARIABELEN),

renamen naar

    TAAK_ONTVANGSTBEVESTIGING(MailTemplateVariabelen.ACTIE_VARIABELEN),
    TAAK_AANVULLENDE_INFORMATIE(MailTemplateVariabelen.ACTIE_VARIABELEN),
    TAAK_ADVIES_EXTERN(MailTemplateVariabelen.ACTIE_VARIABELEN),

flyway script om dat door te werken in de bestaande templates in de database

**Comment by RoyBuis** [comment]
### Refinement 8-12

- Naam van de kolom 'Mail' veranderen naar 'Mail voor'
- Lijst uit vorige comment hebben nieuwe benamingen gekregen, deze graag doorvoeren
- De mailtemplate naam van de default templates bijwerken (dat houdt in het overnemen van de 'Mail voor' naam), flyway script
- Renamen, zoals hierboven in comment genoemd

**Comment by HilbrandHurtak** [comment]
Wijzigingen zijn doorgevoerd
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/0ff578a4-9fe4-4aed-a187-501b39c49c11)
