### ISSUE TITLE
BUG: aangepaste mails worden niet verstuurd

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2006]
***Steps to reproduce:***

1. creeer een nieuwe zaak met zaaktype: mke
2. zorg dat je de mail verstuurd. Onvangstbevesting oid is goed
3. 

***Expected***
Er wordt een mail verstuurd naar de ontvanger en deze wordt als document toegevoegd aan de zaak. 

***Actual***
Zowel de mail als het document van de mail wordt niet gemaakt.

**Comment by RoyBuis** [comment]
### Refinement 8-12

Geproduceerd met ontvangstbevestigingmail waaraan een zelf gemaakt mailtemplate gekoppeld is. Oorzaak ligt waarschijnlijk in de lengte van het subject. De lengte afkorten indien nodig met {StringUtils.abbreviate}.

**Comment by hansmarks** [comment]
Ik heb de abbreviate als toegevoegd in #1999 (78 tekens volgens RFC 2822, lijkt me ook redelijk). Of dit probleem daarmee inderdaad is opgelost moet nog even getest worden.

**Comment by robertverboom** [comment]
Title wordt nu afgerond.
