### ISSUE TITLE
BUG: Indicaties Opschorten en Heropenen worden pas na handmatige refresh getoond bij zaak

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#2008]
***Steps to reproduce:***

1. Maak een zaak aan van zaaktype: melding klein evenement
2. Schort de zaak op

***Expected***
Indicatie: Zaak is opgeschort wordt getoond bij de zaak

***Actual***
Indicatie: Zaak is opgeschort wordt na handmatige refresh bij de zaak getoond

Zelfde issue speelt voor Heropenen van een Zaak
Idem: voor Vergrendelen van documenten

**Comment by RoyBuis** [comment]
### Refinement 20-12

- Zowel Opschorten als Heropenen indicaties hebben eerder wel gewerkt
- Controleren of Open zaak notificatie stuurt en en anders zelf websocket event aanmaken en opgooien.
