### ISSUE TITLE
BUG: Indicatie Is verlengd wordt niet getoond na verlengen van een zaak

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#2011]
***Steps to reproduce:***

1. Maak een nieuwe zaak aan van het zaaktype: melding klein evenement
2. Verleng de zaak
3. 

***Expected***
Er wordt een indicatie Zaak is verlengd getoond

***Actual***
De indicatie Is Verlengd wordt niet getoond bij een verlengde zaak. Ook niet na een handmatige refresh

**Comment by robertverboom** [comment]
Op Dev inmiddels wel na een refresh. Verwacht websocket

**Comment by RoyBuis** [comment]
### Refinement 20-12

- Deze heeft eerder wel gewerkt
- Controleren of Open zaak notificatie stuurt en en anders zelf websocket event aanmaken en opgooien

**Comment by robertverboom** [comment]
test ok
