### ISSUE TITLE
BUG: Het veranderen van Groep of behandelaar kan dubbele 'mogelijke taken veroorzaken'

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#203]
***Steps to reproduce:***

1. Pak een behandelaar
2. kies een groep waar de behandelaar niet bij hoort

***Expected***
Er wordt 1x 'Mogelijke taken' getoond

***Actual***
Mogelijke taken worden 2x getoond. Zie afbeelding ![MogelijkeTakenBug.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/95a2cc05-912e-4734-9419-877d76c9d1c5)

NB. Dit wordt niet altijd gereproduceerd

**Comment by robertverboom** [comment]
Na het reloaden van de pagina komt dit niet meer voor echter kan dit wel voor verwarring zorgen

**Comment by RoyBuis** [comment]
Tijdens planning besproken om deze nog een keer te testen en kijken of dit nog te reproduceren is.

**Comment by robertverboom** [comment]
niet meer te reproduceren
