### ISSUE TITLE
BUG: In tab Gerelateerde zaak wijkt het datum formaat af van de standaard

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#2031]
***Steps to reproduce:***

1. Maak een zaak aan en koppel daar een andere zaak aan
2. Ga naar de tab Gerelateerde zaken

***Expected***
Startdatum wordt getoond als DD-MM-YYYY

***Actual***
Startdatum wordt getoond als YYYY-MM-DD
![Gerelateerde zaak.JPG](https://images.zenhubusercontent.com/61a7619ff842ca7ff613d64f/5efc958f-4539-424e-ad9a-952e790ec8b1)

**Comment by RoyBuis** [comment]
### Refinement 20-12

Kijken naar datumformaat bij tabblad gerelateerde zaken
