### ISSUE TITLE
Facet en zoekresultaten eenvoudig wissen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2038]
***Als*** Behandelaar

***Wil ik*** met 1 klik de zoekresultaten wissen

***Zodat*** ik niet alle facetten ongedaan moet maken

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
na het vullen van het zoekveld of het invoeren van een facet verschijnt er een pijl naar links met een X. Dit icoon zal de resultaten verwijderen 

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 22-12

- Optie om zoekopdracht te wissen toevoegen in zoekpanel met kruisje boven de facetopties
- Optie om te wissen vanuit het zoekveld door op kruisje te klikken
- Link maken tussen zoekveld en zoekcomponent zodat het zoekveld de zoekopdracht kan wissen

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Zoekopdracht is te wissen
