### ISSUE TITLE
BUG: Vrijgeven van zaak geeft foutmelding

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#204]
***Steps to reproduce:***

1. Ga naar zaken-werklijsten
2. vink een zaak aan
3. geef deze vrij

***Expected***
De zaak komt vrij van behandelaar

***Actual***
Het vrijgeven blijft hangen.
Console geeft:
ERROR TypeError: Cannot read properties of undefined (reading 'foutAfhandelingService')

**Comment by robertverboom** [comment]
Feature: C032

**Comment by nl23727** [comment]
Speelt niet meer. Issue succesvol hertest
