### ISSUE TITLE
BUG: limit op leestekens in mail

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2059]
***Steps to reproduce:***

1. Maak een mail aan
2. vul verplichte velden in
3. Zet 1000+ tekens in het berichtveld. 

***Expected***
Zit een max op van 1000 tekens op

***Actual***
Je mag  >1000 versturen

**Comment by robertverboom** [comment]
Willen wij er wel een max op hebben?

**Comment by RoyBuis** [comment]
### Refinement 20-12

**Te realiseren**

- Zorgen dat er een limiet van 100 karakters op onderwerp is
- Zorgen dat de limiet op inhoud verwijderd wordt

**Comment by robertverboom** [comment]
test ok
