### ISSUE TITLE
BUG: Mail tekstvariabele (Zaaknummer) in mail template zaakontvankelijk nog de oude waarde 

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#2067]
***Steps to reproduce:***

1. In de mail teksttemplate die gebruikt wordt bij ontvankelijk verklaren van een zaak staat de variabele: {zaaknummer} i.p.v. {ZAAK_NUMMER}

**Comment by robertverboom** [comment]
Gefixt
