### ISSUE TITLE
KAMPEN: een publicatiestatus

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2068]
**Gemeentenaam**: Kampen 

**Feature verzoek**: Een publicatiestatus

**Waarom zou je deze feature graag in de applicatie willen?**
Ik mis de Publicatiestatus van het document (van belang bij koppeling naar MijnLoket)

**Comment by robertverboom** [comment]
Komt uit document van Maarten van Kalsbeek

**Comment by Snijhuis** [comment]
NB. Dit is een samenspel tussen OIP en Open Zaak. Op basis van bijvoorbeeld de richting (inkomend/uitgaand) en de vertrouwelijksheidsaanduiding van een document kunnen we bepalen welke wel/niet getoond moeten worden.

Bespreken met WG Refinement
