### ISSUE TITLE
KAMPEN: bij géén initiator staat er helemaal niets

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2069]
**Gemeentenaam**: Kampen 

**Feature verzoek**: De initiator bovenaan; bij géén initiator staat er helemaal niets. Er is bovenaan géén verwijzing dat er géén initiator is, óf dat de zaak Anoniem is

**Waarom zou je deze feature graag in de applicatie willen?**
Er is bovenaan géén verwijzing dat er géén initiator is, óf dat de zaak Anoniem is

2069
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Deze story is een aanpassing in de UI voor het Initiator blok. Als een zaak geen initiator heeft toegekend dan is het Initiator blok bovenin nu wel aanwezig maar wordt hierin de tekst 'Geen initiator' getoond.

***Belangrijkste functionaliteiten:***
- Gebruiker kan op de zaakgegevenspagina altijd het Initiator blok bekijken en kan aan de tekst 'Geen initiator' zien dat de geopende zaak geen initiator toegekend heeft

**Comment by robertverboom** [comment]
Komt uit document van Maarten van Kalsbeek. 

Graag met WG overleggen of er een indicatie moet komen, of we dit laten zoals nu: Wanneer geen initiator wordt getoond, is de zaak standaard anoniem.

**Comment by VictorTielenius** [comment]
Nu in e-Suite bij Blok "Geselecteerde zaak" altijd het veld "Aanvrager" aanwezig waar de naam van de aanvrager staat (T. van Lies) of "Anoniem".

**Comment by HilbrandHurtak** [comment]
Zou misschien wat duidelijker zijn. Nu staat er niets en moet je net weten dat dit dan Anoniem is.

**Comment by PaskalKiers** [comment]
Lijkt me een goed dat duidelijk is of het anoniem is of iets wat mis is gegaan. 
(wellicht is het getoonde van de initiator niet gevuld en is er wel één gekoppeld)

Als behandelaar wil ik kunnen zien wie de initiator is of dat de zaak anoniem is ingediend, zodat ik daarmee rekening kan houden met de behandeling.

Misschien nog wel even uitleggen wat de bedoeling is van de waarom vraag.  Nu staat er effectief een cirkelredenering. Ik wil een verwijzing omdat die er niet is.   Misschien de vraag in de template omkeren : wat is het probleem als het gevraagde ontbreekt/ niet wordt opgelost.

**Comment by Snijhuis** [comment]
Zojuist ook al voorgesproken met Atos. We gaan het initiator-blok altijd tonen boven de zaak. Uitgeklapt als er een initiator is. Ingeklapt als deze er niet is.
Via dat blok kan de gebruiker dan:
- de initiator wijzigen, verwijderen (indien aanwezig); 
- de initiator toevoegen (indien niet aanwezig).

Knop/ actie 'Initiator toevoegen/ wijzigen halen we dan uit het linke actiemenu.

**Comment by RoyBuis** [comment]
### Refinement 14-2

**Te realiseren**

Als er geen initiator is:

- Blok is ingeklapt
- Een streepje tonen op de plek van de initiator naam
- Knop om initiator toe te voegen

Als er wel een initiator is:

- Blok is uitgeklapt
- Knop om initiator te wijzigen

Initiator toevoegen/wijzigen actie uit linker menu verwijderen

**Comment by robertverboom** [comment]
Nav overleg Potlood icoontje terug

**Comment by robertverboom** [comment]
Tekst: 'Er is geen initiator toegekend aan de zaak' wijzigen in 'Geen initiator'

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Test ok

[Uploading... image.png]
