### ISSUE TITLE
BUG: afsluiten van een zaak m.b.v. taak Niet ontvankelijk zet de einddatum op gisteren

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#207]
Steps to reproduce:
1. Maak een nieuwe zaak aan van zaaktype: melding klein evenement
2. Start een Taak "Niet ontvankelijk"

Verwachting:
Zaak wordt afgesloten met een einddatum op vandaag

Daadwerkelijk:
De zaak krijgt een einddatum van gisteren

**Comment by bartlukens-atos** [comment]
Bug lijkt in open-zaak te zitten

**Comment by andyverberne** [comment]
Open Zaak geeft de dag van gisteren terug als einddatum waarschijnlijk omdat de dag van gisteren wordt meegegeven tijdens het zetten van de eind status

**Comment by andyverberne** [comment]
In ZGWApiService.java staat:

    private Status createStatusForZaak(final URI zaakURI, final URI statustypeURI, final String toelichting) {
        // Wanneer de huidige datum en tijd gebruikt wordt geeft open zaak een validatie fout dat de datum in de toekomst ligt.
        final Status status = new Status(zaakURI, statustypeURI, ZonedDateTime.now().minusDays(1));
        status.setStatustoelichting(toelichting);
        return zrcClient.statusCreate(status);
    }

**Comment by andyverberne** [comment]
https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html#withZoneSameInstant-java.time.ZoneId-

ZoneOffset.UTC

**Comment by andyverberne** [comment]
Probleem blijkt niet te zitten in de representatie van de datum of in een tijdzone probleem. 1 seconde van de huidige tijd aftrekken blijkt voldoende te zijn om geen melding te krijgen van Open Zaak dat de datum (tijdstip) in de toekomst ligt.

**Comment by andyverberne** [comment]
Exceptie uit Open Zaak dat de meegegeven status registratie datum/tijd in de toekomst ligt blijkt uiteindelijk te worden veroorzaak doordat mijn lokale ontwikkel omgeving 1 seconde voorloopt op de tijd van Open Zaak welke draait op het Haven cluster (of andersom)

**Comment by andyverberne** [comment]
De time server welke door windows gebruikt wordt omgezet naar die van Google: time.google.com

**Comment by robertverboom** [comment]
test ok
