### ISSUE TITLE
KAMPEN: andere indeling van Zaak-actie-buttons 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2071]
**Gemeentenaam**: KAMPEN

**Feature verzoek**: Andere indeling van de zaak-actie-buttons. Taak starten-buttons boven de koppeling-buttons 

**Waarom zou je deze feature graag in de applicatie willen?**
Zo houd je de meest te gebruiken buttons eerder in het zicht

**Comment by robertverboom** [comment]
Komt uit document van Maarten van Kalsbeek

**Comment by RoyBuis** [comment]
### Refinement 5-1

Blok met taak acties verplaatsen naar de plek waar nu de koppelen acties staan

**Comment by Renvooi** [comment]
Getest en akkoord. Actiemenu's zijn op de gewenste positie aanwezigh
