### ISSUE TITLE
KAMPEN: Toon gekoppelde documenten uitzetten wanneer geen zaken zijn gekoppeld 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2072]
**Gemeentenaam**: Kampen

**Feature verzoek**: Bij taak Advies intern behandelen staan de zaakdocumenten getoond, ongeacht wat je doet met het schuifje Toon gekoppelde documenten

**Waarom zou je deze feature graag in de applicatie willen?**
Heeft geen functionele werking 

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #1234 is het tonen van de documenten van gekoppelde zaken opgeleverd. In deze story is deze functionaliteit uitgebreid waardoor deze functionaliteit alleen beschikbaar is als er daadwerkelijk een gekoppelde zaak is.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in een zaak die minimaal één gekoppelde zaak heeft door het ‘Toon gekoppelde zaakdocumenten’ schuifje aan te zetten de documenten van gekoppelde zaken in het zaakdocumentenoverzichten weergeven

**Comment by robertverboom** [comment]
- Wanneer er geen gekoppelde zaken zijn, deze functie niet tonen. 
- Wanneer je in OZ geen deelzaken hebt gekoppeld, de functie zaken koppelen niet tonen.

**Comment by RoyBuis** [comment]
### Refinement 5-1

Schuifje 'Toon gekoppelde zaakdocumenten' alleen tonen als er daadwerkelijk gekoppelde hoofd- of deelzaken zijn

**Comment by robertverboom** [comment]
test ok

**Comment by Renvooi** [comment]
Getest in accept en afzonderlijk bug gemaakt #2409 en ik zie dat Hilbrand ook #2394 heeft aangemaakt

**Comment by CommonGroundGroningen** [comment]
Alleen tonen van schuif als zaken zijn gekoppeld
**Test OK**

Zoals beschreven in bug #2409 en #2394 werkt de schuif niet.
