### ISSUE TITLE
KAMPEN: ontvanger, onderwerp, bijlagen meenemen in html/pdf document

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2073]
**Gemeentenaam**:  Kampen 

**Feature verzoek**: ontvanger, onderwerp, bijlagen meenemen in html/pdf document

**Waarom zou je deze feature graag in de applicatie willen?**
Als email verstuurd is, wordt het als document toegevoegd aan de zaak (Prima!). Echter, als ik het document open (html-bestand), zie ik alleen de tekst van het veld "Bericht" (dus niet aan wie ik het heb verstuurd, én met welke bijlagen) 

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een vanuit de zaak verzonden e-mail wordt als document aangemaakt en toegevoegd aan de zaak. Met deze story is dit aangepast door in dit document ook de afzender, ontvanger en toegevoegde bijlage(n) weer te geven. Daarnaast wordt dit document nu als PDF-bestand aangemaakt.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het PDF document van de verzonden e-mail de informatie over de afzender, ontvanger en toegevoegde bijlagen bekijken

**Comment by robertverboom** [comment]
Komt uit document van Maarten van Kalsbeek

**Comment by RoyBuis** [comment]
### Refinement 5-1

Mogelijke oplossing: https://www.baeldung.com/java-pdf-creation

Uitzoeken of hiermee een PDF te maken is met de gewenste info, te weten verzendinformatie, onderwerp, bericht en evt bijlagen. Als voorbeeld de PDF zoals in e-Suite wordt gemaakt, zie toegeveogde voorbeeld.

**Comment by robertverboom** [comment]
Test ok

**Comment by HilbrandHurtak** [comment]
Mail wordt nu automatisch als pdf omgezet en aan de documenten toegevoegd. De gevraagde gegevens zijn nu aanwezig
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/805a9901-b83d-4eae-b057-54e7e5ca514c)

**Comment by HilbrandHurtak** [comment]
Test ok
