### ISSUE TITLE
BUG: Vertaling formulier definitie 'Verzenden besluit'

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2079]
***Steps to reproduce:***

1. Ga naar een zaaktype in de ZAP.
2. verander onder taakgegevens een formulierdefinitie 
3. 

***Expected***
Verzenden besluit

***Actual***
formulierDefinitie.VERZENDEN_BESLUIT

**Comment by andyverberne** [comment]
Formulier verzenden besluit is geen taak formulier en mag daar dus niet gekozen worden.
Hier moeten we nog iets op vinden.
