### ISSUE TITLE
BUG: Datum formaat in edit mode wijkt af van formaat op het Zaaktonen scherm

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#208]
***Steps to reproduce:***

1. Open de zaak ZAAK-2022-0000000001 op de https://zac.testen-public-service-platform.net/ omgeving
2. Ga naar Startdatum
3. Klik op Edit mode

***Expected***
DD-MM-YYYY wordt getoond

***Actual***
D-M-YYYY wordt getoond

Speelt op alle plaatsen waar datumvelden worden gebruikt

**Comment by bartlukens-atos** [comment]
Timeboxed 1h

**Comment by robertverboom** [comment]
test ok
