### ISSUE TITLE
Contactgegevens tonen bij initiator 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2080]
***Als*** Behandelaar

***Wil ik*** de contactgegevens (indien beschikbaar) tonen bij de initiator 

***Zodat*** ik niet eerst door moet naar de personen/bedrijven pagina 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*

- Could haves
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Via #293 is het toekennen van een initiator gerealiseerd. Met deze story is deze functionaliteit uitgebreid door naast de persoonsgegevens ook de contactgegevens van de initiator op te halen en te tonen in het Initiator blok bij de zaak en op de persoons- of bedrijfspagina. De contactgegevens worden opgehaald via de Klanten API.

***Belangrijkste functionaliteiten:***
- Gebruiker kan op de zaakgegevenspagina in het Initiator blok de contactgegevens die van de initiator bekend zijn bekijken. Een streepje betekent dat er geen gegevens bekend zijn.

**Comment by RoyBuis** [comment]
### Refinement 5-1

- tel nr en e-mail van initiator toevoegen aan gegevensblok
- alle gegevens op 1 rij houden, contactgegevens rechts
- als gegevens leeg zijn dan een streepje tonen

**Comment by hansmarks** [comment]
- Ik heb meteen ook geregeld dat we van de bedrijfsadressen de postcode tonen, als we die hebben.

- En ik heb ervoor gezorgd dat de adressen als ze te lang zijn opbreken in meerdere regels maar dan alleen tussen het straathuisnummerdeel en de postcode en tussen de postcode en de woonplaats. Dus nooit midden in de woonplaats als die een spatie bevat en ook niet binnen het straathuisnummerdeel.

- En ik heb de identificerende velden vooraan gezet. Volgorde van de velden in persoon-/bedrijf-scherm (links) en in het initiator-blok heb ik gelijk gehouden.

**Comment by hansmarks** [comment]
En toen ik toch bezig was heb ik er ook maar meteen voor gezorgd dat er nergens meer een nieuwe regel begonnen wordt op een streepje in een datum. Datums staan daardoor nooit gesplits over twee regels.

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Test met zaak ZAAK-2023-0000000076:
Persoon nu in Accept niet te kiezen, bedrijf wel.
Geen postcode aanwezig bij gekozen bedrijf. (en ook geen huisnummer) In ZAC Accept

**Comment by KarinMasselink** [comment]
@VictorTielenius heb voor personen een link met de 501 melding. Maar die van bedrijven kan ik zo snel niet vinden. Wil je daar een aparte US voor maken en deze linken.

**Comment by VictorTielenius** [comment]
#2525 (postcode en huisnummer bij een Bedrijf) aangemaakt.

**Comment by KarinMasselink** [comment]
@VictorTielenius heb hem gevonden onder 814 deze zat verstopt in de sprint. Wordt deze sprint als het goed is opgeleverd. Heb hem al toegevoegd als blocking.

**Comment by KarinMasselink** [comment]
@VictorTielenius graag hertesten voor personen, de bug is opgelost.
