### ISSUE TITLE
initiator e-mail vooraf ingevuld hebben 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2081]
***Als*** Behandelaar

***Wil ik*** bij Ontvangstbevesting mail, fase mails (afronden intake en afronden in behandeling) en bij het verzenden besluit het e-mail adres van de initiator voor ingevuld hebben (indien beschikbaar)

***Zodat*** ik dit niet over hoef te typen

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Tijdens de zaakbehandeling gebruikt de ZAC een aantal e-mails dat verstuurd wordt, voornamelijk aan de initiator. In deze story is deze functionaliteit uitgebreid waardoor door de behandelaar het bij de initiator bekende e-mailadres in het ontvanger veld kan zetten. Deze functie is alleen beschikbaar als de initiator een, in de Klanten API vastgelegd, e-mailadres heeft.

***Belangrijkste functionaliteiten:***
- Gebruiker kan bij het verzenden van een e-mail met het poppetje icoon het e-mailadres in het 'Ontvanger' veld plaatsen

**Comment by RoyBuis** [comment]
### Refinement 5-1

- In ontvanger veld optie om mailadres van initiator toe te voegen maken, bijvoorbeeld een knop naast het veld
- Knop alleen tonen als initiator een mailadres heeft
- Toepassen op alle mails die in de omschrijving van deze story genoemd zijn

**Comment by robertverboom** [comment]
Graag nog op de volgende plekken toevoegen: 
- in Zaak afhandelen pop-up (net als intake afonden)
- Taakstartformulier: Algemene informatie
- E-mail versturen

**Comment by HilbrandHurtak** [comment]
@RoyBuis . Om dit te testen heb ik dus een e-mailadres nodig die in de Klanten API is vastgelegd. Personen werkt niet. Heb jij misschien een bedrijf met een e-mailadres?

**Comment by robertverboom** [comment]
@HilbrandHurtak 
Op de Zandbak heb ik 4 klanten voorzien van een email en telefoonnummer. Deze kunnen ook gebruikt worden voor evt. andere testen. 

test BSN Persoon:
999992119
999995613
test verstigingsnummer Bedrijf: 
000037178598
000038509474
