### ISSUE TITLE
Besluit intrekken

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2084]
**Als** behandelaar
**wil ik** een verkeerd besluit kunnen intrekken
**zodat** er niet een foutief besluit aan een zaak hangt 

Als een besluit is aangemaakt en het document is verzonden (gemarkeerd met token), dan moet een besluit in te trekken zijn. 
Bij het intrekken van een besluit moet de behandelaar de vervaldatum zetten (voor invullen met vandaag?) en een vervalreden kiezen. 
- Besluit blijft zichtbaar bij de zaak, als ingetrokken besluit 
- Het document dat gekoppeld is aan het besluit mag ook niet verwijderd worden
- Gebruikersindicatie tonen? 

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #1473 is het vastleggen van een besluit bij een zaak opgeleverd. In deze story is deze functionaliteit uitgebreid waardoor het mogelijk is om een besluit in te trekken. 
Een besluit kan ingetrokken worden door deze een vervaldatum en -reden te geven. Om dit uit te voeren is het stop icoon beschikbaar bij een besluit.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met het stop icoon op het besluit een besluit intrekken waarbij de gebruiker de vervaldatum, de reden en een toelichting invult
- Gebruiker wordt erop geattendeerd dat het besluit een verzonden document heeft als dit het geval is
- Het intrekken van een besluit wordt inclusief de door de gebruiker gekozen reden en ingevulde toelichting vastgelegd in de historie van het besluit

**Comment by RikVedder** [comment]
@Werkgroep IB

**Comment by RoyBuis** [comment]
### Refinement 28-2

**Te realiseren**
- Besluit kan ingetrokken worden met intrekken knop
- Intrekken knop opent een pop-up 
- Als één van de gekoppelde documenten een verzonden indicatie heeft dan een melding 'let op: één of meer documenten zijn al verzonden' aan gebruiker tonen
- Bij intrekken vult de behandelaar:
  - de vervaldatum (v)
  -  de vervalreden, keuze uit 2 'intrekken' opties (v)
  - toelichting voor historie (v)
- Besluit mag door behandelaar worden ingetrokken als:
  - zaak niet is beëindigd
- Nadat besluit is ingetrokken:
  - Indicatie 'Is ingetrokken' (grijs) inclusief vervalreden tonen bij mouse over
  - Bij mouse over op vervaldatum de vervalreden tonen

**Comment by CommonGroundGroningen** [comment]
**Gebruiker kan met het stop icoon op het besluit een besluit intrekken waarbij de gebruiker de vervaldatum, de reden en een toelichting invult**
Test OK
**Gebruiker wordt erop geattendeerd dat het besluit een verzonden document heeft als dit het geval is**
Test OK
**Het intrekken van een besluit wordt inclusief de door de gebruiker gekozen reden en ingevulde toelichting vastgelegd in de historie van het besluit**
Test OK
