### ISSUE TITLE
e-mail opslaan in de zaak

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#2090]
**Gemeentenaam**:  Kampen

**Feature verzoek**: e-mail opslaan in de zaak

**Waarom zou je deze feature graag in de applicatie willen?**
Het opslaan van e-mail is een must. E-mail wordt ook beschouwd als archiefbescheiden en daar kan belangrijke informatie in staan.  Ik krijg een foutmelding als ik een mail wil opslaan via 'bestand toevoegen'. Het format .msg staat ook niet in de toegestane bestandtypen..

**Comment by robertverboom** [comment]
Wij snappen het verzoek. Zodra een omgeving wordt ingericht, kunnen bestandsformaten (denk aan .docx maar ook .msg) ingericht worden in de 'globale environmentvariabele'. De functionaliteit bestaat al, echter nog niet ingericht 

Wanneer je vanuit de ZAC mailt, wordt dit opgeslagen.

**Comment by robertverboom** [comment]
Wordt opgelost met #2377
