### ISSUE TITLE
Mail versturen met je eigen e-mailadres als afzender

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2095]
***Als*** behandelaar

***Wil ik***  ook een mail kunnen versturen vanuit mijn eigen e-mailadres

***Zodat*** inwoners hierop kunnen antwoorden (standaard staat meestal op norepy@gemeente.nl) 

***

### Acceptance criteria:
- Instelbare mailfunctionaliteit waarbij de behandelaar kan kiezen vanuit wel e-mailadres de mail wordt verstuurd

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Bij het verzenden van een mail is het voor de behandelaar mogelijk om te kiezen wat de afzender van de e-mail wordt. De keuzes die de behandelaar te zien krijgt zijn in de Mailgegevens tab van de zaps in te stellen en gelden voor alle mails. Een mail heeft altijd de opties e-mailadres van de gemeente, groep, behandelaar en het e-mailadres van de medewerker (de ingelogde gebruiker). Deze opties kunnen worden aangevuld met meer mailafzenders. Daarnaast kan een van deze opties kan als standaard ingevulde mailafzender worden ingesteld. Verder kan bij iedere mailafzender een eigen 'Antwoord aan' e-mailadres worden ingesteld, als dit niet wordt ingesteld dan is deze gelijk aan de afzender.
Het e-mailadres van de gemeente, inclusief de daarbij weergegeven naam van de gemeente, is in een omgevingsvariabele ingesteld. Het e-mailadres van de medewerker, groep en behandelaar wordt uit de gebruikersbeheer component opgehaald. 
***Belangrijkste functionaliteiten:***
- Gebruiker kan aan de altijd beschikbare mailafzender opties (e-mailadres van de gemeente, groep, behandelaar en medewerker) extra opties toevoegen. De extra opties moeten eerst aan de referentietabel 'AFZENDER' worden toegevoegd.
- Gebruiker kan zelf e-mailadressen aan de referentietabel 'AFZENDER' toevoegen, deze zijn daarna als mailafzender en 'Antwoord aan' te gebruiken
- Gebruiker kan een 'Antwoord aan' instellen bij iedere mailafzender'
- Gebruiker kan een default mailafzender instellen, deze wordt dan bij alle e-mails in de ZAC gebruikt

**Comment by robertverboom** [comment]
Het domein kan al aangepast worden, dat is MAIL_DOMEIN in de config files van de omgeving. We zetten er nu zaakafhandelcomponent voor, maar dat kunnen we ook configurable maken. 

Tijdens het inrichten van de omgevingen kan dit door een SI worden geconfigureerd

**Comment by HilbrandHurtak** [comment]
Weet niet of dat voldoende is. Tijdens het versturen van een mail vanuit de zaak moet de behandelaar kunnen kiezen wat de afzender moet gaan worden. Er moet dus ergens een keuze kunnen gemaakt. In de huidige e-Suite kan dit als volgt
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/c5232047-1dc5-4c5c-bf53-55f7681b2c0e)

Waarbij de standaard altijd noreply@gemeente is of je eigen email. Daarnaast kun je dan kiezen uit emailadressen die bij dit zaaktype gebruikt mogen worden( bijvoorbeeld versturen namen emailadres van Burgerzaken of Evenementen)

**Comment by GertrudeKampherbeek** [comment]
![image.png](https://images.zenhubusercontent.com/6215ee21a7a0b74c19209bdb/23048fe5-5ee4-49a4-bcb8-ed2a5b5e1b89)
werkgroep refinement: Wat mij betreft akkoord.

**Comment by HilbrandHurtak** [comment]
Ook wat mij betreft akkoord
