### ISSUE TITLE
Mail versturen met flexibele keuze afzender emailadres

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2096]
***Als*** behandelaar

***Wil ik*** mail kunnen versturen met als afzender het mailadres van mijn afdeling/groep

***Zodat*** ik niet de standaard noreply@gemeente.nl of mijn eigen a-mailadres moet gebruiken

***

### Acceptance criteria:
-Het kunnen versturen van mail vanuit een van te voren aangeven afdeling/groep e-mailadres 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Bij het verzenden van een mail is het voor de behandelaar mogelijk om te kiezen wat de afzender van de e-mail wordt. De keuzes die de behandelaar te zien krijgt zijn in de Mailgegevens tab van de zaps in te stellen en gelden voor alle mails. Een mail heeft altijd de opties e-mailadres van de gemeente, groep, behandelaar en het e-mailadres van de medewerker (de ingelogde gebruiker). Deze opties kunnen worden aangevuld met meer mailafzenders. Daarnaast kan een van deze opties kan als standaard ingevulde mailafzender worden ingesteld. Verder kan bij iedere mailafzender een eigen 'Antwoord aan' e-mailadres worden ingesteld, als dit niet wordt ingesteld dan is deze gelijk aan de afzender.
Het e-mailadres van de gemeente, inclusief de daarbij weergegeven naam van de gemeente, is in een omgevingsvariabele ingesteld. Het e-mailadres van de medewerker, groep en behandelaar wordt uit de gebruikersbeheer component opgehaald. 
***Belangrijkste functionaliteiten:***
- Gebruiker kan aan de altijd beschikbare mailafzender opties (e-mailadres van de gemeente, groep, behandelaar en medewerker) extra opties toevoegen. De extra opties moeten eerst aan de referentietabel 'AFZENDER' worden toegevoegd.
- Gebruiker kan zelf e-mailadressen aan de referentietabel 'AFZENDER' toevoegen, deze zijn daarna als mailafzender en 'Antwoord aan' te gebruiken
- Gebruiker kan een 'Antwoord aan' instellen bij iedere mailafzender'
- Gebruiker kan een default mailafzender instellen, deze wordt dan bij alle e-mails in de ZAC gebruikt

**Comment by RoyBuis** [comment]
### Refinement 19-1

**Te realiseren**

Per zaaktype is in de zaps in te stellen:
- 0 of meer afzenderadressen uit referentietabel AFZENDER
- inclusief 2 speciale waarden voor default gemeente en ingelogde gebruiker zelf
- per afzenderadres is een reply-to in te stellen
- één moet als default ingesteld kunnen worden

Bij versturen mail kan een gebruiker:
- kiezen uit de gekoppelde afzenderadressen
- default is er alleen iets ingevuld als er in de zaps een default is configureerd
- ongeacht wat er in de zaps is ingesteld heeft de gebruiker altijd ook keuze uit eigen mailadres (uit KeyCloak) en default gemeente
- niet zelf de reply-to bepalen, dit wordt bepaald door de zaps instelling
- bij meerdere keuzes tonen op alfabetische volgorde

Default afzendadres gemeente komt in een environment variabele  

Zaps indeling wordt aangepast
- De tab 'Mailtemplate gegevens' wordt 'Mail gegevens'
- De statusmails instellingen verplaatsen van 'Algemene gegevens' naar deze nieuwe tab
- De beschikbare afzendermailadressen komen ook in deze tab

**Comment by GertrudeKampherbeek** [comment]
![image.png](https://images.zenhubusercontent.com/6215ee21a7a0b74c19209bdb/7fcd8635-5add-41c0-9056-fa6447591332)
werkgroep refinement: wat mij betreft akkoord
