### ISSUE TITLE
BUG: Taak aanvullende informatie geeft 500

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2099]
***Steps to reproduce:***

1. Maak een zaak aan
2. Voeg taak: aanvullende informatie toe
3. 

***Expected***
Taak wordt aangemaakt

***Actual***
500 error: Cannot invoke "String.equals(Object)" because the return value of "java.util.Map.get(Object)" is null

**Comment by RoyBuis** [comment]
### Refinement 5-1
Waarschijnlijk al gefixt via #2030
