### ISSUE TITLE
BUG: Sortering werkt niet op inrichtingscheck tabel

### ISSUE THREAD

**Issue by marcoatos** [NL-AMS-LOCGOV/zaakafhandelcomponent#2102]
Ga naar Beheer instellingen -> Inrichtingscheck.

Klik op een van de header kolommen. 
Verwacht: Er veranderen pijltjes op de header wat aantoont dat er sortering mogelijk is.
Werkelijk: Er gebeurt geen sortering op tabel.

Ik heb dit onlangs gefixed voor de mailtemplates. Geef in html de mat-sort-header een id. En implementeer de (matSortChange) methode net als bij mailtemplates. Ga via een switch door de id's en sorteer. Overige sort variabelen en classes kunnen weg op de tabel, die zijn niet nodig.

**Comment by RoyBuis** [comment]
### Refinement 5-1

Zie oplossing van Marco in de omschrijving
