### ISSUE TITLE
Overzicht zaken per zoekresultaat(bijvoorbeeld personen of bedrijven) verbeteren

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2105]
***Als*** behandelaar

***Wil ik*** nadat ik heb gezocht op alle zaken van een persoon of bedrijf op een eenvoudige wijze de openstaande of gesloten zaken zien

***Zodat*** ik niet diverse filters moet gaan aanzetten

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

### Omschrijving
In het overzicht moet ik nu filteren op de status(en dat kunnen er dus meerdere zijn) om de splitsing tussen de afgeronde en openstaande zaken te zien. Graag de einddatum van de zaak en resultaat toevoegen(leeg is open) of een schuifknop waarmee je eenvoudig een verschil tussen de openstaande en afgesloten zaken kunt weergeven

Nu is dat niet duidelijk genoeg
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/3c1b6de3-aec5-41f2-916c-02ea311a13cb)

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De gegevens van een persoon of bedrijf kunnen bekeken worden vanuit de persoons- of bedrijfsgegevenspagina. Deze pagina bevat een overzicht van alle zaken waar de persoon of bedrijf bij betrokken is die in de ZAC worden behandeld. Het overzicht toont standaard de openstaande zaken. Met deze story is het mogelijk gemaakt om ook afgeronde zaken aan het overzicht toe te voegen.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in de persoons- of bedrijfsgegevenspagina de afgeronde zaken aan het het overzicht toevoegen door het schuifje 'Toon afgeronde zaken' aan te zetten

**Comment by RoyBuis** [comment]
### Refinement 12-1

**Te realiseren**

- In persoons/bedrijfpagina schuifje toevoegen om ook de afgeronde zaken te tonen (op zelfde wijze als taken bij een zaak)
- Default alleen de openstaande zaken tonen (schuifje dus dicht)

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Getest bij bedrijven omdat haal centraal personen niet werkt. Er is nu een schuifje voor het tonen van afgeronde (en openstaande) zaken. Default worden alleen de openstaande zaken getoond
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/adc2f45e-8f1d-455f-8199-53999813e27a)
 
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/70fac2f5-c271-41d2-953c-e323be69dd86)
