### ISSUE TITLE
BUG: Websockets na toevoegen document op besluit werken niet

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2107]
***Steps to reproduce:***

1. Maak een zaak aan
2. Voeg een document (type besluit) en een besluit toe
3. Voeg document aan besluit toe

***Expected***
Document component krijgt websocket, dat deze niet meer te ontkoppelen is + gebruikersindicatie van besluit

***Actual***
pas na refresh worden de indicatie 'is Besluit' gezet en knippen/ontkoppelen niet getoond. 

NB: Zelfde speelt na ontkoppelen van een document van een besluit

**Comment by RoyBuis** [comment]
### Refinement 5-1

Er komt een notificatie op kanaal 'besluit' over een besluitinfomatieobject create of destroy. Die moet op een manier vertaald worden naar een web socket 'zaak gewijzigd'.

**Comment by hansmarks** [comment]
Notabene! Kanaal besluit toevoegen aan het open_notificaties-abonnement.

**Comment by robertverboom** [comment]
test ok
