### ISSUE TITLE
tonen van versienummer software

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2126]
***Als*** beheerder

***Wil ik*** kunnen zien welke versie van de software wordt gebruikt

***Zodat*** ik kan zien wat de cyclus van update is

***

### Acceptance criteria:
- bv onderaan het venster het softwarenummer eventueel aangevuld met een datumstamp

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De informatie over de software versie van de ZAC is onderaan bij de Inrichtingscheck in het instellingen menu te zien. Hier staan een build nummer en het tijdstip dat deze gemaakt is. Zodra er een officiele versie is uitgebracht zal ook het versienummer getoond worden.

***Belangrijkste functionaliteiten:***
- Gebruiker kan de informatie van de versie van de ZAC in de Inrichtingscheck bekijken
- Het versienummer wordt ook onderaan de pagina getoond, door met de muisaanwijzer over de versie te zweven is de build informatie te zien

**Comment by RoyBuis** [comment]
### Refinement 17-1

Spike om de beste manier uit te zoeken

- Het gaat om het image id en/of datum/tijd dat ergens getoond moet worden 
- Versienummer is een handmatig gegenereerd nummer (dit komt uit een pom)
- Buildnummer is een automatisch gegenereerd nummer (environment variabele die in de image gezet wordt?)
- Kijk naar Google build
- Inrichtingscheck wellicht goede plek om de nummers te tonen

**Comment by andyverberne** [comment]
@hansmarks : Maak jij het nog visueel aantrekkelijk?

**Comment by HilbrandHurtak** [comment]
Versie nummer is opgenomen onder aan het scherm met mouseover functionaliteit. Tevens staat het versienummer bij de beheerinstellingen. Voor dit ticket Test OK
Nieuwe wens (#2384) om de knop te verplaatsen afzonderlijk testen.
