### ISSUE TITLE
In de mailtemplate 'Proces aanvullende informatie' de variabele 'Taakfataledatum' toevoegen zodat deze in de template gebruikt kan worden

### ISSUE THREAD

**Issue by ronniekoopmans-atos** [NL-AMS-LOCGOV/zaakafhandelcomponent#2127]
In de mailtemplate 'Proces aanvullende informatie' de variabele 'Taakfataledatum' toevoegen zodat deze in de template gebruikt kan worden

**Comment by hansmarks** [comment]
**Hans Marks**
Roy, er komt een mailtemplatevariabele TAAK_FATALEDATUM. Kan de fatalestreefdatum van een taak leeg zijn? En zo ja, is dit dan een variabele die je in dat geval wilt laten staan (lees: fout in je template) of moet ie vervangen worden door een lege string (lees: je weet niet, als je template aan het maken bent, of die leeg zal zijn)?

Ter info: ZAAK_FATALEDATUM doet het eerste.

**Roy Buis**
ja, de fatale datum kan leeg zijn tegenwoordig. Zoals die nu werkt, dus laten staan als fout in de template, lijkt mij de beste keuze hier!

**Comment by hansmarks** [comment]
Voor alle duidelijkheid:
- Koppeling tussen mailtemplates en sets templatevariabelen: https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/blob/main/src/main/java/net/atos/zac/mailtemplates/model/Mail.java
- Definitie van de sets (welke variabelen zitte erin?): https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/blob/main/src/main/java/net/atos/zac/mailtemplates/model/MailTemplateVariabelen.java

**Comment by robertverboom** [comment]
test ok

**Comment by hansmarks** [comment]
Die is beschikbaar in de mailtemplates: SIGNALERING_TAAK_OP_NAAM en SIGNALERING_TAAK_VERLOPEN

Zie:

https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/blob/main/src/main/java/net/atos/zac/mailtemplates/model/Mail.java

https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/blob/main/src/main/java/net/atos/zac/mailtemplates/model/MailTemplateVariabelen.java

**Comment by HilbrandHurtak** [comment]
Ik had hem ook hier verwacht
![image](https://user-images.githubusercontent.com/96229645/231479111-c760646c-97a0-4b35-bc7f-d95910b293bb.png)
Nu geef je in de taak/mail dus een opschortingstermijn op en moet je handmatig nog de uiterlijke datum invullen

**Comment by hansmarks** [comment]
Geen probleem, graag gedaan.

"Ik hoop dat Asterix het me straks allemaal nog even uitlegt... ik weet altijd graag waarvoor ik vecht."

-- Obelix in geen idee meer welk Asterix-album. ;-)
