### ISSUE TITLE
TaakVariabelenService.TAAK_DATA_DOORLOPTIJD omzetten naar Taak.duedate 

### ISSUE THREAD

**Issue by ronniekoopmans-atos** [NL-AMS-LOCGOV/zaakafhandelcomponent#2129]
TaakVariabelenService.TAAK_DATA_DOORLOPTIJD hernoemen naar TAAK_DATA_FATALEDATUM 
Ook AanvullendeInformatie.ts aanpassen

**Comment by RoyBuis** [comment]
### Refinement 12-1

De taakdata fatale datum moet geen taakdata element zijn maar moet worden gemapt op taak.duedate. Zie ook hoe wordt omgegaan met de toekenning van een taak.
