### ISSUE TITLE
Bij overdragen taak de reden vastleggen

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2131]
***Als*** behandelaar

***Wil ik*** bij het wijzigen van de toekenning van een  bestaande taak aan een groep en/of behandelaar wil ik dat de reden wordt vastgelegd

***Zodat*** in de taakhistorie te zien is waarom taken zijn overgedragen

***

### Acceptance criteria:
- dit geldt zowel voor een specifieke taak als taken verdelen via de werklijst

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze user story is het 'reden' veld bij het toekennen van zaken en taken aangepast. In de oude situatie was niet op iedere plek waar een zaak of taak toegekend kon worden een reden veld beschikbaar en was het veld afwisselend een verplicht in te vullen veld.  
In de nieuwe situatie is bij het toekennen zowel vanuit een geopende zaak of taak als vanuit de werklijsten een reden veld beschikbaar dat optioneel ingevuld kan worden. Als de reden wordt ingevuld dan wordt deze gebruikt in de zaak- of taakhistorie.
***Belangrijkste functionaliteiten:***
- Gebruiker kan bij het toekennen van een zaak of taak aan een groep en/of behandelaar vanuit de geopende zaak of taak een reden invullen
- Gebruiker kan bij het toekennen van een zaak of taak aan een groep en/of behandelaar vanuit de werklijst Zaken-werkvoorraad en Taken-werkvoorraad een reden invullen
- Gebruiker kan de bij het toekennen ingevulde reden inzien in de zaak- en taakhistorie

**Comment by RoyBuis** [comment]
### Refinement 12-1

Het is nu niet mogelijk om de reden bij een taak op te slaan. We moeten onderzoeken wat de mogelijkheden zijn en plannen een spike in.

**Comment by andyverberne** [comment]
Er staan 2 ToDo's in de code op de plaatsen waar vanuit de front end de reden moet worden meegegeven

**Comment by robertverboom** [comment]
Als we dit gaan doorvoeren, moeten ook rekening houden met de taken-werkvoorraad: Bulk verdelen/vrijgeven

**Comment by RoyBuis** [comment]
### Refinement 16-3

Er is gekozen om de werking voor overdragen van taken en zaken identiek te maken. Bij beiden kan er een reden worden ingevuld die dan in de historie wordt getoond. Het invullen van een reden is echter niet verplicht zodat hier geen datavervuiling optreedt door het invullen van loze redenen. Als een reden verplicht moet worden ingevuld dan zal dit in het werkproces vastegelegd moeten worden.

**Te realiseren**

Bij overdragen taak vanuit zaak
- reden veld (optioneel)
- reden wordt als toelichting in historie van taak getoond (dit is al gemaakt, moet alleen nog opgehaald worden uit reden veld

Bij overdragen zaak
- reden veld (optioneel)
- reden wordt als toelichting in de historie van de zaak getoond (dit is al zo)

Bij verdelen vanuit werklijst voor zowel zaken als taken
- reden veld tonen (optioneel)
- reden wordt als toelichting in de historie van de zaak getoond (dit is al zo)

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Tijdens de sprintdemo was er veel discussie over het wel of niet verplicht maken van het veld "Reden" op de diverse plekken. Ook binnen de werkgroep refinement waren de meningen verdeeld. In de oude e-Suite zijn de meeste velden verplicht. Dit is niet zonder reden gedaan(nemen we aan). Om dit te achterhalen is Gertrude om haar mening gevraagd (welke "Reden" velden moeten wel verplicht en welke niet(bijvoorbeeld toekennen via bulk). Tevens gaat Victor dit nog eens vragen aan de koplopersgroep bij het testen van ZAC.

Voor nu heb ik het getest zoals het door de product owner is aangegeven (dus niet verplicht). Als het later anders moet worden dan komt hiervoor een nieuw ticket.

Test  
Bij overdragen taak vanuit zaak: AKKOORD
Bij overdragen zaak: AKKOORD
Bij verdelen vanuit werklijst voor zowel zaken als taken: AKKOORD
