### ISSUE TITLE
Inhoud van statusmails weergeven 

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2137]
***Als*** behandelaar

***Wil ik*** de inhoud van de e-mail die bij een statusovergang wordt vertuurd zien

***Zodat*** ik kan bepalen of de e-mail nodig is bij de situatie 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Via #499 en #671 is het verzenden van een standaard mail bij het afronden van de intake en in behandeling fase gerealiseerd. In deze user story is de UI van deze functionaliteit verbeterd door de inhoud van de standaard mail die verstuurd zal worden te tonen. 

***Belangrijkste functionaliteiten:***
- Gebruiker kan de inhoud van het bericht bekijken door op het pijltje in het ‘Bericht’ veld te klikken

**Comment by RoyBuis** [comment]
### Refinement 12-1

Dit gebeurt al bij de actie 'Intake afronden'. Deze oplossing ook toepassen bij de actie 'Zaak afhandelen'.

**Comment by HilbrandHurtak** [comment]
In behandeling: Akkoord
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/6709b1f9-e1ed-47d5-962c-535a4c2c83ee)

Zaak afhandelen: Akkoord
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/4542d7fb-3333-432f-a02d-88dc7b5f256e)

Te verzenden mail wordt getoond. Kan niet worden aangepast. Dat laatste was ook niet gevraagd
