### ISSUE TITLE
BUG: Vinkje Ondertekenen in Goedkeuren taak wordt verwijderd na klikken op de Opslaan button

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#2142]
***Steps to reproduce:***

1. Open zaak ZAAK-2023-0000000041 op Development omgeving
2. Open de taak Goedkeuren
3. Vink het document Werklijsten lopende en afgehandelde Zaken aan om te ondertekenen
4. Klik op de button 'Opslaan'

***Expected***
Verwachting is dat het vinkje Ondertekenen aangevinkt blijft staan

***Actual***
Het vinkje ondertekenen is na het klikken op de Opslaan button verdwene![Document ondertekenen vinkje wordt verwijderd na Opslaan.JPG](https://images.zenhubusercontent.com/61a7619ff842ca7ff613d64f/12dc8a4b-9f08-408b-840f-850e4c6dedb8)n

Het daadwerkelijk ondertekenen werkt eveneens niet, indien je op Opslaan en afronden klikt dan wordt er geen nieuwe documentversie aangemaakt en ook de status van het document wordt niet gewijzigd van In bewerking naar Definitief. Het vinkje ondertekenen is eveneens verdwenen.
![Document ondertekenen vinkje wordt verwijderd na Opslaan en Afronden](https://user-images.githubusercontent.com/75383503/212306935-ea1b412e-af74-4755-a94a-12b6d339abb6.JPG)

**Comment by RoyBuis** [comment]
### Refinement 17-1

- Het vinkje voor ondertekenen documenten moet worden opgeslagen in de taakdata bij tussentijds opslaan. 
- Het daadwerkelijk uitvoeren van de ondertekening gebeurt alleen bij Opslaan en afronden.
- Bij afronden van de taak wordt nu de ondertekening niet op document gezet en wordt geen nieuwe versie gemaakt.

**Comment by robertverboom** [comment]
test ok
