### ISSUE TITLE
Toevoegen van id's voor checkbox velden

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#2143]
Graag op de volgende plaatsen id's toevoegen i.v.m. de auto testen voor ZAC

- Op de taak Aanvullende informatie opvragen staat nu een checkbox(en):
- Bij de Bijlagen (documenten). Indien mogelijk graag hier een id toevoegen, dit is nu een valiabel id, die in de loop der tijd wisselt, hetgeen het onderhoud van de testen lastig maakt,

**Comment by hansmarks** [comment]
Bij het aanmaken van de taak zie ik 1 checkbox, daar staat een id op: <input type="checkbox" class="mdc-checkbox__native-control" id="zaakOpschorten_checkbox-input" tabindex="0" aria-checked="false">

**Comment by hansmarks** [comment]
Bij het verder afhandelen van de taak zie ik geen checkboxen. Wel drie radiobuttons, maar ook daar staat een id op: \<input type="radio" class="mdc-radio__native-control" id="mat-radio-2-input" name="mat-radio-group-0" value="aanvullende-informatie.geleverd-akkoord" tabindex="0">

**Comment by hansmarks** [comment]
De checkboxen in documenten tabel zijn ook dynamisch uiteraard, dus ook daar een volgnummer in het id: <input type="checkbox" class="mdc-checkbox__native-control" id="**mat-mdc-checkbox-1-input**" tabindex="0" aria-checked="false">

**Comment by robertverboom** [comment]
wat mij betreft prima! bedankt
