### ISSUE TITLE
BUG: Verkeerd zaaktype wordt getoond bij toekennen van de domeinen in ZAP 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2151]
***Steps to reproduce:***

1. Ga naar de keycloack van de zandbak
2. Geef jezelf de volgende rollen; beheerer, coordinator, default-roles-zandbak, domein_kampen en recordmanager. Als het goed is heb je ook domein_overig (dit is een default role) 
3. Ga naar de ZAC zandbak. 
- In de referentietabellen zijn 6 domeinen toegekend. Van de koploper gemeenten en domein_overig. 
- In de ZAP zijn de zaaktypes toegekend aan de domeinen: 
  domein_kampen > Aanvragen evenementenvergunning beoordelen
  domein_overig > Melding klein evenement
4. Maak een nieuwe zaak aan

***Expected***
Zaaktype beschikbaar met de toegekende rollen: 
- Aanvragen evenementenvergunning beoordelen
- Melding klein evenement

***Actual***
Zaaktype beschikbaar met de toegekende rollen: 
- Wegenbeheer en onderhoud  (dit zaaktype is ingeregeld bij het domein_oldenzaal) 
- Melding klein evenement

**Comment by andyverberne** [comment]
Ik kan hem niet meer reproduceren :-(
Ik heb extra logging toegevoegd zodat bij inloggen zichtbaar is voor welke zaaktypen je bent geauthentiseerd. 
Wanneer het dus fout gaat kunnen we in de log van het zaakafhandelcomponent kijken.
