### ISSUE TITLE
BUG: Documentstatus wordt niet aangepast na versie wijziging

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2152]
***Steps to reproduce:***

1. Maak een document aan
2. Zet documentstatus op 'In bewerking'
3. Ga naar het document
4. Wijzig versie en documentstatus

***Expected***
- De optie 'Gearchiveerd' mag niet getoond worden
- Documentstatus wordt gewijzigd na opslaan

***Actual***
Documentstatus blijft ongewijzigd.

**Comment by RoyBuis** [comment]
### Refinement 17-1

Komt door refactoring, wordt door Andy bekeken

**Comment by robertverboom** [comment]
test ok
