### ISSUE TITLE
Improvement: Loader voor omzetten naar PDF 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2153]
Soms duurt het enige tijd tot een document geconfigureerd wordt naar een PDF. Graag een loader indicatie.

**Comment by RoyBuis** [comment]
### Refinement 24-1

- Knop disabelen terwijl conversie loopt
- Util service set loading aanroepen
- Op moment dat websocket binnenkomt dat PDF is aangemaakt de knop weer enabelen en loading uitzetten
