### ISSUE TITLE
Uitlijning zaakgegevens pagina

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2167]
***Als*** behandelaar

***Wil ik*** de uitlijning op gelijke hoogte hebben

***Zodat*** het beter te lezen is

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by robertverboom** [comment]
![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/c2b2b94e-0ae3-46e6-b1cf-252bc869dc38)

**Comment by RoyBuis** [comment]
### Refinement 24-1

- Idee: ieder veld een minimum hoogte
- Later nog refinen nadat technische aanpassingen (Angular update) zijn doorgevoerd. Niet in sprint van 26-1
