### ISSUE TITLE
OLDENZAAL: bestandstype toevoegen aan documentencomponent

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2168]
***Als*** Behandelaar

***Wil ik*** het bestandstype als icoon toegevoegd hebben in het documentenoverzicht component

***Zodat*** Dan ziet de gebruiker snel welk bestand het is.

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 24-1

- Icoon met type bestand toevoegen aan document
- Positie: voor de titel van het document met spatie ertussen (let op ook op documentgegevenspagina aanpassen!)
- Title/tooltip toevoegen op de iconen (let op ook op documentgegevenspagina aanpassen!)

**Comment by VincentHofman** [comment]
Tevens de grote van het document tonen

**Comment by robertverboom** [comment]
Bestandsgrootte wordt opgepakt in een andere story: #2241

**Comment by robertverboom** [comment]
icoon ontbreekt nog bij: 

- Bijlage bij mail
- Taakstartformulieren
- Taak bewerkformulier, zoals bij ondertekenen
- Besluit toevoegen 
- Evt bij besluit tonen (al is de informatie daar minimaal)
