### ISSUE TITLE
OLDENZAAL: Wijzig kolommen op documentencomponent

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2169]
***Als*** Behandelaar

***Wil ik*** de kolommen kunnen wijzigen in de documentencomponent

***Zodat*** ik niet relevante kolommen uit kan zetten om overzicht te waarborgen. 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 24-1

Heeft veel impact op code en op performance. Voor nu gaan we deze niet realiseren.
