### ISSUE TITLE
OLDENZAAL: Downloadfunctie op de documentgegevenscomponent

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2170]
***Als*** Behandelaar

***Wil ik*** een document kunnen downloaden direct vanuit de zaakgegevenspagina

***Zodat*** dit mij extra klikken scheelt 

***

### Acceptance criteria:
-

***
### Prioriteit
- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Vanui het documentenoverzicht bij een zaak kan ieder document direct vanuit het overzicht worden gedownload.

***Belangrijkste functionaliteiten:***
- Gebruiker kan vanuit documentenoverzicht een document downloaden door op het Downloaden icoon te klikken

**Comment by RoyBuis** [comment]
### Refinement 24-1

Download knop toevoegen bij de documenten
Knop heeft dezelfde rechten als raadplegen document

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
In een zaak nu bij het blok Documenten de mogelijkheid om een document te openen met knop Downloaden. 
In de e-Suite is deze knop ook aanwezig en heet de knop "Document openen".
WG R&A: Welke naam zou deze knop moeten hebben?

**Comment by VictorTielenius** [comment]
5-4: In WG R&A besloten dat deze knop Downloaden mag heten (voor nu).
Tzt met userbility alle knopnamen meenemen
