### ISSUE TITLE
Toegevoegde bijlagen in Open Formulieren

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2178]
***Als*** behandelaar

***Wil ik*** ik de bij een verzoek toegevoegde bijlagen kunnen in een zaak kunnen raadplegen

***Zodat*** ik de inhoud van de bilagen kan beoordelen

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze user story is het verwerken van bijlagen die bij een productaanvraag zijn toegevoegd gerealiseerd. Als er vanuit een productaanvraag een zaak wordt aangemaakt dan worden de bijlagen als document aan de zaak toegevoegd. Als er vanuit de productaanvraag geen zaak wordt aangemaakt en de productaanvraag in de Inbox productaanvragen komt dan is vanuit de Inbox te zien dat er bijlagen aanwezig zijn.
In beide gevallen worden de bijlagen tijdelijk in de Inbox documenten geplaatst totdat er een zaak wordt aangemaakt of de productaanvraag in de Inbox productaanvragen belandt.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in de Inbox productaanvragen in de regel van de productaanvraag in de kolom 'Aantal bijlagen' zien of er bijlagen zijn

**Comment by RoyBuis** [comment]
### Refinement 24-1

Spike inplannen om werking uit te zoeken. Waarom komen bijlagen nu niet in Open zaak?

- De productaanvraag bevat de url's van de toegevoegde bijlagen
- Nu wordt bij ontvangst van productaanvraag geen zaak gestart door ZAC. Aanvraag PDF staat wel in Open zaak, bijlagen niet.

**Comment by robertverboom** [comment]
### Refinement 06-04
3 uur besteden om bijlagen werkend te krijgen 
- Bij automatisch verwerken productaanvraag de bijlagen koppelen aan de zaak en controleren dat de documenten zijn verwijderd uit de inbox documenten
- Bij niet automatisch verwerken productaanvraag; Aantal bijlagen kolom toevoegen in inbox productaanvragen en bijlagen verwijderen uit de inbox documenten

**Comment by ronniekoopmans-atos** [comment]
code, is klaar. het is echter niet mogelijk om bijlagen toe te voegen (gaat iets fout in open-forms)
Als dat is opgelost, kan dit issue getest worden

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Getest op de zandbak met:
https://open-forms.zandbak-public-service-platform.net/melding-klein-evenement/   en 
https://open-forms.zandbak-public-service-platform.net/indienen-klacht/

Beide formulieren blijven "Hangen" nadat ze zijn doorlopen en verstuurd. Er wordt geen zaak aangemaakt en er komt ook geen foutmelding op het scherm. Test met bijlage kan dus niet worden uitgevoerd. **NIET AKKOORD**

**Comment by HilbrandHurtak** [comment]
Hoi Hilbrand,

Voor #2178 zit er een bug in Open Formulieren die dit veroorzaakt. Ik vraag morgenochtend of dit opgepakt kan worden.

Met vriendelijke groet,
Roy Buis
Tel: +31 6 30518783

**Comment by HilbrandHurtak** [comment]
Na herstart opnieuw getest. Formulier wordt nu wel verzonden maar de afhandeling in ZAC gaat niet goed.

Dag Roy

Ik heb opnieuw getest

Formulier wordt nu wel verstuurd. Binnen ZAC komen er nu 2 documenten in de Inbox documenten. Tevens worden er 5 zaken (zonder documenten) aangemaakt

5 zaken
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/87966fc6-3ab9-413d-b408-329797123dc6)
 

2 documenten
 ![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/6a2b3a31-a998-4d9d-8ebd-12e8ebeabd6a)

Gr
Hilbrand

**Comment by robertverboom** [comment]
@HilbrandHurtak Aanvraagdocument ontbreekt bij het zaaktype. Zal ik inrichten

**Comment by HilbrandHurtak** [comment]
@robertverboom . Helder. Ik ga dan de hertest uitvoeren. Laat maar even weten als het gereed is

**Comment by HilbrandHurtak** [comment]
@robertverboom is dit al aangepast? Heb net een testje gedaan maar krijg nog steeds 3 zaken en 2 documenten

**Comment by robertverboom** [comment]
De fout met formulieren is een configuratiefout geweest. URL met OF in combinatie met OZ op de zandbank stond niet goed.

**Comment by HilbrandHurtak** [comment]
Getest met formulier klacht waarbij meerdere bijlagen worden meegestuurd. De zaak wordt netjes aangemaakt en de meegestuurde documenten zijn als afzonderlijke bijlagen aan de zaak toegevoegd. TEST OK 

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/c99ccb9b-f468-4cc2-973b-9edd550dbdcd)
