### ISSUE TITLE
ACCEPTATIE BUG: In ZAC Accept een 500 foutmelding diverse plekken

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#2188]
**Gebruikersrol:** Behandelaar
**Device:** Laptop
**OS:** 
**Browser:**
**Versie:**

**Issuenummer**
#1895

**Beschrijf de bug**
500 foutmelding

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1. Bij "Zaken-werkvoorraad"
2. Bij Toevoegen Betrokkene, bij kiezen Soort Betrokkene, in zaak ZAAK-2023-0000000005
3. Openen zaak ZAAK-2023-0000000001

**Verwacht gedrag**
Geen foutpagina

**Daadwerkelijk gedrag**
Foutpagina
De server heeft code 500 geretourneerd
Algemene Fout

**Screenshots**
Nvt

**Foutmelding/Log tekst**
Foutpagina
De server heeft code 500 geretourneerd
Algemene Fout

**Comment by VictorTielenius** [comment]
Ook 500 melding op Accept ZAC bij:
Openen zaak: ZAAK-2023-0000000009. Lijkt met ophalen Initiator te maken te hebben bij deze zaak.
En bij ZAAK-2023-0000000010 als je van de Betrokkene de gegevens wil ophalen, via de 3 puntjes bij Gegevens (op Tabblad Betrokkenen)

**Comment by andyverberne** [comment]
Probleem 1. 2. en 3. spelen niet meer op de acceptatie omgeving.
Ik liep nog wel tegen #2258 aan. Deze speelt ook op de develop.

**Comment by VictorTielenius** [comment]
Vandaag (2-3-2023) Zaken - Werkvoorraad nog steeds foutpagina (500) in ZAC Accept

**Comment by KarinMasselink** [comment]
@VictorTielenius als goed is zijn deze bugs met de nieuwe release opgelost. Wil je dit nogmaals testen en anders het issue sluiten?

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by VictorTielenius** [comment]
ZAAK-2022-0000000012 geeft nog steeds foutmelding

**Comment by KarinMasselink** [comment]
@VictorTielenius graag met nieuwe zaak proberen i.v.m. verouderde data.

**Comment by KarinMasselink** [comment]
@robertverboom komt dit nog door een storing?

**Comment by KarinMasselink** [comment]
@VictorTielenius bug is opgelost.

**Comment by VictorTielenius** [comment]
Getest en geen 500 foutmeldingen meer.
