### ISSUE TITLE
7.8.3 tonen van informatie in PDF die is opgemaakt na versturen mail

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2192]
***Als*** medewerker

***Wil ik*** in de PDF die is gecreëerd na het versturen van mail de volgende informatie zien:
- mailadres van afzender
- de datum en tijdstamp van moment versturen
- mailadres van de ontvanger
- in onderwerp - zaakomschrijving
- de meegestuurde bijlagen waarvan dan de documenttitel wordt getoond en niet de bestandsnaam

***Zodat*** in de verstuurde mail terug kan lezen wat er mail de mail is gebeurd.

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by GertrudeKampherbeek** [comment]
![image.png](https://images.zenhubusercontent.com/6215ee21a7a0b74c19209bdb/b423b75f-2d7f-4d83-8bd2-2d9609605489)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Duplicaat, issue wordt gesloten.
