### ISSUE TITLE
OLDENZAAL: email versturen: bestandsextensie

### ISSUE THREAD

**Issue by VincentHofman** [NL-AMS-LOCGOV/zaakafhandelcomponent#2194]
**Gemeentenaam**:  Oldenzaal

**Feature verzoek**: Tonen van een bestandsextentie bij het toevoegen van een bestand bij een mail

**Waarom zou je deze feature graag in de applicatie willen?**
Als je vanuit de zaak wil mailen en een bijlage wil toevoegen, dan zie je als zaakbehandelaar niet welke bestandsextensie de zaakdocumenten heeft. Dit is wel gebruiksvriendelijk. Je wil als zaakbehandelaar zekerheid hebben welke bestanden je als bijlage toevoegt. Je wil zeker weten dat je geen Word bestand naar een klant mailt.

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Op verschillende plekken in de ZAC kan een e-mail verstuurd worden en kan daar een zaakdocument als bijlage aan toegevoegd worden. Bij het selecteren van deze documenten wordt nu bij ieder document met behulp van een icoon aangegeven welk type bestand het betreft. Voor de gangbare typen bestanden zoals PDF en Word worden de daarvoor bekende iconen gebruikt, voor de minder gangbare bestandstypen algemene iconen.
De volgende iconen worden gebruikt: PDF icoon voor bestandsextensie .pdf, Txt voor txt, Word voor doc, docx, ods, odt en rtf, Powerpoint voor ppt en pptx, Excel voor xls en xlsx, Image voor vsd, bmp, gif, jpeg, jpg en pmg, Video voor avi, flv, mkv, mov, mp4, mpeg en wmv.

***Belangrijkste functionaliteiten:***
- Gebruiker kan bij het selecteren van documenten die als bijlage aan een mail toegevoegd moeten worden aan het icoon bij de titel zien welk type bestand het betreft
- Gebruiker kan met de muisaanwijzer over de icoon zweven om een tekstuele beschrijving van het type bestand zien

**Comment by RoyBuis** [comment]
### Refinement 31-1

Zie ook #2168 voor vergelijkbare aanpassing.

**Te realiseren**
Iconen toevoegen aan documentenlijst op zelfde wijze als oplossing voor documentenoverzicht

**Comment by robertverboom** [comment]
test ok
