### ISSUE TITLE
10C.1.1 Voorafgaande – vervolgzaak relaties

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2197]
Epic 'zaak - zaak relatie' waaraan onderstaande userstorys zijn gekoppeld

10C.1.1 Voorafgaande – vervolgzaak relaties:
	10C.1.1.1. Voorafgaande vervolgzaak relatie Leggen #2198
	10C.1.1.2. Nieuwe vervolgzaak aanmaken vanuit een bestaande zaak #2199
	10C.1.1.3. Voorafgaande vervolgzaak relatie Ongedaan maken #2200

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Deze stories zijn gerealiseerd, epic kan gesloten worden
