### ISSUE TITLE
10C1.1.3. Voorafgaande vervolgzaak relatie ongedaan maken

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2200]
**Als**		: Gebruiker
**Wil ik**		: een voorafgaande en vervolgzaak relatie kunnen verwijderen 
**Zodat ik** 	: kan herstellen wanneer een dergelijke relatie tussen twee zaken foutief is gelegd

***

### Acceptance criteria:
•	Het ongedaan maken van een voorafgaande vervolgzaakrelatie moet mogelijk zijn wanneer de vervolgzaak nog open staat
•	Het ongedaan maken van een voorafgaande vervolgzaakrelatie wanneer beide zaken afgesloten zijn moet alleen gedaan kunnen worden door gebruikers die rechten hebben om afgesloten zaken te kunnen bewerken
•	Alle gedane handelingen moeten terug te zien zijn in de historie van de zaak 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Het leggen van een relatie tussen twee zaken als 'relevante andere zaak' is gerealiseerd via #2204. In deze story is tevens het ongedaan maken van deze relatie gerealiseerd. Het koppelen en ontkoppelen van relevante andere zaken wordt niet in de historie van een zaak vastgelegd.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in een zaak via het tabblad ‘Gerelateerde zaken’ op de regel van de zaak die ontkoppeld moet worden op het Zaak ontkoppelen-icoon klikken

**Comment by CommonGroundGroningen** [comment]
Test OK
