### ISSUE TITLE
10C.1.3.1 gerelateerde (onderwerp) zaakrelatie tussen zaken leggen 

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2204]
**Als**	: Gebruiker
**Wil ik**	: een gerelateerde zaak relatie kunnen leggen tussen twee zaken  
**Zodat ik**	: ik vast kan leggen dat de zaken met elkaar te maken hebben. 

***

### Acceptance criteria:
•	Deze onderlinge relatie mag geen gevolgen hebben voor de individuele bewaartermijnen. 
•	Het moet mogelijk zijn om vanuit het actiemenu bij een zaak een koppeling te maken met een reeds bestaande zaak. 
•	Alle gedane handelingen moeten terug te zien zijn in de historie van de zaak 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze story is het als relevante andere zaak aan elkaar relateren van twee zaken gerealiseerd. Hiervoor zijn meerdere soorten 'relevante andere zaak'-relaties tussen zaken mogelijk. Of een bepaalde relatie gelegd mag worden is afhankelijk van of dit in de zaaktypen is ingesteld. Als dit niet is ingesteld dan biedt de ZAC ook niet de mogelijkheid om deze koppeling te maken.
Het ongedaan maken van de relatie tussen twee zaken is ook gerealiseerd.

De ZAC kent de volgende soorten relaties tussen twee zaken:
• Hoofd- en deelzaak
• Relevante andere zaak
Toelichting op de afhankelijkheid van zaaktypeinrichting:
• om een hoofd-deelzaakrelatie te leggen moet in het zaaktype van de hoofdzaak zijn ingesteld dat deze relatie gelegd mag worden.
• om een relevante andere zaak relatie te leggen moet in het zaaktype van de zaak die je wilt koppelen een zaaktyperelatie gelegd zijn met het zaaktype van de zaak waaraan je deze wilt koppelen.

Een relevante andere zaak wordt gebruikt om een relatie tussen twee zaken duidelijk te maken. Er zijn 3 soorten relevante andere zaken mogelijk:
• Onderwerp: De andere zaak is relevant voor cq. is onderwerp van de onderhanden zaak
• Vervolg: De andere zaak gaf aanleiding tot het starten van de onderhanden zaak
• Bijdrage: Aan het bereiken van de uitkomst van de andere zaak levert de onderhanden zaak een bijdrage
Een andere relevante zaak relatie tussen zaken kan één- of tweezijdig gelegd worden waarbij, afhankelijk van de zaaktype inrichting, in de ZAC de volgende relaties mogelijk zijn om te leggen:
• Onderwerp-onderwerp
• Bijdrage-vervolg
• Vervolg-bijdrage

***Belangrijkste functionaliteiten:***
- Gebruiker kan in een zaak met de [Zaak koppelen] actie een zaak op het klembord plaatsen
- Gebruiker kan in een andere zaak waarmee de relatie gelegd moet worden vanuit het klembord de zaken aan elkaar relateren en de soort relatie tussen de zaken bepalen. De gebruiker heeft, als dit is ingericht, ook de optie om de relatie de andere kant op te leggen en hierbij het soort relatie te bepalen.
- Het relateren van zaken als relevante andere zaak wordt niet in de historie van de zaak vastgelegd
- Gebruiker kan in een zaak via het tabblad ‘Gerelateerde zaken’ de zaken inzien en openen via het oog icoon
- Gebruiker kan in een zaak via het tabblad ‘Gerelateerde zaken’ op de regel van de zaak die ontkoppeld moet worden op het Zaak ontkoppelen-icoon klikken
- Het verwijderen van zaken als relevante andere zaak wordt niet in de historie van de zaak vastgelegd

Middels de koppel functionaliteit kunnen zaaktypen die in Open-Zaak een zaaktyperelatie hebben gekoppeld worden. 
Op de zandbak is een nieuw zaaktype gemaakt, dat Vervolg heet. Deze kan gekoppeld worden met het zaaktype Melding klein Evenement. De relatie kan ook terug gelegd worden door dit als 'Bijdrage' te koppelen. 
Zaaktype 'Melding klein evenement' kunnen met dezelfde zaaktype zaken gekoppeld worden als 'Onderwerp'

**Comment by RoyBuis** [comment]
### Refinement 2-2

**Te realiseren**

- Gebruiker heeft de knop Zaak koppelen
- Afhandelijk van zaaktype inrichting volgen de keuzes voor 'hoofd-deelzaakrelatie' of 'relevante zaak-relatie'
- Bij keuze voor 'relevante' dan heeft gebruiker de keuzes 'vervolg' 'bijdrage' en 'onderwerp'
- Na maken keuze aard kiest de gebruiker of de koppeling 2 kanten op gelegd moet worden en welke relatie dan gelegd moet worden. Belangrijk hierbij is een duidelijke UI waar gebruiker kan zien welke relatie gelegd wordt tussen de 2 zaken, bijvoorbeeld de omschrijvingen laten zien van de zaken die gekoppeld gaan worden. Andere verbetering: 'Koppel deze zaak' wijzigen in 'Koppel de zaak van het klembord aan _zaaknummer_' Toon tussen titel en keuzeveld beide zaaknummers met omschrijvingen.

**Comment by Sevdiya** [comment]
Geeft het onderstaande aan:
Zaak koppelen | ZAAK-2023-0000000041
ZAAK-2023-0000000041
melding klein evenement
ZAAK-2023-0000000100
test issue 1848
Er is geen koppeling mogelijk.

**Comment by CommonGroundGroningen** [comment]
Getest in de zandbak omdat niet alle relaties in de acceptatie zijn ingesteld

**Gebruiker kan in een zaak met de [Zaak koppelen] actie een zaak op het klembord plaatsen**
Test OK
**Gebruiker kan in een andere zaak waarmee de relatie gelegd moet worden vanuit het klembord de zaken aan elkaar relateren en de soort relatie tussen de zaken bepalen. De gebruiker heeft, als dit is ingericht, ook de optie om de relatie de andere kant op te leggen en hierbij het soort relatie te bepalen.**
Volgens mij is dit niet ingericht. Alle mogelijke zaakrelatie combinaties zijn maar op één manier in te stellen.
**Het relateren van zaken als relevante andere zaak wordt niet in de historie van de zaak vastgelegd**
Test OK
**Gebruiker kan in een zaak via het tabblad ‘Gerelateerde zaken’ de zaken inzien en openen via het oog icoon**
Test OK
**Gebruiker kan in een zaak via het tabblad ‘Gerelateerde zaken’ op de regel van de zaak die ontkoppeld moet worden op het Zaak ontkoppelen-icoon klikken**
Test OK
**Het verwijderen van zaken als relevante andere zaak wordt niet in de historie van de zaak vastgelegd**
Test OK
**Middels de koppel functionaliteit kunnen zaaktypen die in Open-Zaak een zaaktyperelatie hebben gekoppeld worden.**
Test OK
**Op de zandbak is een nieuw zaaktype gemaakt, dat Vervolg heet. Deze kan gekoppeld worden met het zaaktype Melding klein Evenement. De relatie kan ook terug gelegd worden door dit als 'Bijdrage' te koppelen.
Zaaktype 'Melding klein evenement' kunnen met dezelfde zaaktype zaken gekoppeld worden als 'Onderwerp'**
Test OK
