### ISSUE TITLE
OLDENZAAL: Beter overzicht van de vorige versies van een document

### ISSUE THREAD

**Issue by VincentHofman** [NL-AMS-LOCGOV/zaakafhandelcomponent#2209]
**Gemeentenaam**: Oldenzaal

**Feature verzoek**: vorige versies van een document kun je op een documentpagina raadplegen door te klikken op "<" ">". Deze handeling is niet duidelijk en niet gebruiksvriendelijk.  Een apart tabblad zoals in eSuite is duidelijker.

**Waarom zou je deze feature graag in de applicatie willen?**
Maakt het lezen van documenthistory natuurlijker en eenvoudiger

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Wordt later via koplopergroep Zaak nogmaals getoetst, Issue wordt gesloten.
