### ISSUE TITLE
Metadata bewerken zonder document te openen

### ISSUE THREAD

**Issue by VincentHofman** [NL-AMS-LOCGOV/zaakafhandelcomponent#2211]
**Gemeentenaam**: Oldenzaal

**Feature verzoek**:
Ik wil de meta-data op een documentpagina kunnen bewerken. Zonder het document te hoeven openen. Als het document niet definitief is, dan wil ik dit als behandelaar kunnen. Anders apart recht.

**Waarom zou je deze feature graag in de applicatie willen?**

**Comment by RoyBuis** [comment]
### Refinement SN, KM, RV & RB

@VincentHofman, een document wijzigen betekent in de Documenten API altijd een nieuwe versie. Er is nu een scherm gemaakt waarin je metadata kunt aanpassen en waarmee je dus ook meerdere metadata kunt aanpassen waarbij dan één keer een nieuwe versie wordt gemaakt.
Wat is precies de gewenste aanpassing die je hier beschrijft?

**Comment by EvelineSprangers-Oldenzaal** [comment]
Ah. Functioneel werkt dit inderdaad en ik had even gemist dat je dan niet letterlijk een nieuw document hoeft te uploaden. Het is echter niet intuïtief om te klikken op nieuw document wanneer je de metadata wil aanpassen. Ik heb echter geen suggesties over hoe dit intuïtiever zou kunnen.

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Dit wordt via koplopergroep Zaak opnieuw beoordeeld, issue wordt gesloten.
