### ISSUE TITLE
OLDENZAAL: Zaken bij persoonsgegevens

### ISSUE THREAD

**Issue by VincentHofman** [NL-AMS-LOCGOV/zaakafhandelcomponent#2212]
**Gemeentenaam**: Oldenzaal

**Feature verzoek**:Ik wil als zaakbehandelaar de kolommen die ik zie bij 'zaken' in Persoonsgegevens kunnen aanpassen met groep en behandelaar

**Waarom zou je deze feature graag in de applicatie willen?**

** Gerealiseerd**
Op een persoons of bedrijfsgegevenspagina zijn er 2 kolommen bijgekomen; Groep en Behandelaar. Hierop kan de gebruiker filteren en sorteren. Alleen de groepen/behandelaren worden getoond die betrokken zijn bij een bedrijf/persoon

**Comment by RoyBuis** [comment]
### Refinement SN, KM, RV & RB
@VincentHofman Wij interpreteren deze als het toevoegen van kolommen om de groep en behandelaar bij de zaken te kunnen zien. Klopt dit?

**Comment by EvelineSprangers-Oldenzaal** [comment]
Correct.

**Comment by RoyBuis** [comment]
### Refinement 14-2

- Kolommen 'Groep' en 'Behandelaar' toevoegen aan zakenoverzicht op persoons-  en bedrijfspagina
- Filter en sorteeropties op beide kolommen

**Comment by Renvooi** [comment]
Gewenste kolomkoppen zijn aanwezig cq kunnen worden toegevoegd/verwijderd en op deze kolomkoppen zit een filter. Filter werkt ook correct.
