### ISSUE TITLE
OLDENZAAL: Aantal items per pagina instelling vasthouden

### ISSUE THREAD

**Issue by VincentHofman** [NL-AMS-LOCGOV/zaakafhandelcomponent#2215]
**Gemeentenaam**: Oldenzaal

**Feature verzoek**:
Ik wil als zaakbehandelaar dat het ZAC mijn instellingen voor aantal items per pagina in bijv. werkvoorraadlijsten vasthoud wanneer ik de browser sluit
**Waarom zou je deze feature graag in de applicatie willen?**

2215
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Deze story is een aanpassing in de werking van de werklijst instellingen. Het aantal items dat per pagina getoond wordt is door de gebruiker in te stellen. Dit kan per werklijst gedaan worden en deze instellingen blijven nu na het sluiten van de browsersessie bewaard.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in alle werklijsten het aantal items dat per pagina getoond wordt instellen. Deze instellingen blijven bewaard voor de gebruiker.

**Comment by RoyBuis** [comment]
### Refinement 31-1

Dit soort aanpassingen kunnen impact op de performance in productie hebben. Goed afwegen wat de waarde van dit soort toevoegingen is. Voor deze story wordt de functionaliteit uitgebreid door de gewenste aantallen in ene database op te slaan. 

**Te realiseren**

- Voor een gebruiker per werklijst persisteren hoeveel items per pagina
- Geldt voor alle werklijsten, iedere werklijsten krijgt een eigen standaard

**Comment by HilbrandHurtak** [comment]
Getest op de werklijsten voor zaken, taken en documenten. Daar werkt het. Ook getest op het "generiek zoeken" venster. Daar is het, conform de refinement niet doorgevoerd. Dit lijkt mij, gezien de eventuele performance risico's, ook niet wenselijk. 

Test OK
