### ISSUE TITLE
OLDENZAAL: Procesgegevens

### ISSUE THREAD

**Issue by VincentHofman** [NL-AMS-LOCGOV/zaakafhandelcomponent#2217]
**Gemeentenaam**: Oldenzaal

**Feature verzoek**:Ik wil als functioneel beheerder procesgegevens van een zaak kunnen inzien. Als er iets mis gaat in een zaak, kan deze nodig zijn de juiste gegevens weer naar boven te halen. Ook is het handig voor data-analyse met BI-tools, snel zien welk veld je moet hebben.

**Waarom zou je deze feature graag in de applicatie willen?**

**Comment by Snijhuis** [comment]
@VincentHofman - even een reactie in 3 delen:

- Op dit moment kunnen processen niet gemodelleerd worden in ZAC.
Voor het inzien van de ingevulde waarden op taken kun je klikken op de afgehandelde taken. 
- We gaan nog een tab maken om de formulier-gegevens (van OpenForms) te tonen bij de zaak. Puur ter inzage.
- Daarnaast moeten nog met Rapportages aan de slag. We willen de zaakdata uit OpenZaak kunnen halen en de procesdata uit ZAC.
- Er moet een begrijpelijk foutlogging komen voor ZAC (en later podiumD breed)

Met die 4 functionaliteiten, blijft bovenstaande feature dan nog nodig?

**Comment by EvelineSprangers-Oldenzaal** [comment]
Prima voorstel, de feature is niet meer nodig

**Comment by KarinMasselink** [comment]
Afgesloten op basis van het antwoord van Oldenzaal (vraagsteller).
