### ISSUE TITLE
KAMPEN: BUG - bij afsluiten van een zaak

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#2218]
**Gemeentenaam**: Kampen

Ik krijg de volgende bug bij het afsluiten van zaak: ZAAK-2022-0000000263

Fout
(400) Title: Invalid input., Detail: Name: nonFieldErrors, Code: indicatiegebruiksrecht-unset, Reason: Er zijn gerelateerde informatieobjecten waarvoor `indicatieGebruiksrecht` nog niet gespecifieerd is. Je moet deze zetten voor je de zaak kan afsluiten.

**Comment by Snijhuis** [comment]
@IreneYolande Waarschijnlijk komt dit omdat het een oudere zaak is. Er wordt natuurlijk elke 2 weken nog doorontwikkeld. Zou je dit kunnen reproduceren met een nieuw geregistreerde zaak van hetzelfde zaaktype?

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Niet meer actueel, issue wordt gesloten.
