### ISSUE TITLE
KAMPEN: maximale bestandsgrootte

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#2219]
**Gemeentenaam**: Kampen

**Feature verzoek**: Is het mogelijk om de maximale bestandsgrootte in de toekomst aan te laten passen?

**Waarom zou je deze feature graag in de applicatie willen?**
80 MB is voor nu voldoende, maar lastig om te bepalen of dat in de toekomst ook voldoende blijft. Voornamelijk voor (grote) videobestanden is 80 MB niet voldoende.

**Comment by IreneYolande** [comment]
zie ook : 7.10.2 Configuratie bestandsgrootte documenten door beheerder #355

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Niet meer relevant, issue wordt gesloten.
