### ISSUE TITLE
Kampen: vraag over Metagegevens voor duurzaam toegankelijke overheidsinformatie (MDTO)

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#2222]
**Gemeentenaam**: Kampen

Voldoet het ZAC aan Metagegevens voor duurzaam toegankelijke overheidsinformatie (MDTO)? Zijn alle uit de MDTO verplichte metadatavelden aanwezig bij de zaak en het document?

**Comment by IreneYolande** [comment]
Dit is een must, want verplicht vanuit de Archiefwet/regeling.

**Comment by RikVedder** [comment]
Hiervoor is vanuit WG IB een fit gap gedaan gebaseerd op MDTO standaard zoals deze in Groningen is vastgesteld
[https://app.zenhub.com/files/416646145/bc7c1d7d-448c-4ab4-b42c-239ce15b94ee/download](https://app.zenhub.com/files/416646145/bc7c1d7d-448c-4ab4-b42c-239ce15b94ee/download)

[https://app.zenhub.com/files/416646145/732b2a7c-5362-409e-8e0f-baec687587d5/download](https://app.zenhub.com/files/416646145/732b2a7c-5362-409e-8e0f-baec687587d5/download)

[https://app.zenhub.com/files/416646145/01fad480-15d4-4a4b-ad1e-bf64f6b1ee80/download](https://app.zenhub.com/files/416646145/01fad480-15d4-4a4b-ad1e-bf64f6b1ee80/download)

[https://app.zenhub.com/files/416646145/d0f61008-fbe6-4014-a8b9-eb980fbfd43c/download](https://app.zenhub.com/files/416646145/d0f61008-fbe6-4014-a8b9-eb980fbfd43c/download)

Als hier verder vragen of opmerkingen over zijn neem dan gerust contact met mij of de werkgroep informatiebeer op via SAM

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Deze hoort op de backlog van PodiumD. Issue wordt gesloten.
