### ISSUE TITLE
Kampen: Het kunnen opstellen van overzichten van alle zaken en documenten

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#2223]
**Gemeentenaam**: Kampen

**Feature verzoek**: Een overzicht op kunnen stellen waarbij alle zaken en documenten  worden meegenomen. Ik wil compleet vrij zijn in welke metadata ik meeneem in dat overzicht en welke niet. 

**Waarom zou je deze feature graag in de applicatie willen?**
Ik kan nu alleen overzichten opstellen van mijn openstaande zaken of van door mij afgehandelde zaken of alle openstaande zaken. Als informatiebeheerder zou ik graag overzichten willen opstellen van alle aanwezige zaken, los van de status en/of behandelaar. 

Voor documenten precies hetzelfde verzoek; m.n. als Locatie (zie issue #2221) ook is toegevoegd als metadataveld in het document. Ik wil als informatiebeheerder specificaties van documenten uit kunnen draaien op basis van bepaalde filters. Laat mij filteren op elk metadataveld.

**Comment by IreneYolande** [comment]
Zie ook MVP: Werklijsten specifiek voor archiveren- filteren, sorteren en zoeken

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

WG Refinement heeft aangegeven dit soort export functionaliteit niet in de ZAC hoort, wellicht is dit via rapportage component te realiseren. Issue wordt gesloten.
