### ISSUE TITLE
Werklijsten Zaken / Taken, extra kollommen (optioneel) om toe te voegen. En Initiator als standaard kolom.

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#2228]
***Als*** 
Behandelaar

***Wil ik*** 
Extra kolommen van al de zaakregistratie velden kunnen toevoegen aan de Werklijsten Zaken. (Zaken-Werkvoorraad / Mijn zaken / Afgehandelde zaken)
Taken-werkvoorraad / Mijn taken: Initiator van de zaak als kolom toe voegen. (Standaard getoond)

***Zodat*** 
Ik ook deze velden kan zien in de werkvoorraad, nadat ik ze toevoeg.
Velden Communicatiekanaal / Vertrouwelijkheidaanduiding  / Registratiedatum. (om zelf toe te voegen)
En Initiator (Aanvrager) als Standaard kolom in de werklijsten.
***

### Acceptance criteria:
In ieder geval "Communicatiekanaal" te kiezen en te filteren op 1 van de kanalen. En te sorteren (A-Z).
En zoeken / sorteren van de kolom Initiator.

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves (Initiator)
- Should haves (rest)

***
### Gerealiseerd
Extra kolom standaard met Initiator (bij Zaken en Taken)
Optioneel om toe te voegen de andere velden van Zaakregistratie.

***Belangrijkste functionaliteiten:***
Werklijsten met volledig informatie.

**Comment by VictorTielenius** [comment]
Bij Werklijst Afgehandelde zaken zouden de kollommen vernietigingsdatum / bewaartermijn er nog bij moeten

**Comment by Snijhuis** [comment]
We kunnen deze story niet volledig oppakken @VictorTielenius

**Wat kan wel:**
Bij openstaande zaken werklijsten:
Velden Communicatiekanaal / Vertrouwelijkheidaanduiding / Registratiedatum. (om zelf toe te voegen, niet standaard tonen)

Bij de afgehandelde zaken werklijst:
vernietigingsdatum / bewaartermijn (om zelf toe te voegen, niet standaard tonen)

**Wat kan niet:**
Initiator (Aanvrager) als Standaard kolom in de werklijsten.

Dit komt omdat wij persoonsgegevens niet opslaan in het ZAC. We halen persoonsgegevens bij de bron op dus in werklijsten (waar meerdere zaken staan) hebben we alleen de sleutel van de initiator ter beschikking (BSN, KVK, Vestigingsnummer, RSIN). 
We komen ook in de knel met doelbinding als we allerlei gegevens tonen in werklijsten en bronnen bevragen vanuit werklijsten.

Daarnaast zijn werklijsten niet bedoelt om specifieke zaken te kunnen terugvinden. Het betreft werkvoorraad voor een groep/medewerker die je met allerlei filters/sorteringen kan personaliseren. Het is geen zoekscherm.


**Wat kan wel rondom de initiator:**
- tonen van sleutel indien de ingelogde die mag zien bij die zaaktypen (BSN, KVK, Vestigingsnummer, RSIN) Zie ik de toegevoegde waarde niet van in, kortom: duidelijke "zodat" nodig.
- tonen van type initiator (bijvoorbeeld: bedrijf of persoon). Lijkt mij handig

_NB. Uitgangspunt voor zoeken van zaken op personen/bedrijven_
Als je een zaak zoekt van een persoon/bedrijf, dan is de ingang niet de werklijsten, maar de zoekfunctie. Je moet dan namelijk eerst de specifieke persoon /bedrijf zoeken om daarna te zien welke zaken er lopen op die persoon/dat bedrijf.

Daarnaast is voor zaakgericht werken het zaaknummer leidend. Zoek je een zaak, gebruik het zaaknummer.

**Comment by Snijhuis** [comment]
Voorstel. We pakken deze vast op

- Bij openstaande zaken werklijsten: Velden Communicatiekanaal / Vertrouwelijkheidaanduiding / Registratiedatum. (om zelf toe te voegen, niet standaard tonen)

- Bij de afgehandelde zaken werklijst: vernietigingsdatum / bewaartermijn (om zelf toe te voegen, niet standaard tonen)

Later oppakken in andere story, eerst bespreken met WG R&A

- Alles rondom initiator

**Comment by RoyBuis** [comment]
### Refinement 14-2

**Te realiseren**

- In werkvooraad-zaken en Mijn zaken kolommen toevoegen voor Communicatiekanaal, Vertr Aanduiding en Registratiedatum. Standaard staan kolommen niet in overzicht.
- Inclusief filter- en sorteeropties
- In Afgehandelde zaken kolommen toevoegen met Archiefnominatie en Archiefactiedatum (dat kan vernietigdatum of overbrengingsdatum zijn). Letop: velden staan nog niet in Solr
- Inclusief filter- en sorteeropties

**Comment by EvelineSprangers-Oldenzaal** [comment]
Om mee te nemen naar WG R&A en story rondom initiator:
' Daarnaast zijn werklijsten niet bedoelt om specifieke zaken te kunnen terugvinden. Het betreft werkvoorraad voor een groep/medewerker die je met allerlei filters/sorteringen kan personaliseren. Het is geen zoekscherm.'  

Bij gemeente Oldenzaal wordt dit wel zo gebruikt. Wij gebruiken de werkvoorraad juist wel om snel je zaak te zoeken. Initiator is daarvoor wel van belang. We hebben de vraag breder uitgezet dan onze testgroep, de groep key users van huidige e-Suite waren het hier allemaal over eens. De werklijst wordt gebruikt als ingang om zaken snel op te zoeken. De sleutel is inderdaad niet voldoende, een persoon wordt niet herkend aan BSN, bedrijf niet aan KvKnummer.

**Comment by robertverboom** [comment]
Indicaties ook toevoegen op afgehandelde zaken werkvoorraad

**Comment by KarinMasselink** [comment]
**WG Refinement 8-3**

Rondom initiator:
Nogmaals besproken dat er beperkingen (AVG/Performance) zitten aan het standaard tonen van het initiator. De wens en behoefte blijft bestaan en is duidelijk. 

Voor nu betekend dit dat we dit niet gaan oppakken. Wel besloten om issue #2214  waar deze expliciete wens voor initiator al benoemt stond opnieuw te openen en deze te verslepen naar 'Todo later'

**Comment by VictorTielenius** [comment]
In werkvooraad-zaken en Mijn zaken kolommen toevoegen voor Communicatiekanaal, Vertr Aanduiding en Registratiedatum. Standaard staan kolommen niet in overzicht. OK
Inclusief filter- en sorteeropties: OK
In Afgehandelde zaken kolommen toevoegen met Archiefnominatie en Archiefactiedatum (dat kan vernietigdatum of overbrengingsdatum zijn). : OK
Letop: velden staan nog niet in Solr
Inclusief filter- en sorteeropties: OK
Indicaties ook toevoegen op afgehandelde zaken werkvoorraad: OK
