### ISSUE TITLE
KISS instaleren op cluster

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#2233]
https://github.com/Klantinteractie-Servicesysteem/

**Comment by RoyBuis** [comment]
### Refinement 16-2

Uitvoeren van dit issue is geannuleerd vanwege aanpassingen in de backend van KISS. Gebruik van KISS is nu niet nodig.

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Niet meer actueel, issue wordt gesloten.
