### ISSUE TITLE
BUG: Werklijsten zaken tonen onvolledig overzicht

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2237]
Speelt in zandbak omgeving

***Steps to reproduce:***

1. Open Zandbak omgeving
2. Open Werkvoorraad-zaken
3. 

***Expected***
Alle openstaande zaken waar gebruiker recht op heeft worden getoond  

***Actual***
Alleen recente zaken worden getoond

**Comment by ronniekoopmans-atos** [comment]
Het lijkt erop, dat het her-indexeren een transactie timeout geeft. misschien is het beter om het indexeren in een batch api, of via een helper op te splitsen in kleinere transacties, zodat het proces doorloopt bij grotere aantallen. zal hiervoor een ticket aanmaken, deze eraan linken en sluiten.
