### ISSUE TITLE
BUG: websockets suspenden op zaak tonen bij wijzigen behandelaar en groep, en toevoegen taak en document

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#224]
***Steps to reproduce:***

1. Ga naar een zaak en wijzig behandelaar of groep.
2. Voeg een taak toe

***Expected***
Je krijgt geen 'snackbar' op je eigen scherm te zien

***Actual***
Er komen snackbar meldingen als: msg.gewijzigd.objecttype.ZAAK_TAKEN is zojuist door iemand gewijzigd.

**Comment by robertverboom** [comment]
Let op; bij wijzigen van behandelaar en groep verschijnen er meerdere snackbars 'snel' achter elkaar. Alleen de laatste moet zichtbaar zijn.

**Comment by robertverboom** [comment]
Wanneer je in taakgegevens de behandelaar wijzigt krijg je de melding: 'Deze taak is zojuist door iemand gewijzigd.   Verversen  '
Dit is niet juist gezien jijzelf de taak wijzigt.  
Expected: 
De taak is toegekend aan 'naamBehandelaar'  Sluiten

**Comment by edwinlambregts-atos** [comment]
Even overlegd met Robert.
Bij de Zaak zelf werken de knoppen Ken toe aan jezelf en Vrijgeven ook niet helemaal lekker.
