### ISSUE TITLE
Gebruik e-mail adressen: e-mail adres groep en e-mailadres zaakbehandelaar niet aanbieden

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2240]
***Als*** Beheerder

***Wil ik*** bij de inrichting van mogelijke e-mailadressen als afzender/reply **niet** de mogelijkheid hebben om de e-mail van de groep of zaakbehandelaar te gebruiken. (Je mag namelijk niet mailen vanuit een andere gebruiker en de groeps-email adres is vaak een intern e-mail adres)

***Zodat*** ik alleen de keuze heb bij de inrichting van ZAP  om de e-mail van de ingelogde gebruikers, het standaard e-mail adres van een gemeente en eventueel eigen aangemaakte e-mailadressen te gebruiken en setten als default.

Story n.a.v. opmerkingen gister tijdens sprintreview over ticket #2096  (08-02)

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #2096 is het kunnen kiezen van een afzender mailadres bij het versturen van e-mails opgeleverd. In deze story is deze functionaliteit aangepast door de keuzes voor de groep of zaakbehandelaar als mailafzender te kiezen niet mogelijk te maken.

***Belangrijkste functionaliteiten:***
- Gebruiker kan bij het kiezen van een mailafzender alleen kiezen voor het eigen e-mailadres, het e-mailadres van de gemeente of een extra toegevoegde mailafzender

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
In Zaak E-mail versturen: OK (jezelf + gemeentemailadres te kiezen bij Afzender)
