### ISSUE TITLE
Bestandsgrootte toevoegen in documentencomponent 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2241]
Als behandelaar 
Wil ik de bestandsgrootte van de documenten in 1 oogopslag kunnen zien
Zodat ik weet hoe groot de documenten zijn die aan een zaak gekoppeld zijn. 
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze story is de UI in het documentenoverzicht bij een zaak en het documentenoverzicht bij het verzenden van een mail aangepast door van de documenten de bestandsomvang te tonen. De omvang wordt tot 1 MB in kB weergegeven en daarna in MB.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in overzichten van documenten zien hoe groot de bestanden zijn

**Comment by RoyBuis** [comment]
### Refinement 14-2

- Bestandsgrootte tonen op documentgegevenspagina
- Kolom met Bestandsgrootte toevoegen aan documentcomponent, tussen Documenttype en Status plaatsen
- Kolom Creatiedatum weghalen om ruimte te maken. Deze datum is ook te zien in de kolom Registratietijdstip

**Comment by robertverboom** [comment]
test ok

**Comment by CommonGroundGroningen** [comment]
De 3 refinement punten getest.
Alles OK
