### ISSUE TITLE
10C.3.1.1 Zaak – BAG-object relatie leggen bij aanmaken zaak

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2244]
Als	: registrator
Wil ik	: een BAG-object van het juiste type kunnen zoeken, selecteren en van daar uit een zaak kunnen aanmaken
Zodat ik	: kan vastleggen dat een zaak is gerelateerd aan een specifiek BAG-object

***

### Acceptance criteria:
Acceptatiecriteria	:
•	De gemaakte en koppeling moet terug te zien zijn in de historie van de zaak
•	In de werklijst moet bij zaak een indicatie te zien zijn dat er een BAG-object gekoppeld is (hoeft niet te zien te zijn welk BAG-object het is)
•	De BAG-objecten komen uit de landelijke voorziening
•	10C.3.1.6 moet zijn uitgevoerd

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Het toevoegen van een BAG-object aan een zaak is uitgebreid door het direct mogelijk te maken bij het aanmaken van een nieuwe zaak. Het zoeken naar BAG-objecten is identiek aan het zoeken vanuit een bestaande zaak en kan gedaan worden op (een combinatie van) straatnaam, postcode, huisnummer en woonplaats. Ook het toevoegen van een BAG-object gebeurt net als bij een bestaande zaak. De geselecteerde objecten kunnen eventueel in het 'Zaak aanmaken' scherm weer verwijderd worden.

***Belangrijkste functionaliteiten:***
- Gebruiker in het 'Zaak aanmaken' scherm BAG-objecten zoeken op (een combinatie van) straatnaam, postcode, huisnummer en woonplaats. De trefwoorden kunnen gescheiden door een spatie worden ingevuld.
- Gebruiker voegt een gevonden adres aan de zaak toe door in de lijst van zoekresultaten op het huis icoon te klikken. Om een ander BAG-object bij het adres te selecteren kan het adres worden uitgeklapt door op het pijltje te klikken en vervolgens het gewenste BAG-object via het huis icoon toe te voegen.
- Gebruiker kan de toegevoegde BAG-objecten verwijderen door op het kruisje in het 'BAG objecten' veld te klikken
- Toegevoegde BAG-objecten zijn na het aanmaken van de zaak zichtbaar in de tab 'BAG-objecten'

**Comment by CommonGroundGroningen** [comment]
•De gemaakte en koppeling moet terug te zien zijn in de historie van de zaak
•In de werklijst moet bij zaak een indicatie te zien zijn dat er een BAG-object gekoppeld is, bagid en type (optioneel ingangsdatum)
•Mogelijkheid om meerdere bagobjecten en bloc te relateren aan een zaak, b.v. een flatgebouw (pand) en meerdere appartementen (vbo's)

**Comment by robertverboom** [comment]
Test ok

**Comment by CommonGroundGroningen** [comment]
vraag: voor de bag-identificatie vbo wordt nu de benaming vbo gebruikt. Als ligplaats en standplaats worden toegevoegd wordt dan ook de identificatie adres gebruikt. Om verwarring te voorkomten is het beter om de bag identificaties te hanteren en dat zijn vbo, ligplaats en standplaats. Aan het bagnummer kun je wel herleiden dat het om vbo gaat (lees adres).

**Comment by CommonGroundGroningen** [comment]
Gebruiker in het 'Zaak aanmaken' scherm BAG-objecten zoeken op (een combinatie van) straatnaam, postcode, huisnummer en woonplaats. De trefwoorden kunnen gescheiden door een spatie worden ingevuld.
**Akkoord**
Gebruiker voegt een gevonden adres aan de zaak toe door in de lijst van zoekresultaten op het huis icoon te klikken. Om een ander BAG-object bij het adres te selecteren kan het adres worden uitgeklapt door op het pijltje te klikken en vervolgens het gewenste BAG-object via het huis icoon toe te voegen.
**Akkoord**
Gebruiker kan de toegevoegde BAG-objecten verwijderen door op het kruisje in het 'BAG objecten' veld te klikken
Akkoord, Maar is x vervangen door prullenbak?
Toegevoegde BAG-objecten zijn na het aanmaken van de zaak zichtbaar in de tab 'BAG-objecten'
**Akkoord**

**Comment by CommonGroundGroningen** [comment]
GETEST IN DE ZANDBAK, OMDAT ACCEPTATIE HET NIET DOET, DEZE TEST NOG HERHALEN IN ACCEPTATIE

**Comment by HilbrandHurtak** [comment]
Hertest op ACC uitgevoerd en AKKOORD

Opmerking t.a.v: Gebruiker kan de toegevoegde BAG-objecten verwijderen door op het kruisje in het 'BAG objecten' veld te klikken Akkoord, Maar is x vervangen door prullenbak?
**Reactie werkgroep R&A:**  de werking van X verschilt ten aanzien van overige schermen. Daar is het (bijvoorbeeld bij toevoegen documenten) het cancelen van de actie. Voor BAG is dat anders. De gegevens worden doorgevoerd ook al gebruik je het kruisje. **Victor gaat dit namens de koplopersgroep testen. Als het onduidelijk blijft komt er een nieuwe user story**
>
