### ISSUE TITLE
10C.3.1.2 Zaak – BAG-object relatie leggen wanneer zaak bestaat

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2245]
Als	: registrator/behandelaar
Wil ik	: vanuit een zaak een BAG-object van het juiste type kunnen zoeken, selecteren en koppelen
Zodat ik	: kan vastleggen dat een zaak is gerelateerd aan een specifiek BAG-object

***

### Acceptance criteria:
•	De gemaakte en koppeling moet terug te zien zijn in de historie van de zaak
•	In de werklijst moet bij zaak een indicatie te zien zijn dat er een BAG-object gekoppeld is (hoeft niet te zien te zijn welk BAG-object het is)
•	De BAG-objecten komen uit de landelijke voorziening
•	10C.3.1.6 moet zijn uitgevoerd

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Deze story is gerealiseerd via #2413

**Comment by CommonGroundGroningen** [comment]
• De gemaakte en koppeling moet terug te zien zijn in de historie van de zaak
• In de werklijst moet bij zaak een indicatie te zien zijn dat er een BAG-object gekoppeld is en de volgende velden willen wij 
  dan graag zien, bagid, type (optioneel: ingangsdatum)

**Comment by CommonGroundGroningen** [comment]
• De gemaakte en koppeling moet terug te zien zijn in de historie van de zaak
**Akkoord**
• In de werklijst moet bij zaak een indicatie te zien zijn dat er een BAG-object gekoppeld is en de volgende velden willen wij
dan graag zien, bagid, type (optioneel: ingangsdatum)
**Akkoord**
•Mogelijkheid om meerdere bagobjecten en bloc te relateren aan een zaak, b.v. een flatgebouw (pand) en meerdere appartementen (vbo's)
**Akkoord**
