### ISSUE TITLE
10C.3.1.3 BAG-object-object relatie ongedaan maken

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2246]
Als	: behandelaar
Wil ik	: een gekoppeld BAG-object dat aan een zaak is gerelateerd kunnen ontkoppelen
Zodat ik	: geen onjuiste relatie heb

***

### Acceptance criteria:
•	Handeling moet worden vastgelegd in de historie van de zaak

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een bij een zaak toegevoegd BAG-object kan verwijderd worden. Hiervoor moet een reden worden opgegeven maar deze is nog niet in de historie terug te vinden omdat er nog regel voor het verwijderen wordt aangemaakt.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het tabblad 'BAG-objecten' een object verwijderen door op het prullenbak icoon te klikken. Hierbij moet een reden voor het verwijderen worden opgegeven.
- Het verwijderen van een BAG-object wordt niet vastgelegd in de historie van de zaak

**Comment by CommonGroundGroningen** [comment]
Is er dan nog verschil in deze userstory tussen ontkoppelen en verwijderen

**Comment by RoyBuis** [comment]
### Refinement 4-4

**Te realiseren**
Consistent maken aan verwijderen van betrokkenen
- toegevoegde BAG-objecten kunnen één voor één vanuit de tab met prullenbak verwijderd worden
- verplicht een reden invullen, deze wordt gebruikt als toelichting bij historie

**Comment by ronniekoopmans-atos** [comment]
Ik ga de call voor het verwijderen van een zaakobject implementeren, maar Open-Zaak 1.7.5 maakt gebruik van  zgw-api zaken versie 1.1.2. 
Delete is geïmplementeerd in zgw-api zaken versie 1.2.0.
open-zaak vanaf versie 1.8.0 implementeert de deze versie

**Comment by ronniekoopmans-atos** [comment]
Het verwijderen van een zaak-object is niet terug te zien in de historie, open-zaak maakt hier geen record voor aan, dit is een bug in open-zaak

**Comment by CommonGroundGroningen** [comment]
Gebruiker kan in het tabblad 'BAG-objecten' een object verwijderen door op het prullenbak icoon te klikken. Hierbij moet een reden voor het verwijderen worden opgegeven.
**Akkoord**
Het verwijderen van een BAG-object wordt niet vastgelegd in de historie van de zaak
**Akkoord**
