### ISSUE TITLE
10C3.1.6 Zoeken BAG-objecten

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2249]
Als	: registrator/behandelaar
Wil ik	: bij ‘trefwoorden’ kunnen zoeken naar BAG-objecten 
Zodat ik	: de juiste kan vinden

***

### Acceptance criteria:
•	Bij de zoekresultaten moet een extra verfijning naar ‘type’ gemaakt kunnen worden

***
### Prioriteit
- Must haves
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Het toevoegen van een BAG-object aan een zaak is uitgebreid door het mogelijk te maken om meerdere soorten BAG-objecten toe te voegen. Ook het zoeken naar BAG-objecten in de LV BAG met de Individuele bevragingen API is verbeterd. Er kan nu naar adressen gezocht worden op (een combinatie van) straatnaam, postcode, huisnummer en woonplaats. De gevonden adressen worden in de zoekresultaten getoond, deze kunnen vervolgens worden uitgeklapt om de bijbehorende BAG-objecten te zien. De typen BAG-objecten die getoond worden zijn nummeraanduiding, openbare ruimte, woonplaats en pand.
Een adres en alle gevonden BAG-objecten kunnen aan de zaak toegevoegd worden. Na het toevoegen zijn deze alleen als apart zaakobject aan de zaak toegevoegd en onder het tabblad 'BAG-objecten' in te zien.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het menu met de actie [BAG object toevoegen] het zoekscherm openen
- BAG-objecten kunnen gezocht worden op (een combinatie van) straatnaam, postcode, huisnummer en woonplaats. De trefwoorden kunnen gescheiden door een spatie worden ingevuld.
- Gebruiker voegt een gevonden adres aan de zaak toe door in de lijst van zoekresultaten op het huis icoon te klikken. Om een ander BAG-object bij het adres te selecteren kan het adres worden uitgeklapt door op het pijltje te klikken en vervolgens het gewenste BAG-object via het huis icoon toe te voegen. Geselecteerde BAG-objecten worden direct aan de zaak toegevoegd.
- Gebruiker kan de toegevoegde BAG-objecten bekijken via het tabblad 'BAG objecten' op de zaakgegevenspagina
- Het toevoegen van een BAG-object wordt met het id van het BAG-object als wijziging van een object met vermelding van het type (bijvoorbeeld 'pand') vastgelegd in de historie van de zaak

**Comment by RoyBuis** [comment]
### Refinement 22-2 RV, SN & RB

Dit wordt de story die als eerste wordt opgepakt waarbij we focussen op het zoeken van BAG objecten vanuit 'BAG object toevoegen' actie vanuit de zaak. Spike plannen om de volgende punten uit te zoeken:
- Wat, i.e. welke typen BAG gegevens, kan de huidige API (Individuele bevragingen ) https://www.kadaster.nl/zakelijk/producten/adressen-en-gebouwen/bag-api-individuele-bevragingen
- Uitzoeken of de API kan wat er functioneel gewenst is:
  - met trefwoorden alle relevante BAG objecten vinden en daarna filteren op type
  - eerst type kiezen en dan gericht zoeken

**Comment by robertverboom** [comment]
Refinement 23-02:

- Bij het bekijken naar de API is er uitgekomen dat je alleen per type kan zoeken. 
- Per type moet je zoekcriteria meegeven. 

@Snijhuis pakt dit met de WG R&A op

**Comment by Snijhuis** [comment]
@WG Refinement

Per bag-object type zijn er zoekcriteria. Het is niet mogelijk om 1 zoekingang te maken voor alle typen als we gebruik maken van LV BAG. Direct alles implementeren kost erg veel tijd, daarom willen we beginnen met de belangrijkste typen.

Op dit moment is adres geïmplementeerd. Dat is een samengesteld Bag-object bestaande uit Huisnummeraanduiding, Woonplaats en Openbare ruimte (straat). Je kunt de adressen zoeken door huisnummer en postcode combinatie te gebruiken. 
Zie 'Bag object toevoegen' bij een zaak 

Verzoek is dus om even binnen je eigen gemeente te kijken naar praktijkvoorbeelden:  Welke Bag-object typen worden in de praktijk vaak gezocht en gekoppeld?
Reageren mag in dit issue. Alvast dank!

**Comment by GertrudeKampherbeek** [comment]
Voor Emmen geldt dat de meest gebruikte BAG-objecten zijn:

- nummeraanduiding
- openbare ruimte
- verblijfsobject

**Comment by CommonGroundGroningen** [comment]
Zoekingangen:
Zoeken mbv id’s (iedere type heeft een eigen id):

•	openbare ruimte (OPR) 
•	nummeraanduiding (NUM)
•	pand (PND)
•	ligplaats (LIG)
•	standplaats (STA)
•	verblijfsobject (VBO)

b.v hamburgerstraat 7
Openbare ruimte: 0014300010785160
Pand: 001400010911494
vbo: 0014010011055731
nummeraanduiding: 0014200010862919
In het voorbeeld is het adresseerbaar object een vbo, maar dat kan dus ook een lig- of een standplaats zijn.

Zoeken op type:
•	verblijfsobject (VBO)
•	ligplaats (LIG)
•	standplaats (STA)
•	woonplaats (WPL)
•	openbare ruimte (OPR) 
•	nummeraanduiding (NUM) (aparte zoekingang)
•	pand (PND)

Zoeken op adres:
•	Nummeraanduiding (id)
•	Postcode en huisnummer, huisnummerletter en -toevoeging
•	Woonplaatsnaam, openbare ruimte, huisnummer,  huisnummerletter en -toevoeging

**Comment by Snijhuis** [comment]
Qua volgorde:
1. Verblijfsobject
2. Pand
3. Nummeraanduiding
4. Openbare ruimte

We hebben nu al adres, dat is een samengestelde van Openbare ruimte + Huisnummer + Woonplaats. Hoe zit dat als je kijkt naar bovenstaande?

**Comment by robertverboom** [comment]
Test ok

**Comment by CommonGroundGroningen** [comment]
Deze moet nog verder uitgewerkt worden, wachten met testen

**Comment by CommonGroundGroningen** [comment]
Functionaliteiten gerealiseerd getest op de acceptatieomgeving:

Gebruiker kan in het menu met de actie [BAG object toevoegen] het zoekscherm openen
**Akkoord**
BAG-objecten kunnen gezocht worden op (een combinatie van) straatnaam, postcode, huisnummer en woonplaats. De trefwoorden kunnen gescheiden door een spatie worden ingevuld.
**Akkoord**
Gebruiker voegt een gevonden adres aan de zaak toe door in de lijst van zoekresultaten op het huis icoon te klikken. Om een ander BAG-object bij het adres te selecteren kan het adres worden uitgeklapt door op het pijltje te klikken en vervolgens het gewenste BAG-object via het huis icoon toe te voegen. Geselecteerde BAG-objecten worden direct aan de zaak toegevoegd.
**Akkoord**
Gebruiker kan de toegevoegde BAG-objecten bekijken via het tabblad 'BAG objecten' op de zaakgegevenspagina
**Akkoord**
Het toevoegen van een BAG-object wordt met het id van het BAG-object als wijziging van een object met vermelding van het type (bijvoorbeeld 'pand') vastgelegd in de historie van de zaak
****Akkoord**
