### ISSUE TITLE
10C3.1.8 BAG-objecten binnen OpenFormulieren

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2251]
Als	: formulieren-bouwer
Wil ik	: in de gemaakte formulieren de mogelijkheid bieden aan burgers/bedrijven om iets te melden/aanvragen op het juiste BAG-object 
Zodat ik	: deze uitgevraagde informatie als zaakdata mee kan sturen naar de zaak in het ZAC 

***

### Acceptance criteria:
•	Het BAG-object moet aan de zaak zijn gekoppeld binnen het ZAC zodat de juiste relaties tussen BAG-object en zaak bestaat en terug te zien is

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by Snijhuis** [comment]
NB. Bag Objecten en Open Formulieren. Is dat iets dat gebouwd gaat worden/ op de backlog staat. Navragen bij Stef.

**Comment by PaskalKiers** [comment]
@KarinMasselink met het label: zeg je nu dat OF onderdeel van het product zaakafhandeling? En dat BAG informatie en formulieren onderdeel zijn van het MVP voor evenementmelding?  In de #2243 staat dat dit later kan. 

@GeertDonkers Is dit niet toevallig al in beeld bij de kopgroep OF?  Ik kan geen expliciete bag stories vinden, maar staat me wel bij dat eea al mogelijk is.  Of haal ik nu eisen met betrekking tot locaties en BAG teveel door elkaar?

**Comment by Snijhuis** [comment]
@PaskalKiers @KarinMasselink  deze is voor de goede integratie van Open Forms met ZAC en OpenZaak. De focus rondom implementaties ligt nu natuurlijk op de integratie met e-Suite. Deze neem ik dan ook mee voor later en zal deze op de PodiumD backlog zetten.
Label laat ik er even aan zodat ik deze niet vergeet.

**Comment by Snijhuis** [comment]
Hier wordt dit issue gesloten. Wordt meegenomen in PodiumD backlog, zie https://github.com/Dimpact-Samenwerking/PodiumD/issues/209
