### ISSUE TITLE
BUG: Zoeken op persoon in BRP geeft 501 status (Not Implemented)

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#2258]
***Steps to reproduce:***

1. Zoek persoon op achternaam: Me*

***Expected***
Lijst met personen wordt opgehaald uit BRP

***Actual***
Exceptie in log met melding:

```
09:24:50,034 INFO  [org.jboss.weld.Interceptor] (default task-23) WELD-001703: Unable to determine the @Intercepted Bean<?> for [UnbackedAnnotatedParameter] Parameter 1 of [UnbackedAnnotatedConstructor] @Inject public io.smallrye.faulttolerance.FaultToleranceInterceptor(@Intercepted Bean<?>, FaultToleranceOperationProvider, StrategyCache, FallbackHandlerProvider, MetricsProvider, ExecutorHolder, RequestContextIntegration, CircuitBreakerMaintenanceImpl, SpecCompatibility)
09:24:50,509 WARNING [net.atos.client.brp.BRPClientService] (default task-23) Error while calling listPersonen: Server response from BRP bevragen: 501 (Not Implemented)

```

**Comment by Snijhuis** [comment]
Reactie gehad vanuit HaalCentraal, zie hieronder. Graag even controleren of we op de juiste versie zitten.

Hi Sander, gebruik je de API lab omgeving (v2.0 beta)? Die is onlangs uitgezet, omdat deze een jaar achter liep op v2.0 IO.
Hiervan hebben gebruikers met een API key bericht gekregen, maar jij blijkbaar niet. Excuses daarvoor.

Lees hier hoe je lokaal een testomgeving kunt opzetten, inclusief testpersonen van RvIG:
https://brp-api.github.io/Haal-Centraal-BRP-bevragen/getting-started-v2

**Comment by andyverberne** [comment]
[Uploading... Testset+persoonslijsten+proefomgeving+GBA-V.ods]

**Comment by andyverberne** [comment]
Test data: https://www.rvig.nl/documenten/richtlijnen/2018/09/20/testdataset-persoonslijsten-proefomgevingen-gba-v

**Comment by robertverboom** [comment]
Let op; met dit ticket is alleen de koppeling gerealiseerd. Frontend wordt in ander ticket opgepakt. 
Zoeken op een BSN werkt voor nu alleen!

**Comment by robertverboom** [comment]
ivm met andere front-end tickets, sluit ik deze
