### ISSUE TITLE
BUG: Uitlijning datumcomponent met overige algemene gegevenskolommen 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2261]
***Steps to reproduce:***

1. ga naar een zaakgegevenspagina 
2. 
3. 

***Expected***
uitlijning datumvelden met de rest van de algemene gegevens kolommen 

***Actual***
![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/c218f551-1908-4acb-928b-0fa6bf870e9b)

**Comment by robertverboom** [comment]
NB: Zijn 2 rijen van gemaakt, graag terug naar 3: 

![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/a09100df-84fa-43fb-b661-fd103d019043)

**Comment by RoyBuis** [comment]
### Refinement 16-2

Zaakgegevens in kolommen weergeven
Zaaktypenaam wordt verplaatst naar subheader

**Comment by robertverboom** [comment]
test ok
