### ISSUE TITLE
Filters legen met 1 knop op bedrijfs/personenpagina

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2279]
***Als*** Behandelaar

***Wil ik*** op de bedrijfsgegevenspagina en persoonsgegevenspagina met 1 knop alle toegepaste filters en sorteringen wissen

***Zodat*** ik niet alle filters en sorteringen stuk voor stuk moet legen

***

### Acceptance criteria:
- Wanneer er geen resultaten gevonden worden, graag melding: 'Geen resultaten gevonden'

***
### Prioriteit
- Could haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De gegevens van een persoon of bedrijf kunnen bekeken worden vanuit de persoons- of bedrijfsgegevenspagina. Deze pagina bevat een overzicht van alle zaken waar de persoon of bedrijf bij betrokken is die in de ZAC worden behandeld. In dit overzicht van zaken kan gefilterd en gesorteerd worden. Met deze story is het mogelijk gemaakt om de toegepaste filters en sorteringen in één keer te verwijderen en het overzicht weer in de standaard weergave te zetten, vergelijkbaar met de functie die de werklijsten ook bevat.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met het trechter icoon alle toegepaste filters en sorteringen wissen

**Comment by robertverboom** [comment]
test ok

**Comment by yboers** [comment]
Ik heb deze userstory getest, maar zie geen optie om de zoekopdracht te wissen zoals het nu in het MP wel mogelijk is. Ik mis naast de zoek button een button om te wissen. Ik heb een afbeelding toegevoegd van de inrichting van het MP![wissen.jpg](https://images.zenhubusercontent.com/641c05e481872e4d93db0d77/2e00c541-e465-47bb-a2ee-e9a2acefbaa2).

**Comment by HilbrandHurtak** [comment]
Zie voor het legen van de zoekfilters ook mijn bevinding onder #2537

**Comment by KarinMasselink** [comment]
@HilbrandHurtak  @yboers dit is een andere functie dan het legen van ingevoerde gegevens wanneer je zoekt op bedrijven of personen. 

Dit gaat over de filtering wanneer er aan een persoon of bedrijf meerdere zaken hangen. Wanneer je dan op het oogje in de zoekbalk klinkt kom je op deze pagina: 
![image](https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/assets/124141434/5b56faee-dc8c-4ef7-ad69-e5ea8eec664a)

**Comment by Sevdiya** [comment]
Issue getest op AO ZAC. Filters legen in zoekscherm werkt, alleen bevat het geen trechter icoon maar een pijl naar links met een kruisje erin. 
Filters legen bij persoons en bedrijfspagina werkt ook maar het is niet duidelijk genoeg. Kunnen we de filter als die aan staat een duidelijkere kleurtje geven of een tekst er bij met "let op filter aan" of iets in die zin. Het is nu grijs. 
Daarnaast is het voor de herkenbaarheid wel handig als overal de zelfde filter symbool (de trechter) gebruikt wordt.  Graag overal gelijktrekken.

**Comment by KarinMasselink** [comment]
@Sevdiya wil jij even een printscreen toevoegen van dit symbool, ik zie op de zandbak wel een trechter? Alvast bedankt.

**Comment by yboers** [comment]
![wis filter.jpg](https://images.zenhubusercontent.com/641c05e481872e4d93db0d77/2da38619-c831-468a-b999-be0597844885)

bij deze het voorbeeld van het filter.

**Comment by Sevdiya** [comment]
Filter op persoonsgegevens
![image.png](https://images.zenhubusercontent.com/62bab2ad41d3e533b5edb6fa/3bcc2805-285d-4a6e-a3fb-1027990248af) met filter op zaaktype

zonder filter 
![image.png](https://images.zenhubusercontent.com/62bab2ad41d3e533b5edb6fa/3b0b1004-5095-4c9a-b0ed-8462c61d6557)

![image.png](https://images.zenhubusercontent.com/62bab2ad41d3e533b5edb6fa/e8ad8b0f-a649-4c01-ab9d-b68beb61ce8d) (Wis het zoekfilter)

Graag de filter overal wijzigen in een trechter en duidelijk markeren wanneer filter aan/uit staat.

**Comment by KarinMasselink** [comment]
@yboers  waar is het wis het zoekfilter met pijl en kruisje van ik kan die niet terug vinden? 
Ik heb het idee dat het ook een ander functie is en daardoor ook logischer is waarom er 2 verschillende symbolen zijn. ik kan alleen dat pijl met kruisje zo niet vinden op de pagina die getest moet worden.

**Comment by yboers** [comment]
het icoontje van wis filter komt op meerdere plekken terug als je dan zoekt in de blauwe balk naar Burck en op het loepje klikt en de persoon wordt gevonden, dan zie je ook het icoontje van het wis filter![wis filter bij zoeken naar personen.jpg](https://images.zenhubusercontent.com/641c05e481872e4d93db0d77/e1610e0a-97a3-49c2-932c-95c5a546ef75)

**Comment by KarinMasselink** [comment]
@yboers dank voor het toevoegen van de extra printscreens. En het klopt dat dit 2 verschillende symbolen zijn.
Het verschil tussen de twee is het volgende:
1) pijl met x: is het invoeren van tekst/cijfers, waarna er breed gezocht kan worden, het werkt zeg maar net als de backspaceknop (alleen dan in een keer alles).
2) Trechter: is echt bedoeld voor filters, je kunt dan een selectie in de verschillende kollommen maken en deze filters ook weer wissen, het invoeren van tekst is hier niet mogelijk. 
De werking is daarmee echt wel anders. 

Wat betreft de functionaliteit die is opgeleverd:
Aanpassingen in gebruikersgemak (kleuren van filters, knopjes, etc.) gaan we in het vervolg meenemen en maken niet meer een onderdeel uit van de acceptatie van de functionaliteit bij Atos. 

Op basis van jullie comments zie ik dat jullie het functioneel getest hebben en het werkt, daarom sluit ik dit ticket.

**Comment by Sevdiya** [comment]
@KarinMasselink @yboers 
1. De pijl met x haalt ook de filters leeg en niet alleen de tekst en cijfers, is naar mijn mening geen backspaceknop. Bij het icoontje staat ook letterlijk “wis het zoekfilter”. Prima als het als backspaceknop ingezet wil worden, maar dan moet de tekst vd mouse-over worden aangepast en de optie om de filters/selectie items te wissen worden aangepast. 
2. Bij zaaknummer en bij datumveld kun je iets invoeren. Het is een combi van selectie en invoeren zoals bij punt 1.
