### ISSUE TITLE
Verzenden document per post - zelf

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2289]
Als behandelaar
wil ik vastleggen dat ik een document per post heb verstuurd
zodat het duidelijk is dat een document bij een zaak is verzonden en dat dit ook in het document zichtbaar is 

Zie document in #485 voor beschrijving van functionele wensen en acceptatie criteria

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze story is de actie 'Document verzenden' aan zaakbehandeling toegevoegd waarmee een behandelaar kan vastleggen dat een of meerdere documenten per post zijn verzonden. Een document wordt dan voorzien van een verzenddatum en een ‘is verzonden’ indicatie zodat het duidelijk is dat dit document is verzonden en wanneer dit is gebeurd. Alleen documenten die aan de voorwaarden voor verzenden voldoen kunnen met deze actie worden verzonden, deze voorwaarden zijn: van het bestandstype PDF zijn, status ‘Definitief’ hebben, geen ontvangstdatum hebben en niet de vertrouwelijkheidsaanduiding ‘Geheim, Zeer geheim’ of ‘Confidentieel’ hebben.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met de actie [Document verzenden] een of meerdere documenten selecteren
- Aan de gebruiker worden alleen de documenten getoond die voldoen aan de voorwaarden voor verzenden
- Gebruiker vult de verzenddatum van de documenten in en legt eventueel een toelichting vast
- Aan de verzonden documenten wordt de indicatie ‘is verzonden’ toegevoegd
- Het verzenden van een document leidt tot een nieuwe versie van het document en wordt in de historie van het document vastgelegd

**Comment by RoyBuis** [comment]
### Refinement 16-2

Op scherm moeten de documenten geselecteerd kunnen worden (aanvinken), met de volgende criteria:
-Alleen definitieve bestanden tonen
-Documenten met ontvangstdatum niet tonen
-Alleen van type PDF &PDF/a tonen
-Documenten met vertrouwelijkheidsaanduiding ‘Geheim, Zeer geheim, Confidentieel’ niet tonen
Grootte van bestanden tonen

**Comment by robertverboom** [comment]
test ok (let op deel van ticket is opgelost, rest volgt)

**Comment by CommonGroundGroningen** [comment]
**Gebruiker kan met de actie [Document verzenden] een of meerdere documenten selecteren**
Test ok
**Aan de gebruiker worden alleen de documenten getoond die voldoen aan de voorwaarden voor verzenden**
Test ok
**Gebruiker vult de verzenddatum van de documenten in en legt eventueel een toelichting vast**
Test ok
**Aan de verzonden documenten wordt de indicatie ‘is verzonden’ toegevoegd**
Test ok
**Het verzenden van een document leidt tot een nieuwe versie van het document en wordt in de historie van het document vastgelegd**
Test ok
