### ISSUE TITLE
In scherm bewerk component - DEEL 2

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#23]
Er moet een nieuw component komen om in de tonen schermen direct een veld te kunnen bewerken.

Taak -> toelichting (zoals ook description in Jira wordt ge-edit)

Behandelaar -> keuze van behandelaar, naam van gebruiker zelf bovenaan in lijst tonen

Dit component moet generiek worden opgezet. Goede naam voor bedenken. Er moet een component voor tekst en component voor select komen.

- [x] Bewerk icoontje op docpag kan weg
- [x] Issue: De grote van het icoontje drukt de tekst naar beneden bij Behandelaar toekennen
- [x] Title op icoon
- [x] Assign to me button
- [x] Overbodige componentne verwijderen
- [x] Behandelaar component aanpassen
- [x] knoppen bewerken
- [x] outside click

**Comment by robertverboom** [comment]
- [ ] Issue: De grote van het icoontje drukt de tekst naar beneden bij Behandelaar toekennen
- [ ] Title op icoon
- [ ] Assign to me button
- [ ] Overbodige componentne verwijderen
- [ ] Behandelaar component aanpassen
- [ ] Bewerk icoontje op docpag kan weg
- [ ] knoppen bewerken
- [ ] outside click

**Comment by andyverberne** [comment]
Ik ergens in een file een review commentaar achtergelaten. 
Hoe nu verder met deze review is mij niet duidelijk.

**Comment by andyverberne** [comment]
In de test omgeving gaat het aanmaken van een zaak of het bekijken van een zaak fout.
Voor fout zie Chrome Console.
Het gaat fout in de init method van EditBehandelaarComponent.

Dit is ook lokaal te reproduceren tegen de develop omgeving. Echter het treed niet altijd op.
Onduidelijk is wanneer wel en wanneer niet. Ik heb geen definitief antwoord kunnen vinden.
Ik ben wel het volgende tegengekomen: https://dev.to/nickraphael/ngonchanges-best-practice-always-use-simplechanges-always-1feg
Ik heb dat geprobeerd maar dat loste niet het uiteindelijke probleem op.

**Comment by andyverberne** [comment]
Ik heb de code in de onChange aangepast zoals besproken. Daarna een nieuwe versie op de test omgeving gezet maar nu gaat het mis in de ngOnInit.
