### ISSUE TITLE
Inzicht in foutlogging voor functioneel beheer

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2300]
***Als*** Functioneel beheerder

***Wil ik*** de fouten die ontstaan tijdens de inrichting of gebruik van het ZAC kunnen inzien (monitoren)

***Zodat*** ik goed op de hoogte ben van eventuele fouten, deze kan nalezen/ inzien zodat ik ze kan oplossen.

***
Een eerste basale opzet van een foutenmonitor voor Functioneel beheer. Verfijnen op basis van behoefte

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement SN, RV & RB

Er is nu toegang tot logging in Google Cloud Platform, uitzoeken of een beheerder hier iets mee kan. Of is het nodig om ZAC specifieke meldingen inzichtelijk te maken. Sander bespreekt eerst met platform team.

**Comment by Snijhuis** [comment]
**Update* 27-03*
Pakken we nu niet op voor ZAC alleen. Issue overgezet naar PodiumD backlog. https://github.com/Dimpact-Samenwerking/PodiumD/issues/207
