### ISSUE TITLE
Rapportages: de procesdata (taken) moet te ontsluiten zijn voor rapportages

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2302]
***Als*** Gemeente

***Wil ik*** naast de zaakdata uit OpenZaak ook de Procesdata uit ZAC/Flowable van zaken kunnen ontsluiten voor BI-tools

***Zodat*** wij een volledige rapportage kunnen maken voor management of stuur rapportages

***
Wellicht een API maken die bevraagd kan worden zodat de data real time kan worden opgehaald

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 2-3

In deze fase van de ZAC ontwikkeling is het niet verstandig om hier iets voor te maken
Mogelijke toekomstige oplossing zijn:
- op basis van Solr 
- een specifieke API maken voor ontsluiten van procesdata
- procesdata opslaan via Overige Registraties

Duidelijk onderscheid maken in het doel van het opvragen van de data, is fdit voor rapportages of voor BI doeleinden

Sander bespreekt dit verder met Platform Team

**Comment by Snijhuis** [comment]
Story overgeheveld naar PodiumD backlog. Pakken we nu niet op binnen ZAC maar gaan we breder oppakken vanuit Rapportages
https://github.com/Dimpact-Samenwerking/PodiumD/issues/206
