### ISSUE TITLE
BUG: Foutmelding bij afhandelen hoofdzaak met openstaande deelzaak

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2303]
***Steps to reproduce:***

1. Koppel een zaak als deelzaak aan een andere zaak
2. Open de hoofdzaak en handel deze af met de Zaak afhandelen actie
3. 

***Expected***
Er wordt een melding getoond dat dit niet is toegestaan

***Actual***
Er wordt een 500 melding getoond

Kan op develop gereproduceerd worden met zaken van het zelfde zaaktype, zie bijv https://zac.develop-public-service-platform.net/zaken/ZAAK-2023-0000000144

**Comment by robertverboom** [comment]
### Refinement
- Check aan de achterkant is goed
- knop 'Zaak afhandelen' niet tonen wanneer er deelzaken open zijn
