### ISSUE TITLE
BUG: Verkorte zaak blok vastzetten 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2307]
***Steps to reproduce:***

1. zet een taak op een zaak met een uitgebreide tekst, zodat scherm gevuld kan worden
2. Ga naar de taak
3. verander iets op de verkorte zaak van de taak

***Expected***
Verkorte zaak blijft op zn positie

***Actual***
Gezien de tekst groot is, drukt deze de positie van de verkorte zaak weg

**Comment by robertverboom** [comment]
Een algemene info taak heeft standaard lang stuk tekst in de mail, die dit issue reproduceert

**Comment by marcoatos** [comment]
Komt dit nog voor? Kan het niet meer reproduceren, of ik zie het probleem niet.

Scherm ziet er hetzelfde uit met de taak aanvullende info, met en zonder lang stuk tekst. Ik kan ook niets aanpassen in de verkorte zaak op de taak, dus dat deel snap ik ook niet helemaal.

**Comment by marcoatos** [comment]
In overleg met Robert een maximale breedte gegevens, zodat bij langer zinnen de taakgegevens en verkorte zaak niet samengedrukt worden.

**Comment by robertverboom** [comment]
test ok!

**Comment by RoyBuis** [comment]
### Refinement 16-3

Dit treedt nu nog op voor het verkorte taak blok bij een geopende zaak. issue daarom heropend

**Comment by robertverboom** [comment]
Speelt inderdaad weer door dat (denk ik) de behandelaar volledig wordt getoond.

**Comment by robertverboom** [comment]
test ok
