### ISSUE TITLE
BUG: In edit mode wordt de huidige behandelaar niet getoond maar generieke tekst Behandelaar

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#231]
***Steps to reproduce:***

1. Open ZAAK-2021-0000000329
2. Klik op de behandelaar (bewerk mode)

***Expected***
Verwachting is dat de huidige behandelaar wordt getoond

***Actual***
Generieke tekst Behandelaar wordt getoond
![Screenshot 2022-01-07 141225.png](https://images.zenhubusercontent.com/61a7619ff842ca7ff613d64f/e5dcbad9-a835-4846-bc97-5642ee4cc6b9)

**Comment by robertverboom** [comment]
test ok
