### ISSUE TITLE
BUG: geen optie in select behandelaar om vrij te kunnen geven. 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2323]
***Steps to reproduce:***

1. Ga naar een zaak, die een behandelaar heeft
2. Probeer de zaak vrij te geven zonder op het icoontje te klikken vrijgeven te kilkken
3. 

***Expected***
In het filter heb je - Kies behandelaar - 

***Actual***
Alle gebruikers worden getoond, echter niet een optie om 'geen gebruiker' te selecteren.

**Comment by jeroen-dekker** [comment]
Dat is toch de gewenste functionaliteit van het autocomplete-component? Je kan zelf iets intypen of het veld leeg maken. De vrijgeven-knop doet ook niks anders dan het medewerker-veld leegmaken.

**Comment by robertverboom** [comment]
test ok
