### ISSUE TITLE
Zoeken: Zoekresultaten kunnen exporteren

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#2330]
***Als*** 
Medewerker

***Wil ik*** 
De zoekresultaten kunnen exporteren (zoals bij een Werklijst nu ook kan in het ZAC)

***Zodat*** 
Ik de Zoekresultaten kan exporteren en met het gemaakte bestand de zoekresultaten kan delen met een collega.
***

### Acceptance criteria:
 Zoekresultaten kunnen exporteren naar excel (of csv bestand)

***
### Prioriteit
*Verwijder wat niet van toepassing is:*

Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by PaskalKiers** [comment]
Wil je zoekresultaten exporteren of zoekresultaten delen?  En dat delen, met welk doel is dat? Hoe vaak gebeurt dat?   Mijn eerste gedachte was dat het een verkapte werkverdelersfunctionaliteit is. 
Wat moet er in die zoekresultaten staan.  Als het een export is, dan zou ik bij acceptatiecriteria wel zetten dat privacy en security personen de invulling accepteren.  Hoe makkelijk dat gaat is afhankelijk van welke informatie je exporteert.

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

WG Refinement heeft aangegeven deze niet te realiseren, issue wordt gesloten.
