### ISSUE TITLE
omschrijving zaak, maximaal aantal tekens

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#2331]
***Als*** 
Medewerker / Postmedewerker

***Wil ik*** 
Bij het veld "omschrijving" van een zaak meer tekst kunnen invoeren.
Nu 80 tekens is de max.

***Zodat*** 
Een volledige beschrijving van de zaak kwijt kan in het veld omschrijving.
Het veld "Toelichting" heeft nu een maximum van 1000 tekens. Omschrijving dan ook naar maximaal 1000 tekens oprekken

***

### Acceptance criteria:
Meer tekst kwijt kunnen in veld "Omschrijving"

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by PaskalKiers** [comment]
Wat is de functie van die omschrijving die 1000 karakters nodig heeft? 

Volgens mij is dekt het huidige label omschrijving de lading niet en zou het "korte zaakomschrijving" "zaakidentificatie in woorden"  ofzo moeten zijn.    

Ik heb het idee dat hier een andere behoefte onder zit.  Bijvoorbeeld dat je op steekwoorden kan zoeken, of op andere velden dan nu mogelijk is.

**Comment by VictorTielenius** [comment]
Ook mbt Omschrijving van zaak die vanuit een gekoppelde applicaties komt.

**Comment by Snijhuis** [comment]
**23-03 Refinement**
Kunnen we nu niet oppakken. Het veld omschrijving bevat max 80 tekens vanuit RGBZ, OpenZaak, ZG API's etc. 
Als er aanpassingen gedaan worden op die standaarden kunnen we dit ook implementeren in o.a. ZAC. Voor nu issue dus gesloten op deze backlog.
