### ISSUE TITLE
7.3.2A Document bewerken in Zaakscherm

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#2332]
***Als*** 
Behandelaar

***Wil ik*** 
Op het scherm van de zaak, bij het document, de mogelijkheid hebben om het document te bewerken. (nu is dit mogelijk op het de pagina van het Document in het ZAC)
(Zie ook #351)

***Zodat*** 
Zonder naar de details van het document te gaan, wil ik de mogelijkheid ook hebben om het document te bewerken.

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves / Should haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze story is de UI van het documentenoverzicht op de zaakpagina aangepast. De bewerken functionaliteit is nu, als bewerken mogelijk is, direct beschikbaar vanuit het documentenoverzicht. Daarnaast blijft het oog icoon om te openen altijd beschikbaar. De verplaatsen, ontkoppelen en downloaden functies zijn ook beschikbaar zonder het document te hoeven openen door op het kebab menu te klikken.

***Belangrijkste functionaliteiten:***
- Gebruiker kan een document vanuit het documentenoverzicht direct bewerken via het potlood icoon
- Gebruiker kan de verplaatsen, ontkoppelen en downloaden knoppen bij een document vanuit het documentenoverzicht benaderen via het kebab menu (3 verticale puntjes)

**Comment by PaskalKiers** [comment]
Begrijp ik hem goed dat dit #351 is, met als enige verschil de volgende tekst (of iets van de strekking)? 

'De [Bewerken] knop is beschikbaar in het documentenoverzicht op de zaakview voor documenten die niet definitief zijn en van het type dat bewerkt kunnen worden.'

**Comment by robertverboom** [comment]
### Refinement RB, KM, SN, RV:

- iconen: documentdetail en document bewerken altijd in tabel tonen
- andere opties achter ![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/6c255fe0-f074-4ef0-81af-b0ab5ce45cb3) icoon

**Comment by robertverboom** [comment]
### Refinement RB, KM, SN, RV:

- iconen: documentdetail en document bewerken altijd in tabel tonen
- andere opties achter ![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/6c255fe0-f074-4ef0-81af-b0ab5ce45cb3) icoon

**Comment by robertverboom** [comment]
test ok

**Comment by CommonGroundGroningen** [comment]
**Gebruiker kan een document vanuit het documentenoverzicht direct bewerken via het potlood icoon**
Test OK
**Gebruiker kan de verplaatsen, ontkoppelen en downloaden knoppen bij een document vanuit het documentenoverzicht benaderen via het kebab menu (3 verticale puntjes)**
Test OK
