### ISSUE TITLE
Bij een besluit met vervaldatum de vervalreden vastleggen

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2342]
***Als*** recordmanager

***Wil ik*** bij een besluit dat met een vervaldatum wordt vastgelegd de vervalreden gevuld wordt met 'Besluit met tijdelijke werking'

***Zodat*** dit veld dan een geldige waarde heeft

***

### Acceptance criteria:
- geldt bij het aanmaken en wijzigen van een besluit
- vervalreden is zichtbaar bij besluit (als mouse over bij vervaldatum veld)
- als de vervaldatum wordt verwijderd dan ook de reden weer verwijderen
- wijzigingen van vervalreden tonen in de historie van besluit

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 28-2

**Te realiseren**

- Zie omschrijving van story
- Additionele wijzigingen:
  - Label van veld 'Toelichting' veranderen in 'Toelichting op besluit'
  - Label van veld 'Reden' bij wijzigen besluit veranderen in 'Reden wijziging'

**Comment by jeroen-dekker** [comment]
Er wordt geen audittrail-regel aangemaakt voor het wijzigen van de vervalreden. Dit moet gewijzigd worden in OZ.
