### ISSUE TITLE
Zaken; Grafische weergave van waar je bent in het geheel

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#2343]
***Als*** 
Behandelaar

***Wil ik*** 
Grafische weergave van waar je bent in het geheel van diverse gerelateerde zaken op meerdere niveaus.

***Zodat*** 
Zodat ik kan zien waar ik in het geheel, van diverse zaken die aan elkaar gerelateerd zijn, ben.
Wanneer er sprake is van zaken die aan elkaar gerelateerd zijn op verschillende niveaus kan je nu niet zien waar je bent in het geheel.
Dus bijv. van hoofdzaak naar deelzaak, en de relaties (bijv. vervolgzaak) van de deelzaak ook bij de hoofdzaak te zien.
***

### Acceptance criteria:
(Grafische) weergave zaakrelaties

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves / Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by PaskalKiers** [comment]
Dit gaat alleen om gerelateerde zaken, waarbij er een soort hierarchische relatie tussen de zaken?
Dus dit gaat niet om relaties tussen zaken op basis van betrokken personen, of overeenkomstige bag objecten (evenementmeldingen voor dezelfde locatie, op dezelfde of aanpalende data) 

Grafische weergave?  Wat is er mis met een lap tekst? :)  
Wat is grafisch? Is een tabelletje waaruit je de informatie ook grafisch?  Of moet er een plaatje worden gegenereerd, met daarin de zaken grafisch weergegeven, met daarin pictogrammen met daaronder de zaakidentificaties. 
Wil je niet ook op de gerelateerde zaken kunnen klikken? 
Je wilt altijd dat de complete set aan gerelateerde zaken zichtbaar is?

**Comment by Snijhuis** [comment]
**WG R 10-05**
Grafisch weergeven van bijvoorbeeld zaakrelaties, voortgang (soort kruimelpad idee), bolletjes, tijdlijn. Kortom, visueel maken wat de status, relaties zijn.
Nemen we mee naar PodiumD backlog.
