### ISSUE TITLE
Zaak koppelen aanpassen

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2348]
Als             : medewerker
Wil ik        : bij ‘zaak koppelen’ de zaak kunnen zoeken en koppelen via een overlay scherm (aan de rechterkant van het scherm)
Zodat ik   : alle functionaliteiten bij toevoegen en koppelen op dezelfde manier gebruik
 
Acceptatiecriteria            :
•	‘zaak koppelen’ gaat hetzelfde werken als de overige knoppen (initiator toekennen, betrokkene toevoegen, BAG-object toevoegen) onder koppelingen
•	In de overlay moet dezelfde mogelijkheden beschikbaar zijn als nu bij het vak ‘zoeken’ zodat je op alle mogelijke manieren een zaak kunt vinden en koppelen
•	10C.1.3.1 gerelateerde (onderwerp) zaakrelatie tussen zaken leggen · Issue #2204 is te gebruiken

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement KM, RV& RB

Dit wordt in de gebruiksvriendelijkheidstest nader bekeken. Issue wordt gesloten.
