### ISSUE TITLE
ACCEPTATIE BUG: Document metadata bij nieuwe versie wordt niet weggeschreven

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#2351]
zaakafhandelcomponent#374
7.5.1 Documentmetadata aanpassen door zaakbehandelaar

**Beschrijf de bug**
**Alle aangepaste metadata worden als wijziging in de historie van het document opgenomen**
De wijziging van de status (is metadata) wordt niet meegenomen bij het toevoegen van een nieuwe versie.
De initiële waarde (documentstatus) die aan het document is meegegeven blijft staan zelfs na aanpassing. Bij het tabblad historie zien we het veld status ook niet terug.

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1. Open document bij zaak
2. Klik op nieuwe versie toevoegen
3. Wijzig document status
4. Klik op Toevoegen

**Verwacht gedrag**
Documentstatus wordt gewijzigd. Dit is ook zichtbaar in de historie.

**Daadwerkelijk gedrag**
Documentstatus wordt niet gewijzigd. Wel wordt er een nieuwe versie aangemaakt.

**Comment by Sevdiya** [comment]
Op https://zac.zandbak-public-service-platform.net/fout-pagina geeft het een code 500 fout
Op acceptatie werkt het wel. Zie zaak 2023-0000000038. Bijlagen toevoegen gaf foutbericht.
