### ISSUE TITLE
BUG: iconen van datumpikker staan op de werklijst over de tekst

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2354]
***Steps to reproduce:***

wanneer er meer kolommen in de werklijst staan dan staat het icoon van de kalender over de tekst. Wanneer er minder kolommen staan zodat het op het scherm past staan ze er netjes achter

***Expected***

***Actual***
![image.png](https://images.zenhubusercontent.com/6215ee21a7a0b74c19209bdb/50331eb0-880b-46d5-89bd-289739e1367d)

**Comment by RoyBuis** [comment]
### Refinement 21-3

- Kolommen met een datumbereik krijgen een vaste breedte zodat kalendertje niet over tekst heen valt en het ingevoerde bereik te lezen is.
- Datum van en datum tot onder elkaar tonen in plaats van naast elkaar
- Extra labels bij datumbereik kolommen verwijderen
- In alle kolommen de optie 'Kies een ......' vervangen door '- Alle -' zodat de kolommen smaller worden

**Comment by HilbrandHurtak** [comment]
@RoyBuis Ik heb dit ticket opgepakt maar zie de "BUG" nog steeds (getest op de zandbak door in werkvoorraad alle kolommen toe te voegen)

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/b6df9db0-0ddf-4c9b-a521-682f55e0057a)

Wil jij ook even testen?

**Comment by RoyBuis** [comment]
@HilbrandHurtak Dit is inderdad nog niet uitgerold, ik haal deze even uit jullie bord

**Comment by robertverboom** [comment]
Laatste versie is uitgerold. Dit ticket is gereed voor test
