### ISSUE TITLE
BUG: blok opmerkingen bij taak Aanvullende informatie

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2355]
Het blok 'opmerkingen' staat op de scherm 'Aanvullende informatie' direct zonder zichtbare scheiding onder de tekst van de verzonden mail en lijkt daardoor bij de tekst te horen. Blok verplaatsen onder de aanvullende gegevens.
Je vult als gebruiker eerst de actie in van datum aangeleverd en of deze aanvullende informatie is geleverd en pas daarna een eventuele opmerking.
Vraag aan werkgroep: 

- klopt dan de term 'opmerking' wel of moet dat zijn 'toelichting op hervatten zaak'?

- verplichting aan of uit?

***Expected***

***Actual***

**Comment by GertrudeKampherbeek** [comment]
![image.png](https://images.zenhubusercontent.com/6215ee21a7a0b74c19209bdb/2264ca23-57e4-43dc-be4b-1e03d048e49c)

**Comment by HilbrandHurtak** [comment]
Het veld opmerkingen lijkt nu inderdaad bij de mailtekst te horen. Verschuiven naar de voorgestelde positie is prima

Ik vraag me wel af of het veld alleen maar betrekking heeft op toelichting op hervatten zaak of dat je hier een samenvatting van de aangeleverde informatie kunt invullen.

**Comment by RoyBuis** [comment]
### Refinement KM, SN, RV & RB

Taakscherm aanpassen:

- Opmerkingenveld naar beneden verplaatsen, onder de radiobutton
- Veld optioneel maken
- Naam placeholder aanpassen naar 'Toelichting'
- Duidelijker onderscheid maken in taak tussen gegevens van verzonden mail en de velden die de behandelaar invult

**Comment by RoyBuis** [comment]
### Refinement 28-3

Voorstel voor aanpassing taakscherm Aanvullende infomatie overnemen uit vorige  opmerking, zie hierboven.

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Test ok. Blok verschoven, niet meer verplicht en heet nu toelichting
