### ISSUE TITLE
BUG: hervatten na verlengen is niet mogelijk

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#2356]
zie zaak https://zac.accept-public-service-platform.net/zaken/ZAAK-2023-0000000036 
na opschorten kan de zaak wel worden hervat maar na verlengen niet.
In eerste instantie dacht ik dat het niet kon omdat er nog een taak was die 'mee verlengd' was maar dat was niet het geval.
Het icoon hervatten verandert wel even maar wordt niet actief.

***Expected***

***Actual***
![image.png](https://images.zenhubusercontent.com/6215ee21a7a0b74c19209bdb/d0e65166-b40d-4bef-a3f2-475b496e86e9)

**Comment by HilbrandHurtak** [comment]
Functionaliteit opschorten en verlengen is gewijzigd obv uitwerking Gertrude. Er staan nog tickets open waarbij het verzoek was aan Gertrude om dit te testen. Issues die ik toe gevonden heb zijn:
#175
#176
#1703
#1521
#1848

Graag opnieuw de juiste werking van opschorten en verlengen testen. Wie pakt dit op?

**Comment by RoyBuis** [comment]
### Refinement KM, RB en RV
Voor een zaak die verlengd is wordt de streef- en fatale datum aangepast en dit is dan permanent. Het is niet nodig om een zaak te hervatten.

**Comment by Sevdiya** [comment]
Eens met Roy. De zaak is verlengd hoeft niet hervat te worden.
