### ISSUE TITLE
Her-indexeren van grote hoeveelheden zaken/taken/documenten.

### ISSUE THREAD

**Issue by ronniekoopmans-atos** [NL-AMS-LOCGOV/zaakafhandelcomponent#2357]
***Als*** Ontwikkelaar
***Wil ik*** een robuuste afhandeling van het her-indexeren
***Zodat*** bij het groeien van de data, er geen timeout's optreden, waardoor het indexeren niet meer gebeurt.

### Acceptance criteria:
1. ongeacht het aantal zaken/taken/documenten, waarop het afhandelen van het (her)indexeren plaatsvindt.

***
### Prioriteit
- Should haves

***
### Gerealiseerd
Een afhandeling in kleine transacties, dmv een bv jee batch implementatie, of met een helper-bean met eigen transactie.

**Comment by robertverboom** [comment]
### Refinement 07-03:
- 'misschien' gebruik maken van batch API  
- logging erbij, zodat je ziet wat er gebeurt

**Comment by robertverboom** [comment]
Test ok
