### ISSUE TITLE
Ontkoppelde documenten 

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#2360]
***Als*** 
Medewerker / Postmederwerker

***Wil ik*** 
In werklijst Ontkoppelde documenten ook zichtbaar hebben vanuit welke zaak het document komt. 

***Zodat*** 
Ik heb onterecht ontkoppelen van het document het document snel bij de zaak terug kan zetten
***

### Acceptance criteria:
Zaaknummer vanuit welke zaak het document komt zichtbaar hebben in werklijst Ontkoppelde documenten 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Er is een kolom 'Zaak' aan de werklijst 'Ontkoppelde documenten' toegevoegd waar het zaaknummer waar die uit ontkoppeld is te zien is.
***Belangrijkste functionaliteiten:***
- 
-

**Comment by Renvooi** [comment]
@VictorTielenius 
9-5-2023 Ik heb deze getest. 
In het overzicht van ontkoppelde documenten is een kolom aanwezig met de zaaknummers van herkomst.
Een ontkoppeld document uit zaak ZAAK-2022-0000000055 teruggeplaatst in dezelfde zaak. Dat ging goed. 
Wil je dit zelf ook nog testen of kan #2360 nu als closed worden aangemerkt?

**Comment by HilbrandHurtak** [comment]
11-5-2023 ook getest en alles lijkt te werken. Ticket afgehandeld
