### ISSUE TITLE
BUG: gebruiker wordt niet veranderd bij inloggen ZAC met andere gebruiker

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2367]
***Steps to reproduce:***

1. Log in en open de ZAC
2. Log uit met de huidige gebruiker
3. Log in met een andere gebruiker

***Expected***
De naam van de actuele ingelogde gebruiker wordt getoond in het profiel

***Actual***
De naam van de eerder ingelogde gebruiker wordt getoond in het profiel

**Comment by robertverboom** [comment]
test ok
