### ISSUE TITLE
BUG: Fout bij verplaatsen vanuit werklijst 'Ontkoppeld documenten' door Behandelaar

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2373]
***Steps to reproduce:***

1. Log in de ZAC in met een gebruiker die de 'behandelaar rol' heeft 
2. Ga naar werklijst 'Ontkoppelde documenten'
3. Zet een document op het klembord met de Verplaatsen knop
4. Ga naar een zaak en verplaats het document

***Expected***
Het document wordt toegevoegd aan de zaak

***Actual***
Een 500 error wordt getoond

**Comment by marcoatos** [comment]
Ik denk dat ik deze opgelost heb met #2394 
Kan hem in ieder geval op het moment niet reproduceren.

**Comment by robertverboom** [comment]
Op develop krijg ik nog steeds een foutmelding. 
Let op dat je moet inloggen als Behandelaar, zonder de rechten van recordmanager
