### ISSUE TITLE
BUG: 2e tab voor documenten worden standaard geopend

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2375]
***Steps to reproduce:***

1. Voeg een Document toe aan een besluit: https://zac.develop-public-service-platform.net/zaken/ZAAK-2022-0000002245
2. Open het document in het blok besluit
3. 

***Expected***
document dat wordt geopend, blijft in dezelfde tab open. Pas door cltr + click / open link in nnew tab wordt er een 2e tab geopend

***Actual***
wordt standaard 2e tab geopend met document gegevens.

**Comment by RoyBuis** [comment]
### Refinement 21-3

- Documentenlijstcomponent parametriseren met parameter die aangeeft of het document in een nieuwe tab moet worden geopend of niet.
- Default (niet opgegeven) is 'openen in huidige tab'
- Alleen bij taken moet deze op True gezet worden

**Comment by robertverboom** [comment]
test ok
