### ISSUE TITLE
Mogelijk maken om document van bestandstype .msg aan zaak toe te voegen

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2377]
***Als*** behandelaar

***Wil ik*** een Outlook e-mail als msg bestand aan een zaak kunnen toevoegen

***Zodat*** ik ontvangen e-mails bij een zaak kan toevoegen

***

### Acceptance criteria:
-

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Het bestandstype .msg is toegevoegd aan de lijst van toegestane bestandstypen. Daarmee wordt het mogelijk om documenten met een bestand van bestandstype .msg zoals een Outlook e-mail aan een zaak toe te voegen. 

***Belangrijkste functionaliteiten:***
- Gebruiker kan bestanden van bestandstype .msg gebruiken bij het toevoegen van een document aan een zaak

**Comment by RoyBuis** [comment]
### Refinement 7-3

Toepassen op zandbak omgeving
Bestandstype toevoegen aan ADDITIONAL_ALLOWED_FILE_TYPES: 'msg'
Omgeving opnieuw installeren

**Comment by VictorTielenius** [comment]
Mail gesleept vanuit Outlook en aan Zaak toegevoegd (ZAAK-2023-0000000076; De bijlage in de mail is hier niet te openen. (ATP-scan wordt uitgevoerd" staat op plek van bijlage,

Mail opgeslagen op schijf, en dan aan zaak toegevoegd: OK (hier wordt de bijlage wel getoond en is te openen.)

**Comment by VictorTielenius** [comment]
Nogmaals getest en nu komt mail incl. PDF bijlage goed over bij slepen. Ook plaatje in mail nu zichtbaar.
Lag aan dat ik de mail net naar mezelf had gestuurd en vrij snel na binnenkomst had gesleept naar ZAC Accept en de bijlage nog werd gescand op virussen door onze techniek.
