### ISSUE TITLE
Selectielijst kolomkoppen staat niet meer alfabetisch

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#2379]

**Comment by Renvooi** [comment]
Voorbeeld: Zaken-werkvoorraad > wijzig kolomkoppen.
Meeste wel alfabetisch maar vermoed dat met laatste toevoegingen de volgorde niet automatisch weer alfabetisch werd. Zie bijlag![kolomkoppen instellen.jpg](https://images.zenhubusercontent.com/6215f444b107d1655b3e98b3/91e83905-7be2-4578-bc20-6aadcb5135d2)e

**Comment by RoyBuis** [comment]
### Refinement 16-3

Kolommen met de hand op alfabet zetten
