### ISSUE TITLE
BUG: Document wordt niet bij de zaak getoond (specifieke situatie)

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#2381]
***Steps to reproduce:***

1. Maak een zaak 1 aan en voeg daar een document aan toe
2. Maak een zaak 2 aan
3. Wacht een minuut i.v.m. opbouw indexering
3. Vanuit Zaak 2 zoek vervolgens zaak 1 via Zoekvenster en open deze zaak

***Expected***
Het document behorende bij zaak 1 wordt getoond

***Actual***
Het document behorende bij zaak 1 wordt niet getoond (Pas na handmatige refresh is het document zichtbaar)

**Comment by RoyBuis** [comment]
### Refinement 21-3

Oorzaak mogelijk dezelfde als #2382

**Comment by hansmarks** [comment]
Wat er gebeurde was dat de documenten van de verkeerde zaak (namelijk zaak2) in de zaakdocumenten-component werden geladen.
