### ISSUE TITLE
Versienummer verplaatsen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2384]
***Als*** Behandelaar

***Wil ik*** het versienummer minder opvallend zien

***Zodat*** er meer ruimte overblijft voor andere informatie op het scherm

***

### Acceptance criteria:
- 

***
### Prioriteit
- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Het versienummer van de Zaakafhandelcomponent is verplaatst van onderaan het scherm naar het profiel van de ingelogde gebruiker.

***Belangrijkste functionaliteiten:***
- Gebruiker kan de informatie over de huidige build bekijken door het profiel te openen en met de muisaanwijzer over het versie icoon te zweven
- Gebruiker kan de informatie eveneens zien door de Beheer instellingen te openen en dit onderaan bij de Inrichtingscheck te bekijken

**Comment by robertverboom** [comment]
Idee om versienummer in het profiel menu te zetten. Dan kan een gebruiker er altijd bij en zie je het nergens op het scherm wat ruimte opoffert

**Comment by robertverboom** [comment]
Door de footer komt er nu in de ZAP een dubbele scrolbalk:
![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/89f01e33-5446-4a2b-98ab-b8db192f2d06)

**Comment by RoyBuis** [comment]
### Refinement 16-3

Versie info zoals voorgesteld verplaatsen van onderaan scherm naar het profiel van de gebruiker onder de uitlog knop.

**Comment by CommonGroundGroningen** [comment]
Versienummer alleen zichtbaar in profiel van de gebruiker.
TEST OK
