### ISSUE TITLE
Rechtstreeks .msg bestanden vanuit outlook slepen en als document toevoegen aan de zaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2385]
***Als*** Behandelaar

***Wil ik*** zolang er geen outlook plugin is binnen PodiumD mijn mail vanuit outlook  als .msg bestand kunnen toevoegen door deze te slepen naar het component waar ook andere documenten kunnen worden toegevoegd

***Zodat*** er in de MVP toch op een eenvoudige wijze kan worden gewerkt met het toevoegen van mail.

***

### Acceptance criteria:
- mail kan worden gesleept naar de functie/toevoegen documenten binnen ZAC
- bestand wordt als .msg opgeslagen en kan dus ook als mail weer worden geopend

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

Deze tijdelijke oplossing is reeds besproken in de werkgroep refinement en acceptatie en is akkoord bevonden.

voorbeeld (bestand is vanuit outlook naar het component gesleept)
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/1c870b66-ac6f-402b-a50b-3dd985019b24)

Later dan maar kijken of we vanuit outlook direct zelf een document aan een zaak kunnen toevoegen of een zaak kunnen laten starten
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze user story is de UI verbeterd door het mogelijk te maken om een bestand vanuit bijvoorbeeld Outlook of Windows verkenner te slepen naar het 'Bestandsnaam' veld in de 'Toevoegen document' actie.

***Belangrijkste functionaliteiten:***
- Gebruiker kan bij het gebruik van de [Toevoegen document] actie het bestand toevoegen door deze te slepen vanuit een andere applicatie zoals Outlook

**Comment by robertverboom** [comment]
drag & drop bij bestanden mogelijk maken

**Comment by HilbrandHurtak** [comment]
Gezien de vraag of de bijlagen in de mail als afzonderlijke documenten moeten worden opgeslagen(inclusief de juiste metadata) heb ik de volgende vraag uitgezet bij de werkgroep Informatiebeheer:

Dag Rik

We zijn binnen ZAC bezig met het toevoegen van mail aan een zaak. De eerste versie bestaat uit het slepen van je mail naar het downloadcomponent in de zaak waarna je de metadata kunt invullen en bewaren. De mail wordt als .msg bewaard en is dan ook vervolgens weer te openen via outlook(inclusief te meegestuurde bijlage). Deze functionaliteit is gelijk aan die van de huidige e-Suite. Een integratie met een outlook plugin staat nog niet op de planning.

Vraag
Mogen de mails met bijlagen als 1 bestand worden opgeslagen of moeten de bijlagen als afzonderlijke bestanden(met metadata) worden bewaard. Indien dat wettelijk moet zullen we dan ook de relatie tussen de mail en de meegestuurde bijlagen moeten vastleggen?

Groet
Hilbrand

**Comment by HilbrandHurtak** [comment]
Advies werkgroep Informatiebeheer

Mail en bijlage van mail worden als samengestelde bestanden gezien. Deze moeten dus apart van metadata voorzien kunnen worden en aan elkaar gerelateerd kunnen worden. Hoe dit gebeurt is aan de applicatie.
Grondslag hiervoor is niet een directe wettelijke eis, deze komt uit NEN-ISO 16175-1.

**Comment by RoyBuis** [comment]
Ter info, uit de API specs: Vooralsnog ondersteunt de Documenten API alleen enkelvoudige informatieobjecten.

**Comment by HilbrandHurtak** [comment]
Vanuit de werkgroep Informatiebeheer komt er een nieuwe user story. Uitgangspunt is om toch de mail en de bijlage(samengestelde bestanden) als afzonderlijke bestanden bij de zaak te bewaren. Zodra het ticket is ingevoerd kan het nummer worden gekoppeld

**Comment by HilbrandHurtak** [comment]
Heb dit nummer aan Rik doorgegeven. Hij kan dan zelf de relatie leggen. De werkgroep IB heeft nog wat aanvullingen op de nieuwe user story. Gezien het issue van Victor(virusscanner was nog niet klaar met de bijlagen) heb ik de huidige werking(enkelzijdig informatieobject) opnieuw getest. Mail met bijlagen worden netjes als. msg bestand toegevoegd en kan via outlook weer worden geopend.

**Comment by HilbrandHurtak** [comment]
Voor uitwerking meervoudige informatieobjecten verwijs ik naar #2501
