### ISSUE TITLE
Verzenden Mail + in Taak hetzelfde als in het documentenoverzicht, qua Bestandsomvang en pictogram van type document zien

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#2387]
***Als*** 
Behandelaar

***Wil ik*** 
Verzenden Mail hetzelfde als in het documentenoverzicht, qua Bestandsomvang en pictogram van type document zien
(zie #2168 voor documentenoverzicht qua Bestandsomvang)

***Zodat*** 
Ik overal in ZAC hetzelfde zie bij een document.
Dus ook bij document bij uitzetten Taak en die in een uitgezette Taak getoond wordt. 

***

### Acceptance criteria:
Overal Bestandsomvang + Pictogram bij een document getoond

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement KM, RV& RB

Dit is opgeleverd via een ander issue. Deze wordt als duplicaat gesloten.
