### ISSUE TITLE
Gerelateerde documenten van koppelzaak inzien werkt niet meer

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2394]
Documenten van hoofdzaak bij gerelateerde zaak en andersom werkt niet meer (schuifje).

**Comment by HilbrandHurtak** [comment]
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/e2361326-c4b0-4c92-8c1e-58f400ef25df)

**Comment by robertverboom** [comment]
Graag hertesten, let op mocht de relatie ivm zaaktyperelaties enkelvoudig gelegd zijn, dan worden de documenten ook enkelvoudig gezet.
