### ISSUE TITLE
BUG: Bij het verplaatsen van documenten wordt niet gecontroleerd op documenttype en ontstaat er een 500 foutmelding

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2399]
Als je een document gaat verplaatsen naar een andere zaak waar het desbetreffende documenttype niet aanwezig is krijg je een foutmelding 500.

Voorbeeld op de acc
![image](https://user-images.githubusercontent.com/96229645/224959770-e00eb3cd-905f-4cd1-8b59-c82e6869ec34.png)

Documenttype Aanvraagdocument komt niet voor bij zaaktype Bezwaar

Icoontje voor verplaatsing wordt wel blauw
![image](https://user-images.githubusercontent.com/96229645/224960197-963dcf87-14aa-43c8-b835-d988a25b66f9.png)

Na het klikken op het icoontje krijg je deze foutmelding
![image](https://user-images.githubusercontent.com/96229645/224960585-06be72be-0424-4b85-925f-6bcac61c1792.png)

Oorzaak Documenttype komt niet voor bij de te koppelen zaak

**Comment by HilbrandHurtak** [comment]
Zie ook #2373

**Comment by RoyBuis** [comment]
### Refinement 2-5

Dit kan niet gereproduceerd worden. Er treedt in dit scenario een melding uit Open zaak op waarin staat dat documenttype en zaaktype niet aan elkaar gerelateerd zijn.
Als de fout nog steeds optreedt dan graag nieuw scenario beschrijven

**Comment by RoyBuis** [comment]
Heeft relatie met #2504

**Comment by robertverboom** [comment]
Graag hertesten met nieuw document

**Comment by HilbrandHurtak** [comment]
Probleem blijft bestaan. Als je een document wilt verplaatsen naar een zaaktype waar het documenttype niet is geconfigureerd krijg je dus een 500 foutmelding ipv een nette foutmelding dat dit documenttype niet bij het zaaktype is geconfigureerd.
Eigenlijk zou je niet eens het document moeten kunnen verplaatsen.

Getest bij zaaktype bezwaar door een document van het type "aanvraagdocument" bij een bestaande zaak te verplaatsen naar een zaak van het type "bezwaar"

**Comment by HilbrandHurtak** [comment]
@RoyBuis scenario opnieuw getest en beschreven.

**Comment by HilbrandHurtak** [comment]
Bug is nog aanwezig en kan eenvoudig worden gereproduceerd. Daarom ticket verschoven naar acceptatie bug kolom

**Comment by robertverboom** [comment]
De 400 moet afgehandeld worden zoals wij bedacht hadden

**Comment by HilbrandHurtak** [comment]
@robertverboom Graag informatieobjecttype koppelen aan het zaaktype in OZ zodat we dit kunnen gaan hertesten

**Comment by robertverboom** [comment]
de knop wordt disabled bij het verplaatsen als het documenttype niet beschikbaar is bij de zaak (titel op de knop geeft aan waarom)

**Comment by robertverboom** [comment]
Op Accept heeft melding klein evenement wel documenttype 'aanvraagdocument' en bezwaar indienen niet.

**Comment by robertverboom** [comment]
@HilbrandHurtak ticket #2557 loopt nog

**Comment by HilbrandHurtak** [comment]
Mooie oplossing. Test OK. Zag knopje disabled +melding via mouse over
