### ISSUE TITLE
BUG: Werkvoorraad-zaken kan niet geopend worden door 500 error

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2401]
***Steps to reproduce:***

1. Log in op Accept omgeving als gebruiker die de fout ervaart
2. Open Werkvoorraad-zaken
3. 

***Expected***
Werkvoorraad-zaken wordt geopend

***Actual***
500 error met melding 'RESTEASY008200: JSON Binding deserialization error: javax.json.bind.JsonbException: Unable to deserialize property 'filters' because of: Unable to deserialize property 'ZAAK_STATUS' because of: Can't deserialize JSON array into: class net.atos.zac.zoeken.model.FilterParameters
javax.ws.rs.ProcessingException: RESTEASY008200: JSON Binding deserialization error: javax.json.bind.JsonbException: Unable to deserialize property 'filters' because of: Unable to deserialize property 'ZAAK_STATUS' because of: Can't deserialize JSON array into: class net.atos.zac.zoeken.model.FilterParameters'

**Comment by RoyBuis** [comment]
shell script voor toegang accept database maken

**Comment by andyverberne** [comment]
Graag aangeven hoe de fout gereproduceerd kan worden.

**Comment by RoyBuis** [comment]
Is opgelost door bewaarde zoekopdracht van 2 gebruikers uit database te verwijderen
