### ISSUE TITLE
Tech Debt: Skeleton Loader

### ISSUE THREAD

**Issue by jeroen-dekker** [NL-AMS-LOCGOV/zaakafhandelcomponent#2403]
Uit uitzoekwerk tijdens #2382 blijkt dat de Skeleton Loader op een aantal verschillende manieren wordt gebruikt in het ZAC (zie bijvoorbeeld `zaak-documenten.component`, `bedrijfsgegevens.component`). Ook zitten er wat ongebruikte parameters in de Skeleton Loader, en zit de `showLoader`-pipe logica complex in elkaar. Volgens mij kan dit simpeler en in &eacute;&eacute;n lijn getrokken worden. Voor dit issue moet er een refactorslag worden gemaakt om dat te bereiken.

**Comment by RoyBuis** [comment]
### Refinement 4-4
Skeleton loader zit nu alleen op initiator blok en documentenoverzicht. Besloten om deze er nu uit te halen. Op deze plekken komt een tekst 'wordt geladen' tot de inhoud er is.

Bij het open en dicht klappen van het initiator blok een animatie toeveogen. Gebruik maken van 'detail expand' net zoals document preview

**Comment by robertverboom** [comment]
test ok
