### ISSUE TITLE
BUG: Heropende zaak staat bij Afgehandelde zaken

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#2407]
***Steps to reproduce:***

Getest in:  https://zac.accept-public-service-platform.net/zaken/afgehandeld 

1. Menu Zaken>Afgehandelde Zaken
2. In het overzicht staat een zaak met de indicatie 'Is heropend'
3. 

***Expected***
Een heropende zaak zou (weer) getoond moeten worden in het overzicht 'Zaken werkvoorraad' omdat het na heropenen niet meer de status en resultaat 'Afgehandeld' heeft.

***Actual***
Heropende zaak wordt getoond in overzicht van afgehandelde zaken

Schermprint toegevoegd.![heropende zaak.jpg](https://images.zenhubusercontent.com/6215f444b107d1655b3e98b3/890be4a3-894e-4054-ac73-352fa45d79b8)

**Comment by RoyBuis** [comment]
### Refinement KM, SN, RV & RB

@Renvooi Dit komt waarschijnlijk door verouderde data. Als je dit test met een nieuwe zaak dan zou dit goed moeten werken en zou de zaak in de juiste werklijst voor moeten komen.

**Comment by Renvooi** [comment]
Hertest gedaan met https://zac.accept-public-service-platform.net/zaken/ZAAK-2023-0000000094
zaakheropend. Komt nu niet als heropende zaak niet meer voor in overzicht van afgehandelde zaken.
Na test de zaak weer afgehandeld. Zaak is nu wel weer zichtbaar in Afgehandelde zaken
