### ISSUE TITLE
BUG: Vanuit de zaak > Document verzenden. Overlay incompleet

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#2408]
***Steps to reproduce:***
Getest in Zaak https://zac.accept-public-service-platform.net/zaken/ZAAK-2023-0000000033

1. Open een zaak waarin documenten aanwezig zijn
2. Kies in het actiemenu de optie 'Document verzenden'
3. Overlay wordt getoond 

***Expected***
Zaakdocumenten worden getoond en kunnen voor verzending geselecteerd worden

***Actual***
Geen van de 'Expected' is aanwezig in de overlay. 

Schermprint:![document verzenden.jpg](https://images.zenhubusercontent.com/6215f444b107d1655b3e98b3/7b59f8be-d3fe-4610-871c-b7e9bf63cd92)

**Comment by robertverboom** [comment]
@Renvooi Graag opnieuw testen met de volgende criteria: 

- Alleen definitieve documenten
- Mag geen ontvangstdatum hebben
- Alleen van type PDF &PDF/a 
- Mag niet vertrouwelijkheidsaanduiding ‘Geheim, Zeer geheim, Confidentieel’ hebben
- Grootte van de documenten weergeven in overzicht
- Verzenddatumveld tonen. Default datum van vandaag maar is aanpasbaar

(Loesje koopkracht is een png bestand en geen pdf)

**Comment by HilbrandHurtak** [comment]
Deze combi zou niet mogen (1e versie was docx en 2e versie een pdf)
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/f56afb30-0db9-450b-b554-35ecf3ff3ba2)

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV

@HilbrandHurtak We hebben dit gerprobeerd te reproduceren op acc maar dat lukt niet. Bij converteren van een docx wordt een PDF gemaakt. Zou je dit nog eens willen testen en als het fout gaat beschijven welk scenario je volgt?

**Comment by HilbrandHurtak** [comment]
@RoyBuis In dit scenario gaat het fout.

ZAAK-2023-0000000093
DOCUMENT-2023-0000000120 toegevoegd met status definitief
Converteren gaat goed

DOCUMENT-2023-0000000122 toegevoegd met status In bewerking
Nieuwe versie toegevoegd met exact dezelfde naam maar status definitief
Converteren gaat goed

DOCUMENT-2023-0000000126 toegevoegd met status in bewerking
Nieuwe versie toegevoegd met andere bestandsnaam en status Definitief
![image](https://user-images.githubusercontent.com/96229645/234578372-d79c8267-a070-49aa-ad32-854fa2fe9bcc.png)

Daarna onder exact dezelfde naam een 2e versie toegevoegd en een pdf van gemaakt. dat ging toen goed.

**Comment by RoyBuis** [comment]
### Refinement KM, RV& RB

Opgelost via #2504. Moet nog getest worden.

**Comment by robertverboom** [comment]
graag hertesten

**Comment by KarinMasselink** [comment]
@HilbrandHurtak gaat over wat jij als laatst hebt aangekaart en niet zozeer wat René als eerst heeft ingediend.

**Comment by HilbrandHurtak** [comment]
Onderdeel nieuwe versie toevoegen met gewijzigde bestandnaam en status+PDF heb ik opnieuw getest:
Zandbak: Test OK
Acc: Test OK

**Comment by HilbrandHurtak** [comment]
**Verzenden via Taak**(rekening houdende met de voorwaarden t.a.v. de verzending)
Gedeelte van Rene ook op de acc getest. 
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/902ec5b7-ea2b-4527-9917-ec373267feec)

**Verzenden via functie**
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/752dc5fc-5a75-4d13-9876-4b6287a2e1fc)

**TEST OK**
