### ISSUE TITLE
BUG: Toon documenten van gerelateerde zaken. Schuifje aanzetten toont documenten niet

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#2409]
***Steps to reproduce:***
Heeft relatie met opgeleverde functie uit #2072  (pipeline Userstories tot test) en #2394

Getest in 
hoofdzaak: https://zac.accept-public-service-platform.net/zaken/ZAAK-2023-0000000048
deelzaak   : https://zac.accept-public-service-platform.net/zaken/ZAAK-2023-0000000053

1. Open de hoofdzaak. Je ziet bij deze zaak 1 document
2. Open de deelzaak. Deze bevat geen documenten. 
3. Activeer in de deelzaak het schuifje 'Toon documenten van gerelateerde zaken'

***Expected***
In de deelzaak wordt het document wat zich in de hoofdzaak bevindt getoond

***Actual***
In de deelzaak wordt het document wat zich in de hoofdzaak bevindt niet getoond
(ook niet na verversen van het browserscherm)

**Comment by RoyBuis** [comment]
### Refinement KM, SN, RV & RB

Dit wordt opgelost via #2394. Deze sluiten we als duplicaat

**Comment by HilbrandHurtak** [comment]
Zie uitgevoerde test onder issue #2394
