### ISSUE TITLE
BUG: Filtering van Ontkoppelde documenten op Creatie datum geeft niet altijd juiste resultaat.

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#2410]
***Steps to reproduce:***

1. Werklijst - Ontkoppelde documenten (in ZAC Accept)
2. Creatiedatum - datumrange 1-10-2022 t/m 31-10-2022
3. Geen resultaten, terwijl er toch 1 document is met Creatiedatum 10-10-2022 (komend uit zaak ZAAK-2023-0000000055)

***Expected***
Ontkoppelde documenten tonen die qua datumrange van Creatiedatum er binnen vallen.

***Actual***
Ontkoppeld Document met creatiedatum 10‑10‑2022 niet te vinden binnen de range 1-10 t/m 31-10-2022
Ontkoppelde Documenten van augustus 2022 wel te vinden (3 stuks bij range 1-8-2022 t/m 31-08-2022 

Tijdens testen #1114 tegengekomen

**Comment by hansmarks** [comment]
Ik kan het lokaal niet reproduceren, zoals Ronnie al vermoedde. Even hertesten?

**Comment by robertverboom** [comment]
@VictorTielenius Graag hertesten

**Comment by VictorTielenius** [comment]
Hertest: Nu wel resultaten met datumrange 1-10-2022 t/m 31-10-2022 0f 1-10-2022 t/m 1-10-2022: Akkoord
