### ISSUE TITLE
BUG: Document in afgehandelde zaak toevoegen, dan moet document altijd de Status Definitief krijgen.

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#2422]
***Steps to reproduce:***

1. Document in afgehandelde zaak toevoegen, maar ook mogelijk met Documentstatus In bewerking. Zou alleen status Definitief moeten zijn bij een afgehandelde zaak. Bij Toe voegen document zou automatisch de documentstatus op Definitief moeten gezet worden en niet te wijzigen zijn.

***Expected***
documentstatus op Definitief aangeboden moeten worden bij een afgehandelde zaak

***Actual***
Alle documentstatussen te kiezen

**Comment by RoyBuis** [comment]
### Refinement KM, SN, RV & RB

Deze heeft mogelijk relatie met een nieuwe user story over het wijzigen van een definitief document door een recordmanager. Deze wordt nog door de WG Informatiebeheer uitgewerkt.

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV

WG Refinement geeft aan dat dit gerealiseerd kan worden. Aan een beeindigde zaak mogen alleen documenten met status definitief worden toegevoegd

**Comment by RoyBuis** [comment]
### Refinement 2-5

Te realiseren

- Bij toevoegen document staat de status default op definititief en kan niet gewijzigd worden door gebruiker
- Veld is vooringevuld en disabled

**Comment by robertverboom** [comment]
test ok. let wel op dat een recordmanager een nieuwe versie van het document mag toevoegen en dus daar wel de status aanpassen.

**Comment by HilbrandHurtak** [comment]
Getest op ACC met mijn eigen account(met alle rechten denk ik). Kon een document (alleen optie definitief) bij een reeds afgesloten zaak toevoegen. 
Daarna getest met het account van zaakcoordinator. Optie toevoegen/wijzigen documenten werd niet getoond. Kon dus geen documenten toevoegen of wijzigen.

TEST OK
