### ISSUE TITLE
BAG-objecten aan zaak toevoegen deel 2

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2425]
***Als*** behandelaar

***Wil ik*** bij het toevoegen van BAG-objecten aan een zaak het scherm duidelijk kunnen sluiten

***Zodat*** 

***

### Acceptance criteria:
-

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Via #2249 is toevoegen van een BAG-object gerealiseerd. In deze user story is de UI van deze functionaliteit verbeterd door het scherm voor het zoeken en toevoegen van de BAG-objecten duidelijker te maken.
***Belangrijkste functionaliteiten:***
- Gebruiker ziet aan de titel bovenin het zoek- en toevoegenscherm waar dit scherm voor bedoeld is 
- Gebruiker kan het zoek- en toevoegenscherm sluiten door op het kruisje bovenin te klikken

**Comment by robertverboom** [comment]
test ok
