### ISSUE TITLE
BUG: Wijzigen locatie bij zaak is mogelijk zonder daarbij een reden vast te leggen

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2427]
Bij het testen van #1501 bleek dit het enige veld te zijn waarbij je een wijziging kunt aanbrengen zonder dat er een reden wordt vastgelegd. Ook het wijzigen via een Potlood icoon is hier niet doorgevoerd(bij de overige te wijzigen items wel)

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/6b91aee5-e6c7-45d3-bea7-935be422affb)
Na wijziging van de locatie is de historie wel bijgewerkt maar reden is leeg
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/b7819abf-2d0c-493e-8249-908dbb63df7c)

**Comment by RoyBuis** [comment]
### Refinement 11-4

Reden veld toevoegen
Opslaan en verwijderen knoppen naar onderen verplaatsen

**Comment by hansmarks** [comment]
Het toevoegen van de verplichte Reden is meegenomen in #2434, waarin ook de locatie is omgezet van "alleen mogelijk op gevonden adressen" naar "elk willekeurig coordinaat" (vanuit de gedachte dat adressen beter middels BAG gekoppeld kunnen worden).

Het gevraagde potloodje is echter iets waar we nog even over moeten praten in een refinement:

Het punt is namelijk dat we dat icoontje gebruiken om aan te geven dat er ergens een inline edit mogelijkheid is. En dit kan natuurlijk nooit inline worden, daar is domweg geen ruimte voor. Dus gebruiken we een side panel, zowel voor het bekijken als voor het bewerken van de locatie. Alleen is die mogelijkheid er niet als je geen bewerkrechten hebt. Dus dan kun je de locatie ook niet (op de kaart) bekijken. Waarschijnlijk moet het side panel dus een readonly modus krijgen zodat ook gebruikers die geen bewerkrechten hebben (om wat voor reden dan ook) de locatie nog wel kunnen bekijken.

Verder zou je kunnen overwegen om het openen van het side panel (wat nu gebeurt door een klik op het locatie-icoontje) te doen met een entry in het linker menu, zoals we dat ook doen met andere side panels. Gebruikers zouden dan misschien minder moeite kunnen hebben om het te vinden.

En/of we passen de huidige presentatie nog wat aan zodat ie meer lijkt op wat er gebeurt bij de potloodjes (klein icoon en extra groter icoon dat verschijnt bij een hover). Maar het potlood zelf zou ik willen reserveren voor inline edit mogelijkheden en dat zal dit uiteraard nooit kunnen zijn (daarvoor heeft het teveel ruimte nodig).

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Test ok

Locatie kan worden gewijzigd. Wijzigingen met reden staan in historie
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/47ff5143-f53c-42ac-a509-6c486cb3b971)

Of het veld reden verplicht moet zijn wordt onderzocht (geldt voor alle "reden"velden)
