### ISSUE TITLE
BUG: Koppeling met open-forms op de zandbak werkt niet correct

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2429]
***Steps to reproduce:***

1. Ga naar open-forms van de zandbak
2. maak een formulier aan met indienen klacht en rond af. 
3. Ga naar de zac van de zandbak
4. controleer in de werklijst of er een zaak van het zaaktype indienen-klacht is aangemaakt, waar een pdf document van het formulier aan hangt

***Expected***
Er wordt 1 zaak aangemaakt, waar het aangemaakt formulier in zit. 

***Actual***
Er wordt een inboxdocument aan gemaakt, waar een pdf met het formulier aan hangt. Er wordt 4x een zaak aangemaakt met het zaaktype, waar geen formulier in zit. 
Status van de 4 zaken worden ook niet gezet.

**Comment by robertverboom** [comment]
Op develop werkt dit wel naar behoren!

**Comment by andyverberne** [comment]
Er wordt een zaak correct aangemaakt. Deze zaak kan echter niet geopend worden door bug. Deze treed ook op in develop

**Comment by robertverboom** [comment]
Afhandeling wanneer het zaaktype in O-Z niet het informatieobjecttype bevat die nodig is voor aanmaken vaan zaken vanuit O-F. 

Reproduceren op develop omgeving: 
1 Ga naar open beheer formulieren > ga naar een formulier die je wilt gebruiken, onder de tab Registratie vul je een productaanvraagtype. 
2. ga naar de ZAP van de ZAC en vul bij zaaktype mke vervolg hetzelfde productaanvraag type. 
3. Open de log
4. ga naar open formulier en vul betreffende formulier in. 
expected: 
er wordt 1 zaak aangemaakt en 1 productaanvraag. Omdat 'mke vervolg' niet een aanvraagdocument als informatieobjecttype in OpenZaak heeft, zal er geen koppeling plaatsvinden. Wordt ook in de logging gemeld
Actual
Foutlogging is niet duidelijk en er worden 6 zaken aangemaakt, omdat hij het opnieuw probeert

**Comment by HilbrandHurtak** [comment]
@robertverboom Getest met een open forms (klachten). Aanvraag zonder bijlage maakt nu een zaak aan met aanvraagformulier als document. Open forms(klachten) met daarin een bijlage maakt **geen** zaak aan. Aanvraag komt in de inbox documenten en de meegeleverde bijlage is verdwenen
