### ISSUE TITLE
BUG: Vertrouwelijkheidaanduiding op niveau en niet op alfabet 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2435]
***Steps to reproduce:***

1. Ga naar een zaakpagina of documentpagina
2. Ga naar een select van vertrouwelijkheidaanduiding
3. 

***Expected***
niveau wat Open Zaak aangeeft wat de mate is van vertrouwelijkheid van een zaak/document

***Actual***
wordt nu op alfabet getoond: 
![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/a359e9b3-12a1-42fa-8055-8434adc18285)

**Comment by robertverboom** [comment]
### Refinement 20-04
- Op Document (versie bewerken) en op Zaak

**Comment by Sevdiya** [comment]
Wat is de bedoeling? @robertverboom 
Issue zoals beschreven klopt, vertrouwelijkheidsaanduiding staat op ABC
