### ISSUE TITLE
Mail met bijlagen gelijktijdig  als afzonderlijke documenten aan de zaak toevoegen via het drag en drop principe

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2437]
***Als*** Behandelaar

***Wil ik*** De door mij toegevoegde email bestanden (.msg) bestanden **met bijlagen** als afzonderlijke documenten bij het ZAC kunnen bewaren waarbij deze wel aan elkaar gerelateerd blijven

***Zodat*** Elke bijlage kan worden voorzien van de juiste metadata en er wordt voldaan aan de NEN-ISO 16175-1 eisen 

***

### Acceptance criteria:
- Toevoegen mail vanuit email voorziening door drag en drop blijft gehandhaafd (gerealiseerd in 2385)
- De mail en de bijlagen worden als afzonderlijke documenten bij de zaak opgeslagen
- De mail en de bijlagen dienen van de juiste metadata te kunnen worden voorzien 
- De relatie tussen de toegevoegde mail en de bijlagen blijft zichtbaar
***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #2385 is de functionaliteit van het slepen van e-mail (msg bestanden) naar het ZAC/toevoegen documenten gerealiseerd. De mail inclusief de bijlagens worden nu als 1 bestand toegevoegd .

Volgens de NEN-ISO 16175-1 eisen moeten de mail en de bijlagen apart van metadata kunnen worden voorzien en aan elkaar gerelateerd kunnen worden. Hoe dit gebeurt is aan de applicatie,

***Belangrijkste functionaliteiten:***
-  Bestaande functionaliteit (drag & drop bij bestanden) blijft bestaan
-  Het toevoegen van e-mail **met bijlage** vanuit een e-mail voorziening(Outlook) levert afzonderlijke documenten op bij de zaak
- De afzonderlijke documenten kunnen van de juiste metadata worden voorzien
- De relatie tussen de mail en de bijlagen blijft behouden

**Comment by RoyBuis** [comment]
### Refinement KM, RV& RB

Deze is door de wg Informatiebeheer beschreven in #2501
