### ISSUE TITLE
Toelichting in taakgegevens mag worden verwijderd

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2441]
***Als*** Behandelaar

***Wil ik*** de toelichting van de taak weg hebben

***Zodat*** er maar 1 toelichting/opmerking veld op taakbewerk scherm is. 

***

### Acceptance criteria:
- NB: Bij Zoeken op 'Taak toelichting' ook verwijderen
![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/629764c7-01f4-4060-a3e9-fbe8f1748c49)

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze user story is het toelichting veld bij taken aangepast. In de oude situatie had iedere taak een vast toelichting veld bij de taakgegevens waar naar eigen wens een toelichting gegeven kon worden. Daarnaast bevatte veel taken ook in het taakscherm een toelichtingveld wat voor onduidelijkheid kan zorgen. 
In de nieuwe situatie hebben alle taken alleen nog een vast toelichting veld in het taakscherm. Dit veld wordt ook bij alle taken gemapt op het 'opmerking' veld dat bij alle taken in het takenoverzicht aanwezig is.   

***Belangrijkste functionaliteiten:***
- Gebruiker kan in alle taken een toelichting invullen in het daarvoor bestemde vast veld
- Gebruiker kan in het takenoverzicht bij een zaak de ingevulde toelichting zien door de taak open te klappen met het pijltje en onder het opmerking kopje te kijken

**Comment by robertverboom** [comment]
Gaat om dit scherm: ![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/674b4eaf-7ae2-4f18-a7fd-932b006ba8dc)

**Comment by robertverboom** [comment]
### Refinement 06-04
- Taak toelichting uit blok verkorte taakgegevens verwijderen
- In alle taakformulieren opmerking/toelichting velden verwijderen
- in alle taakformulieren een standaard veld toelichting veld toevoegen wat gebaseerd is op de description van flowable. (zie fatale datum op taakformulier aanvullende informatie)
- taakinformatie mapping op zaakgegevenspagina moet aangepast worden aan het nieuwe toelichting veld

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Veld toelichting is verdwenen uit verkort taakscherm

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/f341c32d-a7bf-4ca4-8fe8-42dc5d47f634)
