### ISSUE TITLE
Indicaties toevoegen op documentlijstcomponent

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2442]
***Als*** Behandelaar

***Wil ik*** in de documentenlijst component de indicaties zien

***Zodat*** ik bijvoorbeeld kan zien welk document verstuurd of vergrendeld is als ik iets per post/mail wil versturen

***

### Acceptance criteria:
-

***
### Prioriteit
- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze story is de lijst van documenten dat beschikbaar is bij bijvoorbeeld het versturen van een e-mail uitgebreid door in deze lijst ook eventuele indicaties zoals 'is ondertekend' bij de documenten te tonen.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in de functionaliteiten waarbij een lijst van documenten wordt gebruikt zien of een document een indicatie heeft
-

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/244aea32-76f3-4a94-b050-394d9634d609)

Documenten worden met indicatie getoond
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/5cdb2f19-1219-4603-bdbf-f7ed5acafa9a)

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/4cadca3e-7c23-4f66-9805-c671eac34bd9)


Test OK
