### ISSUE TITLE
optie om locatie toe te voegen bij aanmaken zaak mag worden verwijderd 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2444]
***Als*** Behandelaar

***Wil ik*** tijdens het aanmaken van een nieuwe zaak geen locatie kiezen

***Zodat*** ik geen verwarring heb met het toevoegen van BAG objecten. 

***

### Acceptance criteria:
-

***
### Prioriteit
- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze story is de optie om in het 'Zaak aanmaken' scherm een locatie aan een zaak toe te voegen verwijderd. Deze functie is nu alleen beschikbaar bij een bestaande zaak. 

***Belangrijkste functionaliteiten:***
Niet van toepassing

**Comment by robertverboom** [comment]
test ok

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Getest op zandbak ivm problemen op acc

Bij aanmaken van nieuwe zaak kan ik geen locatie meer toevoegen- Akkoord
Nadat de zaak is aangemaakt kan ik weer een locatie koppelen obv coördinaten door een punt in de kaart te selecteren- Akkoord
