### ISSUE TITLE
Productaanvragen verwijderen 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2446]
***Als*** DIV? 

***Wil ik*** in de werkvoorraad productaanvragen een productaanvraag verwijderen 

***Zodat*** ik verkeerde productaanvragen kan opruimen 

***

### Acceptance criteria:
- Voor nu krijgt recordmanager alleen dit recht

***
### Prioriteit
- Should haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #319 is er een Inbox productaanvragen aan de ZAC toegevoegd waarin productaanvragen komen die niet tot een zaak hebben geleid omdat er geen match was op productaanvraagtype met één van zaaktypen die in zaps zijn ingericht.
Met deze story is het ook mogelijk om een productaanvraag uit de Inbox productaanvragen te verwijderen. 

***Belangrijkste functionaliteiten:***
- Gebruiker kan de productaanvraag verwijderen door in de regel van de productaanvraag te klikken op het prullenbak icoon

**Comment by robertverboom** [comment]
### Refinement 06-04

- Recht voor het verwijderen van productaanvraag moet apart van recht voor verwijderen van inbox document
- Documenten en productaanvragen blijven bestaan

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Test OK
