### ISSUE TITLE
BUG: Afhandeling wanneer het zaaktype in O-Z niet het informatieobjecttype bevat die nodig is voor aanmaken van zaken vanuit O-F.

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2449]
Reproduceren op develop omgeving:
1 Ga naar open beheer formulieren > ga naar een formulier die je wilt gebruiken, onder de tab Registratie vul je een productaanvraagtype.

2 ga naar de ZAP van de ZAC en vul bij zaaktype mke vervolg hetzelfde productaanvraag type.
3 Open de log
4 ga naar open formulier en vul betreffende formulier in.
**Expected**
er wordt 1 zaak aangemaakt en 1 productaanvraag. Omdat 'mke vervolg' niet een aanvraagdocument als informatieobjecttype in OpenZaak heeft, zal er geen koppeling plaatsvinden. Wordt ook in de logging gemeld
**Actual**
Foutlogging is niet duidelijk en er worden 6 zaken aangemaakt, omdat hij het opnieuw probeert

**Comment by robertverboom** [comment]
#2429

**Comment by RoyBuis** [comment]
### Refinement 18-4

- Fout reproduceren door productaanvraagtype van een fomulier te koppelen van zaaktype 'mke bijdrage' (deze heeft namelijk niet aanvraagdocument als infomatieobjecttype gekoppeld)
- (400) Title: Invalid input., Detail: Name: nonFieldErrors, Code: missing-zaaktype-informatieobjecttype-relation, Reason: Het informatieobjecttype hoort niet bij het zaaktype van de zaak.
- Foutboodschap moet correct gelogd worden
- Er moet geen retry plaatsvinden
