### ISSUE TITLE
Zoeken personen front end bijwerken

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#2451]
Er kan alleen gezocht worden op specifieke combinaties van velden.  Deze mogelijke combinaties moeten op een of andere manier verwerkt worden in de front end logica,

**Comment by hansmarks** [comment]
De "eigen" gemeente-code is op dit moment nog hard gecodeerd. Dat zal uiteraard nog configureerbaar moeten worden via de startup parameters.

**Comment by HilbrandHurtak** [comment]
Test personen: https://www.rvig.nl/brp/documenten/richtlijnen/2018/09/20/testdataset-persoonslijsten-proefomgevingen-gba-v

**Comment by HilbrandHurtak** [comment]
@hansmarks kun jij deze vraag beantwoorden?
Wel vraag ik me af waarom je niet alleen op geslachtsnaam kan zoeken (dit kan nu ook in het MP) en dit altijd op combinatie van een aantal velden moet. (Sommige buitenlandse namen zijn zo specifiek daar vind je er niet veel van).

**Comment by KarinMasselink** [comment]
@HilbrandHurtak  @yboers Hans geeft in een comment hierboven ook aan dat de zoekeisen zijn van de API, op basis daarvan gaat die zoeken. De combivelden worden dus niet door Atos bedacht maar door Haal Centraal. 

De waarom kan dus alleen beantwoorden met het antwoord omdat de API dat zoekveld vereist.

**Comment by HilbrandHurtak** [comment]
Gezien het antwoord sluit ik dit issue. 

Wel is het lastig, nadat er geen gegevens zijn gevonden en je de volledige zoekcombinatie hebt ingevuld, om een nieuwe zoekingang te kiezen. Je moet eerst alle zoekvelden leegmaken en kunt dan pas een nieuwe zoekingang selecteren. Hiervoor heb ik een issue #2537 aangemaakt. Ik laat het aan @KarinMasselink om dit nu nog op te pakken
