### ISSUE TITLE
BUG: Mail slepen vanuit Outlook naar ZAC Accept: Bijlage (PDF) niet te openen en plaatje in handtekening niet getoond.

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#2455]
***Steps to reproduce:***

1. Mail gesleept vanuit Outlook en aan Zaak toegevoegd (ZAAK-2023-0000000076); De bijlage in de mail is hier niet te openen. ("ATP-scan wordt uitgevoerd" staat op plek van bijlage) Ook plaatje in ondertekening niet getoond.

***Expected***
Wel mail incl. bijlage en plaatje in handtekening tonen. In deze zaak ook een mail (test #2377 opgeslagen) eerst opgeslagen op schijf en toen in Zaak gezet. Deze wel de bijlage en plaatje getoond. Beide zijn zelfde mails.

***Actual***
De bijlage in de mail is hier niet te openen. ("ATP-scan wordt uitgevoerd" staat op plek van bijlage) Ook plaatje in ondertekening niet getoond.

**Comment by VictorTielenius** [comment]
Nogmaals getest en nu komt mail incl. PDF bijlage goed over bij slepen. Ook plaatje in mail nu zichtbaar.
Lag aan dat ik de mail net naar mezelf had gestuurd  en vrij snel na binnenkomst had gesleept naar ZAC Accept en de bijlage nog werd gescand op virussen door onze techniek. 
Dit Bug user story kaartje mag gesloten worden.

**Comment by KarinMasselink** [comment]
@robertverboom ik wilde hem al sluiten maar zie dat jij er nog een milestone aangekoppeld hebt maar volgens mij mag die dicht? Wil je dit even nakijken?

**Comment by robertverboom** [comment]
Lukt hier ook, ik sluit het ticket
