### ISSUE TITLE
Inzicht in wie een taak behandelt en heeft afgerond

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#246]
***Als*** behandelaar

***Wil ik*** van een taak zien op wiens naam deze staat en als deze is afgerond welke behandelaar deze taak heeft afgerond

***Zodat*** ik inzicht heb wie bezig is met een taak en wie een taak heeft afgerond

***

### Acceptance criteria:
- Behandelaar moet duidelijk kunnen zien welke behandelaar een taak in behandeling heeft of heeft behandeld
- Systeem toont voor- en achternaam van de behandelaar
***
### Prioriteit

- [ ] Must haves

**Comment by GertrudeKampherbeek** [comment]
wel een commentaar toevoegen

**Comment by JosDimpact** [comment]
Een comment is mogelijk

**Comment by RoyBuis** [comment]
Refinement 24-1:
Functioneel: Bij het afronden van de taak moet het systeem de gebruiker vastleggen die de taak heeft afgerond en in de 'behandelaar' kolom van de taak tonen.
Technisch: het gaat om de assignee. Die moet je claimen en zo nodig unclaimen

**Comment by robertverboom** [comment]
test ok
