### ISSUE TITLE
bijlagen open-forms niet op te halen van het file-systeem

### ISSUE THREAD

**Issue by ronniekoopmans-atos** [NL-AMS-LOCGOV/zaakafhandelcomponent#2465]
2023-04-14 11:49:15 CEST] (Inzending 411): Registratieplugin "Objecten API registratie" (objects_api) meldt: Registratie mislukt.
{"error": "[Errno 2] No such file or directory: '/app/private_media/submission-uploads/2023/04/14/4a6032ec-ae62-4c3b-8ac0-79bcc822c142.txt'", "log_event": "registration_failure", "plugin_id": "objects_api", "plugin_label": "Objecten API registratie"}

Fout lijkt te zitten in open-formulieren configuratie (cluster?) het opslaan van pdf (gegenereerd in plaats van opgeslagen het filesysteem) wordt wel goed opgeslagen in document-registraties.

ook het downloaden van een bijlage gaat fout.
http://open-forms.default/admin/submissions/submissionfileattachment/

**Comment by andyverberne** [comment]
Ingevuld formulier 'melding-klein-evenement' met 1 bijlage resulteerd in de volgende instantie van Productaanvraag in Object Registraties:

{code}
{
  'data': {
    'mijn-gegevens': {
      'voornamen': '',
      'achternaam': '',
      'emailadres': 'andy.verberne@atos.net',
      'telefoonnummer': ''
    },
    'mijn-evenement': {
      'file': [
        {
          'url': 'https://open-forms.develop-public-service-platform.net/api/v2/submissions/files/430d5a24-0a9d-4297-b8f2-39f7d4b0647b',
          'data': {
            'url': 'https://open-forms.develop-public-service-platform.net/api/v2/submissions/files/430d5a24-0a9d-4297-b8f2-39f7d4b0647b',
            'form': '',
            'name': 'Test Bestand.doc',
            'size': 24064,
            'baseUrl': 'https://open-forms.develop-public-service-platform.net/api/v2/',
            'project': ''
          },
          'name': 'Test Bestand-8a66cf91-6532-4b6a-8eac-a4030fc75db5.doc',
          'size': 24064,
          'type': 'application/msword',
          'storage': 'url',
          'originalName': 'Test Bestand.doc'
        }
      ],
      'naamEvenement': 'Test Andy met bijlage',
      'datumEvenement': '2023-04-24',
      'omschrijvingEvenement': 'Test Andy met bijlage',
      'verwachtAantalDeelnemers': 1
    }
  },
  'type': 'melding-klein-evenement',
  'pdf_url': 'http://open-zaak-nginx.default/documenten/api/v1/enkelvoudiginformatieobjecten/a34aa025-edae-4aea-8ae3-a9f9a5716c99',
  'attachments': [
    'http://open-zaak-nginx.default/documenten/api/v1/enkelvoudiginformatieobjecten/48feaaaa-cac7-44b8-a5d2-3cddd6ad2138'
  ],
  'language_code': 'nl',
  'submission_id': 'a15c8d0d-24b1-495b-88f4-b414aff7ab69'
}
{code}
