### ISSUE TITLE
BUG: Downloaden van Productaanvragen op werkvoorraad geeft foutmelding 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2468]
***Steps to reproduce:***

1. Ga naar werkvoorraad van productaanvragen
2. Download productaanvraag
3. 

***Expected***
Wordt gedownload

***Actual***
Server response from ZGW Api's implementation: 500 (Internal Server Error)"

**Comment by andyverberne** [comment]
Dit bleek om corrupte data te gaan. De betreffende productaanvragen zijn verwijderd.
