### ISSUE TITLE
Tonen van gegevens van de locatie

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2471]
***Als*** Behandelaar

***Wil ik*** iets anders zien dan de coordinaten van de locatie, wellicht het dichtstbijzijnde adres

***Zodat*** ik in 1 oogopslag om welke locatie het gaat 

***

### Acceptance criteria:
- Op het kaartje zelf een background toevoegen bij de opmerking: 'dichtstbijzijnde adres'

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 18-4

Besloten om dit nu niet aan te passen en te wachten op feedback van de gebruikers
