### ISSUE TITLE
Locatie wijzigen en weergeven

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2474]
***Als*** behandelaar

***Wil ik*** een locatie kunnen vastleggen, wijzigen en bekijken

***Zodat*** ik daarvoor een duidelijke werkwijze heb

***

### Acceptance criteria:
-

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze user story is de UI bij het vastleggen van een locatie bij een zaak aangepast. In de oude situatie werd na het kiezen van een locatie het dichtsbijzijnde adres getoond bij de zaakgegevens, in de nieuwe situatie worden hier de coordinaten van de gekozen locatie getoond omdat dat de daadwerkelijk gekozen locatie is. Het dichtsbijzijnde adres kan alsnog bekeken worden door de vastgelegde locatie weer te openen. 
Verder is het duidelijk gemaakt dat de locatie is vast te leggen of wijzigen door bij dit veld, net als bij de andere zaakgegevensvelden, het potlood icoon te gebruiken. Bij een beëindigde zaak verandert het potlood in een locatie icoon waarmee de kaart met de vastgelegde locatie als read-only geopend kan worden.  
In de nieuwe situatie is bij het vastleggen van een locatie een reden veld beschikbaar dat verplicht ingevuld moet worden, deze reden wordt gebruikt in de zaakhistorie.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het zaakgegevensscherm een locatie vastleggen of wijzigen door op het potlood icoon te klikken
- Gebruiker kan als alternatieve werkwijze om een locatie vast te leggen of wijzigen met de muisaanwijzer over het locatieveld zweven en op het locatie icoon klikken
- Gebruiker moet bij het vastleggen of wijzigen van de locatie verplicht een reden invullen
- Gebruiker kan de bij het vastleggen ingevulde reden inzien in de zaakhistorie

**Comment by RoyBuis** [comment]
### Refinement 18-4

- Locatie veld gedraagd zich zoals een inline edit control
- Read-only modus waarbij ook het panel read-only wordt geopend. Dit is van toepassing bij een beeindigde zaak en een gebruiker die geen wijzigen rechten voor de locatie heeft

**Comment by robertverboom** [comment]
test ok
