### ISSUE TITLE
BUG: Ophalen uit VNG referentielijsten werkt niet

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#2477]
In de log staat meerdere malen:

{code}
09:43:22,791 INFO  [org.apache.http.impl.execchain.RetryExec] (default task-18) I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://vng-referentielijsten.default:80: The target server failed to respond
09:43:22,791 INFO  [org.apache.http.impl.execchain.RetryExec] (default task-18) Retrying request to {}->http://vng-referentielijsten.default:80
{code}

**Comment by robertverboom** [comment]
Voor de ZAC is het nu opgelost.
