### ISSUE TITLE
BUG: Behandelaarrecht mag documenten niet verzenden

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2479]
***Steps to reproduce:***

1. Login met een recordmanager (waarschijnlijk eigen account)
2. Maak een pdf document aan met status definitief op een zaak (bijv https://zac.develop-public-service-platform.net/zaken/ZAAK-2023-0000000322 )
 - controleer of deze bij document verzenden zichtbaar is
3. Login met een beheerder 
4. ga naar de betreffende zaak
controleer of je dit document mag verzenden (via taak of zelf)

***Expected***
Een behandelaar mag dit document ook verzenden 

***Actual***
Policy is niet correct. Behandelaar mag dit document niet verzenden.

**Comment by Sevdiya** [comment]
Ik kan dit onderdeel niet testen omdat ik geen RM ben. Hebben we een RM account waar we gebruik van kunnen maken om dit onderdeel te testen? @robertverboom

**Comment by robertverboom** [comment]
test  ok

**Comment by Sevdiya** [comment]
@robertverboom Aanmaken van een document is helaas niet mogelijk. (ben je als user geregistreerd in SmartDocuments?)
Mag ik RM rechten in ZAC AO en SmartDocuments
