### ISSUE TITLE
Bug: Vergrendelen document toegevoegd op taak geeft foutmelding

### ISSUE THREAD

**Issue by marcoatos** [NL-AMS-LOCGOV/zaakafhandelcomponent#2488]
Een document vergrendelen welke toegevoegd is op een taak geeft een nullpointer foutmelding:
java.lang.NullPointerException: RESTEASY004690: Parameter annotated with PathParam cannot be null

Steps to reproduce:
1. Start een zaak
2. Start een aanvullende informatie taak
3. Voeg op de taak een document toe
4. Ga naar dat document en probeer deze te vergrendelen.

**Comment by Sevdiya** [comment]
De onderstaande stappen zijn doorlopen: 
Start een zaak
Start een aanvullende informatie taak / taak advies intern aangemaakt
Voeg op de taak een document toe / done
Ga naar dat document en probeer deze te vergrendelen. done

Het werkt. zaak 100 / https://zac.accept-public-service-platform.net/zaken/ZAAK-2023-0000000100

**Comment by robertverboom** [comment]
test ok
