### ISSUE TITLE
BUG: verkeerde waarden bij facet zoeken

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#2489]
***Steps to reproduce:***

1. Open de Zandbak of Acceptatie omgeving
2. Open de zoekfunctie en vul een trefwoord in
3. Bekijk de facetten aan de linkerkant

***Expected***
Alle facetten hebben waarden die voor de gebruiker begrijpelijk zijn

***Actual***
Enkele facetten hebben verkeerde waarden, zie bij voorbeeld bij de velden 'Zaak vertrouwelijkaanduiding' en 'Zaak archief nominatie'

**Comment by robertverboom** [comment]
Oplossing: omgevingen moeten geherindexeerd worden

**Comment by Sevdiya** [comment]
@robertverboom zijn de omgevingen al geherindexeerd zodat we deze issue kunnen testen?

**Comment by yboers** [comment]
Wat mij opvalt is, dat de keuzes de ene keer met een hoofdletter worden geschreven en de andere keer met kleine letters. Misschien kan dit recht getrokken worden en de keuzes allemaal met hoofdletter schrijven.

**Comment by RoyBuis** [comment]
> Wat mij opvalt is, dat de keuzes de ene keer met een hoofdletter worden geschreven en de andere keer met kleine letters. Misschien kan dit recht getrokken worden en de keuzes allemaal met hoofdletter schrijven.

Dit is een kwestie van inrichting. Je ziet nu bijvoorbeeld de documenttypen in kleine letters omdat die ook met kleine letters zijn ingericht in Open zaak

**Comment by hansmarks** [comment]
Is het de bedoeling dat deze open staat? Ik zie niet meteen, als ik dit lees, wat er moet gebeuren...

**Comment by RoyBuis** [comment]
> Is het de bedoeling dat deze open staat? Ik zie niet meteen, als ik dit lees, wat er moet gebeuren...

ja, dit speelt nog op de Zandbak en Accept. Als je een zoekopdracht bovenin doet en dan kijkt naar de facetten van bijvoorbeeld 'Zaak vertrouwelijkheidsaanduiding' dan wordt als waarde 'vertrouwelijkheidaanduiding.openbaar' getoond in plaats van 'openbaar'

**Comment by hansmarks** [comment]
Het moet vertrouwelijkheidaanduiding.OPENBAAR zijn en niet vertrouwelijkheidaanduiding.openbaar, dan krijg je namelijk de "vertaling" Openbaar te zien.

De facetten komen uit Solr, daarin worden die waarden redundant opgeslagen in indexen. In de code kom het in kleine letters niet tegen. Dus ik denk dat hier het antwoord op de vraag van Sevdiya relevant is. ;-)

**Comment by hansmarks** [comment]
De URL is .../rest/indexeren/herindexeren/ZAAK

**Comment by RoyBuis** [comment]
herindexering op de Zandbak heeft het issue niet opgelost, niet geprobeerd op Accept.

**Comment by robertverboom** [comment]
Graag hertesten

**Comment by yboers** [comment]
Issue getest op acceptatie . De juiste facetwaarden worden weergegeven.
Helaas heb ik geen rechten op github om het label van bug aan te passen.
Wil iemand anders het label aanpassen?

**Comment by HilbrandHurtak** [comment]
@yboers Zag dat het label nu weg was. Kan het issue worden afgesloten?

**Comment by HilbrandHurtak** [comment]
Test OK
