### ISSUE TITLE
BUG: Documenten kunnen niet verplaatst worden naar verschillende zaaktypes

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#2492]

**Comment by CommonGroundGroningen** [comment]
Het verplaatsen van documenten van het zaaktype 'melding klein evenement' naar 'bezwaar indienen' levert een foutpagina met code 500 op.

**Comment by RoyBuis** [comment]
### Refinement KM, RB en RV
Dit issue is bekend, wordt besproken via #2399
