### ISSUE TITLE
Zandbak: Foutmelding bij toevoegen nieuwe versie documenten en converteren naar PDF

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2503]
Bij toevoegen van een nieuwe versie van een document met bijvoorbeeld een andere naam geeft de volgende foutmelding.
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/2ced4919-adc9-4f15-b5d0-c1df1790bb46)

Het toevoegen van een nieuwe versie van een document met exact dezelfde naam maar een andere status gaat wel goed.

Van de 2e versie een pdf maken via de functie Converteren geeft weer een foutmelding

Foutmelding
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/2d61e710-8828-4e0f-91aa-b8d79ab29a43)

Niet kunnen testen op ACC ivm 500 foutmeldingen bij openen zaak of toevoegen zaak

**Comment by HilbrandHurtak** [comment]
Getest om de acc. 
Het toevoegen van een nieuwe versie van een document met exact dezelfde naam maar een andere status gaat wel goed. Van de 2e versie een pdf maken via de functie Converteren gaat wel goed.

Zodra er een afwijkende naam bij een nieuwe versie wordt gebruikt komt er een 500 foutmelding

Foutmelding uitvoering beschreven op basis van verzoek @RoyBuis 

Tevens hertest uitgevoerd op zandbak. 2e versie met exact dezelfde naam en converteren gaat nu goed. (vanochtend niet tijdens een demo voor de testers) 

Conclusie. Toevoegen van een nieuwe versie met een afwijkende bestandsnaam veroorzaakt een foutmelding

**Comment by Sevdiya** [comment]
Getest in de AO ZAC
1. nieuwe versie toevoegen werkt
2. nieuwe versie vervangen door een ander bestand / werkt niet, @HilbrandHurtak is dit wat je bedoeld? 
3. Converteren naar PDF / werkt. het was een Excel bestand en is nu een PDF. 
4. Eenmaal geconverteerd naar PDF kan je de versie niet meer wijzigen/bewerken @RoyBuis

**Comment by HilbrandHurtak** [comment]
@RoyBuis dat is inderdaad wat ik bedoel

**Comment by Sevdiya** [comment]
Document vervangen door een ander document werkt. Dit getest in Zac AO zaak ZAAK-2023-0000000100
