### ISSUE TITLE
zaakafhendelcomponent #1473 functionaliteit niet opgeleverd

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#2515]
De volgende functionaliteit kan niet worden getest:
**Gebruiker wordt bij het afhandelen van de zaak met een resultaat waar in vastligt dat de ingangs- of vervaldatum wordt gebruikt om de brondatum te berekenen dan wordt de gebruiker doorgestuurd naar het besluitpanel om deze alsnog vast te leggen.**

**Comment by CommonGroundGroningen** [comment]
Resultaten waarbij de brondatum wordt berekend op basis van de ingangs- of vervaldatum is niet ingericht bij de nu beschikbare zaaktypes.
De term brondatum is ook niet duidelijk.

**Comment by robertverboom** [comment]
@KarinMasselink @CommonGroundGroningen 

Het zaaktype 'Melding klein evenement' heeft 2 resultaattype erbij gekregen: 
1. Verleend Omgeving  (selectielijstklasse 11.1.12 archiefactietermijn van 1 jaar) > Hierbij is de ingangsdatum van een besluit verplicht en met deze ingangsdatum wordt gerekend (berekening doet OZ) Brondatum == ingangsdatum besluit
2. Verleend leegstand (selectielijstklasse 11.1.15 archiefactietermijn van 5 jaren) > Hierbij is de vervaldatum van een besluit verplicht en met deze vervaldatum wordt gerekend. (berekening doet OZ) Brondatum == vervaldatum besluit

**Comment by CommonGroundGroningen** [comment]
De resultaten "Verleend omgeving" en "Verleend leegstand" kunnen alleen via een besluit worden gegeven. De vernietigingsdatum wordt berekend op basis van de datum in het besluit.
Test OK
