### ISSUE TITLE
BUG: Wanneer we zoeken op Personen staat de BSN in de URL 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2517]
Is het gewenst om de bsn in de URL te zetten als we zoeken op een persoon: https://zac.accept-public-service-platform.net/persoon/999993872

**Comment by hansmarks** [comment]
Lijkt me handig. Wat is volgens jou het probleem?

**Comment by hansmarks** [comment]
Aangezien we HTTPS gebruiken, is de URL bij het verzenden over het netwerk/internet versleuteld. Alleen de domeinnaam van de webserver is voor een meekijkende man in the middle te zien. Dus dat BSN-nummer is daar keurig beveiligd. Uiteraard kunnen we het verplaatsen naar de body van het request. Maar daar wordt het niet veiliger van. Je verstopt het dan alleen wat meer. (Security by obscurity.)

En op zich is het natuurlijk ook gewoon handig voor de gebruiker om op deze manier een persoon te kunnen opvragen. Wel moet dan de autorisatie om die persoonsgegevens te mogen zien op de detail-pagina zelf daadwerkelijk gecontroleerd worden, zodat het niet mogelijk is om een ontbrekende autorisatie te omzeilen door de URL aan te passen. (Testen dat dit het geval is!)
