### ISSUE TITLE
Wis alles knop op zoeken persoon/bedrijf

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2518]
***Als*** Behandelaar

***Wil ik*** een wis alle velden knop wanneer ik zoek op een bedrijf of persoon

***Zodat*** eenvoudig een nieuwe zoekactie kan uitvoeren, zonder eerst bij elk veld langs te gaan om deze leeg te maken
***

### Acceptance criteria:
- op de volgende panels zoeken, initiator toevoegen en bij betrokkene 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves
- Should haves
- Could haves
- Won't haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Knop wissen is toegevoegd voor zoeken personen en bedrijven. Knop getest en werkt. Test OK

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/6769e6e3-8473-4b2b-bdeb-92e049a6d5b3)
