### ISSUE TITLE
6B.7.4 Gegevens aanvrager (bedrijf) tonen bij geopende zaak (zaakoverzichtscherm)

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#252]
***Als*** zaakbehandelaar

***Wil ik*** de gegevens van de aanvrager/indiener/melder (bedrijf) bij een geopende zaak kunnen zien 

***Zodat*** ik weet in een oog opslag weet wie de aanvrager is, de zaak goed kan behandelen en kan communiceren over de behandeling/afhandeling van de zaak indien nodig

***

### Acceptance criteria:
-	Als MVP onderstaande gegevens tonen op het zaakoverzicht scherm (gelijk aan e-Suite):
o	Naam aanvrager/indiener/melder (volledige naam bedrijf)
o	Vestigingsnummer
o	Vestigingsdatum
o	Inschrijfadres
o	Correspondentieadres
o	Telefoonnummer
o	Telefoonnummer 2e
o	Faxnummer
o	E-mailadres
-	De getoonde gegevens moeten uit de bron komen (NHR?).
-	Rechten en autorisatie rondom persoonsgegevens tonen/kunnen inzien volgen later (andere story)

### Prioriteit

- [ ] Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Op de zaakgegevenspagina is in het linker menu een knop gekomen om een bedrijf als initiator toe te voegen. Vervolgens komt er een zoekfunctionaliteit om het juiste bedrijf te selecteren. 

***Belangrijkste functionaliteiten:***
- De KVK API is de bron voor bedrijfsgegevens.
- Er wordt gebruik gemaakt van de test API van de KVK. Met handelsnaam: 'Test' kunnen verschillende bedrijfen gevonden worden.
- Tonen van contactgegevens wordt (nog) niet getoond. 
- Het is mogelijk om een initiator te verwijderen, om een nieuwe initiator toe te voegen

**Comment by robertverboom** [comment]
informatie tijdelijk even uit objectregistratie halen ipv Haal Centraal. Wellicht even met mouse-over vermelden.

**Comment by RoyBuis** [comment]
Refinement:

- Beginnen met deze story, net al voor personen.
- Dummy inlog eHerkenning op Open Formulieren, zo bedrijf als initiator koppelen aan zaak in ZAC
- Bedrijf op zelfde plek als persoon tonen
- Te tonen gegevens afhankelijk van API, staan beschreven op https://developers.kvk.nl/nl/apis/zoeken bij de factsheet
- Specs van de API zie hier: https://developers.kvk.nl/nl/apis/zoeken/swagger
- Uitzoeken of tel nr en email via Klanten API zijn op te halen, geen onderdeel van deze story, dit wordt een aparte story voor aangehaakte gegevens

**Comment by Hugo-ter-Doest** [comment]
De KVK API's zijn inderdaad de bron voor bedrijfsgegevens. Ik krijg wel een melding "Vanaf 1 april kun je de API's Search en Profile niet meer gebruiken. [Stap over op onze nieuwe API's](https://developers.kvk.nl/nl/support/switch-to-new-apis)."

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Zaak aanmaken met Initiator Bedrijf. Bedrijf getoond na aanmaken Zaak?
Initiator verwijderen. Weg bij zaak, en in Historie?
Weer een bedrijf koppelen bij zaak. Lukt dit + staat dit in Historie?

Zaak in ZAC test aangemaakt met initiator Bedrijf: ZAAK-2022-0000000028
Verwijderen + opnieuw koppelen:  Alleen Vestigingsnummer bij Historie te zien, Is dit voldoende?

**Comment by VictorTielenius** [comment]
Acceptatie Bug #1020 opgelost.
Acceptance criteria: voldoet voor nu en rest van functionaliteiten volgt
