### ISSUE TITLE
BUG: Kampen: mail vanuit zac naar externen werkt niet

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#2520]
Als ik een e-mail wil versturen vanuit zac komt deze niet aan bij de ontvanger. Ik heb mails verzonden naar mijn Kampen mail en ook een naar mijn privémail, maar geen van deze mails zijn aangekomen. Wacht nu al een paar uur....

Het betreft alle mail, dus b.v. ook als er een ontvangstbevestiging wordt verzonden of een verzoek om meer informatie wordt gevraagd.

Kan dit gefixt worden?

**Comment by robertverboom** [comment]
@IreneYolande wellicht wordt de mailserver geblokkeerd bij jullie. Graag hertesten naar een ander mailaccount.

**Comment by robertverboom** [comment]
@IreneYolande Gebruik je bij de afzender jouw eigen mail adres? Althans die van kampen, deze wordt geblokkeerd door onze mailJet wat betekend dat ze niet verstuurd worden. Wanneer de omgeving bij jouw eigen gemeente is ingericht, kan deze functionaliteit pas gebruikt worden. Voor nu kan je alleen mailtjes versturen met een afzender die eindigen met ...@develop/zandbak-public-service-platform.net.

Bij het zaaktype van Kampen heb ik voor het gemak een default afzender gekozen. Dit kan je inrichten bij instellingen > zaakafhandel-parameters > Zaaktype van kampen: Aanvragen evenementenvergunning beoordelen > doorklikken naar het 4e punt; Mailgegevens

**Comment by IreneYolande** [comment]
@robertverboom het lukt nu wel inderdaad. Dank!

**Comment by KarinMasselink** [comment]
@IreneYolande als het gelukt is wil je dit ticket dan weer sluiten?
