### ISSUE TITLE
Kampen: Communicatiekanaal toevoegen?

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#2521]
**Gemeentenaam**: 
Kampen

**Vraag**
Wat houdt communicatiekanaal Morse code in? Zie afbeelding. Voelt een beetje als een grapje :-) 
![Knipsel](https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/assets/119419731/eb15fd96-d148-4c8d-bedc-effa5ecbb93d)

**Toevoegen communicatiekanaal**
Bij de e-suite is er een communicatiekanaal dat 'Medewerkersportaal' heet, misschien ook voor zac een idee? Met name handig als een zaak door een interne trigger wordt gestart ipv een externe trigger als mail, brief, telefoon etc. Dat is bij bedrijfsvoering vaak het geval namelijk...

**Comment by robertverboom** [comment]
@IreneYolande Morese code was destijds inderdaad een grapje. Deze communicatiekanalen kunnen middels het component VNG referentielijsten ingericht worden.
