### ISSUE TITLE
BUG: Kampen: zaakdata wijzigen werkt niet

### ISSUE THREAD

**Issue by IreneYolande** [NL-AMS-LOCGOV/zaakafhandelcomponent#2523]
De optie om zaakdata te wijzigen werkt niet. 
![Knipsel](https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/assets/119419731/9e60ff6e-bba6-4de4-8005-e19fb7e859d4)

Als ik deze open dan krijg ik een wit vlak, waar ik niks kan. 
![Knipsel](https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/assets/119419731/7112a790-943d-4706-8315-925ea7f240c1)

In principe kun je in een open zaak al heel wat wijzigen, behalve zaaktype en registratiedatum. Bij een afgesloten zaak kun je minder wijzigen, maar werkt de optie ook niet. Dus weet ook niet waarvoor de optie zaakdata wijzigen er is. Dus of fix de bug of haal de optie weg, lijkt me...

**Comment by KarinMasselink** [comment]
@IreneYolande dit issue wordt al opgelost gaat om formulier data en het inzien. Zie ook #2439
