### ISSUE TITLE
BUG: Hoofdzaak afronden geeft policy exception

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2530]
***Steps to reproduce:***

1. Koppel een zaak aan een andere zaak (melding klein evenementen met bijv melding klein eveenmenten)
2. Probeer de hoofdzaak af te ronden
3. 

***Expected***
Nette foutmelding: Hoofdzaak mag je niet afronden, omdat er nog een deelzaak open staat 

***Actual***
Er wordt een policy exception getoond.

**Comment by robertverboom** [comment]
Voorbeeld zaak: https://zac.develop-public-service-platform.net/zaken/ZAAK-2023-0000000418

**Comment by robertverboom** [comment]
Speelt nog met zaak afbreken: 

Koppel 2 zaken aan elkaar, breek de hoofdzaak af. 

Verwachting is dat dit niet mag, met nette foutmelding, omdat er nog deelzaken aan gekoppeld zijn. 

Daadwerkelijk krijg je een policy exception.

**Comment by andyverberne** [comment]
Deze is opgelost via #2558

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Getest onder ##895/ Test OK
