### ISSUE TITLE
ACCEPTATIE BUG: Zoeken op foutief BSN geeft een 500 foutmelding ipv een nette melding

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2534]
Sinds kort kan er weer een persoon aan een zaak worden gekoppeld(Als initiator of betrokkene). Het ingeven van een foutief BSN genereert een 500 foutmelding.

Dit is te testen door bijvoorbeeld een persoon als initiator of betrokkenen aan een zaak te gaan koppelen en dan bijvoorbeeld bij de zoekactie je geboortedatum in te voeren(ipv BSN) en vervolgens op zoek te klikken

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/70db1222-651f-43de-9ee1-3f5a1703fcea)

**Comment by KarinMasselink** [comment]
@robertverboom wil jij dit meenemen, is getest naar aanleiding van de zoeken van personen.

**Comment by RoyBuis** [comment]
@HilbrandHurtak Ik probeer dit testen op Accept zoals je omschrijft maar ik krijg het niet gereproduceerd.
Als ik zoek op een ongeldig bsn (bijv 900009628) dan krijg ik de melding 'Geen gegevens gevonden'

**Comment by HilbrandHurtak** [comment]
@RoyBuis Toets maar eens je geboortedatum in(in mijn geval 11031967). Ik krijg dan een 500 error terwijl er een melding zou moeten zijn dat dit geen geldig bsn is

**Comment by robertverboom** [comment]
Graag BSN validatie op betreffende veld.

**Comment by robertverboom** [comment]
Test ok
