### ISSUE TITLE
ACCEPTATIE BUG: Zoeken personen verbeteren door knop wissen zoekresultaat toe te voegen

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2537]
Je kunt personen zoeken via verschillende combinaties. Er ontbreekt een knop "wissen zoekresultaat" als je van zoekcombinatie wilt wijzigen. In de huidige e-Suite werk dit heel eenvoudig. In ZAC niet(kan na weghalen postcode en huisnummer geen andere zoekactie kiezen)

Voorbeeld (zoeken geeft geen resultaat. Vervolgens wil ik opnieuw gaan zoeken maar dan op BSN. Dat lukt dus niet. De velden blijven disabled

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/15f8e7f1-8435-4fb3-8561-fa7cae8bbd96)

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/a743a368-e9ea-442e-a969-6c8304412fca)

**Comment by HilbrandHurtak** [comment]
@KarinMasselink wil jij dit nog bespreken met Atos

**Comment by KarinMasselink** [comment]
@RoyBuis @robertverboom ook graag dit issue meenemen net als #2536 .

**Comment by robertverboom** [comment]
@KarinMasselink is een nieuwe functionaliteit en vergelijkbare story staat al op de refinement pipeline.

**Comment by KarinMasselink** [comment]
@robertverboom @HilbrandHurtak  ik sluit deze als duplicaat op basis van comment van Robert over dubbele US.
