### ISSUE TITLE
Hoofdzaak afhandelen als deelzaak nog openstaat resulteert in foutpagina

### ISSUE THREAD

**Issue by CommonGroundGroningen** [NL-AMS-LOCGOV/zaakafhandelcomponent#2539]
Gerelateerd aan #895.
Het afhandelen van een hoofdzaak kan niet als er een nog niet afgehandelde deelzaak is gekoppeld. Dit werkt in essentie maar resulteert in een foutpagina. Suggestie om de knop "zaak afhandelen" niet beschikbaar te maken of om een melding te geven op de zaakpagina als op de knop "zaak afhandelen" wordt geklikt en er nog een deelzaak open staat.

**Comment by KarinMasselink** [comment]
Deze is al gemeld via #2530 daarom sluit ik deze als duplicaat. Zal die ook even toevoegen aan de gelinkte US.
