### ISSUE TITLE
BUG: Bij Document toevoegen ontbreekt de markering Verplicht voor het veld Status

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#254]
![Toevoegen document - Status (verplicht)](https://user-images.githubusercontent.com/75383503/149529189-7564ec56-11ff-4bcb-8d56-52de3b216d2e.PNG)
***Steps to reproduce:***

1. Open een bestaande zaak
2. Selecteer de actie: Voeg een document toe

***Expected***
* Verwachting is dat het veld status als verplicht gemarkeerd staat

***Actual***
* Het veld status staat niet als verplicht gemarkeerd waardoor het niet mogelijk is documenten toe te voegen zonder dit veld te selecteren. Dit geeft verwarring bij medewerkers

**Comment by robertverboom** [comment]
test ok
