### ISSUE TITLE
BUG: Vertrouwelijkheidsniveau wordt niet overgenomen van OZ 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#2543]
***Steps to reproduce:***

1. maak een zaak aan, of voeg een document toe
2. bekijk vetrouwelijkheidsniveau
3. 

***Expected***
Deze wordt overgenomen wat in OZ is ingesteld

***Actual***
Deze is niet vooraf ingevuld

**Comment by hansmarks** [comment]
Ik kan het niet reproduceren. Volgens mij werkt het zoals je zou verwachten.
