### ISSUE TITLE
BUG: Functie afbreken zaak geeft 500 foutmelding bij afhandelen hoofdzaak met openstaande deelzaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#2565]
Ga 2 zaken aan elkaar relateren
Breek de hoofdzaak of deelzaak af via de menu functie Afbreken zaak
Foutmelding 500 komt in beeld

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/b95184ab-0567-4f9b-81fa-30ba79f9cd13)

Zaak is daarna ook niet meer te openen zonder 500 melding 

Ook het in behandeling nemen van de deelzaak geeft een 500 melding

In behandeling nemen van de hoofdzaak gaat wel goed.

Getest op de zandbak met zaaktype Vervolg en Kleine evenementen

Ook het in behandeling nemen van het zaaktype Vervolg geeft een foutmelding. 

Nog verder getest. Op de zandbak geeft ook bij Indienen klacht een 500 foutmelding bij het in behandeling nemen

Er lijkt dus iets anders aan de hand te zijn

**Comment by KarinMasselink** [comment]
@robertverboom wil je deze meenemen?

**Comment by robertverboom** [comment]
Dit is een duplicate met #2530. Wordt in ander issue opgelost.

**Comment by KarinMasselink** [comment]
@robertverboom @HilbrandHurtak prima doen we deze weer dicht. Heb #2530 nu gelinkt aan het issue waar dit een bug voor is.
