### ISSUE TITLE
Uitgebreid en complex formulier maken in Open formulieren

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#259]
Een formulier maken met zoveel mogelijk verschillende velden erin, zodat het zo complex mogelijk wordt. Zoveel mogelijk de mogelijkheden van Open Formulieren laten terugkomen.

Doel om daarna de data op te halen en te tonen in een 'overzicht' dat beschikbaar is bij de zaak en taak

**Comment by RoyBuis** [comment]
Formulier is afgerond en staat in Open formulieren development. 
Nog te doen:
Zorgen dat het formulier in Overige registraties komt. Bespreken met Andy en Marc
