### ISSUE TITLE
Knop beschikbaar maken naar overzicht met alle productaanvraaggegevens

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#260]
Juist plek voor deze knop bedenken, in zowel zaak als taak

**Comment by RoyBuis** [comment]
Eerst een spike ingeland voor 2 uur om mogelijkheden te bekijken. Daarna verder refinen met volledige team.

**Comment by robertverboom** [comment]
Oplossingsrichting: 
- Alle zaakacties worden net als 'initiator toevoegen' met rechter side nav getoond. Naast Mail versturen, Document toevoegen, dus ook 'Inzien start formulier'
- De paginering wordt gerealiseerd d.m.v. een verticale Stepper (zie zaakafhandelparameters). Afstand tussen de twee steps te verkleinen. 
- Wanneer de gebruiker 'buiten' de rechter side nav klikt, wordt de informatie van dat moment bewaard.
