### ISSUE TITLE
Autocomplete gebruiksvriendelijker maken 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#263]
- Inline edit  van groep en behandelaar moet vorige waarde tonen (zaakgegevens pagina)
- Na het selecteren, is het niet duidelijk dat de gebruiker het veld weer moet leegmaken, om nieuwe waarde te selecteren (verdelen velden) 
- verdelen zaken: autocomplete moet gelijk valideren, wanneer je bovenstaande velden wijzigt. nu zie je niet wat waarom je niet kan verdelen.

**Comment by robertverboom** [comment]
Ref 31-01: 
- De gekozen waarde neerzetten in het label. 
- Inputveld alleen als filter op de lijst gebruiken. 
- Opletten met het opslaan dat je de juiste waarde mee geeft. 
- 2e formcontrol in de autocomplete zetten: 1 voor de waarde en 1 voor het filter
- validator moet op de waarde komen te staan.

**Comment by hansmarks** [comment]
Het probleem met het hervalideren bij een andere groep heeft Ronnie in een ander ticket opgelost.

Ik heb ervoor gezorgd dat de inline edit variant van de auto complete. De oude waarde nog toont als je 'm opent. En als je dan meteen op OK klikt dan is die waarde ook valid (dat was voorheen het probleem waarom dat oude waarde meteen gewist werd). Verder kun je nu zien of je nog aan het zoeken bent of dat je al een waarde uit de lijst gekozen hebt (vergrootglaasje).

Ik denk dat ie zo een stuk vriendelijker is in het gebruik.

**Comment by robertverboom** [comment]
test ok
