### ISSUE TITLE
BUG: In edit mode blijft de vorige tekst staan na klikken op de Annuleer button voor de velden Toelichting en Omschrijving bij de zaak 

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#265]
***Steps to reproduce:***

1. Open een bestaande niet afgesloten zaak
2. Wijzig de omschrijving van de zaak
3. Klik op de button Annuleren
4. Open vervolgens opnieuw het veld Omschrijving 

***Expected***
De originele tekst in het veld omschrijving wordt getoond en niet de aangepaste omschrijving uit stap 2

***Actual***
De aangepaste tekst uit stap 2 wordt getoond

NB: soortgelijk speelt dit voor het veld Toelichting

**Comment by bartlukens-atos** [comment]
Bij het annuleren de originele waarde terug zetten

**Comment by robertverboom** [comment]
test ok
