### ISSUE TITLE
BUG: Annuleer knop ontbreekt bij bewerken van een notitie

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#272]
***Steps to reproduce:***

1. Open een lopende zaak
2. Klik op de knop Notities
3. Voeg een notitie toe
4. Klik op bewerken

***Expected***
Verwachting is dat de knoppen Opslaan en Annuleren getoond worden

***Actual***
Enkel de knop Opslaan wordt getoond, waardoor het niet mogelijk is de actie ongedaan te maken

**Comment by robertverboom** [comment]
test ok

**Comment by nl23727** [comment]
#C051 C051zaakPagina_notitieBewerkenBestaandeNotitieAnnuleren
