### ISSUE TITLE
BUG: Taken werklijsten geeft 500 error

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#274]
***Steps to reproduce:***

1. Ga naar taken werklijsten
2. 
3. 

***Expected***
je ziet werklijst van taken

***Actual***
je krijgt een 500 error

**Comment by bartlukens-atos** [comment]
Data corrigeren
Oppakken ook voor de variabele van #169

**Comment by robertverboom** [comment]
test ok
