### ISSUE TITLE
Diverse refreshes (als er websockets binnenkomen) werken niet.

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#28]
- [x] Websockets nalopen (vervolg https://jira.sdmc.ao-srv.com/browse/ESUITEDEV-25998)

**Comment by robertverboom** [comment]
Ik zag dat door een aantal aanpassingen die ik had gedaan de timeout van de load balancer weer terug was op 30 seconden.
Ik heb nu een oplossing gevonden dat dit nooit meer gebeurd. Het is niet meer nodig om de timeout na het aanpassen van de loadbalancer handmatig aan te passen. Dat gebeurd nu automagisch via een BackendConfig.

Kan het zijn dat hiermee dit websocket probleem is opgelost? Of ging dit ergens anders over?

**Comment by robertverboom** [comment]
Marks, Hans added a comment - 2021-11-24 03:43
Er was inderdaad een websocket probleem wat veroorzaakt werd doordat de load balancer een timeout had van 30 seconden waardoor de websockets niet werkten.

Maar dat is niet waar dit ticket over gaat. Het probleem is hier niet dat websockets niet doorkomen maar dat de afhandeling ervan (in de callback in Angular) her en der niet werkt. Er vindt geen daadwerkelijke refresh plaats als de callback wordt aangeroepen.

**Comment by hansmarks** [comment]
Commits:
https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/commit/961e049207e2f81bf719cc559420fec532a6c8f0
https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/commit/9661e642413cebee6445d0ea6c98e41e5c1b76bd

**Comment by hansmarks** [comment]
Toch de wildcards niet voldoende doorgedacht. ;-)

Hersteld en nette logging toegevoegd zodat de client side werking voorlopig even gemakkelijk gecontroleerd kan worden.

**Comment by ronniekoopmans-atos** [comment]
review ok

**Comment by robertverboom** [comment]
voor zover test ok
