### ISSUE TITLE
Op lokale omgeving ontvangen van notificaties

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#280]
Als developer wil ik op mijn lokale omgeving notificaties kunnen ontvangen welke worden verstuurd vanuit Open Notificatoes

**Comment by nl23727** [comment]
Niet testbaar door de testers. Doorgezet naar closed.

**Comment by andyverberne** [comment]
Signaleringen worden nu ook op lokale development omgeving aangemaakt. Dat is niet de bedoeling. De bijbehorende notificaties kunnen echter niet worden uitgefilterd door de notifications-router-local omdat dezelfde notificaties ook zorgen voor het triggeren van websockets en cache updates. De filtering moet daarom gebeuren in het zaakafhandelcomponent zelf
