### ISSUE TITLE
6B.13.1 Goedkeuring( mede goedkeuring) vragen en vastleggen bij een zaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#281]
***Als*** zaakbehandelaar

***Wil ik*** goedkeuringen (mede goedkeuringen) uitvragen bij interne collega's en vastleggen tijdens het behandelen van een zaak

***Zodat*** ik op basis van de ontvangen goedkeuring weer verder kan met de behandeling van de zaak

***

### Acceptance criteria:

- Het kunnen uitzetten van goedkeuringen bij collega’s die hiervoor de juiste rechten hebben binnen de procesafhandeling van het zaaktype   
- ~~Het kunnen bewaken van de voortgang van de goedkeuringen~~ Opnemen in algemene epic over taak voortgang bewaking
- Een tekstveld voor het stellen van de goedkeuringsvraag (verplicht) (aanmaken goedkeuring)
- Een tekstveld voor het beantwoorden van de goedkeuringsvraag (verplicht) (afhandelen goedkeuring)
- ~~Het kunnen uploaden van relevante documenten bij goedkeuringenvraag (aanmaken goedkeuring)~~
- Het kunnen selecteren van relevante documenten bij de goedkeuringsvraag (aanmaken goedkeuring)
- Het kunnen uploaden van een document bij de goedkeuring taak zelf (afhandelen goedkeuring)
- Het steeds opnieuw kunnen uitzetten van goedkeuringen 
- Het vastleggen van de goedkeuringen en de daarbij behorende documenten bij de zaakhistorie. Opmerking uit story voor advies vragen:  in huidige werking wordt voldoende historie vastgelegd, taken kunnen na het afronden ingezien worden

***
### Prioriteit

- Must haves

***
### Gerealiseerd
Wanneer een zaak in status behandeling zit, kunnen er onbeperkt Goedkeuring taken gestart worden. 
In de taakstart formulier kan:
- De vraag gesteld worden
- Documenten meegestuurd worden (Alleen documenten die aan de zaak gekoppeld zijn)
- Toegewezen worden aan een groep en medewerker. 

tijdens Goedkeuren behandel kan
- Goedgekeurd worden mbv bullet
- toelichting gegeven worden
- optioneel extra documenten toegevoegd worden. 
- taak afronden.

**Comment by Snijhuis** [comment]
Voorbeeld Goedkeuringstaak
![image](https://user-images.githubusercontent.com/75792697/151763849-34d2be28-7ccf-4b4c-8cca-7dacc14fcafa.png)
Voorbeeld Goedkeuringstaak

**Comment by Snijhuis** [comment]
Voorbeeld Aanmaken/uitvragen goedkeuring.
![image](https://user-images.githubusercontent.com/75792697/151764563-c4cf19a6-ce29-41be-91fa-35c5167f24d8.png)

**Comment by robertverboom** [comment]
- kopie maken van het adviesformulier
- 2 enum aanpassen (zit in de taakformulieren service)

**Comment by robertverboom** [comment]
test ok

**Comment by CommonGroundGroningen** [comment]
- [x] Het kunnen uitzetten van goedkeuringen bij collega’s die hiervoor de juiste rechten hebben binnen de procesafhandeling van het zaaktype
- [x] Opnemen in algemene epic over taak voortgang bewaking
- [x] Een tekstveld voor het stellen van de goedkeuringsvraag (verplicht) (aanmaken goedkeuring)
- [ ] Een tekstveld voor het beantwoorden van de goedkeuringsvraag (optioneel) (afhandelen goedkeuring)
1
- [x] Het kunnen selecteren van relevante documenten bij de goedkeuringsvraag (aanmaken goedkeuring)
- [ ] Het kunnen uploaden van een document bij de goedkeuring taak zelf (afhandelen goedkeuring)
2
- [ ] Het steeds opnieuw kunnen uitzetten van goedkeuringen
3
- [ ] Het vastleggen van de goedkeuringen en de daarbij behorende documenten bij de zaakhistorie.
4

**Comment by CommonGroundGroningen** [comment]
**Testgeval 1**
Aanmaken taak voor 'Goedkeuren'. Goedkeuring wordt gedaan zonder tekst.
**Verwachting**
- Goedkeuringsvraag moet opgegeven worden in daarvoor bedoeld tekstveld
- Taak wordt opgenomen in scherm voor voortgangsbewaking
- Tekst hoeft niet opgegeven te worden bij beantwoording
- Taak wordt aangemaakt
- Zaakhistorie wordt bijgewerkt
**Resultaat**

**Testgeval 2**
Aanmaken taak voor 'Goedkeuren'. Goedkeuring wordt gedaan met tekst.
**Verwachting**
- Goedkeuringsvraag moet opgegeven worden in daarvoor bedoeld tekstveld
- Taak wordt opgenomen in scherm voor voortgangsbewaking
- Tekst kan opgegeven worden bij beantwoording
- Taak wordt aangemaakt
- Zaakhistorie wordt bijgewerkt
**Resultaat**

**Testgeval 3**
Aanmaken taak voor 'Goedkeuren'. Bij vraag wordt document geselecteerd
**Verwachting**
- Goedkeuringsvraag moet opgegeven worden in daarvoor bedoeld tekstveld
- Taak wordt opgenomen in scherm voor voortgangsbewaking
- Testdocument kan geselecteerd worden bij goedkeuringsvraag
- Tekst hoeft niet opgegeven te worden bij beantwoording
- Taak wordt aangemaakt
- Zaakhistorie wordt bijgewerkt
**Resultaat**

**Testgeval 4**
Aanmaken taak voor 'Goedkeuren'. Bij antwoord wordt document geupload
**Verwachting**
- Goedkeuringsvraag moet opgegeven worden in daarvoor bedoeld tekstveld
- Taak wordt opgenomen in scherm voor voortgangsbewaking
- Tekst hoeft niet opgegeven te worden bij beantwoording
- Document kan geupload worden bij beantwoording
- Taak wordt aangemaakt
- Zaakhistorie wordt bijgewerkt
**Resultaat**

**Testgeval 5**
Na goedkeuring opnieuw aanmaken taak voor 'Goedkeuren'.
**Verwachting**
- Taak kan opnieuw aangemaakt worden
- Taak wordt opgenomen in scherm voor voortgangsbewaking
- Taak wordt aangemaakt
- Zaakhistorie wordt bijgewerkt
**Resultaat**

**Comment by CommonGroundGroningen** [comment]
Testresultaat:
- [ ] OK
- [x] NOK

**Comment by HilbrandHurtak** [comment]
Globaal opnieuw getest onder zaaknummer ZAAK-2022-0000000182:
-Kan ik een taak van het type goedkeuring aanmaken en toewijzen- OK
- Kan ik bijlagen toevoegen aan een goedkeuringstaak- OK
- Zie ik als behandelaar van de goedkeuringstaak ook de documenten die ik moet goedkeuren- OK
- Kan ik de taak goedkeuren en moet ik verplicht een toelichting geven- OK
- Kan ik zelf bij de taak ook een bijlage toevoegen- OK
- Komt het toegevoegd document ook in het dossier- OK
- Kan ik meerdere taken aanmaken - OK

Taak goedkeuring werkt dus OK.  Er is geen taak om alle uitgezette taken te bewaken maar dat was bekend
