### ISSUE TITLE
6B.16.1 Een resultaattype handmatig kunnen wijzigen tijdens het behandelen van een zaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#285]
***Als*** zaakbehandelaar

***Wil ik*** tijdens het afhandelproces een resultaattype kunnen wijzigen

***Zodat*** op basis daarvan het juiste resultaattype van de zaak kan worden aangeven

***

### Acceptance criteria:
•	Een resultaattype handmatig kunnen wijzigen
•	Het verplicht invullen van de reden van wijziging
•	De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Bij het vastleggen van een besluit kan de behandelaar ook het resultaat vastleggen. Als een behandelaar dit resultaat wil wijzigen tijdens de behandeling van de zaak dan kan dat door het besluit te wijzigen. Als bij een zaak geen besluit vastgelegd wordt dan kan de behandelaar bij het afhandelen van de zaak het resultaat vastleggen. Deze is daarna alleen nog maar te wijzigen door de zaak te heropenen.

***Belangrijkste functionaliteiten:***
- Bij het vastleggen besluit moet het resultaat gekozen worden. Het besluit, en daarmee ook het resultaat kan gewijzigd worden door op het potlood icoon te klikken

**Comment by RoyBuis** [comment]
User story verder werken, met name de 'zodat'.

**Comment by RoyBuis** [comment]
Via gelinkte stories wordt het mogelijk om bij het handmatig beeindigen van een zaak het resultaat te bepalen.

**Comment by RoyBuis** [comment]
Het ZAC werkt op basis van CMMN. Hierin wordt het resultaat altijd handmatig door de behandelaar bepaald. De behandelaar kan:

- de zaak afbreken, in dit geval kiest de behandelaar een reden waar een resultaat aan gekoppeld is.
- de zaak afhandelen, in dit geval kiest de behandelaar het resultaat waarmee de zaak wordt beeindigd


Deze story wordt opgelost door:
- story #169 
- story #809

**Comment by robertverboom** [comment]
### Refinement 12-07:

- Als recordmanager wil ik een document aan een gesloten zaak kunnen toevoegen, zonder de zaak te heropenen.

**Comment by CommonGroundGroningen** [comment]
**de zaak afbreken, in dit geval kiest de behandelaar een reden waar een resultaat aan gekoppeld is.**
Akkoord

**de zaak afhandelen, in dit geval kiest de behandelaar het resultaat waarmee de zaak wordt beeindigd**
Akkoord
