### ISSUE TITLE
6B.16.2 Een resultaattype via een procesflow automatisch kunnen wijzigen tijdens het behandelen van een zaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#286]
***Als*** zaakbehandelaar

***Wil ik*** tijdens het afhandelproces een resultaattype geautomatiseerd kunnen laten wijzigen zoals dat in de procesflow is bepaald

***Zodat*** op basis daarvan het juiste resultaattype volgens een van te voren gedefinieerd proces wordt ingevuld 

***

### Acceptance criteria:
•	Een resultaattype geautomatiseerd kunnen wijzigen door het volgen van een van te voren gedefinieerd proces 
•	De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Deze story is opgelost via stories #169 en #809. Het kiezen of wijzigen van het resultaat van de zaak wordt altijd via een actie gedaan en is geen onderdeel van het CMMN afhandelproces.

**Comment by RoyBuis** [comment]
Het ZAC werkt op basis van CMMN. Hierin wordt het resultaat altijd handmatig door de behandelaar bepaald. De behandelaar kan:


- de zaak afbreken, in dit geval kiest de behandelaar een reden waar een resultaat aan gekoppeld is.
- de zaak afhandelen, in dit geval kiest de behandelaar het resultaat waarmee de zaak wordt beeindigd

Deze story wordt opgelost door:

story https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/169
story https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/809
