### ISSUE TITLE
6B.17.1 Inzien en bewerken Algemene zaakgegevens

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#287]
***Als***  zaakbehandelaar

***Wil ik*** bij een zaak de algemene zaakgegevens kunnen bekijken en wijzigen 

***Zodat*** deze gegevens kunnen worden gecorrigeerd

***

### Acceptance criteria:
•	Het kunnen wijzigen van de algemene gegeven zoals kanaal, vertrouwelijkheidsaanduiding, omschrijving en toelichting ~~reden~~)
•	het kunnen wijzigen van status is beschreven in issue #283 
•	Het kunnen wijzigen van de startdatum, streefdatum en fatale datum 
•	De streefdatum en fatale datum mogen niet voor de startdatum liggen.
•	De fatale datum mag niet voor de streefdatum liggen
•	Reden van wijziging moet worden ingevuld
•	De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd 

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De zaakgegevens van een zaak, te vinden onder het tabblad Algemene gegevens, zijn door een gebruiker te bewerken. Alleen de gegevens die bewerkt mogen worden volgens Zaken API zijn in het ZAC aan te passen, bij het zaaknummer en het zaaktype van een zaak is dit bijvoorbeeld niet toegestaan.

***Belangrijkste functionaliteiten:***
- Met het potlood icoon wordt het veld bewerkbaar voor de gebruiker. De vink knop voert de bewerking door, annuleren kan met de X knop.
- De start- en termijndatums kunnen als geheel bewerkt worden door op het potlood van een van de velden te klikken. Er wordt hier validatie uitgevoerd op startdatum<streefdatum<fataledatum
- De gebruiker kan optioneel een reden voor de bewerking invullen
- De bewerkingen zijn in de historie, met de eventueel ingevulde reden, te zien

**Comment by RoyBuis** [comment]
Refinement:
Kanaal: url naar een referentielijst van VNG. Waar staat deze referentielijst, bij VNG? Bespreken met htD in architectuuroverleg. Voorlopig nog niet wijzigbaar te maken vanuit ZAC.
Vertr aanduiding: wijzigbaar maken
Omschrijving en toelichting: is al wijzigbaar, nog 'reden' veld toevoegen

Start-, streef- en fatale datum: 
- deze 3 velden groeperen en gezamenlijk wijzigbaar maken. Validatie uitvoeren op streef en fataal niet voor start em fataal niet voor streef en streef niet voor start
- andere logica, bijv automatisch doorrekenen streef en fataal, nog niet toepassen, bespreekt Sander met werkgroep en wordt mogelijk een aparte story

Einddatum: dit veld alleen tonen wanneer er einddatum gezet is

Reden wijziging: alle genoemde velden krijgen 'reden' veld op dezelfde manier als groep, optioneel invullen. Mogelijkheid meenemen om een redenveld verplicht te maken.

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
• Het kunnen wijzigen van de algemene gegeven zoals kanaal, vertrouwelijkheidsaanduiding, omschrijving en toelichting reden)
• het kunnen wijzigen van status is beschreven in issue #283
• Het kunnen wijzigen van de startdatum, streefdatum en fatale datum
• De streefdatum en fatale datum mogen niet voor de startdatum liggen.
• De fatale datum mag niet voor de streefdatum liggen
• Reden van wijziging moet worden ingevuld
• De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd (gebouwd: De gebruiker kan optioneel een reden voor de bewerking invullen)

Zie voor  Kanaal ook: #410 + #722

Getest met ZAAK-2022-0000000099 (en 98)
Wijzigen Vertrouwelijkheidaanduiding.
Wijzigen Groep: 2 items in Historie.
Wijzigen van de startdatum, streefdatum en fatale datum:  streefdatum niet in te geven? Startdatum + Fatale datum:  aanpasbaar maar houden geen rekening met elkaar. Fatale datum mag niet voor startdatum liggen.
Wijzigen van Omschrijving
Wijzigen van Toelichting
Locatie ook te wijzigen, via marker.

#in Werkgroep bespreken:
Reden is niet verplicht
Zaaktype niet te wijzigen. Komt hier een mogelijkheid voor zoals nu knop Wijzigen Zaaktype (dmv recht, muv bij formulier) 
Aantal velden in bij aanmaken zaak niet verplicht (de 4 velden bij Overige gegevens)
Registratiedatum ook in verleden te kiezen bij aanmaken, later ook niet te wijzigen in de zaak.

**Comment by JosDimpact** [comment]
Besproken in de werkgroep:
- Verplichting van een reden is wel gewenst om de traceerbaarheid goed te houden. Zal vrijwel zeker ook een eis van informatiebeheer zijn.
- TBV historie vastleggen: Oude waarde, nieuwe waarde, whodunnit, timestamp, reden vd wijziging.
- Zaaktype wijzigen kan/mag niet. Open zaak biedt de mogelijkheid op dit moment gewoonweg niet. Dit kunnen we uitsluitend aanpakken als we een wijziging indienen bij de ontwikkeling van open zaak. Gertrude geeft hier een goede user story voor geschreven (#1497) voor het ontwikkelteam van open zaak, mede ook met een goede 'zodat ik...' want we willen dit wel kunnen wijzigen, dit zal namelijk anders voor veel vervuiling zorgen. We hebben dit niet voor niets ook gewijzigd aan de huidige eSuite (Zie wijziging 165 ook voor de redenen/aanleidingen)
- Over die vier velden bij overige gegevens: Communicatiekanaal - moet wel verplicht zijn; Vertrouwelijkheidsaanduiding - Zou eigenlijk beantwoord moeten worden door de werkgroep privacy en security. Wij kunnen hooguit een aanname doen. Paskal vraagt het na bij een collega; Omschrijving - is de basis vd metadata, moet wel verplicht; Toelichting - niet verplicht (Jos maakt een issue aan)
- Registratiedatum - zal altijd 'nu' (het moment van vastleggen) moeten zijn en moet niet te wijzigen zijn. nb: De startdatum van het proces moet wel in het verleden kunnen liggen. (Jos maakt een issue aan)
- Groep bij aanmaken zaak, is inderdaad ingericht bij zaaktype. Deze moet wel ingevuld kunnen worden en wijzigbaar zijn (issue).
- Geen afdeling, alleen groep: is een semantische keuze om een willekeurige organisatorische eenheid aan te geven. Is hooguit in relatie tot de huidige eSuite een lastige woordkeuze omdat het al een betekenis had.

**Comment by JosDimpact** [comment]
@Snijhuis, ik wilde gerelateerd aan deze userstory een issue maken met de zaken die we besproken hadden (zoals genotuleerd in mijn comment van vanmorgen), maar ik zie dat er nu twee gerelateerde user stories zijn aangemaakt. Hoeven er dan geen issues meer te worden aangemaakt? Of zijn er nog open punten van vanmorgen die niet in deze twee vervolguserstories geraakt worden?

**Comment by Snijhuis** [comment]
@JosDimpact Klopt, ik heb ze aangemaakt. Had nog overleg met Atos en morgen planningssessie. Dus heb het direct maar even gedaan!

**Comment by VictorTielenius** [comment]
Groep nu verplicht (bij aanmaken zaak en in lopende zaak); Akkoord
