### ISSUE TITLE
6B.19.1  Een deel-gerelateerde of vervolgzaak handmatig laten aanmaken

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#289]
***Als*** zaakbehandelaar

***Wil ik*** Een deel-gerelateerde of vervolgzaak handmatig kunnen starten en automatisch aan de hoofdzaak koppelen

***Zodat*** de relatie met de hoofdzaak direct kan worden gelegd

***

### Acceptance criteria:
•	De nieuwe deel-gerelateerde of vervolgzaak moet handmatig kunnen worden aangemaakt 
•	Het aanmaken en toewijzen van deel-gerelateerde of vervolgzaak is alleen mogelijk als men hiervoor geautoriseerd is
•	De deel-gerelateerde of vervolgzaak wordt aangemaakt conform de vastgestelde inrichting van het zaaktype
•	Bij de deel-gerelateerde- vervolg en hoofdzaken kunnen ook de gerelateerde documenten worden getoond
•	De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Deze story is opgeleverd via user stories #895, #996 en #1235 voor de hoofd-deelzaak relatie en via user story #2204 voor de relevante andere zaak relatie. In story #1234 is het inzien van documenten van gekoppelde zaken opgeleverd.

**Comment by HilbrandHurtak** [comment]
Even wat overzicht:

#895 user story met bug
#996 In progress
#1235 Closed
#2204 User story met bug
1234 Closed

Misschien is het verstandig om deze items als geheel te testen. Ik ga dit met de testers van Groningen overleggen 

@CommonGroundGroningen willen jullie dit als 1 geheel testen. Het kan zijn dat Robert of Roy nog wat moeten inrichten in Open zaak (daar worden de relaties die mogelijk zijn gelegd)

**Comment by CommonGroundGroningen** [comment]
Bovenstaande kaartjes zijn getest en afgesloten.
