### ISSUE TITLE
6B.19.3  Een deel-gerelateerde of vervolgzaak achteraf koppelen en ontkoppelen 

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#291]
***Als*** zaakbehandelaar

***Wil ik*** Een bestaande deel-gerelateerde of vervolgzaak aan een bestaande zaak kunnen koppelen en ontkoppelen

***Zodat*** de relatie met de hoofdzaak achteraf kan worden gelegd

***

### Acceptance criteria:
•	De bestaande deel-gerelateerde of vervolgzaak moet handmatig kunnen worden gekoppeld en ontkoppeld
•	Bij de deel-gerelateerde- vervolg en hoofdzaken kunnen ook de gerelateerde documenten worden getoond
•	De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

**Comment by RoyBuis** [comment]
### Refinement KM, RB en RV
Stories zijn gerealiseerd. Eventuele openstaande stories gaan als losse stories verder.
