### ISSUE TITLE
6B.20.1 Het raadplegen van de procesflow en het tonen van de actuele stap in het proces tijdens het behandelen van de zaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#292]
***Als***  zaakbehandelaar

***Wil ik*** kunnen zien welk proces er moet worden gevolgd en in welke processtap de behandeling van de zaak zit.

***Zodat*** ik als behandelaar een beter overzicht heb van het afhandelproces

***

### Acceptance criteria:
•	Het te volgen proces schematisch tonen
•	De actuele processtap schematisch tonen

***
### Prioriteit

- Could haves

**Comment by Snijhuis** [comment]
Voorbeeld + criteria in screenshot
![image.png](https://images.zenhubusercontent.com/61a7728f4b7bcc716765fdd1/ee4cc837-0ba0-427c-b7b3-e58b49992b96)

**Comment by robertverboom** [comment]
Wordt in documentatie opgenomen. Andere wiki's ook updaten
