### ISSUE TITLE
6B.22.1 Het koppelen van een bedrijf tijdens het behandelen van een zaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#294]
***Als*** zaakbehandelaar

***Wil ik*** een bestaand bedrijf aan een bestaande zaak kunnen koppelen

***Zodat*** ik achteraf het juiste bedrijf aan de zaak kan koppelen 

***

### Acceptance criteria:
•	Indien hiervoor geautoriseerd kan een bedrijf worden opgezocht op naam, KVK nummer, vestigingsnummer en vestigingsadres. 
•	Het gevonden bedrijf kan aan de zaak worden gekoppeld
•	De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd

***
### Prioriteit

- Must haves

***
### Gerealiseerd
Op de zaakgegevenspagina kan een bedrijf als initiator worden toegevoegd indien dit niet al gebeurt is. Er verschijnt een sidepanel waar de gebruiker zoekcriteria kan invullen. De informatie wat getoond wordt, wordt uit de KVK api gehaald.

**Comment by CommonGroundGroningen** [comment]
**Testcase 1**
Koppelen van een bestaand bedrijf (op basis van KvKnr) aan mijn zaak zonder dat er al een bedrijf gekoppeld is
**Verwachting**
Bedrijf is gekoppeld aan mijn zaak
Zaakhistorie wordt bijgewerkt
**Resultaat**
Foutmelding wordt gegeven zolang er nog geen 8 cijfers ingegeven zijn
Bedrijf is gekoppeld
Zaakhistorie loopt 1 actie achter (de koppeling wordt niet getoond)

**Testcase 2**
Koppelen van een bestaand bedrijf (op basis van KvKnr) aan mijn zaak terwijl er al een bedrijf gekoppeld is
**Verwachting**
Foutmelding op reeds gekoppeld bedrijf. 
Bedrijf wordt niet gekoppeld aan mijn zaak
**Resultaat**
Optie om bedrijf te koppelen wordt niet getoond

**Testcase 3**
Koppelen van een bestaand bedrijf (op basis van KvKnr) aan een zaak waar ik geen behandelaar van ben (ZAAK-2022-0000000036)
**Verwachting**
Bedrijf wordt gekoppeld aan de zaak
Zaakhistorie wordt bijgewerkt
**Resultaat**
Bedrijf wordt gekoppeld
Historie wordt getoond NA verversen

**Testcase 4**
Koppelen van een niet bestaand bedrijf (op basis van niet bestaande naam)
**Verwachting**
Foutmelding op niet bestaande naam
Bedrijf wordt niet gekoppeld
Zaakhistorie wordt niet bijgewerkt
**Resultaat**
Bedrijf wordt niet gevonden (melding geen gegevens gevonden)
Er wordt niets gekoppeld
Zaakhistorie wordt niet bijgewerkt

**Testcase 5**
Koppelen van een niet bestaand bedrijf (op basis van niet bestaand KvKnr)
**Verwachting**
Foutmelding op niet bestaand KvKnr
Bedrijf wordt niet gekoppeld
Zaakhistorie wordt niet bijgewerkt
**Resultaat**
Foutmelding wordt gegeven als nog geen 8 cijfers ingegeven zijn
Bedrijf wordt niet gevonden (melding geen gegevens gevonden)
Er wordt niets gekoppeld
Zaakhistorie wordt niet bijgewerkt

**Testcase 6**
Koppelen van een niet bestaand bedrijf (op basis van niet bestaand vestigingsnr)
**Verwachting**
Foutmelding op niet bestaand vestigingsnr
Bedrijf wordt niet gekoppeld
Zaakhistorie wordt niet bijgewerkt
**Resultaat**
Foutmelding wordt gegeven zolang nog geen 12 cijfers ingegeven zijn
Bedrijf wordt niet gevonden (melding “Geen gegevens gevonden”)
Er wordt niets gekoppeld
Zaakhistorie wordt niet bijgewerkt

**Testcase 7**
Koppelen van een niet bestaand bedrijf (op basis van niet bestaand vestigingsadres)
**Verwachting**
Foutmelding op niet bestaand vestigingsadres
Bedrijf wordt niet gekoppeld
Zaakhistorie wordt niet bijgewerkt 
**Resultaat**
Foutmelding wordt gegeven zolang de postcode niet voldoet aan 1111AA
Bedrijf wordt niet gevonden (melding “Geen gegevens gevonden”)
Er wordt niets gekoppeld
Zaakhistorie wordt niet bijgewerkt
