### ISSUE TITLE
6B.24.1 Het (ont)koppelen van BAG objecten tijdens het behandelen van een zaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#296]
***Als*** zaakbehandelaar

***Wil ik*** bestaande BAG objecten aan een bestaande zaak kunnen koppelen en ontkoppelen

***Zodat*** ik achteraf de juiste BAG objecten aan de zaak kan koppelen en kan laten tonen op de kaart

***

### Acceptance criteria:
 •	Indien hiervoor geautoriseerd kunnen bestaande BAG objecten aan een zaak worden gekoppeld door te zoeken op “adres” en de volgende typering(per type aan en uit te zetten):

> o	Buurt
> o	Gemeente
> o	Ligplaats
> o	Nummeraanduiding
> o	Openbare ruimte
> o	Pand
> o	Standplaats
> o	Verblijfsobject
> o	Wijk
> o	Woonplaats

•	De gevonden BAG objecten kunnen aan de zaak worden gekoppeld
•	De gekoppelde BAG objecten kunnen bij de zaak worden ontkoppeld
•	De gekoppelde BAG objecten kunnen in de kaart worden getoond
•	De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd

***
### Prioriteit
- Must haves
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een BAG-object kan via een actie handmatig aan een zaak worden toegevoegd. Het is mogelijk om in de LV BAG te zoeken op postcode en huisnummer en een gevonden adres toe te voegen aan de zaak waarbij gebruik gemaakt wordt van de BAG API Individuele bevragingen. Na het toevoegen is het adres als zaakobject van het type 'Adres' aan de zaak toegevoegd en is het onder het tabblad 'BAG-objecten' in te zien. Een zaak kan meerdere BAG-objecten toegevoegd hebben. Het is in de oplevering niet mogelijk om een BAG-object te verwijderen.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het menu met de actie [BAG object toevoegen] het zoekscherm openen
- Een BAG-object kan gezocht worden op postcode en huisnummer.
- Gebruiker selecteert het BAG-object door in de lijst van zoekresultaten op het huis icoon te klikken. Hierna is het BAG-object zichtbaar in de tab 'BAG objecten' van het zaakgegevensscherm.
- Het toevoegen van een BAG-object wordt als wijziging van een object met vermelding van het type 'adres' vastgelegd in de historie van de zaak

**Comment by RoyBuis** [comment]
### Backlog refinement
Sander bespreekt prio met werkgroep

**Comment by Snijhuis** [comment]
Toevoeging: Dat het koppelen en ontkoppelen gewenst is duidelijk. Je wil ook deze BAG objecten uit de basisregistraties halen. Echter om het functioneel toe te voegen in ZAC willen we graag een specifieke story hebben vanuit een persona met een duidelijke zodat.

**Comment by RoyBuis** [comment]
### Refinement 7-7
De te gebruiken API is de HaalCentraal Huidige bevraging API

Spike om de volgende punten te onderzoeken:

- Zaak krijgt een extra tab voor zaakobjecten
- Als het zaakobject een BAG-object is dan is er de mogelijkheid om het object in een kaart te tonen
- Mogelijkheid om het zaakobject te ontkoppelen
- In het menu knop om BAG-object te koppelen, deze opent een panel waarin de gebruiker kan zoeken naar BAG-objecten, evt op basis van de gekoppelde zaaklocatie
- Beginnen met mogelijk maken om een nummeraanduiding te zoeken op postcode en huisnummer en te koppelen aan de zaak

Documentatie: https://vng-realisatie.github.io/Haal-Centraal-BAG-bevragen/swagger-ui#/Adresseerbaar%20object/raadpleegAdresseerbareobjecten

**Comment by andyverberne** [comment]
Benodigde API Key is aangevraagd

**Comment by Renvooi** [comment]
20220728 14:09 getest in zaak-2022-0000000101
BAG object gekoppeld 7131BJ 2
Foutmelding
(400) Title: Invalid input., Detail: Name: object, Code: bad-url, Reason: De URL https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen/1586200000041549 gaf als antwoord HTTP 400. Geef een geldige URL op.

Na sluiten foutmelding kwam wel een tekstblok in beeld dat het BAG object gekoppeld is aan de zaak. Echter in de zaak in onder tabblad BAG-Objecten het betreffende object niet weergegeven.

**Comment by robertverboom** [comment]
@Renvooi Bedankt voor de opmerking, echter is BAG aan onze kant nog in ontwikkeling

**Comment by robertverboom** [comment]
@Renvooi In open-zaak moest de 'BAG API Huidige bevragingen' service nog ingericht worden. Dit is inmiddels gedaan.

**Comment by HilbrandHurtak** [comment]
BAG functionaliteit is verder uitgewerkt in:
#2420
#2243
#2244
#2245
#2246
#2247
#2248
#2249
#2250
#2251
