### ISSUE TITLE
6B.25.1 Het handmatig kunnen aanmaken van externe taken

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#297]
***Als*** zaakbehandelaar

***Wil ik***  handmatig een externe taak voor een burger kunnen aanmaken, opnieuw uitzetten en intrekken

***Zodat*** de externe taak op een veilige manier kan worden ingevuld, bij de zaak kan worden opgenomen en ik het afhandelproces kan vervolgen

*** De externe taken worden verder uitgewerkt in Epic 8-Taken

### Acceptance criteria:
In de huidige e-Suite is het mogelijk om in een afhandelproces een taak bij een burger of bedrijf uit te zetten. Deze kan de taak uitvoeren waarna de behandelaar weer verder kan met het afhandelproces.

•	De externe taak moet kunnen worden beveiligd(denk aan DigiD of e-Herkenning)
•	Een burger/bedrijf moet via de mail op de hoogte kunnen worden gebracht van de externe taak
•	Een burger/bedrijf moet de velden in de taak kunnen invullen en de taak kunnen afronden
•	De behandelaar moet de externe taak opnieuw kunnen uitzetten
•	De behandelaar moet een herinnering kunnen versturen van een reeds aangemaakte externe taak
•	De behandelaar moet de externe taak kunnen intrekken
•	De behandelaar moet de externe taken kunnen monitoren
•	De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd

***
### Prioriteit
- Should haves

**Comment by RoyBuis** [comment]
Deze wordt opgepakt via de stories #483 en #484
Deze story wordt afgesloten.
