### ISSUE TITLE
Inrichting van zac.test-public-service-platform.net voor test automatisering

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#30]
Object registratie en formulier component worden niet ingericht op test.

- [x] @robertverboom  openzaak inrichten 
- [x] @andyverberne Groep en behandelaar koppelen aan zaak

**Comment by andyverberne** [comment]
Het niet kunnen aanmaken van een zaak op de test omgeving wordt veroorzaakt door #23

**Comment by andyverberne** [comment]
Het CMMN model was nog niet gedeployed!
