### ISSUE TITLE
6B.30.1 Downloaden van het dossier(alle documenten) tijdens het behandelen van de zaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#305]
***Als*** zaakbehandelaar

***Wil ik*** de documenten als dossier(bijvoorbeeld in een .zip file) kunnen downloaden

***Zodat ik*** bij het behandelen van de zaak het volledig dossier beschikbaar heb en niet elk document afzonderlijk hoef te downloaden

***

### Acceptance criteria:
•	De aan een zaak gekoppelde documenten (Inclusief gerelateerde zaak documenten) kunnen selecteren, downloaden en bewaren als een gecomprimeerd bestand (bijvoorbeeld zip bestand).
•	In het gecomprimeerd bestand worden de documenten verzameld op basis van documentrichting (Inkomend. Uitgaand en Intern)

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Could haves

### Gerealiseerd
Bovenstaande user story is gerealiseerd. 
Er is een deel 2 (#1429)  aangemaakt, met enkele vragen wat besproken kan worden met de werkgroep

**Comment by RoyBuis** [comment]
### Backlog refinement 18-5
Vanwege lagere prio naar icebox verplaatst.

**Comment by robertverboom** [comment]
### Refinement 25-07:
- .zip moet gestreamd weggeschreven worden 
- kijken hoe dit werkt in de e-suite (downloaden documentan als zip-file)

**Comment by robertverboom** [comment]
Er is een deel 2 (#1429)  aangemaakt, wat besproken kan worden met de werkgroep. Dossier downloaden is gerealiseerd.
