### ISSUE TITLE
6B.31.1 Een zaak achteraf anoniem maken

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#306]
***Als*** zaakbehandelaar

***Wil ik*** een zaak achteraf anoniem kunnen maken

***Zodat ik*** het juiste subject(Persoon/Bedrijf) kan koppelen

***

### Acceptance criteria:
•	Een aangemaakte zaak kan achteraf anoniem gemaakt worden 
•	De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd

***
### Prioriteit

- Must haves

### Gerealiseerd: 
Wanneer een initiator is toegevoegd, wordt er een prullenbak getoond om de initiator te kunnen verwijderen, ofwel anoniem te te maken. De wijziging wordt vastgelegd in de zaakhistorie

**Comment by PaskalKiers** [comment]
De zaakbehandelaars die ik spreek willen helemaal niet anoniem maken, die vinden het maar omslachtig werken. Die willen eigenlijk:
 
Als zaakbehandelaar
Wil ik een ander subject aan een zaak koppelen
Zodat ik een foutief gekoppeld subject kan corrigeren. 

Anoniem maken is een mogelijke oplossing voor dit probleem, maar ik zou inventievere oplossingen kunnen bedenken als ik niet beperkt werd door de behoefte om eerst anoniem te maken.  

Wellicht dat er andere reden zijn om anoniem te maken...

**Comment by HilbrandHurtak** [comment]
> De zaakbehandelaars die ik spreek willen helemaal niet anoniem maken, die vinden het maar omslachtig werken. Die willen eigenlijk:
> 
> Als zaakbehandelaar Wil ik een ander subject aan een zaak koppelen Zodat ik een foutief gekoppeld subject kan corrigeren.
> 
> Anoniem maken is een mogelijke oplossing voor dit probleem, maar ik zou inventievere oplossingen kunnen bedenken als ik niet beperkt werd door de behoefte om eerst anoniem te maken.
> 
> Wellicht dat er andere reden zijn om anoniem te maken...

Zaken worden bij ons soms anoniem gemaakt op basis van een datalek . Na afronding van het onderzoek kan dan de juiste persoon worden gekoppeld of blijft het anoniem. Tevens komt het voor dat een anonieme aanvraag door een behandelaar aan een persoon wordt gekoppeld. De vraag is of dat wel mag. De aanvraag is immers ingediend via een DigiD e-formulier.

**Comment by PaskalKiers** [comment]
> Zaken worden bij ons soms anoniem gemaakt op basis van een datalek . Na afronding van het onderzoek kan dan de juiste persoon worden gekoppeld of blijft het anoniem. Tevens komt het voor dat een anonieme aanvraag door een behandelaar aan een persoon wordt gekoppeld. De vraag is of dat wel mag. De aanvraag is immers ingediend via een DigiD e-formulier.

Ik snap het nog niet helemaal waarom de zaak anoniem gemaakt moet worden, maar dat is niet erg voor nu.  De user story die jij mist is meer in de trant:
Als zaakbehandelaar
Wil ik het subject van een zaak verwijderen
zodat ik in het geval van een datalek nader onderzoek kan doen, zonder dat de identiteit van het subject voor iedereen zichtbaar is.

Of is het meer dat geldt:

Als zaakbehandelaar 
wil ik de zichtbaarheid van het subject beperken tot iemand met gerichte machtiging hiervoor
zodat ik in het geval van een datalek nader onderzoek kan doen, zonder dat de identiteit van het subject voor iedereen zichtbaar is.

Wat ik me dan wel afvraag, wat is de toegevoegde waarde als je de wijziging gewoon na kunt kijken in de historie, of moet daar dan ook specifiek rechten op--> user story 

Wat betreft het kunnen koppelen, ik heb nog niet gekeken of die user story al op de lijst staat.  Zou ik wel verwachten op basis van de user story.   

Of je een subject aan een anonieme zaak koppelen mag is ook een goede, wellicht een punt voor de acceptatiecriteria om te refereren aan voldoen aan de wet op dit punt. Al herken ik het niet dat een anonieme zaak is ingediend via Digid.    Anoniem is anoniem in Rotterdam. Als ik iets anoniem in wil dienen, zou ik me ook redelijk bezwaard voelen om dat via Digid te doen.

**Comment by HilbrandHurtak** [comment]
> > Zaken worden bij ons soms anoniem gemaakt op basis van een datalek . Na afronding van het onderzoek kan dan de juiste persoon worden gekoppeld of blijft het anoniem. Tevens komt het voor dat een anonieme aanvraag door een behandelaar aan een persoon wordt gekoppeld. De vraag is of dat wel mag. De aanvraag is immers ingediend via een DigiD e-formulier.
> 
> Ik snap het nog niet helemaal waarom de zaak anoniem gemaakt moet worden, maar dat is niet erg voor nu. De user story die jij mist is meer in de trant: Als zaakbehandelaar Wil ik het subject van een zaak verwijderen zodat ik in het geval van een datalek nader onderzoek kan doen, zonder dat de identiteit van het subject voor iedereen zichtbaar is.
> 
> Of is het meer dat geldt:
> 
> Als zaakbehandelaar wil ik de zichtbaarheid van het subject beperken tot iemand met gerichte machtiging hiervoor zodat ik in het geval van een datalek nader onderzoek kan doen, zonder dat de identiteit van het subject voor iedereen zichtbaar is.
> 
> Wat ik me dan wel afvraag, wat is de toegevoegde waarde als je de wijziging gewoon na kunt kijken in de historie, of moet daar dan ook specifiek rechten op--> user story
> 
> Wat betreft het kunnen koppelen, ik heb nog niet gekeken of die user story al op de lijst staat. Zou ik wel verwachten op basis van de user story.
> 
> Of je een subject aan een anonieme zaak koppelen mag is ook een goede, wellicht een punt voor de acceptatiecriteria om te refereren aan voldoen aan de wet op dit punt. Al herken ik het niet dat een anonieme zaak is ingediend via Digid. Anoniem is anoniem in Rotterdam. Als ik iets anoniem in wil dienen, zou ik me ook redelijk bezwaard voelen om dat via Digid te doen.

Dag Pascal. Ik denk dat dit soort dingen met de product owner moet worden besproken. Ik heb Sander al gevraagd op dat op te pakken

**Comment by PaskalKiers** [comment]
Hi Hilbrand, 
bedankt voor je terugkoppeling, ik vond je terugkoppeling wel fijn, want volgens mij voeden wij de PO namelijk met user stories.  Ik ben echter nog niet zo bekend met de etiquette voor dit project.  Ik ben gewend dat je op een open platform overal op kunt reageren. In de discussie ontstaat de scherpte en het begrip.   Toevallig bleef ik nu bij deze user story hangen om mee te lezen en te reageren.  Ik  zal Sander ook benaderen over de user stories die bovenaan de lijst staan voor de sprint backlog en refinement, zodat ik wat gerichter kan bijdragen.  
Groeten, Paskal

**Comment by HilbrandHurtak** [comment]
Dag Pascal
Vond je commentaar ook erg zinvol. Op dit moment maak ik inderdaad een deel van de user stories. We bespreken dit in een werkgroep en daarna zet ik het op Github. Sander bespreekt dit dan verder met Atos en koppelt vragen aan onze werkgroep terug. Tot op heden heeft Sander de user stories in Github aangemaakt en kreeg hij ook de reacties. Voor mij was het dus even nieuw dat ik vanuit deze hoek de vragen kreeg;)
De huidige werkgroep gebruikt niet alle functionaliteit van de e-Suite. We zullen straks ook expertise van andere gemeenten gaan vragen(bijvoorbeeld t.a.v. DRS functionaliteit). Misschien kun je eens met Sander gaan praten. Expertise is altijd welkom.

Groetjes
Hilbrand (Gemeente Groningen)

**Comment by robertverboom** [comment]
het wijzigen van een subject/initiator wordt opgepakt in story #1363

**Comment by HilbrandHurtak** [comment]
Initiator kan eenvoudig worden gewijzigd(andere initiator of geen)
