### ISSUE TITLE
6A-1.1 Zaak handmatig starten zonder (Intern) startformulier

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#309]
***Als*** Medewerker

***Wil ik*** handmatig een zaak kunnen starten

***Zodat*** ik aanvragen die niet via een e-formulier of vanuit een andere gekoppelde applicatie zijn ontvangen ook in het zaaksysteem kan registreren

***

### Acceptance criteria:
•	Een zaak moet op basis van een centrale inrichting(bijvoorbeeld ZTC) vanuit een eenvoudige grafisch user interface (in de huidige omgeving is dat het medewerkersportaal) kunnen worden aangemaakt
•	Een zaak kan anoniem, ~~op naam van een inwoner op naam van een bedrijf en op een locatie~~ worden gestart. Refinement: op naam van persoon als aparte story aangemaakt, zie gekoppelde story #386. Op naam van bedrijf, zie story #432 Locatie koppelen zie #433
•	~~Bij gebruik van persoons-, bedrijfsgegevens en locatie dient gebruik te worden gemaakt van de authentieke bronnen.~~ Dit is een acc crit voor story koppelen persoon, bedrijf of locatie, zie #386 #432 #433 
•	~~De zaak mag alleen gestart worden door medewerkers die daartoe geautoriseerd zijn~~ komt in apart story over rechten
•	Bij het aanmaken van een zaak wordt een uniek nummer gegenereerd (Zaaknummer)
•	Bij het handmatig aanmaken van een zaak zonder startformulier worden tenminste de volgende gegevens vastgelegd:

- 	Zaaknummer (Open zaak= identificatie)
- 	Zaaktype (Open zaak= zaaktype)
- 	Kanaal (Open zaak= Communicatiekanaal)
- 	Status (Open zaak= status)
- 	Behandelwijze (vertrouwelijk behandelen) (Open zaak= Vertrouwelijkheid aanduiding)
- 	Aangemaakt door (gebruiker uit ZAC)
- 	Behandelaar (gebruiker uit ZAC)
- 	Initiële afdeling/groep (groep uit  ZAC)
- 	Creatiedatum (Open zaak= Registratie datum)
- 	Startdatum(kan in het verleden liggen) (Open zaak= Startdatum)
- 	Streefdatum (Open zaak= Einddatum gepland)
- 	Fatale datum (Open zaak= Uiterlijke einddatum afdoening)
- 	Omschrijving (Open zaak= Omschrijving)
- 	~~Reden start (NIET VERPLICHT)~~ (Open zaak=Toelichting)
- 	~~Indien de zaak op naam van een inwoner is aangemaakt moet de relatie tussen de inwoner en de zaak zichtbaar zijn~~ Dit is een acc crit voor story #386 
- 	~~Indien de zaak op naam van een bedrijf is aangemaakt moet de relatie tussen het bedrijf en de zaak zichtbaar zijn~~ Dit is een acc crit voor story #432 
- 	~~Indien de zaak op basis van een locatie is aangemaakt moet de relatie tussen de locatie en de zaak zichtbaar zijn~~ Dit is een acc crit voor story #433 
•	Bij het aanmaken van een zaak worden termijnen van doorlooptijd automatisch berekend 
•	Na het aanmaken van de zaak wordt automatisch een afhandelproces gestart voor een afdeling, groep of behandelaar
•	Na het starten van de zaak wordt er een Audit trail vastgelegd

***
### Prioriteit
- Must haves

Story #386 is gerelateerd
Story #432 is gerelateerd
Story #433 is gerelateerd

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Vanuit het ZAC kan een nieuwe zaak worden aangemaakt. Bij het aanmaken kunnen een aantal bepalende zaakgegevens, zoals het zaaktype, de startdatum en het communicatiekanaal ingevuld worden. De in de Zaken API verplichte attributen moeten zijn in dit scherm verplichte velden. 

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het hoofdmenu via het Dossier icoon een nieuwe zaak aanmaken
- Gebruiker kan een aantal van de zaakgegevens direct invullen
- Met de [Aanmaken] knop wordt de zaak opgeslagen
- De zaak wordt toegekend aan de groep die is ingesteld in de Zaakafhandelparameters onder Algemene gegevens. Optioneel is hier ook een standaard behandelaar in te stellen.
- De streefdatum (optioneel) en fatale datum (verplicht) van de zaak worden berekend o.b.v. de instelling in het zaaktype
- Het CMMN-model dat bij de zaak beschikbaar komt wordt door de instelling in de Zaakafhandelparameters onder Algemene gegevens bepaald. De eerste fase van het model, inclusief de beschikbare acties, wordt automatisch gestart.
- Het aanmaken, toekennen en zetten van de status van de zaak wordt in de historie van de zaak vastgelegd

**Comment by RoyBuis** [comment]
Refinement 3-2:

- Deze story aangepast naar 'Zaak handmatig anoniem starten zonder startformulier'
- Persoon koppelen als aanvrager bij starten zaak als aparte story opgenomen
- Voor het koppelen van een bedrijf en een locatie ook aparte stories nog maken

Openstaande vragen voor deze story:
Behandelaar: er kan nu ná het aanmaken van een zaak een behandelaar gekozen worden, zowel via de zaak als via verdelen functie. Moet het ook mogelijk zijn om direct bij het aanmaken van de zaak de behandelaar al te kiezen?
Initiële groep: deze staat nu in het ZAC ingesteld. Moet het bij het aanmaken van de zaak mogelijk zijn om hier van af te wijken? In de huidige werking kan de groep vanuit de zaak of via verdelen worden aangepast?

**Comment by Snijhuis** [comment]
WG 9-2-2022: Functionaliteit voor het kunnen wijzigen van groep/medewerker bij het aanmaken van zaken:
Sommige gemeenten willen dit wel, anderen niet. Kan dit optioneel worden ingericht? Wellicht per zaaktype.

**Comment by robertverboom** [comment]
Overige stories aanmaken

**Comment by Snijhuis** [comment]
WG R&A Oppakken met Stef (Open Formulieren)
Actie Sander

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV

Story is gerealiseerd.
