### ISSUE TITLE
BUG: Additionele Specs op #108 Signalering op zaken voor zaakbehandelaar binnen ZAC zijn nog niet verwerkt

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#311]
***Steps to reproduce:***

Extra specs dd: 13 dec 2021 zijn nog niet verwerkt in de userstory:

- Te tonen velden bij een zaak in het signaleringen overzicht: zaaknummer, zaaktype, omschrijving en startdatum
- Volgorde in het overzicht van nieuw naar oud met mogelijkheid om om te draaien van oud naar nieuw

**Comment by hansmarks** [comment]
Startdatum toegevoegd, Identificatie veranderd naar Zaaknummer (op verzoek van Robert), Titel van de card aangepast (ook in overleg met Robert) het zijn geen nieuwe zaken maar signaleringen van zaken die nieuw op naam van de gebruiker zijn gezet (bespreekt Robert nog verder met Roy).

De hele tabel was al sorteerbaar, dus nu ook op Startdatum.

**Comment by robertverboom** [comment]
wellicht "Recent aan mij toegewezen"
