### ISSUE TITLE
6A.2.1 Zaak vanuit een e-formulier laten aanmaken 

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#312]
***Als*** behandelaar

***Wil ik*** dat er automatisch een zaak wordt aangemaakt als een inwoner of bedrijf een e-formulier heeft ingediend 

***Zodat*** het juiste afhandelproces wordt gestart en ik de zaak in behandeling kan nemen

***

### Acceptance criteria:
•	Op basis van een ingediend e-formulier moet er automatisch een zaak van het juiste zaaktype worden aangemaakt.
•	Op basis van de automatisch aangemaakte zaak wordt het juiste afhandelproces gestart
•	Het ingevulde e-formulier moet als pdf document bij de zaak beschikbaar zijn
•	De velden uit het e-formulier moeten als data bij de zaak beschikbaar zijn en kunnen worden gebruikt voor het vullen van de omschrijving, reden start van de zaak of in het afhandelproces
•	Er moet automatisch een ontvangstbevestiging worden verstuurd en aan het zaakdossier worden toegevoegd 
•	Een zaak moet op basis van een centrale inrichting(bijvoorbeeld ZTC) worden aangemaakt
•	Een zaak kan anoniem, op naam van een inwoner, op naam van een bedrijf en op een locatie worden gestart
•	Bij gebruik van persoons-, bedrijfsgegevens en locatie dient gebruik te worden gemaakt van de authentieke bronnen.
•	Bij het aanmaken van een zaak wordt een uniek nummer gegenereerd(Zaaknummer)
•	Bij het automatisch aanmaken van de zaak via een e-formulier worden tenminste de volgende gegevens vastgelegd:

- 	Zaaknummer
- 	Zaaktype
- 	Kanaal=Internet
- 	Status
- 	Behandelwijze (vertrouwelijk behandelen)
- 	Aangemaakt door
- 	Behandelaar
- 	Initiële afdeling/groep
- 	Creatiedatum
- 	Startdatum (kan in het verleden liggen)
- 	Streefdatum
- 	Fatale datum
- 	Omschrijving
- 	Reden start (NIET VERPLICHT)
- 	Indien de zaak op naam van een inwoner is aangemaakt moet de relatie tussen de inwoner en de zaak zichtbaar zijn
- 	Indien de zaak op naam van een bedrijf is aangemaakt moet de relatie tussen het bedrijf en de zaak zichtbaar zijn
- 	Indien de zaak op basis van een locatie is aangemaakt moet de relatie tussen de locatie en de zaak zichtbaar zijn

•	Bij het aanmaken van een zaak worden termijnen van doorlooptijd automatisch berekend 
•	Na het aanmaken van de zaak wordt automatisch een afhandelproces gestart voor een afdeling, groep of behandelaar
•	Na het starten van de zaak wordt er een Audit trail vastgelegd

***
### Prioriteit

- Must haves

### gerealiseerd 
Na het afhandelen van het formulier in open formulieren(e-formulier), wordt er een zaak aangemaakt in Zaak afhandel component. Het formulier wordt als pdf als document op de zaak gezet. 

### Niet gerealiseerd: 
De velden uit het e-formulier moeten als data bij de zaak beschikbaar zijn en kunnen worden gebruikt voor het vullen van de omschrijving, reden start van de zaak of in het afhandelproces

**Comment by RoyBuis** [comment]
### Backlog refinement
gerealiseerd behalve de volgende punten:

- De velden uit het e-formulier moeten als data bij de zaak beschikbaar zijn en kunnen worden gebruikt voor het vullen van de omschrijving, reden start van de zaak of in het afhandelproces

**Comment by HilbrandHurtak** [comment]
**Testcase 1**
Op basis van een ingediend e-formulier moet er automatisch een zaak van het juiste zaaktype worden aangemaakt.
**Verwachting**
Nieuwe zaak van het juiste zaaktype
**Resultaat**
Nieuwe zaak van het juiste zaaktype
 **OK**

**Comment by HilbrandHurtak** [comment]
Het beschikbaar maken van de ingevulde data uit Open Formulieren is niet generiek en nu vreemd opgepakt onder een knop "wijzigen zaakdata" Met Sander is afgesproken dat deze functionaliteit wordt verwijderd. De bedoeling is dat de ingevulde data in Open Formulieren beschikbaar is om te gebruiken voor een flowconditie of te tonen op een scherm. De data mag natuurlijk niet worden gewijzigd.

**Comment by robertverboom** [comment]
Story graag sluiten, punten worden opgepakt in vervolg story. #2179
