### ISSUE TITLE
6A.4.1 Zaak vanuit een Application Programming Interface (API) laten aanmaken

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#314]
***Als*** organisatie

***Wil ik*** dat er op basis van een Application Programming Interface (API) koppeling automatisch een zaak kan worden gestart, bijgewerkt en afgehandeld

***Zodat*** gegevens niet meer op meerdere plekken worden bewaard en door middel van berichtenverkeer moeten worden gesynchroniseerd(asynchroon). Volgens de common ground principes zouden de gegevens in registers beschikbaar moeten zijn en via synchrone services kunnen worden gebruikt door andere applicaties

***

### Acceptance criteria:
Binnen de gemeentelijke organisatie worden vakapplicaties gebruikt voor de afhandeling van processen. In de huidige e-Suite wordt de e-Formulieren, KCC, Mijn Loket en DMS functionaliteit ingezet om de klant zo goed mogelijk te bedienen of te kunnen voldoen aan bepaalde wettelijke verplichtingen(bijvoorbeeld archivering). De procesafhandeling blijft vaak in de vakapplicatie uitgevoerd worden. Via een API koppeling zouden de gegevens niet meer in diverse applicaties moeten worden bijgehouden en kan er gebruik worden gemaakt van gegevens zoals die in centrale registers beschikbaar zijn. Door deze nieuwe wijze van koppelen zijn gegevens altijd actueel(synchroon).

•	Het moet mogelijk om op basis van een API vanuit een vakapplicatie een zaak te kunnen starten en op basis van CRUD ( Create , Read, Update en Delete ) functionaliteit te actualiseren
•	Het moet mogelijk om op basis van een API vanuit een zaaksysteem een zaak in een vakapplicatie te kunnen starten en op basis van CRUD ( Create , Read, Update en Delete ) functionaliteit te actualiseren
•	Een zaak kan anoniem, op naam van een inwoner, op naam van een bedrijf en op een locatie worden gestart
•	Bij gebruik van persoons-, bedrijfsgegevens en locatie dient gebruik te worden gemaakt van de authentieke bronnen
•	Bij het aanmaken van een zaak wordt een uniek nummer gegenereerd(Zaaknummer)
•	Bij het handmatig aanmaken van een zaak via de API worden tenminste de volgende gegevens vastgelegd:

-	Zaaknummer
-	Zaaktype
-	Kanaal
-	Status
-	Behandelwijze (vertrouwelijk behandelen)
-	Aangemaakt door
-	Behandelaar
-	Initiële afdeling/groep
-	Creatiedatum
-	Startdatum(kan in het verleden liggen)
-	Streefdatum
-	Fatale datum
-	Omschrijving
-	Reden start (NIET VERPLICHT)
-	Indien de zaak op naam van een inwoner is aangemaakt moet de relatie tussen de inwoner en de zaak zichtbaar zijn
-	Indien de zaak op naam van een bedrijf is aangemaakt moet de relatie tussen het bedrijf en de zaak zichtbaar zijn
-	Indien de zaak op basis van een locatie is aangemaakt moet de relatie tussen de locatie en de zaak zichtbaar zijn

•	Bij het aanmaken van een zaak worden termijnen van doorlooptijd automatisch berekend 
•	Na het aanmaken van de zaak wordt automatisch een afhandelproces gestart voor een afdeling, groep of behandelaar. 
•	Na het starten van de zaak wordt er een Audit trail vastgelegd
•	Op basis van de API moeten automatisch gegevens kunnen worden uitgewisseld/getoond
•	Op basis van de API moet automatisch een zaak kunnen worden afgesloten
•	Op basis van de API moeten automatisch documenten kunnen worden uitgewisseld
•	Op basis van de API moet automatisch een proces kunnen worden gestart(in zowel de e-Suite als de backoffice applicatie)
•	Verstoringen moeten worden gesignaleerd en kunnen worden hersteld
•	Het autorisatiemodel is ook van toepassing op de API koppeling zodat medewerkers alleen met de juiste rechten zaken kunnen starten, wijzigen en afronden
###	Deze materie is nieuw. Wat moeten we hier nog meer als acceptatie criteria opnemen?

***
### Prioriteit

- Must haves

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV

Wordt in een ander issue opgelost
