### ISSUE TITLE
6A.6.1 Zaak vanuit een mailprogramma laten aanmaken

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#317]
***Als*** medewerker

***Wil ik*** dat er op basis van een ontvangen mail vanuit het mailprogramma een zaak kan worden aangemaakt en de mail als document bij de zaak wordt toegevoegd

***Zodat*** ik de mail op een efficiënte wijze kan registreren, distribueren en archiveren

***

### Acceptance criteria:
Binnen de gemeentelijke organisatie wordt nu gebruik gemaakt van een (outlook) plugin om vanuit de mailapplicatie een document bij de zaak te voegen, een document in de werkvoorraad te zetten of een contact aan te maken. Het is nu nog niet mogelijk om direct een zaak aan te maken. Deze functionaliteit zou echter wel wenselijk zijn

•	Het moet mogelijk zijn om vanuit de mail direct een zaak te laten aanmaken
•	Een zaak kan anoniem, op naam van een inwoner, op naam van een bedrijf en op een locatie worden gestart
•	Bij gebruik van persoons-, bedrijfsgegevens en locatie dient gebruik te worden gemaakt van de authentieke bronnen
•	Bij het aanmaken van een zaak wordt een uniek nummer gegenereerd(Zaaknummer)
•	Bij het handmatig aanmaken van een zaak vanuit een mailprogramma worden tenminste de volgende gegevens vastgelegd:

- 	Zaaknummer
- 	Zaaktype
- 	Kanaal
- 	Status
- 	Behandelwijze (vertrouwelijk behandelen)
- 	Aangemaakt door
- 	Behandelaar
- 	Initiële afdeling/groep
- 	Creatiedatum
- 	Startdatum(kan in het verleden liggen)
- 	Streefdatum
- 	Fatale datum
- 	Omschrijving
- 	Reden start (NIET VERPLICHT)
- 	Indien de zaak op naam van een inwoner is aangemaakt moet de relatie tussen de inwoner en de zaak zichtbaar zijn
- 	Indien de zaak op naam van een bedrijf is aangemaakt moet de relatie tussen het bedrijf en de zaak zichtbaar zijn
- 	Indien de zaak op basis van een locatie is aangemaakt moet de relatie tussen de locatie en de zaak zichtbaar zijn

•	Bij het aanmaken van een zaak worden termijnen van doorlooptijd automatisch berekend 
•	Na het aanmaken van de zaak wordt automatisch een afhandelproces gestart voor een afdeling, groep of behandelaar. 
•	Na het starten van de zaak wordt er een Audit trail vastgelegd
•	Verstoringen moeten worden gesignaleerd en kunnen worden hersteld
•	Het autorisatiemodel is ook van toepassing op de Mail koppeling zodat medewerkers alleen met de juiste rechten zaken kunnen starten
•	Het moet mogelijk zijn om de mail direct als document aan de nieuwe zaak toe te voegen
•	De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd 

***
### Prioriteit

- Could haves

**Comment by IreneYolande** [comment]
Dit is een must have!

**Comment by HilbrandHurtak** [comment]
@Snijhuis . Kan jij (als product owner) aangeven of het een must of een could have moet worden.

**Comment by HilbrandHurtak** [comment]
@Snijhuis en @KarinMasselink . Willen jullie dit issue nog eens bekijken/beoordelen. Er wordt veel gebruik van gemaakt. Deze week zag ik een ander zaaksysteem waarin de mail(met bijlagen) gewoon direct als .msg bestand kon worden gesleept (dus niet eerst downloaden en dan toevoegen) in het component waar je normaal gesproken vanuit een netwerkschijf dat doet. Vervolgens kon je de metadata invullen. Misschien een leuke tussenoplossing zolang we niet weten of een outlook plugin kan.

**Comment by HilbrandHurtak** [comment]
Graag bespreken als tussenoplossing:
- vanuit een mailprogramma (meestal outlook) de mail slepen als .msg bestand tijdens het toevoegen van een document en dan voorzien van de metadata. Nu lukt dat niet (slepen van mail in de huidige e-Suite wel maar toevoegen .msg niet.) Het is functionaliteit die veel wordt toegepast.

voorbeeld (bestand is vanuit outlook naar het component gesleept)
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/1c870b66-ac6f-402b-a50b-3dd985019b24)



Later dan kij

**Comment by HilbrandHurtak** [comment]
Graag bespreken als tussenoplossing:
- vanuit een mailprogramma (meestal outlook) de mail slepen als .msg bestand tijdens het toevoegen van een document en dan voorzien van de metadata. Nu lukt dat niet (slepen van mail in de huidige e-Suite wel maar toevoegen .msg niet.) Het is functionaliteit die veel wordt toegepast.

voorbeeld (bestand is vanuit outlook naar het component gesleept)
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/1c870b66-ac6f-402b-a50b-3dd985019b24)



Later dan kij

**Comment by HilbrandHurtak** [comment]
Nieuwe userstory #2385 is aangemaakt

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV

Story wordt via PodiumD backlog verder opgepakt.
