### ISSUE TITLE
6A.7.2 Intake automatisch vanuit een e-formulier laten aanmaken

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#318]
***Als*** medewerker

***Wil ik*** een intake kunnen aanmaken

***Zodat*** later in het proces het juiste zaaktype kan worden gestart

***

### Acceptance criteria:
De inwoner weet soms niet om welk zaaktype het gaat. Via een e-formulier kan er dan een algemene melding worden gemaakt. Deze wordt automatisch als Intake geregistreerd. Na beoordeling door een medewerker kan vanuit de Intake het juiste zaaktype worden gestart en worden gegevens overgezet naar het juiste zaaktype.  

Acceptance criteria:

•	Op basis van een ingediend e-formulier moet er automatisch een Intake van het juiste Intaketype worden aangemaakt.
•	Op basis van de automatisch aangemaakte Intake wordt het juiste afhandelproces gestart
•	Het ingevulde e-formulier moet als pdf document bij de Intake beschikbaar zijn
•	De velden uit het e-formulier moeten als data bij de Intake beschikbaar zijn en kunnen worden gebruikt voor het vullen van de omschrijving, reden start van de Intake of in het afhandelproces
•	Er moet automatisch een ontvangstbevestiging worden verstuurd 
•	Een Intake moet op basis van een centrale inrichting(bijvoorbeeld ZTC) worden aangemaakt
•	Een Intake kan anoniem, op naam van een inwoner, op naam van een bedrijf en op een locatie worden gestart
•	Bij gebruik van persoons-, bedrijfsgegevens en locatie dient gebruik te worden gemaakt van de authentieke bronnen
•	Bij het aanmaken van een Intake wordt een uniek nummer gegenereerd (Zaaknummer is duidelijk te onderscheiden van ‘gewone’ zaaknummers, bijvoorbeeld een zaaknummer beginnende met een “i”)
•	Bij het automatisch aanmaken van de Intake via een e-formulier worden tenminste de volgende gegevens vastgelegd:
o	Zaaknummer (herkenbaar als intake, bijvoorbeeld beginnende met een “i”)
o	Intaketype
o	Kanaal=Internet
o	Status
o	Behandelwijze (vertrouwelijk behandelen)
o	Aangemaakt door
o	Behandelaar
o	Initiële afdeling/groep
o	Creatiedatum
o	Startdatum (kan in het verleden liggen)
o	Streefdatum
o	Fatale datum
o	Omschrijving
o	Reden start (NIET VERPLICHT)
o	Indien de Intake op naam van een inwoner is aangemaakt moet de relatie tussen de inwoner en de Intake zichtbaar zijn
o	Indien de Intake op naam van een bedrijf is aangemaakt moet de relatie tussen het bedrijf en de Intake zichtbaar zijn
o	Indien de Intake op basis van een locatie is aangemaakt moet de relatie tussen de locatie en de Intake zichtbaar zijn
•	Bij het aanmaken van een Intake worden termijnen van doorlooptijd automatisch berekend 
•	Na het aanmaken van de Intake wordt automatisch een afhandelproces gestart voor een afdeling, groep of behandelaar
•	Na het starten van de Intake wordt er een Audit trail vastgelegd

***
### Prioriteit

- Should haves

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV

Story is gerealiseerd via Inbox productaanvraag, zie #319
