### ISSUE TITLE
6A.7.3 Productaanvraag handmatig afhandelen en omzetten naar zaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#319]
***Als*** behandelaar

***Wil ik*** een ~~intake~~ productaanvraag kunnen afhandelen en het juiste zaaktype kunnen starten

***Zodat*** het juiste afhandelproces kan worden doorlopen

***

### Acceptance criteria:
Nadat de ~~intake~~ productaanvraag is geregistreerd moet deze handmatig kunnen worden afgehandeld. Tijdens de afhandeling moet het juiste zaaktype worden gekozen. Hierbij kunnen alleen zaaktypes worden gekozen die bij de inrichting van de Intake zijn geconfigureerd. Nadat het juiste zaaktype is aangemaakt is de Intake afgehandeld

Acceptance criteria:

•	Een zaak die vanuit een Intake wordt gestart moet op basis van een centrale inrichting(bijvoorbeeld ZTC) vanuit een eenvoudige grafisch user interface (in de huidige omgeving is dat het medewerkersportaal) kunnen worden aangemaakt
•	De volgende gegevens worden vanuit de Intake overgezet :

- 	Reeds gekoppelde personen
- 	Reeds gekoppelde bedrijven
- 	Reeds gekoppelde documenten
- 	Reeds gekoppelde betrokkenen
- 	Relatie tussen Intake en aangemaakte zaak (vervolgzaak)
- 	Creatiedatum van de nieuwe zaak (gaat automatisch)

•	De volgende gegevens moeten bij het aanmaken van de zaak vanuit de Intake opnieuw worden ingevuld:

- 	Zaaktype
- 	Status (na invullen van het zaaktype)
- 	Omschrijving
- 	Reden start (NIET VERPLICHT) 
- 	Behandelaar (optioneel)
- 	Initiële afdeling/groep(wordt op basis van de ZTC inrichting ingevuld)
- 	BAG objecten en locaties moeten na het aanmaken van de zaak opnieuw worden toegevoegd. 

•	De volgende gegevens kunnen bij het aanmaken van een zaak vanuit de Intake worden overgenomen of gewijzigd:

- 	Kanaal
- 	Behandelwijze (vertrouwelijk behandelen)
- 	Startdatum(kan in het verleden liggen)
- 	Streefdatum
- 	Fatale datum

•	Tijdens het aanmaken van het juiste zaaktype moeten ook de gegevens voor het afsluiten van de intake worden ingevuld waarna de Intake direct wordt afgesloten. Het gaat dan om:

- 	Eindstatus Intake
- 	Resultaat Intake
- 	Reden beëindigen Intake

•	Na het starten van de zaak wordt er een Audit trail vastgelegd

***
### Prioriteit
- Should haves
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In deze user story is er een Inbox productaanvragen aan de ZAC toegevoegd waarin productaanvragen komen die niet tot een zaak hebben geleid omdat er geen match was op productaanvraagtype met één van zaaktypen die in zaps zijn ingericht.
Vanuit de Inbox kan het aanvraagdocument van de productaanvraag bekeken worden en kan alsnog met de 'Zaak aanmaken' functionaliteit een zaak gestart worden. Het is ook nogelijk om een productaanvraag te verwijderen. 

***Belangrijkste functionaliteiten:***
- Gebruiker kan de Inbox productaanvragen openen door in het menu bovenin onder de categorie 'Inbox' de werklijst 'Inbox productaanvragen te kiezen
- Gebruiker kan het aanvraagdocument van een productaanvraag bekijken door in de regel van de productaanvraag links op het pijltje te klikken of rechts via het oog icoon
- Gebruiker kan het aanvraagdocument van een productaanvraag downloaden door in de regel van de productaanvraag op het download icoon te klikken
- Gebruiker kan met de productaanvraag een nieuwe zaak aanmaken door in de regel van de productaanvraag te klikken op het map plus icoon

**Comment by robertverboom** [comment]
#318

**Comment by robertverboom** [comment]
#320

**Comment by RoyBuis** [comment]
### Refinement SN, RV & RB

Bespreken of het mogelijk is om een productaanvraag als intake te kunnen laten fungeren. Wellicht via Inbox documenten waarbij geen zaak aangemaakt wordt maar de gebruiker vanuit het document bepaalt welke type zaak aangemaakt moet worden.
Eerst nieuwe verie Open Formulieren installeren.

**Comment by RoyBuis** [comment]
### Refinement 17-1

Productaanvragen die niet tot een zaak hebben geleid in een werklijst tonen zodat een medewerker deze kan beoordelen en vandaar uit ene zaak kan aanmaken

Registreren productaanvraag
- Werklijst 'Productaanvragen' introduceren. Hier komt iedere productaanvraag uit Overige Registraties in die niet tot een zaak heeft geleid
- In de productaanvraag is het PDF document te zien als documentvoorbeeld
- Op het moment dat de productaanvraag wordt aangemaakt als item in de ZAC dan kan het document uit de Inbox documenten gehaald worden

Aanmaken zaak
- Vanuit werklijst kan een productaanvraag geopend worden

NB: aanmaken zaak wordt verder uitgewerkt tijdens refinement 19 januari

**Comment by robertverboom** [comment]
Pas oppakken als #2249

**Comment by HilbrandHurtak** [comment]
Getest op de Zandbak omdat daar data(Uit open formulieren) aanwezig was: 

Werklijst 'Productaanvragen' introduceren. Hier komt iedere productaanvraag uit Overige Registraties in die niet tot een zaak heeft geleid: **Er staan wat aanvragen melding klein evenement zonder een zaak maar wel met een aanvraag formulier: TEST OK**
In de productaanvraag is het PDF document te zien als documentvoorbeeld: **TEST OK**
Op het moment dat de productaanvraag verschijnt in de werklijst 'Productaanvragen' (vanuit een Open notificatie) dan kan het bijbehorend document uit de Inbox documenten gehaald worden: **Geen idee hoe dit te testen**

Aanmaken zaak
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/1c6a6743-6709-4c9d-b5dc-3025e240f8ec)

In de werklijst productaanvraag is te zien:
productaanvraagtype: **TEST OK**
id van initiator (persoon of vestiging) *NIET TE TESTEN. Was geen aanvraag met DigiD of e-Herkenning te vinden)
PDF doc van ingevulde formulier **TEST OK**
datum ontvangst (uit de notificatie halen): **Ontvangstdatum wordt getoond. TEST OK**
Vanuit werklijst kan een gebruiker met een knop een zaak starten: **TEST OK**
Zaak aanmaken scherm opent: **TEST OK**
Kies zaaktype: **TEST OK**
initiator is gevuld. Als productaanvraag anoniem is dan kan gebruiker evt zelf initiatior kiezen: **TEST OK door zelf te kiezen**
kanaal default vullen met 'e-formulier': **TEST OK**
toelichting default vullen met 'Vanuit productaanvraag van type xxxx'. Deze kan door de gebruiker worden overschreven in Zaak aanmaken scherm. **TEST OK**
Nadat zaak is aangemaakt wordt PDF als startformulier toegevoegd aan zaak: **FOUT 500**
Nadat zaak is aangemaakt moet de productaanvraag uit de werklijst "Productaanvragen' gehaald worden **Niet kunnen testen vanwege het niet aanmaken van een zaak**

**Comment by HilbrandHurtak** [comment]
Bij het starten van een zaak vanuit de inbox productaanvragen gaat het fout. Nadat het zaaktype is geleselcteer en de bonodigde gegevens zijn ingevuld komt er een 500 foutmelding

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/f56625c8-4bc4-4606-b02c-93b3e1e77631)

**Comment by HilbrandHurtak** [comment]
@RoyBuis . Ik heb dit getest op de zandbak. Het gaat fout als je een zaak wilt aanmaken. Heb ditverse zaaktypes geprobeerd maar krijg steeds 500 foutmeldingen

**Comment by robertverboom** [comment]
Wordt opgelost als #2178 goed is ingericht

**Comment by robertverboom** [comment]
@HilbrandHurtak productaanvraagtype van formulier 'Melding klein evenement' veranderd naar 'test' wat niet overeen komt met een productaanvraag van een zaaktype in de ZAC op de zandbak. Hierdoor komt de aanvraag in de inbox productaanvragen terecht, waarna je daar een zaak kan koppelen. 

Let op; er zijn blijkbaar meerdere formulieren, je hebt de onderste nodig: melding klein evenement

**Comment by HilbrandHurtak** [comment]
Getest met melding klein evenement.

Formulier komt inderdaad binnen bij Inbox productaanvragen.
Formulier is te openen en leesbaar
Zaak gestart vanuit de inbox productaanvragen
Zaak is aangemaakt
Aanvraag en bijlage zijn als afzonderlijke documenten aan de nieuwe zaak gekoppeld
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/a05d306d-66d1-45a2-9d80-91955e01416f)

TEST OK
