### ISSUE TITLE
Refactor werklijsten

### ISSUE THREAD

**Issue by bartlukens-atos** [NL-AMS-LOCGOV/zaakafhandelcomponent#321]
#79 verder refactoren zodat het kiezen van kolommen zonder 'hacks' werkt

**Comment by robertverboom** [comment]
test ok

**Comment by nl23727** [comment]
E.e.a. is niet helemaal correct qua default kolommen die nu getoond worden:

1. Ga naar Zaken - Afgehandelde zaken
2. Selecteer GroepA

Expected
De volgende default kolommen die getoond worden:
Zaaknummer
Zaaktype
Startdatum
Einddatum
Aanvrager
Behandelaar
Resultaat

Actual
Zaaknummer
Status
Zaaktype
Groep
Startdatum
Aanvrager
