### ISSUE TITLE
7.1.X Documenten toevoegen aan een zaak

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#328]
Verzamelbalk voor user stories m.b.t. documenten toevoegen aan zaak

**Comment by GertrudeKampherbeek** [comment]
bijbehorende urserstory's

- 7.1.1 Document(en) toevoegen met sjabloongenerator door Gebruiker 
- 7.1.2 Documenten (enkelvoudig document of meerdere tegelijk) toevoegen door Gebruiker vanaf een device 
- 7.1.3 Document vanuit een office programma toevoegen door Gebruiker 
- 7.1.4 Document vanuit een bron-applicatie toevoegen door Gebruiker 
- 7.1.5 Document vanuit een verzamelbak toevoegen door Postregistratie 
- 7.1.6 Documenten met scansoftware voorzien van automatische documentherkenning toevoegen door Postregistratie 
- 7.1.7 Documenten vanuit een overheidsloket en/of eigen loket toevoegen aan een zaak door burger/bedrijf 
- 7.1.8 Documenten vanuit een extern taakformulier toevoegen aan een zaak door burger/bedrijf 
- 7.1.9 Documenten toevoegen aan een afgehandelde zaak door recordmanager 
- 7.1.10 Vanuit ‘verzamelbak’ documenten direct een nieuwe zaak aanmaken

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Stories zijn gerealiseerd. Eventuele openstaande worden los opgepakt.
