### ISSUE TITLE
7.1.2 Documenten (enkelvoudig document of meerdere tegelijk) toevoegen door zaakbehandelaar

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#330]
***Als*** Zaakbehandelaar

***Wil ik*** Op eenvoudige wijze bij een zaak een document/ meerdere documenten tegelijk kunnen uploaden

***Zodat*** de zaak kan worden aangevuld met de voor de zaak relevante documenten zodat het dossier compleet is

***

### Acceptance criteria:
- Gebruiker moet de actie kunnen uitvoeren met zo min mogelijk klikken 
- Gebruiker kan de actie in zelfde scherm starten 
- Gebruiker kan de actie repeterend uitvoeren voor meerder documenten tegelijk
- Document(en) krijgt/krijgen verplichte metadata (MDTO) 
- Gebruiker kan metadata toevoegen (Wat wordt hier mee bedoeld, welke overige metadata?) Refinement: navragen wat hier de behoefte is, Sander

***
### Prioriteit
- Must haves
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Vanuit een zaak kan een document aan een zaak worden toegevoegd. Het document is daarna aan de zaak gekoppeld.

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het menu met de actie [Document toevoegen] een document aan de zaak koppelen
- Gebruiker kan zelf de metadata van het document bepalen. Een aantal metadata is vooringevuld en kan door de gebruiker worden aangepast. De auteur wordt vooringevuld met de naam van de ingelogde gebruiker en voor de titel wordt de bestandsnaam, zonder de extensie, gebruikt.
- Met de [Toevoegen] knop wordt het document aan de zaak gekoppeld. Als de nog een document toevoegen checkbox is aangevinkt dan kan direct een volgend document worden toegevoegd waarbij de ingevulde metadata van het vorige document worden overgenomen.

**Comment by RoyBuis** [comment]
Story is grotendeels al gerealiseerd. Volgende punten tijdens refinement bespreken:
1 Op eenvoudige wijze meerdere documenten toevoegen waarbij ingevulde metadata uit eerste document vooringevuld bij een volgende worden gebruikt
2 Documenttitel laten voorinvullen met de bestandsnaam
3 Bestand kunnen toevoegen met drag en drop

**Comment by RoyBuis** [comment]
Refinement 14-2:
Aanpassingen:
- Bijlage upload bovenaan scherm
- Naam van het bestand wordt gebruikt om de documenttitel te vullen. Als de gebruiker al de documenttitel heeft ingevuld dan wordt die titel niet overschreven
- Drag en drop bij uploadveld is technisch lastig te maken, voor nu uit deze story halen. Eventueel in de toekomst nieuwe story voor schrijven.
- Mogelijk om meerdere documenten te kunnen oploaden. Extra knop beschikbaar maken 'Nog een document toevoegen'
- Ingevulde metadata van het eerste document worden vooringevuld getoond bij het volgende document. Dit betreft Doc type, vertr aand, creatiedatum, auteur, status en taal. Andere velden moet leeg worden gemaakt.
- Vertr aanduiding default laten vullen op basis van gekozen documenttype. In Open zaak heeft ieder informatieobject type een default vertr aand ingesteld.
- Auteur veld default laten vullen met naam van ingelogde gebruiker. Voor- en achternaam tonen.
- Taal veld default vullen met 'Nederlands' NB: taal moet op basi van ISO code, zie gerelateerd issue #450

**Comment by bartlukens-atos** [comment]
Checkbox 'Nog een document toevoegen' 
Bij aangevinkt:

- Document toevoegen als er op de opslaan knop geklikt wordt
- Bepaalde velden worden geleegd (zie hierboven)
- Vinkje blijft aangevinkt
- Na toevoegen terug naar de zaak view

**Comment by robertverboom** [comment]
test ok

**Comment by CommonGroundGroningen** [comment]
**Testcase 1**
Toevoegen van 1 document
**Verwachting**
Toevoegen van 1 document wordt correct uitgevoerd
3 kliks zijn nodig om 1 document toe te voegen
Toevoegen van een document kan gestart worden vanuit het overzichtsscherm
Document wordt voorzien van metadata
**Resultaat**

**Testcase 2**
Toevoegen van metadata aan toegevoegd document van testcase 1
**Verwachting**
Metadata kan toevoegd worden
**Resultaat**

**Testcase 3**
Toevoegen van 1 x 3 documenten
**Verwachting**
Toevoegen van 3 documenten wordt correct uitgevoerd
5 kliks zijn nodig om 3 documenten toe te voegen
Toevoegen van een document kan gestart worden vanuit het overzichtsscherm
Alle documenten worden voorzien van metadata
**Resultaat**

**Testcase 4**
Toevoegen van 3 x 3 documenten
**Verwachting**
Toevoegen van 3 documenten wordt correct uitgevoerd
15 kliks zijn nodig om 9 documenten toe te voegen
Toevoegen van een document kan gestart worden vanuit het overzichtsscherm
Alle documenten worden voorzien van metadata
**Resultaat**

**Comment by HilbrandHurtak** [comment]
Commentaar aan #1457 toegevoegd. Het gaat om de mogelijkheid om ontbrekende of onjuiste metadata bij een aanwezig document te kunnen toevoegen/wijzigen. De knop aanpassen ontbreekt. In de oude e-Suite bestaat deze mogelijkheid wel (zie schermafdrukken bij #1457

**Comment by RoyBuis** [comment]
### Refinement SN, RV & RB

Definitieve documenten kunnen alleen met de rol 'recordmanager' gewijizgd worden. Dit kan getest worden door een gebruiker met deze rol. 
Dit comment heeft met name betrekking op #1457 maar dit issue is al gesloten. Er kan getest worden vanuit dit issue.

**Comment by HilbrandHurtak** [comment]
Test ok. Tevens nog getest of je met de rol Coordinator definitieve documenten kon bewerken. Dat was niet het geval en conform de verwachting
