### ISSUE TITLE
7.1.5 Document vanuit een verzamelbak toevoegen door Postregistratie

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#331]
***Als*** Registrator

***Wil ik*** Ontvangen documenten scannen naar een digitale ‘verzamelbak’ en van daaruit op eenvoudige wijze aan een zaak kunnen toevoegen 

***Zodat*** De door de organisatie ontvangen documenten aan bestaande zaken van zaakbehandelaars kan toevoegen ~~of een nieuwe zaak kan aanmaken vanuit het document uit de verzamelbak.~~

***

### Acceptance criteria:
- registrator moet de actie kunnen uitvoeren met zo min mogelijk klikken 
- Document(en) krijgt/krijgen verplichte metadata (MDTO) 
- registrator kan metadata toevoegen  (Wat wordt hier mee bedoeld, welke overige metadata?)
- registrator kan vanuit de verzamelbak een of meerdere documenten aan een bestaande zaak toevoegen 
- ~~registrator kan vanuit de verzamelbak een nieuwe zaak aanmaken, toewijzen en een of meerdere documenten toevoegen~~ Andere story voor aanmaken

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

**Comment by GertrudeKampherbeek** [comment]
de nieuwe hierboven gewenste userstory is 7.1.10

**Comment by robertverboom** [comment]
Refinement 05-05:
- bij notificatie nieuw document, het document toevoegen aan lijst van nieuwe documenten. (zoals bij ontkoppelde documenten)
- Bij notificatie nieuw document zaak koppeling, het document weer verwijderen uit lijst van nieuwe documenten.
- zelfde tabel gebruiken
- nieuwe lijst heet Inbox documenten

**Comment by hansmarks** [comment]
Een actor in de open_notificaties zou ook hiervoor handig zijn: https://github.com/VNG-Realisatie/gemma-zaken/issues/1965
