### ISSUE TITLE
6B.26.X Advies inwinnen Externe (keten) partner/ organisatie

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#333]
***Als*** Zaakbehandelaar

***Wil ik*** vanuit de zaak een extern advies (of meerdere) kunnen uitvragen bij een (keten)partner/organisatie

***Zodat*** ik vanuit 1 applicatie mijn zaak volledig kan afhandelen met een volledig dossier.

***

### Acceptance criteria: Algemeen voor deze epic
- De externe advies uitvraag moet veilig zijn (documenten gaan vaak ook mee)
- De behandelaar moet de externe advies vraag meerdere keren kunnen uitzetten
- De behandelaar moet relevante documenten bij het aanmaken van adviestaak kunnen selecteren
- Meer acceptatiecriteria wordt uitgewerkt in de specifieke user stories  zoals #299.

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Voorbeeld
Bij een evenementmelding moet er soms advies ingewonnen worden bij de brandweer, politie, handhavind, etc. Dat wil je a;ls behandelaar het liefst doen vanuit dezelfde applicatie waar je de zaak behandeld.

**Comment by RoyBuis** [comment]
Refinement:
- Uitzoeken op welke manieren veilig informatie gevraagd of uitgewisseld kan worden, bijvoorbeeld via een portal
- Nieuwe story onder deze epic: in CMMN proces een taak maken voor vastleggen van gevraagde advies. In deze taak in ieder geval vastleggen aan wie advies gevraagd is, keuze uit een tabel. Voorbeeld maken voor taakstartformulier en taakbehandelformulier waarin de velden/labels zijn uitgewerkt.

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Stories zijn gerealiseerd. Eventuele openstaande worden los opgepakt.
