### ISSUE TITLE
7.1.3 Document vanuit een office programma toevoegen door Gebruiker

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#342]
**Als**	: Gebruiker 
**Wil ik**	: Op eenvoudige wijze vanuit een office programma (tenminste Outlook, Word en Excel)  waarin ik werk het document kunnen toevoegen aan een zaak 

**Zodat ik**	: dat document direct bij de zaak kan voegen

**Acceptance criteria**:

- Gebruiker moet de actie kunnen uitvoeren met zo min mogelijk klikken 
- Document(en) krijgt/krijgen verplichte metadata (MDTO) 
- Gebruiker kan metadata toevoegen 

**Prioriteit**
- Must haves

**Comment by RoyBuis** [comment]
Mogelijkheden bespreken in architectuuroverleg. Documenten toevoegen aan Open Zaak?

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Story wordt via PodiumD backlog verder opgepakt.
