### ISSUE TITLE
7.1.4 Document vanuit een bron-applicatie toevoegen door Gebruiker  

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#343]
**Als**	: Gebruiker 
**Wil ik**	: Op eenvoudige wijze vanuit een bron-applicatie* waarin ik werk een document kunnen toevoegen aan een zaak 
**Zodat ik**: dat in niet eerst het document uit de bronapplicatie moet exporteren/opslaan en daarna het zaaksysteem moet openen om het document handmatig toe te voegen  

**Acceptance criteria**:

- Gebruiker moet de actie kunnen uitvoeren met zo min mogelijk klikken 
- Document(en) krijgt/krijgen verplichte metadata (MDTO) 
- Gebruiker kan metadata toevoegen 

**Prioriteit**
- Must haves

*_Bedoeld zijn gekoppelde applicaties bijv. iBurgerzaken, GWS-4all, Key2Burgerzaken, Powerbrowser (IJPY), etc_

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Story wordt via PodiumD backlog verder opgepakt.
