### ISSUE TITLE
7.1.7 Documenten vanuit een overheidsloket en/of eigen loket toevoegen aan een zaak door burger/bedrijf 

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#345]
**Als:** Burger/bedrijf 
**Wil ik:** vanuit een overheidsloket documenten kunnen toevoegen aan mijn lopende zaken  
**Zodat ik:** deze documenten niet op andere wijze bij de overheidsinstantie hoef aan te bieden

**Acceptance criteria:**

- Systeem kan overweg met toevoegen van documenten door burger/bedrijf aan een zaak 
- Document(en) krijgt/krijgen verplichte metadata (MDTO) 
- Zaakbehandelaar / recordmanager kan metadata toevoegen 

Prioriteit
- Must haves

**Comment by RoyBuis** [comment]
Story splitsen in aparte stories voor:

- document aan zaak toevoegen vanuit Mijn loket: meenemen als criterium voor de OIP
- document aan zaak toevoegen vanuit overheidsloket (Mijn overheid)

Bespreken in architectuuroverleg

**Comment by Snijhuis** [comment]
**WG R&A 21-09 bespreken:**
Deze kan gesloten worden.
1. Documenten aan zaak toevoegen in mijn omgeving --> wordt opgepakt via OIP https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/36
2. MijnOverheid loket issues: #674 , #675, #794, #795
