### ISSUE TITLE
7.1.8 Documenten vanuit een extern taakformulier toevoegen aan een zaak door burger/bedrijf

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#346]
**Als:** Burger/bedrijf 
**Wil ik:** documenten naar mijn lopende zaak kunnen uploaden en aan een zaak toevoegen  
**Zodat ik:** deze eenvoudig, digitaal aan kan leveren en waarbij  deze direct in de zaak beschikbaar komen en ik deze niet op ander wijze hoef toe te zenden. 

**Acceptance criteria**:

- Systeem kan overweg met toevoegen van documenten door extern taakformulier
- Document(en) krijgt/krijgen verplichte metadata (MDTO)
- Zaakbehandelaar / recordmanager kan metadata toevoegen 

**Prioriteit**
- Must haves

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Story wordt via PodiumD backlog verder opgepakt.
