### ISSUE TITLE
7.1.9 Documenten toevoegen aan een afgehandelde zaak door recordmanager 

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#347]
**Als:** recordmanager 
**Wil ik:** een documenten aan een afgehandelde zaak kunnen toevoegen  
**Zodat ik:** als recordmanager een zaak compleet kan maken voor archivering 

**Acceptance criteria:**

- Systeem kan overweg met toevoegen van documenten door extern taakformulier 
- Document(en) krijgt/krijgen verplichte metadata (MDTO) 
- Zaakbehandelaar / recordmanager kan metadata toevoegen 
- Specifieke rechten voor recordmanagement waarbij de organisatie kan bepalen aan wie dat recht wordt toegekend 

**Prioriteit**
- Must haves
## Gerealiseerd
- document kan toegevoegd worden aan afgesloten zaak

Niet gerealiseerd:
- rechten / rollen

Systeem kan overweg met toevoegen van documenten door extern taakformulier
- Een afgesloten zaak kan geen openstaande taken hebben

**Comment by GertrudeKampherbeek** [comment]
- volgens mij zijn niet alle velden die nodig zijn om aan de MDTO te voldoen beschikbaar. Nagaan bij de werkgroep Informatiebeheer. Hier is al een userstory vanuit die werkgroep maar die zie ik nog niet in Zenhub.

- in de acceptatie-omgeving heb ik (nog geen) url voor het startformulier waardoor ik niet heb controleren of het document goed en met de juiste data wordt toegevoegd.

**Comment by VictorTielenius** [comment]
Dit zou ook door een andere gebruiker dan Recordmanager mogelijk moeten zijn. Door hiervoor een recht te maken (Toevoegen document aan afgehandelde zaak) kan dit recht aan de rol Recordmanager gekoppeld kunnen worden, maar ook aan een andere rol. 
Dus de rol Recordmanager zou gevuld moeten worden met rechten om bepaalde acties te kunnen en niet met een verzamelrecht waar diverse acties in zitten.

**Comment by VictorTielenius** [comment]
Document is afgehandelde zaak (in ZAAK-2023-0000000039) toe te voegen (OK), maar ook met Documentstatus In bewerking. Zou alleen status Definitief moeten zijn bij een afgehandelde zaak. = NOK

**Comment by KarinMasselink** [comment]
@VictorTielenius volgens mij kan dit ticket dit op basis van de acceptatiecriteria gesloten worden. Dat documenten een status definitief moeten krijgen bij het opvoeren was geen vereiste in het ticket. Ik heb hem al wel gezien, laten we die nog even bespreken met de WG. Maar dan is dat een andere userstory op basis van dit ticket.
