### ISSUE TITLE
7.2.1 Documentinhoud d.m.v. preview bekijken door gebruiker 

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#349]
**Als :** Gebruiker 
**Wil ik:** Bij een zaak wil een documentvoorbeeld/preview kunnen inzien 
**Zodat ik:** snel de inhoud van het document kan raadplegen. 

**Acceptance criteria:**

- vanuit de preview moet het document geprint kunnen worden

 **Prioriteit**
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

Een zaakbehandelaar kan bij een document bij een zaak in het ZAC een preview bekijken. Hiervoor hoeft het document dus niet in een andere applicatie, bijvoorbeeld Acrobat Reader, geopend te worden. Deze functie geldt voor bestandstypen PDF.
Belangrijkste functionaliteit:
- de documentpreview is vanuit het overzicht documenten beschikbaar
- de preview wordt geopend door op de titel van het document te klikken

**Comment by RoyBuis** [comment]
Eerder gerefined via duplicate issue #72 :
Uitzoeken wat allemaal kan met office documenten, tevens kijken naar PDF viewer

**Comment by bartlukens-atos** [comment]
Er zijn momenteel geen gratis document viewers voor office documenten die we kunnen gebruiken, zonder de bestanden naar een externe partij te uploaden. Je zit al snel aan een betaalde licentie vast om documenten te kunnen previewen. (Bijv, PDFTron, Leadtools )


Voor PDF en plaatjes kan er wel een preview gemaakt worden. Met bijvoorbeeld https://mozilla.github.io/pdf.js/ of een angular component https://github.com/intbot/ng2-pdfjs-viewer

**Comment by RoyBuis** [comment]
Refinement 21-3:
Vervolg:

- Office documenten is moelijk uitvoerbaar, voor nu niets mee doen
- Voor PDF-documenten en afbeelding bestanden maken we identieke oplossing als e-Suite, zie ook links in vorig comment


Functioneel:

- Document is te openen door op de titel te klikken. Bart en Robert bespreken de mooiste manier hiervoor
- Document wordt na klikken geopend onder de documentregel

Schatting: 21 uren

**Comment by VictorTielenius** [comment]
Bij een zaak wil een documentvoorbeeld/preview kunnen inzien.
vanuit de preview moet het document geprint kunnen worden.

Bij Zaak ZAAK-2022-0000000034 een PDF document toegevoegd, en deze is via icoon in preview te openen. Geopend in Preview kan ik deze printen.
