### ISSUE TITLE
7.3.2 Documenten in een zaak openen, bewerken en opslaan door gebruiker  

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#351]
**Als:** Gebruiker 
**Wil ik:** Documenten binnen een zaak met Office openen (compatible met Office) kunnen bewerken en als nieuwe documentversie opslaan 
**Zodat ik**: correcties in het document voor de zaakbehandelaar kan aanbrengen en niet eerst het document moet downloaden/opslaan voor bewerking 

**Acceptance criteria:**
- Bestandstype Office ondersteunen
- RTF, ODF ook mogelijk? 

**Prioriteit**
- Must haves
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een MS Office document dat aan een zaak is gekoppeld kan vanuit de documentgegevenspagina geopend en aangepast worden via de [Bewerken] knop. Na het opslaan van het document wordt een nieuwe versie gecreëerd in het DRC.

***Belangrijkste functionaliteiten:***
- De [Bewerken] knop is beschikbaar op de documentgegevenspagina van documenten die niet definitief zijn en van het type dat bewerkt kunnen worden
- Documenten van het type Word, Excel of PowerPointPresentation kunnen worden bewerkt.
- Het bewerken van het document wordt als 'nieuwe versie' met een toelichting in de historie van het document opgenomen

**Comment by RoyBuis** [comment]
### Backlog refinement

- vergelijkbaar met webdav functionaliteit zoals in e-Suite. Is dit mogelijk met Google Cloud?
- user story aanscherpen voor refinement sessie

**Comment by robertverboom** [comment]
WebDav van e-Suite aan de praat krijgen op GCP omgevingen

**Comment by andyverberne** [comment]
https://www.comparitech.com/net-admin/webdav/#:~:text=WebDAV%20servers%20and%20clients%20still%20going%20strong,-WebDAV%20is%20a&text=In%20many%20of%20its%20use%20cases%2C%20WebDAV%20is%20being%20supplanted,encountered%20in%20many%20different%20applications.

**Comment by andyverberne** [comment]
Na het uitzetten van de Identity Aware Proxy bleek WebDAV te werken op GCP7.

**Comment by andyverberne** [comment]
Lock document  (als het nog niet gelocked is) op het moment dat het document bewerkt wordt

**Comment by andyverberne** [comment]
ToDo er moet nog een websocket event gegooid worden nadat er een nieuwe versie is aangemaakt zodat het scherm refreshed

**Comment by andyverberne** [comment]
@robertverboom : WebDAV werkt standaard niet op develop. Wel op zandbak en accept. Dat komt door de Identity Aware Proxy. Maar deze kan ik best even tijdelijk uitzetten op develop zodat je kunt testen,

**Comment by VictorTielenius** [comment]
De [Bewerken] knop is beschikbaar op de documentgegevenspagina van documenten die niet definitief zijn en van het type dat bewerkt kunnen worden
Documenten van het type Word, Excel of PowerPointPresentation kunnen worden bewerkt.
Het bewerken van het document wordt als 'nieuwe versie' met een toelichting in de historie van het document opgenomen

Een Word document in zaak ZAAK-2022-0000000081 toegevoegd (Status In Bewerking) + bewerkt (via WebDAV). OK
In Historie van document: Versie + Registratiedatum: OK
Een Definitief (Word) document: Geen "Bewerken" knop aanwezig. OK
Excel: OK (Status document Definitief + In bewerking getest)
