### ISSUE TITLE
7.10.1 Configuratie bestandsformaten documenten door beheerder

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#352]
Als	: Functioneel beheerder 

Wil ik	: Bestandsformaten kunnen instellen die door het systeem geaccepteerd worden als een gebruiker een document toevoegt  

Zodat ik	: niet kan toestaan dat kwetsbare bestandformaten aan een zaak toegevoegd kunnen worden 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
352
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Het is mogelijk om aan de lijst van toegestane bestandsformaten extra bestandsformaten toe te voegen. Dit gebeurt in de omgevingsvariabele 'ADDITIONAL_ALLOWED_FILE_TYPES'. Documenten die van een extra toegevoegd bestandsformaat zijn hebben in de ZAC het standaard icoon.

***Belangrijkste functionaliteiten:***
- Omgevingsbeheerder kan de lijst van van toegestane bestandsformaten uitbreiden via de variabele ADDITIONAL_ALLOWED_FILE_TYPES' door het bestandsformaat hier aan toe te voegen

**Comment by RoyBuis** [comment]
### Refinement 27-10

Momenteel is er een lijst van toegestane bestandsformaten, zie vorig comment. Er komt een globale environmentvariabele met een lijst van extra bestandsextensies. We maken één icoon voor de extra extensies (fa-file) 
Een toevoeging aan deze lijst kan door een verzoek bij de system integrator in te dienen.

**Comment by Sevdiya** [comment]
Hoe kan ik dit testen? Ik zie documenten nergens bij beheerinstellingen.

**Comment by RoyBuis** [comment]
@Sevdiya De omgevingsvariabele waarin de bestandstypen zijn te configureren is niet voor een ZAC beheerder toegankelijk. Deze story is dus zo niet door jullie te testen. Er wordt nu via issue #2377 een bestandstype aan de variabele toegevoegd waardoor je dit voor het type .msg getest kan worden.

**Comment by KarinMasselink** [comment]
Is opgeleverd.
