### ISSUE TITLE
7.3.3 Documenten in een zaak openen, bewerken en opslaan door controleur/accordeur

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#353]
**Als:** Controleur / Accordeur van een document 
**Wil ik:** Office documenten en andere documenten binnen een zaak die ik moet accorderen, kunnen bewerken en als nieuwe documentversie opslaan 
**Zodat ik:** correcties in het document voor de zaakbehandelaar kan aanbrengen en niet eerst het document moet downloaden/opslaan voor bewerking of het document voor correctie terug hoef te doen naar de zaakbehandelaar 

Acceptance criteria:
-

Prioriteit
- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een MS Office document dat aan een zaak is gekoppeld kan vanuit de documentgegevenspagina geopend en aangepast worden via de [Bewerken] knop. Na het opslaan van het document wordt een nieuwe versie gecreëerd in het DRC.

**Belangrijkste functionaliteiten:**

De [Bewerken] knop is beschikbaar op de documentgegevenspagina van documenten die niet definitief zijn en van het type dat bewerkt kunnen worden
Documenten van het type Word, Excel of PowerPointPresentation kunnen worden bewerkt.
Het bewerken van het document wordt als 'nieuwe versie' met een toelichting in de historie van het document opgenomen

**Comment by RoyBuis** [comment]
### Refinement SN, RV & RB
Deze functionaliteit is gemaakt via #351 en is reeds beschikbaar. Het recht om dit te doen is nu gekoppeld aan de rol 'behandelaar' en 'recordmanager'

**Comment by VincentHofman** [comment]
Is dit ook van toepassing op definitieve documenten?

**Comment by RoyBuis** [comment]
@VincentHofman Zie de beschrijving bij 'Gerealiseerd', dit kan alleen bij niet-definitieve documenten

**Comment by Sevdiya** [comment]
Getest, document die op definitief stond was te bewerken, opnieuw opgeslagen, werd versie 4. zaak 2023-42. 
Definitieve documenten zou je niet moeten kunnen bewerken. 
Opnieuw ondertekenen werd aangeboden,  we hebben het oondertekend en het document werd versie 5.

**Comment by RoyBuis** [comment]
@Sevdiya Deze story is gerealiseerd vanuit de persona 'accordeur'. Een recordsmanager met de rol 'recordmanager' mag wel definitieve documenten bewerken.

**Comment by Sevdiya** [comment]
Reactie gemeente Zwolle / RM / Maria Willems 
Ik kan wel een nieuwe versie maken, maar een document bewerken kan niet, dan wordt Word opgestart, maar krijg ik de melding dat ‘wij problemen ondervindt bij het maken van verbinding met de server’. 
Het is volgens mij níet de bedoeling om definitieve documenten aan te kunnen passen, zeker niet als ze al verzonden zijn. Wel moeten de metadata aangepast kunnen worden, maar ik weet niet hoe dat dan moet.

**Comment by RoyBuis** [comment]
@Sevdiya Jouw gebruiker heeft de recordmanager rol

In deze story is het bewerken van een document gerealiseerd. Met bewerken wordt hier het bewerken van het bestand bedoeld via de actie [Bewerken]. Om dit te doen wordt de webdav techniek gebruikt, deze kan in de Zandbak getest worden. Hier trad vanochtend inderdaad een fout op vandaar dat je een foutmelding kreeg, inmiddels is dit opgelost.

Deze bewerken functionaliteit is alleen beschikbaar voor documenten die niet de status 'Definitief' hebben. Echter, als een gebruiker de recordmanager rol heeft dan mag die definitieve documenten wijzigen en dus ook het bestand bewerken. Als dit anders zou moeten werken dan graag met de werkgroep Refinement bespreken om hier een user story van te maken.

**Comment by Sevdiya** [comment]
@RoyBuis dan klopt het.
