### ISSUE TITLE
7.3.4 Documenten in een zaak openen, bewerken en opslaan door recordmanager 

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#354]
**Als:** Recordmanager 
**Wil ik:** Office documenten en ???-documenten binnen een zaak, kunnen bewerken en als nieuwe documentversie opslaan. Dit moet ook kunnen binnen afgehandelde zaken en definitieve documenten. 
**Zodat ik:** fouten kan herstellen, correcties in het document voor de zaakbehandelaar kan aanbrengen en niet eerst het document moet downloaden/opslaan voor bewerking of het document voor correctie terug moet doen naar de zaakbehandelaar 

Acceptance criteria:

- Ontgrendelen van door zaakbehandelaar vergrendelde documenten 

**Prioriteit**
- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een MS Office document dat aan een zaak is gekoppeld kan vanuit de documentgegevenspagina geopend en aangepast worden via de [Bewerken] knop. Na het opslaan van het document wordt een nieuwe versie gecreëerd in het DRC.

**Belangrijkste functionaliteiten:**

- De [Bewerken] knop is beschikbaar op de documentgegevenspagina van documenten die niet definitief zijn en van het type dat bewerkt kunnen worden
- Documenten van het type Word, Excel of PowerPointPresentation kunnen worden bewerkt.
- Het bewerken van het document wordt als 'nieuwe versie' met een toelichting in de historie van het document opgenomen

**Comment by Snijhuis** [comment]
WG R&A 18-05:
Zie comments hierboven. Groot deel van de functionaliteit wordt al gebouwd in stories https://app.zenhub.com/workspaces/dimpact-refinement-620a77ef5ed231001123e692/issues/nl-ams-locgov/zaakafhandelcomponent/358 en https://app.zenhub.com/workspaces/dimpact-refinement-620a77ef5ed231001123e692/issues/nl-ams-locgov/zaakafhandelcomponent/351

**TO DO** 

Story schrijven over het vergrendelen en ontgrendelen van documenten. Bij de acc-criteria rekening houden met:

1. Wie mag vergrendelen
- Afhankelijk van rechten op zaaktype mag je wel/niet document van die zaaktypen vergrendelen?
- Een recordmanager mag altijd vergrendelen? 

2. Wie mag ontgrendelen?
- In principe alleen de user die het document heeft vergrendeld?
- Is dat nog aan te passen?
- Recordmanager mag altijd ontgrendelen?

**Comment by Snijhuis** [comment]
Stories voor vergrendelen aangemaakt:
- #1054
- #1055

**Comment by Snijhuis** [comment]
Deze story is opgeleverd. Met Webdav kun je documenten bewerken (in principe nog alle rollen). 
Bij de autorisaties kunnen we kijken of bepaalde functionaliteiten aan een rol gekoppeld horen te worden.

**Comment by RoyBuis** [comment]
Deze is gerealiseerd via issue #351
