### ISSUE TITLE
7.10.4 Configuratie documenttypen door beheerder 

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#357]
Als	: Beheerder 

Wil ik	: Documenttypen kunnen koppelen aan een zaaktype 

Zodat ik	: kan voldoen aan de regelgeving m.b.t archivering 

***

### Acceptance criteria:

- documenttypen moeten selecteerbaar zijn uit een samen te stellen standaard lijst (bijv. referentietabel) 

- Epic 13.x moet beschikbaar zijn  

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
- Should haves
- Could haves
- Won't haves

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Dit kan in Open Zaak gedaan worden.
