### ISSUE TITLE
7.3.5 Documenten in een zaak vervangen door Zaakbehandelaar  

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#358]
**Als:** Zaakbehandelaar 
**Wil ik:** Een bestaand document in een zaak vervangen door een nieuwe versie te uploaden. 
**Zodat ik:** een betere/correcte versie van het document bij de zaak kan plaatsen 

**Acceptance criteria:**

- De mogelijkheid ‘uploaden’ moet op documentniveau beschikbaar zijn. 

**Prioriteit**
- Must haves
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Voor een document dat aan een zaak is gekoppeld kan vanuit de documentgegevenspagina een nieuwe versie van het document worden toegevoegd. Bij het maken van de nieuwe versie kan zowel het bestand als de metadata aangepast worden.

***Belangrijkste functionaliteiten:***
- De [Nieuwe versie] knop is beschikbaar op de documentgegevenspagina van documenten die aangepast mogen worden
- Gebruiker kan een nieuw bestand aan het document toevoegen en bepalen welke metadata aangepast moeten worden
- Alle aangepaste metadata worden als wijziging in de historie van het document opgenomen

**Comment by RoyBuis** [comment]
### Backlog refinement
Sander bespreekt prio met werkgroep

**Comment by RoyBuis** [comment]
### Refinement 28-4

**Te realiseren**

- Gebruiker kan een nieuw bestand toevoegen via actie in linker menu (side nav)
- Naam actie: Nieuwe versie toevoegen
- Gebruiker kan in het side nav dialoog naast het nieuwe bestand toevoegen ook de metadata bewerken.

Niet in deze story: het inzien van eerdere versies van een document

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Document aan zaak toegevoegd
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/439e8297-bb01-4fa8-bb56-d5a68af5922c)

Optie nieuwe versie: Nieuw bestand toegevoegd. Document Historie is bijgewerkt. Akkoord
Voorgaande versies zijn te downloaden en te openen: Akkoord

Metadata bewerken kan alleen door het toevoegen van een nieuwe versie. Er is geen functie om dit afzonderlijk te doen. Akkoord


Optie Bewerken: Actuele versie wordt geopend en wordt na bewerking als nieuwe versie opgeslagen. Wijziging was te zien: Akkoord
