### ISSUE TITLE
7.10.5 Configuratie keuze documentsjablonen door beheerder 

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#359]
Als	: Beheerder 

Wil ik	: Documentsjablonen* kunnen koppelen aan een zaaktype  

Zodat ik	: deze beschikbaar kan stellen aan de zaakbehandelaar  

***

### Acceptance criteria:

- *Sjablonen zijn die sjablonen die beschikbaar zijn in de eigen documentgeneratie-tool (SmartDocuments / iWriter)   
- Bij deze Userstory ook 7.1.1 in de gaten houden 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
- Should haves
- Could haves
- Won't haves

**Comment by Snijhuis** [comment]
Deel 1 gerealiseerd (integratie met SmartDocs).
Deel 2 wordt nog opgepakt.
Daarna kan deze getest worden

**Comment by RoyBuis** [comment]
### Refinement SN, RV, RB & KM

De inrichting van sjablonen wordt in SD gedaan en dus niet meer via de ZAC, dit wordt via story #1599 gerealiseerd. 
Dit issue sluiten we daarom
