### ISSUE TITLE
 7.9.1 Documenten in een zaak opslaan als gefixeerd PDF-exemplaar door systeem

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#360]
Als	: systeem 

Wil ik	: Documenten met status ‘definitief’ omzetten naar archiefwaardig exemplaar 

Zodat ik	: kan voldoen aan de archiefwetgeving 

***

### Acceptance criteria:
- Documenten automatisch omzetten naar PDF/A of dan geldend archiefwaardig exemplaar 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
- Should haves
- Could haves
- Won't haves

**Comment by RoyBuis** [comment]
### Backlog refinement
Bespreken in architectuuroverleg

**Comment by Snijhuis** [comment]
24-08 WG Refinement

Oppakken in ZAC. Nog wel twee vragen uitgezet bij WG Informatiebeheer:

- Documenten definitief maken bij afhandelen zaak? NB. document kan wel aan meerdere zaken gekoppeld zijn.
- Bij handmatig documentstatus naar definitief zetten: document ook archiefwaardig maken?

**Comment by robertverboom** [comment]
Een zaak mag niet van Archiefstatus "De zaak cq. het zaakdossier is nog niet als geheel gearchiveerd." veranderen als alle toegevoegde enkelvoudige informatieobjecten (documenten) de status: "Gearchiveerd" hebben. 

Wanneer enkelvoudige informatieobjecten de status: "Gearchiveerd" moet het enkelvoudige informatieobject een duurzaam, niet-wijzigbaar formaat hebben. (denk aan PDF-A)

Ofwel, wanneer een zaak is beëindigd moeten alle enkelvoudige informatieobjecten de status "gearchiveerd" krijgen en een duurzaam, niet-wijzigbaar formaat hebben?

**Comment by GertrudeKampherbeek** [comment]
deze vervalt in overleg met de werkgroep Informatiebeheer en gaat verder in ....
