### ISSUE TITLE
7.9.2 Documenten in een zaak opslaan als gefixeerd PDF-exemplaar door archiefmedewerker

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#362]
Als	: Archiefmedewerker 

Wil ik	: Documenten in een zaak handmatig kunnen markeren voor omzetten naar archiefwaardig exemplaar 

Zodat ik	: kan voldoen aan de archiefwetgeving 

***

### Acceptance criteria:
-Documenten ook handmatig om te zetten naar PDF/A of dan geldend archiefwaardig exemplaar

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
- Should haves
- Could haves
- Won't haves

**Comment by RikVedder** [comment]
Reactie WG Informatiebeheer:
Concept archiefwaardige versie wordt niet gedefinieerd in bestandsformaat.
"Archiefwaardige" versie wordt gezien als het originele exemplaar van het bestand met bijbehoren metadata.
PDF/A versie wordt heirbij gezien als raadpleegkopie van her originele exemplaar. 

Als : Archiefmedewerker

Wil ik : Documenten in een zaak handmatig kunnen markeren voor omzetten naar archiefwaardig exemplaar

Zodat ik : "Archiefwaardige" documenten kan fixeren binnen een zaakdossier

Acceptance criteria:
-Documenten ook handmatig gefixeerd worden of dan geldend archiefwaardig exemplaar

Zie ook opmerkingen bij https://app.zenhub.com/workspaces/dimpact-refinement-620a77ef5ed231001123e692/issues/nl-ams-locgov/zaakafhandelcomponent/383

**Comment by GertrudeKampherbeek** [comment]
deze vervalt in overleg met de werkgroep Informatiebeheer en gaat verder in ....
