### ISSUE TITLE
7.8.1 Documenten vanuit een zaak verzenden door Zaakbehandelaar/Gebruiker/Postverwerker

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#364]
Als	: Zaakbehandelaar/Gebruiker/Postverwerker 

Wil ik	: Een document vanuit een zaak verzenden / aanbieden bij geadresseerde(n) 

Zodat ik	: een document in digitale versie kan aanbieden 

***

### Acceptance criteria:
- Document kan vanuit de zaak worden gemaild / aangeboden bij Loket overheid (Mijn overheid of Mijn Loket eigen gemeente)

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
- Should haves
- Could haves
- Won't haves

**Comment by VictorTielenius** [comment]
9.3.2. Terugkoppeling via loketfunctionaliteit (Relatie met deze User Storie)
Acceptance criteria:
Definitieve (Status) / extern beschikbare (Publicatie niveau) documenten van een Zaaktype die Extern beschikbaar is op Loket (PIP) tonen.

**Comment by Snijhuis** [comment]
**WG Refinement**
1. Mailen vanuit de zaak kan al (inclusief doc)
2. Documenten bij zaken kan toegevoegd worden. Indien vertrouwelijksheidsniveau **Openbaar** zichtbaar bij de zaak in Mijn loket (OIP).
3. Documenten selecteren en aanbieden naar Mijn Berichtenbox kan nog niet (Zie EPIC)

**Comment by Snijhuis** [comment]
Wordt opgepakt vanuit issue #485. Deze sluit ik daarom als duplicaat
