### ISSUE TITLE
7.4.3 Documenten uit in een zaak ontkoppelen  door Zaakbehandelaar  

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#365]
**Als:** Zaakbehandelaar 
**Wil ik:** Een bestaand document uit in een zaak ontkoppelen 
**Zodat ik:** niet archiefwaardige documenten uit een zaak kan halen 

**Acceptance criteria:**

- Zaakbehandelaar moet reden ontkoppelen aan kunnen geven
- ontkoppelde documenten komen in een verzamelbak 
- Recordmanager bepaald wat met het document in de verzamelbak moet gebeuren 

**Prioriteit**
- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De behandelaar kan vanuit de zaakgegevens pagina de documenten ontkoppelen. In de pop-up moet een reden van ontkoppelen opgegeven worden. 

***Belangrijkste functionaliteiten:***
- Er is een werklijst gemaakt met ontkoppelde documenten. Hier worden ook de redenen weergegeven en opties om documenten weer opnieuw toe te voegen, of te verwijderen.

**Comment by RoyBuis** [comment]
Refinement 21-2:
Mogelijk maken om een document te ontkoppelen van zaak
Als document ook aan andere zaak is gekoppeld dan een waarschuwing tonen
Document komt na ontkoppelen terecht in verzamelbak, dit is een nieuwe tabel in onze database
Verzamellijst komt in menu bovenin als 'Documenten'
In verzamellijst van ieder document id, titel en creatiedatum tonen

Bij ontkoppelen eerst checken of het doc aan een andere zaak gekoppeld is, zo niet dan in de lijst opnemen

Verzamelijst wordt bijgewerkt o.b.v. notificaties
De tabel vullen obv notificaties van zaak-documenten relaties
