### ISSUE TITLE
7.4.4 Documenten uit in een zaak verwijderen door Recordmanager  

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#366]
**Als:** Recordmanager 
**Wil ik:** Een bestaand document uit in een zaak verwijderen 
**Zodat ik:** niet archiefwaardige documenten uit een zaak kan halen 

**Acceptance criteria:**

- verwijderde documenten komen in een prullenbak 
- Recordmanager kan prullenbak legen 
- Recordmanager kan document terugplaatsen uit prullenbak naar een zaak of verplaatsen naar de verzamelbak met ontkoppelde documenten. 

**Prioriteit**
- Must haves

***
## Gerealiseerd

Verwijderen gaat via de ontkoppelknop en vervolgens via de werklijst ontkoppelde documenten
Bij het ontkoppelen komt een reden veld (vrij invulveld) als het document aan 1 zaak gekoppeld is

Knop om te verwijderen wordt toegevoegd per document, incl 'weet u het zeker' 

Belangrijke functionaliteit:
- Knop om te ontkoppelen. 
- Werklijst met ontkoppelde documenten. Knop om documenten voorgoed te verwijderen en knop om document weer aan een zaak te hangen.

**Comment by RoyBuis** [comment]
Refinement 28-3:

Document verwijderen bij zaak:

- Verwijderen gaat via de ontkoppelknop en vervolgens via de Ontkoppellijst
- Bij het ontkoppelen komt een reden veld (vrij invulveld) als het document aan 1 zaak gekoppeld is

Werklijst Ontkoppelde documenten:

- Knop om te verwijderen wordt toegevoegd per document, incl 'weet u het zeker' (hier komt autorisatie op)
- Nieuwe kolom om de ingevulde reden te noemen

**Comment by robertverboom** [comment]
Test ok

**Comment by VictorTielenius** [comment]
In werklijst Ontkoppelde documenten een document verwijderd en document naar een zaak verplaatst
