### ISSUE TITLE
7.5.1   Documentmetadata aanpassen door zaakbehandelaar 

### ISSUE THREAD

**Issue by Renvooi** [NL-AMS-LOCGOV/zaakafhandelcomponent#368]
**Als:** Zaakbehandelaar 
**Wil ik:** Alle documentmetadata van één of meerdere documenten tegelijk in een lopende zaak kunnen aanpassen  
**Zodat ik:** deze juist aanbied voor registratie/archivering 

**Acceptance criteria:**

- documentkenmerk mag niet aangepast kunnen worden

**Prioriteit**
- Must haves

**Comment by RoyBuis** [comment]
### Backlog refinement
duplicaat van #374
