### ISSUE TITLE
7.6.1 Documenten in een zaak aanbieden voor accoord door Zaakbehandelaar 

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#371]
Als	: Zaakbehandelaar 

Wil ik	: Een bestaand document via een taak in een zaak voor akkoord kunnen aanbieden bij een controleur/accordeur 

Zodat ik	: digitaal een document kan laten goedkeuren en ondertekenen 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Met de taak 'Goedkeuren' kan een document digitaal worden ondertekend. Bij het aanmaken van de taak kan het te ondertekenen document, één of meerdere, geselecteerd worden. De behandelaar van de taak kan het document ondertekenen door het document aan te vinken en de taak daarna af te ronden. Bij het document worden in een nieuwe versie het ondertekeningssoort 'Digitaal' en de ondertekeningsdatum vastgelegd en de status wordt op definitief gezet. 

***Belangrijkste functionaliteiten:***
- Gebruiker kan in het menu met de taak 'Goedkeuren' een (of meerdere) document(en) selecteren om te laten ondertekenen
- Gebruiker kan in de taak de documenten ondertekenen door het document aan te vinken. De ondertekening wordt bij het afronden van de taak op het document gezet.
- Gebruiker kan in de taak ook aangeven of het document is goedgekeurd en een toelichting hierop geven.
- De ondertekening is voor de gebruiker zichtbaar met een indicatie op het document, bij een mouse-over is de ondertekeningsinformatie zichtbaar.
- De ondertekening is zichtbaar in de historie van het document, hier is te zien wie er heeft ondertekend

**Comment by RoyBuis** [comment]
Deze is gerealiseerd via issue #489. In feite zijn het duplicaten.

**Comment by HilbrandHurtak** [comment]
Refinement 30-06
Goedkeuren taakscherm voor elk document in de relevante documententabel een checkbox
Naam kolom: Ondertekenen
Na 'opslaan' de vinkjes onthouden **Akkoord**
Na 'opslaan & afronden' worden de aangevinkte definitief en ondertekend **Akkoord**
Bij definitief een toelichting meegeven: Door ondertekenen. **Zit in de taak Akkoord**
Ondertekeningsoort is digitaal **Gegevens zijn vastgelegd Akkoord**
Op documentgegevenspagina een chip: Ondertekend (hover info: ondertekeningsoort - datum)

Getest
- OK
