### ISSUE TITLE
7.6.2 Documenten in een zaak accorderen door Zaakbehandelaar zelf 

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#372]
Als	: Zaakbehandelaar 

Wil ik	: Een document in een zaak kunnen accorderen en ondertekenen  

Zodat ik	: digitaal een document kan ondertekenen en rechtmatigheid kan aangeven 

***

### Acceptance criteria:

- na akkoord moet de status van  het document ‘definitief’ worden 
- In documenthistorie terug kunnen zien wie akkoord heeft gegeven en op welke versie en datum – tijd indicatie 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Documenten kunnen vanuit het document zelf digitaal ondertekend worden. Bij een ondertekening wordt gebruiker die heeft ondertekend en de datum en tijdstip van ondertekening vastgelegd. Een ondertekening leidt altijd tot een nieuwe versie van het document en een aanpassing van de status naar ‘Definitief’. Een versie van een document kan eenmaal ondertekend worden.

***Belangrijkste functionaliteiten:***
- Gebruiker kan op de documentgegevenspagina met de actie [Ondertekenen] een digitale ondertekening zetten
- Het systeem maakt na de ondertekening een nieuwe versie van het document met de status 'Definitief' aan
- Er wordt een grijze 'Is ondertekend' indicatie op het document geplaatst
- Een ondertekening wordt als wijziging van ondertekening in de historie van het document vastgelegd

**Comment by robertverboom** [comment]
Wordt toch net iets anders gevraagd: kunnen accorderen in de zaak ipv een taak

**Comment by robertverboom** [comment]
Gebruikersindicatie toevoegen

**Comment by robertverboom** [comment]
### Refinement 23-08:
- In documentmenu knop met Ondertekenen
- Bevestiging van ondertekenen 
- Policy: Nog geen ondertekening
- Controleren of document op status: Definitief staat

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Document gemaakt
Document als behandelaar ondertekend
Na ondertekening is document definitief
Na ondertekening is er een versie 2 toegevoegd
De gegevens van de ondertekening staan in de historie

Dit is conform Refinement 23-08:


Test OK
