### ISSUE TITLE
7.6.3 Documenten in een zaak accorderen door Accordeur / gemandateerde 

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#373]
Als	: Accordeur 

Wil ik	: documenten die mij ter accordering zijn aangeboden kunnen inzien/controleren en van akkoord voorzien 

Zodat ik	: mijn functie als accordeur kan uitoefenen en daarmee de rechtmatigheid van documenten kan aangeven 

***

### Acceptance criteria:

- na akkoord moet de status van  het document ‘definitief’ worden 
- In documenthistorie terug kunnen zien wie akkoord heeft gegeven en op welke versie en  datum – tijd indicatie 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
- Should haves
- Could haves
- Won't haves

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Een document kan in de ZAC ondertekend worden.
