### ISSUE TITLE
 7.5.1   Documentmetadata aanpassen door zaakbehandelaar

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#374]
Als	: Zaakbehandelaar 

Wil ik	: Alle documentmetadata van één ~~of meerdere~~ documenten tegelijk in een lopende zaak kunnen aanpassen  

Zodat ik	: deze juist aanbied voor registratie/archivering 
***

### Acceptance criteria:
- documentkenmerk mag niet aangepast kunnen worden

***
### Prioriteit
- **Must haves**

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Voor een document dat aan een zaak is gekoppeld kan vanuit de documentgegevenspagina de metadata aangepast worden. Hierdoor ontstaat een nieuwe versie van het document. Dit is alleen mogelijk als de status van het document niet ‘Definitief’ is.

***Belangrijkste functionaliteiten:***
- De [Nieuwe versie] knop is beschikbaar op de documentgegevenspagina van documenten die aangepast mogen worden
- Gebruiker kan een nieuw bestand aan het document toevoegen en bepalen welke metadata aangepast moeten worden
- Alle aangepaste metadata worden als wijziging in de historie van het document opgenomen

**Comment by RoyBuis** [comment]
Refinement 14-4:

Info: https://vng-realisatie.github.io/gemma-zaken/standaard/documenten/index#drc-010

- Om een doc te wijzigen moet deze eerst gelocked worden (eerst een lock in de servicelaag)
- Uitzoeken welke metadata aangepast mogen worden, zie API specs en intro pagina
- Metadata velden kunnen relaties met elkaar hebben en daardoor niet altijd te wijzigen zijn
- Gebruiker kan metadata wijzigen via potlood icoons
- Ieder metadata veld krijgt een optioneel reden veld
- Iedere wijziging wordt in de historie vastgelegd met daarbij de ingevulde reden

Extra:
Metadata veld 'beschrijving' toevoegen aan metadata overzicht, deze is ook wijzigbaar

**Comment by RoyBuis** [comment]
Let op: specs van deze story gewijzigd door nieuwe inzichten in het creeren van nieuwe versie van een document door de Document API

**Comment by robertverboom** [comment]
test ok

**Comment by CommonGroundGroningen** [comment]
Testen Tom en Pieta.
**De [Nieuwe versie] knop is beschikbaar op de documentgegevenspagina van documenten die aangepast mogen worden**
Akkoord

**Gebruiker kan een nieuw bestand aan het document toevoegen en bepalen welke metadata aangepast moeten worden**
Akkoord

**Alle aangepaste metadata worden als wijziging in de historie van het document opgenomen**
De wijziging van de status (is metadata) wordt niet meegenomen bij het toevoegen van een nieuwe versie.
De initiële waarde (documentstatus) die aan het document is meegegeven blijft staan zelfs na aanpassing. Bij het tabblad historie zien we het veld status ook niet terug.

**Om een doc te wijzigen moet deze eerst gelocked worden (eerst een lock in de servicelaag)**
Een document kan gewijzigd worden ongeacht deze gelocked is of niet.

**Metadata velden kunnen relaties met elkaar hebben en daardoor niet altijd te wijzigen zijn**
Zijn er documenttypes toegevoegd die een verplichte status hebben?
We hebben geen voorbeeld om te testen.

**Gebruiker kan de metadata voor 1 document tegelijkertijd bewerken**
Waarom is deze refinement gespecificeerd?

**Gebruiker kan metadata wijzigen via side nav dailoog waarmee alle metadata tegelijk gewijzigd kunnen worden**
Akkoord.

**Naam actie: Nieuwe versie toevoegen**
Onduidelijk wat hier bedoeld wordt.

**Ieder metadata veld krijgt een optioneel reden veld In de side nav dialoog is een reden veld voor de wijziging als geheel die de gebruiker kan invullen**
Er is maar 1 toelichtingsveld?

**Iedere wijziging wordt in de historie vastgelegd met daarbij de ingevulde reden**
Documentstatus veld is niet zichtbaar in de historie. Maar deze wordt ook niet gewijzigd dus waarschijnlijk ander probleem.
**Overzicht van documentmetadata volgens Documenten API
Metadata | Tonen | Bewerken | Toelichting**
Tonen en Bewerken begrijpen we. Het veld Toelichting, wordt hiermee het veld toelichting bedoeld? Of per metadata? Dit zien we namelijk niet terug per metadata.

**Comment by HilbrandHurtak** [comment]
Hertest op de volgende onderdelen:

1. Alle aangepaste metadata worden als wijziging in de historie van het document opgenomen
De wijziging van de status (is metadata) wordt niet meegenomen bij het toevoegen van een nieuwe versie.
De initiële waarde (documentstatus) die aan het document is meegegeven blijft staan zelfs na aanpassing. Bij het tabblad historie zien we het veld status ook niet terug.

2. Om een doc te wijzigen moet deze eerst gelocked worden (eerst een lock in de servicelaag)
Een document kan gewijzigd worden ongeacht deze gelocked is of niet.

3. Ieder metadata veld krijgt een optioneel reden veld In de side nav dialoog is een reden veld voor de wijziging als geheel die de gebruiker kan invullen Er is maar 1 toelichtingsveld?

4. Alleen bewerken als de NIET definitief is
