### ISSUE TITLE
7.5.2  Documentmetadata aanpassen door recordmanager 

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#375]
Als	: Recordmanager  

Wil ik	: Alle documentmetadata van één of meerdere documenten tegelijk in alle zaken kunnen aanpassen 

Zodat ik	: deze juist aanbied voor registratie/archivering 
***

### Acceptance criteria:
- documentkenmerk mag niet aangepast kunnen worden 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
- Should haves
- Could haves
- Won't haves

### Gerealiseerd
Wanneer een document niet op definitief staat, kan de documentmetadata bewerkt worden. Dit resultaat vanuit open-zaak altijd in een nieuwe versie. 

### Niet gerealiseerd
documentmetadata bewerken in bulk

**Comment by VictorTielenius** [comment]
Zie #369
