### ISSUE TITLE
7.3.X Documenten in een zaak bewerken

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#378]
Epic met user stories rond documenten bewerken vanuit een zaak

**Comment by GertrudeKampherbeek** [comment]
•	https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/350 
•	https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/351 
•	https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/353 
•	https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/354 
•	https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/358

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Stories zijn gerealiseerd.
