### ISSUE TITLE
7.4.X Documenten uit een zaak verplaatsen of verwijderen

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#379]
Epic met stories rondom documenten verplaatsen en verwijderen

**Comment by GertrudeKampherbeek** [comment]
- https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/361 
- https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/363  
- https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/365 
- https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/366

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Stories zijn gerealiseerd.
