### ISSUE TITLE
7.6.X Documenten in een zaak accorderen 

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#381]
Epic met stories rondom accorderen/goedkeuren documenten.

**Comment by GertrudeKampherbeek** [comment]
- https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/371 
- https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/372 
- https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/373

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Stories zijn gerealiseerd.
