### ISSUE TITLE
7.7.X Documenten met specifieke autorisaties 

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#382]
Epic met stories rond zaakspecifieke documenten/autorisaties

**Comment by GertrudeKampherbeek** [comment]
- https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/367 
- https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/370

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Stories zijn gerealiseerd, openstaande story wordt los opgepakt
