### ISSUE TITLE
7.9.X Documenten naar PDF-exemplaar 

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#383]
Epic met stories rond archivering van documenten. Hangt nauw samen met zaakarchivering

**Comment by GertrudeKampherbeek** [comment]
- https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/369 
- https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/362

**Comment by RikVedder** [comment]
Reactie WG IB:
Verheldering wat gezien wordt als archiefwaardig exemplaar:

Dit is het originele document met bij behoorde metadata. Wanneer er een PDF/A gemaakt wordt wordt deze gezien als een raadpleeg kopie van dit exemplaar. 

Als er gesproken wordt over functionaliteit wordt vanuit IB perspectief gezien in de vorm van het fixeren van informatie objecten met bijbehorende metadata.

**Comment by GertrudeKampherbeek** [comment]
#2327

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Stories zijn gerealiseerd.
