### ISSUE TITLE
6B.26.3 Advies vragen aan externe organisatie met vastlegging in taak

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#391]
Als zaakbehandelaar
Wil ik aan een externe organisatie gevraagd advies vastleggen bij de zaak
Zodat ik de actie van het uitvragen van het advies en de uitkomst daarvan bij mijn zaak kan vastleggen

Het vragen van advies aan een externe organisatie kan op vele manieren gedaan worden, denk aan een mail of per post. Deze story gaat over het kunnen vastleggen van dat deze actie gedaan is en zodra er een antwoord komt dit antwoord bij de zaak kunnen vastleggen. Dit antwoord kan bestaan uit tekst en/of een document.

De taak moet de volgende velden bevatten:
Taakstart:
adviesvraag, tekstveld V
aan wie, tekstveld V
wijze waarop advies gevraagd is, tekstveld V

Taakbehandel:
uitkomst advies, tekstveld V
documenten bij het advies, upload NV 

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In de behandelfase kan een taak worden aangemaakt waarmee een advies dat aan een externe organisatie is gevraagd wordt vastgelegd. De taak is aan een groep en medewerker toe te kennen zodat de voortgang kan worden bewaakt en de uitkomst in de taak kan worden vastgelegd. Er kunnen ook documenten aan de taak worden toegevoegd.

***Belangrijkste functionaliteiten:***
- Gebruiker kan het menu de taak 'Advies extern' aanmaken, aan een groep en/of medewerker toekennen en de uitkomst in de taak vastleggen
- Gebruiker kan in de taak met de [Document toevoegen] actie een document dat aan het advies gerelateerd is aan de taak toevoegen. Dit document is daarna ook op zaakniveau zichtbaar.
- De taak kan herhaaldelijk worden gebruikt

**Comment by Renvooi** [comment]
Volgt overleg over binnen de werkgroep. Is dit wel wat wij hebben gevraagd? Uit de tekst onder 'Gerealiseerd' en het getoonde scherm maak ik op dat het hier gaat om het vastleggen en beoordelen van een extern advies. M.i. werd er in de US gevraagd om het uitzetten van een extern advies net zoals gerealiseerd is bij Intern advies.

**Comment by HilbrandHurtak** [comment]
In overleg is er een nieuwe beschrijving gemaakt voor deze 'beperkte' externe taak - #1673
Uiteindelijk wil je externe taken kunnen uitzetten waarbij partijen een taakafhandelscherm krijgen (nadat men is ingelogd via e-Herkenning bijvoorbeeld). Of deze taak dan in een OIP omgeving moet komen moet verder worden verkend. De omschrijving van deze story ging dus uit van de definitieve oplossing en dat is dus niet meer actueel. Daarom deze story afgesloten.
