### ISSUE TITLE
BUG: Verplichte veldmarkeringen bij Toevoegen document ontbreken

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#399]
***Steps to reproduce:***

1. Open een openstaande zaak
2. Klik op Document toevoegen

***Expected***
Verwachting is dat er een Verplicht markering staat bij Bestandsnaam. Zonder het invullen van dit veld lukt het niet een document te uploaden

***Actual***
Verplicht markering ontbreekt voor het veld Bestandsnaam . De button toevoegen wordt overigens wel enabled als je alle andere velden vult, m.u.v. deze beide velden (ook status heeft soortgelijk issue, hier is echter een ander issue voor aangemaakt). 

Klein aanvullend consistentie issue: beschrijving --> Beschrijving (met hoofdletter)

**Comment by marcoatos** [comment]
Issue lijkt al te zijn opgelost, heb wel nog een vertaling toegevoegd voor beschrijving, deze ontbrak en dat was de rede waarom hij met kleine letters stond weergegeven.

**Comment by robertverboom** [comment]
test ok
