### ISSUE TITLE
Uitlog functie 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#4]
De gebruiker moet kunnen uitloggen, zodat een andere gebruiker in dezelfde browser kan inloggen

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Als je op profiel icoontje klinkt, kan er uitgelogd worden. 

***Belangrijkste functionaliteiten:***
- Op de browser word je uitgelogd. Dus ook op andere openstaande tabbladen
- Ook op Keycloack wordt de sessie geëindigd

**Comment by robertverboom** [comment]
Time-out op het automatisch uitloggen verlengen

**Comment by RoyBuis** [comment]
Refinement 28-3:

- Uitzoeken hoe uitloggen gemaakt moet worden. Redirect naar een Key Cloak url.
- In Key Cloak bij de client staat een backchannel logout url
- Zonder single logout
- Als gebruiker meerdere vensters open heeft worden allen uitgelogd
- Na het klikken op logout wordt het inlogscherm weer getoond

**Comment by bartlukens-atos** [comment]
Oplossing
- Session van de gebruiker invalideren (weggooien)
- Naar het inlogscherm gaan (redirect naar baseurl)

**Comment by hansmarks** [comment]
https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/pull/771

**Comment by robertverboom** [comment]
Het uitloggen gaat zoals verwacht, echter inloggen met een ander account toont nog de oude gebruiker. pas na het openen van een nieuwe browser wordt de nieuwe gebruiker getoond.

**Comment by andyverberne** [comment]
Ik ben een boek aan het lezen over OpenID Connect. Daarin zit een hoofdstuk over uitloggen maar daar ben ik nog niet aan toe gekomen. Deze anders nog even laten rusten?

**Comment by andyverberne** [comment]
Het uitloggen en daarna inloggen met andere userid werkt correct.
Alleen de gebruikersnaam in het profiel in Angular wordt niet bijgewerkt.
Maar de ingelogdeGebruiker die overal in de code geinjecteerd wordt is wel correct.

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Na het klikken op logout wordt het inlogscherm weer getoond: OK
gebruiker meerdere vensters open heeft worden allen uitgelogd: NOK, "De server heeft code 0 geretourneerd" na poging om werkvoorraad in 2e scherm te openen. Bij opnieuw inloggen in zelfde venster hierna "Bad Request". In nieuwe browser wel in te loggen. 
In Edge Chromium getest.

**Comment by robertverboom** [comment]
@VictorTielenius Graag een nieuw issue (BUG Accepatie) voor aanmaken met de bevindingen.

**Comment by VictorTielenius** [comment]
Acceptatie Bug #994 opgelost. Akkoord
