### ISSUE TITLE
Knop om filters en sorteringen te wissen

### ISSUE THREAD

**Issue by edwinlambregts-atos** [NL-AMS-LOCGOV/zaakafhandelcomponent#409]

**Comment by nl23727** [comment]
1. Selecteer de werklijst - Afgehandelde zaken
2. Selecteer in menu de extra kolommen: Streefdatum en Toelichting
3. Klik vervolgens op de button Wissen

Verwachting is dat de kolommen daarna niet meer getoond worden

Daadwerkelijk blijven de kolommen staan (Niet altijd overigens. Zeer wisselend qua gedrag)

Nog additioneel puntje: als je op dit scherm aankomt begint direct het laden van zaken.

**Comment by robertverboom** [comment]
test ok
