### ISSUE TITLE
Vastleggen en wijzigen van communicatiekanaal bij een zaak

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#410]
***Als*** zaakbehandelaar

***Wil ik*** kunnen zien via welk communicatiekanaal een zaak is aangemaakt en dit kanaal kunnen wijzigen

***Zodat*** ik bij het vastleggen van een onjuist kanaal dit kan corrigeren

***

### Acceptance criteria:
- bij het wijzigen van een kanaal kan een reden worden opgegeven
- de wijziging is terug te vinden in de historie van de zaak

***
### Prioriteit

- Must haves

### Gerealiseerd
Bij het aanmaken van de zaak en op de zaakgegevenspagina kan een communicatiekanaal gezet worden en worden gewijzigd. De wijziging wordt in de historie opgeslagen. 

***Belangrijkste functionaliteiten:***
- communicatiekanalen worden geconfigureerd in open-zaak

**Comment by RoyBuis** [comment]
Refinement 7-2:
Communicatiekanaal komt uit Open zaak. Daar is het omschreven: Het medium waarlangs de aanleiding om een zaak te starten is ontvangen. URL naar een communicatiekanaal in de VNG-Referentielijst van communicatiekanalen.
Bespreken in architectuuroverleg, waar is deze referentielijst te vinden en hoe deze te gebruiken?

**Comment by bartlukens-atos** [comment]
- Helmscript maken
- Client voor maken (genereren)
- Lijst communicatiekanalen ophalen
- Communicatie kanaal opslaan bij de zaak
- Tonen bij de zaak

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
bij het wijzigen van een kanaal kan een reden worden opgegeven
de wijziging is terug te vinden in de historie van de zaak
Zie ook: communicatiekanaal kunnen bewerken op de zaakgegevenspagina#722
Getest:
- Zaak ZAAK-2022-0000000098
Kanaal is niet verplicht bij aanmaken zaak.
Reden is in te vullen, maar niet verplicht.
Wijziging kanaal komt netjes bij de Historie.

**Comment by JosDimpact** [comment]
Besproken in de werkgroep:
Die verplichting op keuze kanaal en verplichting bij de reden wanneer je het kanaal wijzigt zal vrijwel zeker een eis zijn vanuit informatie beheer.
We willen die verplichtingen dus wel: Issue aanmaken obv deze user story.

**Comment by Snijhuis** [comment]
Opgenomen in #1501

**Comment by VictorTielenius** [comment]
communicatiekanaal bij aanmaken zaak nu verplicht. En in de aangemaakte zaak te wijzigen (incl. Reden en dit komt bij de historie)
