### ISSUE TITLE
BUG: Bij invullen onjuist datumformaat wordt er een incorrecte validatiemelding teruggegeven

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#416]
***Steps to reproduce:***

1. Ga naar het zaakaanmaken scherm
2. Vul als startdatum de datum 00-01-2022 in

***Expected***
Verwachting is dat hier een melding komt te staan zoals "Er is een ongeldige datum ingevoerd in het veld Startdatum"

***Actual***
Het Startdatum-veld is niet ingevuld. Vul de vereiste gegevens in!

** Automatische testcases die hierdoor geraakt worden **
#C007 t/m #C010

**Comment by robertverboom** [comment]
test ok
