### ISSUE TITLE
BUG: Validatiemelding ontbreekt op het veld Registratiedatum - bij het aanmaken van een nieuwe zaak

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#417]
***Steps to reproduce:***

1. Ga naar het zaakaanmaken scherm
2. Vul als datum 00-01-2022 in bij het veld Registratiedatum

***Expected***
Verwachting is dat hier een melding komt te staan zoals "Er is een ongeldige datum ingevoerd in het veld Registratiedatum"

***Actual***
Het veld wordt rood gemarkeerd, zonder validatiemelding

** Automatische testcases die hierdoor geraakt worden:
#C007 t/m #C010 raken deze functionaliteit en falen op onderstaande:

**Comment by marcoatos** [comment]
Het is een generiek stukje geworden wat nu elk datumveld valideert. Niet alleen de registratiedatum (startdatum op hetzelfde scherm had hier bijvoorbeeld ook geen validatie voor, maar toonde de required validatie bij een verkeerd ingevulde datum).

Als er op een veld een required validatie zit, wordt altijd eerst gekeken nu naar de validatie of het datum formaat juist is. (zoals bij de startdatum).

**Comment by robertverboom** [comment]
Test ok
