### ISSUE TITLE
Progress indicators tonen bij het laden van componenten

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#423]
***Als*** medewerker

***Wil ik*** inzicht hebben dat ik moet wachten op het laden van de gegevens

***Zodat***  ik een indicatie heb en weet of het product daadwerkelijk geladen wordt, of dat het leeg blijft. 

***

### Acceptance criteria:
 Per Grid een Skeleton loading weergeven dat alvast het grid vult, zodat het scherm minder heen en weer springt. ( https://betterprogramming.pub/the-what-why-and-how-of-using-a-skeleton-loading-screen-e68809d7f702 ) 

***
### Prioriteit
- Should haves

**Comment by RoyBuis** [comment]
Spike inplannen van 8 uur
Doel is om duidelijk te maken welke onderdelen op het scherm aan het laden zijn. dit kan zijn een pagina, een panel of een lijst.

**Comment by edwinlambregts-atos** [comment]
Gebruik gemaakt van https://github.com/willmendesneto/ngx-skeleton-loader

Loader zelf is makkelijk te implementeren, met verschillende stijlen (rond, balkje). Als je creatief bent kun je ze ook combineren.
Ze kunnen animeren maar ook stilstaand getoond worden.

Oogt druk bij sommige schermen. Bij lijsten en Persoonsgegevens hebben we besloten om dit niet toe te passen. Daardoor blijft vrijwel alleen de verkorte zaak over.
