### ISSUE TITLE
Taak toewijzen aan een medewerker

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#428]
***Als*** medewerker

***Wil ik*** bij het aanmaken van een taak ook de groep en/of medewerker kunnen toewijzen

***Zodat*** ik een taak ook aan een specifieke medewerker kan toewijzen

***

### Acceptance criteria:
- De werking moet het zelfde zijn als de generieke werking van het in-bewerkcomponent van behandelaar/groep

**Comment by RoyBuis** [comment]
Refinement:
Groep en behandelaar kiezen op identieke wijze als verdelen functie.
Groep is verplicht, behandelaar is optioneel
Functionaliteit is gelijk voor alle taken
