### ISSUE TITLE
Bedrijf koppelen als initiator bij starten van een nieuwe zaak

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#432]
***Als*** medewerker

***Wil ik*** bij het starten van een zaak in het ZAC een bedrijf als initiator kunnen koppelen

***Zodat*** ik weet wie de aanvrager van de zaak is en de zaak ook op deze naam is terug te vinden
***

### Acceptance criteria:
- De bedrijfsgegevens worden uit een authentieke bron gehaald
- Als de zaak op naam van een bedrijf is aangemaakt moet de relatie tussen de aanvrager en de zaak zichtbaar zijn

***
### Prioriteit
- Must haves

***
### Te realiseren
_Omschrijving van de op te leveren functionaliteit in deze story_

Een ZAC-gebruiker kan bij het aanmaken van een zaak in het ZAC direct een bedrijf als initiator toevoegen. 
Belangrijkste functionaliteit:
- bedrijf kan worden gezocht en geselecteerd in het aanmaken zaak scherm
- geselecteerde bedrijf is na het aanmaken van de zaak gekoppeld als initiator

**Comment by RoyBuis** [comment]
Refinement:
Kvk heeft al een API die goed voldoet, url: https://developers.kvk.nl/nl/support/switch-to-new-apis
Gebruik test API is gratis
Voorleggen in architectuuroverleg om gebruik te maken van deze API
Spike plannen om:
- uitzoeken gebruik van test API
-

**Comment by robertverboom** [comment]
test ok

**Comment by JosDimpact** [comment]
Opgepakt door Hilbrand (Groningen)

**Comment by HilbrandHurtak** [comment]
**_Testcripts_**
**De bedrijfsgegevens worden uit een authentieke bron gehaald**. Zoek een bestaande zaak op en koppel een bedrijf via de functie "Bedrijf toevoegen" in de menubalk aan de linkerkant. Geeft bij Handelsnaam de volgende waarde in Test. Selecteer 1 van de bedrijven. Het geselecteerd bedrijf dienst nu als initiator gekoppeld te zijn aan de zaak.

**De bedrijfsgegevens worden uit een authentieke bron gehaald**. Maak een nieuwe zaak aan en kies bij het veld Initiator voor een bedrijf (Icoontje gebouw). Geef bij Handelsnaam de volgende waarde in Test. Selecteer 1 van de bedrijven en maak de zaak aan. Een nieuwe zaak met als initiator het gekoppelde bedrijf

**Zoek op een gedeelte van de handelsnaam met daarbij een wildcard(*) Bijvoorbeeld Tes*. Wordt er een lijst met gevonden waarden weergegeven?

**Ontkoppel(icoontje prullenbak) bij een bestaande zaak de initiator en kies een nieuwe**
De nieuwe initiator is nu aan de zaak gekoppeld

**Zijn de acties van ontkoppelen en koppelen ook bij de zaakhistorie vastgelegd?**
Oude en nieuwe waarde dient zichtbaar te zijn bij de zaakhistorie

**Zijn de gekoppelde gegevens volledig**  Belangrijkste functionaliteiten:

Zijn de volgende gegevens aanwezig:
KvK nummer
Vestigingsnummer
Naam
Rechtsvorm
Vestigingstype
Hoofdactiviteit
Type adres
Adres
Postcode
Plaats
Land

Testresultaat: 

- [ ] OK  

- [ ] NOK

Toelichting:

**Comment by HilbrandHurtak** [comment]
Issue met postcode wordt later opgelost als de echte data beschikbaar komt
Bedrijf gekoppeld, ontkoppeld en historie bijgewerkt. . Test OK
