### ISSUE TITLE
Locatie koppelen bij starten van een nieuwe zaak

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#433]
***Als*** medewerker

***Wil ik*** bij het starten van een zaak in het ZAC een locatie kunnen koppelen

***Zodat*** ik kan zien op welke locatie een zaak betrekking heeft

***

### Acceptance criteria:
- Als aan een zaak een locatie is gekoppeld moet de relatie tussen de locatie en de zaak zichtbaar zijn

***
### Prioriteit
- Must haves

Deze story is gerelateerd aan story #309 
***
### Te realiseren
Omschrijving van op te leveren functionaliteit na refinement

- In deze spike worden de mogelijkheden om bij het aanmaken van een zaak in  het ZAC een locatie via Open Layers kaart te koppelen onderzocht

Een spike wordt gebruikt om voor een user story mogelijke oplossingsrichtingen in kaart te brengen met als doel de te realiseren funcctionaliteit van een user story te kunnen omschrijven en te kunnen schatten.

**Comment by RoyBuis** [comment]
Refinement:

- Uitzoeken of Open Layers te gebruiken is om locatie te kiezen
- Voor eerste opzet alleen mogelijk maken om een punt te kiezen (geen lijn of vlak)
- Spike inplannen om een eerste basis werking op te zetten

**Comment by bartlukens-atos** [comment]
Open-zaak ondersteund alleen gws84

**Comment by robertverboom** [comment]
test ok
