### ISSUE TITLE
11.1.1 Werklijsten lopende en afgehandelde Zaken-Taken-Contacten van Gebruiker zelf

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#434]
**Als** gebruiker (eigen werkvoorraad)

**Wil ik** op eenvoudige wijze een overzicht kunnen inzien van mijn lopende en afgehandelde Zaken | Taken | Contacten

**Zodat ik** snel inzicht krijg in de mij toegewezen nog te behandelen - en afgehandelde Zaken | Taken | Contacten en deze vanuit het overzicht kan openen 
 

***

### Acceptance criteria:
Acceptance criteria:

•	Gebruiker moet de actie kunnen uitvoeren met zo min mogelijk klikken
•	Actie moet in zelfde scherm kunnen worden uitgevoerd
•	Gebruiker ziet in de werklijsten alleen gegevens waarvoor autorisaties / rechten zijn toegewezen
•	De werklijst wordt getoond op volgorde ‘meest recente eerst’ <- De getoonde volgorde kan worden ingesteld (default meest recente bovenaan).
•	Gebruiker kan de Zaak | Taak | Contact vanuit de werklijst openen binnen hetzelfde scherm of op een nieuw browsertabblad
•	Er is een zoekfunctie aanwezig waarmee door de werkverdeler binnen de opgebouwde lijst zoekopdrachten kan doen
•	Gebruiker kan bij de getoonde Zaken | Taken | Contacten  zien welke behandel- signaleringsfase van toepassing is
•	Epic 11.2 Werklijsten persoonlijke weergave van de werklijst is uitgevoerd
•	Epic 11.3 Werklijsten exporteren is uitgevoerd

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Met de werklijsten 'Mijn zaken' en 'Mijn taken' zijn alle lopende zaken en taken van een gebruiker in een overzicht in te zien. Per zaak/taak zijn de belangrijkste gegevens te zien om inzicht in de werkvoorraad te krijgen. De gegevens die in de werklijst staan, de kolommen, zijn door de gebruiker in te stellen. De werklijst is met filters en sorteeropties aan te passen zodat alleen gewenste zaken/taken worden weergegeven. Vanuit de werklijst kan een zaak/taak geopend worden. Voor beëindigde zaken kan de gebruiker de werklijst 'Afgehandelde zaken' gebruiken en daar filteren op Behandelaar.

***Belangrijkste functionaliteiten:***
- Gebruiker kan vanuit het hoofdmenu de werklijsten 'Mijn zaken' en 'Mijn taken' openen
- Gebruiker kan per werklijst instellen welke kolommen worden weergegeven door in een werklijst rechtsboven op het filters icoon te klikken. De kolommen kunnen door de kolomkop te slepen met de muisaanwijzer van plek gewisseld worden.
- Gebruiker kan in de kolommen Zaaknummer, Omschrijving en Toelichting zoeken met trefwoorden
- Gebruiker kan in de kolommen Startdatum, Streefdatum en Fatale datum zoeken met een datumbereik
- Gebruiker kan met het oog icoon een zaak of taak openenen, Ctrl + oog icoon opent de zaak of taak in een nieuw tabblad

**Comment by RoyBuis** [comment]
### Backlog refinement 18-5
Deze story is gerealiseerd muv filter- en sorteer functionaliteit

**Comment by HilbrandHurtak** [comment]
De werking is gelijk aan Mijn Zaken. Er kan nu op diverse velden worden gesorteerd. Tevens kunnen ingestelde filters worden bewaard en weer worden hergebruikt.  De lijsten zijn in een csv format te downloaden waarna ze in excel kunnen worden geïmporteerd. Dit zou misschien nog wat kunnen worden verbeterd zodat het oerzicht direct netjes in kolommen wordt gepresenteerd. Overzicht contacten zit er niet om omdat deze niet in ZAC worden afgehandeld
