### ISSUE TITLE
11.1.3 Werklijsten lopende Zaken - Taken - Contacten van werkverdeler

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#436]
Als werkverdeler

Wil ik op eenvoudige wijze een overzicht kunnen inzien van lopende Zaken | Taken | Contacten

Zodat ik lopende c.q. te herverdelen Zaken | Taken | Contacten kan inzien en in bulk aan behandelaars kan toewijzen waarbij selectie van zaken, taken of contacten moet mogelijk zijn.

***

### Acceptance criteria:
•	Optie ‘behandelaar – is leeg’ is binnen de filters beschikbaar
•	Gebruiker moet de actie kunnen uitvoeren met zo min mogelijk klikken
•	Actie moet in zelfde scherm kunnen worden uitgevoerd
•	Gebruiker ziet in de werklijsten alleen gegevens waarvoor autorisaties / rechten zijn toegewezen
•	De werklijst wordt getoond op volgorde ‘meest recente eerst’ 
•	Gebruiker kan de Zaak | Taak | Contact vanuit de werklijst openen binnen hetzelfde scherm of op een nieuw browsertabblad
•	Er is een zoekfunctie aanwezig waarmee door de werkverdeler binnen de opgebouwde lijst zoekopdrachten kan doen
•	Gebruiker kan bij de getoonde Zaken | Taken | Contacten  zien welke behandel- signaleringsfase van toepassing is
•	Epic 11.2 Werklijsten persoonlijke weergave van de werklijst is uitgevoerd
•	Epic 11.3 Werklijsten exporteren is uitgevoerd

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
- Should haves
- Could haves
- Won't haves

### Gerealiseerd

Gebruiker kan filteren, sorteren en zoeken in de verschillende daartoe gewezen kolommen. zoekopdrachten kunnen als favoriet worden opgeslagen. Er zijn 2 verschillende werklijsten gemaakt: 'Mijn zaken' en 'Mijn taken'

### Niet gerealiseerd
- Werklijsten exporteren wordt uitgevoerd in ander ticket #443
- Contacten werklijsten worden niet ontwikkeld in het Zaak afhandel component
- Datumvelden hebben een range gekregen (beperking vanuit Angular)

**Comment by RoyBuis** [comment]
Acceptatiecriteria verder uitwerken in stories door Sander met werkgroep R&A.

**Comment by VictorTielenius** [comment]
Nu in diverse weklijsten mogelijk om een Zaak / Taak / Document op nieuw tabblad of venster te openen. Met rechtermuisknop en met Ctrl of Shift en klikken (zie #1640)
