### ISSUE TITLE
11.1.6 Werklijst zoeken Alle gebruikers

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#439]
Als gebruiker

Wil ik op eenvoudige wijze in de gekozen werklijst kunnen zoeken op inhoud van de zaak(of contact-)registratie (metadata) 

Zodat  ik een duidelijk, gefilterd, overzicht heb van mijn werkvoorraad 

***

### Acceptance criteria:
•	Epic 11.2 Werklijsten persoonlijke weergave van de werklijst is uitgevoerd
•	Epic 11.3 Werklijsten exporteren is uitgevoerd

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In alle werklijsten zijn er sorteer- en filteropties beschikbaar op de verschillende gegevenskolommen. De verschillende opties kunnen in combinatie met elkaar gebruikt worden om zo een gewenst overzicht te maken. Een gebruiker heeft ook de mogelijkheid om de toegepaste filters als zoekopdracht te bewaren.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met het pijl icoon in de kolomkop het geopende overzicht sorteren op basis van de gegevens in een kolom. Door nog een keer op de pijl te klikken wordt de andere kant op gesorteerd.
- Gebruiker kan filters op meerdere gegevenskolommen toepassen. Door te klikken op het vergrootglas in de kolomkop kan gefilterd worden op trefwoorden, met de keuzelijst kan gefilterd worden op één keuze en door te klikken op de kalender kan een datumbereik worden ingevuld.
- Gebruiker kan met het trechter icoon alle toegepaste filters wissen
- Gebruiker kan met het ster icoon de toegepaste sortering en filters als zoekopdracht opslaan. Door in een ongefilterd overzicht op het trechter icoon te klikken kan een bewaarde zoekopdracht worden geopend en kunnen zoekopdrachten met een klik op de prullenbak worden gewist.

**Comment by RoyBuis** [comment]
### Backlog refinement
Zoeken en filteren in werkvoorraad is nog niet mogelijk met de ZGW API's. Mogelijke oplossingen zijn:
- doorontwikkeling ZGW API's met inclusions en filter parameters
- oplossen in ZAC met bijvoorbeeld Solr

Sander bespreekt prio met werkgroep

**Comment by Snijhuis** [comment]
04-05-2022
1. Mooiste is wachten op de doorontwikkeling ZGW API. Ook kijken d vanuit de performance. Kunnen we vaart zetten achter de wijziging? PO Open Zaak benaderen.
2. Zowel Rotterdam als Emmen geven aan dat deze functionaliteit wel nodig is voor de livegang. For the time being kan Solr wel een oplossing bieden om zelf te zoeken als gebruiker met bepaalde filters.
#46

**Comment by RoyBuis** [comment]
Volgende caches verwijderen:

   String ZGW_ZAAK_BEHANDELAAR_MANAGED = "zgw-zaak-behandelaar-managed";

    // Deze cache is managed (alleen zaak URI als sleutel gebruiken!)
    String ZGW_ZAAK_GROEP_MANAGED = "zgw-zaak-groep-managed";

    // Deze cache is managed (alleen URI als sleutel gebruiken!)
    String ZRC_STATUS_MANAGED = "zrc-status-managed";

**Comment by robertverboom** [comment]
Datumcomponent moet nog verbeterd worden. Ander ticket #999 
 Voor de rest test ok.

**Comment by HilbrandHurtak** [comment]
@Snijhuis kan dit issue worden gesloten. Inmiddels zijn de mogelijkheden voor (Mijn) zaken en taken behoorlijk uitgebreid (ik neem aan via de Solr oplossing). De afzonderlijke tickets zijn getest

**Comment by HilbrandHurtak** [comment]
@KarinMasselink (als nieuwe productowner) kan dit issue worden gesloten?. Inmiddels zijn de mogelijkheden voor (Mijn) zaken en taken behoorlijk uitgebreid (ik neem aan via de Solr oplossing). De afzonderlijke tickets zijn getest

**Comment by RoyBuis** [comment]
### Refinement SN, KM & RB

Deze kan inderdaad gesloten worden
