### ISSUE TITLE
11.1.7 keuze aangemaakte en afgehandelde zaken of contacten (alle gebruikers)

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#440]
Als gebruiker 

Wil ik op eenvoudige wijze een overzicht kunnen maken van aangemaakte zaken of contacten die in een bepaalde periode zijn aangemaakt en afgehandeld

Zodat ik snel inzicht krijg in de aangemaakte en afgehandelde zaken of contacten binnen de gekozen periode
 

***

### Acceptance criteria:
•	Gebruiker kan daarbij een periodeselectie invoeren
        -Bij de keuze aangemaakt de aanmaak/creatiedatum
        -Bij de keuze afgehandeld de einddatum
•	Deze moet mogelijke zijn op alle beschikbare werklijsten
•	Gebruiker moet de actie kunnen uitvoeren met zo min mogelijk klikken
•	Actie moet in zelfde scherm kunnen worden uitgevoerd
•	Gebruiker ziet in de werklijsten alleen gegevens waarvoor autorisaties / rechten zijn toegewezen
•	De werklijst wordt getoond op volgorde ‘meest recente eerst’ <- De getoonde volgorde kan worden ingesteld (default meest recente bovenaan).
•	Gebruiker kan de Zaak | Taak | Contact vanuit de werklijst openen binnen hetzelfde scherm of op een nieuw browsertabblad
•	Er is een zoekfunctie aanwezig waarmee door de werkverdeler binnen de opgebouwde lijst zoekopdrachten kan doen
•	Gebruiker kan bij de getoonde Zaken | Taken | Contacten  zien welke behandel- signaleringsfase van toepassing is
•	Epic 11.2 Werklijsten persoonlijke weergave van de werklijst is uitgevoerd
•	Epic 11.3 Werklijsten exporteren is uitgevoerd

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
- Should haves
- Could haves
- Won't haves

### Gerealiseerd
Gebruiker kan filteren, sorteren en zoeken in de verschillende daartoe gewezen kolommen. zoekopdrachten kunnen als favoriet worden opgeslagen.

### Niet gerealiseerd
- Werklijsten exporteren wordt uitgevoerd in ander ticket #443
- Contacten werklijsten worden niet ontwikkeld in het Zaak afhandel component
- Datumvelden hebben een range gekregen (beperking vanuit Angular)

**Comment by RoyBuis** [comment]
Acceptatiecriteria verder uitwerken in stories door Sander met werkgroep R&A.

**Comment by Renvooi** [comment]
Idem als bij 11.1.3
Acceptatie criterium = Gebruiker kan de Zaak | Taak | Contact vanuit de werklijst openen binnen hetzelfde scherm of op een nieuw browsertabblad.
Met button Zaak bekijken heeft niet de optie om in een nieuw browsertabblad te openen (rechter muisknop > Link openen in nieuw tabblad)
Dit mis ik ook in andere schermen, bijv. bij Afgehandelde zaken, lopen en afgehandelde taken, binnen het dasboard.
Daarom label Bug toegevoegd.

**Comment by VictorTielenius** [comment]
Werklijsten: Mijn zaken + Afgehandelde zaken + Zaken-werkvoorraad (met oogje ook op nieuw tabblad / venster zaak te openen)
Filter en sorteren mogelijk. Datumrange zoeken en zoeken in aantal kolommen mogelijk.
Wel Startdatum als kolom, niet Creatiedatum. WG; is dit nodig?

Filter op Groep werkt niet goed.

**Comment by VictorTielenius** [comment]
Filter op Groep nu wel werkend
