### ISSUE TITLE
11.2.1 Werklijst persoonlijke weergave van de werklijst - Alle gebruikers

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#441]
Als gebruiker

Wil ik op eenvoudige wijze een werklijst kunnen indelen naar de informatie die ik persoonlijk in het scherm wil zien 

Zodat  ik een duidelijk overzicht heb van gewenste informatie binnen mijn werkvoorraad 

***

### Acceptance criteria:

•	Aantal getoonde regels is te kiezen
•	Indien van toepassing wordt een paginering voor tonen alle items opgebouwd
•	Gebruiker heeft in het scherm de keuze of hij Lopende - of Afgehandelde Zaken | Taken | Contacten wil zien
•	Gebruiker heeft in de beschikking over alle metadata-velden om te selecteren van het onderwerp van de werklijst 
•	Gebruiker kan kolomkoppen uitgebreid of verminderen met bepaalde gegevens
•	Gebruiker kan op bepaalde kolomkoppen sorteringen doen
•	Gebruiker kan op bepaalde kolomkoppen filteren
•	Gebruiker kan bij de getoonde Zaken | Taken | Contacten  zien welke behandel- signaleringsfase van toepassing is
•	Er is een zoekfunctie aanwezig waarmee door de werkverdeler binnen de opgebouwde lijst zoekopdrachten kan doen
•	Epic 11.1 Werkvoorraad is uitgevoerd
•	Epic 11.3 Werklijsten exporteren is uitgevoerd

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
- Should haves
- Could haves
- Won't haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Gebruiker kan filteren, sorteren en zoeken in de verschillende daartoe gewezen kolommen. zoekopdrachten kunnen als favoriet worden opgeslagen. 

### Niet gerealiseerd
- Werklijsten exporteren wordt uitgevoerd in ander ticket #443
- Contacten werklijsten worden niet ontwikkeld in het Zaak afhandel component
- Datumvelden hebben een range gekregen (beperking vanuit Angular)

**Comment by Renvooi** [comment]
Ik heb de sprintreview van vorige week dinsdag nog even teruggekeken.
Daarbij viel me nu iets op waarvan ik denk dat het mogelijk anders moet / bedoeld was.
Betreft de demo van Ronny mbt het zoeken in Werkvoorraad.

Schermopname sprintreview tijd 5:17
Je ziet dan het scherm ‘Mijn zaken’ met een overzicht.
In dat scherm worden kennelijk AL je lopende maar ook afgehandelde zaken direct getoond.
In de loop van de tijd/jaren kan dat een heel fors overzicht worden met honderden zoniet een paar duizend zaken.
In de opties voor de indeling van de kolomkoppen voorziet er niet in dat je alleen de lopende zaken wilt zien. 
Een van de aangegeven criteria is: Gebruiker heeft in het scherm de keuze of hij Lopende - of Afgehandelde **Zaken** | Taken | Contacten wil zien
Die optie zie ik niet terug bij de instelling voor de kolomkoppen.
Standaard zouden hier alleen de lopende zaken getoond moeten worden met in de optie voor kolomkopindeling de mogelijkheid om ook voor de al afgehandelde zaken te kiezen.

**Comment by robertverboom** [comment]
Afgehandelde zaken heeft een aparte werklijst gekregen en de optie is uit de mijn zaken werklijst gehaald. In de afgehandelde zaken kan een behandelaar (ook jijzelf) gekozen worden om 'mijn afgehandelde zaken' te kunnen inzien.

**Comment by VictorTielenius** [comment]
- Afgehandelde zaken heeft een aparte werklijst: OK
- Aantal getoonde regels is te kiezen: OK (10 -25 -50 - 100 en 25 default)
- Gebruiker heeft in het scherm de keuze of hij Lopende - of Afgehandelde Zaken | Taken | Contacten wil zien: OK, Zaken-werkvoorraad - Afgehandelde zaken - Taken-werkvoorraad
Contacten nvt.
- Gebruiker kan kolomkoppen uitgebreid of verminderen met bepaalde gegevens: OK
- Gebruiker kan op bepaalde kolomkoppen sorteringen doen: OK
- Gebruiker kan op bepaalde kolomkoppen filteren: OK
-Gebruiker kan bij de getoonde Zaken | Taken | Contacten zien welke behandel- signaleringsfase van toepassing is: OK, Status Zaak of Naam Taak zichtbaar.
- Er is een zoekfunctie aanwezig waarmee door de werkverdeler binnen de opgebouwde lijst zoekopdrachten kan doen: OK, zoekfunctie op Zaakomschrijving en zaaknummer.
- zoekopdrachten kunnen als favoriet worden opgeslagen: OK (en ook weg te gooien)
