### ISSUE TITLE
11.2.2 Werklijst visuele termijnbewaking - Alle gebruikers

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#442]
Als gebruiker

Wil ik op eenvoudige wijze in de gekozen werklijst kunnen zien hoe lang het nog duurt voordat (eind)datums worden bereikt - signaleringsindicatoren

Zodat  ik een duidelijk overzicht heb van mijn werkvoorraad 
 

***

### Acceptance criteria:
•	Door kleuren of andere indicatoren is te zien hoe lang het nog duurt voor de (eind)datum is bereikt
•	Epic 11.1 Werkvoorraad is uitgevoerd
•	Epic 11.3 Werklijsten exporteren is uitgevoerd

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
- Should haves
- Could haves
- Won't haves

### Gerealiseerd
Er zijn 2 kolommen bijgekomen: 'Aantal dagen tot fatale datum is bereikt' en 'Aantal dagen tot streefdatum is bereikt'
Achter de kolommen 'fatale datum' en 'streefdatum' worden de uitroepteken iconen nu getoond wanneer de datum is verstreken.

**Comment by Snijhuis** [comment]
Vanuit werkverdeler/Afdelinghoofd/ etc zijn wellicht deze indicaties op de werklijst voldoende als signalering. Dit in het verlengde van #778

**Comment by robertverboom** [comment]
## Refinement 05-05:

- We maken een extra aanduiding van het aantal dagen voordat de streefdatum en fatale datum is bereikt en voegen deze toe aan de werklijst Zaken-werkvoorraad en Mijn zaken (technisch: dit gebeurt op dezelfde manier als de card voor signalering zaken)
- 2 nieuwe kolommen. 1 voor 'Dagen tot streefdatum' en 1 voor 'Dagen tot fatale datum'
- Soortgelijke oplossing gebeurt bij de Mijn taken #777
- Gebruik maken van een pipe voor aantal dagen berekening

**Comment by VictorTielenius** [comment]
In Werklijst "Zaken - Werkvoorraad"  nu de kolommen "Dagen tot fatale datum" + "Dagen tot streefdatum" toe te voegen. In de Werklijst "Mijn Zaken" zijn deze standaard aanwezig.
En rood driehoekje met uitroepteken aanwezig wanneer de datum is verstreken bij Fatale datum.
Bij Streefdatum geen icoontje dat datum is overschreden. Is dit nodig?

**Comment by VictorTielenius** [comment]
Nu Oranje (of donker gele) driehoek icoontjes met uitroepteken aanwezig bij Overschreden Streefdatums
