### ISSUE TITLE
11.3.1 Werklijsten exporteren - Alle gebruikers

### ISSUE THREAD

**Issue by GertrudeKampherbeek** [NL-AMS-LOCGOV/zaakafhandelcomponent#443]
**Als** gebruiker

**Wil ik** op eenvoudige wijze een overzicht kunnen exporteren naar een gangbaar bestandsformaat, bv Excel

***

### Acceptance criteria:
•	Optie ‘behandelaar – is leeg’ is binnen de filters beschikbaar
•	Epic 11.1 Werklijsten lopende en afgehandelde Zaken - Taken  - Contacten is opgelost
•	Epic 11.2 Werklijsten persoonlijke weergave van de werklijst is opgelost

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- **Must haves**
### Gerealiseerd
**Let op: na de oplevering van deze story zijn er nieuwe stories (#1585 en #1586) gerealiseerd die deze story hebben beïnvloed. Deze stories zijn meegenomen in de 'Gerealiseerd' beschrijving.**
_Omschrijving van de op te leveren functionaliteit in deze story_
Van de werklijsten 'Zaken-werkvoorraad', 'Mijn zaken', 'Afgehandelde zaken' en 'Taken-werkvoorraad' en 'Mijn taken' kan de volledige inhoud naar een .csv bestand worden geëxporteerd. Bij gebruik van de Nederlandse versie van MS Office wordt het bestand automatisch in Excel in kolommen geopend.

***Belangrijkste functionaliteiten:***
- Gebruiker kan vanuit een werklijst de gegevens exporteren naar een .csv bestand door op de Exporteer knop onderaan de werklijst te klikken
- Er wordt bij het exporteren van de gegevens rekening gehouden met in de werklijst toegepaste filters en sorteringen

**Comment by RoyBuis** [comment]
### Backlog refinement 18-5
Vanwege lagere prio naar icebox verplaatst.

**Comment by robertverboom** [comment]
### Refinement 25-07
- volgende werklijsten: zaken-werkvoorraad, mijn zaken, afgehandelde zaken, taken-werkvoorraad, mijn taken(zaak zoekobject en taakzoekobject) 
- .csv bestand maken. 
- 1 vast formaat met vast aantal kolommen  
- inhoud (rijen)  wordt bepaald door ingestelde filters
- servlet 
- Kijk even bij csv utility in de e-suite
- geen extra policy

**Comment by robertverboom** [comment]
test ok

**Comment by Sevdiya** [comment]
test is ok

**Comment by robertverboom** [comment]
@Sevdiya @KarinMasselink wellicht bespreken met de werkgroep
Graag een nieuw issue aanmaken als er nieuwe functionaliteit, zoals rechten eraan gekoppeld moet worden.

**Comment by KarinMasselink** [comment]
@Sevdiya wil je deze oppakken, dan wel niet bug(s) aanmaken en deze naar de juiste kolom verslepen.
