### ISSUE TITLE
Vastleggen taal als metadata bij een document

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#450]
***Als*** medewerker

***Wil ik*** bij een document de taal kunnen vastleggen

***Zodat*** ik de juiste verplichte metadata bij een document kan vastleggen

***

### Acceptance criteria:
-

***
### Prioriteit

- Must haves

Deze story is gerelateerd aan story #330 

Uit Documenten API
Een ISO 639-2/B taalcode waarin de inhoud van het INFORMATIEOBJECT is vastgelegd. Voorbeeld: `nld`. Zie: https://www.iso.org/standard/4767.html

**Comment by robertverboom** [comment]
- flywayscript om tabel te vullen. 
- configuratieservice aanpassen. 

https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html

**Comment by hansmarks** [comment]
Bron voor de codes, als er twee staan is degene met de sterrtje de B-code: https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes

**Comment by hansmarks** [comment]
- dut Nederlands

**Comment by hansmarks** [comment]
#582

Ik heb de weergave op het document tonen scherm ook meteen even meegenomen. Onbekende taalcodes (in de bestaande data staat vaak nld of NLD, moet dus dut zijn) worden getoond als leeg veld.

**Comment by robertverboom** [comment]
test ok
