### ISSUE TITLE
11.1.X Werklijsten Zaken / Taken

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#452]
Epic voor user stories rondom werklijsten van zaken/taken. Contacten worden vooralsnog niet in het ZAC opgepakt. Wel in andere projecten, zoals KISS

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Stories zijn gerealiseerd. Openstaande stories worden apart opgepakt.
