### ISSUE TITLE
Werklijst afgehandelde zaken (periode) voor zaakbehandelaar

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#46]
**_Als_** zaakbehandelaar

**_Wil_** ik op eenvoudige wijze met een aantal zoekcriteria/filters een overzicht kunnen inzien van afgesloten zaken

**_Zodat_**  ik de afgehandelde zaak snel kan terugvinden.

Acceptance criteria, bijv.

- [ ] Actie kunnen uitvoeren met zo min mogelijk klikken
- [ ] Filteroptie op basis van zaaktype, behandelaar, groep, resultaat
- [ ] Filter op basis van tekstveld (omschrijving/toelichitng)
- [ ] Binnen het overzicht moet er op alle kolommen gesorteerd kunnen worden, denk aan: einddatum (datum afhandeling), zaaktype, behandelaar, groep, status, etc.

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De werklijst 'Afgehandelde zaken' is verrijkt met sorteer, filter- en zoekopties. De beschikbare opties zijn afhankelijk van het type data dat de kolom bevat. Zo kan er bijvoorbeeld bij data dat uit een waardelijst komt, zoals 'status' gesorteerd en gefilterd worden. 

***Belangrijkste functionaliteiten:***
- Per kolom kan een sortering, filter of zoekterm ingesteld worden, de opties kunnen gecombineerd worden.
- De toegepaste opties kunnen met de [Wis zoekopdracht] in één keer verwijderd worden. De lijst keert dan terug naar de standaardweergave.

**Comment by RoyBuis** [comment]
Refinement 6 december:
User story scherper uitwerken. Met name de 'zodat' uitwerken aan de hand van de personas. Wie wil een overzicht van afgehandelde zaken kunnen zien en waarom? Na uitwerken story opnieuw refinen.

**Comment by Snijhuis** [comment]
04-05-2022
Story aangepast met groep

**Comment by marcoatos** [comment]
Planning 02-06
Te realiseren
- Omzetten naar Solr

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Filteroptie op basis van zaaktype, behandelaar, groep, resultaat: OK 
( Groep is als fiter erbij te kiezen, niet standaard zichtbaar)
Filter op basis van tekstveld (omschrijving/toelichitng): OK
Binnen het overzicht moet er op alle kolommen gesorteerd kunnen worden, denk aan: einddatum (datum afhandeling), zaaktype, behandelaar, groep, status, etc.: OK 
(door op kolomnaam te klikken,Status + Groep erbij te zetten, niet standaard)
Wis zoekopdracht: OK
