### ISSUE TITLE
8.1.1 Signalering voor taken behandelaar

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#462]
***Als*** taakbehandelaar

***Wil ik*** erop geattendeerd worden dat er iets bij een taak is gewijzigd (bijvoorbeeld nieuwe taak op naam, document aan taak toegevoegd, streefdatum taak bereikt) waardoor ik een actie moet uitvoeren

***Zodat*** ik snel inzicht krijg in wijzigingen die niet door mijzelf zijn aangebracht

***

### Acceptance criteria:

- Actie moet door taakbehandelaar zelf aan/uit kunnen worden gezet 
- Actie moet op basis van een communicatievoorkeur kunnen worden ingesteld 
- Actie moet ook door de systeembeheerder kunnen worden geconfigureerd 
- Actie moet ook zichtbaar zijn zonder gebruik te maken van het systeem 

***
### Prioriteit
- Should haves

***
### Te realiseren
_Omschrijving van op te leveren functionaliteit na refinement_
- Signalering wanneer een behandelaar een taak op naam krijgt toegewezen
- Signalering is in de card 'Recent aan mij toegewezen taken' op het dashboard te zien
- Als de taak is geopend door de behandelaar dan verdwijnt deze uit de card

NB: een card wordt op het dashboard gebruikt om data uit het ZAC te tonen, in dit geval taak- en zaakdata

**Comment by RoyBuis** [comment]
Refinement 7-3:

- Signalering voor 'nieuwe taak op naam van behandelaar' als card toevoegen aan dashboard. Titel: Recent aan mij toegewezen taken
- Als taak geopend is dan verdwijnt de taak uit de card
- Signalering voor 'Streefdatum taak bereikt' eerst verder refinen. Dit is nu al inzichtelijk door in 'Mijn taken' te kijken
- Signalering voor 'Document aan taak toegevoegd verder refinen. Een document aan de taak toevoegen kan nu in de 3 taken van de behandelfase. Welke persona wil hiervan gesignaleerd worden en waarom?  

Omschrijving van op te leveren functionaliteit toegevoegd
-

**Comment by robertverboom** [comment]
test ok

**Comment by CommonGroundGroningen** [comment]
**Testcase 1**
Aanzetten van email signalering door behandelaar
**Verwachting**
De email signalering kan door de behandelaar zelf aangezet worden
**Resultaat**
De email signalering kan door de behandelaar zelf aangezet worden
- [x] OK


**Testcase 2**
Uitzetten van email signalering door behandelaar
**Verwachting**
De email signalering kan door de behandelaar zelf uitgezet worden
**Resultaat**
De email signalering kan door de behandelaar zelf uitgezet worden
- [x] OK


**Testcase 3**
Aanzetten van dashboard signalering door behandelaar
**Verwachting**
De dashboard signalering kan door de behandelaar zelf aangezet worden
**Resultaat**
De dashboard signalering kan door de behandelaar zelf aangezet worden
- [x] OK


**Testcase 4**
Uitzetten van dashboard signalering door behandelaar
**Verwachting**
De dashboard signalering kan door de behandelaar zelf uitgezet worden
**Resultaat**
De dashboard signalering kan door de behandelaar zelf uitgezet worden
- [x] OK

**Testcase 5**
Aanzetten van email signalering door behandelaar
Aanzetten van dashboard signalering door behandelaar
Aanmaken zaak
**Verwachting**
Behandelaar ontvangt signalering per email
Behandelaar ontvangt signalering in dashboard
**Resultaat**
Email is verstuurd
In de applicatie verschijnt een bolletje bij 'Home' ter attentie. Onder 'Recent aan mij toegewezen zaken' verschijnt de zaak.
- [x] OK

- [x] Eindresultaat: OK

**Comment by HilbrandHurtak** [comment]
Op de acc getest maar daar werkt het niet. @robertverboom heb jij een ander account voor mij op de zandbak omgeving zodat ik daar een taak vanuit een ander account aan mij kan toewijzen

**Comment by robertverboom** [comment]
@HilbrandHurtak Zojuist een taak op jouw naam gezet op de Zandbak omgeving.

**Comment by HilbrandHurtak** [comment]
Test ok
