### ISSUE TITLE
8.1.2 Signalering voor taken afdeling/groep

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#463]
***Als*** Afdeling of groep

***Wil ik*** erop geattendeerd worden dat er iets bij een taak voor de afdeling/groep is gewijzigd (bijvoorbeeld nieuwe taak, document aan taak toegevoegd, streef-of fatale datum taak bereikt) waardoor ik een actie moet uitvoeren 

***Zodat*** de afdeling/groep snel inzicht krijgt in wijzigingen die niet door de afdeling/groep zijn aangebracht (bijvoorbeeld nieuwe taak op naam afdeling/groep of nieuw document bij bestaande taak) 

***

### Acceptance criteria:

- Actie moet door de systeembeheerder kunnen worden geconfigureerd 
- Actie moet ook zichtbaar zijn zonder gebruik te maken van het systeem 

***
### Prioriteit

- Should haves

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Story zijn gerealiseerd via ander issue.
