### ISSUE TITLE
8.3.1 Taak vanuit een procesmodel aanmaken

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#465]
***Als*** behandelaar

***Wil ik*** vanuit een van tevoren vastgesteld procesmodel taken automatisch kunnen laten starten

***Zodat*** de processtappen volgens een vast patroon worden doorlopen

***

### Acceptance criteria:
Tijdens de afhandeling van een zaak moeten taken in een van tevoren vastgelegde workflow automatisch kunnen worden gestart en afgehandeld. Met name het uitvoeren conform een vast patroon is voor een juiste afhandeling randvoorwaardelijk en borgt dat een proces op een uniforme wijze wordt doorlopen. 

Per soort taak (bijvoorbeeld ontvankelijkheid, advies, ondertekening, goedkeuring enz) kunnen de gegevens op de schermen verschillen. Dit wordt in afzonderlijke user stories beschreven.  Elke taaksoort die automatisch vanuit een procesflow wordt gestart moet in ieder geval voldoen aan de onderstaande criteria.  

- Een taak moet op basis van een van tevoren vastgelegd procesmodel kunnen worden aangemaakt en doorlopen 
- Een taak moet meerdere keren kunnen worden aangemaakt 
- Meerdere taken moeten gelijktijdig kunnen worden aangemaakt 
- Een taak moet bij het aanmaken aan een afdeling/groep kunnen worden toegekend  
- Een taak moet bij het aanmaken aan een behandelaar van een afdeling/groep kunnen worden toegekend 
- Taken kunnen alleen worden aangemaakt als hiervoor de autorisaties aanwezig zijn 
- Taken kunnen bij het aanmaken alleen worden toegekend aan geautoriseerde afdelingen/groepen of behandelaars 
- Een taak kan bestaande informatie (reeds eerder ingevulde zaak- of taakgegevens) bevatten 
- Een taak kan nieuwe, nog in te vullen informatie, bevatten  
- Een taak moet vanuit een eenvoudige grafisch user interface kunnen worden aangemaakt 
- Een taak heeft altijd een verplichtte startdatum 
- Een taak kan een streefdatum bevatten 
- Een taak kan een fatale datum bevatten 
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

**Comment by robertverboom** [comment]
wordt opgepakt met PDK

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Story wordt via PodiumD backlog verder opgepakt.
