### ISSUE TITLE
8.3.1 Taak toewijzen

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#466]
***Als*** behandelaar

***Wil ik*** een taak aan een afdeling/groep of behandelaar toewijzen

***Zodat*** de taak door de juiste afdeling/groep of behandelaar kan worden afgehandeld 

***

### Acceptance criteria:

- Een taak moet handmatig kunnen worden toegewezen 
- Een taak moet vanuit een werkverdeler kunnen worden toegewezen 
- Een taak moet geautomatiseerd vanuit een procesflow kunnen worden toegewezen 
- Een taak moet aan jezelf kunnen worden toegewezen 
- Voor het toewijzen van taken is het autorisatiemodel van toepassing   
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De taak kan via de werklijsten toegekend worden, via de zaak en via de taak zelf. In de zaakafhandelparameters kunnen default groepen geselecteerd worden.

**Comment by CommonGroundGroningen** [comment]
**Testcase 1**
Taak wordt afgehandeld door een afdeling
Verwachting
Resultaat

**Testcase 2**
Taak wordt afgehandeld door een groep
Verwachting
Resultaat

**Testcase 3**
Taak wordt afgehandeld door een behandelaar
Verwachting
Resultaat

**Comment by HilbrandHurtak** [comment]
Er is nu een keuze. Alleen groepsleden of alle medewerkers
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/ada24e9d-9333-46ca-9564-d7187bc6a981)
