### ISSUE TITLE
8.3.2 Taak overdragen Deel 1

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#467]
***Als*** behandelaar

***Wil ik*** een taak kunnen overdragen

***Zodat*** iemand anders mijn taak kan overnemen

***

### Acceptance criteria:

Deel 1
- Een taak moet tenminste aan een afdeling/groep kunnen worden overgedragen 
- Een taak kan ook aan een behandelaar worden overgedragen 
- Taken kunnen alleen worden overgedragen aan afdelingen/groepen of behandelaars als hiervoor de autorisaties aanwezig zijn 
- Bij het overdragen van een taak kan een reden worden ingevuld 
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

Deel 2 (optie). Indien noodzakelijk wordt dit door de werkgroep refinement en acceptatie verder uitgewerk). Voor nu is besloten om dat nog niet te doen

- Bij het verdelen van een taak kan ook gelijktijdig de daaraan gekoppelde zaak worden overgedragen
- Taken kunnen alleen worden overgedragen aan afdelingen/groepen of behandelaars als hiervoor de autorisaties aanwezig zijn** Hiervoor zijn als stories aangemaakt onder #2033 en #2034

### Prioriteit

- Must haves
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een taak kan als deze geopend is aan een groep en/of een behandelaar worden overgedragen. Bij het overdragen aan een behandelaar kan, indien gewenst, ook gezocht worden naar behandelaars die niet tot de groep behoren.

***Belangrijkste functionaliteiten:***
- Gebruiker kan vanuit een zaak een taak openen en in het tabblad 'Algemene gegevens' deze overdragen door op het potlood icoon bij groep of bij behandelaar te kiezen. Hierdoor wordt het toekenningsblok geopend en kan de groep en/of behandelaar gekozen worden.
- Gebruiker kan in het toekenningsblok een behandelaar buiten de geselecteerde groep zoeken en selecteren door met een klik op het poppetjes icoon de 'Alleen groepsleden' functie uit te zetten 
- Gebruiker kan zichzelf als behandelaar toekennen door op het poppetje + icoon te klikken. Als gebruiker niet tot de groep behoort dan moet eerst de 'Alleen groepsleden' functie uitgezet worden.
- Alle wijzigingen van de groep of behandelaar worden in de historie van de taak opgenomen

**Comment by RoyBuis** [comment]
### Backlog refinement
gerealiseerd behalve

- Bij het verdelen van een taak kan ook gelijktijdig de daaraan gekoppelde zaak worden overgedragen
- Taken kunnen alleen worden overgedragen aan afdelingen/groepen of behandelaars als hiervoor de autorisaties aanwezig zijn

**Comment by HilbrandHurtak** [comment]
Roy gevraag of en zo ja wanneer de ontbrekende functionaliteit wordt opgepakt (bijvoorbeeld in een nieuwe user story deel 2)

**Comment by HilbrandHurtak** [comment]
Splitsing voorgelegd aan Sander waarbij deel 2 nog met de werkgroep moet worden besproken.

**Comment by HilbrandHurtak** [comment]
Getest deel 1
Een taak moet tenminste aan een afdeling/groep kunnen worden overgedragen.  **OK**
Een taak kan ook aan een behandelaar worden overgedragen **OK**
Bij het overdragen van een taak kan een reden worden ingevuld **NOK** **Ik kan geen rden invullen bij het wijzigen van een taakbehandelaar. Bij het wijzigen van een zaakafhandelaar kan dit wel**
De taakgegevens dienen bij de taakhistorie te worden vastgelegd  **OK**

**Comment by HilbrandHurtak** [comment]
@RoyBuis Heb het getest. Kan echter bij overdragen van taak geen reden invullen (bij zaak wel). Dit was wel 1 van de acceptatie voorwaarden. Vandaar afwijzing via label Bug.

**Comment by RoyBuis** [comment]
Bug aangemaakt voor het vastleggen van reden, zie #2131

**Comment by Sevdiya** [comment]
@HilbrandHurtak zal ik dit onderdeel ook testen? deel 1 e 2.

**Comment by KarinMasselink** [comment]
@HilbrandHurtak bug is opgelost dus deze zou dan ook moeten werken? Graag testen.

**Comment by HilbrandHurtak** [comment]
Veld reden bij overdagen taak kan nu worden ingevuld(optioneel conform de afspraak)
