### ISSUE TITLE
8.6.1 Taak handmatig afhandelen

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#468]
***Als*** behandelaar

***Wil ik*** een taak handmatig kunnen afhandelen 

***Zodat*** het zaakproces verder kan gaan

***

### Acceptance criteria:

- De taak kan worden geopend waarna de benodigde informatie moet worden ingevuld 
- Bij het afhandelen moet in ieder geval de status, de afdeling/groep, de behandelaar en de einddatum worden opgeslagen 
- De taak kan tussentijds worden opgeslagen zodat deze op een later moment kan worden afgerond. De reeds ingevulde gegevens blijven bewaard. 
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Bovenstaande criteria is gerealiseerd.

**Comment by CommonGroundGroningen** [comment]
**Testcase 1**
Handmatig afhandelen taak
**Verwachting**
De taak kan afgehandeld worden
Het zaakproces loopt door/blijft ongemoeid
De zaakhistorie wordt aangepast
**Resultaat**
