### ISSUE TITLE
8.7.1 Taken automatisch sluiten bij handmatig afronden zaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#469]
***Als*** behandelaar

***Wil ik*** de nog openstaande taken automatisch laten sluiten als de zaak handmatig wordt afgerond

***Zodat*** er geen openstaande taken meer zijn bij een afgesloten zaak

***

### Acceptance criteria:
In de huidige e-Suite kan een zaak handmatig worden afgesloten waarbij er nog openstaande taken zijn (bijvoorbeeld als een bezwaar wordt ingetrokken). Bij het handmatig afsluiten van de zaak worden dan automatisch alle openstaande taken(zoals die op dat moment zijn gevuld) afgesloten. Met name als er veel taken al zijn uitgezet en een zaak wordt ingetrokken kan het handig zijn om niet alle nog openstaande taken handmatig te moeten afsluiten. 

- Bij het handmatig afsluiten van de zaak moeten ook alle nog openstaande taken automatisch worden afgesloten 
- De taken worden afgesloten zoals ze op dat moment waren ingevuld(kunnen dus ook leeg zijn) 
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

***
### Prioriteit

- Should haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Bij het handmatig afronden wordt gebruik gemaakt van zaak afbreken. 

***Belangrijkste functionaliteiten:***
- openstaande taken worden afgerond
- informatie in de taak wordt readonly en deze kunnen nog geopend worden.

**Comment by CommonGroundGroningen** [comment]
**Testcase 1**
Zaak afbreken (?)
**Verwachting**
Openstaande taken worden automatisch afgesloten
**Resultaat**
