### ISSUE TITLE
8.3.3 Documenten bij een taak raadplegen 

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#470]
***Als*** behandelaar

***Wil ik*** de documenten die bij de afhandeling van een taak zijn aangemaakt bij de taak kunnen bekijken 

***Zodat*** ik weet welke documenten er tijdens de behandeling van de taak zijn gegenereerd

***

### Acceptance criteria:
Taakdocumenten kunnen bij de behandeling van een taak worden aangemaakt. Als voorbeeld kunnen de taakdocumenten worden genoemd die vanuit een taak in de e-Suite in Smartdocuments worden aangemaakt en aan de zaak worden toegevoegd.  

- Documenten die vanuit een taak worden gegenereerd moeten bij de taak zichtbaar zijn 
- Documenten die vanuit een taak worden gegenereerd moeten bij de taak kunnen worden gedownload 
- Documenten die vanuit een taak worden gegenereerd moeten bij de taak kunnen worden vergrendeld 
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

### Prioriteit
- Should haves

### Gerealiseerd
Bovenstaande user story is gerealiseerd

**Comment by CommonGroundGroningen** [comment]
**Documenten die vanuit een taak worden gegenereerd moeten bij de taak zichtbaar zijn**
TEST OK
**Documenten die vanuit een taak worden gegenereerd moeten bij de taak kunnen worden gedownload**
TEST OK
**Documenten die vanuit een taak worden gegenereerd moeten bij de taak kunnen worden vergrendeld**
Vanuit taak kan een document worden geopend via het oogje. In het documentscherm kan het document vergrendeld worden. Uit de refinement klinkt het alsof het document direct vanuit de taak vergrendeld kan worden.
Wat mij betreft is de werkwijze via het openen van het document prima.
TEST OK
De taakgegevens dienen bij de taakhistorie te worden vastgelegd
TEST OK
