### ISSUE TITLE
8.2.2 Taak - Ontvankelijkheid

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#472]
***Als*** behandelaar

***Wil ik*** de ontvankelijkheid van een zaak kunnen bepalen door hiervoor een taak aan te maken en toe te wijzen. 

***Zodat*** er kan worden bepaald of de zaak in behandeling kan worden genomen

***

### Acceptance criteria:
Één van de eerste taken in het generiek afhandelproces is het beoordelen van de ontvankelijkheid.  

- De gegevens van het bepalen van de ontvankelijkheid moeten kunnen worden vastgelegd 
- Nadat de ontvankelijkheid is bepaald moet het afhandelproces worden vervolgd zoals dat van tevoren bij het zaaktype is geconfigureerd 
- De inwoner moet op de hoogte kunnen worden gebracht van het feit dat de zaak ontvankelijk is   
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

### Gerealiseerd
Wanneer de behandelaar naar de volgende fase gaat, wordt er een optie aangeboden of de intake ontvankelijk is. 
- Wanneer deze ontvankelijk is, gaat de zaak naar de behandelfase. 

- Wanneer deze niet ontvankelijk is, wordt de zaak afgerond met resultaat: niet ontvankelijk. Er moet verplicht een reden worden ingevuld, wat wordt opgeslagen in de historie

- In de zaakafhandelparameters kunnen afgebroken zaken van te voren ingesteld worden met reden en resultaten. waaronder resultaat niet ontvankelijk

**Comment by Snijhuis** [comment]
WG Refinement 09-03 - Oplossingsrichting taak

Taakscherm maken voor ontvankelijkheid:
1. Ja/Nee
2. Reden waarom niet (optioneel)
3. Keuzelijst (configureerbaar)
4. Taakscherm aan/uit te zetten
5. Historie: wie, wanneer, wat

Proces nu met actiebuttons:
Ontvankelijk: ja --> in behandeling
nee --> Aanvullende info taak: invoeren wat je mist
nee --> niet ontvankelijk en zaak sluiten

**Comment by RoyBuis** [comment]
Refinement 17-3:
Oplossing MVP:

- Actie 'Niet ontvankelijk' krijgt een verplicht reden veld (vrije tekst veld) erbij
- Reden bij Niet ontvankelijk wordt opgeslagen als toelichting bij resultaat en status
- Toelichting van resultaat en status zijn zichtbaar bij zaakgegevens via vraagteken knop, dit is nieuw te maken nog
- Elke actie kan een toelichting krijgen als dialoog, bijvoorbeeld een lijst van dingen die gedaan moeten worden.
- Toelichting is onder zaakafhandelparameters in te stellen, dit kan per zaaktype, per actie ingesteld worden.

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Test ok. Mailtemplates kunnen nog beter nu er variabelen gebruikt kunnen worden. Als het goed is kun je deze zelf aanpassen
