### ISSUE TITLE
8.2.4 Taak – Aanvullende informatie opvragen 

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#476]
***Als*** behandelaar

***Wil ik*** aanvullende informatie kunnen opvragen

***Zodat*** de benodigde informatie volledig is en de zaak kan worden afgehandeld 

***

### Acceptance criteria:
Soms is het nodig om aanvullende informatie binnen een bepaalde termijn op te vragen. Nadat deze informatie is ontvangen kan de zaak wel of niet in behandeling worden genomen.  

- Via een taak kan de noodzakelijke aanvullende informatie worden vastgelegd(vraag en antwoord) 
- Via een taak kan ook de termijn waarbinnen de informatie moet worden verstrekt worden bepaald  
- Via een taak kan ook worden bepaald of de afhandeltermijn moet worden opgeschort  
- Een taak voor aanvullende informatie kan meerdere keren worden aangemaakt 
- De voortgang van de taken moet kunnen worden bewaakt 
- Nadat de aanvullende informatie is ontvangen dient de juiste stap in het afhandelproces te kunnen worden aangegeven.  
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

Een zaakbehandelaar kan via een taak aanvullende informatie opvragen die nodig is om de zaak te behandelen. 
Belangrijkste functionaliteit:
- bericht voor het opvragen van de informatie wordt per e-mail verstuurd
- inhoud van het bericht (body) kan door de gebruiker zelf worden opgesteld
- e-mailadres van de ontvanger van het bericht wordt door de gebruiker ingevuld
- na het het versturen van de e-mail wordt een taak gestart waarmee de uitvraag van de informatie kan worden bewaakt
- de verzonden e-mail wordt als document aan de zaak gekoppeld 
- startvelden email en body, datum opgevraagd automatisch invullen
- textarea Opmerkingen (verplicht), datum aangeleverd (niet verplicht) invulbaar 
- Document upload veld erbij (niet verplicht)
- Is de aanvullende informatie wel geleverd? met de 3 bullets

**Comment by robertverboom** [comment]
wat wordt er bedoeld met: 
_Nadat de aanvullende informatie is ontvangen dient de juiste stap in het afhandelproces te kunnen worden aangegeven._

**Comment by RoyBuis** [comment]
Refinement 14-3:
MVP:

- Aanvullende info taak waarmee per mail ontbrekende info aan de initiator gevraagd kan worden
- Gebruiker kan de body aan de hand van een voorbeeld tekst invullen
- Gebruiker vult emailadres van de ontvanger in
- Gebruiker vult groep/medewerker voor de bewakingstaak in
- ZAC maakt een taak 'Bewaken voortgang aanvullende info' aan en zet deze op naam van de groep en/of medewerker
- ZAC koppelt de mail als document aan de zaak

Wat moet er gebeuren:

- Taakstartformulier aanpassen met body (met voorbeeldtekst) en ontvanger voor mail
- Mailfunctionaliteit toevoegen
- Taakbehandelformulier aanpassen, opsplitsen in key value pair (functioneel)

**Comment by Snijhuis** [comment]
Later toevoegen: Sjabloon kunnen aanmaken voor uitvraag aanvullende info (Doccreatie)

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Testcase 1

Verwachting

Resultaat

Testcase 2
Verwachting

Resultaat


- [ ] OK  

- [ ] NOK
