### ISSUE TITLE
8.2.5 Taak – Behandelen

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#477]
***Als*** behandelaar

***Wil ik*** een taak “Behandelen” kunnen aanmaken

***Zodat*** de inhoudelijke behandeling door iemand anders dan de zaakbehandelaar kan worden uitgevoerd.  

***

### Acceptance criteria:
Nadat de ontvankelijkheid is bepaald en de eventuele aanvullende informatie is ontvangen kan de zaak  wel of niet in behandeling worden genomen. Het in behandeling nemen van een zaak is een stap in het afhandelproces en kan via een taak worden uitgezet bij een andere afdeling/groep of behandelaar of gewoon bij de zaakbehandelaar zelf. De behandelaar van de zaak en de taak kunnen dus verschillende personen zijn waarbij de zaakbehandelaar de regie blijft houden over het geheel en de taakbehandelaar de inhoudelijke behandeling blijft bewaken 

- Via een taak kan de inhoudelijke behandeling van een zaak worden gestart 
- Tijdens de inhoudelijke behandeling kunnen andere taken worden uitgevoerd(denk aan advies, goedkeuring, ondertekening enz) 
- Bij de inhoudelijke behandeling wordt de behandelaar op de hoogte gehouden van de  overige taken die van belang zijn voor de inhoudelijke behandeling(hiervoor is een afzonderlijke user story “voortgangsbewaking” gemaakt) 
- Nadat alle noodzakelijke taken zijn doorlopen kan de zaak worden afgerond 
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

**Comment by Snijhuis** [comment]
WG R&A 18-05:
Deze komt te vervallen gezien de huidige opzet/werking van ZAC met fasen en taken binnen een fase. Indien nodig, vanuit de huidige werking opnieuw kijken naar de gewenste functionaliteit om toe te voegen aan ZAC.
Issue gesloten.
