### ISSUE TITLE
8.2.6 Taak – Adviseren

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#479]
***Als*** behandelaar

***Wil ik*** een taak “Adviseren” kunnen aanmaken

***Zodat*** ik tijdens de behandeling van de zaak advies kan inwinnen en vastleggen

***

### Acceptance criteria:
Het inwinnen van advies is een belangrijk onderdeel van het generiek afhandelproces. In sommige gevallen wordt er veelvuldig advies gevraagd bij verschillende afdelingen/groepen of behandelaars. Pas als alle adviezen zijn ontvangen kan de inhoudelijke afhandeling verder worden opgepakt. Voor de zaakbehandelaar is het belangrijk om snel overzicht te krijgen in alle gegeven adviezen en de voortgang daarvan te bewaken. Dit is in een afzonderlijke user story verder uitgewerkt. Naast de in de user story 8.2.1 (handmatig aanmaken van een zaak) genoemde algemene eisen zijn voor een adviestaak nog de volgende criteria van toepassing

- Bij adviestaken kunnen relevante documenten worden meegestuurd waarover advies moet worden gegeven 
- Bij adviestaken kan de adviseur zelf ook documenten uploaden (handmatig of gegenereerd vanuit bijvoorbeeld een sjablonen generator zoals SmartDocuments) 
- Bij een adviestaak moet uit een lijstje (die te configureren is) de uitkomst van het advies op hoofdlijnen kunnen worden aangegeven (bijvoorbeeld positief, positief onder voorwaarde, negatief, negatief tenzij, niet beoordeeld) 
- Bij een adviestaak moet de toelichting op de vraag en de onderbouwing van het advies kunnen worden vastgelegd 
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

 

***
### Prioriteit

- Must haves

### Gerealiseerd
Wanneer de zaak in de behandelfase zit, kunnen er onbeperkt advies taken aangemaakt worden. 

***Belangrijkste functionaliteiten:***
- Er wordt een taakadvies intern startformulier getoond om de juiste vragen te stellen. Behandelaar kan een groep en andere behandelaar selecteren
- Documenten kunnen geselecteerd worden. 
- Op advies intern pagina kan de adviseur het takenformulier invullen

**Comment by RoyBuis** [comment]
### Backlog refinement 11-5

Story is al gerealiseerd.

**Comment by HilbrandHurtak** [comment]
Testcase 1
Bij adviestaken kunnen relevante documenten worden meegestuurd waarover advies moet worden gegeven
Verwachting
Adviestaak met relevante documenten
Resultaat
Adviestaak met relevante documenten
OK

**Comment by HilbrandHurtak** [comment]
Antwoord van Atos t.a.v #1433 : De bedoeling is dat er een referentietabel gemaakt wordt in het beheer stuk (wat je volgens mij gedaan hebt), echter moet je dan ook de goede tabel bij de taak advies intern installeren. De acties die zijn uitgevoerd bij de zaakafhandelparameters moeten inderdaad worden opgeslagen.
Bij een ander zaaktype wil je wellicht andere antwoordopties voor het advies. Vandaar dat je hem nog moet aangeven bij de zaakafhandelparameters

Functioneel werkt het dus.
