### ISSUE TITLE
Taak behandelen vervolg - afgeronde taken

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#48]
Wanneer een taak is afgerond moet deze nog inzichtelijk zijn voor de behandaar.

Tevens moet er gekeken worden of het opbouwen van de taak formulieren verbeterd kan worden.

**_Refinement:_**

- [x] **Functioneel:** Na afronden taak blijft gebruiker in zelfde scherm en ziet een read-only weergave van de taak Snackbar dat de gebruiker daadwerkelijk iets gedaan heeft

**Technisch:** 
- [x] @bartlukens-atos Taak moet opnieuw geladen worden na het afronden. 
- [x] @andyverberne Taakdata moet ook weer beschikbaar zijn bij afgeronde taak

**Comment by andyverberne** [comment]
Taakdata is nu beschikbaar bij afgesloten taak. 
Bij openen van afgeronde taak wordt het "afhandelen taak" scherm getoond met de oude waarde.
Wat nu nog moet gebeuren is dit scherm read only maken en de save knoppen verwijderen.

**Comment by andyverberne** [comment]
@bartlukens-atos zou je mijn commit kunnen reviewen?

**Comment by bartlukens-atos** [comment]
Review ok
