### ISSUE TITLE
8.2.7 Taak – Goedkeuren

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#480]
***Als*** behandelaar

***Wil ik*** een taak “Goedkeuren en ondertekenen” kunnen aanmaken

***Zodat*** ik tijdens de behandeling van de zaak goedkeuring kan krijgen en verder kan met de afhandeling van de zaak  

***

### Acceptance criteria:
Het goedkeuren en ondertekenen is een belangrijk onderdeel van het generiek afhandelproces. In sommige gevallen wordt er diverse keren om goedkeuring, mede goedkeuring en ondertekenen van documenten gevraagd bij verschillende afdelingen/groepen of behandelaars. Pas als alle goedkeuringen zijn ontvangen kan de inhoudelijke afhandeling verder worden opgepakt. Voor de zaakbehandelaar is het belangrijk om snel overzicht te krijgen in alle goedkeuringen en de voortgang daarvan te bewaken. Dit is in een afzonderlijke user story verder uitgewerkt. Naast de in de user story 8.2.1 (handmatig aanmaken van een zaak) genoemde algemene eisen zijn voor een goedkeuringstaak nog de volgende criteria van toepassing: 

- Bij goedkeuringstaken kunnen relevante( te ondertekenen documenten) worden meegestuurd  
- Bij goedkeuringstaken moeten soms ook documenten worden ondertekend. Voor het ondertekenen is een afzonderlijke user story gemaakt 
- Bij een goedkeuringstaak moet uit een lijstje(die te configureren is) de uitkomst van de goedkeuring op hoofdlijnen kunnen worden aangegeven(bijvoorbeeld Akkoord, Niet akkoord, Gedeeltelijk akkoord/niet akkoord ) 
- Bij een goedkeuringstaak kan de toelichting op de goedkeuring en de onderbouwing van de goedkeuring worden vastgelegd 
- Bij goedkeuringstaken kunnen ook documenten worden geüpload (handmatig of gegenereerd vanuit bijvoorbeeld een sjablonen generator zoals SmartDocuments) 
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

### Gerealiseerd
Wanneer de zaak in de behandelfase zit, kunnen er onbeperkt goedkeur taken aangemaakt worden.

### Belangrijkste functionaliteiten:
- Er wordt een goedkeurentaak startformulier getoond om de juiste vragen te stellen. Behandelaar kan een groep en andere behandelaar selecteren
- Documenten kunnen geselecteerd worden en aan de taak worden toegevoegd. Ook achteraf
- Het formulier kan beoordeeld worden door de aangewezen behandelaar.
- resultaten worden vastgelegd in de taak

**Comment by RoyBuis** [comment]
### Backlog refinement 11-5

Deze story is gerealiseerd

**Comment by HilbrandHurtak** [comment]
Als #1577 is opgeleverd dag hertesten (referentietabel aanpassen en kijken of de keuzelijst dan is aangepast). Daarna kort even een goedkeuringstaak doorlopen

**Comment by HilbrandHurtak** [comment]
Zie besluit Sander. Dus geen configureerbare tabel maar extra optie
