### ISSUE TITLE
8.2.8 Voortgangsbewaking taken door behandelaar zaak 

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#481]
***Als*** behandelaar

***Wil ik*** de door mij uitgezette taken op een eenvoudige wijze kunnen bewaken

***Zodat*** ik overzicht blijf houden op de voorgang van de zaakafhandeling en kan bijsturen indien dat noodzakelijk is    

***

### Acceptance criteria:
De behandelaar van de zaak is afhankelijk van de informatie van anderen. Meerdere adviezen, goedkeuringen, ondertekeningen enz kunnen als taak worden aangemaakt voor andere taakbehandelaars. Pas als alle informatie is ontvangen kan de behandelaar van de zaak weer verder. Om overzicht te houden in de voortgang van deze uitgezette taken moet de behandelaar op een eenvoudige wijze overzicht krijgen en worden gesignaleerd als taken niet tijdig worden afgerond. In de huidige e-Suite zijn hiervoor afzonderlijke voortgangstaken aanwezig. Binnen een voortgangstaak wordt alle informatie(vraag en antwoord) van de uitgezette taken weergegeven. Hierdoor krijgt de behandelaar van de zaak op een eenvoudige wijze de informatie en kan op basis daarvan zelf weer de afhandeling van de zaak oppakken. 

- De zaakbehandelaar moet op een eenvoudige wijze inzicht kunnen krijgen in de taken die bij andere taakbehandelaars zijn uitgezet 
- De zaakbehandelaar moet gesignaleerd worden als deze taken niet tijdig worden afgehandeld  
- De zaakbehandelaar moet gesignaleerd worden als de taken door de andere taakbehandelaars zijn afgerond 
- De zaakbehandelaar moet de informatie(vraag en antwoord) van deze uitgezette taken in een overzicht kunnen bekijken  
- Nadat alle informatie is ontvangen moet de behandelaar het afhandelproces verder kunnen oppakken  
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

### Gerealiseerd 
In de tabel van taken is doormiddel van een uitklappijltje een overzicht van de taakresultaten te zien. De volgende taken met labels en uitkomsten worden getoond: 

_Aanvullende informatie verstrekken_
**Aanvullende info**: < nieuwe optie binnen aanvullende info (#738)
**Opmerking** : 
**Bijlage toegevoegd** : titel van document

_Goedkeuren behandelen_
**Goedkeuren**:
**opmerking toelichting**:
**Bijlage**: Titel bijlage

_Advies intern behandelen_
**Advies**: 
**Toelichting advies**:
**Bijlage**: titel bijlage

_Extern advies vastleggen behandelen_
**Extern advies**:
**Bijlage**: Titel bijlage

### Niet gerealiseerd: 
- De signaleringcriteria worden in andere US opgepakt.

**Comment by RoyBuis** [comment]
Mogelijke oplossing voor bewaking vanuit een zaak:
Vanuit overzicht taken is de belangrijkste info uit de taken te zien:

- voor aanvullende info is dat het veld 'info geleverd'
- voor advies is dat het veld 'advies'
- voor goedkeuring is dat het veld 'goedkeuren'

Behandelaar heeft hiermee in één blik de status en de inhoudelijke uitkomst van de taken

**Comment by RoyBuis** [comment]
Refinement 31-3:

- uitkomst als variabele aan Flowable taak toevoegen, deze is gevuld met vaste waarden uit het taakbehandelformulier
- definieren welke velden per taak gebruikt worden om de variabele te vullen iom Sander/Roy
- uitkomst wordt getoond onder de taakregel als deze is uitgeklapt
- knop/toggle om alle taakregels in en uit te klappen toevoegen


Actie:
- Sander: naam voor de variabele bedenken met werkgroep R&A, voorlopige naam: uitkomst

**Comment by robertverboom** [comment]
Sander: naam voor de variabele bedenken met werkgroep R&A, voorlopige naam: uitkomst: **Label Taakinformatie**
Sander: keuze voor UI met werkgroep R&A bespreken: **Gekozen voor UI optie 1.**
Sander/Roy: uitzoeken hoeveel variabelen nodig zijn en bepalen welke velden op de variabelen gemapt worden

## Aanvullende informatie verstrekken:

radiobuttons;
**Aanvullende info:** 
Wel geleverd en akkoord
Wel geleverd en niet akkoord
Niet geleverd
**Opmerking** : 
**Bijlage toegevoegd** : titel van document

## Goedkeuren behandelen

**Goedkeuren**
**opmerking toelichting**
**Bijlage**: Titel bijlage

## Advies intern behandelen
**Advies**: 
**Toelichting advies**:
**Bijlage**: titel bijlage

## Extern advies vastleggen behandelen
**Extern advies**
**Bijlage**: Titel bijlage

**Comment by bartlukens-atos** [comment]
labels van de velden:
**Uitkomst
Opmerking
Bijlage**

**Comment by robertverboom** [comment]
test ok
