### ISSUE TITLE
8.2.9 Taak-Vastleggen besluiten

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#482]
***Als*** behandelaar

***Wil ik*** via een taak “Vastleggen besluit” de procestermijn kunnen bepalen indien dat van toepassing is 

***Zodat*** de juiste bewaartermijn kan worden bepaald

***

### Acceptance criteria:
Bij een zaaktype wordt de bewaartermijn bepaald via het resultaat en de daaraan gekoppelde selectielijst items met termijnen. Aan een resultaattype kan een besluit vastzitten dat van invloed is op het moment waarop de bewaartermijn van de zaak ingaat (procestermijn). De procestermijn is de periode waarin het zaakdossier actief gebruikt en/of geraadpleegd wordt omdat de zaak nog van belang is voor de bedrijfsvoering. Na het vervallen van dit belang gaat de (wettelijke) bewaartermijn in. De werking van de procestermijn is uitgewerkt in het ***Thema 9 Afsluiten/Afhandelen***

- Indien van toepassing(configuratie zaaktype) moet er een taak “Vastleggen besluit” kunnen worden gestart 
- In deze taak kan de behandelaar de in de selectielijst vastgelegde procestermijn veranderen door de ingangsdatum en/of vervaldatum van het besluit te wijzigen 
- Door het bepalen van de procestermijn moet bij de afsluiting van de zaak de juiste bewaartermijn automatisch worden vastgesteld 
- Bij de zaak moeten de gegevens van het besluit zichtbaar zijn( Type besluit, Ingangsdatum, Vervaldatum, Vernietigingsdatum en het besluit document) 
- De taakgegevens dienen bij de taakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

**Comment by RoyBuis** [comment]
### Backlog refinement 18-5
Sander bespreekt met werkgroep r&a hoe deze story aan te scherpen.

**Comment by Snijhuis** [comment]
WG R&A 18-05:
Deze story moet herschreven worden. In principe wil/moet je binnen de generieke zaakafhandeling een besluit kunnen vastleggen bij bepaalde zaaktypen. Besluit vastleggen moet optioneel zijn, niet elk zaaktype kent besluiten namelijk.

In de user story moet niet de oplossingsrichting zitten, zoals 'Taak' in dit geval. 

NB. N.a.v. een besluit moet bepaalt worden wat de Archiefactietermijn wordt etc. Dat zijn specifieke stories voor Archief epics.

**Comment by Snijhuis** [comment]
Voor Gertrude: Issue e-Suite: https://support.dimpact.nl/jira/browse/WIJZ-556

**Comment by PaskalKiers** [comment]
ik kan hem wel vinden. NIet assignen

**Comment by PaskalKiers** [comment]
Kleine versimpeling: volgens mij zijn doel en gewenste functionaliteit nog steeds correct.

**Als** behandelaar 

**Wil ik** een procestermijn kunnen vastleggen indien dat van toepassing is

**Zodat** de juiste bewaartermijn kan worden bepaald

Dit AC is een beetje twijfelachtig: - als een procestermijn van toepassing is, wordt deze getoond in hetzelfde scherm als waar ik het resultaat vastleg, op basis waarvan ik die conclusie kan trekken
- ik kan een eventueel automatisch bepaalde en voor ingevulde procestermijn aanpassen
- als een procestermijn is ingevuld, verschuift het start van de bewaartermijn met procestermijn naar de toekomst.  Hetzelfde geldt voor einde bewaartermijn. Dit is zichtbaar op het scherm
- een procestermijn leg ik vast in de vorm van een startdatum en een einddatum / een procestermijn geeft ik op als een termijn, die wordt bij einde zaakdatum (oid) opgeteld)
 (als de keuze startdatum einddatum wordt gebruikt, dan een check op volgordelijkheid)

**Comment by GertrudeKampherbeek** [comment]
Met Lian gesproken. Deze opzet zou wenselijk anders moeten met object waaraan een procesactietermijn is. Zie ook 10.C. Er zijn een aantal opties beschreven maar de werkgroep Informatiebeheer moet nog een uitspraak over doen en vervolgens uitwerken.

**Comment by Snijhuis** [comment]
Is op dit moment geen Taak maar een Actie. Verder uitwerking rondom besluiten loopt via andere issues. Vanuit WG informatiebeheer willen we concrete epics en stories gaan oppakken die ZAC raken m.b.t. informatiebeheer/archivering

**Comment by Snijhuis** [comment]
**WG R&A 21-09 bespreken:**
Sluiten en nieuwe epics opstellen met informatiebeheer
