### ISSUE TITLE
8.2.14 Taak-Starten nieuwe zaak

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#488]
***Als*** behandelaar

***Wil ik*** dat er vanuit uit een processtap/taak een nieuwe gerelateerde, deel of vervolgzaak kan worden aangemaakt  

***Zodat*** de juiste acties binnen de juiste zaaktypes kunnen worden uitgevoerd en de relatie met de hoofdzaak is geborgd  

***

### Acceptance criteria:
Vanuit een taak kan een andere zaak(en dus proces) worden gestart. Hierbij wordt de relatie tussen hoofdzaak en gerelateerde, deel of vervolgzaak automatisch gelegd en kan zaakdata van de hoofdzaak worden gebruikt bij de nieuwe zaken. Hierdoor is het mogelijk om gedurende de behandeling van de hoofdzaak te beslissen of er wel of geen nieuwe zaken moeten worden aangemaakt. Bij de inrichting van het hoofdzaaktype moet worden geconfigureerd welke gerelateerde, deel of vervolgzaken er mogen worden gestart. 
****Ik weet niet of deze toepassing ook daadwerkelijk veelvuldig wordt gebruikt ***

- Vanuit het afhandelproces van de hoofdzaak moeten automatisch nieuwe gerelateerde, deel of vervolgzaken kunnen worden gestart 
- Bij de inrichting van het zaaktype moet worden bepaald welke gerelateerde, deel of vervolg zaaktypes er mogen worden aangemaakt 
- De zaakdata van de hoofdzaak kan automatisch door de nieuwe zaak worden gebruik 
- De gegevens van het aanmaken van de nieuwe zaken dient bij de zaakhistorie te worden vastgelegd. 

***
### Prioriteit

- Should haves

**Comment by RoyBuis** [comment]
### Backlog refinement 11-5

Deze story nader uitwerken, bijv 'vanuit een bestaande zaak een nieuwe deelzaak starten'. Sander bespreekt dit met werkgroep R&A.

**Comment by Snijhuis** [comment]
WG R&A 18-05: 
@VictorTielenius zal 3 nieuwe stories maken:
- Vanuit hoofdzaak een deelzaak starten (incl criteria van die relatie)
- Vanuit hoofdzaak een vervolgzaak starten (incl criteria van die relatie)
- Vanuit hoofdzaak een gerelateerde zaak starten (incl criteria van die relatie)

NB. Je wil ook relaties kunnen leggen tussen reeds bestaande zaken. Functioneel gezien hetzelfde alleen dan vanuit een andere 'Actie button'

**Comment by Snijhuis** [comment]
@VictorTielenius  zal 3 nieuwe stories maken:
•	Vanuit hoofdzaak een deelzaak starten (incl criteria van die relatie)
•	Vanuit hoofdzaak een vervolgzaak starten (incl criteria van die relatie)
•	Vanuit hoofdzaak een gerelateerde zaak starten (incl criteria van die relatie)
NB. Je wil ook relaties kunnen leggen tussen reeds bestaande zaken. Functioneel gezien hetzelfde alleen dan vanuit een andere 'Actie button'

**Comment by Snijhuis** [comment]
Deze kan gesloten worden, lopen verder via de genoemde issues
