### ISSUE TITLE
8.3.4 Administratief ondertekenen van documenten in een taak  

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#489]
***Als*** behandelaar

***Wil ik*** binnen taken ook documenten op een eenvoudige wijze digitaal kunnen laten ondertekenen

***Zodat*** het hele proces digitaal kan worden uitgevoerd  

***

### Acceptance criteria:
Documenten kunnen aan een taak worden gekoppeld zodat ze in het afhandelproces digitaal kunnen worden ondertekend. Met name bij de goedkeuringstaken is dat het geval. Bij het aanmaken van de taak kunnen de te ondertekenen documenten worden toegevoegd. Niet alle documenten hoeven (juridisch gezien) te worden voorzien van een geavanceerde of gekwalificeerde elektronische handtekening (is afhankelijk van de mate van betrouwbaarheid van de ondertekening) 
In de huidige e-Suite oplossing is dat beperkt tot het administratief vastleggen van een ondertekening (eventueel met een gescande handtekening). 

- De zaakbehandelaar kan in een taak documenten toevoegen die in een vervolgproces moeten worden ondertekend 
- Bij het aanmaken van de taak moet ook duidelijk worden welke mate van betrouwbaarheid de ondertekening moet zijn. In deze user story is dat alleen de administratieve verwerking. 
- De taakbehandelaar krijgt in een taak de te ondertekenen documenten met een toelichting te zien  
- De taakbehandelaar moet de documenten openen voordat het document kan worden ondertekend   
- De taakbehandelaar kan eventueel zelf nog wijzigingen in het document aanbrengen (nieuwe versie) en deze ondertekenen 
- De taakbehandelaar moet tevens kunnen aangeven of hij akkoord is of niet 
- De taakbehandelaar kan eventueel een toelichting invullen 
- Als er verder geen echte handtekening nodig is wordt de ondertekening administratief vastgelegd 
- Bij de zaakdocumenten is op documentniveau te zien wie welke versie wanneer heeft ondertekend 
- Documenten kunnen meerdere keren worden ondertekend  
- Het autorisatiemodel is van toepassing (wie mag goedkeuren en ondertekenen) 
- De taakgegevens dienen bij de taakhistorie en te worden vastgelegd 
- De ondertekeningen dienen bij de documenthistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Met de taak 'Goedkeuren' kan een document digitaal worden ondertekend. Bij het aanmaken van de taak kan het te ondertekenen document, één of meerdere, geselecteerd worden. De behandelaar van de taak kan het document ondertekenen door het document aan te vinken en de taak daarna af te ronden. Bij het document worden in een nieuwe versie het ondertekeningssoort 'Digitaal' en de ondertekeningsdatum vastgelegd en de status wordt op definitief gezet.
***Belangrijkste functionaliteiten:***
- Gebruiker kan in het menu met de taak 'Goedkeuren' een (of meerdere) document(en) selecteren om te laten ondertekenen
- Gebruiker kan in de taak de documenten ondertekenen door het document aan te vinken. De ondertekening wordt bij het afronden van de taak op het document gezet.
- Gebruiker kan in de taak ook aangeven of het document is goedgekeurd en een toelichting hierop geven.
- De ondertekening is voor de gebruiker zichtbaar met een indicatie op het document, bij een mouse-over is de ondertekeningsinformatie zichtbaar.
- De ondertekening is zichtbaar in de historie van het document, hier is te zien wie er heeft ondertekend

**Comment by Snijhuis** [comment]
Ondertekening WG R&A

1. Beginnen met administratief ondertekening (metadata/audit trail)  Eerste instantie op Taak Goedkeuren. 
2. Waar? Op taakniveau:   
-Liefst aan de linkerkant, daarna selectie van documenten, documenten openen in view/ Word zodat de ondertekenaar gedwongen wordt om te lezen.  Mogelijk? 

3. Op Zaakniveau: Achter het document een icoon voor ondertekening.

- Gemandateerd: diegene die het document heeft gecreëerd ondertekend ook. 
- Niet gemandateerd: diegene die het document ondertekend is niet de creator/ auteur 

4. Meerdere keren ondertekenen mag. Ja dat mag. Kan dat ook i.r.t. Open Zaak/ versie Informatieobject?

**Comment by robertverboom** [comment]
## Refinement 30-06

- Goedkeuren taakscherm voor elk document in de relevante documententabel een checkbox 
- Naam kolom: Ondertekenen
- Na 'opslaan' de vinkjes onthouden
- Na 'opslaan & afronden' worden de aangevinkte definitief en ondertekend

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Test ok conform refinement van 30-06-2022

Wijkt wel af van wens van de werkgroep R/A:
Document kan niet meerdere keren worden ondertekend
Autorisatiemodel met gemandateerde niet kunnen testen.

Voor nu akkoord.
