### ISSUE TITLE
Taak behandelen vervolg - tussentijds opslaan

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#49]
Knop komen met tussentijds opslaan

Guard op de URL mocht je weggaan, dat je een reminder krijgt 

- [x] Knop 'Tussentijds opslaan'
- [ ] Issue oplossen

**Comment by robertverboom** [comment]
[14:49] Marks, Hans
Na het tussentijds opslaan van een taak, ga je dan naar de zaak? Of terug naar waar je vandaan komt? Of blijf je op de taak?

[14:50] Verboom, Robert
Op de taak blijven 

[14:50] Marks, Hans
En na de knop Opslaan & afronden?

[14:50] Verboom, Robert
waar je vandaan komt 

[14:50] Marks, Hans
OK

[14:51] Verboom, Robert
Somminge werken vanuit en werklijst dus die willen weer terug naar de werklijst 

[14:51] Verboom, Robert
als je even tijdig wilt opslaan, omdat je moet plassen of koffie wilt halen, dan wil je op de taak blijven

**Comment by andyverberne** [comment]
Vervolg van:

Opmerking van @bartlukens-atos : 
Wil je wel de knop disabelen als hij invalid is? Misschien wil je wel opslaan terwijl er nog een verplicht veld is ingevuld. Aan de andere kant wil je andere validaties wel afvangen (datum formaat, max lengte). Wellicht is het nodig om een custom validatie daar te checken die de verplichte velden buiten beschouwing laat.

console.log in taak-view.ts

**Comment by hansmarks** [comment]
Het lijkt mij wel dat je dat wilt. Wat je opslaat moet valide zijn. Ook als je het nog niet afrondt. Als je dat anders gaat doen wordt het erg ingewikkeld, ook voor de gebruiker lijkt mij. Ze kunnen altijd bepaalde velden niet verplicht maken als dat hiervoor nodig is. Maar misschien moet het voorgelegd worden aan de product-owner.

**Comment by hansmarks** [comment]
Als die dat ander wil (en aangeeft wat dan precies), kunnen we het in een vervolg-ticket uitzoeken hoe we dat het beste kunnen doen.
