### ISSUE TITLE
8.24.4 Ondertekenen van documenten in de zaak  

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#492]
***Als*** zaakbehandelaar

***Wil ik*** zelf documenten kunnen ondertekenen  

***Zodat*** hiervoor geen afzonderlijke taken hoeven te worden aangemaakt als de zaakbehandelaar bevoegd is om zelf te ondertekenen    

***

### Acceptance criteria:
Soms moet de zaakbehandelaar zelf de documenten ondertekenen en hoeven er geen taken te worden aangemaakt. In dat geval moet er dus ook functionaliteit zijn om dat te doen. Ook hier zijn de in de user stories 08.24.1 t/m 08.24.3 genoemde varianten van toepassing 

- De zaakbehandelaar kan de documenten ondertekenen 
- Per document kan de mate van betrouwbaarheid van de ondertekening worden bepaald  
- Op basis van de aangegeven mate van betrouwbaarheid van ondertekening wordt de benodigde functionaliteit beschikbaar gesteld 
- De gestelde eisen van betrouwbaarheid van de ondertekening worden bij de documenten opgeslagen  
- Documenten kunnen meerdere keren worden ondertekend  
- De ondertekeningen dienen bij de documenthistorie te worden vastgelegd 

***
### Prioriteit

- Should haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Via story #372 is deze functionaliteit opgeleverd.

**Comment by Snijhuis** [comment]
Volgens mij kan dit nu. Even checken samen

**Comment by CommonGroundGroningen** [comment]
**Gebruiker kan op de documentgegevenspagina met de actie [Ondertekenen] een digitale ondertekening zetten**
TEST OK
**Het systeem maakt na de ondertekening een nieuwe versie van het document met de status 'Definitief' aan**
TEST OK
**Er wordt een grijze 'Is ondertekend' indicatie op het document geplaatst**
TEST OK
**Een ondertekening wordt als wijziging van ondertekening in de historie van het document vastgelegd**
TEST OK
