### ISSUE TITLE
8.3.7 Bijlagen uploaden in een taak 

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#493]
***Als*** behandelaar

***Wil ik*** bijlagen kunnen uploaden in een taak

***Zodat*** vanuit het afhandelproces bijlagen kunnen worden toegevoegd aan het zaakdossier

***

### Acceptance criteria:
Bij het afhandelen van een taak dienen ook bijlagen te kunnen worden toegevoegd als dit tijdens de afhandeling van het proces noodzakelijk is.  

- Het kunnen toevoegen van bijlagen in een taak (bijvoorbeeld advies, ondertekening enz) 
- Het wel of niet toevoegen van bijlagen in een taak moet configureerbaar zijn(verplicht, optioneel of helemaal niet) 
- De bijlagen die kunnen worden toegevoegd kunnen per soort taak verschillen.  
- De metadata van de toe te voegen bijlagen wordt van te voren bepaald (documenttype, documentstatus, publicatieniveau, documentrichting, documentnaam en documentextensies) en kan niet door de taakbehandelaar worden gewijzigd. 
- Het toevoegen van de bijlagen dient bij de zaakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
bij een taakstart formulier kunnen documenten geselecteerd worden die gekoppeld zijn aan de zaak. Ook op het taakscherm kan een document toegevoegd worden. 

***Belangrijkste functionaliteiten:***
- 
-

**Comment by VictorTielenius** [comment]
In Taak (Advies intern behandelen) kan nu:
Document Toevoegen
Document maken (werk bij mij nu niet. Koppeling met Smartdocs nog te realiseren)

Document toevoegen aan Taak, dan direct: 
documentstatus Definitief (ook bij invullen Verzenddatum of geen Ontvangstdatum / Verzenddatum)
+Beschrijving: taak-document 
+ Vertrouwelijkheidaanduiding: Openbaar
