### ISSUE TITLE
8.3.9 Selecteren afdeling, groep of medewerker in een taak 

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#495]
***Als*** taakbehandelaar

***Wil ik*** kunnen aangeven door welke afdeling/groep of medewerker de volgende taak in het proces moet worden uitgevoerd

***Zodat*** de juiste afdeling/groep of persoon de taak kan oppakken

***

### Acceptance criteria:
Een taakbehandelaar kan in een afhandelproces kiezen door wie de vervolgtaak moet worden opgepakt. In de huidige omgeving kan dat in een taak worden aangegeven waarna de vervolgtaak op de juiste plek komt(afdeling/groep component). Randvoorwaarde is dat de afdeling/groep of medewerker wel de juiste rechten heeft op dat zaaktype 

- De taakbehandelaar moet kunnen bepalen door welke afdeling/groep of medewerker de vervolgtaak(als deze er al is) moet worden opgepakt 
- De toewijzing mag alleen aan een afdeling/groep of medewerker als hiervoor de juiste rechten aanwezig zijn. 
- De gegevens van wijzigingen dienen bij de zaakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

### Gerealiseerd
De taak kan via de werklijsten toegekend worden, via de zaak en via de taak zelf. In de zaakafhandelparameters kunnen default groepen geselecteerd worden. 

***Belangrijkste functionaliteiten:***
-  De wijzigingen worden in de taakhistorie vastgelegd 
-

**Comment by VictorTielenius** [comment]
Vanuit Zaak (ZAAK-2023-0000000010) Taak gestart op Groep + Groep + behandelaar.
In Taak en vanuit werklijst (verdelen). OK
