### ISSUE TITLE
8.3.10 Taakdocumenten Deel 1

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#496]
***Als*** behandelaar

***Wil ik*** vanuit een taak automatisch documenten kunnen laten toevoegen die ik in een documentengenerator heb gemaakt 

***Zodat*** er gebruik kan worden gemaakt van de standaard sjablonen zoals die binnen de organisatie worden gebruikt

***

### Acceptance criteria:
Vanuit een taak kunnen sjablonen worden gestart die in een andere applicatie worden samengesteld (Bijvoorbeeld SmartDocuments). Bij het samenstellen van de sjablonen kan er gebruik worden gemaakt van de zaak- en formulierendata om zo bepaalde gegevens al in te laten vullen. Nadat het document is samengesteld wordt deze automatisch aan de zaak toegevoegd 

- Vanuit een taak kan een extern sjabloon (of meerdere sjablonen) worden geopend en gevuld met zaakdata. 
- Na het samenstellen van het document wordt deze automatisch bij de zaak toegevoegd 
- De toegevoegde documenten zijn voorzien van metadata  
- De gegevens van de toegevoegde documenten worden bij de taakhistorie vastgelegd 

***
### Prioriteit

- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Bovenstaande is gerealiseerd. In Smart Documents kunnen de sjablonen ingeregeld worden.

***Belangrijkste functionaliteiten:***
- Toegevoegde documenten worden in de zaakhistorie ipv taakhistorie vastgelegd

**Comment by robertverboom** [comment]
wordt vastgelegd in de zaakhistorie

**Comment by HilbrandHurtak** [comment]
Getest met de 2 test SmartDocuments sjabonen die bij de zaak kunnen worden aangemaakt:

Via de knop 'Aanmaken documenten' sjabloon Data Test en OpenZaakTest aangemaakt. Diverse velden worden al ingevuld. Het opgeslagen document wordt aan de zaak toegevoegd met een status 'vast te stellen'. Om dit te wijzigen dient een nieuwe versie te worden toegevoegd.

Het aanmaken van documenten gaat via de zaak en niet de taak. dit verschilt dus t.a.v. de huidige e-Suite. In de historie van de zaak kan ik niet zien wie het document heeft toegevoegd
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/36d4d9d4-fdfd-4b2a-aa06-c56607172c55)

Tevens ontbreek het veld documentrichting.

**Comment by HilbrandHurtak** [comment]
Document aangemaakt in de huidig e-Suite
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/72e9c6d6-7117-418a-9eb9-86682b42e020)

Document aangemaakt in ZAC
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/aae14edb-cf05-485b-afc5-f211a0ea8ce7)

**Comment by HilbrandHurtak** [comment]
@robertverboom. Ik ben bezig met het testen van de SmartDocuments functionaliteit. Ik zie dat ik nu documenten vanuit de zaak en taak kan aanmaken.

Is er ook een configuratie waarbij ik per taak de te gebruiken SmartDocuments sjablonen kan instellen (Net zoals bij de mailtemplates bijvoorbeeld). Dat is functionaliteit die we nu wel hebben/gebruiken

**Comment by HilbrandHurtak** [comment]
@robertverboom Ik heb deel 2 al gevonden (Aanmaken documenten (via Smartdocuments): Deel 2#1599)

**Comment by HilbrandHurtak** [comment]
Wachten op deel 2 en dan alles opnieuw testen
