### ISSUE TITLE
8.30.1 Verzend naar zaaksysteem en wacht op eindstatus tijdens procesafhandeling

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#498]
***Als*** behandelaar

***Wil ik*** tijdens de procesafhandeling automatisch een zaak kunnen laten aanmaken in een ander systeem  

***Zodat*** daar de verdere afhandeling kan plaatsvinden 

***

### Acceptance criteria:
De e-Suite is gekoppeld(stuf zaken/DMS) met diverse systemen. In sommige processen worden eerst taken in de e-Suite uitgevoerd waarna er vervolgens automatisch een zaak in een externe applicatie wordt aangemaakt. De procesafhandeling gaat dan verder in de externe applicatie. In de tussentijd worden documenten en statussen uitgewisseld. Bij het afsluiten van het proces in de externe applicatie krijgt de e-Suite dan het resultaat door en kan de zaak vervolgens afsluiten en de vastgestelde bewaartermijnen doorvoeren. In de huidige e-Suite zijn hiervoor in het afhandelproces 2 nodes (Verzend naar zaaksysteem en wacht taak) beschikbaar 

- Bij de procesafhandeling moet het mogelijk zijn om in welke fase dan ook een proces in een externe applicatie, op basis van Stuf zaken/DMS of een API, te laten starten,  
- Nadat de koppeling tot stand is gebracht moeten de procesgegevens(op basis van de standaarden) tussen beide systemen kunnen worden uitgewisseld 
- De nieuwe e-Suite moet uiteindelijk de zaak automatisch kunnen afsluiten op basis van een resultaat of eindstatus  
- Voor het geïntegreerd proces gelden de vastgestelde autorisaties 
- De gegevensuitwisseling moet bij de zaakhistorie worden vastgelegd   

***
### Prioriteit

- Must haves

**Comment by robertverboom** [comment]
Met de groep opnieuw beschrijven

**Comment by Hugo-ter-Doest** [comment]
Dit gaat in de nieuwe situatie heel anders werken omdat applicaties werken op OpenZaak. De basis is dat een TSA zich kan abonneren op nieuwe zaken van een bepaald zaaktype. En vervolgens de afhandeling daar kan plaatsvinden. Ik vind dat je kritisch moet zijn op de afhandeling in meerdere apps. Dat is een situatie die we gecreeerd hebben met e-Suite in combinatie met TSA's. Maar dat is niet gewenst en niet goed te beheren. 

Ik heb bij de werkgroep implementatievoorbereiding meerdere keren uitleg gegeven over dit nieuwe patroon volgens CG. 

Uiteraard krijgen we ook te maken met TSA's die nog om kunnen gaan met ZGW API's. Voor die gevallen zouden we kunnen denken aan een vertaler van notificaties naar CreerZaak. Is nog slechts een idee.

**Comment by Hugo-ter-Doest** [comment]
@Snijhuis Misschien beter om deze op de andere backlog https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues te zetten?

**Comment by RoyBuis** [comment]
### Refinement KM, RB & RV
Story wordt via PodiumD backlog verder opgepakt.
