### ISSUE TITLE
Eerste opzet ophalen en tonen historie van zaak en document

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#50]
Opzet maken voor het ophalen van audit trails voor zaak en document

Historie tonen in tabblad bij zaak en document

https://vng-realisatie.github.io/gemma-zaken/themas/achtergronddocumentatie/audit-trail

- [x] Rest- converters audit-wijzigingen objecten
- [x] @andyverberne Onderzoeken of de sub classes van AuditWijziging echt nodig zijn.
- [x] @andyverberne Ingelogde medewerker fixen want werkt nu niet omdat deze wordt geinjecteerd via ApplicationScoped bean

**Comment by ronniekoopmans-atos** [comment]
c1edb8e5360a1a2e694d702a37f2f39f74cbf888 
a2abcf4ca90ac62ae063e8b9a9c6bc46035afa86 
666a81cc8660d0cb73b23385fc827cd2b8456309

**Comment by andyverberne** [comment]
Ingelogde medewerker werkt.
SubClasses van AuditWijziging  is prima zo.

**Comment by robertverboom** [comment]
test ok
