### ISSUE TITLE
8.32.1 Opschorten tijdens procesafhandeling 

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#500]
***Als*** taakbehandelaar

***Wil ik*** het proces kunnen laten opschorten

***Zodat*** de doorlooptijd van het proces kan worden verlengd

***

### Acceptance criteria:
In de generieke procesafhandeling kan een taakbehandelaar een zaak opschorten, dat wil zeggen de doorlooptijd van een zaak verlengen. Hierbij wordt het aantal opgegeven dagen opgeteld bij de bestaande streef- en fatale datum. De zaak blijft opgeschort tot dat deze weer hervat wordt. Het hervatten van de zaak zit ook in de generieke procesafhandeling gemodelleerd. 

- Bij de procesafhandeling moet het mogelijk zijn om in welke fase dan ook automatisch de zaak op te schorten 
- Bij het opschorten moet kunnen worden aangegeven vanaf welke datum en voor hoeveel dagen. 
- De streef en fatale datum wordt aangepast met het aantal dagen van opschorting 
- Bij de zaak moet duidelijk zichtbaar zijn dat de zaak is opgeschort 
- De behandelaar moet de opschorting op een eenvoudige wijze kunnen bewaken 
- De behandelaar moet kunnen bepalen of de zaak na de opschorting nog verder moet worden behandeld 
- De naar aanleiding van de opschorting gewijzigde gegevens dienen bij de zaakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

**Comment by Snijhuis** [comment]
**WG R&A 21-09 bespreken:**
