### ISSUE TITLE
8.33.1 Hervatten tijdens procesafhandeling 

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#502]
***Als*** taakbehandelaar

***Wil ik*** het proces, nadat deze is opgeschort, weer kunnen hervatten

***Zodat*** de generieke procesafhandeling weer kan worden opgepakt

***

### Acceptance criteria:
Een opgeschorte zaak moet ook weer kunnen worden hervat. Indien de datum van het hervatten voor de einddatum van de opschorting ligt, worden de streefdatum en fatale datum vanaf dat moment aangepast. 

- Bij de procesafhandeling moet het mogelijk zijn om het opschorten de zaak ook weer te hervatten 
- De datum van het hervatten moet kunnen worden aangegeven 
- De streef en fatale datum wordt aangepast vanaf het moment waarop het hervatten wordt doorgevoerd 
- Bij de zaak moet duidelijk zichtbaar zijn dat de zaak is hervat 
- De behandelaar moet het hervatten op een eenvoudige wijze kunnen bewaken 
- De behandelaar moet kunnen bepalen of de zaak na het hervatten nog verder moet worden behandeld 
- De, naar aanleiding van het hervatten, gewijzigde gegevens dienen bij de zaakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

**Comment by Snijhuis** [comment]
**WG R&A 21-09 bespreken:**
