### ISSUE TITLE
8.34.1 Verdagen tijdens de procesafhandeling 

### ISSUE THREAD

**Issue by HilbrandHurtak** [NL-AMS-LOCGOV/zaakafhandelcomponent#503]
***Als*** taakbehandelaar

***Wil ik*** de doorlooptijd van de zaak en de daarbij behorende taken kunnen verlengen

***Zodat*** ik meer tijd heb om de zaak te behandelen

***

### Acceptance criteria:
Met het verdagen wordt de doorlooptijd(streef en fatale datum) van de zaak met een x-aantal dagen verlengd.  

- De zaak (streef en fatale datum) kan worden verdaagd met een x-aantal dagen 
- Bij het verdagen dient een reden te worden aangegeven 
- Als optie moeten ook de onderliggende openstaande taken met deze termijn kunnen worden verdaagd. 
- Bij de zaak moet duidelijk zichtbaar zijn dat de zaak is verdaagd 
- De, naar aanleiding van de verdaging, gewijzigde gegevens dienen bij de zaakhistorie te worden vastgelegd 

***
### Prioriteit

- Must haves

**Comment by Snijhuis** [comment]
**WG R&A 21-09 bespreken:**

**Comment by Snijhuis** [comment]
**WG R&A 21-09 bespreken:**
Voor nu voldoende de algemene functionaliteit voor opschorten. Wellicht onderdeel van PDK
