### ISSUE TITLE
6B.4.1 Handmatig afhandelen van zaak DEEL 2

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#504]
Refinement 20-1:
UI:
Knop beschikbaar maken in linkermenu. Naam van knop: 'Zaak afbreken'
Gebruiker kiest reden uit lijst.
Annuleerknop is ook beschikbaar

Openstaande taken:
ingevulde velden blijven bewaard en zijn te raadplegen
taak krijgt bij handmatig afhandelen van de zaak de status 'Afgerond' maar wordt getoond als 'Afgebroken'. Evt ook verdere visuele verduidelijking maken.
Boolean Afgebroken == true (op de taak)

Case model:
Lopende case moet worden afgesloten
Configuratie in zaakafhandelparameters:

Historie van zaak:
Reden van afbreken opnemen. Wijziging = resultaat, Toelichting = gekozen van reden afbreken

Zaakafhandelparameters:
Reden bij zaakafhandelparameters min 1 verplicht maken. (Nu nog niet het geval)

Gerealiseerd in DEEL1
~~Per zaaktype de 'reden van beeindiging' kunnen inrichten
Aan een reden moet het bijbehorende resultaat gekoppeld worden. Resultaten komen uit Open zaak.
Eindstatus is bepaald door het zaaktype in Open zaak dus kan niet geconfigureerd worden~~

***
### Gerealiseerd
Als #169 aangevinkt is, wordt de functie Zaak afbreken getoond op de zaakgegevens pagina. Door de zaak af te breken, wordt gevraagd naar een reden. Aan elke reden is een resultaat gekoppeld (gerealiseerd in Deel 1) 

Belangrijke functionaliteit
- Status krijgt afgerond met een infomeer icoon waarom deze is afgerond. 
- Alle openstaande taken worden ook afgerond. Opgegeven informatie in de taken worden wel bewaard. 
- In de Historie wordt beschreven waarom deze is afgerond met bijbehorende resultaat

**Comment by CommonGroundGroningen** [comment]
**Testcase 1**
Afbreken zaak
**Verwachting**
Zaak kan afgebroken worden
Reden kan opgegeven waarom zaak afgebroken kan worden
**Resultaat**
Knop afbreken zaak is beschikbaar
Reden afbreken kan opgegeven worden
Zaak wordt afgebroken

**Testcase 2**
Afbreken zaak wordt geannuleerd
**Verwachting**
Zaak kan afgebroken worden
Afbreken zaak kan geannuleerd worden
**Resultaat**
Afbreken zaak kan geannuleerd worden

**Comment by HilbrandHurtak** [comment]
Zie testbevindingen #169. Opnieuw getest en bevindingen vastgelegd
