### ISSUE TITLE
8.1.X Signalering taken

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#508]
Epic voor signaleringen op taken

**Comment by VincentHofman** [comment]
Word hier ook meegenomen dat je een signalering krijgt bij het ondertekenen van een document?

**Comment by RoyBuis** [comment]
[### Refinement KM, RV & RB

Issues zijn gerealiseerd. Epic wordt gesloten.
