### ISSUE TITLE
504 Gateway Timeout bij opstarten Zaakafhandelcomponent

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#51]
Starten van zaakafhandelcomponent na lange tijd inactiviteit geeft foutmelding 
In de console van de browser staan fouten. Mogelijk zijn die gerelateerd. 

Andy: 
Porbleem lijkt een combinatie te zijn van het gebruik van Keycloak en de Service Worker
Er zijn wat experimenten uitgevoerd met aanpassingen in de ngsw-config.json.
Deze aanpassingen lieten andere gedrag zien maar het lijkt geen totale oplossing te zijn.

Om een oplossing te kunnen vinden zullen we meer onderzoek moeten doen naar de werking en configuratie van de service worker.

Bart: 
https://github.com/angular/angular/issues/38194

**Comment by andyverberne** [comment]
Vervolg van https://jira.sdmc.ao-srv.com/browse/ESUITEDEV-25905
