### ISSUE TITLE
BUG: Uitlijnen van advies intern 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#524]
***Steps to reproduce:***

1. Ga naar een Advies intern taak

***Expected***
Lijn valt netjes in het blokje

***Actual***
![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/5222ea2d-d073-41d3-b4f5-299bc3afc09b)

**Comment by robertverboom** [comment]
Lijkt erop dat de relevante documenten de taak naar beneden drukken: https://zac.develop-public-service-platform.net/taken/5a1a8be3-92f3-11ec-a0d4-f6f197794f9b

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Issues wordt gesloten, geen prio.
