### ISSUE TITLE
0.1 Project algemeen: Acceptatie omgeving

### ISSUE THREAD

**Issue by JosDimpact** [NL-AMS-LOCGOV/zaakafhandelcomponent#531]
Als acceptant
Wil ik een representatieve testomgeving
Zodat ik, met zo veel mogelijk zekerheid over hoe nieuwe functionaliteit uiteindelijk zal werken in de productie-praktijk, conclusies kan trekken over de kwaliteit en geschiktheid van de nieuwe functionaliteit.
***

### Acceptance criteria:
-	Ik wil een omgeving met zo min mogelijk stubs en drivers
Daar waar aanpalende componenten beschikbaar zijn, wil ik deze gebruiken om zoveel mogelijk de ‘koninklijke route’ te kunnen volgen en dus zo representatief conclusies over de uiteindelijke productie situatie kan trekken.
-	Beheerfunctionaliteit moet mogelijk zijn om als acceptant een bepaalde uitgangssituatie te kunnen creëren. Dit hoeft initieel niet de uiteindelijke definitieve beheer-oplossing te zijn, daar zijn andere epics voor. De beheerfunctionaliteit kan dan met die epics meegroeien in gebruiksvolwassenheid.
-	De omgeving is gevuld met zo veel mogelijk productie-like niet herleidbare (anonieme) data.
-	De omgeving heeft governance. Functioneel ligt de regie bij Dimpact (testcoördinator), Technisch ligt de regie bij Atos (ontwikkelteam).
-	De omgeving wordt met de nieuwste functionaliteit bijgewerkt zodra de software dit toelaat, zodra een of meerdere user stories testbaar zijn met die software. Waarschijnlijk is dat voor- of juist na- een sprint-review. 
-	Updatewindow is voor 09.00 of na 16.00.
-	De omgeving wordt gedocumenteerd opgeleverd ten behoeve van het inrichten van gemeentelijke acceptatieomgevingen. Als we weten wat er technisch nodig is voor een testomgeving, dan kunnen we dat plotten op de acceptatieomgeving en later op de productieomgeving.

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

**Comment by JosDimpact** [comment]
Opgepakt voor test door Jos

**Comment by VictorTielenius** [comment]
Beheerfunctionaliteit is er nog niet
