### ISSUE TITLE
Inlogsessie verlengen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#537]
***Als*** mederwerker

***Wil ik*** langer ingelogd blijven, ookal doe ik niks op het scherm

***Zodat*** ik niet telkens uit de sessie gezet wordt en telkens opnieuw moet inloggen

***

### Acceptance criteria:
- Minimaal 60 minuten in de sessie blijven

***
### Prioriteit
- Should haves

**Comment by robertverboom** [comment]
- keycloack sessie verlengen
- uitzoeken wanneer je niet meer in de sessie zit, wat voor foutmelding je krijgt en waarom. Opnieuw redirecten naar het inlogscherm.

**Comment by hansmarks** [comment]
https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/sessions/timeouts.html

**SSO Session Idle**, zou ik zeggen en ook even kijken waar **SSO Session Max** op staat.

**Comment by hansmarks** [comment]
**SSO Session Idle** op 8 uur gezet in alle realms.

**Comment by hansmarks** [comment]
Web Origins bij zaakafhandelcomponent-localhost de /* eraf gehaald wegens: https://stackoverflow.com/questions/45051923/keycloak-angular-no-access-control-allow-origin-header-is-present
