### ISSUE TITLE
Teveel redenen

### ISSUE THREAD

**Issue by hansmarks** [NL-AMS-LOCGOV/zaakafhandelcomponent#544]
In de zaak-view-component hebben we inmiddels 6 reden-formFields. Deze vervangen door eentje omdat er toch nooit meer dan een open kan staan.

(Dit is niet een voorstel om iets te veranderen aan hoe het eruit ziet op het scherm.)

**Comment by RoyBuis** [comment]
Bespreken of het effect heeft of dat sommige redenvelden verplicht worden en anderen niet
