### ISSUE TITLE
Actuele contactgegevens toevoegen aan persoon/bedrijf

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#556]
***Als*** Behandelaar

***Wil ik*** de aangehaakte contactgegevens van persoon/bedrijf willen ophalen 

***Zodat*** actuele contactgegevens kan inzien van een persoon/bedrijf

***

### Acceptance criteria:
- Gebruik maken van de Klanten API

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

**Comment by robertverboom** [comment]
![image](https://user-images.githubusercontent.com/94612050/156369788-920471e0-1386-4424-be84-7cfd499f1003.png)

**Comment by robertverboom** [comment]
![image](https://user-images.githubusercontent.com/94612050/156370522-82ac3f27-5c51-42fe-8313-f248a7bd6208.png)

https://vng-realisatie.github.io/gemma-zaken/standaard/verzoeken/Verzoeken%20API%201.0.0b.png

**Comment by RoyBuis** [comment]
refinement:
Functioneel:

- Contactgegevens persoon ophalen via Klanten API, zie https://github.com/maykinmedia/open-klant/issues
- Ophalen telefoonnummer en emailadres uit API
- zoeken op bsn
- 2e telefoonnummer niet beschikbaar
- Tonen bij de persoonsgegevens blok boven de zaak
- Contactgegevens bedrijf ook via Klanten APi

Architectuur:

- Eerst uitzoeken of de Klanten APi gebruikt moet worden voor deze contactgegevens. 
- Actie Roy: Voorleggen in architectuuroverleg.
-

**Comment by RoyBuis** [comment]
Architectuurverleg 15-3:

- Bij initiator van zaak tonen we contactgegevens uit https://vng-realisatie.github.io/gemma-zaken/standaard/klanten/index
- De contactgegevens uit startformulier kunnen straks bekeken worden door de mogelijkheid om het hele startform te bekijken

**Comment by Snijhuis** [comment]
Voorlopig on hold: De klantenAPI nog niet implementeren. Aan contactgegevens ophalen zit ook aan doelbinding. Wie mag wanneer deze gegevens zien? 
Later refinen en uitwerken

**Comment by CommonGroundGroningen** [comment]
Contactgegevens berdrijven (mail, telefoonnummer) zijn geen aanvullende gegevens, maar basisgegevens . Voor persoonsgegevens zijn dit wel aanvullende gegevens, dus daar moet je wel kijken naar AVG etc.

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Story is via ander issue gerealiseerd.
