### ISSUE TITLE
Taakhistorie

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#564]
***Als*** behandelaar

***Wil ik*** de taakhistorie kunnen inzien van een taak

***Zodat*** de relevante wijzigingen van de taak kan terug vinden 

***

### Acceptance criteria:
- 

***
### Prioriteit

- Must haves

**Comment by RoyBuis** [comment]
Refinement 3-3:

Uitzoeken of het mogelijk is om de historie die Flowable maakt te gebruiken
Kijken naar niveau van historie in Flowable, op 'full' zetten

Spike inplannen om uit zoeken wat er nu wordt opgeslagen als historie. 

Bedenken waar we historie, en andere gegevens die niet in Open zaak past, willen opslaan. Mogelijk in Overige registraties?
Kijk hier naar: HistoricTaskLogEntryBuilder

Daarna opnieuw refinen om keuzes te maken.

**Comment by Snijhuis** [comment]
23-03 WG Refinement
1. Overdragen/ opnieuw toewijzen van een taak. Vastleggen actie + overdragen
2. Document aan taak toegevoegd: vastleggen bij taak of bij zaak? Nu vastgelegd bij Zaak en document. Navragen bij Atos wat nodig.
3. Uitgangspunt: e-Suite als basis voor taakhistorie? Moet archiefwaardig zijn in ieder geval. Vanuit DIV/IB als persona ook naar kijken. --> voorleggen aan WG Informatiebeheer.

**Comment by RoyBuis** [comment]
Te refinen:

- kunnen de genoemde wijzigingen worden vastgelegd in historie
- UI: hoe kan de zaak-/taakbehandelaar de wijzigingen inzien

**Comment by RoyBuis** [comment]
Refinen en schatten tijdens sprintplanning

**Comment by bartlukens-atos** [comment]
Spike:
Uitzoeken welke historie wordt opgeslagen in flowable. Kijk ook naar de historie setting (zie commentaar hierboven).
