### ISSUE TITLE
BUG: email controle wordt niet gedaan

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#599]
***Steps to reproduce:***

1. Ga naar Mail versturen pagina
2. Voer een naam in de ontvanger

***Expected***
Verwacht een 'email' controle, zoniet dan de juiste foutmelding 

***Actual***
een letter is voldoende om te versturen.

**Comment by hansmarks** [comment]
Reguliere expressies overgenomen uit de eSuite. In overleg met Roy de validate voor meerdere E-Mail adressen ( ;- gescheiden) erop gezet. Maar de validator voor een enkel E-Mail-adres is ook beschikbaar.

**Comment by hansmarks** [comment]
https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/pull/620

**Comment by robertverboom** [comment]
test ok
