### ISSUE TITLE
Zaakafhandelcomponent: Aanmaken abonnement op zaak notificaties automatiseren

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#60]
Lokaal draaien moet er geen abonnement worden aangemaakt. 
- Parameters meegeven 'LocalDev' bool

Spike: Onderzoeken of autorisatietoken gelezen kan worden door andere applicaties. Onderzoeken hoe de rechten (scopes) geinterpreteerd moeten worden.

Vraag; Zou het mogelijk moeten zijn dat alle applicaties alle abonnementen moeten lezen?

**Comment by robertverboom** [comment]
Spike: Onderzoeken of autorisatietoken gelezen kan worden door andere applicaties. Onderzoeken hoe de rechten (scopes) geinterpreteerd moeten worden.

Vraag; Zou het mogelijk moeten zijn dat alle applicaties alle abonnementen moeten lezen?

Timeboxed: 4h

**Comment by andyverberne** [comment]
Het is niet mogelijk om geautomatiseerd een abonnement aan te maken. 
Reden is dat het niet mogelijk is om het autorisatie token mee te geven via een API call.
Het abonnement zal handmatig aangemaakt moeten worden.
