### ISSUE TITLE
Tonen van startformulier bij zaakgegevens pagina

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#603]
***Als*** behandelaar

***Wil ik*** wil ik het startformulier inzien

***Zodat*** ik de gegevens van de burger bij de hand heb. 

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

**Comment by robertverboom** [comment]
Oplossingsrichting:

Alle zaakacties worden net als 'initiator toevoegen' met rechter side nav getoond. Naast Mail versturen, Document toevoegen, dus ook 'Inzien start formulier'
De paginering wordt gerealiseerd d.m.v. een verticale Stepper (zie zaakafhandelparameters). Afstand tussen de twee steps te verkleinen.
Wanneer de gebruiker 'buiten' de rechter side nav klikt, wordt de informatie van dat moment bewaard.

**Comment by robertverboom** [comment]
Zie oplossingsrichting #260

**Comment by RoyBuis** [comment]
Refinement 21-3:
keuze: een link naar het Open Formulieren aanvraag PDF-document binnen de zaak maken
Selectie obv private static final String ZAAK_INFORMATIEOBJECT_TITEL = "Aanvraag PDF";

**Comment by robertverboom** [comment]
test ok
