### ISSUE TITLE
9.X Afsluiten/afhandelen zaken

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#607]
Epic voor het afsluiten/afhandelen van zaken.

Omdat er al veel functonaliteit is opgenomen in user stories bij de 6B Epics (behandelen zaken) heb ik 1 Epic gemaakt waaronder user stories kunnen worden opgevoerd die nog niet bestaan.

Denk aan stories rondom:

9.1 Vastleggen besluit (procesactietermijn)
9.2 Vastleggen resultaat
9.3 Terugkoppeling naar Burger/bedrijf
9.4 Publiceren besluit
9.5 Verzenden documenten (Zie ook epic 7.8)
9.6 Status wijzigen
9.7 Besluiten / (digitaal)ondertekenen / goedkeuren (Zie ook epic 7.6)
9.8 Document creëren = epic 7.1

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Epic wordt gesloten.
