### ISSUE TITLE
Improvement: ZGWClientHeadersFactory.putMedewerkerToelichting() en removeMedewerkerToelichting()

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#619]
De samenwerking van ZGWClientHeadersFactory.putMedewerkerToelichting() en removeMedewerkerToelichting() is foutgevoelig,

**Comment by hansmarks** [comment]
Hier schuilt misschien een oplossing in omdat de Java-doc zegt dat je ook @Context parameters kunt gebruiken op die factory.

https://stackoverflow.com/questions/20937362/what-objects-can-i-inject-using-the-context-annotation

**Comment by hansmarks** [comment]
Finally verplaatst naar de clientheaderfactory en nog wat fijngeslepen aan de naamgeving.
