### ISSUE TITLE
BUG: Wanneer een zaakstatus afgerond is, kan je de zaak alsnog afbreken 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#623]
***Steps to reproduce:***

1. Maak een zaak aan
2. Rond de zaak volledig af (of breek hem handmatig af)
3. Controleer de status

***Expected***
Nadat de status afgrond (laatste fase) is, verwacht ik de functie zaak afbreken niet meer te kunnen. 

***Actual***
Je kan de zaak afbreken, maar de functionaliteit werkt niet meer. Blijft hangen, omdat de zaak al afgrond is.

**Comment by hansmarks** [comment]
Opgelossing meegenomen in #625

**Comment by robertverboom** [comment]
test ok
