### ISSUE TITLE
BUG: Taken worden verwijderd bij het Handmatig afhandelen 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#624]
***Steps to reproduce:***

1. maak een zaak aan
2. zet de zaak in behandeling
3. Maak de 3 taken aan

***Expected***
Openstaande taken:
ingevulde velden blijven bewaard en zijn te raadplegen
taak krijgt bij handmatig afhandelen van de zaak de status 'Afgerond' maar wordt getoond als 'Afgebroken'. Evt ook verdere visuele verduidelijking maken.
Boolean Afgebroken == true (op de taak)

***Actual***
De taken worden verwijderd

**Comment by robertverboom** [comment]
Zie #504

**Comment by bartlukens-atos** [comment]
- Uitzoeken wat er met de taken gebeurd

**Comment by robertverboom** [comment]
De zaken die zijn afgebroken/afgerond verwachten een andere Case UUID. Geeft een 500 fout terug

**Comment by robertverboom** [comment]
Steps: 

1 ga naar zaak: ZAAK-2022-0000000678 heeft alle taken. ZAAK-2022-0000000679 heeft alleen niet afgeronde aanvullende info  
2. Toggle 'toon afgeronde taken' aanvinken
3. de taken openen

Expected: 
Alle taak behandel formulieren worden als 'read only' getoond


Actual: 
De behandel taak formulieren worden niet getoond door het handmatig afbreken van de zaak:
niet afgerond aanvullende info
niet afgerond goedkeuren
niet afgerond advies intern
niet afgerond advies extern wordt naar behoren getoond. 

Wanneer een taak wel is afgerond, voordat de zaak handmatig is afgebroken wordt deze wel volledig getoond

**Comment by robertverboom** [comment]
test  ok
