### ISSUE TITLE
BUG: Minimaal 1 reden moet verplicht zijn bij Zaak afbreken in de zaakafhandelparameters

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#625]
***Steps to reproduce:***

1. Ga naar de zaakafhandelparameters 
2. Vink alle zaakbeindiging gegevens uit
3. Maak een zaak aan (met dat juiste zaaktype)
4. probeer een zaak af te breken

***Expected***
Volgens de specs #504
Zaakafhandelparameters:
Reden bij zaakafhandelparameters min 1 verplicht maken. (Nu nog niet het geval)

***Actual***
je kan nu niks kiezen

**Comment by hansmarks** [comment]
Klopt, dit is afgestemd met Andy. En die zei: "Moeten ze het maar goed inrichten. En als ze dat niet doen, dan komen ze daar snel genoeg achter."

**Comment by hansmarks** [comment]
Overlegd met Robert, Knop niet tonen als geen afbreekredenen geconfigureerd.

**Comment by hansmarks** [comment]
https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/pull/656

**Comment by robertverboom** [comment]
test ok
