### ISSUE TITLE
7.4.5 Ontkoppelen van document opslaan bij historie document

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#628]
***Als*** Zaakbehandelaar/ DIV

***Wil ik*** dat het ontkoppelen van document bij een zaak als historie bij het document wordt opgeslagen

***Zodat*** ik kan zien waar het document aan gekoppeld was (zaak) en wanneer en door wie het document is ontkoppeld.

NB. Bij de zaak wordt dit al opgeslagen. Story gemaakt n.a.v. sprintreview 23-03 van oplossing #365

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

**Comment by RoyBuis** [comment]
Refinen en schatten tijdens sprintplanning

**Comment by bartlukens-atos** [comment]
Bij het document wordt de history van het enkelvoudig informatieobject (document) getoond. Het ontkoppelen van het document verandert niets aan het document zelf. De koppeling tussen een document en de zaak ligt bij de zaak. De ontkoppel actie wordt wel vastgelegd in de history van de zaak.

**Comment by RoyBuis** [comment]
Deze is gerefined en de conclusie is dat deze niet uit te voeren is.

Bij het document wordt de history van het enkelvoudig informatieobject (document) getoond. Het ontkoppelen van het document verandert niets aan het document zelf. De koppeling tussen een document en de zaak ligt bij de zaak. De ontkoppel actie wordt wel vastgelegd in de history van de zaak.

**Comment by Snijhuis** [comment]
Teruggekoppeld aan groep. Akkoord
