### ISSUE TITLE
Iedere medewerker moet een taak kunnen bewerken

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#63]
Iedere medewerker moet taak kunnen bewerken:
 
- Aanpassen van groep
- Aanpassen van behandelaar

**Comment by robertverboom** [comment]
### Refinement:

eerst een component maken voor toekennen, zie gelinkt issue ESUITEDEV-25989
Uitgangspunten:

een taak moet altijd een groep hebben
iedere medewerker moet een taak kunnen bewerken
een afgeronde taak mag niet bewerkt worden (het enige overblijvende recht)

**Comment by andyverberne** [comment]
@ronniekoopmans-atos : Omdat voor dit issue wellicht ook classes moeten worden verwijderd rondom rechten daarom deze even op jouw naam gezet

**Comment by robertverboom** [comment]
test ok
