### ISSUE TITLE
Een inbewerkcomponent verwijderen met extra check

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#630]
***Als*** Behandelaar

***Wil ik*** een een extra check hebben voordat 'iets' verwijder

***Zodat*** ik niet te snel/perongeluk data verwijder

***

### Acceptance criteria:
-

***
### Prioriteit

- Could haves

***
## Gerealiseerd
Bij bijvoorbeeld de prullenbakjes; Document verwijderen of initiator verwijderen komt een pop-up met de vraag weet u het zeker.

**Comment by VictorTielenius** [comment]
een extra check hebben voordat 'iets' verwijder: Document verwijderen of initiator verwijderen komt een pop-up met de vraag weet u het zeker.
Getest in zaak ZAAK-2022-0000000081
Doc verwijderen: Reden opgeven: OK
Initiator verwijderen: JA/Nee pop-up: OK
