### ISSUE TITLE
Extra gegevens over ontkoppeling bij werklijst Ontkoppelde documenten 

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#638]
***Als*** DIV-medewerker

***Wil ik*** in de werklijst Ontkoppelde documenten kunnen zien welke behandelaar op welke datum een document heeft ontkoppeld en bij welke zaak deze hoorde

***Zodat*** ik in één oogopslag kan zien wanneer en door wie documenten zijn ontkoppeld en daardoor eenvoudiger mijn taken kan uitvoeren en de juiste bestemming voor de documenten kan inschatten 

***

### Acceptance criteria:
-

***
### Prioriteit
- Should haves

***
### Gerealiseerd
Er zijn extra kolommen toegevoegd bij de werklijst Ontkoppelde documenten: 
- Zaak
- Ontkoppeld door
- Ontkoppeld op
- Reden

**Comment by RoyBuis** [comment]
Refinen en schatten tijdens sprintplanning

**Comment by VictorTielenius** [comment]
Document verwijderen geeft foutpagina (Foutpagina
De server heeft code 500 geretourneerd)

**Comment by VictorTielenius** [comment]
Hertest #1590:
Nu een PDF en een Word document te verwijderen zonder foutpagina te krijgen
