### ISSUE TITLE
Locatie koppelen bij startenvan een nieuwe zaak DEEL 2 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#643]
Tonen van Locatie in zaakgegevens, ruwe data converteren naar adres invoeren e.d. 

#433

**Comment by bartlukens-atos** [comment]
Alleen een punt kunnen kiezen en het bijbehorende adres opzoeken, deze wordt getoond in het inputveld bij het aanmaken van een zaak. Coordinatien worden opgeslagen.

Op de zaak de mogelijkheid om de locatie te kunnen wijzigen.

Tonen van de locatie:
- adres in zaak gegevens tonen
- openen van kaartje door op een button te klikken
