### ISSUE TITLE
Signalering document toegevoegd aan zaak op mijn naam

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#645]
***Als*** Zaakbehandelaar

***Wil ik*** een signalering ontvangen als iemand anders een document toevoegt aan een zaak die op mijn naam staat

***Zodat*** ik weet dat er nieuwe infomatie bij mijn zaak is toegevoegd

***

### Acceptance criteria:
- geen signalering als ik het document zelf toevoeg
- signalering verdwijnt als gebruiker de zaakgegevenspagina of taakgegevenspagina ~~of documentgegevenspagina~~ geopend heeft
- alle overige signaleringen over documenten bij de zaak op de zaak verdwijnen zodra de zaak, taak of een van de documenten een keer geopend is

***
### Prioriteit
- Must haves

### Gerealiseerd
Wanneer de gebruiker op zijn naam icoon klikt, komt er een optie om signaleringen in te stellen. Door het aanvinken van deze opties, worden de signaleringen getoond op het dashboard in verschillende 'cards'

***Belangrijkste functionaliteiten:***
- Wanneer een nieuwe persoonlijke signalering binnen komt, zal er een indicatie badge getoond worden op het dashboard icoontje. 
- wanneer de zaak bekeken is via het dashboard, dan verdwijnt de zaak van de card

**Comment by RoyBuis** [comment]
Functioneel:
- Titel card:  Recent aan mijn zaken toegevoegd documenten

Technisch:
- Nieuwe signalering maken (type toevoegen aan database)
- Plekken opzoeken waar de signalering gegenereerd moet worden
- Card om de signalering te tonen
- Code om signalering weer te verwijderen

**Comment by hansmarks** [comment]
De card laat geen documenten zien maar zaken (waaraan een of meer documenten zijn toegevoegd). Daarom heb ik de titel aangepast naar:

**Mijn zaken met recent toegevoegde documenten**

**Comment by hansmarks** [comment]
In het kader van de change voor deze story is aan het signaleringen in het algemeen (of eigenlijk aan signalering-events) een zogenaamde actor toegevoegd (de medewerker die direct of indirect het signalerings-event heeft veroorzaakt, bijvoorbeeld door iets te wijzigen of toe te voegen).

Als deze actor gelijk is aan de target (de medewerker die de signalering moet ontvangen) dan zal de betreffende signalering onderdrukt worden. (lees: de signalering verschijnt niet in een card, wordt niet gemaild, etc.)

Dit geldt voor **alle** signaleringen (het is generieke functionaliteit) maar de voorwaarde is natuurlijk wel dat de actor op de plaats waar het signalering-event vandaan komt "bekend" moet zijn.

_Bij signaleringen events die voortkomen uit notificaties vanuit open-notificaties is dat bijvoorbeeld niet het geval. Dit soort signaleringen kunnen dus niet onderdrukt worden als de target gelijk is aan de actor._

**Comment by RoyBuis** [comment]
Wijziging in de acceptatiecriteria: de signalering verdwijnt **niet** als de documentgegevenspagina van het document is geopend. Functioneel kan dit nu ook niet omdat een document altijd via een zaak of taak wordt geopend. Conclusie: de signalering verdwijnt dus als de zaak of een taak van de zaak is geopend.

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
@robertverboom Wil jij wat documenten aan deze zaak ZAAK-2022-0000000226 toevoegen zodat ik hiervan een signalering krijg in mijn Dashboard

**Comment by HilbrandHurtak** [comment]
Test ok
