### ISSUE TITLE
Rechten binnen ZAC

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#664]
Opzet besproken op 29 maart:

**Uitgangspunten functioneel**
- Basisrollen per persona per zaaktype (bijv Zaakbehandelaar Evenementenmelding)
- Specifieke rollen (bijv Recordmanager, Functioneel beheerder)
- Basisrol heeft een vaste set aan rechten (bij Zaakbehandelaar mag zaak van zaaktype raadplegen en bewerken, minder fragmentatie dan in e-Suite)
- Specifieke rol heeft een vaste set aan rechten maar dan zaaktypeoverstijgend
- Rollen op groepsniveau? Bijv als gebruiker X bij Groep A hoort dan heeft hij automatisch de rechten die horen bij die groep 
- Voor zaakspecifieke autorisatie uitzoeken wat behoefte is. Use cases uit de praktijk hierbij verzamelen

**Uitgangspunten doelbinding**
Welke rol mag welke gegevens van een zaak zien, dit betreft met name:
- Persoonsgegevens en bedrijfsgegevens
- Aangehaakte gegevens

**Comment by RoyBuis** [comment]
Acties uit refinement 30-3:

Stap 1
- Functionele beschrijving maken van de gewenste opzet, inclusief eerste overzicht rollen (Sander. Roy)
- Bespreken binnen Dimpact met juiste stakeholders (Sander)
- Behoefte aan zaakspecifieke autoristatie in kaart brengen, use cases verzamelen (Sander)

Stap 2
- Opzet vastleggen in datamodel (Atos)
- Opzet toetsen bij VNG werkgroep (Andy)
- Nieuwe refinementsessie om vervolgstappen te bepalen

**Comment by Snijhuis** [comment]
Bijgevoegd 2 bestanden:
1. Autorisatie ZAC.docx: beschrijving van uitgangspunten (aantekeningen)
2. Autorisatie opzet.png: een mogelijke opzet voor de inrichting van functies. Gebaseerd op voor gedefinieerde  basisrollen/roltypen.

Toelichting: 
Het gaat nu vooral om de opzet. Samen tijdens refinement bespreken volgende week maandag!

[Autorisatie opzet.png] (https://images.zenhubusercontent.com/61a7728f4b7bcc716765fdd1/1d415cea-ee5b-4a7b-a510-ff5256ae3315)[https://app.zenhub.com/files/416646145/14f75e2f-5902-4aae-b27a-182ccf6fe42a/download](https://app.zenhub.com/files/416646145/14f75e2f-5902-4aae-b27a-182ccf6fe42a/download)
[https://app.zenhub.com/files/416646145/6283f79f-5dae-463a-8226-e8fdf4e1d95f/download]

**Comment by robertverboom** [comment]
[AutorisatieZac.pdf](https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/files/8716149/AutorisatieZac.pdf)

**Comment by PaskalKiers** [comment]
![image](https://user-images.githubusercontent.com/98458831/183093155-595c59d7-95cc-4614-9cae-2a45cb00087a.png)

We proberen nu in de WG refinement en acceptatie de basisrollen en dergelijk in te vullen, terwijl ik nog zoek naar hoe de structuur in elkaar zit om eea te toetsen. Nu kwam ik dit GIThub item tegen en ik heb het proberen te vertalen naar een relatiediagram (ik ben wat roestig en het is nooit mijn ding geweest, dus verbeter me vooral)    Ik heb drie toevoegingen gemaakt.  De gebruiker, de groep en een soort van koppeling tussen zaaktype en persoonsgegevensrechten.   Die laatste volgde voor mij uit de grijze blokken hierboven. Gebruikers heb ik via een groep gekoppeld aan een functie, maar zou misschien ook rechtstreeks moeten kunnen.   In discussies komt beiden naar voren.

Klopt dit een beetje?  Ik zit zelf nog te twijfelen of het nu ook klopt voor de generieke roltype. Zoals het hierboven besproken wordt niet denk ik. Want voor generieke roltypen worden geen zaaktypen gekoppeld en dat betekent dat alles bekeken mag worden.  

Uit de heup zie ik twee risico's: 1 je hebt twee autorisatiemodellen die gespiegeld werken, wat de kans op vergissingen vergroot.  2. Er geen uitzondering mogelijk voor zaaktypen die niet bekeken/bewerkt mogen worden met een generieke functies.

Het is wel makkelijker onderhouden als je voor generieke rollen alleen de uitzondering hoeft te definiëren.

Het doet me eraan denken dat het plaatje nog niet compleet is, er kunnen zaakspecifieke rechten die gezet worden en volgens mij ook iets met gevoelige zaken (of is dat hetzelfde?)  Loopt dat via users of groepen? 

De autorisatie op data is alleen op persoonsgegevens, hoe zit het met documenttypen, daar heb ik volgens mij wel wat langs zien komen, maar dat wordt in bovenstaande ook nog niet expliciet benoemd. Is misschien wel relevant als je wilt voorkomen dat gebruikers via een document alsnog gegevens te zien krijgen die ze niet mochten zien.
Ook andere data (financiele gegevens bijvoorbeeld)  wil je ook af kunnen schermen.  In de context van de ZAC nu niet natuurlijk, maar is het model dat nu is ontworpen robuust genoeg om ook dergelijke uitbreidingen aan te kunnen?

**Comment by robertverboom** [comment]
[https://app.zenhub.com/files/416646145/04013dca-3b10-4157-a3bc-554242ba2899/download](https://app.zenhub.com/files/416646145/04013dca-3b10-4157-a3bc-554242ba2899/download)

**Comment by robertverboom** [comment]
Refinement 22-09:
- Beheerder mag alles en is zaaktype onafhankelijk. 
- Basisrol Behandelaar, recordmanager & zaakcoordinator (geldt voor elk zaaktype) per setje zaaktypes een aparte rol. 
- Zaaktypes worden gekoppeld aan rol (DomeinA, DomeinB, DomeinC)

**Comment by andyverberne** [comment]
Wijzigen:

- [ ] Coderen: Zaak alleen kunnen heropenen wanneer deze gesloten is.

**Comment by andyverberne** [comment]
ToDo:
- [ ] Werklijsten acties realiseren (app acties verwijderen)

**Comment by andyverberne** [comment]
[https://app.zenhub.com/files/416646145/f56f4357-ddf1-416b-9f6a-b35718c92e0e/download](https://app.zenhub.com/files/416646145/f56f4357-ddf1-416b-9f6a-b35718c92e0e/download)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Issues zijn gerealiseerd. Epic wordt gesloten.
