### ISSUE TITLE
Gebruik maken van auth token in notificaties van Open Zaak naar ZAC

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#67]
Het zaakafhandelcomonent ontvangt notificaties vanuit Open Zaak. In het abonnement kan een auth token worden opgegeven. Het ZAC moet controleren of dat token, wat door Open Zaak weer wordt meegegeven in de notificatie, klopt.

Dit is ook meteen een fix voor[ESUITEDEV-25426](https://jira.sdmc.ao-srv.com/browse/ESUITEDEV-25426)

**Comment by andyverberne** [comment]
Dit is een duplicaat van #61
