### ISSUE TITLE
9.3.1. Terugkoppeling via Mail

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#671]
Als zaakbehandelaar

Wil ik een mail naar de aanvrager of andere betrokken partijen kunnen sturen 

Zodat er vanuit de zaak via mail kan worden gecommuniceerd met de aanvrager/betrokkenen en de verzonden mail wordt opgeslagen bij de zaak en gearchiveerd kan worden

Acceptance criteria:

•	Meerdere documenten moeten kunnen worden geselecteerd en als bijlage met de mail worden verstuurd.
•	Bij het selecteren van de documenten wordt gevalideerd of de bestandsgrootte van het totaal aan geselecteerde documenten 
        niet te groot is om via de mail te versturen
•	Per zaaktype kunnen bepalen of de mailfunctionaliteit wel/niet beschikbaar moet zijn
•	De zaakbehandelaar kan zelf kiezen of de mail naar de aanvrager of andere betrokken partij(en) wordt verstuurd (keuzemoment)
•	De mail kan automatisch vanuit het proces worden verstuurd op basis van een vooraf gedefinieerde sjabloon / template
•	De mail kan worden verstuurd vanuit het mailadres van de behandelaar.
•	Indien de behandelaar niet zijn eigen e-mailadres wil gebruiken(privacy redenen) zou ook de mail verstuurd moeten kunnen 
        worden vanuit het centraal e-mailadres van de gemeente of een specifiek mailadres van de afdeling of groep
•	De specifieke e-mailadressen van de afdeling of groep moeten alleen geselecteerd kunnen worden als dit bij de configuratie van 
        het zaaktype is bepaald.
•	Bij het opstellen van de mail kan gebruik worden gemaakt van een sjabloon
•	Bij het opstellen van de mail kan ook zelf het onderwerp en de inhoud worden ingevoerd
•	De verzonden mail wordt als document bij de zaak opgeslagen

Prioriteit

- Must haves
### Gerealiseerd
**Let op: na de oplevering van deze story zijn er nieuwe stories gerealiseerd die deze functionaliteit hebben veranderd. Deze stories zijn meegenomen in de 'gerealiseerd' beschrijving.**
_Omschrijving van de op te leveren functionaliteit in deze story_
Bij het afhandelen van een zaak is het mogelijk om een belanghebbende een standaard mail hierover te sturen. De behandelaar kan zelf kiezen óf en aan welk e-mailadres deze mail verstuurd wordt. De verzonden mail wordt als document aan de zaak gekoppeld. 
De inhoud van deze mail wordt bepaald door de mailtemplate 'Zaak afgehandeld'. De beschikbaarheid van deze mail is in de Mailgegevens tab van de zaps in te stellen bij 'Statusmail afronden fase'.

***Belangrijkste functionaliteiten:***
- Gebruiker kan bij het uitvoeren van de actie [Zaak afhandelen] kiezen om een mail te versturen door 'Verzend mail' aan te vinken
- Gebruiker kan de te gebruiken afzender van de mail kiezen
- Gebruiker kan het e-mailadres van de ontvanger van de mail invullen. Als het e-mailadres van de initiator bekend is dan kan deze worden toevoegen door op het poppetje icoon in het veld te klikken.
- Gebruiker kan de inhoud van het bericht bekijken door op het pijltje in het ‘Bericht’ veld te klikken
- Gebruiker kan de verzonden mail als document bij de zaak inzien
- Gebruiker kan de beschikbaarheid en standaard waarde van de 'Verzend mail' optie in de 'Mailgegevens' tab van de zaps instellen bij 'Statusmail afronden fase'
- Gebruiker kan de beschikbare mailafzenders bij de 'Verzend mail' optie in de 'Mailgegevens' tab van de zaps instellen bij 'Mailafzenders'
- Gebruiker kan de te gebruiken template van de mail in de 'Mailgegevens' tab van de zaps instellen bij de 'Zaak afgehandeld' mailtemplate

**Comment by robertverboom** [comment]
### Refinement 12-07:
- Bij het afhandelen van een zaak een mogelijkheid maken om een terugkoppelingsmail te sturen. 
- Roy komt met een standaard tekst

**Comment by CommonGroundGroningen** [comment]
Test OK
