### ISSUE TITLE
9.3.3. Terugkoppeling via MijnOverheid - Berichtenbox

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#674]
Als zaakbehandelaar

Wil ik documenten in MijnOverheid -de berichtenbox van de aanvrager kunnen plaatsen

Zodat personen via MijnOverheid - de berichtenbox kunnen worden geïnformeerd 

Acceptance criteria:

•	De functionaliteit voldoet aan de eisen m.b.t. het landelijke koppelvlak voor MijnOverheid - de berichtenbox
•	De functionaliteit is van toepassing op personen als aanvrager
•	Het systeem valideert of de aanvrager heeft aangeven via MijnOverheid - de berichtenbox geïnformeerd te willen worden
•	Als de aanvrager heeft aangegeven dat deze niet via MijnOverheid - de berichtenbox wil worden geïnformeerd dan biedt het 
        systeem, o.b.v. een signaal vanuit MijnOverheid - de berichtenbox, een alternatief kanaal (conditionele flow) om de aanvrager te 
        kunnen informeren (bijvoorbeeld mail of post)
•	De zaakbehandelaar kan aangeven welke documenten er overgezet moeten worden naar MijnOverheid - de berichtenbox
•	Het systeem valideert of de totale grootte van de geselecteerde documenten de maximale toegestane grootte aan documenten 
        van MijnOverheid - de berichtenbox niet overschrijdt

Prioriteit

- Must haves

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Deze story wordt opgepakt via #2483
