### ISSUE TITLE
9.3.7 Terugkoppeling via tool voor bestanden delen

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#676]
Als zaakbehandelaar / Ondersteuner (=administratie)

Wil ik grote bestanden of een grote hoeveel bestanden met een aanvrager / ketenpartner kunnen delen

Zodat deze in 1 keer beschikbaar zijn zonder tegen beperkingen m.b.t. omvang aan te lopen zoals bijvoorbeeld via de mail

Acceptance criteria:
•	De bestanden worden via een beveiligde oplossing gedeeld waarbij de privacy gevoelige informatie in de bestanden 
        gewaarborgd is.
•	De oplossing biedt voldoende ruimte (bijvoorbeeld 1 Gigabyte) om bestanden uit een groot dossier te kunnen delen, met 
        melding als grootte overschreden wordt.

Prioriteit

- Must haves

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Het ligt aan de mailclient hoe groot te verzenden bestanden kunnen zijn. In de omgevingsvariabele van de ZAC is in te stellen hoe groot de bestanden van toe te voegen zaakdocumenten mogen zijn.
