### ISSUE TITLE
9.3.2. Terugkoppeling via loketfunctionaliteit

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#677]
Als zaakbehandelaar

Wil ik zaakinformatie beschikbaar kunnen maken op een loket (PIP)

Zodat de aanvrager via een loketfunctionaliteit geïnformeerd kan worden met actuele zaakinformatie

Acceptance criteria:

•	Zaaktypen die Extern beschikbaar zijn op Loket (PIP) tonen.
•	Naam Zaaktype tonen (dit is nu op de PIP Onderwerp)
•	Zaaknummer tonen
•	Status van de zaak tonen op Loket (Huidige Status)
•	Omschrijving van de zaak tonen op Loket
•	Ontvangstdatum van de zaak
•	Datum afgehandeld  van de zaak (mits zaak is afgehandeld)
•	Resultaat van de zaak (mits zaak is afgehandeld)
•	Documenten (Zie 7.8.1) 
        Definitieve (Status) / extern beschikbare (Publicatie niveau) documenten van een Zaaktype die Extern beschikbaar is op Loket 
        (PIP) tonen.

Prioriteit

- Must haves

**Comment by desireebinder** [comment]
het zou mooi zijn wanneer we ook een verwachte afhandeldatum kunnen tonen in het Loket. Dit kan op basis van de doorlooptijd die aan de zaak toegevoegd wordt. 
zodoende weet de aanvrager wanneer ongeveer een resultaat verwacht mag worden. 
(bij een bezorging is uiteindelijk ook alleen de dag en het tijdstip van bezorging echt interessant voor de klant)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Dit wordt via de integratie met OIP gerealiseerd.
