### ISSUE TITLE
Document aan zaak toevoegen vanuit werklijst Ontkoppelde documenten

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#689]
***Als*** Als recordmanager  

***Wil ik*** vanuit de werklijst Ontkoppelde documenten een document aan een zaak kunnen toevoegen

***Zodat*** ik het document aan de juiste zaak kan koppelen

***

### Acceptance criteria:
-

***
### Prioriteit
- Must haves

***
### Gerealiseerd: 
Met het schaar icoon wordt een document op een 'clipboard' geplaatst. vervolgens kan de gebruiker de gewenste zaak opzoeken en het document vanuit het clipboard 'plakken'. 

Belangrijke aspecten: 
Er kunnen meerdere documenten tegelijk geknipt worden.

**Comment by robertverboom** [comment]
test ok
