### ISSUE TITLE
Startformulier beschikbaar maken bij zaak!

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#69]
Als medewerker wil ik het ingevulde startform kunnen inzien

**Comment by robertverboom** [comment]
### Refinement: 

Ophalen van objectregistratie object

Tonen van read-only velden uit starformulier

Mapping objectregistratie objecttype naar startformulier. Eerst hard coderen, daarna manier uitwerken om via configuratie te doen.

**Comment by RoyBuis** [comment]
Refinement 17-1:

- Knop beschikbaar maken naar overzicht met alle ingevulde gegevens
- Juist plek voor deze knop bedenken, in zowel zaak als taak (Robert en Bart denken hier over na)
- Uitgebreid en complex formulier maken in Open formulieren (Robert, Roy en Marc werken dit uit)

Deze story splitsen in issues, een voor de functionaliteit in het ZAC en één voor het formulier.
