### ISSUE TITLE
Focus op openstaande zaken in 'Mijn zaken' werklijst 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#693]
***Als*** zaakbehandelaar

***Wil ik*** in een oogopslag mijn openstaande zaken zien

***Zodat*** ik snel een overzicht heb van het werk dat ik nog moet doen

***

### Acceptance criteria:
-

***
### Prioriteit
- Must haves

***
### Gerealiseerd
Filter, sorteer en zoekopties zijn gerealiseerd in de werklijst 'Mijn zaken'. Deze opties kunnen als favoriet opgeslagen worden als favoriete werklijst.

**Comment by robertverboom** [comment]
Bewaren tot de SOLR engine op ZAC beschikbaar is

**Comment by HilbrandHurtak** [comment]
Er is de laatste tijd veel gewijzigd in de Mijn zaken en, Mijn Taken overzichten. Voor nu meer dan voldoende om snel een overzicht op maat te maken en te bewaren
