### ISSUE TITLE
Dialog en taak startformulierschermen verplaatsten naar rechter Sidenav

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#703]
Verversen gaat via een screenevent

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Onderstaande improvements zijn toegepast: Nu wordt er aan de rechterkant een panel geopend waar de gebruiker zijn werkzaamheden kan verrichten ipv dat er een nieuw scherm wordt geopend. 

***Belangrijkste functionaliteiten:***
- Wanneer 1 panel wordt geopend (bijvoorbeeld Document toevoegen), vervolgens wordt er in het panel iets bewerkt, scherm wordt door een outside click gesloten en weer heropend, dan worden de ingevoerde gegevens onthouden. Wanneer je tussendoor iets anders doet dan worden de gegevens niet bewaard.

**Comment by HilbrandHurtak** [comment]
Test OK door testers van Groningen. Ticket gesloten
