### ISSUE TITLE
refactor Layout taakscherm

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#709]
Om zaak en taak schermen consistent te maken en mede doordat straks ook documentpreview zichtbaar moet zijn op taakschermen, wordt de layout van de taakschermen aangepast: 

![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/10025c60-dcde-4ea5-9922-deb144768dfa)

**Comment by bartlukens-atos** [comment]
Layout:
Links (60%): taak formulier
Rechts (40%): Taakgegevens + tabbladen (Algmene gegevens, Verkorte zaak)

Onder (volledige breedte): Zaak documenten

**Comment by robertverboom** [comment]
Test ok
