### ISSUE TITLE
Locatiedata terug vinden in de historie

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#733]
***Als*** Behandelaar

***Wil ik*** de locatie gegevens in de historie terug zien

***Zodat*** ik terug kan zoeken welke locaties er gebruikt zijn

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by robertverboom** [comment]
Vervolg op: https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/433

**Comment by bartlukens-atos** [comment]
- Locatie in de historie tonen
- Verwijder knopje

**Comment by robertverboom** [comment]
test ok
