### ISSUE TITLE
Omgaan met signaleringen op taken welke afgesloten zijn

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#739]
Taken kunnen aanleiding geven tot een signalering. Bijvoorbeeld wanneer een taak op iemands naam wordt gezet. Maar wanneer de taak vervolgens wordt afgesloten, bijvoorbeeld omdat de zaak wordt afgebroken, dan ontstaat er een NullPointer in de SignaleringenRestService. Deze NullPointer is gefixed door nu ook afgesloten taken te retourneren. Maar is dat correct gedrag? Wat doen we met signaleringen op taken welke zijn afgesloten?

En kan zoiets ook voor Zaken gebeuren? (wanneer de Case is beeindigd)

**Comment by bartlukens-atos** [comment]
Signalering laten staan en bij het klikken op de knop naar de afgesloten zaak gaan
