### ISSUE TITLE
Groepen en medewerkers ophalen via LDAP

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#74]
https://forum.flowable.org/t/keycloak-idmidentityservice/5942/6

**Comment by RoyBuis** [comment]
Opnieuw refinen, ook kijken naar de rollen.

**Comment by andyverberne** [comment]
https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/user-federation/ldap.html

https://www.talkingquickly.co.uk/installing-openldap-kubernetes-helm

**Comment by andyverberne** [comment]
https://docs.bitnami.com/tutorials/create-openldap-server-kubernetes/

**Comment by robertverboom** [comment]
test ok
