### ISSUE TITLE
BUG: Koppeling met Mailjet zijn niet op de andere domeinen ingeregeld

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#751]
Ontvangsbevesting versturen, mail versturen, algemene info opvragen:

Op de zandbak, accept en test omgeving werkt de mailfuntionaliteit niet

**Comment by marcoatos** [comment]
Alleen Test was niet goed ingeregeld, heb daar een aanpassing Google Cloud gemaakt en een domein toegevoegd via Mailjet. 

Op de andere omgevingen ontbrak het informatieobject voor e-mail

**Comment by robertverboom** [comment]
test ok
