### ISSUE TITLE
Taak aanvullende informatie opvragen: tekstueel aanduiden dat je intern een taak wegzet voor het verwerken van aanvullende info

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#752]
***Als*** Zaakbehandelaar

***Wil ik*** zien dat ik bezig ben met het mailen van de klant voor aanvullende info en tegelijkertijd en taak wegzet intern voor het verwerken van deze informatie

***Zodat*** duidelijk wordt wat ik aan het doen ben binnen deze taak

Zie screenshot --> geel gearceerd de aanpassing
NB. De naam van taak 'Aanvullende info verstrekken' moet gewijzigd worden naar 'Aanvullende info verwerken'. De medewerker verwerkt de aanvullende info. Het verstrekken doet de burger.

'Aanvullende informatie verstrekken' is de taak die start na het afronden van de 'aanvullende info opvragen' starttaak.

***

### Acceptance criteria:
- 

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

- ![Aanvullende info opvragen.png](https://images.zenhubusercontent.com/61a7728f4b7bcc716765fdd1/dfbe15ee-cee4-4dc1-8391-3cea6c8f8acd) 
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Het is toegepast op alle taak start schermen waar een groep en behandelaar toegekend kan worden. 

***Belangrijkste functionaliteiten:***

-

**Comment by robertverboom** [comment]
## Refinement 05-05

- Opgevraagd + datum mag weg uit taakstart formulier
- Divider formfield maken 
- Fieldset legend; styling gelijk trekken met label van component

**Comment by HilbrandHurtak** [comment]
Bij het verzenden van de mail kon ik een taak aanmaken en toewijzen. De taak heet nu Aanvullende informatie. Voor mij was het duidelijk genoeg. Misschien dat er straks vanuit de koplopers nog nieuwe wensen komen.

De mailtemplate kon beter(geen zaaknummer bijvoorbeeld). In de sprint van 16-11-2022 werd nieuwe functionaliteit omtrent mailtemplates getoond. Als gemeente kun je dit dus zelf aanpassen en ook variabelen gebruiken . Voor nu lijkt me deze user story voldoende
