### ISSUE TITLE
Zaak: Bij niet ontvankelijk verklaren moet het redenveld een limiet krijgen op het aantal karakters

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#756]
***Als*** Zaakbehandelaar

***Wil ik*** dat het redenveld bij het niet-ontvankelijk verklaren van een zaak een limiet krijgt op het aantal karakters

***Zodat*** medewerkers de reden kort en bondig opgeven en geen lange verhalen hier gaat plaatsen.

***

NB. OpenZaak heeft een limiet van 1000 karakter voor de reden

### Acceptance criteria:
- Limiet in ZAC op reden veld bij niet-ontvankelijk verklaren van de zaak: 100 karakters
- Ook tonen aan de gebruiker dat er een limiet zit op dit veld. Wellicht met indicatie/telling van aantal tekens resterend (bijv. 100/100)

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Should haves

***
### Gerealiseerd
Bovenstaande US is gerealiseerd

**Comment by Snijhuis** [comment]
![image.png](https://images.zenhubusercontent.com/61a7728f4b7bcc716765fdd1/fcdbc617-cd2a-4eac-8391-042988f3ba80)

**Comment by RoyBuis** [comment]
Refinement 14-4:
Te realiseren:

- max lengte optie toevoegen aan reden veld
- max 100 karakters

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
redenveld bij het niet-ontvankelijk verklaren nu max. 100 karakters, en aantal gebruikte karakters ook in beeld: OK
