### ISSUE TITLE
Zaakgegevens: Icoon achter het resultaat en status wijzigen

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#757]
Achter het resultaat en de eindstatus van een zaak staat een vraagteken-icoontje (zie screenshot). 
Graag deze vervangen door een icoon die de lading dekt. Vraagteken lijkt op een hulptekst.

Eigenlijk is het een reden/toelichting bij het gezette resultaat /status. Een informatie-icoon (een i) of kladblok-icoon zou een optie kunnen zijn.
![image.png](https://images.zenhubusercontent.com/61a7728f4b7bcc716765fdd1/43fd9b70-1351-45b1-83db-d444d0334931)

**Comment by robertverboom** [comment]
https://fonts.google.com/icons?icon.query=info

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Icoontje gewijzigd in een I + toelichtende tekst bij mouseover actie. Voor nu prima
