### ISSUE TITLE
Documenttype toevoegen als kolom in documentoverzicht op Taak en Zaak niveau

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#759]
In het documentenoverzicht ontbreekt de kolom voor documenttype. Gemeenten willen dit ook graag zien in het overzicht.
Documentoverzicht wordt getoond op zowel Zaak als Taak-niveau dus daar graag aanpassen.
Zie screenshot
![image.png](https://images.zenhubusercontent.com/61a7728f4b7bcc716765fdd1/ee0f6ae8-fc8a-4010-9695-b5ab20b2a36a)

**Comment by RoyBuis** [comment]
Refinement 19-4:

Te realiseren:
- Kolom 'documenttype' (informatieobjecttype) toevoegen aan overzicht
- Positie op plek 2 na de titel

**Comment by robertverboom** [comment]
test ok
