### ISSUE TITLE
Improvement: Menu item Ontvangstbevesting sturen uit menu halen. 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#770]
Als een zaak is afgerond/afgebroken, of als een ontvangstbevestiging al eens is gestuurd dan hoeft het menu item ''Ontvangstbevesting sturen' niet meer getoond te worden.

**Comment by ronniekoopmans-atos** [comment]
heb ik reeds gefixed met omzetten scherm naar panel

**Comment by robertverboom** [comment]
test ok
