### ISSUE TITLE
Als ontwerper wil ik een bestaand taak formulier een andere naam geven

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#775]
De naam van het formulier voor de Advies extern taak "Extern advies vastleggen" is niet gewijzigd. Dat bleek toch lastig te zijn omdat dan oom de waarde in de database aangepast moet worden op alle omgevingen. Dat zou kunnen met eeb flyway script. Maar maak hier een nieuwe User Story voor aan: "Als ontwerper wil ik een bestaand taak formulier een andere naam geven" dan kunnen we die met het team refinen en er zo ovder nadenken

**Comment by RoyBuis** [comment]
Refinement 14-4:

Enumwaarden van formulierdefinitie een vertaling geven
