### ISSUE TITLE
BUG: Reden afbreken is te groot voor pop-up

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#776]
***Steps to reproduce:***

1. Maak een zaak
2. Zaak afbreken
3. Kies; "Verzoek is bij verkeerde organisatie ingediend." 

***Expected***
Gezien er geen extra redenen bijkomen, de popup een paar pixels groter hebben zodat de gehele tekst te lezen is

***Actual***
Wordt nu getoond: "Verzoek is bij verkeerde organisatie ingedi..."

**Comment by hansmarks** [comment]
MAT_DIALOG_DEFAULT_OPTIONS geintroduceerd met daar 500px als width en in alle bestaande dialogs de width verwijderd. Dus alle dialogs gelijk getrokken. met wel nog de mogelijkheid om daarvan af te wijken.

**Comment by robertverboom** [comment]
test ok
