### ISSUE TITLE
Signalering voor streefdatum taak

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#777]
***Als*** medewerker (intern) die advies geeft over de evenementenmelding

***Wil ik*** gesignaleerd worden als een adviestaak op mijn naam de streefdatum heeft bereikt

***Zodat*** ik weet dat ik in actie moet komen

***

### Acceptance criteria:
- signalering kan voor zowel binnen het ZAC (dashboard) als buiten het ZAC om door de gebruiker aan en uit gezet worden
- signalering verdwijnt binnen het ZAC zodra de taak of zaak geopend is
***
### Prioriteit
- Must haves

### Gerealiseerd
**Let op: een later gerealiseerde story heeft invloed op deze story gehad, zie #1438**
_Omschrijving van de op te leveren functionaliteit in deze story_
In de werklijst 'Mijn taken' is de aanduiding 'dagen tot fatale datum' toegevoegd. Hierin kan een gebruiker per taak zien hoeveel dagen nog resteren, een 'streepje' betekent dat de datum al bereikt is. Een behandelaar van een taak kan zich ook buiten het ZAC om per e-mail laten signaleren over bereiken van fatale datum van de taak. De signalering wordt verstuurd op de dag dat de fatale datum is bereikt. Het instellen hiervan kan een gebruiker bij de Signalering-instelling onder het profiel icoon doen.
***Belangrijkste functionaliteiten:***
- Gebruiker kan in de werklijst 'Mijn taken' in de kolom 'dagen tot fatale datum' per taak zien hoeveel dagen resteren tot de fatale datum. Een streepje in deze kolom betekent dat de datum bereikt is. Als een taak uberhaupt geen fatale datum had dan wordt ook een streepje weergegeven.
- De signalering wordt, indien ingeschakeld, per e-mail verstuurd naar het e-mailadres dat bij de gebruiker, in bijvoorbeeld KeyCloak, is ingesteld.
- De signalering wordt bij het bereiken van de fatale datum eenmaal verstuurd
- Gebruiker kan het versturen van de e-mail in- en uitschakelen door in het profielmenu de taaksignalering 'Mijn taak heeft de fatale datum bereikt' aan te passen

**Comment by RoyBuis** [comment]
dit was oorspronkelijk onderdeel van story #462

**Comment by Snijhuis** [comment]
1. Verzenden signalering wanneer streefdatum is bereikt
2. Behandelaar binnen ZAC: kaart op dashboard (instelbaar)
3. Behandelaar buiten ZAC: mail (instelbaar)

**Comment by RoyBuis** [comment]
### Refinement 28-4

**Te realiseren**

Signalering binnen het ZAC

- De gebruiker heeft nu al 'Mijn taken' werklijst. Hierin is in één overzicht te zien welke taken de streefdatum hebben bereikt. In deze lijst kan ook gestorteerd worden op streefdatum. Een card voegt op dit moment niets  hieraan toe.

- We maken een extra aanduiding van het aantal dagen voordat de streefdatum is bereikt en voegen deze toe aan de werklijst Mijn taken (technisch: dit gebeurt op dezelfde manier als de card voor signalering zaken)

Signalering buiten het ZAC
- Signalering per e-mail aan de gebruiker op wiens naam de staat
- e-mail wordt verstuurd op de dag dat de streefdatum is bereikt
- In de andere story (#778) is al een batchjob gemaakt waarin een query is gemaakt . Daar komt nu een query bij waarbij taken worden opgehaald waarvoor mails gestuurd moeten worden.

**Comment by marcoatos** [comment]
planning 02-06
Te realiseren:

Via Solr oplossen

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Signalering via mail moet nog worden getest(data is aangepast)
