### ISSUE TITLE
Signalering voor streef- en fatale datum zaak

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#778]
***Als*** zaakbehandelaar

***Wil ik*** gesignaleerd worden als een zaak op mijn naam de streefdatum of daarna de fatale datum bereikt

***Zodat*** ik weet dat ik in actie moet komen

***

### Acceptance criteria:
- signalering kan voor zowel binnen het ZAC (dashboard) als buiten het ZAC om door de gebruiker aan en uit gezet worden
- signalering verdwijnt binnen het ZAC zodra de zaak geopend is

***
### Prioriteit
- Must haves

***
### Gerealiseerd
Wanneer de gebruiker op zijn naam icoon klikt, komt er een optie om signaleringen in te stellen. Door het aanvinken van deze opties, worden de signaleringen getoond op het dashboard in verschillende 'cards'

Belangrijkste functionaliteiten:
- Wanneer een nieuwe persoonlijke signalering binnen komt, zal er een indicatie badge getoond worden op het dashboard icoontje.
- wanneer de zaak bekeken is via het dashboard, dan verdwijnt de zaak van de card

**Comment by RoyBuis** [comment]
Refinement 19-4:

Er zijn vele manieren om de signalering te laten werken. sander bespreekt met de werkgroep wat gewenst is, beredeneerd vanuit de personas: behandelaar in ZAC, behandelaar die zelden in ZAC komt en werkverdeler die een groep bewaakt

**Comment by Snijhuis** [comment]
1. Instellen van dagen voor streef en fatale datum per zaaktype een must.
Indien streef en fatale datum gelijk, dan alleen fataal sturen

2. Signalering moet je uit kunnen zetten per user.

3. Signalering binnen ZAC: dashboard is ok. In werklijst moet je ook kunnen zien/sorteren
Signalering buiten ZAC: werken met kalenderdagen is goed, wel vermelden.

4. Verplicht te vullen ?streef en fataal

5. Ook even kijken naar de werklijst story #442. (Sander)

**Comment by RoyBuis** [comment]
Refinement 25-4:

Te realiseren:
Interne signalering binnen ZAC:
- Per zaaktype instelbaar maken hoeveel kalenderdagen van te voren er gesignaleerd moet worden op streef- en fatale datum (bij zaakafhandelparameters, ook vermelden dat het om kalenderdagen gaat)
- Aantal dagen dat in te stellen is: 0 t/m 31
- Een interne signalering betekent dat de zaak moet verschijnen op het dashboard 
- Een card maken die alle openstaande zaken toont die de streef- of fatale datum gaan bereiken of bereikt hebben
- Card heeft 2 kolommen die het aantal resterende kalenderdagen toont tot de streef- respectievelijk fatale datum is bereikt 
- De card wordt altijd getoond
- Gebruiker kan de card sorteren op aantal resterende dagen van streef- of fatale datum en zaaktype

Buiten ZAC:
- Signalering wordt per e-mail verstuurd
- Versturen op de dag dat het ingestelde aantal dagen van  te voren is bereikt
- Gebruiker kan de signalering aan en uit zetten, zowel voor streef- als fatale datum

Technisch:
- Timer bean binnen ZAC die in database bijhoudt voor welke openstaande zaken er externe signaleringen gestuurd zijn
- Cron pattern voor schedulen timer bean is een environment variabele
- Functionaliteit implementeren in aparte bean welke aan te roepen is via REST call
- Zaken worden niet uit database verwijderd zodra de zaak beeindigd wordt

**Comment by RoyBuis** [comment]
Voor de externe signalering wordt een apart issue aangemaakt (schatting 34 uur). Deze wordt opgepakt na het issue voor de interne signalering.

**Comment by GertrudeKampherbeek** [comment]
discussie met werkgroep refinement:

-  de indicatie van dat de termijn verlopen is is bij streefdatum geel en bij fateledatum rood terwijl ze hetzelfde betekenen. Gelijk trekken?

- in de werklijst staat het aantal dagen tot verlopen maar er is geen instelling mogelijk dat je daar een signaleringsmail van kunt krijgen. Nieuwe userstory? En bij hoeveel dagen? instellen bij zaaktype?

-
