### ISSUE TITLE
Omschrijving van zaak tonen in werklijsten

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#779]
***Als*** werkverdeler

***Wil ik*** in de werklijsten de omschrijving van de zaak kunnen zien

***Zodat*** ik in één oogopslag zie waar de zaak over gaat

***

### Acceptance criteria:
-

***
### Prioriteit
- Must haves

***
### Gerealiseerd
Omschrijving is meegenomen als kolom in de werklijsten. Ook is er een zoekfunctie gerealiseerd om snel in de kolom omgevingen te zoeken

**Comment by RoyBuis** [comment]
Refinement 14-4:
Te realiseren:
- Kolom 'omschrijving' toevogen aan de 3 werklijsten voor zaken
- standaard 'aan' zetten
- gebruiker kan de kolom  verbergen

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
in de werklijsten de omschrijving van de zaak kunnen zien.
zoekfunctie gerealiseerd om snel in de kolom.

Getest:
Kolom aanwezig op Mijn Zaken / Zaken-werkvoorraad / Afgehandelde zaken (en ook te verbergen, standaard aan)
Zoeken: boven kolom tekst in te geven, en met Enter zoek je. Geen zoekknop??. Ook * is te gebruiken.
Werklijsten Taken-werkvoorraad + Mijn taken: hier zou de kolom omschrijving (van de zaak) ook wenselijk zijn. Nu in de e-Suite ook. Nieuwe user story maken?

**Comment by JosDimpact** [comment]
Besproken in de werkgroep:
- Zoekknop: Zou issue met wat lagere prio kunnen zijn.
- Kolom omschrijving vd zaak bij mijn taken: Is inderdaad wenselijk, vervolguserstory van maken door @Snijhuis.

**Comment by VictorTielenius** [comment]
Omschrijving van de zaak nu in werklijsten zaken en taken aanwezig
