### ISSUE TITLE
Automatisering creatie van ZAC abonnnement op Open Zaak

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#78]
Het zaakafhandelcomponent moet notificaties ontvangen van Open Zaak om zo de afhandeling van een zaak (CMMN / BPMN) te kunnen starten. Dit abonnement is in de development omgeving handmatig aangemaakt. Het aanmaken van het abonnement moet echter door het ZAC zelf gebeuren. Bijvoorbeeld door tijdens het starten te controleren of er een abonnement bestaat. Het zou ook mooi zijn wanneer het ZAC bij afsluiten het abonnement verwijderd.

Er moet rekening mee worden gehouden dat het ZAC ook op lokale laptops van developers draait. Moet er dan ook automatisch een abonnement worden aangemaakt?

**Comment by andyverberne** [comment]
Het abonnement kan niet automatisch aangemaakt worden omdat het niet mogelijk is om via de API het security token te specificeren welke meegestuurd kan worden met de Notificaties.
