### ISSUE TITLE
Verbeteringen documentgegevens pagina

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#784]
***Als*** zaakbehandelaar

***Wil ik*** een gebruiksvriendelijk overzicht  van de gegevens bij een document hebben

***Zodat*** ik een duidelijk overzicht van de relevante gegevens heb 

***

### Acceptance criteria:
-

***
### Prioriteit
- Must haves

***
### Gerealiseerd
- Versiebeheer toegevoegd 
- Iconen om type documenten te tonen.
- Wanneer er een preview beschikbaar is, wordt deze getoond. (Afbeeldingen, of PDF). 
- Gebruikers indicatie wordt als 'chips' getoond. Denk aan document vergrendelen 
- Linker menu wordt met document opties getoond. 
- in rechter grid worden de zaakgegevens verkort getoond

**Comment by RoyBuis** [comment]
Refinement 19-4:

Ontvangstdatum/verzenddatum: kan niet tegelijkertijd!
Bronorganisatie: wel of niet tonen?
Bestandsformaat: wel of niet tonen?
Gebruiksrechten:
Ondertekening: mag alleen bij status definitief

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
overzicht van de gegevens bij een document hebben:
Versiebeheer toegevoegd
Iconen om type documenten te tonen. (bij Details document, niet bij zaak)
preview beschikbaar is, wordt deze getoond. (Afbeeldingen, of PDF).
Ontvangstdatum/verzenddatum: kan niet tegelijkertijd! Velden alleen tonen als ze gevuld zijn. Datums groeperen en onderaan documentgegevensscherm tonen. OK
Creatiedatum / Registratiedatum / Verzenddatum (of Ontvangstdatum, veld niet aanwezig als beide leeg zijn) 
Vergrendeld: niet tonen in overzicht. Icoon toevoegen aan 'Document' kop. Alleen tonen als document vergrendeld is.: OK, bij zaak icoon V bij vergrendeld document, in detail document "Is vergrendeld". Erop zweven geeft ook naam wie vergrendeld heeft.
Beschrijving: toevoegen aan metadata overzicht, dit veld is in te vullen bij het aanmaken van een document: OK
Metadata nu niet te wijzigen: #369 is hiervoor mbt Recordmng.
