### ISSUE TITLE
BUG: Bedrijf als initiator wordt niet als nieuwe waarde ingevuld

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#788]
***Steps to reproduce:***

1. Maak een zaak aan
2. Vul bedrijf in als initiator
3. Ga naar historie

***Expected***
Er wordt een nieuwe waarde gezet in historie. Bij verwijderen worden er een oude waarde verwijderd

***Actual***
er wordt geen nieuwe waarde gevuld in de historie bij bedrijf. Bij persoon wordt het BSN gebruikt

**Comment by hansmarks** [comment]
https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/pull/801

**Comment by robertverboom** [comment]
test ok
