### ISSUE TITLE
taakhistorie Deel 2

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#789]
***Als*** Taakbehandelaar

***Wil ik*** de taakhistorie kunnen inzien

***Zodat*** de relevante wijzigingen van de taak kan terug vinden

***

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by robertverboom** [comment]
Deel 1: #564

**Comment by RoyBuis** [comment]
Refinement 19-4:

Te realiseren:

- opgehaalde gegevens (datum, wat, oud, nieuw) tonen in regels
- tabblad maken voor historie (a la zaak)

Daarna opnieuw refinen en verbeteringen bespreken.

**Comment by robertverboom** [comment]
test ok
