### ISSUE TITLE
Zoeken binnen ZAC op zaken, taken, documenten, productaanvragen (objecten), locatie, etc

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#792]
***Als*** Zaakbehandelaar

***Wil ik*** een zoekfunctionaliteit hebben om zaken, taken, documenten, productaanvragen (objecten), locaties / BAG objecten (i.r.t. zaken), etc. te kunnen zoeken

***Zodat*** ik snel en efficient de juiste/relevante items kan vinden om mijn werk te doen

***
NB. De specifieke user stories worden nog uitgewerkt. Deze Epic vast aangemaakt zodat de technische basis gelegd kan worden (zoekengine etc).

### Acceptance criteria:
- De getoonde resultaten van elke zoekactie worden bepaald door de rol/rechten van diegene die zoekt.

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Issues zijn gerealiseerd. Epic wordt gesloten.
