### ISSUE TITLE
9.3.4. Terugkoppeling via MijnOverheid - Persoonlijke gegevens

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#794]
(Zie ook 9.3.3.)
Als zaakbehandelaar

Wil ik informatie kunnen delen met personen via MijnOverheid - Persoonlijke gegevens

Zodat deze inzicht krijgen over welke informatie de gemeente over deze persoon heeft vastgelegd

Acceptance criteria:

• De functionaliteit voldoet aan de eisen m.b.t. het landelijke koppelvlak voor MijnOverheid
• De functionaliteit is van toepassing op personen als aanvrager

Prioriteit

Must haves

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Story wordt gerealiseerd via #2483
