### ISSUE TITLE
9.3.5. Terugkoppeling via MijnOverheid - Lopende zaken

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#795]
(Zie ook 9.3.3.)
Als zaakbehandelaar

Wil ik Statuswijzigingen in een proces kunnen doorzetten naar Mijn overheid - Lopende zaken

Zodat klanten de voortgang van het proces (zaakstatus) via Mijn overheid - Lopende zaken kunnen volgen.

Acceptance criteria:

• De functionaliteit voldoet aan de eisen m.b.t. het landelijke koppelvlak voor MijnOverheid
• De functionaliteit is van toepassing op personen als aanvrager

Prioriteit

Must haves

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story wordt gerealiseerd via https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/2483
