### ISSUE TITLE
Streefdatum bij een zaak niet verplicht

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#805]
***Als*** organisatie

***Wil ik*** dat de streefdatum van een zaak niet verplicht een waarde moet hebben 

***Zodat*** ik ook kan kiezen om een zaaktype in te richten waar niet met een streefdatum wordt gewerkt

***

In de Catalogi en Zaken API's is dit veld niet verplicht. Met oa het oog op het instellen van signaleringen willen we het ook mogelijk maken om zonder streefdatum te werken zodat hier dan ook niet verplicht een signalering op ingesteld hoeft te worden. Uit de e-Suite hebben we geleerd dat een organisatie in deze situatie vaak de streefdatum en fatale datum gelijk aan elkaar instelt waarmee aan het doel van deze functionaliteit voorbij wordt gegaan.

### Acceptance criteria:
-

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 28-4

Te realiseren, nieuwe werking
- Als een zaak een streefdatum heeft dan is deze dus verplicht. 
- Als een zaak geen streefdatum heeft dan mag deze geen streefdatum krijgen.
- Als een zaaktype geen streefdatum heeft ingesteld dan is er in het ZAC ook geen signalering in te stellen.
- In de werklijsten krijgen zaken die geen streefdatum hebben een streepje 
- In het zaakgegevensscherm wordt een streepje getoond

**Comment by hansmarks** [comment]
Validatie ook aangepast.
- Was streef mag niet voor start en fatale mag niet voor streef.
- Als de streefdatum leeg is wordt er nu gevalideerd op fatale mag niet voor start.

**Comment by RoyBuis** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
test ok
