### ISSUE TITLE
BUG: Historie veld Toelichting wordt niet gevuld bij het vrijgeven van een behandelaar bij een zaak

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#806]
***Steps to reproduce:***

1. Open een bestaande zaak
2. Ga naar veld behandelaar en vul een reden in
3. Geef de behandelaar vrij
4. Open de tab historie bij de zaak

***Expected***
Verwachting is dat de Toelichting gevuld wordt met de reden 

***Actual***
Toelichting wordt niet gevuld

**Comment by robertverboom** [comment]
test ok
