### ISSUE TITLE
BUG: Consistentie datum formaat Historie records

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#807]
***Steps to reproduce:***

1. Open een zaak
2. Wijzig de fatale datum van de zaak
2. Open de tab historie

***Expected***
Velden datum, oude waarde en nieuwe waarde worden qua datum formaat op dezelfde wijze getoond

***Actual***
Inconsistent datum formaat: dd-mm-yyyy versus yyyy-mm-dd

**Comment by robertverboom** [comment]
test ok
