### ISSUE TITLE
10A.X Vastleggen metadata t.b.v. zaakarchivering incl documenten en procesdata 

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#808]
***Als*** Zaakbehandelaar/ informatiebeheerder

***Wil ik*** Zaken van de juiste metadata voorzien  (MDTO en Archiefwet) zoals status, resultaat, selectielijst, einddatum, procestermijn, etc

***Zodat*** Zaken op een correcte manier bewaard/ gearchiveerd / overgebracht / vernietigd kunnen worden met de daarvoor bestemde achiveringstool/oplossing/component

NB. User stories worden uitgewerkt per persona en gekoppeld aan dit issue

### Acceptance criteria:
-

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
Relevante informatie over de werking van een zaak afhandelen en archivering:

- Schema/data model ZGW API's: https://vng-realisatie.github.io/gemma-zaken/standaard/ZGW%20API's.png
- Startpagina ZGW API's: https://vng-realisatie.github.io/gemma-zaken/standaard/index
 Zie de pagina van de Catalogi API over het valideren van resultaattypen!
Zie de pagina van de Zaken API over het afsluiten van een zaak en het afleiden van archiveringsparameters!
- Archiveringsproces samengevat: https://vng-realisatie.github.io/gemma-zaken/themas/achtergronddocumentatie/archiveren
- Schematische weergave van de levenscyclus van een zaak: https://user-images.githubusercontent.com/37660390/52470550-babfe780-2b8e-11e9-916f-beefc9632561.png

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Issues zijn gerealiseerd. Epic wordt gesloten.
