### ISSUE TITLE
Zaak afhandelen

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#809]
***Als*** zaakbehandelaar

***Wil ik***  bij het afhandelen van een zaak het juiste resultaat vastleggen

***Zodat*** de zaak met de juiste uitkomst wordt beëindigd

***

### Acceptance criteria:
- 

***
### Prioriteit
- Must haves
***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een zaak die helemaal gereed is kan worden afgehandeld met de actie [Zaak afhandelen], deze is dan ook alleen beschikbaar als alle taken zijn afgerond.
Bij het afhandelen van de zaak wordt het resultaat vastgelegd. Dit resultaat bepaalt vervolgens op welke wijze de zaak gearchiveerd wordt en hoe bijvoorbeeld de archiefactiedatum wordt berekend. Het kan voorkomen dat bij een bepaald resultaat een besluit moet worden vastgelegd, dit wordt in die situatie door de ZAC afgedwongen.
 
***Belangrijkste functionaliteiten:***
- Gebruiker kan met de actie [Zaak afhandelen] het resultaat vastleggen en een zaak beëindigen
- Gebruiker kan, als het resultaattype dit verplicht, via de actie [Zaak afhandelen] het besluit bij de zaak vastleggen. Dit kan echter ook direct via de actie [Besluit vastleggen].
- Het afhandelen van een zaak wordt als wijziging van de status en resultaat in de historie van de zaak vastgelegd

**Comment by RoyBuis** [comment]
Refinement 21-4:

Wat gebeurt er in deze story in hoofdlijnen:
1 Gebruiker kiest de actie 'zaak afhandelen' in ZAC

2 ZAC haalt de resultaattypen op die bij het zaaktype zijn geconfigureerd

3 ZAC toont de resultaattypen in een keuzeveld

4 Gebruiker selecteert een resultaat in het keuzeveld

5 ZAC haalt het resultaattype (GET Een specifieke RESULTAATTYPE opvragen)

6 Zaak wordt afgesloten: Resultaat wordt aan zaak toegevoegd
Status wordt aan zaak toegevoegd (deze functionaliteit is er al)
Einddatum wordt gevuld (deze functionaliteit is er al)

7 ZAC kan nu de selectielijst klasse voor de zaak bepalen, opzoeken met resultaattype

8 ZAC kan nu de archiefnominatie voor de zaak bepalen, overnemen uit resultaattype

9 ZAC kan nu uit ResultaatType.BrondatumArchiefprocedure de afleidingswijze halen

10 ZAC kan met de afleidingswijze de brondatum van de zaak bepalen, in het geval van 'Afgehandeld' is dat de einddatum zaak

UI:

Actie in linker menu
Naam actie: zaak afhandelen

Functioneel:
Gebruiker kiest 'zaak afhandelen'
Gebruiker kiest het juiste resultaat voor de zaak
Gebruiker klikt op Opslaan

Zaak na afhandelen:
Einddatum is gevuld
Resultaat is gevuld
Archiefactiedatum tonen? Gaan we deze term ook voor de ZAC-gebruiker gebruiken?
Archiefnominatie tonen?

**Comment by HilbrandHurtak** [comment]
Test
1 Gebruiker kiest de actie 'zaak afhandelen' in ZAC: **Akkoord**

2 ZAC haalt de resultaattypen op die bij het zaaktype zijn geconfigureerd. I**k zie bij dit zaaktype 4 opties. Ik kan niet controleren of dit de juiste zijn omdat de configuratie in Open Zaak staat. Ik ga er vanuit dat dit zo is: Akkoord**

3 ZAC toont de resultaattypen in een keuzeveld: **Akkoord**

4 Gebruiker selecteert een resultaat in het keuzeveld: **Akkoord. Optioneel is een Toelichting en het verzenden van een mail**

5 ZAC haalt het resultaattype (GET Een specifieke RESULTAATTYPE opvragen). **Kan ik niet controleren in de log omdat deze voorziening nog niet beschikbaar is**

6 Zaak wordt afgesloten: Resultaat wordt aan zaak toegevoegd: **Akkoord**
Status wordt aan zaak toegevoegd (deze functionaliteit is er al): **Status is op Afgerond gezet. Akkoord**
Einddatum wordt gevuld (deze functionaliteit is er al). **Einddatum van de zaak is gevuld: Akkoord**

7 ZAC kan nu de selectielijst klasse voor de zaak bepalen, opzoeken met resultaattype

8 ZAC kan nu de archiefnominatie voor de zaak bepalen, overnemen uit resultaattype. **Kan ik niet controleren. Ik zie er een vernietigingdatum is gevuld maar weet dus niet de termijn volgens de selectielijst: **

9 ZAC kan nu uit ResultaatType.BrondatumArchiefprocedure de afleidingswijze halen: **Is niet te testen/controleren.** 

10 ZAC kan met de afleidingswijze de brondatum van de zaak bepalen, in het geval van 'Afgehandeld' is dat de einddatum zaak: **Ik zie dat de vernietigingdatum is gezet=12 maanden na einde zaak**

Getest met de volgende resultaattypes:
Ingetrokken - 12 maanden
Afgebroken - 12 maanden
Verleend - 12 maanden
Geweigerd - 60 maanden



UI:

Actie in linker menu
Naam actie: zaak afhandelen

Functioneel:
Gebruiker kiest 'zaak afhandelen'
Gebruiker kiest het juiste resultaat voor de zaak
Gebruiker klikt op Opslaan

Zaak na afhandelen:
Einddatum is gevuld
Resultaat is gevuld
Archiefactiedatum tonen? Gaan we deze term ook voor de ZAC-gebruiker gebruiken?
Archiefnominatie tonen?
