### ISSUE TITLE
Zoeken op Zaken

### ISSUE THREAD

**Issue by bartlukens-atos** [NL-AMS-LOCGOV/zaakafhandelcomponent#812]
***Als*** Zaakbehandelaar 

***Wil ik*** in het ZAC zaken kunnen zoeken op basis van vrije tekst, welke staat in de omschrijving en toelichting van de zaak

***Zodat*** de zaakbehandelaar op een efficiënte manier de zaak kan vinden

***

### Acceptance criteria:
- Zoekfunctie moet globaal beschikbaar zijn 
- Relevante zoekresultaten verschijnen bovenin de lijst
- De zaak kan geopend worden vanuit de zoekresultaten
- De volgende velden moeten getoond worden:
1. Zaaknummer
2. Zaaktype
3. Status
4. Omschrijving
5. Toelichting
6. Locatie (adres)
zaak openen button

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by bartlukens-atos** [comment]
- [ ] Nieuw quarkus component + github repository
- [ ] Opvangen van notificaties en indexeren naar SOLR
- [ ] Zoeken api maken (Zoek methode + zoekparameters + zoekresulaat)
- [ ] Annotaties voor Open API toevoegen
- [ ] Open API spec genereren voor het zoekcomponent en implementeren in het ZAC
- [ ]

**Comment by andyverberne** [comment]
https://solr.apache.org/guide/8_1/using-solrj.html
