### ISSUE TITLE
ACCEPTATIE BUG: Het * geeft foute zoekreslutaten

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#813]
**Gebruikersrol:** Behandelaar
**Device:** Laptop
**OS:** Windows
**Browser:** Chrome
**Versie:** 100.0.4896.127

**Issuenummer**
_Welk issue was je aan het testen? Met een # voor het nummer wordt het een link_
#432

**Beschrijf de bug**
_Een duidelijke en beknopte beschrijving van wat de bug is_
Zoeken op 3 letters met een wildcard geeft een foutmelding

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1.  Maak een zaak aan
2. Voeg bedrijf als initiator toe
3. Vul bij tekstveld Handelsnaam: Tes* 
4. Druk op Zoek

**Verwacht gedrag**
_Een duidelijke en beknopte beschrijving van wat je verwachtte dat er zou gebeuren_
Bedrijven die Tes in hun handelsnaam hebben. 

**Daadwerkelijk gedrag**
_Een duidelijke en beknope beschrijving van wat er daadwerkelijk gebeurde_
Volgende melding wordt getoond: Unknown error, status code 400

**Screenshots**
_Er is tenmiste 1 screenshot als bijlage toegevoegd_
![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/69265f05-9e69-41bc-9838-6d6d6a943ecb)

**Foutmelding/Log tekst**
_Wordt er een foutmelding getoond, of kan je bij de logtekst toevoegen_
Niet bekend

**Aanvullende informatie**
_Indien nodig voeg hier aanvullende informatie over het probleem._

**Comment by RoyBuis** [comment]
### Refinement 20-6

Er kan bij zoeken in de KVK API geen gebruik gemaakt worden van het '*' teken. We gaan ervoor zorgen dat het ZAC geen foutmelding meer teruggeeft wanneer dit wel wordt gebruikt om te zoeken.

**Te realiseren**

- Niet mogelijk maken om * te gebruiken bij zoeken op handelsnaam
- idem voor haakjes ()

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Testen met 3 letters en een * geeft geen foutmelding meer maar ook geen resultaat. Er kan niet gezocht worden op een deel van de naam. Voorbeeld is
Test BV Donald Nevenvestiging
Zoek op Neven geeft geen zoekresultaat
Zoek op Nevenvestiging wel

Issue met * is verholpen maar zoeken op delen van woorden werkt niet. Ik zal een nieuwe user story aanmaken en deze goedkeuren
