### ISSUE TITLE
ACCEPTATIE BUG: Vestigingsadres is niet compleet 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#814]
**Gebruikersrol:** Behandelaar
**Device:** Laptop
**OS:** Windows
**Browser:** Chrome
**Versie:** 100.0.4896.127

**Issuenummer**
_Welk issue was je aan het testen? Met een # voor het nummer wordt het een link_
#432

**Beschrijf de bug**
_Een duidelijke en beknopte beschrijving van wat de bug is_
Postcode ontbreek bij vestigingsadres
Land ontbreekt bij vestigingsadres

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
1.  Maak een zaak aan
2. Voeg een bedrijf toe als initiator

**Verwacht gedrag**
_Een duidelijke en beknopte beschrijving van wat je verwachtte dat er zou gebeuren_
Bij Vestigingsadres wordt het volledige adres getoond dus ook; land en de postcode

**Daadwerkelijk gedrag**
_Een duidelijke en beknope beschrijving van wat er daadwerkelijk gebeurde_
Alleen straat en plaats worden getoond

**Screenshots**
_Er is tenmiste 1 screenshot als bijlage toegevoegd_
![image.png](https://images.zenhubusercontent.com/61a4c47ab0eb9f1d97385a8a/31a33dc4-cb45-4c9c-b01b-d69c6a3bf9d7)

**Foutmelding/Log tekst**
_Wordt er een foutmelding getoond, of kan je bij de logtekst toevoegen_
Geen foutmelding

**Aanvullende informatie**
_Indien nodig voeg hier aanvullende informatie over het probleem._

**Comment by robertverboom** [comment]
Wij maken gebruik van de KVK api. Op de accept omgeving staat de mock van een kvk test api. 

[FactSheet KVK handelsregister](https://app.zenhub.com/files/416646145/cb1b6f46-04de-4c01-a049-91d6ab27646c/download)

**Comment by robertverboom** [comment]
Als land en postcode er wel in staat, wordt dit ook getoond in de ZAC

**Comment by JosDimpact** [comment]
Dit willen we hertesten zodra de meer productie-like API gekoppeld is.

**Comment by robertverboom** [comment]
Refinement; 
- Uitbreiden met postcode en land

**Comment by RoyBuis** [comment]
### Refinement 31-1
Lijkt niet mogelijk om in de API aan te geven welke gegevens op te halen. Uitzoeken of dit wel mogelijk is.

**Comment by jeroen-dekker** [comment]
### Onderzoeksresultaten 2023-02-06

- Het blijkt dat het zoeken naar een huisnummer/postcode niet mogelijk is met de Zoeken-API van de KVK.
- De huisnummers/postcodes van adressen kunnen wel gevalideerd worden via de Zoeken-API.
- Via beide de Bedrijfsprofielen API en de Vestigingsprofielen API kan op basis van bekende basisgegevens (vestigingsnummer, kvk-nummer) wel een huisnummer/postcode opgehaald worden.

De nodige code-wijzigingen om via de Vestigingsprofielen API het exacte adres op te halen in de use-case zoals beschreven door Robert in de issuebeschrijving staan in PR https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/pull/2234.

**Comment by RoyBuis** [comment]
### Refinement 21-2

Zie https://developers.kvk.nl/nl/apis/basisprofiel

Mogelijke oplossing: 
- Gegevens bedrijf bij een zaak worden getoond met de gegevens die door de Zoeken API zijn opgehaald. 
- Gebruiker kan met druk op knop zoeken naar de volledige gegevens die door de Basisprofiel en Vestigingsprofiel  API's worden opgehaald

- Uitzoeken of voor beiden aparte API-keys zijn
- API-key voor Basisprofiel en Vestigingsprofiel moeten door gemeente geregeld worden
- API-keys zijn in omgevingsvariabelen ingesteld, als API-key niet is ingesteld dan knop niet tonen

**Comment by PaskalKiers** [comment]
@Snijhuis Eén van onze architecten was bezig met een inventarisatie rondom gebruik van het NHR. Eén aspect daarbij was kosten.  Volgens hem hoeven gemeentes niet te betalen, omdat er sprake is van een zogenaamde input financiering. Ik weet niet of dat nog wat veranderd voor de keuzes, maar hierbij de aanvullende informatie:

- [Inputfinanciering (kvk.nl)](https://www.kvk.nl/informatiebank/inputfinanciering/)
- [Productlijst inputfinanciering (kvk.nl)](https://www.kvk.nl/download/kvk_productlijst_inputfinanciering_tcm109-503428.pdf) zie pagina 2

Dit raakt de volgende api's:
- https://developers.kvk.nl/nl/documentation/zoeken-api
- [API Basisprofiel - KVK Developer Portal](https://developers.kvk.nl/nl/apis/basisprofiel)
- [API Vestigingsprofiel - KVK Developer Portal](https://developers.kvk.nl/nl/apis/vestigingsprofiel)
- [API Naamgeving - KVK Developer Portal](https://developers.kvk.nl/nl/apis/naamgeving)

**Comment by RoyBuis** [comment]
### Refinement 7-3

- Oplossing zal waarschijnlijk werken, besloten om deze te maken, voor beschrijving zie refinement 21-2. 
- Extra spec voor oplossing: als de extra gegevens van bedrijf worden opgehaald dan zijn deze zichtbaar in zowel het initiator blok als op de bedrijfsgegevenspagina
- API-key is optioneel
- Voor testen zie, https://developers.kvk.nl/nl/documentation/testing

**Comment by robertverboom** [comment]
**Gerealiseerd** met knop: Volledig profiel ophalen op bedrijfsgegevenspagina en in initiatorblok (let op; er wordt testdata gebruikt)

**Comment by HilbrandHurtak** [comment]
Knop getest. Er worden extra gegevens getoond. Kan niet beoordelen of alle beschikbare informatie wordt getoond. In ieder geval zie ik nu adressen met huisnummer en postcode 

Het veld land zie ik bijvoorbeeld niet (ook niet als ik dit via kvk online ga opvragen) 

Knop is zichtbaar in zoekpanel en bij initiator
Voor nu technisch gerealiseerd. Extra gegevens kunnen worden opgehaald. Zodra er straks een omgeving is waarbij de echte KVK gegevens kunnen worden opgevraagd moeten we de volledigheid van de gegevens beoordelen,

**Comment by HilbrandHurtak** [comment]
Test ok
