### ISSUE TITLE
Oplossing vinden voor paginering van open zaken

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#82]
Het is momenteel niet, out of the box, mogelijk om met bestaande functionaliteit te zoeken op openstaande zaken. Dit word nu opgelost met een filter op zaken die al zijn opgehaald. Maar dan ontbreekt de paginering ervoor omdat je de originele data dus aanpast..

**Comment by RoyBuis** [comment]
Het kunnen filteren op openstaand/afgelosten van opgehaalde zaken is nog niet mogelijk.

Er staat issue open in Github voor Zaken API versie 1.3 maar duurt waarschijnlijk nog een tijd voordat deze beschikbaar is. Zie https://github.com/VNG-Realisatie/gemma-zaken/issues/1659

Nieuw issue aanmaken om het vanuit API op te lossen, in Icebox plaatsen met label 'Impediment'

Andy past oplossing voor nu toe

**Comment by andyverberne** [comment]
Oplossing bleek een exceptie te veroorzaken. Dat is inmiddels gefixed

**Comment by andyverberne** [comment]
Het volgende gaat nog fout:
* zaken-werkvooraad -> zaaktype -> "MOR anoniem - met kleine evenement proces" (bovenste)
* Dit geeft 159 resultaten
* zet paginering op 25 en ga steeds naar de volgende pagina.
* Na de pagina 76 - 100 volgt een lege pagina terwijl de verwachting is dat er een pagina met zaken getoond wordt

**Comment by andyverberne** [comment]
Bovengenoemd probleem bleek veroorzaakt te worden door invalide data (zaken met twee keer een groep in behandelaar rol). Ik heb deze zaken verwijderd.

**Comment by robertverboom** [comment]
issue speelt nog steeds. Niet alleen bij MOR, maar ook bij mke. 
In de paginering geeft hij aan dat er bijv 124 zaken aanwezig zijn. daadwerkelijk worden er 101 geteld. Bij MKE worden er ook minder getoond dan de paginering aangeeft.

**Comment by robertverboom** [comment]
test ok
