### ISSUE TITLE
7.2.1 Documentinhoud d.m.v. preview bekijken door gebruiker DEEL 2

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#831]
functionaliteit van PDF is gerealiseerd. Voor afbeeldingen moet er nog een preview functie voor komen 

#349

**Comment by RoyBuis** [comment]
### Refinement 28-4

- Typen afbeeldingbestanden in kaart brengen
- Te grote plaatjes naar beneden schalen
- Te kleine plaatjes tonen zoals ze zijn

**Comment by robertverboom** [comment]
test ok

**Comment by robertverboom** [comment]
test ok
