### ISSUE TITLE
BUG: Optie - kies een groep/zaaktype - geeft geen resultaten in de werklijst Zaken-werkvoorraad

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#840]
***Steps to reproduce:***

1.  Ga naar de werkvoorraad
2.  kies een groep of zaaktype
3.  kies vervolgens - kies een groep/zaaktype-

***Expected***
Alle zaken worden geladen

***Actual***
wordt gemeld dat er geen gegevens gevonden zijn

**Comment by RoyBuis** [comment]
Oplossing:

- De optie 'kies een groep' eruit halen en een placeholder neerzetten.
- Zowel bij groep als zaaktype toepassen
- Zowel bij werkvoorraad als afgehandelde zaken lijsten

**Comment by robertverboom** [comment]
test ok
