### ISSUE TITLE
BUG: Afgesloten taken geven een 500 foutmelding

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#847]
***Steps to reproduce:***

1. Maak een zaak aan
2. Maak een taak aan
3. Rond de taak af
4. ga terug naar de zaak

***Expected***
Gaat terug naar de zaak

***Actual***
krijgt een foutmelding: No enum constant net.atos.zac.app.planitems.model.UserEventListenerActie.sid-84903A63-A8BA-4E7D-9DCD-D955D343059F

Stacktrace: 
[https://app.zenhub.com/files/416646145/2a627de9-2cc1-4d6a-a93f-0482002b5e19/download](https://app.zenhub.com/files/416646145/2a627de9-2cc1-4d6a-a93f-0482002b5e19/download)

**Comment by andyverberne** [comment]
Ik kan deze niet meer reproduceren op develop
