### ISSUE TITLE
Externe signalering voor streef- en fatale datum zaak

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#848]
***Als*** zaakbehandelaar

***Wil ik*** gesignaleerd worden als een zaak op mijn naam de streefdatum of daarna de fatale datum bereikt

***Zodat*** ik weet dat ik in actie moet komen

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Een behandelaar van een zaak kan zich buiten het ZAC om laten per e-mail laten signaleren over het naderen van de streefdatum en fatale datum van de zaak. De signaleringen worden verstuurd wanneer de, volgens de waarschuwingsvensters berekende, signaleringsdag is bereikt. De waarschuwingsvensters zijn onderdeel van de ZAC zaakafhandelparameters.

***Belangrijkste functionaliteiten:***
- De signalering wordt per e-mail verstuurd naar het e-mailadres dat bij de gebruiker, in bijvoorbeeld Keycloak, is ingesteld.
- Er wordt voor de streefdatum en fatale datum eenmaal een signalering verstuurd
- De gebruiker kan het versturen van de e-mail in- en uitschakelen door in het profielmenu de zaaksignalering 'Mijn zaak nadert de streef- of fatale datum' aan te passen.

**Comment by RoyBuis** [comment]
### Refinement 25-4

**Te realiseren**
- Een externe signalering wordt per e-mail verstuurd
- Versturen op de dag dat het ingestelde 'aantal kalenderdagen van te voren' is bereikt
- Gebruiker kan de signalering aan en uit zetten, zowel voor streef- als fatale datum

**Technisch**
Zie technische opmerkingen in gekoppelde story #778

**Comment by marcoatos** [comment]
Planning 02-06
Te realiseren
- Technische fake regel bij de signalering instellingen toevoegen voor fatale en streefdatum naderend
- Dashboard card erbij
- Toevoegen aan signalerings type tabel

**Comment by GertrudeKampherbeek** [comment]
zie ook commentaar in #778. In de inrichting staat aantal signaleringsdagen in het waarschuwingsventer maar er is geen optie om dat ook via mail te laten doen. Nieuwe userstory? Er is in ieder geval geen visueel verloop op de indicatieicoon van de ingestelde 15 dagen van te voren.
