### ISSUE TITLE
Raadplegen eerdere versies van een document

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#849]
***Als*** zaakbehandelaar

***Wil ik*** een eerdere versie van een document kunnen raadplegen

***Zodat*** ik inzicht heb in de wijzigingen die bij een document zijn aangebracht
***

### Acceptance criteria:
-

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Bij een document dat meerdere versies heeft kan vanuit de documentgegevenspagina eenvoudig naar een voorgaande of volgende versie worden genavigeerd. Bij het openen van een andere versie worden de metadata en indicaties die voor de geopende versie gelden weergegeven. Bij het downloaden van het bestand kan het bestand van de specifieke versie geraadpleegt worden.
***Belangrijkste functionaliteiten:***
- Gebruiker kan in de documentgegevenspagina van een document naar een eerdere (kleiner dan icoon) of latere versie (groter dan icoon) gaan
- Gebruiker kan het bijbehorende bestand van een versie raadplegen door de [Downloaden] knop te gebruiken

**Comment by RoyBuis** [comment]
### Refinement 2-5

**Te realiseren**
- Gebruiker kan met blader knop bij 'Versie' veld door eerdere versie bladeren
- ZAC toont de metadata van de gekozen versie, via de Download actie kan het bestand geopend worden
- Bij de kop Documenten' de datum van de eerdere versie tonen en duidelijke indicatie dat de gebruiker niet in de huidige versie zit

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Getest en Akkoord bevonden
