### ISSUE TITLE
Streefdatum bij een taak niet verplicht

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#853]
***Als*** organisatie

***Wil ik*** taken kunnen gebruiken zonder dat daar een streefdatum voor geldt

***Zodat*** ik voor een proces waarbij streeftermijnen voor taken niet van belang zijn de taken zonder streeftermijn kan gebruiken

***

### Acceptance criteria:
- een beheerder kan per taak per zaaktype de streeftermijn invullen
- de streeftermijn kan de waarde '0' hebben
- de streeftermijn kan leeg gelaten worden

***
### Prioriteit
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by robertverboom** [comment]
test ok
