### ISSUE TITLE
Hierarchische opbouw van labels in nl.json en en.json verbeteren

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#87]
Er lijkt geen duidelijke structuur te zitten in de hierachische opbouw van de labels in nl.json en en.json. Hierdoor is het lastig iets terug te vinfen of te kijken of een label al bestaat.

**Comment by andyverberne** [comment]
Dit is reeds gerealiseerd.
