### ISSUE TITLE
BUG: Taken werklijsten op de zandbak worden niet meer geladen 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#877]
***Steps to reproduce:***

1. ga naar https://zac.zandbak-public-service-platform.net/taken/werkvoorraad

***Expected***
De werkvoorraad wordt geladen 

***Actual***
Krijgt een 500 foutmelding met: 
No variable found with name 'zaaktypeUUID' for open case instance id 'f96697c3-106e-11ec-90e2-6e9c12b63e2b'

[https://app.zenhub.com/files/416646145/6023713b-53ea-437d-8c90-2e3846e25972/download](https://app.zenhub.com/files/416646145/6023713b-53ea-437d-8c90-2e3846e25972/download)

**Comment by andyverberne** [comment]
Op de zandbak omgeving zijn de zaken van vorig jaar verwijderd. Code is verder niet aangepast.

**Comment by robertverboom** [comment]
test ok
