### ISSUE TITLE
Rechtenchecks via Solr entiteiten regelen

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#88]
Om rechten te bepalen voor een medewerker zijn er vaak behandelaren/groepen nodig. Onderdelen die in de open-zaak zaak als URI worden weergegeven, hiervoor moeten we dus steeds uitstapjes maken.

De rechten utils moeten dus gebruik gaan maken van de solr entiteit waar deze gegevens al aanwezig zijn.

**Comment by andyverberne** [comment]
We gaan geen SOLR gebruiken binnen het zaakafhandelcomponent. In plaats daarvan hebben we caching gerealiseerd.
