### ISSUE TITLE
Tonen van indicaties

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#888]
Als Behandelaar

Wil ik indicaties op een zaak zien

Zodat ik snel kan zien dat er iets speciaals met de zaak aan de hand is. Denk aan verlengen, opschorten, gebruiksrechten.

**Comment by RoyBuis** [comment]
Te bespreken in refinement:

- waar komen indicaties te staan?
- andere handige toevoegingen voor de UI, denk aan inzoom op de gegevens waar de indicatie betrekking op heeft

**Comment by RoyBuis** [comment]
### Refinement 16-5

**Te realiseren**

- Chips toevoegen aan zaak regel, rechts uitgelijnd, in roze met een i-icoon
- de reden als title van de chip
- chips gelden voor opschorten en verlengen
- bij opschorten wordt de verwachte duur getoond linksonder in de datumgroep
- bij verlengen idem voor de totaal verlengde duur

**Comment by robertverboom** [comment]
Mouse-over van de chips halen. (De kleur verandering). i-icoon met mouse-over functie moet blijven. Nu lijkt het voor de gebruiker dat je iets met de indicatie kan doen.
