### ISSUE TITLE
Taken verdelen vanuit werkvoorraad

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#89]
User story: als medewerker wil ik taken kunnen toekennen aan medewerkers en groepen zodat ik de werkvoorraad kan beheersen

**Comment by robertverboom** [comment]
### Refinement
Taken kunnen selecteren, alleen op huidige pagina, bij navigeren naar volgende pagina is selectie kwijt

Toekennen aan groep of medewerker

**Comment by ronniekoopmans-atos** [comment]
review ok

**Comment by robertverboom** [comment]
test ok
