### ISSUE TITLE
Zaken als hoofd- en deelzaak koppelen

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#895]
***Als*** zaakbehandelaar

***Wil ik*** een hoofd-deelzaak relatie tussen zaken kunnen leggen

***Zodat*** ik bij een zaak inzicht heb in afhankelijkheid van andere zaken

***

### Acceptance criteria:
- een hoofdzaak mag beeindigd worden als alle deelzaken zijn beeindigd
- een hoofdzaak mag zelf geen deelzaak zijn

***
### Prioriteit
- Must haves

***
### Gerealiseerd
**Let op: een later gerealiseerde story heeft invloed op deze story gehad, zie #1235**
_Omschrijving van de op te leveren functionaliteit in deze story_
Het is mogelijk om tussen twee openstaande zaken een hoofd- en deelzaak relatie te leggen. De hoofdzaak mag pas worden afgehandeld als de deelzaak is afgehandeld. Bij het behandelen van een deelzaak in de ZAC is dezelfde functionaliteit als bij een reguliere zaak beschikbaar. Voor het koppelen van zaken wordt de klembord functionaliteit gebruikt.
Om een hoofd-deelzaakrelatie te leggen moet in het zaaktype van de hoofdzaak zijn ingesteld van welke zaaktypen een deelzaakrelatie gelegd mag worden. Als dit niet is ingesteld dan geeft de ZAC een foutmelding bij het koppelen van de zaken.

***Belangrijkste functionaliteiten:***
- Gebruiker kan met de actie [Zaak koppelen] een zaak op het klembord plaatsen
- Gebruiker kan in een openstaande zaak waarmee de koppeling gelegd moet worden vanuit het klembord te zaken aan elkaar koppelen en de soort relatie tussen de zaken bepalen
- Gebruiker kan de hoofdzaak afhandelen als de deelzaak is afgehandeld 
- Het koppelen van zaken als hoofd- en deelzaak wordt als wijziging van hoofdzaak in de historie van de DEELzaak vastgelegd

**Comment by RoyBuis** [comment]
### Refinement 9-5

**Te realiseren**

UI
- zaak als hoofd- of deelzaak koppelen gebeurt door de zaak op het clipboard te zetten
- linkermenu actie 'Zaak koppelen' opent het clipboard en zet de geopende zaak erop 
- clipboard kan meerdere zaken om te koppelen bevatten
- per keer kan 1 zaak vanaf het clipboard gekoppeld worden
- na het kiezen van een zaak in het clipboard kiest de gebruiker of de te koppelen zaak een hoofd of deelzaak is

- na het koppelen is de zaak zichtbaar in het tabblad 'Gekoppelde zaken' 
- per gekoppelde zaak bevat het tabblad een regel met het zaaknummer, zaaktype, status, startdatum en aard relatie van de zaak
- gekoppelde zaken zijn via het oog icoon te openen vanuit de regel

- als een zaak de hoofdzaak is wordt een indicatie 'heeft deelzaken' getoond
- als een zaak de deelzaak is wordt een indicatie 'is deelzaak' getoond

Technisch
- Controleren dat de relatie tweezijdig wordt gelegd
- Vanuit achterkant indicator meegeven of de zaak beeindigd kan worden (zaak.rechten.beeindigbaar)
- Logica dat de actie afhandelen of niet ontvankelijk actief zijn uit het CMMN model halen, deze logica moet dus bepaald worden in de backend

Buiten scope
- het ontkoppelen van hoofd- en deelzaak
- raadplegen van documenten van gekoppelde zaken

**Comment by HilbrandHurtak** [comment]
Zie ##2530 Zandbak Zaak 
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/dc45cdaa-d5f1-4426-a4c5-701eac898ecb)
**Test Hoofzaak sluiten als deelzaak nog openstaat. Genereer een nette foutmelding**
Hoofdzaak afgebroken via menu optie- Geeft direct foutmelding
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/aed5f046-0202-4c6e-ba4b-4e3c8df65ff2)

Hoofdzaak in behandeling genomen en proberen af te handelen. Optie wordt niet getoond bij de hoofdzaak
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/390e66ed-d9fb-4874-8f14-b322d94633b7)


Optie wordt wel bij de deelzaak getoond
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/4e247b15-d3d5-4893-9015-fc7f5fff1cde)

Na afhandelen deelzaak wordt ook de optie afhandelen bij de hoofdzaak getoond
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/3099c710-5953-42bb-8014-4ce9aad98ab7)

Conclusie
Afhandelen van een hoofdzaak met openstaande deelzaak is pas mogelijk als de deelzaak is afgehandeld- TEST OK
Optie **Afbreken** van een hoofdzaak met openstaande deelzaak geeft 500 foutmelding

@robertverboom kun je dit nog opnieuw laten bekijken?

**Comment by HilbrandHurtak** [comment]
Ik heb hem gelezen, in die hoek toevallig een ander ticket ook opgelost. Zal hem naspelen, maar denk inderdaad dat wij onze rules daarvoor moeten aanpassen. Bedankt voor het uitzoeken! 

Kind regards,
Robert Verboom

**Comment by HilbrandHurtak** [comment]
Kan niet verder met het testen. De zandbak geeft steeds meer 500 foutmeldingen bij wijziging van status (bijvoorbeeld bij in behandeling nemen of afbreken)

**Comment by KarinMasselink** [comment]
@HilbrandHurtak je kan deze hertesten met de issues die opgeleverd zijn.
