### ISSUE TITLE
BUG: Status van informatieobject zonder status wordt onjuist getoond

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#897]
***Steps to reproduce:***

1. Voeg een document toe aan een zaak via het zaakafhandeldocument.
2. Verwijder via de Open Zaak administratie tool de status van het document.
3. Ga naar de document details in het zaakafhandeldocument

***Expected***
Document heeft geen status

***Actual***
![image.png](https://images.zenhubusercontent.com/61a5fb30660cec2442027526/4de82957-ac2d-4978-9e27-dee6a814ca97)

**Comment by robertverboom** [comment]
Nu geeft zowel de zaak als document een foutmelding. Wanneer je het document verwijderd bij openzaak en vervolgens in ZAC terug gaat naar de zaak : 
[StacktraceVerwijderenDocumentOpenzaak.txt](https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/files/8713943/StacktraceVerwijderenDocumentOpenzaak.txt)

**Comment by robertverboom** [comment]
wanneer status niet gevuld is, wordt deze niet getoond op het scherm. Test: Ok
wanneer je nieuwe versie wilt toevoegen wordt dit niet geladen, omdat hij waarschijnlijk verwacht dat de status altijd gevuld is. Test Nok
Document: https://zac.develop-public-service-platform.net/informatie-objecten/8cb1f5e5-27e2-4118-9cf7-ce9851ac755a/2

**Comment by robertverboom** [comment]
![image](https://user-images.githubusercontent.com/94612050/169260440-3d4809ca-7e0d-4b79-9699-237a9f9ba8db.png)
Vertaling gaat nog niet soepel
