### ISSUE TITLE
BUG: Limit van 1000 op Toelichting op Takenscherm

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#901]
***Steps to reproduce:***

1. Ga na een taak 
2. Vul een toelichting met meer dan 1000 karakters in 
3. 

***Expected***
zit een max op 1000 karakters 

***Actual***
kan meer dan 1000 karakters invoeren en geeft een foutmelding

**Comment by edwinlambregts-atos** [comment]
Besproken met Robert. Alle inputvelden nagelopen en waar nodig een maxlength toegevoegd. Geldt ook voor velden waar dus voorheen nog geen maxlength voor bestond.
Bij normale tekst inputvelden kun je nu ook aangeven of je het aantal karakters wilt tonen. Dit is dus een kleine uitbreiding daarop.

Gerelateerde tickets #900 #899 #892
