### ISSUE TITLE
archiefactietermijn mag null zijn

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#903]
1 maak zaak aan
2 handel zaak af
3 zet niet akkoord als resultaat

**Comment by hansmarks** [comment]
Dus als de archieftermijn null is dan zal de actietermijn ook null zijn.

En in dat geval is er ook geen noodzaak om de brondatum (einddatum+procestermijn) te bepalen.
