### ISSUE TITLE
Open Formulieren Installatie en verkenning gebruik

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#92]

**Comment by andyverberne** [comment]
https://open-forms.readthedocs.io/en/latest/installation/index.html#installation-index

**Comment by andyverberne** [comment]
Het JSON schema voor een ProductAanvraag staat in de github repository van objecttypes:
https://github.com/open-objecten/objecttypes/blob/main/community-concepts/productaanvraag/productaanvraag-denhaag.json

**Comment by andyverberne** [comment]
Hoe Open Objects notificaties kan versturen:
https://objects-and-objecttypes-api.readthedocs.io/en/latest/admin/notifications.html
