### ISSUE TITLE
Alle Taakschermen: Upload bijlagen verplaatsen naar actiemenu links

### ISSUE THREAD

**Issue by Snijhuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#924]
***Als*** Zaakbehandelaar

***Wil ik*** Op een generieke wijze bijlagen kunnen toevoegen vanuit een taakscherm

***Zodat*** Ik op elk moment op elke taak op dezelfde wijze een document kan uploaden.

***

### Acceptance criteria:
- Werking bijlagen uploaden op taken gelijktrekken aan bijlagen uploaden op zaakniveau. (Actieknop links en sidepanel rechts)

NB. 
1, Door het document uploaden uit het taakscherm/formulier te halen moet het ook mogelijk zijn om taken tussentijds op te slaan door gebruikers. Graag naar kijken.
2. Vanuit de voortgangsbewaking worden de geuploade bestanden per afgesloten taak getoond.  Bovenstaande story kan dus invloed hebben op de gebouwde oplossing in https://app.zenhub.com/workspaces/dimpact-refinement-620a77ef5ed231001123e692/issues/nl-ams-locgov/zaakafhandelcomponent/481. In de voortgangsbewaking wordt namelijk de titel van het geuploade document getoond (zie screenshot)
3. Het tonen van de documenten die vanuit een taak worden gecreëerd in de voortgangsbewaking moet een aparte story worden

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by RoyBuis** [comment]
### Refinement 12-5

**Te realiseren**
- actie 'Document uploaden' toevoegen aan taakmenu (generieke functionaliteit)
- deze actie maakt gebruik van dezelfde functionaliteit als Document toevoegen bij de zaak
- titel(s) van geuploade documenten worden getoond bij de voortgangsbewaking info
- knop toevoegen om een taak tussentijds op te slaan

**Comment by RoyBuis** [comment]
test ok

**Comment by robertverboom** [comment]
test ok
