### ISSUE TITLE
Lokaal reversed tunnel te leggen naar een pod 

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#93]

**Comment by andyverberne** [comment]
Er zijn wel mogelijkheden. Zie:
* https://webapp.io/blog/container-tcp-tunnel/
* https://til.zqureshi.in/reverse-tunnelling-via-kubectl/
Maar tot op heden is het nog niet gelukt,

Andere mogelijke oplossingen voor de volgende problemen:
* Lokaal testen van code rondom notificaties: remote debuggen
* Caches worden lokaal niet bijgewerkt en websockets gaan niet af: Een decorator bouwen rondom ZRCClientService welke zelf de nodige events gooit. Zie http://www.devdoc.net/javaxe/JavaEE-7u2/docs/javaee-tutorial/doc/cdi-adv-examples005.htm
