### ISSUE TITLE
Verbetering laden Mijn zaken werklijst

### ISSUE THREAD

**Issue by RoyBuis** [NL-AMS-LOCGOV/zaakafhandelcomponent#939]
***Als*** werkverdeler

***Wil ik*** een acceptabele wachttijd hebben voor het kunnen inzien van Mijn zaken

***Zodat*** ik een gebruiksvriendelijke applicatie heb
***

### Acceptance criteria:
-

***
### Prioriteit
- Must haves

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Alle werklijsten worden gegenereerd op basis van indexering waarmee de snelheid van het openen van een overzicht wordt verbeterd. Indexering wordt iedere minuut geupdate waardoor het maximaal een minuut duurt voordat een gewijzigd item, zoals de aanpassing van een status of de toekenning aan een behandelaar, zichtbaar is in een werklijst.

**Comment by andyverberne** [comment]
Volgende caches verwijderen:

   String ZGW_ZAAK_BEHANDELAAR_MANAGED = "zgw-zaak-behandelaar-managed";

    // Deze cache is managed (alleen zaak URI als sleutel gebruiken!)
    String ZGW_ZAAK_GROEP_MANAGED = "zgw-zaak-groep-managed";

    // Deze cache is managed (alleen URI als sleutel gebruiken!)
    String ZRC_STATUS_MANAGED = "zrc-status-managed";

**Comment by marcoatos** [comment]
Planning 02-06
te realiseren
- Via Solr laten gaan ipv cache

**Comment by VictorTielenius** [comment]
Werklijst "Mijn zaken" opent snel
