### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#942]
# Gebruiken wildcards <BR/> 
 **Als**  Medewerker <br/>**wil ik** kunnen zoeken met   wildcards, <br/>**zodat ik** relevante informatie kan vinden, ook als   de spelling van mijn zoekopdracht niet helemaal bekend is<br/><br/>**Acceptatiecriteria**<br/><br/>**wildcards** <BR/><BR/>   **Opmerkingen** <BR/> <br/>**Verwijzingen:**<br/> [Dimpact   Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7)   <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
De zoekfunctie maakt gebruik van SOLR. Er kan in SOLR, naast de Boolean operators, van meerdere wildcards gebruik gemaakt worden:

**Wildcards**

- gebruik * voor aanvullingen (evenement* vindt evenementenmelding en evenementenvergunning)
- gebruik ? voor een enkel karakter (Ro? vindt Roy en Ron)

**Boolean operators**

- gebruik van AND toont resultaten waar meerdere trefwoorden in voorkomen
- gebruik van OR toont resultaten als één van de trefwoorden voorkomt
- gebruik van NOT laat resultaten weg als het trefwoord na deze operator in de zoekopdracht wordt gebruikt  

Voor een vollledig overzicht zie ook https://solr.apache.org/guide/8_7/the-standard-query-parser.html

**Comment by VictorTielenius** [comment]
Is het ook mogelijk om bij zoeken zonder gebruik te maken van wildcard (*) toch de resultaten te krijgen zoals wanneer je wel gebruik maakt van de wildcard (*)?
Zoals Google zoeken.

**Comment by RoyBuis** [comment]
### Refinement SN, KM & RB
Voorleggen aan wg R&A

**Comment by KarinMasselink** [comment]
Deze pak ik later op als beter bekend is wat we ermee gaan doen.
