### ISSUE TITLE
Zoeken niet exacte match 

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#943]
#Zoeken niet exacte match <br/>**Als** Medewerker <br/>**wil ik** geholpen worden bij het zoeken op namen die op verschillende manieren gespeld kunnen worden,<br/>**zodat** ik niet zelf alle opties hoef af te lopen.<br/><br/>**Acceptatiecriteria** <br/>vergelijkbaar met functionaliteit in sharepoint
oa voor namen met accenten  René <> Rene maar zou kunnen <BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
De zoekfunctie maakt gebruik van SOLR. Er kan in SOLR gebruik gemaakt worden van de zogenaamde fuzzy search. Ook de wildcards kunnen hier handig zijn

- gebruik ~ voor gelijksoortige woorden (bijvoorbeeld: Dimpact~ vindt Dimpekt

**Comment by HilbrandHurtak** [comment]
Gebruik van de wildcards en funny search werkt. In de handleiding zou hieraan wel aandacht kunnen worden besteed( niet iedereen kent de opties * of ~ 

Test OK
