### ISSUE TITLE
Zoeken gemachtigde open dossier

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#944]
#Zoeken gemachtigde open dossier<br/>**Als** Medewerker<br/>**wil ik** een lopend zaakdossier kunnen vinden op naam van de gemachtigde ,<br/>**zodat** ik binnengekomen post kan toevoegen. .<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
De gegevens van een persoon of bedrijf kunnen bekeken worden vanuit de persoons- of bedrijfsgegevenspagina. De pagina bevat een overzicht van alle zaken waar de persoon of bedrijf bij betrokken is die in de ZAC worden behandeld. In dit overzicht kan gefilterd worden op 'betrokkenheid' om zo inzicht te krijgen in hoe de persoon of bedrijf bij de zaak betrokken is.
Deze pagina is te benaderen door vanuit een zaak op het oog icoon van een initiator of betrokkene te klikken of door een persoon of bedrijf via de zoekfunctie te openen.
 
***Belangrijkste functionaliteiten:***
- Gebruiker kan de persoons- of bedrijfsgegevenspagina benaderen door de persoon of het bedrijf te zoeken via de zoekfunctie en deze vanuit de zoekresultaten te openen
- Gebruiker kan de wijze waarop een persoon of bedrijf bij een zaak betrokken is zien door in het zaken overzicht van de persoons- of bedrijfsgegevenspagina te filteren op 'betrokkenheid'

**Comment by RoyBuis** [comment]
### Refinement
Deze story graag verder uitwerken. Welke persona betreft het en waar wordt de gemachtigde gezocht?

**Comment by Snijhuis** [comment]
**WG Refinement**
Je moet kunnen filteren of specifiek kunnen zoeken op een type betrokkene. Oplossing #946 afwachten

**Comment by HilbrandHurtak** [comment]
946 Getest. Alleen de zaken waar de persoon de initiator is worden getoond. Daar waar hij als alleen als betrokkene is gekoppeld dus niet.

**Comment by RoyBuis** [comment]
### Refinement RV en RB

- Betrokkenen moeten geindexeerd worden in Solr
- Zoekscherm uitbreiden met facet voor roltypen als gezocht wordt op bsn, vestigingsnummer of RSIN

**Comment by RoyBuis** [comment]
### Refinement 12-1

**Te realiseren**

- Een betrokkene zoeken gaat via zoeken op persoon/bedrijf waarna je naar de persoons/bedrijfspagina gaat
- In persoons/bedrijfspagina mogelijkheid maken om op roltype te filteren
- Alleen roltypen waar die persoon/bedrijf voorkomt in een zaak als filteroptie tonen. (Uitzoeken of dit met geneste documenten in Solr kan!)

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
@robertverboom Volgens mij is deze functionaliteit (Zoekscherm uitbreiden met facet voor roltypen) in de afgelopen sprint getoond. Op de zandbak kan ik het nog niet zien. Kan dat kloppen?

**Comment by RoyBuis** [comment]
@HilbrandHurtak Deze is nog niet zichtbaar in de zandbak inderdaad, we hebben de laatste versie nog niet uitgerold. Excuus voor de vertraging, dit plannen we voor as. maandag in.

**Comment by HilbrandHurtak** [comment]
Getest e(met bedrijven)
Een betrokkene zoeken gaat via zoeken op persoon/bedrijf waarna je naar de persoons/bedrijfspagina gaat. AKKOORD
In persoons/bedrijfspagina mogelijkheid maken om op roltype te filteren: AKKOORD

Alleen roltypen waar die persoon/bedrijf voorkomt in een zaak als filteroptie tonen. (Uitzoeken of dit met geneste documenten in Solr kan!) 

Zoeken met facet: Test AKKOORD
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/1a46c967-4efc-426c-88f7-d7e2cb7f2537)

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/cbd64734-3b72-4d70-8d3c-6d191e007370)
