### ISSUE TITLE
Zoeken gemachtigde gesloten dossier

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#945]
#Zoeken gemachtigde gesloten dossier<br/>**Als** Medewerker informatiebeheer<br/>**wil ik** een gesloten zaakdossier kunnen vinden op naam van de gemachtigde,<br/>**zodat** ik binnengekomen post kan toevoegen. .<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement
Deze story graag verder uitwerken. Welke persona betreft het en waar wordt de gemachtigde gezocht?

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd door te kunnen zoeken op betrokkenen en vervolgens naar de pagina van de betrokken persoon of bedrijf te gaan en dara de afgesloten zaken te bekijken
