### ISSUE TITLE
Zoeken aanvrager open dossier

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#946]
#Zoeken aanvrager open dossier<br/>**Als** Medewerker informatiebeheer<br/>**wil ik** een lopend zaakdossier kunnen vinden op naam van de aanvrager,<br/>**zodat** ik binnengekomen post kan toevoegen. .<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by robertverboom** [comment]
### Refinement 13-10:
- In zoekpanel komen 3 tabjes: Zoeken op zaak, zoeken op persoon, zoeken op bedrijf
- Zoeken op persoon/bedrijf geeft het zoekvenster van het personen/bedrijven zoekpanel
- Als er gezocht wordt op een persoon/bedrijf, wordt de persoon/bedrijf middels een icoontje (per gevonden persoon: vergrootglaasje) overgenomen als trefwoord en worden de zaken van deze persoon getoond
- Zijn al twee varianten en er komt een derde variant

**Comment by RoyBuis** [comment]
### Refinement 25-10

Nav issue #1045 kleine aanpassing in deze story die gelijk wordt meegenomen:

Oorspronkelijke uitwerking:
Als er gezocht wordt op een persoon/bedrijf, wordt de persoon/bedrijf middels een icoontje (per gevonden persoon: vergrootglaasje) overgenomen als trefwoord en worden de zaken van deze persoon getoond

Nieuwe uitwerking:
In plaats van dat het vergrootglas icoon een trefwoord opent wordt het een oog icoon die een klantpagina opent. Op die klantpagina is dan een overzicht van de zaken van die klant te zien en overzicht persoons- of bedrijfsgegevens.

**Comment by robertverboom** [comment]
test ok

**Comment by HilbrandHurtak** [comment]
Zoeken op zaken van 1 persoon gaf een overzicht met alle gevonden zaken. Via filtering op status kun je een verschil maken tussen de lopende en afgesloten zaken. Dit zou misschien nog wat eenvoudiger (einddatum gevuld) of een schuifje met Openstaande/Afgesloten zaken. Ik maak hier een nieuwe user story voor.

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/8d98b21c-ffd3-4c66-bb11-e3dfd8adf27b)

**Comment by HilbrandHurtak** [comment]
Userstory #2105 voor verbetering zoekresultaat toegevoegd
