### ISSUE TITLE
Zoeken aanvrager gesloten dossier

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#947]
#Zoeken aanvrager gesloten dossier<br/>**Als** Medewerker informatiebeheer<br/>**wil ik** een gesloten zaakdossier kunnen vinden op naam van de aanvrager,<br/>**zodat** ik binnengekomen post kan toevoegen. .<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by HilbrandHurtak** [comment]
Zoeken op zaken van 1 persoon gaf een overzicht met alle gevonden zaken. Via filtering op status kun je een verschil maken tussen de lopende en afgesloten zaken. Dit zou misschien nog wat eenvoudiger (einddatum gevuld) of een schuifje met Openstaande/Afgesloten zaken. Ik maak hier een nieuwe user story voor.

![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/8d98b21c-ffd3-4c66-bb11-e3dfd8adf27b)

Userstory #2105 voor verbetering zoekresultaat is aangemaakt
