### ISSUE TITLE
Zoeken lopend dossier zaaknummer

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#948]
#Zoeken lopend dossier zaaknummer<br/>**Als** Medewerker informatiebeheer<br/>**wil ik** een lopend zaakdossier kunnen vinden op zaaknummer,<br/>**zodat** ik binnengekomen post kan toevoegen. .<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement

- Een zaak kan gezocht worden op het volledige zaaknummer, bijvoorbeeld ZAAK-2022-0000001028
- Daarnaast is het mogelijk om de * wildcard te gebruiken. De zoekopdracht *1028 vindt ook ZAAK-2022-0000001028

**Comment by HilbrandHurtak** [comment]
Getest. Test OK
# 1822 Facetresultaat werkt
#1839 Openen in nieuw tabblad via oogje werkt
# 948 Zoeken op zaaknummer of gedeelte werkt. Tevens ruime zoekmogelijkheden op andere items (ook met *)
