### ISSUE TITLE
Zoeken gesloten dossier zaaknummer

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#949]
#Zoeken gesloten dossier zaaknummer<br/>**Als** Medewerker informatiebeheer<br/>**wil ik** een afgesloten zaakdossier kunnen vinden op zaaknummer,<br/>**zodat** ik binnengekomen post kan toevoegen. .<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement

- Een zaak kan gezocht worden op het volledige zaaknummer, bijvoorbeeld ZAAK-2022-0000001028
- Daarnaast is het mogelijk om de * wildcard te gebruiken. De zoekopdracht *1028 vindt ook ZAAK-2022-0000001028

**Comment by HilbrandHurtak** [comment]
Filters bij gevonden zaken geven de mogelijkheid om ook op afgesloten zaken te zoeken
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/dcb560d3-aa19-433f-88ce-8af597ebbff4)
Zoeken op delen van een zaaknummer werkt zoals door Roy beschreven

Test OK
