### ISSUE TITLE
Zoeken op adres

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#950]
#Zoeken op adres<br/>**Als** Medewerker informatiebeheer<br/>**wil ik** een zaakdossier kunnen vinden op adres,<br/>**zodat** ik binnengekomen post kan toevoegen. .<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by robertverboom** [comment]
Zoeken op locatie van de zaak of locatie van het BAG object?

**Comment by PaskalKiers** [comment]
Als je met locatie van de zaak bedoeld het adres dat gerelateerd is aan de melder en daarmee aan de zaak;  dan die in ieder geval.   Die zal bij normaal geschreven brieven in ieder geval ook opgegeven worden.

Als er een bag locatie is toegevoegd, omdat dat relevant is voor het zaaktype, dan wil je daar ook op kunnen zoeken, maar dat lijkt me een andere user story.

Of wordt de zaaklocatie als bag locatie opgeslagen? Blijkbaar niet, anders vraag je het niet. 


Ik zal het nog niet ingewikkelder maken, want wat als een bewindvoerder ook geregistreerd is in de zaak en de brief op het briefpapier van de bewindvoerder is.  Of vice versa.  zijn denk ik ook andere stories.   In een aanzienlijk deel zal in de brief ook een referentie naar het zaaknummer staan.

**Comment by Snijhuis** [comment]
**WG Refinement**
1. Zoeken op persoon kan. Via de persoon zijn dan zaken te vinden. Eerst oplossing in #946
2. BAG moet nog verder uitgewerkt worden. Nu alleen adres als BAG-object te koppelen. Specifiek zoeken zaken via BAG moet een story voor gemaakt worden.
3. Zoeken zaken op locatie: verder uitwerken in story.

Eerst oplossing #946 afwachten

**Comment by Snijhuis** [comment]
Voor deze story maken we nieuwe stories aan. 
1. voor BAG-objecten zoeken (via algemeen zoekvenster) en daaraan de gekoppelde zaken tonen
2. voor locatie zoeken (via algemeen zoekvenster) en daaraan de gekoppelde zaken tonen

Daarna verder kijken naar
1.  BAG-objecten koppelen aan zaak. Welke objecttypen, welke zoekvelden, etc
2. BAG-object als initiator voor het starten van de zaak.

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd en word via andere issues verder uitgewerkt, zie oa #2248
