### ISSUE TITLE
Zoeken op zaaknummer

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#951]
#Zoeken op zaaknummer<br/>**Als** Medewerker informatiebeheer<br/>**wil ik** kunnen vinden op zaken op zaaknummer,<br/>**zodat** ik binnengekomen post kan toevoegen. .<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by HilbrandHurtak** [comment]
Zoeken op zaaknummer (gedeelte) is mogelijk: Binnen zoekresultaat diverse verfijningen mogelijk. Voor nu voldoende functionaliteit
