### ISSUE TITLE
zoeken meta informatie

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#952]
#zoeken meta informatie<br/>**Als** Medewerker informatiebeheer<br/>**wil ik** gericht kunnen zoeken op meta informatie van de zaak,<br/>**zodat** ik sneller het gezochte kan vinden.<br/><br/>**Acceptatiecriteria** <br/>Ik kan zoeken op betrokkene, startdatum, zaaknummer, dienst (zaaktype), onderwerp, trefwoorden, locatie<BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd.
