### ISSUE TITLE
zoeken tonen resultaten aanvrager

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#954]
#zoeken tonen resultaten behandelaar<br/>**Als** Behandelaar<br/>**wil ik** dat zoekresultaten op een overzichtelijke wijze worden getoond,<br/>**zodat** ik een zo groot mogelijke kans heb om snel  te vinden wat ik zoek..<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by HilbrandHurtak** [comment]
Zoeken op aanvrager met wildcard geeft het volgende resultaat:
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/f0f35190-9528-4e35-a648-15f681c59abf)

Na selectie van de juiste persoon wordt een overzicht getoond van de gerelateerd zaken:
![image.png](https://images.zenhubusercontent.com/621fbac8fb54e5427009eefc/7e288a60-1db2-4ccb-9546-7c600469f0d8)

**Comment by HilbrandHurtak** [comment]
Als de persoon een andere rol (Betrokkene) heeft(dus niet de initiator) worden deze zaken niet in het overzicht weergegeven. Hiervoor is user story #944 reeds aangemaakt
