### ISSUE TITLE
Zoeken snel resultaat

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#955]
#Zoeken snel resultaat<br/>**Als** medewerker<br/>**wil ik** dat de eerste zoekresultaten binnen 3 seconden op mijn scherm staan,<br/>**zodat** ik niet zit te wachten op resultaten..<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by VictorTielenius** [comment]
Zoekresultaten komt snel op scherm
