### ISSUE TITLE
Zoeken terugkoppeling verloop

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#956]
#Zoeken terugkoppeling verloop<br/>**Als** medewerker<br/>**wil ik** duidelijke terugkoppeling over de duur van de zoekopdracht,<br/>**zodat** ik weet wanneer de zoekopdracht klaar is.<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by HilbrandHurtak** [comment]
Is op dit moment moeilijk te testen. Er zit een beperkte dataset in als het gaat om personen en bedrijven. Het zoeken op zaken en de verdere uitfiltering gaat supersnel(zitten in de zandbak maar 100 zaken). Je krijgt netjes een melding dat je zoekopdracht wordt uitgevoerd maar geen indicatie hoe lang dat gaat duren of heeft geduurd. Mijn voorstel is om dit bij de algemene performance testen mee te nemen indien
