### ISSUE TITLE
Zoeken op zaakgegegevens

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#957]
#Zoeken op zaakgegegevens<br/>**Als** medewerker<br/>**wil ik** een zaak kunnen vinden op basis van zaakgegevens,<br/>**zodat** ik mijn werk kan uitvoeren.<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd.
