### ISSUE TITLE
zoeken op zaaktype

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#959]
#zoeken op zaaktype<br/>**Als** zaakbehandelaar<br/>**wil ik** zaken kunnen vinden op basis van zaaktype,<br/>**zodat** ik zo snel mogelijk kan vinden wat ik zoek.<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd.
