### ISSUE TITLE
zoeken eenduidige presenteren resultaat

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#960]
<br/>**Als** medewerker<br/>**wil ik** dat de presentatie van zoekresultaten eenduidig is binnen de gebruikersinterface,<br/>**zodat** er ik  weet wat ik kan verwachten als ik een zoekfunctie gebruik.<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by VictorTielenius** [comment]
Wat is de volgorde van de getoomde zoekresultaten? Nieuwste zaak bovenaan zou wenselijk zijn.

**Comment by PaskalKiers** [comment]
Die heb ik niet gedefinieerd, want de essentue was eenduidige presentatie. Zodat het intuitief werkt en je niet de ene keer deze opties krijgt en de andere keer andere (of de ene keer resultaten krijgt voor trefwoord en de andere keer voor trefwoord*)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd. Deze kan verder beoordeeld worden via gebruikersvriendelijkstesten
