### ISSUE TITLE
zoeken presenteren met juiste context

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#961]
#zoeken presenteren met juiste context<br/>**Als** Medewerker <br/>**wil ik** dat de presentatie van zoekresultaten het best past bij de zoekvraag,<br/>**zodat** ik zoveel mogelijk relevante informatie krijg, ongeacht de zoekvraag/context.<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd. Deze kan verder beoordeeld worden tijdens de gebruikersvriendelijkheidstesten.
