### ISSUE TITLE
zoeken obv alle objecttypen

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#962]
#zoeken obv alle objecttypen<br/>**Als** medewerker <br/>**wil ik** dat ik dat kan zoeken op de inhoud van alle objecttypen die relevant zijn voor de zaaktypen waar ik voor geautoriseerd ben,<br/>**zodat** ik een zo groot mogelijke kans heb om snel  te vinden wat ik zoek..<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd. Deze kan verder beoordeeld worden tijdens de gebruikersvriendelijkheidstesten.
