### ISSUE TITLE
zoeken op inhoud documenten

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#963]
#zoeken op inhoud documenten<br/>**Als** Medewerker <br/>**wil ik** wil ik door de inhoud van documenten kunnen zoeken,<br/>**zodat** ik een zo groot mogelijke kans heb om snel  te vinden wat ik zoek..<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Dit heeft grote impact op performance en daarnaast behoeft dit nog veel uitzoekwerk voor wat wel en niet mag en kan. Zoeken in het algemeen is ook opgenomen in de backlog van PodiumD.
