### ISSUE TITLE
zoeken filteren zoekresultaten op inhoud

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#964]
#zoeken filteren zoekresultaten op inhoud<br/>**Als** Medewerker <br/>**wil ik** wil ik op zaakinhoud kunnen filteren op de zoekresultaten,<br/>**zodat** ik een zo groot mogelijke kans heb om snel  te vinden wat ik zoek..<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd.
