### ISSUE TITLE
Zoeken op relatie informatieobjecten.

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#965]
#Zoeken op relatie informatieobjecten.<br/>**Als** medewerker<br/>**wil ik** wil ik kunnen zien welke informatieobjecten gerelateerd zijn aan het object dat ik op dat moment bekijk,<br/>**zodat** .<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Voor zaken geldt dat de informatieobjecten te zien zijn door het openen van de zaak vanuit de zoekresultaten.
