### ISSUE TITLE
Zoeken via relaties persoon

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#966]
#Zoeken via relaties persoon<br/>**Als** medewerker<br/>**wil ik** wil ik kunnen zien welke personen gerelateerd zijn aan mijn zaak,<br/>**zodat** ik een zo groot mogelijke kans heb om snel  te vinden wat ik zoek..<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Bij het zoeken naar zaken kan niet in de zoekresultaten getoond worden welk personen hier als initiatitor of betrokkene aan gerelateerd is. Er kan wel gezocht worden naar personen en van daaruit zoeken naar zaken waar die persoon aan gerelateerd is.
