### ISSUE TITLE
zoeken via relaties zaak

### ISSUE THREAD

**Issue by PaskalKiers** [NL-AMS-LOCGOV/zaakafhandelcomponent#967]
#zoeken via relaties zaak<br/>**Als** medewerker<br/>**wil ik** wil ik kunnen zien welke zaken gerelateerd zijn aan de  persoon(NP/RP) die ik bekijk,<br/>**zodat** ik een zo groot mogelijke kans heb om snel  te vinden wat ik zoek..<br/><br/>**Acceptatiecriteria** <br/><BR/> <br/>**Opmerkingen** <br/><BR/><BR/>**Verwijzingen:<br/> [Dimpact Thema](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/7) <br/>[Dimpact Epic](https://github.com/Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening/issues/42)

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB
Story is gerealiseerd.
