### ISSUE TITLE
Intake afronden - Aanpassen Zaak menu en dialoog

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#989]

**Comment by andyverberne** [comment]
- [ ] Gebruiker kiest in het dialoog ' Ontvankelijk' of 'Niet ontvankelijk'
- [ ] Als gebruiker kiest voor Niet ontvankelijk dan moet het reden veld ingevuld worden
- [ ] In zaakmenu wordt header 'Actie uitvoeren' verwijderd. De acties 'Intake afronden' en 'zaak afhandelen' komen voortaan bovenin het menu te staan, net boven 'Zaak afbreken'

**Comment by andyverberne** [comment]
Zie ToDo in zaak-view-component.ts

**Comment by RoyBuis** [comment]
test ok
