### ISSUE TITLE
Historie afronden op zaken/documenten

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#99]
Historie: 

- [ ] Status en resultaat worden niet meegenomen in oude waarde
- [x] Tijd als pop over instellen?
- [x] zaak moet document worden in document historie
- [x] 'Door wie' wordt niet gevuld

**Comment by ronniekoopmans-atos** [comment]
het is niet mogelijk om een status te updaten, alleen te zetten
