### ISSUE TITLE
Intake afronden - Wijzigen zaakafhandelparameters

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#990]

**Comment by andyverberne** [comment]
- [ ] In zaakafhandelparameters komt 'Actiegegevens' te vervallen en wordt vervangen door twee hardgecodeerde waarden: 'Intake afronden gegevens' en 'Zaak afhandelen gegevens'
- [ ] In zaakafhandelparameters wordt 'Zaakbeeindig gegevens' naam gewijzigd in 'Zaakafbreken gegevens'
- [ ] Tabel 'User event listener parameters' opruimen en zaakafhandelparameters uitbreiden

**Comment by andyverberne** [comment]
Zie ToDo in PlanItemRESTService

**Comment by RoyBuis** [comment]
test ok
