### ISSUE TITLE
ACCEPTATIE BUG: Uitlog functie bij meerdere vensters open

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#994]
**Gebruikersrol:** Behandelaar
**Device:** Laptop
**OS:** Windows
**Browser:** In Edge Chromium + Mozilla Firefox getest. 
**Versie:**

**Issuenummer**
_Welk issue was je aan het testen? Met een # voor het nummer wordt het een link_
#4

**Beschrijf de bug**
Als gebruiker meerdere vensters open heeft worden allen uitgelogd: NOK, Uitgelogd in 1 venster, andere lijkt nog ingelogd, maar na poging om werkvoorraad in 2e scherm te openen: "De server heeft code 0 geretourneerd". Bij opnieuw inloggen in zelfde venster hierna "Bad Request". In nieuw tabblad wel in te loggen. Op oude venster waar je ingelogd was en had uitgelogd dan opnieuw inloggen geeft "You are already logged in." , en opent ZAC niet.

**Te reproduceren:**
_Stappen om het gedrag te reproduceren_
Zie hierboven

**Verwacht gedrag**
Op alle vensters / pagina's te zijn uitgelogd'.

**Daadwerkelijk gedrag**
_Een duidelijke en beknopte beschrijving van wat er daadwerkelijk gebeurde_

**Screenshots**
_Er is tenminste 1 screenshot als bijlage toegevoegd_

**Foutmelding/Log tekst**
"De server heeft code 0 geretourneerd" + "Bad Request"

**Aanvullende informatie**
nvt

**Comment by VictorTielenius** [comment]
![Logout fout.png](https://images.zenhubusercontent.com/62455493ca4f57573cfa2501/f5f74ab6-a99b-44e2-ae17-37abc00fc146)

**Comment by andyverberne** [comment]
Het gedrag van keycloak wanneer je probeert in te loggen terwijl je al ingelogd bent is niet te beinvloeden.

**Comment by robertverboom** [comment]
er zijn twee bugs beschreven. issue met uitloggen op verschillende tabbladen is gefixt. Opnieuw inloggen met verschillende schermen kan niet beïnvloedt worden

**Comment by VictorTielenius** [comment]
Getest en akkoord
