### ISSUE TITLE
6. Vanuit zaak een deelzaak starten

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#996]
***Als*** 
Behandelaar en/of postmedewerker

***Wil ik*** 
Vanuit een zaak een Deelzaak starten. Hiermee wordt de relatie tussen de 2 zaken: hoofdzaak / deelzaak.

***Zodat*** 
Er 1 of meerdere deelzaken aangemaakt kunnen worden vanuit een zaak, waar een proces uitgevoerd kan worden wat een onderdeel in van de hoofdzaak. De deelzaak is dan van een ander zaaktype, met (evt.) andere behandelaar welke eerst afgehandeld dienen te worden voordat de hoofdzaak afgehandeld kan worden.

### Acceptance criteria:
Vanuit een Zaak op makkelijke manier een deelzaak kunnen starten. 
Relatie (hoofdzaak / deelzaak) wordt automatisch gelegd.
Vanuit zaak moet je eenvoudig naar de gerelateerde hoofdzaak / deelzaak kunnen navigeren.
Documenten van de gerelateerde zaak zijn te zien in beide zaken, evt. met optie tonen documenten gerelateerde zaak.
Vernietiging: Pas als alle deelzaken zijn vernietigd mag de hoofdzaak zich aanbieden voor vernietiging

***
### Prioriteit
- Must haves

***
996
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
In user story #895 is het kunnen koppelen van openstaande zaken als hoofd- en deelzaak opgeleverd. Deze functionaliteit maakt het ook mogelijk om vanuit een zaak een deelzaak te starten. Dit kan door de hoofdzaak op het klembord te zetten, vervolgens een nieuwe zaak te starten via de 'Aanmaken zaak' knop en daarna in de nieuw aangemaakte zaak vanaf het klembord de koppeling te maken.  
***Belangrijkste functionaliteiten:***
- Gebruiker kan met de actie [Zaak koppelen] een zaak op het klembord plaatsen
- Gebruiker kan in een nieuw aangemaakte zaak waarmee de koppeling gelegd moet worden vanuit het klembord te zaken aan elkaar koppelen en de soort relatie tussen de zaken bepalen
- Het koppelen van zaken als hoofd- en deelzaak wordt als wijziging van hoofdzaak in de historie van de DEELzaak vastgelegd

Zie ook User Storie 8.2.14 Taak-Starten nieuwe zaak (https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/488)

**Comment by VictorTielenius** [comment]
![Uploading Hoofd Deel Vervolgzaak bij inkoop en aanbesteding.png…]()

**Comment by VictorTielenius** [comment]
<img width="530" alt="Hoofd Deel Vervolgzaak bij inkoop en aanbesteding" src="https://user-images.githubusercontent.com/97599511/169303815-75b7c79a-22fd-4fe0-8a88-6601e65fd289.png">

**Comment by RoyBuis** [comment]
### Refinement 23-5
Op de productbacklog staat nu story #895 waarmee het mogelijk wordt om de hoofd-deelzaak relatie te leggen vanuit bestaande zaken. Na het opleveren hiervan kan deze kan deze story nogmaals beoordeeld worden

**Comment by CommonGroundGroningen** [comment]
**Gebruiker kan met de actie [Zaak koppelen] een zaak op het klembord plaatsen**
Test OK
**Gebruiker kan in een nieuw aangemaakte zaak waarmee de koppeling gelegd moet worden vanuit het klembord te zaken aan elkaar koppelen en de soort relatie tussen de zaken bepalen**
Test OK
**Het koppelen van zaken als hoofd- en deelzaak wordt als wijziging van hoofdzaak in de historie van de DEELzaak vastgelegd**
Test OK
