### ISSUE TITLE
6. Vanuit zaak een vervolgzaak starten

### ISSUE THREAD

**Issue by VictorTielenius** [NL-AMS-LOCGOV/zaakafhandelcomponent#998]
***Als*** 
Behandelaar en/of postmedewerker

***Wil ik*** 
Vanuit een zaak een vervolgzaak starten. Hiermee wordt de relatie tussen de 2 zaken: voorafgaande zaak / vervolgzaak.

***Zodat*** 
Er 1 of meerdere vervolgzaken aangemaakt kunnen worden vanuit een zaak, waar een proces uitgevoerd kan worden wat een vervolg in van de eerdere zaak. De vervolgzaak is dan (evt.) van een ander zaaktype, met (evt.) andere behandelaar.
Dit moet vanuit een lopende zaak en vanuit een afgehandeld zaak mogelijk moeten zijn. Ook moet deze relatie bij 2 bestaande zaken gelegd moeten kunnen worden
***

### Acceptance criteria:
Vanuit een Zaak op makkelijke manier een vervolgzaak kunnen starten.
Relatie (voorafgaande zaak / vervolgzaak) wordt automatisch gelegd bij aanmaken vanuit een zaak.
Vanuit zaak moet je eenvoudig naar de voorafgaande zaak / vervolgzaak kunnen navigeren.
Documenten van de gerelateerde (=voorafgaande zaak / vervolgzaak) zaak zijn te zien in beide zaken, evt. met optie tonen documenten gerelateerde zaak.
Vernietiging: Pas als (alle) vervolgzaken zijn vernietigd mag de voorafgaande zaak zich aanbieden voor vernietiging.

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_
Vervolgzaak kunnen aanmaken vanuit een zaak en rekening houden met de acceptatie criteria.

***Belangrijkste functionaliteiten:***
- 
-
Zie ook User Storie 8.2.14 Taak-Starten nieuwe zaak (https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/488)

**Comment by VictorTielenius** [comment]
<img width="530" alt="Hoofd Deel Vervolgzaak bij inkoop en aanbesteding" src="https://user-images.githubusercontent.com/97599511/169303918-874d1ab5-aaea-4c91-95c6-d19ee687b486.png">

**Comment by Snijhuis** [comment]
@VictorTielenius Ik lees online dit:
"Een zaak is enkel een vervolgzaak als deze enkel gestart kon worden op basis van het afsluiten van de initiator zaak.
Bijvoorbeeld: Een subsidievaststelling kan enkel 'volgen' op een subsidieverlening. Deze kan niet gestart worden tijdens de verlening en is geen onderdeel van het verleningsproces."

Moeten wij deze logica ook hanteren?

**Comment by VictorTielenius** [comment]
uit: ZAAKGERICHT WERKEN BETERE INFORMATIEVOORZIENING EN BETERE DIENSTVERLENING BIJ DE OVERHEID CORNÉ DEKKER
We maken onderscheid tussen subzaken, die gestart en afgehandeld worden tijdens een hoofdproces, en vervolgzaken, die pas gestart worden na afhandeling van een hoofdzaak. Een advies van de afdeling Milieu over een bouwvergunning is een voorbeeld van een subzaak. Een inspectie, die start na het verlenen van een bouwvergunning, is een voorbeeld van een vervolgzaak. Een vervolgzaak kan ook verder in de toekomst liggen. Na de afhandeling van een aanvraag subsidie, zou men direct kunnen vastleggen dat een jaar later een zaak moet worden gestart om de besteding van de subsidie te controleren. Dit noemen we een agenderingszaak. De kracht van een goed zaaksysteem zit in het feit dat bij een zaaktype heel eenvoudig sub- en vervolgzaaktypen kunnen worden geconfigureerd (zonder hulp van de leverancier)!

**Comment by robertverboom** [comment]
ivm duplicate sluit ik dit issue: #2197 #90 #2207
